### ISSUE TITLE
Unexpected character ' ' while parsing IRI

### ISSUE THREAD

**Issue by JeroenSteen** [dgraph-io/dgraph#1002]
I installed Dgraph and converted a N-Triple file to RDF (with https://sourceforge.net/projects/rdfconvert/) , so that I can import it in Dgraph. I runned `dgraphloader --r AATOut_Full.rdf.gz`, but then I get this error:
```

Dgraph version   : v0.7.7
Commit SHA-1     : 699e7e7
Commit timestamp : 2017-06-01 20:45:46 +1000
Branch           : HEAD

Processing AATOut_Full.rdf.gz
2017/06/01 19:34:27 main.go:135: Error while parsing RDF: Unexpected character ' ' while parsing IRI, on line:1 <?xml version="1.0" encoding="UTF-8"?>
```

Why do I get this error, how can it be fixed?

**Comment by janardhan1993** [comment]
@JeroenSteen Dgraph takes  N-Triple's as input. I think may be you converted it to rdf xml and tried to import. RDF N-triple would work directly with dgraph. Can you please paste the raw data and data after transformation.

**Comment by JeroenSteen** [comment]
Here is the beginning (When I run head) of the raw data (N-Triple):

```
<http://vocab.getty.edu/aat/300250904> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.getty.edu/ontology#Subject> .
<http://vocab.getty.edu/aat/300250904> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> .
<http://vocab.getty.edu/aat/300250904> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.getty.edu/ontology#Concept> .
<http://vocab.getty.edu/aat/300250904> <http://www.w3.org/2000/01/rdf-schema#label> "storytelling"@en .
<http://vocab.getty.edu/aat/300250904> <http://www.w3.org/2000/01/rdf-schema#label> "story-telling"@en .
<http://vocab.getty.edu/aat/300250904> <http://www.w3.org/2000/01/rdf-schema#label> "story telling"@en .
<http://vocab.getty.edu/aat/300250904> <http://www.w3.org/2000/01/rdf-schema#label> "telling of stories"@en .
<http://vocab.getty.edu/aat/300250904> <http://www.w3.org/2000/01/rdf-schema#label> "telling, story"@en .
<http://vocab.getty.edu/aat/300250904> <http://www.w3.org/2000/01/rdf-schema#label> "\u8AAA\u66F8"@zh-hant .
<http://vocab.getty.edu/aat/300250904> <http://www.w3.org/2000/01/rdf-schema#label> "\u8B1B\u6545\u4E8B"@zh-hant .
```

After the conversion, the head beginning looks like:

```
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
	xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">

<rdf:Description rdf:about="http://vocab.getty.edu/aat/300250904">
	<rdf:type rdf:resource="http://vocab.getty.edu/ontology#Subject"/>
	<rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
	<rdf:type rdf:resource="http://vocab.getty.edu/ontology#Concept"/>
	<label xmlns="http://www.w3.org/2000/01/rdf-schema#" xml:lang="en">storytelling</label>
	<label xmlns="http://www.w3.org/2000/01/rdf-schema#" xml:lang="en">story-telling</label>

```

I see that I can also import nt directly with Dgraph, but then I get this error:
`Error while parsing RDF: Unrecognized rdf type http://www.w3.org/2001/XMLSchema#positiveInteger`.

The positiveInteger type is not supported yet, I think.

**Comment by janardhan1993** [comment]
@JeroenSteen yeah postiveinteger is not supported, for time being you can preprocess the data and convert it integer. You can see list of supported types at https://docs.dgraph.io/v0.7.7/query-language/#supported.
If you feel that we should be supporting some type please feel free to raise the issue.

**Comment by ashwin95r** [comment]
For now, we can just map this to int. Later, if this is useful, we could have a uint type.

**Comment by janardhan1993** [comment]
mapped positive integer to int type for now
