### ISSUE TITLE
Filter Posting List by ID

### ISSUE THREAD

**Issue by calummoore** [dgraph-io/dgraph#1004]
As per the discuss thread ([Filter Posting List by ID](https://discuss.dgraph.io/t/filter-posting-list-by-id/1529)), it would be really useful to be able to filter a Posting List by ID.

E.g. in the friends node below.
```
me (id: <uid>) {
    name
    friends (id: <uid>) {
        name
    }
}
```
As suggested by @manishrjain, it might be a good idea to use a fn to wrap the `<uid>` and to use filter instead of `(id: <uid>)`.

**Comment by pawanrawal** [comment]
This has been merged to master.
