### ISSUE TITLE
add expand(_forward_) and expand(_reverse_)

### ISSUE THREAD

**Issue by prange** [dgraph-io/dgraph#1006]
the expand function is really useful for exploring data. Alas, the _all_ keyword does not expand reverse predicates which often is useful for exploring your graph.
Adding _forward_ and _reverse_ keywords could enable this. The _all_ keyword could then yield both predicates and reverse predicates.

**Comment by manishrjain** [comment]
Forgot @abhishekgahlot  was working on it.

**Comment by abhishekgahlot** [comment]
@manishrjain  I am currently working on this. Just an update.

**Comment by pawanrawal** [comment]
A related issue is that `_predicate_` should also return reverse predicates.

**Comment by peterstace** [comment]
I've been making changes related to `expand(_all_)` already, so I'll take a look at this.

**Comment by peterstace** [comment]
PR: https://github.com/dgraph-io/dgraph/pull/1817

**Comment by peterstace** [comment]
A change to add reverse edges to expand(_all_) is now in master at 579121a.
