### ISSUE TITLE
Delete mutation does not delete incoming edges

### ISSUE THREAD

**Issue by sungwoncho** [dgraph-io/dgraph#1008]
version: 0.7.7

---

**Reproduction**

1. Set up the following data

```
mutation {
  schema {
    Has: uid @reverse .
  }
}
```

```
mutation {
  set {
    <fooz> <Has> <barz> .
  }
}
```

2. Delete all edges of `<barz>`

```
mutation {
  delete {
    <barz> * * .
  }
}
```

3. The edge from `fooz` to `barz` still remains.

```
{
  me(id: barz) {
    ~Has {
      _uid_
    }
  }
}
```

**Expected**

All derived edges should be deleted, as specified in https://docs.dgraph.io/v0.7.7/query-language/#delete

**Thoughts**

When doing `S * *` delete mutation, it is handy to delete all incoming edges. If not, frontend relying on Dgraph result is prone to breaking because a tree in the result might be pointing to nodes with incomplete data.

e.g. 

if `<POST> --Comment--> <COMMENT>`, and we delete the comment by

```
mutation {
  delete {
    <commentXID> * * .
  }
}
```

A post might still have an edge `<Comment>` to `<commentXID>`

**Comment by pawanrawal** [comment]
In this case you could do
```
mutation {
  delete {
    <postID> <comment> <commentXID> .
    <commentXID> * * .
  }
}
```

**Comment by sungwoncho** [comment]
Thanks. But let's still keep the discussion open about deleting incoming edges when doing `S * *` delete mutation

**Comment by ashwin95r** [comment]
This would add unnecessary complexity in Dgraph to achieve. So, better to do the deletion from the UI.
