### ISSUE TITLE
`count` is present in the result even when node does not exist

### ISSUE THREAD

**Issue by sungwoncho** [dgraph-io/dgraph#1009]
version: 0.7.7

---

**Reproduction**

1. Query a random node that does not exist, with `count`.

```
{
  me(id: somethingrandom) {
      RandomField
      RandomCount: count(What)
  }
}
```

2. `RandomField` is omitted from the result as it does not exist. But `RandomCount` is always present.

**Problem**

A frontend developer consuming result from Dgraph might find this unexpected. If the node with id `somethingrandom` does not exist, then the result should be empty. This behavior causes result to be incomplete, causing problems with rendering the frontend.

**Comment by pawanrawal** [comment]
This issue is not present on master and should be fixed in the next release because we don't do fingerprinting of `xid` anymore. So if a random node doesn't exist, we don't process its children.
