### ISSUE TITLE
Clarify language lists semantics

### ISSUE THREAD

**Issue by tzdybal** [dgraph-io/dgraph#1010]
Language lists can be a counter intuitive/confusing, because of the "fallback" logic employed when given language(s) are absent. For example there is no way to select a value only in selected language(s), without fallback.

Proposed change is to add `.` as a special value in language list, denoting `look for default value (no language tag) and then for value in any language`.

New rules will be following:
- name   => Look for default, then return nothing.
- name@. => Look for default, then any language.
- name@en => Look for en, then return nothing.
- name@en:. => Look for en, then default, then any language.
- name@en:pl => Look for en, then pl, then return nothing.
- name@en:pl:. => Look for en, then pl, then default, then any language.

**Comment by MichaelJCompton** [comment]
@tzdybal this makes lots of sense.  Fixes the problems I was having in #994.

I'm wondering though if the semantics for `name@en` should just be to check in en - because there is no way in the proposed semantics to check if there is a string tagged with en.

**Comment by tzdybal** [comment]
@MichaelJCompton thanks for suggestion. Comment updated.
