### ISSUE TITLE
A valid query with `count` and `var` returns "Invalid mention of brackets"

### ISSUE THREAD

**Issue by sungwoncho** [dgraph-io/dgraph#1011]
version: 0.7.7

---

*Reproduction*

1. Run the following valid query

```
{
  user as var(id: u3)

  me(id: p1) {
    Upvote {
       u as Author @filter(var(user))
    }
      
    UserUpvoteCount: count(var(u))
  }
}
```

It fails and returns an error `Invalid mention of brackets`

The following query runs:

```
{
  user as var(id: u3)

  me(id: p1) {
    Upvote {
       Author @filter(var(user))
    }
  }
}
```

**Comment by pawanrawal** [comment]
I think we can support count with `var`. Working on supporting it.

**Comment by ashwin95r** [comment]
I think the right way to write this query would be:
```
{
  user as var(id: u3)

  me(id: p1) {
    Upvote {
       u as count(Author @filter(var(user)))
    }
    UserUpvoteCount: sum(var(u))
  }
}
```
Though the error message should be made better. What do you think @mrjn @sungwoncho .

**Comment by manishrjain** [comment]
Then you lose out on Author information, it doesn't get returned.

**Comment by ashwin95r** [comment]
We can still retrieve the author information.
```
{
  user as var(id: u3)

  me(id: p1) {
    Upvote {
       u as count(Author @filter(var(user)))
       Author @filter(var(user))
    }
    UserUpvoteCount: sum(var(u))
  }
}
```

**Comment by ashwin95r** [comment]
We don't allow count with var as it is ambiguous in certain cases. The same functionality can be achieved cneatly with sum().
