### ISSUE TITLE
Documentation for EC2 and GCE

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#1015]
Add documentation to show how to run Dgraph in Amazon EC2 or GCE.

**Comment by campoy** [comment]
Hey @MichaelJCompton,

I'm afraid this issue is not relevant anymore.
I checked on the docs and found information about how to run Dgraph on EC2  and GCP
https://docs.dgraph.io/deploy

Do you think it's enough or would you add other information? If it looks good, please close this issue.
