### ISSUE TITLE
Bind to ip address passed as part of `my` flag and not localhost when bindall is false. 

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1025]
Currently, even if a `--my` flag is passed, we bind to `localhost` if `bindall` is false. We should bind to the ip address given as part of the `--my` flag. Also `--my` flag has ip and a port (which is the same as workerport). I think we don't need port in the `--my` flag.  

What are your thoughts @janardhan1993?

**Comment by ashwin95r** [comment]
Maybe just print out a warning.

**Comment by janardhan1993** [comment]
we print a warning now, if user specifies --my flag and doesn't specify bindall
