### ISSUE TITLE
Add text to runnable in docs

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#1030]
Currently runnable is offset from surrounding text.  Would make examples clearer if text explaining the example were marked up with the runnable - for example a box surrounding both.

See branch docs-refactor-mjc, which has

Query Example: .... explanatory text....

...then runnable box...

bundle these up together.

**Comment by sungwoncho** [comment]
For maintainability and possible code sharing, I think runnable component should be standalone without extra stuff like explanatory text.

Would it be clearer to the readers if we used shortcode? (example below)

![graphs_ _a_tour_of_dgraph](https://user-images.githubusercontent.com/8265228/27020270-fbe456e0-4f82-11e7-8b3f-94dcebbe497f.png)

**Comment by manishrjain** [comment]
I think the explanation of the query and the query itself, belong together. runnable should reflect that -- also it can then format the query explanation a bit nicer. Right now, it's different and away, it should be closer. I don't think Note template cuts it.

**Comment by manishrjain** [comment]
This isn't important. Closing this issue.
