### ISSUE TITLE
Try to expose http via grpc

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#1032]
https://cloud.google.com/endpoints/docs/transcoding

If we can just have one internal endpoint, it would avoid code duplication.

**Comment by tzdybal** [comment]
https://github.com/grpc/grpc.github.io/wiki/Mapping - more information on mapping

**Comment by tzdybal** [comment]
Even more resources:
http://www.grpc.io/blog/coreos (source code: https://github.com/philips/grpc-gateway-example)
https://github.com/grpc-ecosystem/grpc-gateway

**Comment by tzdybal** [comment]
Unfortunately it is not possible to set this without TLS: https://github.com/philips/grpc-gateway-example/issues/11
