### ISSUE TITLE
[Question] How to store a list of values?

### ISSUE THREAD

**Issue by AlexanderChen1989** [dgraph-io/dgraph#1034]
Give a node with a position key with value (x, y, z), How can I store this in Dgraph?
The order of value in list is important.

**Comment by manishrjain** [comment]
One way you can store this is just storing it as a single value, i.e. marshal it to string or bytes, and just store them as such. That way order would be maintained.

This does mean that you can't append to the list, you'll have to re-set the entire list every mutation. That might be OK though.

**Comment by AlexanderChen1989** [comment]
@manishrjain If I store the relations of nodes with same key, will the order be preserved?

**Comment by AlexanderChen1989** [comment]
@manishrjain or can I sort edges by facts?

**Comment by manishrjain** [comment]
You can retrieve the facets for all these edges, and then sort them. We haven't built the sorting in Dgraph because there's no added advantage of doing it within Dgraph.

**Comment by AlexanderChen1989** [comment]
@manishrjain thanks
