### ISSUE TITLE
Allofterms matches extra terms

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1046]
```
	{
		me(func: allofterms(email, "michonne@gmail.com")) {
			name
			email
		}
	}
```

Returns
```
{"me":[{"email":"michonne@gmail.com","name":"Michonne"},{"email":"michonne+sub@gmail.com","name":"Rick Grimes"}]}
```

**Comment by pawanrawal** [comment]
@willcj33 Our term tokenizer considers `+`, `@` to be delimiters and tokenizes around them. So in the above example, `michonne`, `sub` and `gmail.com` are the tokens. I would suggest using an `exact` or `hash` tokenizer if you wanted to do a match on email.

**Comment by manishrjain** [comment]
This isn't a bug. Both the results have all the right terms in them.
