### ISSUE TITLE
-version doesn't report version info

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#1064]
after fresh build `~/go/src/github.com/dgraph-io/dgraph/cmd/dgraph/dgraph -version`

reports

```
Copyright 2017 Dgraph Labs, Inc.

Licensed under AGPLv3.
For Dgraph official documentation, visit https://docs.dgraph.io.
For discussions about Dgraph     , visit https://discuss.dgraph.io.
To say hi to the community       , visit https://dgraph.slack.com.
```

**Comment by janardhan1993** [comment]
@MichaelJCompton :doing a normal go build won't give us the version info. We actually store version in a variable inside the code which has to be set during build by using the below flag.
"-X github.com/dgraph-io/dgraph/x.dgraphVersion=0.8"

**Comment by MichaelJCompton** [comment]
Sorry, where/how is the flag set?

**Comment by janardhan1993** [comment]
I think its go build "-X github.com/dgraph-io/dgraph/x.dgraphVersion=0.8" ./...
@pawanrawal  is that correct ?

**Comment by pawanrawal** [comment]
@MichaelJCompton `contrib/releases/build.sh` injects this information into the binary at compile time. We use this script to create the tar gzip which is uploaded on Github.

**Comment by pawanrawal** [comment]
A script has been added at `contrib/compile.sh` which can build the binaries with the correct `ldflags`.
