### ISSUE TITLE
Dgraph memory issues with 21million and trigram index

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#1066]
Having trouble loading 21million dataset with recent commits.  I put up an issue for a crash in latest version #1065 .  But even if I roll back a few commits I can't get it to load.  The issue is memory.  With 21million.schema from the benchmarks, dgraph seems to load fine till about 18M-19M triples and then spins on

```
Retrying req: 19355. Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

at that point doesn't seem like many more triples get added, but the memory usage on disk goes way up (from about 4-5GB in p dir) until dgraph maxes out the disk space - du reports p dir about 20GB at point of crash on test machine.

Tested a few combinations of indexes in schema file.  E.g. with `name : string @index(term, exact, fulltext) .` the load completes with p dir finishing at 5.7G.  Adding `trigram` produces the described behaviour.

**Comment by janardhan1993** [comment]
@MichaelJCompton : This should be fix now. Can you please try it on master now.
Please feel free to reopen if you face any issues.
