### ISSUE TITLE
Querying any UID returns a result

### ISSUE THREAD

**Issue by dpeek** [dgraph-io/dgraph#1070]
Seems like Dgraph always returns a result when querying by uid:

```
{
  me(id: whatever) {
    _uid_
  }
}
```

Returns:

```
{
  "me": [
    {
      "_uid_": "0x933943497d1a3639"
    }
  ]
}
```

Not sure if this is expected behaviour or not.

**Comment by Rader** [comment]
in your case, the \_uid_ returned is a hash ("fingerprint" used in dgraph) of the id `whatever` because its not a valid `uint64` number.

In dgraph, v0.7.6 I am using, if you query \_uid_ by id, you will always get,
1. the id you input, if it's a valid uint64 number
2. otherwise, a hash of the id you input

It's a little confusing if we _query by an id not exist but dgraph returns something_. But it's not a big problem as people always don't need to deal with `_uid_` in real case. That's why it's defined as an **internal** attribute.

#1078 has some information about `_uid_` query. Hope you can find something useful.

**Comment by tzdybal** [comment]
```
{
  me(id: [0x456789, 0x1234]) {
    count()
  }
}
```
always returns 2 (even when database is empty).

**Comment by tzdybal** [comment]
Dgraph storage is edge-centric. There is no efficient way to check node existence (probably the most common sense for 'node existence' is that node has some edges). 
You can think about it as all nodes (for every possible UID) exists all the time but they have no edges. `_uid_` is the only thing you can select.
As @Rader said, it may be confusing that `_uid_` is returned for non-existing node, but the attribute is internal, and we can't think of any real usage for such query.
If you like to check the existence of a node, you're probably also want to select some real attributes.

**Comment by manishrjain** [comment]
Just to add to what @tzdybal said, with the recent changes, we no longer support XID. So, `id: whatever` won't work anymore, and hence, uids would only be returned if they're actually present for the corresponding query.

**Comment by j0hnsmith** [comment]
> uids would only be returned if they're actually present for the corresponding query

Seems that's not true in `1.0.11`, arrived here by noticing this strange behaviour (to me at least). A brief mention in the [docs](https://docs.dgraph.io/query-language/#uid) would be useful.

```
{
  me(func: uid(0x9c410000000000)) {
    uid
    name
  }
}
```
returns

```
{
  "data": {
    "me": [
      {
        "uid": "0x9c410000000000"
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 8705,
      "processing_ns": 1049767,
      "encoding_ns": 712091
    },
    "txn": {
      "start_ts": 54275
    }
  }
}
```

**Comment by danielmai** [comment]
UIDs will be returned when they're present, as is shown in your query example with `0x9c410000000000` present in the query root func. @j0hnsmith The `uid()` function is like an identity function. It will return back to you the UID regardless of whether or not it has edges.

The [docs](https://docs.dgraph.io/query-language/#uid) for the `uid()` function have been updated to clarify this. Thanks for your feedback.
