### ISSUE TITLE
Finding uid and xid from protos.Node

### ISSUE THREAD

**Issue by ajaybodhe** [dgraph-io/dgraph#1072]
In version v0.7.7
graphp.Node:
type Node struct {
	Uid        uint64      `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Xid        string      `protobuf:"bytes,2,opt,name=xid,proto3" json:"xid,omitempty"`
	Attribute  string      `protobuf:"bytes,3,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Properties []*Property `protobuf:"bytes,4,rep,name=properties" json:"properties,omitempty"`
	Children   []*Node     `protobuf:"bytes,5,rep,name=children" json:"children,omitempty"`
}

Has been changed to protos.Node:
type Node struct {
	Attribute  string      `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Properties []*Property `protobuf:"bytes,2,rep,name=properties" json:"properties,omitempty"`
	Children   []*Node     `protobuf:"bytes,3,rep,name=children" json:"children,omitempty"`
}

How can I get uid/xid from new Node struct?

**Comment by MichaelJCompton** [comment]
The UID is only returned if you query for it.  So a query like
```
q(funct: allofterms(name, "something") {
  _uid_
 ...
}
```
will return the a `_uid_` edge in the properties list.

In 0.7.7 it's not possible to go from UID->XID even through `Node`.  Next release changes how XID is handled.

**Comment by ajaybodhe** [comment]
1. Regarding UID
so I have to loop through properties list find compare "Prop" with "_uid_"
If it matches I need to call , 
uid :=propert.Value.GetIntVal() 
which will give uid right?

2. Regarding XID
If I hit query with XID Or If the data was inserted using XID and not UID, then it should return XID in response properties right?

**Comment by MichaelJCompton** [comment]
1. sounds ok, but there is GetUidVal() which will get you the uint64 correctly.  You could always read into a map if you are looking things up over and over.

2. No.  The XID never comes back in 0.7.7

Note: that the next release changes both these points.  For 1) there is support in the library to read straight into a custom struct.  It's already in master.  I'm just about to do some examples and docs which should be up in a couple of days.  For 2) Dgraph will store XID in an edge off the node, so you can go both ways.  That's also on master and docs are in the master branch https://docs.dgraph.io/master/query-language/#external-ids

**Comment by pawanrawal** [comment]
From the next release, you can unmarshal the response to a custom struct so there would be no need to loop through the properties. @MichaelJCompton is going to soon add docs for this.
