### ISSUE TITLE
No index on _xid_

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#1074]
Should Dgraph automatically put an exact or hash index on `_xid_` if the user doesn't give one at time of bulk upload?

**Comment by Rader** [comment]
_xid_ is no longer supported. So don't depends on it.

**Comment by manishrjain** [comment]
Yes. We should do a hash index on it.

**Comment by ashwin95r** [comment]
Since we have removed the support for XIDs, do we need this? @janardhan1993

**Comment by manishrjain** [comment]
@janardhan1993 creates an xid edge via the client. We could potentially set a hash index on it by default.

**Comment by MichaelJCompton** [comment]
Would be simpler for a user to do just run `dgraphloader ... -x` on their RDF and then have the `_xid_` edges set up with an index to use - better than requiring a user to put in their schema and manage the `_xid_` edge.

**Comment by janardhan1993** [comment]
@MichaelJCompton We set up the index automatically if user specified -x. Btw we rename _xid_ to xid.
