### ISSUE TITLE
two variables in a mutation not parsed

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#1076]
It looks like with variables in mutations there is mutations code to deal with 

```
{
  var(func: eq(_xid_, "http://schema.org/Person")) {
    allPeople as <~http://schema.org/type>
  }
}
mutation {
  set {
    var(allPeople) <friend> var(allPeople) .
  }
}
```

But it won't go through the parser

`Invalid end of input. Input: [var(allPeople) <friend> var(allPeople) .]`

**Comment by ashwin95r** [comment]
Fixed with 9e0b5f3643bd10b89f174a036a72973ab5b91712.
