### ISSUE TITLE
dgraph redundant query for _uid_

### ISSUE THREAD

**Issue by Rader** [dgraph-io/dgraph#1078]
Every time we query for `_uid_`, we actually already has it. But we still run extra query for `attr` \_uid_.

Tow kind of queries in dgraph:
1. query something, attribute or predicates, directly by id
2. use index or predicates to get an id and then query something by id

To item 1, we query on root by func `id:[id]`. The id is alreay given by the user, so we know it(not matter it's valid or not).
To item 2, the id is query result. Of course we know it, unless the query returns nothing.

For example, a query like this
```Text
query{
	id(func:eq(tag,"device"),first:2){
		_uid_
	}
}
```

will be executed like this,
```Text
--taskquery{
        "attr": "tag",
        "src_func": [
                "eq",
                "",
                "device"
        ]
}

--task query result{
        "uid_matrix": [
                {
                        "uids": [
                                11430041756990,
                                22013783089703,
                                ...
                                ]
                }
        ],
        "values": [
                {}
        ]
    }
    

--taskquery{
	"attr": "_uid_",
	"uid_list": {
		"uids": [
			11430041756990,
			22013783089703
		]
	}
}

--task query result{
	"uid_matrix": [
		{},
		{}
	],
	"values": [
		{
			"val": "Xw=="
		},
		{
			"val": "Xw=="
		}
	]
}
```

**Comment by pawanrawal** [comment]
Hey @Rader 

Thanks for finding this out. We don't call ProcessGraph for `_uid_` anymore.
