### ISSUE TITLE
unknown method AssignUids

### ISSUE THREAD

**Issue by aminalaee** [dgraph-io/dgraph#1080]
I've installed dgraph using the following command:
`go get -u -v github.com/dgraph-io/dgraph/client github.com/dgraph-io/dgraph/protos/graphp`

And this is the sample code I'm trying to run:

`func main() {
	conn, err := grpc.Dial("127.0.0.1:8080", grpc.WithInsecure())
	x.Checkf(err, "While trying to dial gRPC")
	defer conn.Close()

	bmOpts := client.BatchMutationOptions{
		Size:          1000,
		Pending:       100,
		PrintCounters: false,
	}

	dgraphClient := client.NewDgraphClient(conn, bmOpts)

	person1, err := dgraphClient.NodeBlank("person1")
	if err != nil {
		log.Fatal(err)
	}

	// Creating a person node, and adding a name attribute to it.
	e := person1.Edge("name")
	e.SetValueString("Steven Spielberg")
}`

I get the following error:
`rpc error: code = Unimplemented desc = unknown method AssignUids
exit status 1`

I'm trying to add batch mutations, am I using the right method?

**Comment by manishrjain** [comment]
Please use the released versions of Dgraph, unless you are trying to contribute to the DB.

You can use the `release/v0.7.7` branch for the protos and run it against the v0.7.7 release of Dgraph.

**Comment by aminalaee** [comment]
Thank you very much.
