### ISSUE TITLE
/admin/backup to output blank nodes

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#1086]
the /admin/backup endpoint should output UIDs as blank nodes in the saved RDF.  dgraphloader can then be used to load the saved RDFs allocating new UIDs as it goes.

Maybe something like `_:UID<current-uint64-UID>` for each node.

**Comment by ashwin95r** [comment]
We've now changed the endpoint to `/admin/export` and it exports the data as blank nodes. We'll also have a backup endpoint in future which will dump the KV pairs to a file.
