### ISSUE TITLE
allow sort by facets

### ISSUE THREAD

**Issue by sjcheng** [dgraph-io/dgraph#1093]
Now the dgraph cannot support sort by facets, and it makes difficult in the following case:
-------------------
There are mulitple entities( call them uid ), and there are relationships between each other, so we create a edge "rel" between each uid, and then we set a facet named "weight" in the edge to show the relativity weight.

And now we want to get the top 10 related uids for a specific uid 10001 sort by the "weight" of "rel" edge.

--------------------

Maybe the gql+ can be like that:

{
 data(id: 10001) {
    uid,
    name,
    rel @facets( orderasc: weight, , first: 10 )@factes(weight){ uid,name }
}}

Many thanks!
Aimee

**Comment by ashwin95r** [comment]
We support this now @sjcheng.
```
{
 data(id: 10001) {
  uid
  name
  rel(first: 10) @facets(orderasc: weight){uid,name }
 }
}
```
