### ISSUE TITLE
Build monitoring endpoint for Dgraph

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#1096]

**Comment by manishrjain** [comment]
Also, include stats from Badger. Create a function there to get stats.

**Comment by manishrjain** [comment]
What's left to do here?

- [ ] Expose Badger metrics in prometheus.
- [ ] Change naming of variables in Dgraph.

**Comment by manishrjain** [comment]
@pawanrawal has a pending PR for Badger metrics. Name change done.
