### ISSUE TITLE
Benchmark/Comparison against google/cayley

### ISSUE THREAD

**Issue by petrkotek** [dgraph-io/dgraph#11]
https://github.com/google/cayley seems like an alternative to this project. Would be interesting to document the differences.

**Comment by manishrjain** [comment]
Good question, and common one. So, I've added that to the wiki page: https://github.com/dgraph-io/dgraph/wiki/Differences-between-DGraph-and-Cayley .

Is that sufficient?

**Comment by petrkotek** [comment]
Thanks @manishrjain for such quick response. All makes sense.

Great work.
