### ISSUE TITLE
running single instance

### ISSUE THREAD

**Issue by lonnietc** [dgraph-io/dgraph#110]
Greeting all,

I have recently found dgraph and it looks perfect for the project that I am working on at the moment so I started to investigate it usage on my Ubuntu 15.04 system.

I was going through the single-instance docker setup and ran into a problem:

-------------------------------------------------------------------------
Single instance via Docker

There's a docker image that you can readily use for playing with DGraph.

$ docker pull dgraph/dgraph:latest

# Setting a `somedir` volume on the host will persist your data.
$ docker run -t -i -v /somedir:/dgraph -p 80:8080 dgraph/dgraph:latest

Now that you're within the Docker instance, you can start the server.

$ mkdir /dgraph/m # Ensure mutations directory exists.
$ dgraph --mutations /dgraph/m --postings /dgraph/p --uids /dgraph/u

---------------------------------------------------------------------------

I was able to create and start up the docker image as I made the "somedir" to be /data that I created. It all started up and then inside the docker image I am at:

root@3577df598657:/go#

The catch is the last line above

$ dgraph --mutations /dgraph/m --postings /dgraph/p --uids /dgraph/u

in that 

root@3577df598657:/go# dgraph --mutations /dgraph/m --postings /dgraph/p --uids /dgraph/u
bash: dgraph: command not found

I am assuming that the docker setup compiled dgraph with golang and also set the path directory, but I am not sure why it does not start?

I want to continue down your installation and testing path so that I can complete the testing of the single instance and then move on to the multiple instances on a single machine followed by installing dgraph docker images on different physical servers as well.

I also want to set up the github "website" repository so that I can replicate your

https://dgraph.io/

on a local host to do more testing towards my project.

Can you please let me know what is happening with the dgraph command not found problem as it seems that golang has not compiled the code to create it?

Thanks,
Lonnie

**Comment by ashwin95r** [comment]
Hey Lonnie, 

Glad to know that Dgraph fits your use case well. 

The Readme of master is updated according to changes after v0.3. The executable was named 'server'  till v0.3 and the docker image hasn't been updated since. Could you please try 'server'  instead of  'dgraph'  while we work on updating the docker image. 

We are eager to here how it works for you. 

Thanks

**Comment by lonnietc** [comment]
Hello,

Thanks for responding to my post and I was able to run the single-instance
with the docker approach by using the "server" executable.

So then, I am also guessing that the docker version of dgraph is 0.3 and I
will eagerly look forward to running the 0.4 docker version as soon as it
is ready. Are there any estimates on when the new version may be ready?

I really like what I have seen in dgraph and think that it is going to work
how very well for the project.

Thanks again,
Lonnie

**Comment by manishrjain** [comment]
We're planning to cut a release for v0.4 by the end of June. It might be a bit ambitious -- so might slip to first week of July.
