### ISSUE TITLE
Adding security to dgraph

### ISSUE THREAD

**Issue by lonnietc** [dgraph-io/dgraph#111]
Hello,

As I work more and more with dgraph, I find that I really like it and am excited to use it in the project that is currently underway.

Not really sure if this qualifies as an issue, but its more of a security access question that could be looked at as an issue since it is rather important to deployment of dgraph nodes across the LAN/WAN.

The one thing that just occurred to me is a question of security and injection attacks that could result from an open call like in the examples:

--------------------------------
# Make Alice follow Bob, and give them names.
$ curl localhost:80/query -X POST -d $'mutation { set {<alice> <follows> <bob> . \n <alice> <name> "Alice" . \n <bob> <name> "Bob" . }}'

# Now run a query to find all the people Alice follows 2 levels deep. The query would only result in 1 connection, Alice to Bob.
$ curl localhost:80/query -X POST -d '{me(_xid_: alice) { name _xid_ follows { name _xid_ follows {name _xid_ } } }}'

# Make Bob follow Greg.
$ curl localhost:80/query -X POST -d $'mutation { set {<bob> <follows> <greg> . \n <greg> <name> "Greg" .}}'

# The same query as above now would now show 2 connections, one from Alice to Bob, another from Bob to Greg.
$ curl localhost:80/query -X POST -d '{me(_xid_: alice) { name _xid_ follows { name _xid_ follows {name _xid_ } } }}'
--------------------------------------------

I need to be able to find a way to add some simple security to regulate, with perhaps passwords or access control lists, or keys, etc... as to who & what can be written or read from any shard in the collective graph database cluster.

With this in mind, can you please advise me on what might be achievable in this regard?

Any help would be greatly appreciated.

Cheers,
Lonnie

**Comment by manishrjain** [comment]
Hi Lonnie,

I've created a topic at discuss.dgraph.io:
https://discuss.dgraph.io/t/adding-security-to-dgraph/427

We typically use github issues only for bug reports. So, let's move the conversation there.

Thanks!
