### ISSUE TITLE
Add MaxDepth Arg to Shortest Path

### ISSUE THREAD

**Issue by willcj33** [dgraph-io/dgraph#1111]
I would like to be able to limit the depth of how far the shortest path travels. Similar to the argument in recurse, could a MaxDepth argument be added to limit this traversal?

**Comment by manishrjain** [comment]
@ashwin95r - Don't we already have something like this?

**Comment by ashwin95r** [comment]
We have it in `recurse`. Will add for shortest as well.

**Comment by ashwin95r** [comment]
Added in master.
