### ISSUE TITLE
Multiple Distributed Instances Error

### ISSUE THREAD

**Issue by lonnietc** [dgraph-io/dgraph#112]
Greetings,

As I now understand that this communication method is for reporting bugs and issues, I have posted some other discussions on the slack and blog, but while trying to work my way through the "Multiple Distributed Instances" part of the install file, I ran into a small problem.

in that section, after installing Git LFS, which I did, I am supposed to:
-----------------------------------------------------------------------

$ git clone https://github.com/dgraph-io/benchmarks.git
$ cd benchmarks/rocks
$ tar -xzvf uids.async.tar.gz -C $DIR
$ tar -xzvf postings.tar.gz -C $DIR
# You should now see directories p0, p1, p2 and uasync.final. The last directory name is unfortunate, but made sense at the time.

----------------------------------------------------------------------

I cloned the benchmarks.git repository but now have the problem in the benchmarks/rocks directory.

The uids.async.tar.gz and postings.tar.gz files are only 134 bytes and hold not data while the $DIR is not defined so I cannot complete these steps.

I want to still utilize the docker images that I have for dgraph and want to load in the 21M RDFs from Freebase Films data so that I can access it via the DGraph "website" repository that I installed in a local nginx server that I have running on my test machine.

Where can I get the data to put into the directory that I made for the "Single Instance" in the Quick Start section:

$ mkdir /dgraph/m # Ensure mutations directory exists.
$ dgraph --mutations /dgraph/m --postings /dgraph/p --uids /dgraph/u

What fixes need to be done here?

Thanks,
Lonnie

**Comment by manishrjain** [comment]
Hi @lonnietc ,

The README instructions are a tad out of date, I'll work on it asap.

To load data for a distributed instance of Dgraph, follow these instructions:
https://github.com/dgraph-io/dgraph#distributed-bulk-data-loading

The benchmarks data is now old and won't work with v0.3 and onwards. So, you're better off loading the data on your own.

Cheers,
Manish

**Comment by manishrjain** [comment]
Added a Trello card: https://trello.com/c/fVuSB0wZ

Let me know if you run into more issues with the data loading. Otherwise, I'll close this issue in a few days.
