### ISSUE TITLE
Create edges using value vars

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#1124]
Continuing from discussion in #919 
```
mutation {
 set {
  uid(c) <friendsCount> val(c) .
 }
}
#or 
mutation {
 set {
  <1> <friendsCount> uid(c) (weight = val(c)) .
 }
}
{
 var(id: [id1, id2, id3]) {
   c as count(friends)
 }
}
```
This can be useful when we want to store a custom score generated while doing say, collaborative filtering, we can store the weights in a new edge.

**Comment by pawanrawal** [comment]
We no longer support mutation variables so this isn't relevant anymore.
