### ISSUE TITLE
GRPC muxing causing client connection hang on setup

### ISSUE THREAD

**Issue by markphilpot** [dgraph-io/dgraph#1131]
From the source code, it looks like the listener is muxing both http2/grpc traffic and http traffic into the same port.  It looks like all grpc communication must have the `content-type: application/grpc` header in it.

I don't think this will always hold true, which is why I'm having issues... Using `grpc-java` and the Netty channel provider, the opening HTTP2 frame contains three subframes... `Magic`, `Settings`, and `Window Update`

It seems like the window update negotiation happens without a `content-type` header... and thus is not being routed by dgraph to the correct handler.  Below is some output from Wireshark

![image_720](https://user-images.githubusercontent.com/46191/27890486-e1a6dac8-61a7-11e7-85e0-8722d0e6918e.png)

![image_720](https://user-images.githubusercontent.com/46191/27890491-e8327f14-61a7-11e7-8673-88c0e6be2742.png)

![image_720](https://user-images.githubusercontent.com/46191/27890494-ec6561f0-61a7-11e7-89a3-af45bd1a49af.png)

I generated the java clients from the official java protobuf plugins.  The java code looks like:

```java
        ManagedChannel channel = NettyChannelBuilder
                .forAddress(
                        "docker",
                        8080
                )
                .usePlaintext(true)
                .keepAliveTime(
                        60,
                        TimeUnit.SECONDS
                )
                .build();
        DgraphGrpc.DgraphBlockingStub blockingStub = DgraphGrpc.newBlockingStub(channel);

        Check checkRequest = Check.newBuilder().build();
        Version version = blockingStub.checkVersion(checkRequest);
```

The java client send the first HTTP2 frame (frame 5 in the wireshark output above) and then hangs indefinitely waiting for a response.

**Comment by markphilpot** [comment]
Looking at the GRPC spec, I don't believe every HTTP2 frame will necessarily include that `content-type` header, so I don't think it can be used for muxing.

https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

I would recommend just having a separate port for GRPC communication.

**Comment by manishrjain** [comment]
@srh : Have a look at the internal library that we're using, and raise this issue with them as well. We're using a lib from CockroachDB, who have forked a lib to do this muxing. So, they must have seen this issue as well.

**Comment by srh** [comment]
It looks like CockroachDB wound up going with 2 ports.
https://www.cockroachlabs.com/blog/a-tale-of-two-ports/

**Comment by srh** [comment]
Also, they don't expose gRPC to any client protocol (I think?  They have a dead PR for that, and I can't find any documented gRPC interface) so they wouldn't have encountered this specific situation, just Golang<->Golang gRPC.

**Comment by markphilpot** [comment]
I would hate to give up the gRPC client interface... A separate, dedicated port for gRPC should hopefully fix the issue.

**Comment by srh** [comment]
For debugging/test scripting purposes I will also add a --port_offset flag, so that you can run machines locally with different ports just by specifying `--port_offset N` with different values of N.  Machines will listen on ports 8080 + N, 9080 + N (for gRPC), and 12345 + N.  The flag still gets considered if you specify `--port`, `--grpc_port`, or `--workerport`.

**Comment by srh** [comment]
gRPC will be served on port 9080 as of 302486faa4bfef316082fac3b2ca80728f3e3bc5.
