### ISSUE TITLE
Graph/Label Filtering for Queries

### ISSUE THREAD

**Issue by chrisrichard** [dgraph-io/dgraph#1143]
Background: https://discuss.dgraph.io/t/access-control-in-dgraph/1513

We're hoping to use labels to partition statements into different graphs and then be able to run queries against different subsets of the overall graph by passing a list of one or more labels along with a query. We think this is generally useful but our main use-case is implementing a flexible access control scheme.

**Comment by manishrjain** [comment]
We can implement label filtering in Dgraph. Potentially in v0.9.

**Comment by abbas-zaidi** [comment]
My use case is similar: I am using dgraph to store nodes/edges corresponding to different business use cases. Like one set of nodes/edges for fraud detection and another set for recommendations. So i was looking for a way to logically group these nodes/edges like we have schema objects in Oracle.

**Comment by jimanvlad** [comment]
Label filtering would also be useful in our use case.
