### ISSUE TITLE
Switch syncCh to use async writes in Badger

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#1150]
We introduced `syncCh` to avoid paying the cost of Cgo (and linux threads) when doing writes to RocksDB. Now that we have broken away from Cgo, we can remove this channel and do writes directly to Badger. To keep our performance, we should use async writes, and pass in a function which can optionally delete the key from LRU cache, and also update the sync watermark.

needs dgraph-io/badger#98

**Comment by manishrjain** [comment]
Manish R Jain removed needs dependency to issue #98 (posted by Codetree)

**Comment by pawanrawal** [comment]
This has been merged to master.
