### ISSUE TITLE
Missing log entry

### ISSUE THREAD

**Issue by janardhan1993** [dgraph-io/dgraph#1152]
On restart

raft2017/07/08 13:09:44 missing log entry [last: 1826326, append at: 1826427]
panic: missing log entry [last: 1826326, append at: 1826427]

goroutine 331291 [running]:
log.(*Logger).Panicf(0xc4200f6ff0, 0xd49bb5, 0x2b, 0xc42dd0a060, 0x2, 0x2)
        /usr/local/go/src/log/log.go:215 +0xdb
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*DefaultLogger).
Panicf(0x135dfe0, 0xd49bb5, 0x2b, 0xc42dd0a060, 0x2, 0x2)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos
/etcd/raft/logger.go:121 +0x60
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*MemoryStorage).
Append(0xc42015e0e0, 0xc42c2c2000, 0xbba3, 0xeaa9, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos
/etcd/raft/storage.go:266 +0x662
github.com/dgraph-io/dgraph/worker.(*node).initFromWal(0xc420316240, 0xc425a4800
0, 0x0, 0x0, 0x53d14)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/draft.go:902 +0x4
6d
github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode(0xc420316240, 0xc425
a48000)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/draft.go:908 +0x5
a
github.com/dgraph-io/dgraph/worker.StartRaftNodes.func1(0xc425a48010, 0xc4203162
40)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/groups.go:145 +0x
61
created by github.com/dgraph-io/dgraph/worker.StartRaftNodes
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/groups.go:146 +0x
55d

**Comment by manishrjain** [comment]
I think this was fixed by the changes we made to WAL.

**Comment by janardhan1993** [comment]
I think it was related to snapshot. We leave 1000 entries and snapshot everything else. 
I think we did snapshot at index 1826326, and then we tried to do next snapshot, i guess server crashed after deleting the entries and before writing the snapshot key.

**Comment by manishrjain** [comment]
I see. Yeah, makes sense to write the snapshot first, and then delete the entries.
