### ISSUE TITLE
UI displays timeout while executing schema mutation

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1165]
Tried running the below schema mutation on 21million data
```
mutation {
  schema {
    name: string @index(exact) .
  }
}
```

and it timed out in the UI after 1 minute with the error
```
timeout: Could not connect to the server
```

The window also shows Not Connected although Dgraph is up. I think we should remove the 1 minute timeout for mutations from the UI.

**Comment by sungwoncho** [comment]
Yeah we can remove timeout to accommodate long-running queries. Wondering what the reason of implementing it was?

> The window also shows Not Connected although Dgraph is up.

When we timeout, we update the connection info: https://github.com/dgraph-io/dgraph/blob/master/dashboard/src/actions/index.js#L115 Should be fixed if timeout is removed.

**Comment by pawanrawal** [comment]
On server now we have a timeout of 1 minute for everything (queries and mutations) except schema mutations. We could have the same for the UI. If query has `mutation` and `schema` words, then we dont apply the timeout.

This would also mean that when a user does a normal mutation and a schema query in the same request, timeout won't be applied. But thats ok.

**Comment by pawanrawal** [comment]
We don't have any timeouts on the client anymore as the server would return an error once a query timeouts.
