### ISSUE TITLE
Slow Queries After Doing A Bulk Load On Nightly Build

### ISSUE THREAD

**Issue by willcj33** [dgraph-io/dgraph#1168]
Version: 

```
Dgraph version   : v0.7.7-dev
Commit SHA-1     : 07abc9a2
Commit timestamp : 2017-07-10 19:24:11 +1000
Branch           : HEAD
```

I am experiencing LONG delays (3.5-10s) on queries (usually heavily filtered ones that access a lot of related data) within hours of restoring data to the newest release of Dgraph. My CPU seems lost (< 10%) pretty much at all times. I try to restart it, and it does nothing to help. When I run it a second time (same query), What took 5s, takes 35ms (which is how fast it ran on 0.7.7). Seemingly, after a day or so of this instance running (untouched) the speeds are faster that 0.7.7, where after a restart (to ensure no caching or anything), what took 35ms on 0.7.7, takes around 8ms on master, but it seems I have to wait some random amount of time. UID queries are blazing fast always. Tagging @janardhan1993 and @pawanrawal as they are most familiar with my issue.

**Comment by willcj33** [comment]
[profile (19).zip](https://github.com/dgraph-io/dgraph/files/1136311/profile.19.zip)

Added a profile for when these long queries happen. This one actually times out through the UI. This is hours after my data load when making this ticket.

**Comment by willcj33** [comment]
It finally returned in 37 seconds. This is a millisecond response on 0.7.7, so something is going on here for sure. This is after I bulk loaded data still, 2 hours after. I have also restarted the server once to try to fix the speed issues. Attached my /debug/vars at the time this is happening. 


[vars.pdf](https://github.com/dgraph-io/dgraph/files/1136321/vars.pdf)

**Comment by pawanrawal** [comment]
```
     0.01s  0.38%  0.38%      1.77s 66.54%  github.com/dgraph-io/badger.(*KV).get
     0.01s  0.38%  0.75%      1.67s 62.78%  github.com/dgraph-io/badger.(*logFile).iterate
         0     0%  0.75%      1.67s 62.78%  github.com/dgraph-io/badger.(*valueLog).doRunGC
         0     0%  0.75%      1.67s 62.78%  github.com/dgraph-io/badger.(*valueLog).runGCInLoop
         0     0%  0.75%      1.60s 60.15%  github.com/dgraph-io/badger.(*valueLog).doRunGC.func1
     0.03s  1.13%  1.88%      1.56s 58.65%  github.com/dgraph-io/badger.(*levelHandler).get
         0     0%  1.88%      1.56s 58.65%  github.com/dgraph-io/badger.(*levelsController).get
         0     0%  1.88%      0.88s 33.08%  github.com/dgraph-io/badger/table.(*TableIterator).Seek
         0     0%  1.88%      0.88s 33.08%  github.com/dgraph-io/badger/table.(*TableIterator).seek
     0.01s  0.38%  2.26%      0.88s 33.08%  github.com/dgraph-io/badger/table.(*TableIterator).seekFrom
     0.01s  0.38%  2.63%      0.71s 26.69%  github.com/dgraph-io/badger/table.(*TableIterator).seekHelper
     0.03s  1.13%  3.76%      0.65s 24.44%  github.com/dgraph-io/badger/table.(*BlockIterator).Seek
     0.01s  0.38%  4.14%      0.58s 21.80%  github.com/dgraph-io/dgraph/algo.ApplyFilter
         0     0%  4.14%      0.58s 21.80%  github.com/dgraph-io/dgraph/query.ProcessGraph
         0     0%  4.14%      0.58s 21.80%  github.com/dgraph-io/dgraph/worker.ProcessTaskOverNetwork
         0     0%  4.14%      0.58s 21.80%  github.com/dgraph-io/dgraph/worker.processTask
     0.02s  0.75%  4.89%      0.57s 21.43%  github.com/dgraph-io/dgraph/worker.processTask.func2
     0.17s  6.39% 11.28%      0.56s 21.05%  github.com/dgraph-io/badger/table.(*BlockIterator).Next
         0     0% 11.28%      0.55s 20.68%  github.com/dgraph-io/dgraph/worker.fetchValue
```

**Comment by manishrjain** [comment]
We can make our GC smarter. Right now, it just starts testing if a value log needs to be rewritten every 10 mins. We need to expose some vars from Badger to be able to really figure out what to optimize there. Maybe we can allow a user to turn it off entirely. Or, reduce how many iterations it does before deciding to rewrite the file.

**Comment by manishrjain** [comment]
So, @willcj33 : This randomness of being slow, sounds to me like it is a GC problem. And the cpu profiling indicates that well. We could just reduce the amount of GC work going on in the background, and that should be sufficient here.

Is this blocking for you? Do you see this often?

**Comment by manishrjain** [comment]
So, to summarize, I think the real change that's required here is to have LSM tree be in RAM. That would speed up both the GC effort in background, and the startup slowness mentioned in #1180 .

**Comment by pawanrawal** [comment]
@willcj33 confirmed that after switching to using SSD this is not an issue anymore. 

@manishrjain should we still reduce the window size?

**Comment by manishrjain** [comment]
No need. I think the main diff is load to ram.
