### ISSUE TITLE
[log.Fatal] List reference should never be less than zero

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1171]
I loaded 21 million rdf on master without any schema and then tried to run this schema mutation.
```
mutation {
  schema {
    name: string @index(exact) .
  }
}
```

Server crashed with the following line.
```
2017/07/11 12:10:07 error.go:72: List reference should never be less than zero: -1
```

On a restart the same mutation succeeded.

**Comment by janardhan1993** [comment]
This might be race condition where we were evicting a pl and calling decr before calling incr after put if missing.
