### ISSUE TITLE
No way to return quads in dgraph

### ISSUE THREAD

**Issue by nii236** [dgraph-io/dgraph#118]
Hello!

After setting a quad in dgraph:
```curl localhost:8080/query -XPOST -d 'mutation{ set { <alice> <follows> <bob> quad . }}'
{"code":"E_OK","message":"Done"}%```
There is no way to retrieve the label at the end (`quad`).

**Comment by pawanrawal** [comment]
@nii236 Could you expand a bit on the use case you have for graph labels? I need to have a bit more context about how you are planning to use it, before I can implement this.

**Comment by nii236** [comment]
There's no particular use for it at the moment, but I just noticed that bug which is why I filed it. I can see adding context to triples mostly being useful for metadata and such.

**Comment by pawanrawal** [comment]
Ok, I think we will want to fix it later when someone has a use case for it. Right now we aren't sure what's the use case. Closing this for now.
