### ISSUE TITLE
Prevent multiple processes from accessing same storage files

### ISSUE THREAD

**Issue by srh** [dgraph-io/dgraph#1185]
It's very easy to create two processes configured to the same posting or wal dir.  This will result in corrupted data files.  Some sort of process id lock file (or one in each directory) is in order.

**Comment by manishrjain** [comment]
Agreed. Had been a to-do in my mind for a while. Would be great to get it
done. This would be a badger code change.

**Comment by srh** [comment]
Fixed in Badger.
