### ISSUE TITLE
func (d *Dgraph) NodeBlank stalls program

### ISSUE THREAD

**Issue by TBotV63** [dgraph-io/dgraph#1196]
### Client version

Commit: `09a4e50ee37aad34b318108f86241e47b001ecb3` (on par with master)
Go: `go version go1.8.3 linux/amd64`

### Code
```
func ExampleReq_AddMutation() {
	conn, err := grpc.Dial("127.0.0.1:9080", grpc.WithInsecure())
	x.Checkf(err, "While trying to dial gRPC")
	defer conn.Close()

	bmOpts := client.BatchMutationOptions{
		Size:          1000,
		Pending:       100,
		PrintCounters: false,
	}
	clientDir, err := ioutil.TempDir("", "client_")
	x.Check(err)
	dgraphClient := client.NewDgraphClient([]*grpc.ClientConn{conn}, bmOpts, clientDir)

	req := client.Req{}
	person1, err := dgraphClient.NodeBlank("person1")
	if err != nil {
		log.Fatal(err)
	}
...
}
```
See [client/examples_test.go](https://github.com/dgraph-io/dgraph/blob/07abc9a22252d7a12085c2c563663545f7de1063/client/examples_test.go#L51)

When running above code the program will stall indefinitely (I only waited ~5mins) once it gets to creating the Node.

**Comment by TBotV63** [comment]
So it sleeps in `func (a *allocator) fetchOne() (uint64, error)` due to an rpc error:

`rpc error: code = Unimplemented desc = unknown method AssignUids` from `err := grpc.Invoke(ctx, "/protos.Dgraph/AssignUids", in, out, c.cc, opts...)` in [graphresponse.pb.go](https://github.com/dgraph-io/dgraph/blob/master/protos/graphresponse.pb.go#L789)

**Comment by janardhan1993** [comment]
@TBotV63 I think you are using latest client with older version of dgraph.

**Comment by TBotV63** [comment]
Ah damn, yep :(
