### ISSUE TITLE
Data importers for Dgraph

### ISSUE THREAD

**Issue by mohitranka** [dgraph-io/dgraph#120]
We need to make it easier for people to try and test Dgraph with their existing production data - and tools that allow data ingestion easily would help in that.

This task is split in the following subtasks - 
1. Market research - Check out what kind of data ingestion support do competing graph database provide and decide which sources make sense to support.
2. Design discussion - on approach of writing the importers.
3. Implementation of individual importers.
4. Update [Wiki](http://wiki.dgraph.io) with the relevant articles.

**Comment by manishrjain** [comment]
Hey @mohitranka, I could use your help with this page:
https://wiki.dgraph.io/index.php?title=Beginners%27_guide

That'd be a great place to add documentation about how to use various data importers.

**Comment by mohitranka** [comment]
@manishrjain Sure.

**Comment by manishrjain** [comment]
Any particular action that we can take here? This issue needs more clarification. Feel free to reopen if you have specific ideas about what we should do.

**Comment by mp5088643** [comment]
so how to import csv file？
