### ISSUE TITLE
Maximum call stack size exceeded in dashboard

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#1201]
If the number of root nodes is too high (I think) this happens on Dgraph dashboard.

To reproduce:

Load SuperUser data (it's on s3. @sung has access) and run this query:
```
{
  me(func: eq(Type, "Answer")) {
    Type
  }
}
```

**Comment by pawanrawal** [comment]
I think there is something wrong with our code that processes the JSON response from the server. I will have a look.

**Comment by sungwoncho** [comment]
@pawanrawal You're right. FYI the culprit is https://github.com/dgraph-io/dgraph/blob/master/dashboard/src/lib/graph.js#L412.

**Comment by pawanrawal** [comment]
I fixed it with 9e6dad3. @sungwoncho you might want to have a look at the fix.
