### ISSUE TITLE
go build failed

### ISSUE THREAD

**Issue by bonly** [dgraph-io/dgraph#1202]
github.com/dgraph-io/dgraph/worker/worker.go:63:4: undefined: grpc.MaxRecvMsgSize
github.com/dgraph-io/dgraph/worker/worker.go:64:4: undefined: grpc.MaxSendMsgSize

**Comment by bonly** [comment]
vendor need grpc? what version with tag on git?

**Comment by manishrjain** [comment]
@pawanrawal What version of grpc is required. Also, can you point @bonly to the instructions for upgrading grpc? (We should have them in docs somewhere).

**Comment by pawanrawal** [comment]
Hi @bonly. These options were added after `go-grpc` version `1.4.1`. I added instructions on how to update `go-grpc` https://docs.dgraph.io/deploy/#building-from-source.

The command is 
```
go get -u google.golang.org/grpc
```

**Comment by bonly** [comment]
thx
