### ISSUE TITLE
Heuristic use of bool index for equality

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#1205]
Bool indices can easily create supernodes and it is expensive to bring a large posting list in memory and do an intersection than checking the value for the UIDs in consideration. 

So we should have some heuristic on when to use the index and when not to.

**Comment by manishrjain** [comment]
I'm pretty convinced that lookups would always win against iteration; so it still makes sense for us to use PLs. Let's see how well sharded PLs work; before we proceed on this heuristic. I'm not a fan of heuristics because they increase the number of code paths. The fewer they are, the better.
