### ISSUE TITLE
Dgraphloader does not allow spaces between the comma separated rdf file names

### ISSUE THREAD

**Issue by sungwoncho** [dgraph-io/dgraph#1209]
```
Dgraph version   : v0.8.0
Commit SHA-1     : 0231fcc
Commit timestamp : 2017-07-17 19:09:42 +1000
Branch           : HEAD
```

---

Description:

Dgraphloader has `-r` flag to specify the location of the rdf files to load. While it allows the argument to be a comma separated string, it does not allow spaces in between filenames. This is unintuitive from user perspective, and the error message does not help.

Works:

```
dgraphloader -r "users.rdf.gz,votes.rdf.gz"
```

Does not work:

```
dgraphloader -r "users.rdf.gz, votes.rdf.gz"
```

Error:

```
2017/07/19 10:16:02 open  votes.rdf.gz: no such file or directory
```

**Comment by ashwin95r** [comment]
Fixed.
