### ISSUE TITLE
error updating an edge value (delete/set) in same request

### ISSUE THREAD

**Issue by cesardevera** [dgraph-io/dgraph#1216]
hi,

I'm trying to update an edge value by deleting it and the setting it with a new value, in the same request, using the Go client. 

it seems that the delete is not working.

here is my test code:
[teste2.go.txt](https://github.com/dgraph-io/dgraph/files/1160030/teste2.go.txt)

**Comment by pawanrawal** [comment]
Thanks for the detailed code which helped reproduce and understand the issue immediately.  It would work if you did
```
e = usrnode.Edge("profile")
e.SetValueString("admin")
req.Delete(e)
```
That is you have to give the current value of the edge. Infact `req.Delete(e)` gives an error, which you should check. Though, it should be possible to delete the edge without knowing the value, like `S P *`.  Right now you can do that through a raw mutation.

```
req.SetQuery(fmt.Sprintf("mutation { delete { <%d> profile * . } }", userNode))
```
I will add helper functions to the client for doing `S P *` and `S * *` deletion.

**Comment by cesardevera** [comment]
hum... I understood what you said, but I tried the changes and they still didn't work,

could it be a version issue? I'm using:

```
./dgraph --config config.yaml

Dgraph version   : v0.8.0
Commit SHA-1     : 5e6d0192
Commit timestamp : 2017-07-18 21:52:22 +1000
Branch           : HEAD
```

I modified my test file in two versions: on that uses mutations and the other that sets the string value, and in both, I separated the delete request from the new set request.

anyway, the output is the same:

```
dgraph % go run teste2-setValueString.go 
Query1: [{UID:8002 Email:user1@aaa.com Profile:admin}]

error is <nil>
Query2: [{UID:8002 Email:user1@aaa.com Profile:admin} {UID:8002 Email:user1@aaa.com Profile:root}]

8002
8002

dgraph % go run teste2-mutation.go      
Query1: [{UID:9002 Email:user1@aaa.com Profile:admin}]

error is <nil>
Query2: [{UID:9002 Email:user1@aaa.com Profile:admin} {UID:9002 Email:user1@aaa.com Profile:root}]

9002
9002
```

I attached my tests too.

[teste2-mutation.go.txt](https://github.com/dgraph-io/dgraph/files/1162354/teste2-mutation.go.txt)
[teste2-setValueString.go.txt](https://github.com/dgraph-io/dgraph/files/1162355/teste2-setValueString.go.txt)

**Comment by pawanrawal** [comment]
This is a bug with the Unmarshal function. It is related to passing the same `var r Res` to `Unmarshal` multiple times. It just keeps on appending to `r.Root`. So even though the server second-time returns only one user with Profile as root, Unmarshal appends it to the already existing user value with Profile `admin`. 

This is different from how `json.Unmarshal` behaves, hence I would consider it as a bug and will submit a fix. In the meantime if you were to clear the Res object as shown in the file you wont see this issue.

[main.go.txt](https://github.com/dgraph-io/dgraph/files/1164658/main.go.txt)

**Comment by cesardevera** [comment]
solved! thanks :D
