### ISSUE TITLE
Strange behavior in Multiple Vars in mutations

### ISSUE THREAD

**Issue by advancedlogic** [dgraph-io/dgraph#1217]
I am trying to create a mutation in this way:

```
{
  n1 as var(func:allofterms(name, "name1")) 
  n3 as var(func:allofterms(name, "name3")) 
}

mutation {
  set {
    uid(n1) <knows> uid(n3) .
  }
}
```

where name1 and name3 exist.
The output is:

**Some variables are defined but not used Defined:[n1 n3] Used:[n3]**

If I change in:
```
{
  n1 as var(func:allofterms(name, "name1")) 
  n3 as var(func:allofterms(name, "name3")) 
}

mutation {
  set {
    uid(n1) <whatever> "whatever" .
    uid(n1) <knows> uid(n3) .
  }
}
```

then it works but a new edge (whatever) is added.

**Comment by manishrjain** [comment]
Looks like we're somehow ignoring variables when they occur in the subject.

**Comment by pawanrawal** [comment]
A fix has been merged to master.
