### ISSUE TITLE
Panic in 0.8 on GCE

### ISSUE THREAD

**Issue by willcj33** [dgraph-io/dgraph#1218]
Receive this panic when running SOME query (I have around 10 polling my graph in 0.8. 

```
Dgraph version   : v0.8.0
Commit SHA-1     : 713b49f0
Commit timestamp : 2017-07-19 12:06:32 +1000
Branch           : HEAD

```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb733c7]

goroutine 68450 [running]:
github.com/dgraph-io/dgraph/query.ProcessGraph(0x1300e00, 0xc42bc9c6c0, 0xc42acc0d80, 0x0, 0xc42b6aac00)
    /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1594 +0x77
created by github.com/dgraph-io/dgraph/query.(*QueryRequest).ProcessQuery
    /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:2201 +0x4a9
```

This seemed like it may have done it, but honestly not sure, seems pretty random through the ui: 
```
{
  start(func: eq(ENTITY_type, "4")){
    expand(_all_)
  }
}
```

**Comment by manishrjain** [comment]
@ashwin95r: This code should be stable by now. Why are we seeing nil errors here?

**Comment by manishrjain** [comment]
@willcj33 : you can just delete the LOCK file and restart. The LOCK file is there to avoid another process reusing the same directory.

**Comment by willcj33** [comment]
@manishrjain I did do that, Ill Update the ticket to remove that part. Thanks

**Comment by ashwin95r** [comment]
I think this query is not the reason for this crash. I saw a similar crash yesterday for 
```
{
 me(func: uid()) {
 }
}
```
Is it possible that you had an empty root? Anyways @pawanrawal has included a fix for this in a PR

**Comment by pawanrawal** [comment]
@willcj33 Does this happen anymore?

**Comment by manishrjain** [comment]
Closing this issue for now. If this happens again, please feel free to reopen, @willcj33.
