### ISSUE TITLE
Idea: cascade deletion

### ISSUE THREAD

**Issue by sungwoncho** [dgraph-io/dgraph#1222]
As a frontend dev, I would like to delete not only all outgoing edges of a node, but also those of certain nodes that are connected to the node.

**Example**

In graphoverflow, `<Question> ---[Has.Answer]--->  <Answer> ---[Author]---> <User>`.

When one deletes a question, all the answers that used to belong to that question remains, causing UI to break at times.

Currently I have to query all answer's UIDs and delete them manually. However I feel that this is error-prone.

In SQL, developers can set cascade deletion on a table so that rows that depends on another will be deleted when the parent is deleted.

Can there be a way to set up the schema so that when `<Question>` is deleted, all `<Has.Answer>` will also get deleted?

**Comment by manishrjain** [comment]
We should be able to do this via variables in mutations.

**Comment by manishrjain** [comment]
This can be done via transactions now.

**Comment by urandom** [comment]
@manishrjain 
What do you mean by "via transactions"?
Do you mean by manually deleting all related nodes from within the same transaction? If so, that doesn't seem all that different to the error-prone way suggested by OP.
Could you please give an example.

**Comment by MichelDiz** [comment]
Here is a way to do this https://docs.dgraph.io/mutations/#bulk-delete-example

You can use multiple query blocks, reverse edges to get all nodes you need to delete. (But you need dgraph type well done).
