### ISSUE TITLE
var err

### ISSUE THREAD

**Issue by bonly** [dgraph-io/dgraph#1228]
as "var" usage describ in page:
https://docs.dgraph.io/master/query-language/#variables-in-mutations

ql:
{
  adults as var(func: ge(age, 18))
}
mutation {
  set {
    var(adults) <isadult> "true"^^<xs:boolean> .
  }
}

should be report as error as below:

: Invalid input: v at lexText

**Comment by pawanrawal** [comment]
Hey @bonly 

This was an issue with our documentation. The syntax for using variables in mutation was updated but the docs were still using the older syntax. I have updated the docs now.

@MichaelJCompton can you please verify that this(b968141af80e13c0b2350d28f3931027ecee5940) is all we need?

**Comment by MichaelJCompton** [comment]
Looks like it.
