### ISSUE TITLE
Where is the configuration file to set server and port information (website issue)

### ISSUE THREAD

**Issue by lonnietc** [dgraph-io/dgraph#123]
Greetings,

I have set up the Dgraph cluster for testing as well as have loaded the benchmark data for the film/movie/actor series. I have also set up the Dgraph "website" repository web server code which seems to serve well, but I do not see, in that code where it configures the Dgraph server and port for making the connection.

I actually posted this in the "website" repository issues section but it does not seem that anyone is monitoring that list.

What I need to locate is where is the configuration file in the "website" repository to set up the server IP and port to call the Dgraph cluster so that when I start up the Dgraph cluster then the website code can make a connection as right now I get he message:

"
query result is not available
Error talking to server
"

Also, I am running all of this on a Ubuntu 14.04 machine as well.

Any help would be greatly appreciated.

Cheers,
Lonnie

**Comment by mohitranka** [comment]
The website is not supposed to be the generic frontend to dgraph, but something dgraph-io team wrote for the demo purpose alone.

The call to /query is made at https://github.com/dgraph-io/website/blob/master/app/app.js#L267

**Comment by lonnietc** [comment]
Greetings,

Thanks for responding to this inquiry as I understand that it was supposed
to be something that the team set up for a demo, but my current interest
was to replicate the demo so that I could get a better feel for how things
worked with the dgraph/website repositories.

I wanted to set up a complete duplicate of the http://dgraph.io example and
was able to get the backend dgraph cluster working without any problems,
but just not the frontend.

I actually found that statement, but it did not clarify to me what the url
and port were, given that it is a single statement.

Thanks again,

Cheers,
Lonnie

**Comment by manishrjain** [comment]
We don't officially support the website for users. It's open source but specific for dgraph.io usage. Best place to ask these questions is discuss.dgraph.io.
