### ISSUE TITLE
Different behavior between json and pb

### ISSUE THREAD

**Issue by advancedlogic** [dgraph-io/dgraph#1232]
here a strange behavior:
`{
   q(func:allofterms(x, "x")) {
     ~relation1 {
        something
    }
    ~relation2 {
      something_else
   }
   relation3 {
     something_else1 
  }
  }
}`

In json I see all the relations, in pb only the first 2 (the last one is missining)

**Comment by pawanrawal** [comment]
@advancedlogic I tried to reproduce this but couldn't. Could you provide the code you used to reproduce this?

**Comment by manishrjain** [comment]
>  Could you provide the code you used to reproduce this?

Ping, @advancedlogic.

**Comment by manishrjain** [comment]
Closing the issue for now. Insufficient information to proceed.
