### ISSUE TITLE
Server dies on query involving objects and literals

### ISSUE THREAD

**Issue by bitmalloc** [dgraph-io/dgraph#124]
Having the following mutations:
```shell
$ curl localhost:8080/query -X POST -d $'mutation { set {<alice> <follows> <jim> .}}'
{"code":"E_OK","message":"Done"}
$ curl localhost:8080/query -X POST -d $'mutation { set {<alice> <follows> "Tim" .}}'
{"code":"E_OK","message":"Done"}
```
 And executing the following query:
```shell
$ curl localhost:8080/query -X POST -d '{me(_xid_: alice) { name _xid_ follows { name _xid_ } }}'
```

Kills the server with:
```
...
2016/06/26 21:49:32 List merge counters. added: 0 merged: 5 clean: 0 pending: 0 mapsize: 5 dirtysize: 0
2016/06/26 21:49:52 List merge counters. added: 0 merged: 1 clean: 0 pending: 0 mapsize: 7 dirtysize: 0
2016/06/26 21:49:58 prev: map[follows:[map[_xid_:jim _uid_:0xb2ec6818c1ba4e8e]]] _uid_: 10125359828081617157 new: [84 105 109] Previous value detected. A uid -> list of uids / value. Not both
```

The issue seems to be that Dgraph assumes a certain "schema" for the `follows` predicate while executing the query, expecting all `o` in `s` `p` `o` to be the same type (non-literals). 
Usually graph databases don't enforce a certain schema, hence any valid triple/quad pattern can be inserted into the database and queried; if a certain triple/quad doesn't match the pattern it is simply ignored. 
In this case the mutations and the query are valid, but the query at runtime enforces only one type of value. Probably the easiest thing for now here would be to prevent the server from dying after this exception.

**Comment by manishrjain** [comment]
We do want to enforce a schema on the data entered. Freebase has a great schema, and GraphQL also enforces a strong schema on the data.

I think the real issue here is that we should be checking the schema at the input. So, we know what to expect from `follows` predicate.

**Comment by bitmalloc** [comment]
How is the schema (ontology) defined and specified in Dgraph in order to be enforced? 
Specifically, how is Dgraph able to determine which triples/quads are defining the schema of the data that it should be able to ingest? 
Is there a specific `graph-label` for this in the design?

**Comment by manishrjain** [comment]
It would be defined via GraphQL: https://facebook.github.io/graphql/#sec-Type-System

That way, the end point (object) for each property (edge) would be enforced to be of the same type, so either byte value (specific data type) or a ID etc.

We need to implement the type system of GraphQL. It's part of the roadmap, but we're not there yet. So, technically this is not a bug -- even though it's bad that data causes the server to log FATAL. Having said that, the Log Fatal is doing exactly what it's supposed to do.

Any advice on how to proceed with this issue?

**Comment by bitmalloc** [comment]
I've been thinking about this issue, but probably a discussion re: Dgraph's type system could be continued in [discuss](https://discuss.dgraph.io/). I tried creating a new topic under the `dev` category but I did not have access to it.
Regarding this issue, probably as long as the server is not killed by an invalid query should be enough to close it; I'd be happy to work on it, if possible, as it will help to further improve my knowledge of the codebase.

**Comment by pawanrawal** [comment]
That's strange @bitmalloc that you couldn't create a topic. Just to clarify the category is `Devs`. Sure once we decide what the right course of action here, you could take it up.

**Comment by manishrjain** [comment]
Only Dgraph team can create topics in devs. Users is for contributors.

**Comment by manishrjain** [comment]
This particular issue isn't a bug. A single predicate shouldn't have two different types of objects.

Either they should be an entity, or they should be values, but not both. @akhiltak is working on a schema, but that isn't going to necessarily *fix* this, because a user can choose not to provide a schema and yet provide us this mixed data -- so a crash is a justified solution here. We could switch it an error return later if that's what users deem appropriate. But until at least v1.0, a log fatal is good.
