### ISSUE TITLE
Demo looks broken

### ISSUE THREAD

**Issue by Vanuan** [dgraph-io/dgraph#1241]
When I click tabs on https://dgraph.io/
I see this error:

`"Invalid syntax using id. Use func: uid().\n"`

"People who played Harry Potter" shows empty json

In addition, the tree tab shows constant values.

**Comment by pawanrawal** [comment]
Hi @Vanuan 

I have fixed the demo. The query syntax had changed in the latest release and the website was using the older syntax.

**Comment by lazharichir** [comment]
Maybe should also do it in the Docs, even for the simplest queries like in the Mutations and then Query parts :)
