### ISSUE TITLE
From and to argument in shortest path should accept uid variables

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1243]
`from` and `to` function in shortest path query doesn't accept a uid variable, hence a user must know the know the exact uid while doing a shortest path query.

We should allow using uid variable from another query block. We can assert that length of uid variable should be one.

**Comment by birdayz** [comment]
Is this on the roadmap? From my point of view, as someone who just recently started working with dgraph, it's surprising that it's not possible.

**Comment by martinmr** [comment]
The fix for this issue should also work for the k-shortest path algorithm.

**Comment by ruicore** [comment]
can give an example? I try to use variables in shortest path but failed，thanks
