### ISSUE TITLE
Use index better, directly check values in some situations

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#1245]
Sometimes, it's better to just check the values when we do inequality functions than using the index. For example: 

```
{
  directed(func: eq(name@en, "Tom Hanks")) {
    name@en
    director.film @filter(ge(initial_release_date, "1970-01-01")) {
      initial_release_date
      name@en
    }
  }
}
```
In this query `Tom hanks` has only 3 movies that he has directed. When we filter `ge(initial_release_date, "1970-01-01")` we read `~50` index keys (when indexed by year) with values (Which takes ~4s in the first run and ~700ms thereafter) whereas we could've just fetched the value for the 3 UIDs that we require (Which would take considerably less time).

So in general, if the number of UIDs are less than the number of index KV that we need to fetch, we should directly check the values.

**Comment by pawanrawal** [comment]
Nice idea @ashwin95r. I have made the corresponding change and merged it to master.
