### ISSUE TITLE
Slow start in embedded/library mode

### ISSUE THREAD

**Issue by tzdybal** [dgraph-io/dgraph#1246]
First start of application using Dgraph as library is fast. But all the latter starts are very slow - there is a lag of about 15s before queries start to work.

**Comment by manishrjain** [comment]
Could be because we're busy loading up all the pending writes, since the last successful Raft snapshot. Did you close cleanly?

**Comment by tzdybal** [comment]
The problem is following: if we start from scratch, we force raft election immediately after starting raft.
After restarting raft, we have to wait 9 or 10 seconds/ticks for election. 
And client code sleeps after each error in exponential manner. 1+2+4+8=15s -after that client can execute.

**Comment by manishrjain** [comment]
@srh had a plan to change the ticks to 10ms. In that case, we can do elections faster.

**Comment by srh** [comment]
The ticks are 20 ms as of sam/tickrate which is in a PR now.

**Comment by tzdybal** [comment]
I'll merge/cherry-pick your PR and test your changes.

**Comment by tzdybal** [comment]
@srh your change solves the problem. I'm closing the issue.
