### ISSUE TITLE
count index not updated after schema update

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#1247]
(on v0.8)

If I run

```
mutation {
  set {
    _:bob <friend> _:jane .
    _:bob <name> "Bob" .
    _:jane <name> "Jane" .
  }
}
```

then

```
mutation {
  schema {
    friend: uid @reverse @count .
    name: string @index(exact) .
  }
}
```

It looks like the count index is not created properly because

```
{
  q(func: has(~friend)) {
    name
  }
}
```

returns nothing. But the other indexes and the reverse edge seem to be created properly.

**Comment by pawanrawal** [comment]
This is related to setting both `@reverse` and `@count` index at the same time. Investigating what is causing this.

**Comment by pawanrawal** [comment]
A fix has been merged to master.
