### ISSUE TITLE
Can we access the visual interface host:8080 publically?

### ISSUE THREAD

**Issue by lazharichir** [dgraph-io/dgraph#1251]
Hello,

Just setup a small linode server (Ubuntu 17) to play around with 0.8 and I access the visual interface on 8080 only when I do it locally from the server itself through a curl (it shows me the html code, so it works.)

From the browser, using the public name and the port 8080, it just shows a generic `ERR_CONNECTION_REFUSED`. Is there any settings to flag to use when starting dgraph to make it publically available?

Quick netstat..

<img width="1115" alt="screen shot 2017-07-25 at 14 22 23" src="https://user-images.githubusercontent.com/12215372/28571792-c794f244-7144-11e7-99f4-f233475a86a5.png">

Let me know,

Thanks

**Comment by janardhan1993** [comment]
@lazharichir  Please pass -bindall option.
`dgraph -bindall=true`

**Comment by lazharichir** [comment]
@janardhan1993 this works perfectly - sorted and thank you very much, very quick.
