### ISSUE TITLE
can't set language tags in go client

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#1253]
there's no way to do something like

```
e = n.Edge("name@en")
```

in the go client

**Comment by MichaelJCompton** [comment]
would be good in v0.8 too.

**Comment by pawanrawal** [comment]
We now have [SetValueStringWithLang](https://godoc.org/github.com/dgraph-io/dgraph/client#Edge.SetValueStringWithLang). Added it to both `release/v0.8.0` and `master`.

**Comment by katutz** [comment]
I checked the 1.0.3 version and there isn't this method SetValueStringWithLang or any other to specify the language for the value. So i'm using the nquadsFromJson method from dgraph/edgraph/server.go (that I copied the code to my application) to convert my JSON to NQuad slice and set the language. Is there another way to achieve this?

**Comment by pawanrawal** [comment]
If you are using JSON, you could have your predicates as `name@en`, `name@fr`. For e.g.

```
{
  "name@en": "katutz",
  "name@fr": "katutz"
  ...
}
```

Would translate to
```
_:a <name> "katutz"@en .
_:a <name> "katutz"@fr .
````

**Comment by katutz** [comment]
Great! This solution is better. Thank you!
