### ISSUE TITLE
can't delete with * in go client

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#1254]
I couldn't find a way to use the `* P *` or `x P *` syntax in client

**Comment by pawanrawal** [comment]
Hi @MichaelJCompton 

I added a couple of helper functions to do S P * and S * *.
https://godoc.org/github.com/dgraph-io/dgraph/client#Edge.Delete // S P *
https://godoc.org/github.com/dgraph-io/dgraph/client#Node.Delete // S * *

I will add one for * P * too.

**Comment by MichaelJCompton** [comment]
Yep, that's what I was looking for :-)  ...I'm on v0.8 though - can you also add to that.

**Comment by pawanrawal** [comment]
I have added the above two functions along with [Delete Predicate](https://godoc.org/github.com/dgraph-io/dgraph/client#DeletePredicate) to both `release/v0.8.0` and `master`.

**Comment by priyank-shah-1105** [comment]
The above provide links are not working. Can you please provide me an example on how to use S P * and S P * * in dgraph client?
