### ISSUE TITLE
Update docs about changes in schema parsing for tokenizer.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1277]
We made specifying a tokenizer mandatory for all types. We also changed the name of `dateTime` tokenizer to `year`. Docs need to be updated to reflect this.

Corresponding changes are in #1274.

**Comment by manishrjain** [comment]
We also need to modify our 21M RDF schema, and other schemas. @pawanrawal

**Comment by pawanrawal** [comment]
Done for both 21M and goldendata.

**Comment by pawanrawal** [comment]
I did this before the `v0.8.1` release.
