### ISSUE TITLE
How to define, use and query custom schema or custom object types?

### ISSUE THREAD

**Issue by lazharichir** [dgraph-io/dgraph#1278]
Not having working on a big personal project for a while, I updated dgraph from where I left (roughly 0.6/0.7) - I like the feel very much.

However, my graph database is mainly a knowledge graph roughly structured as follows.

First, there is the top-level `Topic` type, with the following properties:
- `label` string @index
- `slug` string @index
- `wikipedia_en` string _the url for the topic's wikipedia page_

Then, we have the `Term` type, with the following properties:
- `label` string @index
- `slug` string @index
- `wordcount` int

Topics are broad abstract concepts and terms are words or expressions often found when discussing a given topic.

Relationships are as follows: `Term` <pertains_to> `Topic` (weight: 1) - a topic has hundreds of terms in its _vocabulary_, and a term pertains to several topics, usually with different weights.

Because I cannot see how to give an explicit type to a new object, I don't see how I can query only the topics with the word 'food' in their names. If i run an `allofterms(label, "food")` function, it will get all topics and terms including the word `food` in their label.

I just want topics - it must be easy but I just cannot find it in the documentation right now...

**Comment by pawanrawal** [comment]
Hey @lazharichir 

We don't have object types. The way to do this would be to assign an explicit `Type` edge and have an index on it. So
```
Type: string @index(exact) .
```

Topic nodes would have value `Topic` for `Type` edge, Term nodes would have value `Term`. Then you can filter topic node like

```
{
  me(func: eq(Type, "Topic")) @filter(allofterms(label, "food")) {

  }
}
```

**Comment by manishrjain** [comment]
Actually, we should document how to do object types in Dgraph. @MichaelJCompton -- Most likely we don't need to change anything, but just have a tutorial about putting together existing mechanisms to achieve the same effect.

**Comment by lazharichir** [comment]
Will take a few days to get used to this way of working but fine by me! Thanks a lot both.

**Comment by pawanrawal** [comment]
We have some docs in the [How To section](https://docs.dgraph.io/howto/#giving-nodes-a-type) for this.
