### ISSUE TITLE
Config value for `peer` should take multiple IP addresses

### ISSUE THREAD

**Issue by elbow-jason** [dgraph-io/dgraph#1279]
I’m trying to setup a cluster of dgraph servers using a script that installs a systemd unit (treating dgrpah as a service). If my `peer` server goes down, moves, or otherwise changes it’s IP I’ll have to alter the unit file or the `config.yaml`. If I could assign more than one peer it would make the clustering more resilient.

It would be nice to specify a list of IP addresses in the `config.yaml` or even a comma-separated string of IPs to the `--peer` flag.

**Comment by manishrjain** [comment]
`--peer` flag is no longer valid. We've replaced it with `--zero`. Any of them can be used to start Dgraph server. Dgraph server would automatically connect with the leader, whoever the leader happens to be.
