### ISSUE TITLE
docs.dgraph.io: Update FAQ about RocksDB

### ISSUE THREAD

**Issue by deepakjois** [dgraph-io/dgraph#1281]
https://docs.dgraph.io/faq/#why-does-dgraph-use-rocksdb

We don’t use RocksDB anymore, but use Badger instead. Options are:

1. Remove the FAQ entry
2. Change the question to  _Why doesn’t Dgraph use RocksDB anymore?_
3. Add an additional question: _Why does Dgraph use Badger?_

**Comment by peterstace** [comment]
I can think of another option as well:

4. What does Dgraph use for its persistent storage?

And the answer can include some details about badger and why we use it, along with a short historical summary of why we used to use RocksDB (but don't any more).

**Comment by manishrjain** [comment]
Above sounds good.

Also, we need to introduce some new questions about our licensing. In fact, we need a doc about licensing in general. We follow MongoDB model, where using Dgraph is free even for proprietary purposes. But, if you modify the server, then those changes must be released back. Maybe, @deepakjois you can articulate it better, read the blog post about it, and then create a page about licensing. So, we can link it every time someone has questions.

**Comment by manishrjain** [comment]
```Is Dgraph fast?

Every other graph system that I’ve run it against, Dgraph has been at least a 10x factor faster. It only goes up from there. But, that’s my own observations. We have a couple of folks doing a thorough benchmarking of Dgraph against Cayley and Neo4J, which we’ll publish blog posts for soon. See relevant Github issues here.```

We now have these posts already. Can you look through all of these FAQs and brush them up.

**Comment by deepakjois** [comment]
Added info about Badger in 08918c4ad270e2bce375e6aaa412fc414d3ab635.

Will brush up other parts of the FAQ separately.

**Comment by deepakjois** [comment]
Updated the FAQ about Dgraph performance with some links to benchmarks: a68f5d62936220ced4fb8d4049995782a14c7cde
