### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by carloslenz** [dgraph-io/dgraph#1284]
**Query**
{
  h(func: eq(path_id, uid(0x1))) @filter(eq(user_id, uid(0x2)) AND eq(sha512, uid(0x3)))
}

**Output**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb74acf]

goroutine 10744 [running]:
github.com/dgraph-io/dgraph/query.ProcessGraph(0x1302e80, 0xc424debaa0, 0xc420074900, 0x0, 0xc424debb00)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1604 +0xbf
created by github.com/dgraph-io/dgraph/query.(*QueryRequest).ProcessQuery
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:2204 +0x4a9

**Server**
Docker image dgraph/dgraph as of Jul, 31st, 2017.
Using default tag: latest
latest: Pulling from dgraph/dgraph
Digest: sha256:00b0a5a4ee1cbf48a2321bb2a89a1580fbcc55d09d75e6659e72537cf4155490
Status: Image is up to date for dgraph/dgraph:latest

**Database contents**
Half-way through dgraph tour, I haven't added any schema or data to support the query yet.

**Comment by pawanrawal** [comment]
Hi @carloslenz 

This looks like a bug in our parsing logic. The second argument of `eq` is supposed to be a value as mentioned [here](https://docs.dgraph.io/query-language/#inequality). It can't be a uid function. I will fix this. 

Now regarding your query, it could be done something like this
```
{
  h(func: uid(0x1)) @filter(uid_in(user_id, 0x2) AND uid_in(sha512, 0x3)) {
    ...
  }
}
```

**Comment by carloslenz** [comment]
Hi @pawanrawal, thanks for the query tips.
But more important than the parsing logic, a parser bug should not kill the server altogether.

**Comment by pawanrawal** [comment]
Agreed @carloslenz. I have added a fix to master that makes the parser stricter.
