### ISSUE TITLE
Memory leak in web UI

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1286]
Running queries with lots of nodes causes the web UI to slow down until its unusable. I've seen this in both Chrome and Firefox.

Using the "Close all" button fixes the problem.

E.g. running the following query on the `1million.rdf.gz` dataset 10 times causes it to slow down (33 nodes, 49 edges).

```
{
  var(func: allofterms(name, "Taraji Henson")) {
    actor.film {
      F as performance.film {
        G as genre
      }
    }
  }

  Taraji_films_by_genre(func: uid(G)) {
    genre_name : name@en
    films : ~genre @filter(uid(F)) {
      film_name : name@en
    }
  }
}
```

Since it only occurs after running multiple queries, most likely is a memory leak in the UI.

**Comment by sungwoncho** [comment]
I can confirm that the slowness is a result of memory leak in the UI. The memory from the HTML canvas is not being garbaged collected.

FYI @pawanrawal, this is a current investigation of the memory leak: https://github.com/almende/vis/issues/3098

**Comment by pawanrawal** [comment]
This should not be an issue anymore. We were re-rendering the whole app while modifying the query in the editor which we don't do anymore.

**Comment by peterstace** [comment]
Leak fixed a while ago, closing.
