### ISSUE TITLE
Remove dependencies from tests

### ISSUE THREAD

**Issue by tzdybal** [dgraph-io/dgraph#1289]
Some tests in `query` package depends on execution of other tests. At least 2 tests modify data. Tests executed before those tests expect the data to be in same form as defined in `populateGraph`, other expects the data to be altered.
Because of this we're not able to execute single test and be sure that result is correct.

**Comment by pawanrawal** [comment]
This would be a great change. Either each test should setup and clear all its data or tests shouldn't modify any data independently (all setup should happen in populateGraph once).

**Comment by tzdybal** [comment]
Following tests can't be executed alone:
```TestCount
TestToProto
TestToProtoNormalizeDirective
TestNormalizeDirective
TestDebugUid
TestCountAtRoot
TestCountAtRoot3
TestHasFuncAtRoot
TestHasFuncAtRootFilter
TestHasFuncAtChild2
TestHasFuncAtRoot2
TestMultipleEqInt
TestReflexive
TestReflexive2
TestReflexive3
TestCascadeUid
```

**Comment by tzdybal** [comment]
Merged to master.
