### ISSUE TITLE
Cannot specify literal language when using bulk data loading with external ids

### ISSUE THREAD

**Issue by aatimofeev** [dgraph-io/dgraph#1292]
It seems that  in `v0.8.0` bulk data loading does not support literals with specified language.
Let's say i'm trying to upload the following triples:
```
<luke> <foaf:name> "Luke Skywalker"@en .
<leia> <foaf:name> "Princess Leia" .

<sw1> <name> "Star Wars: Episode IV - A New Hope" .
<sw1> <release_date> "1977-05-25" .
<sw1> <revenue> "775000000" .
<sw1> <running_time> "121" .
<sw1> <starring> <luke> .
<sw1> <starring> <leia> .
```
The only difference between `luke` and `leia` here is that Luke has `@en`. Using `dgraphloader` with `-x` flag I'm uploading the data:
```
Dgraph version   : v0.8.0
Commit SHA-1     : 49291a98
Commit timestamp : 2017-07-24 10:25:23 +1000
Branch           : HEAD


Processing c.ttl.gz
Number of mutations run   : 12                                                                      
Number of RDFs processed  : 11
Time spent                : 1.009786311s
RDFs processed per second : 11
```
Then, the following query:
```
{
  data(func:allofterms(name, "Star Wars"))  {
    starring {
      _predicate_
     expand(_all_)
    }
  }
}
```
gives the following response:
```
{
  "data": [
    {
      "_uid_": "0x3ec",
      "starring": [
        {
          "_predicate_": [
            {
              "_name_": "foaf:name"
            },
            {
              "_name_": "xid"
            }
          ],
          "_uid_": "0x3ea",
          "xid": "luke"
        },
        {
          "_predicate_": [
            {
              "_name_": "foaf:name"
            },
            {
              "_name_": "xid"
            }
          ],
          "_uid_": "0x3eb",
          "foaf:name": "Princess Leia",
          "xid": "leia"
        }
      ]
    }
  ]
}
```
So, the predicate exist, but literal doesn't.

**Comment by pawanrawal** [comment]
On initial investigation, I have found:

1. We accept `:` as part of the predicate (IRI) while doing mutations according to RDF spec, but while doing query we consider `:` it to be a delimiter for [alias](https://docs.dgraph.io/query-language/#alias). Hence in this case internally we are querying for `name` with an alias of `foaf`.

2. Also `expand(_all_)` only returns strings without any language tag. This is mentioned in the [docs](https://docs.dgraph.io/query-language/#expand-predicates). That's why you don't see `foaf:name` for Luke. 

>  If the predicate has no string without a language tag, expand() won’t expand it.

**Comment by pawanrawal** [comment]
Added a note about retrieving predicates with special characters to the [docs](https://docs.dgraph.io/master/query-language/#returning-values). Closing this issue.
