### ISSUE TITLE
Incorrect function behaviour when language is not specified

### ISSUE THREAD

**Issue by tzdybal** [dgraph-io/dgraph#1295]
```
mutation {
  schema {
    test: string @index(hash, term) .
  }
  set {
    <_:t1> <test> "India"@en .
  }
}
```
Query:
```
{
  i(func:eq(test, "India")) {
    tae: test@en
    ta: test
  }
}
```

Query returns no results, but according to docs it should.

> Note In functions, language lists and `.` notation are not allowed. In functions, a string edge without a language tag means apply function to all languages, while a single language tag means apply to only the given language.

**Comment by tzdybal** [comment]
Problem is visible only for `hash` index. With `exact` index `eq` works as expected.

**Comment by tzdybal** [comment]
Seems that problem is visible for all functions and index types. Previous tests were to trivial - English was the only language used, therefore it was selected as 'any language'.

**Comment by manishrjain** [comment]
This is how we currently do retrieval:

Retrieval:
test@en => English
test@. => Any language
test => Value without lang tag

We should implement the function in the same manner.
