### ISSUE TITLE
json endpoint for cluster information

### ISSUE THREAD

**Issue by elbow-jason** [dgraph-io/dgraph#1296]
It would be very useful to have an HTTP endpoint that returned cluster information. I imagine something like a list of servers with their configurations. For example:

```
GET http://localhost:8080/debug/cluster

{
  "data": {
    "servers": [
      {
        "idx": 1,
        "groups": [0, 1, 2, 3],
        "peer": "<some_peer>:<some_peer_workerport>",
        "my": "<my_ip>:<my_workerport>"

        // other fields
      }
    ]
    // other server objects
  }
}
```

**Comment by janardhan1993** [comment]
We have /state endpoint on master. We have added a new binary called dgraphzero which takes care of all group stuff and manages membership stuff and will distribute the data and move it automatically.
