### ISSUE TITLE
Double click on web UI cyclic graph causes infinite loop

### ISSUE THREAD

**Issue by 1lann** [dgraph-io/dgraph#1302]
This is due to the double click handler not accounting for cyclic graphs by not checking whether or not the edge/node has already been seen in GraphContainer.js: https://github.com/dgraph-io/dgraph/blob/79d1f4586d5d7898496a9617272addf67d7a818c/dashboard/src/containers/GraphContainer.js#L197-L208

**Comment by 1lann** [comment]
Oh, I should probably throw in some instructions on how to reproduce it. Follow the tour here: https://tour.dgraph.io/intro/3/ and the next step inside the Dgraph web UI. Then in the graph view, try double clicking on a node.

**Comment by pawanrawal** [comment]
Thanks for finding this out @1lann.  I have fixed this in master.
