### ISSUE TITLE
Have a way to dynamically update the lease

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1306]
We should be able to update `lease` information through an admin endpoint similar to #1144. 

Dgraphloader should get the lease before starting loading and return an error if the uids being loaded are greater than the lease.

**Comment by pawanrawal** [comment]
This is needed before `v0.8.3` so that even if users bootstrap dgraph with bulkloader things go smoothly.

**Comment by peterstace** [comment]
We won't need this before v0.8.3 due to https://github.com/dgraph-io/dgraph/pull/1583 , which allows dgraphzero to accept a lease. This still seems like a good feature to have though.

**Comment by manishrjain** [comment]
I think the lease flag is a good solution. We don't need to do anything more at this point.

**Comment by peterstace** [comment]
Ok, I think we can park this for now then.

**Comment by manishrjain** [comment]
Closing it for now. We can reopen if we need this again.
