### ISSUE TITLE
Allow dgraph to read settings from configuration files

### ISSUE THREAD

**Issue by mohitranka** [dgraph-io/dgraph#131]
Most of the datagraphs do that. It would allow us to handle configurations in more elegant manner, as the number of configs increase and we start supporting running dgraph on startup as daemon etc.

**Comment by ankurayadav** [comment]
Hi Guys, I want to take this up.
As I am new few pointers to get me started around this would be a great!

**Comment by manishrjain** [comment]
Use the `--help` on dgraph binary to figure out which all flags are available. Then chase them down in the codebase; and you can move them all to a YAML config.

**Comment by manishrjain** [comment]
Done. Thanks to @ankurayadav.
