### ISSUE TITLE
Fix bad parsing logic

### ISSUE THREAD

**Issue by srh** [dgraph-io/dgraph#1311]
Once sam/parsertest gets merged, some test cases will be named "Bad" and they represent bad parser behavior (not bad test cases).  They should be fixed

- TestParseQueryWithVarValAggBad - `me(func: val(L), orderasc: val(n))` should not be permitted
- TestParseIdListBad - `uid( [0x1, 0x1, 2, 3, 0x34])` is obsolete
- TestParseFilter_unknowndirectiveBad - `@filtererr` should not be tolerated
- TestParseGeneratorErrorBad - okay parsing, bad error message
- TestParseGraphQLVarIdBad - `uid($a,$b,$c)` rejected with "Invalid use of comma"

Also maybe the message for "Expected 3 periods ("..."), got 2.'." could be improved.

**Comment by pawanrawal** [comment]
Closed via adf0d346d8681f93c33250917ae7d94cad967df8
