### ISSUE TITLE
Missing infos for getting geo datas

### ISSUE THREAD

**Issue by AsT4re** [dgraph-io/dgraph#1312]
There are some example of go clients for unmarshal from query response to go structure for all kinds of types but not for geo type. After looking deeper in the doc and in the code, I found that it was encoded binary datas that was returned and that I had to call wkb.Unmarshal to get back a geom.T type.

First it would be great to have more information in doc and go client examples dealing with getting geo informations.
Secondly, when calling unmarshal on go stucture, it would be nice to get decoded data directly like geom.T type or a structure like the geo json we have added originally.

**Comment by pawanrawal** [comment]
@AsT4re Agree that the docs miss info about Geo types. I will definitely add an example to the docs. 

I have to see if it's possible to decode the data to `geom.T` as part of `client.Unmarshal()` since `geom.T` is an interface.

**Comment by pawanrawal** [comment]
Hi @AsT4re 

I have added an example on how to set and query for Geo types using the Go client https://godoc.org/github.com/dgraph-io/dgraph/client#example-Edge-SetValueGeoJson. It doesn't convert to `geom.T` yet. I have added [another issue](https://github.com/dgraph-io/dgraph/issues/1472) for that.
