### ISSUE TITLE
Dgraph tour not working with docker image 0.8.0 2d294351220d

### ISSUE THREAD

**Issue by the42** [dgraph-io/dgraph#1313]
When pulling DGraph docker image version 0.8.0, running it as described by the tour,
https://tour.dgraph.io/intro/2/

further steps to interact with dgraph using  the tour interactive elements result in error

    Error: Is Dgraph running locally?

However, browsing to localhost:8080 successfully returns DGraphs UI.

OS: Linux, kernel 4.12.4
Browser: Firefox 54 64 bit, multiprocess

**Comment by pawanrawal** [comment]
That's strange. I tried the `v0.8.0` docker image and it works fine. Two questions

1. Does the error persist after the first 10-15 seconds? In `v0.8.0` we had a slower boot up time due to RAFT membership election. That has been rectified in the master.
2. Do you see Dgraph server logs?

**Comment by the42** [comment]
> Does the error persist after the first 10-15 seconds? In v0.8.0 we had a slower boot up time due to RAFT membership election. That has been rectified in the master.

Yes

> Do you see Dgraph server logs?
Yes


I tried it using Chromium where it indeed works. However using FF 54 the only reply is 
    Error: Is Dgraph running locally?
Maybe it's an issue with Firefox Multiprocess? I also tried opening the debug console with F12 to see if a request is actually made but as it seems FF doesn't even perform a request to localhost.

**Comment by pawanrawal** [comment]
Hey @the42 

Thanks for the report. Apparently Firefox blocks [mixed-content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) i.e. content from `http` sources when a site is served over https. This can also be observed from the error message in the console.

Though starting from Firefox version 55 (which releases on 8th Aug), they have decided to allow mixed content from `localhost` which is what we want here (chrome does the same). I have tested that `https://tour.dgraph.io` works on the [beta version](https://www.mozilla.org/en-US/firefox/channel/desktop/) of firefox. I would suggest waiting a day and upgrading to Firefox 55 which should resolve this issue.

**Comment by pawanrawal** [comment]
Verified that this works in the latest released version (55) of Firefox. Closing the issue.
