### ISSUE TITLE
Build support for dgraph to run as daemon/startup on server start

### ISSUE THREAD

**Issue by mohitranka** [dgraph-io/dgraph#132]
Databases are expected to run as always-on daemon processes.

**Comment by manishrjain** [comment]
hmm... how about using ampersand at the end of it? Or, using tmux.

To run it as a service, someone needs to write this script: http://www.cyberciti.biz/tips/linux-write-sys-v-init-script-to-start-stop-service.html

**Comment by sameersamarthp** [comment]
```
#!/bin/bash
#
# description: Dgraph server
#

# Start Dgraph
start() {
        initlog -c "echo -n Starting Dgraph server: "
        /usr/local/bin/dgraph
        ### Create the lock file ###
        touch /var/lock/subsys/dgraph.lock
        success $"Dgraph server started"
        echo
}

stop() {
        initlog -c "echo -n Stopping Dgraph server: "
        pkill dgraph
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/dgraph.lock
        echo
}
 
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status dgraph
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
  
exit 0
```

I tested this script on "Ubuntu 16.04.1 LTS". Here are the steps required to make dgraph run as a service:-

- copy and save the above code as file "dgraph" (without quotes)
- place the above file (dgraph) under /etc/init.d/ (`cp dgraph /etc/init.d/`)
- give executable permission (`chmod 755 /etc/init.d/dgraph`)
- reload systemctl daemon (`systemctl daemon-reload`)
- start dgraph (`service dgraph start`)
- stop dgraph (`service dgraph stop`)
- restart dgraph (`service dgraph restart`)

Hope this helps.

**Comment by manishrjain** [comment]
Hi @sameersamarthp, Can you do two things:

- Send out a PR to add a file in contrib directory or something copying your code above. So, users can just download it.
- Add instructions in https://wiki.dgraph.io/Beginners_Guide, adding a new section about running Dgraph as a daemon with your instructions above, and pointing to the code.

**Comment by sameersamarthp** [comment]
Sure. will do.

**Comment by manishrjain** [comment]
This can wait until we go into distributions.
