### ISSUE TITLE
Unexpected behavior using mutation set without newlines

### ISSUE THREAD

**Issue by elbow-jason** [dgraph-io/dgraph#1320]
#### The issue:

When doing a mutation set if the triples of the set's block are not delimited by newlines only the first triple is written to the database. The rest of the triples are ignored. This behavior is unexpected. It would be better to either detect extra content (non-whitespace) on the same line as the first triple (after the ` . `) and throw an error, or use the naked ` . ` as the delimiter and write all the triples in the `set` block.

#### What happened:

I sent this query:

```
mutation { set { _:company <name> \"TurfBytes\"^^<xs:string> . _:company <owner> _:owner . _:owner <name> \"Jason\"^^<xs:string> . } }
```
note: The above query does not delimit triples with newlines.

This was the response:

`{"code": "Success", "message": "Done", "uids": {"company" => "0x55"}}`

#### What I expected to happen:

I want to send this query (no newlines again):

```
mutation { set { _:company <name> \"TurfBytes\"^^<xs:string> . _:company <owner> _:owner . _:owner <name> \"Jason\"^^<xs:string> . } }
```
And get an error or get this response:

`{"code": "Success", "message": "Done", "uids": {"company": "0x55", "owner":  "0x56"}}`

**Comment by pawanrawal** [comment]
The [RDF spec](https://www.w3.org/TR/n-quads/#sec-intro) says that individual nquads should be terminated with a `.` and a newline. So I think we should throw an error if the input doesn't conform to this. Working on a fix.

**Comment by pawanrawal** [comment]
A fix has been merged to master. We throw an error now.
