### ISSUE TITLE
Installer fails with rate limit exceeded error from Github API

### ISSUE THREAD

**Issue by ericho** [dgraph-io/dgraph#1327]
The installer fails to get a connection with Github API, running
```
curl -i https://api.github.com/repos/dgraph-io/dgraph/releases/latest
```
Shows the following error

```
{
  "message": "API rate limit exceeded for 192.55.54.38. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by pawanrawal** [comment]
@ericho This doesn't look like a problem with Dgraph. Github imposes a [rate limit](https://developer.github.com/v3/#rate-limiting) which you are hitting.

**Comment by manishrjain** [comment]
@ericho : Do you see this when running `curl https://get.dgraph.io | bash`?

**Comment by ericho** [comment]
Hi @pawanrawal 

I understand the limit from Github API however I think it might be two issues involved here. The first is that in such conditions the installer doesn't notify that there was an error. The output if the following : 

```
  _____                        _
 |  __ \                      | |
 | |  | | __ _ _ __ __ _ _ __ | |__
 | |  | |/ _` | '__/ _` | '_ \| '_ \
 | |__| | (_| | | | (_| | |_) | | | |
 |_____/ \__, |_|  \__,_| .__/|_| |_|
          __/ |         | |
         |___/          |_|

Latest release version is .
Downloading checksum file.
######################################################################## 100.0%
Download complete.
Comparing checksums for dgraph binaries
You already have Dgraph  installed.
You have the latest assets files.
Please visit https://docs.dgraph.io/get-started for further instructions on usage.
```

The second issue is that if dgraph becomes more popular, new users will be blocked by the API limit, which could led to a first bad taste of the project. So I'm wondering that probably the install method can be changed to not use the Github API.

**Comment by pawanrawal** [comment]
Hey @ericho 

Agree we should handle errors better. I will make the change. 

About the second issue, it shouldn't become a problem if Dgraph becomes popular because this limit is per client (60 reqs/hour and 5000 reqs/hour with Authentication) and not per repo. So unless the user is using Github API extensively he shouldn't encounter it. We upload our binaries to Github during a release and hence use the same for getting the release binary.

**Comment by manishrjain** [comment]
I think we could proxy this particular `/releases/latest` endpoint via Dgraph. That would avoid hitting Github API limits.

**Comment by pawanrawal** [comment]
We now proxy the endpoint via `get.dgraph.io/latest`.
