### ISSUE TITLE
dgraph does not work on Windows

### ISSUE THREAD

**Issue by abbas-zaidi** [dgraph-io/dgraph#1328]
i tried installing with Cygwin, the message that dgraph is installed but the binaries are not installed.
Opening the issue on github to track the same.

**Comment by Motakjuq** [comment]
you can create a windows executable without too much effort, you only need mingw. With gcc in your path, you just to do a `go build`

**Comment by janardhan1993** [comment]
@abbas-zaidi What command did you use to install on windows ?

**Comment by abbas-zaidi** [comment]
I used the below command on Cygwin:
curl https://get.dgraph.io -sSf | bash

It gave an impression that it is installed but then when i search for the binary file dgraph to start the server it was not found.

**Comment by janardhan1993** [comment]
@abbas-zaidi We don't have binaries for cygwin platform. We modified the script to throw error if we don't have binary for that platform.

You need to compile the dgraph from source if you want to run on cygwin.

**Comment by janardhan1993** [comment]
You can compile it from source and ideally it should work on both cygwin and windows. @manishrjain or @pawanrawal can comment on supporting binaries for windows or cygwin.

**Comment by pawanrawal** [comment]
@abbas-zaidi we released binaries for Windows from `v0.8.3`. You can't get them from `get.dgraph.io` as I am not sure if there is a standard location in Windows that I can install them to but you can download and install them manually. 

Documentation at https://docs.dgraph.io/get-started/#installing-on-windows
