### ISSUE TITLE
dgraph does not start on OS X

### ISSUE THREAD

**Issue by advancedlogic** [dgraph-io/dgraph#1329]
This is the message I am having:

`Allotted memory for Dgraph should be at least 1GB. Current set to: -1.000000`

**Comment by janardhan1993** [comment]
@advancedlogic You need to set max allotted memory using the flag - - memory_mb. Recommend value is half the size of ram.

**Comment by srh** [comment]
I've pushed 72b02a871f8574be2f942e66c318ee99d7f0f705 which will at least make the error message much clearer.
