### ISSUE TITLE
Make it easy to install Dgraph

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#133]
Caddy has this amazing script: https://getcaddy.com/

Would be cool to have such a script for Dgraph. This would make installing and upgrading the binaries easy for the end user.

**Comment by mohitranka** [comment]
Another great example is 21.co. You can try it with ```curl https://21.co | sh```

**Comment by mohitranka** [comment]
The script is available at `get.dgraph.io` and can be installed using `curl get.dgraph.io | bash `. Closing the issue.
