### ISSUE TITLE
Dgraph does not allow to do aggregations (i.e. sum) at the top level of a query

### ISSUE THREAD

**Issue by magallardo** [dgraph-io/dgraph#1330]
I have been trying to do aggregations at the top level of a query but it seems like it only works when the aggregation is done at a sub-level. 
Since aggregation only works on variables, and variables can't be used on the same level, then aggregation does not work at the root level.

**Comment by pawanrawal** [comment]
Closed via e4b731d2751bb4a5ec18e14f4292c8e4318a2912. Will be part of the next release.
