### ISSUE TITLE
Dgraphloader stops making progress on 3-node cluster

### ISSUE THREAD

**Issue by srh** [dgraph-io/dgraph#1336]
If I start up a 3-node cluster and then run `dgraphloader -r ~/1million.rdf.gz -s data/21million.schema`, quite consistently it stops making progress at some point or another.

```
[Request:    845] Total RDFs done:   838056 RDFs per second:    7102 Time Elapse
[Request:    845] Total RDFs done:   838056 RDFs per second:    6984 Time Elapse
[Request:    845] Total RDFs done:   838056 RDFs per second:    6869 Time Elapse
```

And then it doesn't respond to SIGINT or SIGQUIT.

In doing this I've found that usually one of the cluster nodes also doesn't respond very well to SIGINT either.

If you restart dgraphloader after giving it a SIGKILL, it sometimes hangs again, but sometimes, it finishes loading the data.

**Comment by srh** [comment]
When opening up a 4th node, one with no data on it, I tried running a query.

```
curl http://localhost:8083/query -XPOST -d 'query { me(func: anyoftext(name, "Ivan")) { name@. } }'; echo
{ "data": {} }
srh@pc4:~/blah$ curl http://localhost:8083/query -XPOST -d 'query { me(func: anyoftext(name@., "Ivan")) { name@. } }'; echo
{"errors":[{"code":"Error","message":"rpc error: code = Unavailable desc = transport is closing"}],"data":null}[3]-  Exit 1                  ~/go/bin/dgraph --group_conf ~/blah/groups.conf --groups "0,1" --idx 3 --port 8082 --sc 1000 --memory_mb 8192 --grpc_port 9082 --workerport 12347 --my "127.0.0.1:12347" --peer "127.0.0.1:12345" --p ~/blah/svr3/p --w ~/blah/svr3/w >> ~/blah/svr3/dgraph.log 2>&1
```

Server 3 died with the log message `Tokenizer not found for fulltext.`

**Comment by pawanrawal** [comment]
This above is a bug, we are trying to find tokenizer for `.`. I created https://github.com/dgraph-io/dgraph/issues/1337 for this.

**Comment by srh** [comment]
This started becoming much more difficult to reproduce -- not because of any particular commit.

**Comment by srh** [comment]
https://github.com/dgraph-io/badger/issues/178 might cause this.  I'm not saying it does.
