### ISSUE TITLE
Support multiple sorting criteria

### ISSUE THREAD

**Issue by windoze** [dgraph-io/dgraph#1352]
For now dgraph only supports single sorting criterion, such as:
```
{
  q(func: uid(NNN), orderasc: lastName) {
    ...
  }
}
```

It could be very useful if we can support multiple sorting criteria in the same query block, such as:
```
{
  q(func: ..., orderasc: lastName, orderasc: firstName) {
    ...
  }
}
```

**Comment by manishrjain** [comment]
I doubt we'll get to this before v1.0. If this can be achieved via other means without changing the code, we should explore those.
