### ISSUE TITLE
running dgraph on a low-end vps cluster

### ISSUE THREAD

**Issue by jeromew** [dgraph-io/dgraph#1368]
Hello,

I was wondering if you have any idea/hint how dgraph would behave on a big cluster of low-end servers (1 core, ram 1Go, Disk 20Mo).
Obviously the performance would take a hit compared to the [benchmarks](https://blog.dgraph.io/post/performance-throughput-latency/) but would it totally stall/crash because of the low specs of the cluster of would it grind its way through the queries ?

thanks for your feedback.

**Comment by manishrjain** [comment]
We haven't really tested Dgraph with 1GB RAM. Hard to say how it would perform. Maybe worth trying it out, but not a priority for us at the moment.
