### ISSUE TITLE
Can't query schema using gRPC interface?

### ISSUE THREAD

**Issue by srh** [dgraph-io/dgraph#1369]
User "mark" (Mark Philpot) on Slack reported this just gets the error "UNKNOWN: empty query and mutation."

```
Request request = Request.newBuilder()
                .setSchema(
                        SchemaRequest.newBuilder().build()
                )
                .build();

        Response response = blockingStub.run(request);
```

Looking in server.go it looks like it's returning that error without even looking at `req.Schema`.

Or maybe there is no bug, and documentation could be improved.

**Comment by pawanrawal** [comment]
> Mark Philpot [2:03 AM] 
> @mrjn I'm not using the community client... just a rest library at the moment.

He says he is using a Rest client.
