### ISSUE TITLE
Build LDBC vendor implementation for Dgraph

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1379]
LDBC has a [driver](https://github.com/ldbc/ldbc_driver) which coupled with vendor specific implementations can be used to run their [Social Network Benchmarks](http://ldbcouncil.org/developer/snb).

We need to build a vendor specific implementation in Java which can be used to run the interactive workload benchmark for Dgraph. https://event.cwi.nl/grades/2017/12-Apaci.pdf has two parts one of which was the Interactive Workload mentioned above.

Here are the links for some vendor specific implementations

https://github.com/PlatformLab/ldbc-snb-impls
https://github.com/ldbc/ldbc_snb_implementations
https://github.com/ldbc/ldbc_snb_interactive_validation (Validator for connector)

**Comment by manishrjain** [comment]
This would be quite a bunch of work. And it's better if a third party does this work and run the benchmarks than us.
