### ISSUE TITLE
Empty predicate/edge names crash db

### ISSUE THREAD

**Issue by kayteh** [dgraph-io/dgraph#1381]
Given this example, you can create Edges with empty strings as names, and it crashes the DB, and crashes on every subsequent start until data is reset.

```go
c := client.NodeBlank("somename")
e := c.Edge("")
e.ConnectTo(c)

// save it in some way
req := client.Req{}
req.Set(e)
client.Run(context.Background(), req)
```

**Comment by pawanrawal** [comment]
Thanks for the report @kayteh. Fixed with ac0c07c4a34a9ca431c3122844e0f2f3d04f9340.
