### ISSUE TITLE
(n *node) send() can Fatal because n.messages channel is full

### ISSUE THREAD

**Issue by srh** [dgraph-io/dgraph#1384]
We have this code:

```
	select {
	case n.messages <- sendmsg{to: m.To, data: data}:
		// pass
	default:
		// TODO: It's bad to fail like this.
		x.Fatalf("Unable to push messages to channel in send")
	}
```

Under high load I got that to trigger once.

**Comment by janardhan1993** [comment]
I think it should be safe to drop the messages, raft is supposed to take care of network failures also.

**Comment by manishrjain** [comment]
https://github.com/dgraph-io/dgraph/commit/b77f9cd5ad84ef399f70a12b9a42f62200964771
