### ISSUE TITLE
Setting string with lang tag returns an error if tokenizer is fulltext

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1388]
Set schema

```
mutation {
  schema {
    name: string @index(fulltext) .
  }
}
```

Now do mutation
```
mutation {
  set {
    <1> <name> "पवन"@hi .
  }
}
```

We get an error for all languages except `en`. 
failed to apply mutations error: internal error: Tokenizer not available for language: hi

**Comment by pawanrawal** [comment]
This looks like its correct behavior. We return an error when we don't have a full-text tokenizer for a language. It was not caught earlier while loading 21 million probably we were [not returning errors](https://github.com/dgraph-io/dgraph/commit/ac42962b7aa458e654ed2a284262ecea90ffc4ac) while doing index mutations.

**Comment by tzdybal** [comment]
It should be correct, otherwise we should see errors also in the unit tests.
