### ISSUE TITLE
Support upsert operation

### ISSUE THREAD

**Issue by jimanvlad** [dgraph-io/dgraph#1393]
Hi,

I am looking for an optimized 'upsert' function, which in effect checks if a node already exists (based on a condition). If it does, it returns it (which can then further be used within the query). If it doesn't, it creates it and then returns it.

Further functionality should split the 2 operations, with the ability to perform a set of logic if a node has been found, and a different set if it has been created.

See [MongoDB Upsert](https://docs.mongodb.com/manual/reference/method/db.collection.update/) and [Neo4J MERGE](http://neo4j.com/docs/developer-manual/current/cypher/clauses/merge/).

This is useful when you have data streaming into the graph, but you want to avoid duplication.

Vlad

**Comment by pawanrawal** [comment]
This was added as part of `v0.8.2`, hence closing this issue. 
https://docs.dgraph.io/query-language/#upsert
