### ISSUE TITLE
Error in delete with pattern when expand_edge is false

### ISSUE THREAD

**Issue by tzdybal** [dgraph-io/dgraph#1395]
If `expand_edge` is set to `false`, `delete` mutation with predicate pattern doesn't work and there is no error/warning.

For the simple case:
```
mutation{
  set{
    <0x1> <name> "test" .
    <0x1> <alias> "test" .
  }
}
```

After running 
```
mutation {
  delete {
    <0x1> * * .
  }
}
```
data is not deleted, and no error nor warning is returned

Following query returns results (shows that nothing was deleted):
```
{
  me(func:uid(0x1)) {
    name
    alias
  } 
}
```

**Comment by pawanrawal** [comment]
Thanks @tzdybal. This is fixed in master. We throw an error now.
