### ISSUE TITLE
dgraph visualizer

### ISSUE THREAD

**Issue by candysmurf** [dgraph-io/dgraph#1411]
Dear DGraph,

After going through your tutorial and by reading your benchmark comparison vs ne04j, I would love to choose DGraph for our new project. I haven't seen any DGraph visualizer although it's mentioned in the tutorial(links are shown text only).

Any pointer is appreciated.

**Comment by manishrjain** [comment]
We have a UI running on the HTTP port. By default, it should be on port 8080.

**Comment by candysmurf** [comment]
@manishrjain, thanks for the quick response. I got "404 page not found" when I go to http://127.0.0.1:8080.

Did I miss anything? 

BTW, does DGraph support data from different databases, such as MySQL or Cassandra?

**Comment by janardhan1993** [comment]
@candysmurf I think the assets might be missing. If you have downloaded the assets to a separate location you can mention the path using --ui flag.

From each release the corresponding assets are located at  https://github.com/dgraph-io/dgraph/releases/download/$release_version/$assetsFile.

Or you can use the script at https://get.dgraph.io/.

**Comment by manishrjain** [comment]
Yeah, `curl https://get.dgraph.io -sSf | bash` is the recommended installation method.

**Comment by candysmurf** [comment]
@manishrjain, @janardhan1993, appreciate your quick responses. yaaah, I can see graphs now. Lastly, if we have data in MySQL,  any recommended tool to export and import them into DGraph?
Of Course, the redesign may be better. I just want to see the options.

**Comment by candysmurf** [comment]
I guess that I can use csv to rdf converter. If you have any other suggestions, please let me know. thanks.

**Comment by candysmurf** [comment]
Thanks for your help. This issue can be closed.
