### ISSUE TITLE
Document how to run dgraph with kubernetes

### ISSUE THREAD

**Issue by janardhan1993** [dgraph-io/dgraph#1413]

**Comment by jalberto** [comment]
a helm chart would be handy

**Comment by pawanrawal** [comment]
Picking this up as it is related to https://github.com/dgraph-io/dgraph/issues/1790.

**Comment by pawanrawal** [comment]
Instructions have been added at https://docs.dgraph.io/master/deploy/#kubernetes.

Created a separate issue for helm chart at https://github.com/dgraph-io/dgraph/issues/1917.
