### ISSUE TITLE
Bundle assets with the dgraph binary

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1415]
Sometimes users just download the releases binary from Github and forget to download the assets and the UI doesn't work for them. We can use https://github.com/jteeuwen/go-bindata to bundle assets within the binary so that they don't have to download them separately.

**Comment by fervic** [comment]
It happened to me :stuck_out_tongue: .

And coincidentally I just found about `go-bindata` this past week while browsing through an Apex repo and Dgraph assets came to my mind.

If nobody has grabbed this I can take a stab.

**Comment by pawanrawal** [comment]
Sure go for it @fervic.

**Comment by fervic** [comment]
Hi @pawanrawal, I'll have availability to work on this next weekend. If it needs to be done before that just let me know so I step aside.

**Comment by chilts** [comment]
There is also https://github.com/gobuffalo/packr which essentially does the same thing but in a slightly different way.

**Comment by pawanrawal** [comment]
Assets are now bundled with the ratel binary.
