### ISSUE TITLE
windows version :)

### ISSUE THREAD

**Issue by joeblew99** [dgraph-io/dgraph#142]
Dont be a hater, and i hate windows too.

The reason this is a thing for me is because many projects i do rely on deployment to servers, but also desktops.

http://rocksdb.org/blog/2033/rocksdb-is-now-available-in-windows-platform/

**Comment by pawanrawal** [comment]
Hey @joeblew99

The problem is none of our devs use Windows, so its not possible for us right now to test out installation, build binaries of Dgraph on Windows. 

Though if someone from the community can come up and help us with this, we would be more than happy.

**Comment by mohitranka** [comment]
@joeblew99, btw [Manual Installation](https://wiki.dgraph.io/Beginners_Guide#Manual_Installation) should still work on windows. Do let us know if you face any issues in that.

**Comment by manishrjain** [comment]
This is a feature request. discuss.dgraph.io is the ideal platform for this discussion.

**Comment by svenwiegand** [comment]
@mohitranka: Sounds good to follow the manual installation guide. Unfortunately it states I should download the version matching my platform and there are only builds for Linux and Mac. Any advise?

**Comment by manishrjain** [comment]
Hey @svenwiegand, while we don't officially support Windows, because as @pawanrawal mentioned, we just don't have a windows machine; I think v0.8 which gets rid of RocksDB and switches to pure Go libraries should make Dgraph work alright on windows.

**Comment by svenwiegand** [comment]
Thanks @manishrjain. Any plans when v0. 8 will be available?

**Comment by manishrjain** [comment]
We're getting close to start testing Badger, the KV store which could potentially replace RocksDB. I'd take a month, to be on the cautious side -- for that to be tested and stabilized. Once we have confidence in Badger, we won't wait for anything else and make a release quickly. So, expect mid-April for v0.8.
