### ISSUE TITLE
full text search is not support chinese

### ISSUE THREAD

**Issue by gzliudan** [dgraph-io/dgraph#1421]
maybe below tokenizer can be integrated into dgraph:

https://github.com/yanyiwu/gojieba

https://github.com/huichen/sego

**Comment by windoze** [comment]
Thanks Dan.

Right now Dgraph is using blevesearch/bleve for FTS, which doesn't support Chinese yet.
I'll look into these Chinese tokenizers to see if I can integrate them into Dgraph.

**Comment by manishrjain** [comment]
Bleve has support for CJK, using bigrams. This is the same approach as what Elastic Search does. So, let's use it.

**Comment by peterstace** [comment]
Merged to master at 623638c. This will appear in the upcoming v0.9.0 release.
