### ISSUE TITLE
Mutation delete usage in docs should include unsupported patterns

### ISSUE THREAD

**Issue by elbow-jason** [dgraph-io/dgraph#1422]
In slack a user asked about using the patterns `* * O` or `* P O` in a mutation delete. The docs show examples for `* P *` and `P O *`, but do not mention the previous two patterns. The docs should explicitly state that both  `* * O` and `* P O` are not supported and give a description about why they are not supported (something about not tracking incoming edges of a node).

**Comment by janardhan1993** [comment]
updated the docs in master.
