### ISSUE TITLE
Need help with mutation set for geo typed field

### ISSUE THREAD

**Issue by elbow-jason** [dgraph-io/dgraph#1429]
I am getting an error with this query:

```
mutation { set {
_:land <geo_center> "[-112.44615353350031,33.35600630797468]"^^<geo:geojson> .
} }
```
I am getting this error:
```
 {"errors":  [{"code": "ErrorInvalidRequest","message": "json: cannot unmarshal array into Go value of type geojson.Geometry"}]}
```
The docs do not give examples of using the typed syntax (using the `^^` ) with geo.

What is the correct form for this query? Thanks.

**Comment by pawanrawal** [comment]
Hi @elbow-jason

Did you have a look at https://docs.dgraph.io/master/query-language/#geolocation? The docs haven't made it to the latest release yet.

**Comment by elbow-jason** [comment]
@pawanrawal  Thanks!

For future people with this issue the following is the example from the updated docs (from master targeting v0.8.1)

```
mutation {
  set {
    <_:0xeb1dde9c> <loc> "{'type':'Point','coordinates':[-122.4220186,37.772318]}"^^<geo:geojson> .
    <_:0xf15448e2> <name> "Hamon Tower" .
  }
}
```
