### ISSUE TITLE
Add Dgraph to Arch Linux AUR package

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#144]
This would make installing Dgraph easier for folks using Arch Linux.

Something like `yaourt dgraph` would do the job.

**Comment by trengrj** [comment]
Dgraph seems a cool project. I added a binary installation package `dgraph-bin` to the AUR https://aur.archlinux.org/packages/dgraph-bin/. I'll try to add a source installation package too.

A couple remarks:

1. The tar bomb for the binaries is not nice.
2. Do you have a systemd unit file? Do you want one?
3. Is there a global configuration file?
4. I think the port 8080 default might need to change.

**Comment by manishrjain** [comment]
Nice. Thanks a lot @trengrj!

- Tar bomb? You mean the .tar.gz files? What would you suggest?
- Not yet, no. So, basically systemd would allow running dgraph as a background process. Sounds like a good idea.
- There would be a data file for ICU tokenizer. @jchiu0 -- can you elaborate on the location of this file?
- What port would you suggest?

**Comment by pawanrawal** [comment]
[Here](https://github.com/dgraph-io/gru/blob/develop/dgraph/dgraph.service) is a sample unit file that we are using for https://github.com/dgraph-io/gru to run Dgraph using systemd.

@trengrj Would love to get your suggestions on how we can improve it.

**Comment by trengrj** [comment]
Hi @manishrjain @pawanrawal 

I added a systemd unit file to the AUR package: https://aur.archlinux.org/cgit/aur.git/tree/dgraph.service?h=dgraph-bin. It is pretty similar to the unit file you provided but I set the uids / mutations / postings directories to be in /var/lib/dgraph/data (this is similar to where postgres write data on Arch Linux). Being able to set the parent directory for these files as an environment variable would be nice (maybe this can already be done).

You start or enable (start on boot) via systemd `sudo systemctl start|enable|stop dgraph`, with logs available via `journalctl -u dgraph`.

About those other points. When a tar.gz extracts to multiple files and not to a directory it is sometimes called a tar bomb. It doesn't matter for now but if the number of files increases in the binary zip file it becomes hard to find the files and they can overwrite stuff.

Port wise, there is a list of well-known ports here https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers and you can also register them officially. The problem with 8080 is that it is used by proxy servers. My approach would be to pick random primes not on the table  :smile:. What about port 9311?

**Comment by manishrjain** [comment]
9311 is good. Want to send a PR? Also, @pawanrawal do we have a script to build the .tar.gz? If so, we should change it.

Note that in the next release, we'll have a `p` and a `w` directory only.

**Comment by pawanrawal** [comment]
We do have a script which we use for our releases. We have it like this so that while extracting binaries they can be extracted and stored directly to `/usr/local/bin`. I think I will add the intermediate step to getdgraph.sh script to copy from the extracted folder to `/usr/local/bin`.

**Comment by trengrj** [comment]
I've added an arch linux package that builds the latest dgraph from source using go get https://aur.archlinux.org/packages/dgraph-git/. Had some issues getting this working initially due to that build error. Do you want me to do a PR for a systemd unit file?

**Comment by manishrjain** [comment]
Ideally, we only pick the latest release from Github, and not build from source. We're continuously adding in stuff there, and builds can break. OTOH, when we push a release, we test it out thoroughly before releasing.

Sure, send me a PR. Happy to review!

**Comment by trengrj** [comment]
Yes I have created two packages `dgraph-bin` and `dgraph-git`, one for the binaries and one for the latest source (following the standard AUR naming convention).

Ideally there would be a `dgraph` package that builds the latest stable version. This source package, would be the one that could make it to the main Arch repo (where they enforce building from source).

`go get` doesn't handle vendor dependencies and versioning well. I've heard good things about [Glide](https://glide.sh/) for managing Go packaging. Adding a Glide config would make it easier to create this source package.

**Comment by manishrjain** [comment]
We check in all our deps in vendor folder, using govendor. So, just `go
get` should work.

Thanks!

Cheers,
Manish

Founder/CEO, Dgraph Labs
+61-487138931
https://calendly.com/mrjn

**Comment by manishrjain** [comment]
I'll test it out once we do the v0.7 release.
