### ISSUE TITLE
DGraph rest apis does not understand few characters

### ISSUE THREAD

**Issue by shankaragarwal26** [dgraph-io/dgraph#1444]
I executed the query api with the following json
{ab(func: eq(name@en, "$pringfield (or, How I Learned to Stop Worrying and Love Legalized Gambling)")) { _uid_ }}

The response returned is
Variable not defined $pringfield (or, How I Learned to Stop Worrying and Love Legalized Gambling)

**Comment by pawanrawal** [comment]
A fix has been merged to master with ce013bdf63654c374703b668b572dd6554e54ef9 and would be part of the next release.
