### ISSUE TITLE
Bulkloader gets killed by the OS

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1452]
```
MAP 01m42s rdf_count:18.34M rdf_speed:178.5k/sec edge_count:42.32M edge_speed:412.0k/sec
MAP 01m43s rdf_count:18.44M rdf_speed:177.8k/sec edge_count:42.56M edge_speed:410.4k/sec
MAP 01m44s rdf_count:18.55M rdf_speed:177.0k/sec edge_count:42.81M edge_speed:408.7k/sec
[1]    1447 killed     ./bulkloader -r ~/dgraph-io/ldbc/snb_data_scale_1.rdf.gz -s 
```

This happened twice while trying to load a file with 40M RDF's. My machine has 16GB RAM. This happens around the time it is using 13GB.

**Comment by pawanrawal** [comment]
Reducing `j` to 4 helped and I was able to load the data. Also looks like it performs better when `j` is 4. 

Even at the end of the MAP phase I was getting
```
MAP 03m18s rdf_count:38.44M rdf_speed:193.2k/sec edge_count:100.8M edge_speed:506.8k/sec
MAP 03m19s rdf_count:38.44M rdf_speed:192.2k/sec edge_count:100.8M edge_speed:504.3k/sec
MAP 03m20s rdf_count:38.44M rdf_speed:191.3k/sec edge_count:100.8M edge_speed:501.8k/sec
```

which is more than the value we were getting when it got killed above.

**Comment by manishrjain** [comment]
I think this is because of swap being turned on. In the former case, high RAM usage is pushing things to swap space, which is causing more activity hence reducing the speed of intake.
