### ISSUE TITLE
Full text search not working properly in v0.8.1 when query against single-character string

### ISSUE THREAD

**Issue by zhicwu** [dgraph-io/dgraph#1454]
First of all, kudos to the great work! I'm evaluating dgraph with a few sample data. Everything works very well except a few glitches. Could you take a look when you have time?

Steps to reproduce the issue:

* schema and test data
```
mutation {
  schema {
    test_status: string @index(exact, fulltext) @count .
  }
  set {
    _:test_status_1 <test_status> "A" .
    _:test_status_2 <test_status> "B" .
  }
}
```
* query
```
{
  not_working(func: anyoftext(test_status, "A")) {
    test_status
  }
  works(func: eq(test_status, "A")) {
    test_status
  }
}
```
* actual response - first query returned nothing, which is not expected
```json
{
  "data": {
    "works": [
      {
        "_uid_": "0x11942",
        "test_status": "A"
      }
    ],
    "server_latency": {
      "json": "179µs",
      "total": "461µs",
      "parsing": "116µs",
      "processing": "160µs"
    }
  }
}
```

**Comment by pawanrawal** [comment]
Hi @zhicwu

We use bleve for tokenization. `a` is a stopword for English language(which is default) hence must not have been indexed.
https://github.com/blevesearch/bleve/blob/master/analysis/lang/en/stop_words_en.go

It should work well if you use a term index.

**Comment by zhicwu** [comment]
Interesting... didn't think about that. Will use term index instead.

**Comment by pawanrawal** [comment]
Btw it also doesn't work with other single letters. I suspect it's being truncated and not returned as a token by bleve. These are steps it goes through to get tokenized https://docs.dgraph.io/query-language/#full-text-search.
