### ISSUE TITLE
Remove RocksDB references in codebase

### ISSUE THREAD

**Issue by corysimmons** [dgraph-io/dgraph#1465]
Got interested in dgraph, saw you were using RocksDB somewhere, remembered FB PATENTS issue, [grepped codebase](https://github.com/dgraph-io/dgraph/search?utf8=%E2%9C%93&q=rocks&type=), saw you were using Badger now, but still lots of references to RocksDB throughout project.

You're not using Rocks anymore right?

**Comment by peterstace** [comment]
Correct, we're no longer using Rocks. Instead we're using our own (native Go) KV store called Badger. Since it's native, we don't have to deal with using cgo anymore. There are also some major performance advantages. See https://blog.dgraph.io/post/badger/

**Comment by manishrjain** [comment]
@corysimmons FWIW, RocksDB is under Apache 2.0 license, not BSD.

https://github.com/facebook/rocksdb/blob/master/LICENSE.Apache

**Comment by corysimmons** [comment]
@manishrjain Appreciate it, but Facebook has made their intentions clear to me. I'm just not going to use any of their stuff anymore. Who knows when they'll decide to PATENTS stuff and you'll be forced to rewrite your project (like Apache and Automattic are having to do now)...

**Comment by deepakjois** [comment]
I have cleaned up references to RocksDB in c15adb1e29740557e5d75f1f6a4e8e7faa8586c5

I found these by doing `rg -g '!vendor' -g '!dashboard' rocks` (using ripgrep). I assume there aren’t any other locations I missed out on.

Pls feel free to close.
