### ISSUE TITLE
Add upsert functionality to dgraphloader

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1468]
@jimanvlad mentioned that he would like to use upsert with dgraphloader. We could have a flag that allows you to upsert nodes by querying the server in case it doesn't find the xid => uid mapping in cache.

**Comment by manishrjain** [comment]
For XIDs, we should use the new upsert mutation, and store the resulting UID (new or old, doesn't matter) in the local XID -> UID mapping.

In fact, we should do this for every XID, only assigning UIDs locally for blank nodes in Dgraph loader.

**Comment by jimanvlad** [comment]
Yep, on the back of https://github.com/dgraph-io/dgraph/issues/1393

**Comment by lazharichir** [comment]
Can't wait for this as my initial RDF file (live loader) has a few duplicates and upsert would be ideal in this situation.

**Comment by manishrjain** [comment]
We're currently removing support for upsert. Instead, working on adding full support for transactions, which would provide upsert plus a lot more atomic functionality required by users. https://github.com/dgraph-io/dgraph/issues/1445

**Comment by jimanvlad** [comment]
@manishrjain When are transactions expected?

**Comment by lazharichir** [comment]
@manishrjain oh, so upserts are taking a step back just to make a better leap forward.. do you know when they're expected to start and when upserts are being removed?

**Comment by manishrjain** [comment]
Work on txns is going on as we speak. Our next release, which would be v0.9, would contain txns. Majority of the work would be testing and ensuring things are good with this major change, so we're expecting to release this in a month or so.

**Comment by mindreframer** [comment]
Thanks for making this happen! This is the single issue that stops me from using DGraph for any serious project.

**Comment by manishrjain** [comment]
Dgraph release https://github.com/dgraph-io/dgraph/releases/tag/v0.9.0 contains support for distributed ACID transactions.
