### ISSUE TITLE
Have a way to delete schema

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1473]
This is a continuing from https://discuss.dgraph.io/t/delete-a-predicate-from-schema-cont/1759/4.

Users should be able to delete the schema for a predicate if it has no data. Maybe we can have set and delete blocks as part of the schema block.  Right now we delete schema for a predicate when the user deletes a predicate and they didn't set the schema explicitly.

**Comment by calummoore** [comment]
This would be really useful when testing. In order to ensure my tests are isolated, I delete all my data and would like to also remove the schema.

**Comment by peterstace** [comment]
In fc2c509 , the schema for a predicate is now deleted when we do a drop for that predicate.
