### ISSUE TITLE
On empty string, internal error: ValueId cannot be zero

### ISSUE THREAD

**Issue by niemeyer** [dgraph-io/dgraph#1477]
Hello again,

I'm getting an error while attempting to add an edge from Go which is set to an empty string:

_rpc error: code = Unknown desc = failed to apply mutations error: internal error: ValueId cannot be zero_

The code looks like the typical edge insertion, I believe:
```
edge = node.Edge("svalue")
err = edge.SetValueString(v)
if err == nil {
        req.Set(edge)
}
if err != nil {
        return err
}
```
Hacking the value to be non-empty in those specific cases with `v = "-"` makes the code work fine.

Setting empty strings via the browser also works fine.

**Comment by pawanrawal** [comment]
Thanks for reporting the issue @niemeyer. I have pushed a fix as part of cb8a79fc7ea51b9043ee5d742df22312a47d2900 and it would be part of the next release.

**Comment by niemeyer** [comment]
Thanks for the quick fix @pawanrawal.

Reading the fix, do we have some special semantics by setting a string value with "_nil_"? What happens if that string happens to be found in the data itself?

**Comment by niemeyer** [comment]
Yes, that's indeed true as confirmed with code. I'm opening a separate issue about it.
