### ISSUE TITLE
Make clientDir optional for Go client.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1481]
User @willcj33 mentioned that he doesn't need use NodeXid and doesn't need the NodeBlank mapping, so he doesn't the functionality provided by badger in the client.

So if the user provides an empty client directory then we shouldn't the initialize badger and store the mappings.

**Comment by manishrjain** [comment]
But, it's hard to know whether there would be blank nodes or not upfront. We could consider not persisting these xid -> uid mappings, and keeping them in RAM -- they seem to work out for bulkloader.
