### ISSUE TITLE
dgraph OOM when import data

### ISSUE THREAD

**Issue by gzliudan** [dgraph-io/dgraph#1482]
Dgraph porcess is killed when I run:  dgraphloader -r  21million.rdf.gz

below is log from /var/log/message: 
Sep 18 16:26:34 kg kernel: dgraph invoked oom-killer: gfp_mask=0x280da, order=0, oom_score_adj=0
Sep 18 16:26:34 kg kernel: dgraph cpuset=/ mems_allowed=0
Sep 18 16:26:34 kg kernel: CPU: 0 PID: 1488 Comm: dgraph Not tainted 3.10.0-693.el7.x86_64 #1
Sep 18 16:26:34 kg kernel: [ 1328]     0  1328  3091817  1665706    4454   490826             0 dgraph
Sep 18 16:26:34 kg kernel: [ 1597]     0  1597   472979   216010     702    21115             0 dgraphloader
Sep 18 16:26:34 kg kernel: Out of memory: Kill process 1328 (dgraph) score 816 or sacrifice child
Sep 18 16:26:34 kg kernel: Killed process 1328 (dgraph) total-vm:12367268kB, anon-rss:6662824kB, file-rss:0kB, shmem-rss:0kB
Sep 18 16:30:26 kg kernel: dgraph invoked oom-killer: gfp_mask=0x280da, order=0, oom_score_adj=0
Sep 18 16:30:26 kg kernel: dgraph cpuset=/ mems_allowed=0
Sep 18 16:30:26 kg kernel: CPU: 0 PID: 8801 Comm: dgraph Not tainted 3.10.0-693.el7.x86_64 #1
Sep 18 16:30:26 kg kernel: [ 1668]     0  1668 17899915  1723184   11938   582173             0 dgraph
Sep 18 16:30:26 kg kernel: [ 9005]     0  9005   165214    20996     145        0             0 dgraphloader
Sep 18 16:30:26 kg kernel: Out of memory: Kill process 1668 (dgraph) score 875 or sacrifice child
Sep 18 16:30:26 kg kernel: Killed process 1668 (dgraph) total-vm:71599660kB, anon-rss:6892736kB, file-rss:0kB, shmem-rss:0kB

below is conf file:
export: export
gentlecommit: 0.33
idx: 1
groups: "0,1-5"
bindall: true
ui: /usr/local/dgraph/assets
port: 8080
grpc_port: 9080
workerport: 12345
memory_mb: 4096
trace: 0.33
p: /var/lib/dgraph/p
w: /var/lib/dgraph/w
debugmode: false

**Comment by janardhan1993** [comment]
@gzliudan What was your system configuration, ram ?

**Comment by gzliudan** [comment]
VM physical memory is 8G, I set memory_mb: 4096

**Comment by janardhan1993** [comment]
Are you using it on docker ?

**Comment by gzliudan** [comment]
not docker, It's a VM which has 4core and 8G memory, and is managed by virtualbox.

**Comment by janardhan1993** [comment]
What is the host OS you are using and what storage are you using (Hard disk or SSD).

Can you please try running the following command and share the output.
`time dd if=/dev/zero of=test.dat bs=1024 count=100000`

**Comment by gzliudan** [comment]
host OS is windows 10. SSD is NVMe SAMUNG MZVLW256. I will test the IO speed laster since I'm import data again after increased memory size to 16G.

**Comment by gzliudan** [comment]
time dd if=/dev/zero of=test.dat bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB) copied, 0.101645 s, 1.0 GB/s

real    0m0.106s
user    0m0.006s
sys     0m0.097s

**Comment by gzliudan** [comment]
dgraphloader -r 21million.rdf.gz

Dgraph version   : v0.8.1
Commit SHA-1     : 8ea4b0a5
Commit timestamp : 2017-09-18 10:56:37 +1000
Branch           : HEAD


Processing 21million.rdf.gz
Number of mutations run   : 21240
Number of RDFs processed  : 21239872
Time spent                : 15m6.317412394s
RDFs processed per second : 23443

**Comment by peterstace** [comment]
Looks like this is resolved.
