### ISSUE TITLE
Bulkloader storing extra uids when rdf's have lang tags.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1483]
Try loading these
```
<m.017n9>       <name>  "Blade Runner"@ca       .
<m.017n9>       <name>  "Blade Runner"@cs       .
<m.017n9>       <name>  "Blade Runner"@da       .
<m.017n9>       <name>  "Blade Runner"@de       .
<m.017n9>       <name>  "Blade Runner"@en       .
<m.017n9>       <name>  "Blade Runner"@es       .
```

with a schema
```
name: string @index(exact) .
```

And then try to inspect the badger keys.
1. The index key corresponding to `<Blade Runner, name>` has 6 uids which are all the same, whereas it should just have one.
2. The key corresponding to `<uid, _predicate_>` has 6 uids, though there should be only one corresponding to name.

**Comment by peterstace** [comment]
The root cause is the same for both 1 & 2: there's no de-duplication of keys.

**Comment by peterstace** [comment]
PR: #1485

**Comment by peterstace** [comment]
In master as of f33912c.
