### ISSUE TITLE
Feature request for calculating the length of edge path

### ISSUE THREAD

**Issue by matth3wga0** [dgraph-io/dgraph#1494]
With Neo4j, the query can be ordered by the length of the edge path, and return depth of the path in the query result, it's useful in some scenario, such as calculating the relationship rank.

In Dgraph, the depth is only a parameter in the recurse query, I think Dgraph can go further.
```
START n=node:index(Name=“Steven Spielberg”) 
MATCH path=n-->m--l<--o 
RETURN o
ORDER BY length(path);
```

**Comment by manishrjain** [comment]
We also seem to need this for LDBC benchmarks. So, might be worth investigating how much effort this would be.

**Comment by campoy** [comment]
Setting low priority since no other requests have been received regarding this issue.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8405). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
