### ISSUE TITLE
Support for OpenCypher

### ISSUE THREAD

**Issue by matth3wga0** [dgraph-io/dgraph#1495]
I really love the Cypher query language from Neo4j, and its specification is [open sourced](https://www.opencypher.org), will you guys consider the implementation?

**Comment by jimanvlad** [comment]
I think that's scheduled for post 1.0 (as seen here https://github.com/dgraph-io/dgraph/issues/1 ).

I'm also keen for Cypher support, as it would hopefully be super easy to replace our Neo4J backend (which generates cypher queries), to Dgraph.

**Comment by Textras** [comment]
Even Gremlin would be good for those Tinkerpop folks. But I'd start with Cypher.

**Comment by manishrjain** [comment]
Yeah, we want to start with Cypher first. We'll get the work going by early Q2.

**Comment by appinteractive** [comment]
Hey @manishrjain what’s the status for cypher support now one year later? Is it happening at all?

**Comment by kant111** [comment]
Cypher support would be ideal because some of the Streaming engines support Cypher. This way people can leverage ETL sources as well as graphdb's using Cypher.

**Comment by swelet** [comment]
Cypher support would really help many people looking for horizontal scalability transition from Neo4j.

**Comment by kant111** [comment]
@swelet why do you think people want to transition from Neo4J?

**Comment by swelet** [comment]
For horizontal scalability.

**Comment by kant111** [comment]
@swelet What's wrong with vertical scalability? Does it not satisfy the needs? If so, can you list the requirements?

**Comment by vldmarton** [comment]
Hello @manishrjain , any ETA on Cypher support? I'm also looking to migrate from Neo4j. Thanks

**Comment by wdroste** [comment]
@manishrjain would definitely be interested in this feature.

**Comment by maxresdefault** [comment]
@manishrjain Hi, any updates on this? I've been evaluating Graph DBs and I like the scalability and performance of Dgraph, but I'm still considering other options simply because I find Cypher to be _that_ good to work with. Cypher support would be a strong motivator for me and many others to use Dgraph.

**Comment by appinteractive** [comment]
The worst think for me currently is the missing support if labeled edges in the GraphQL implementation. It makes the whole graph aspect of the db a lot less useful.
