### ISSUE TITLE
Zero count nodes aren't found at query root

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1500]
E.g. for the following query:

```
mutation {
  schema {
    foo: string @count .
  }
  set {
    _:xxx <bar> "aoeu" .
  }
}
{
  q(func: eq(count(foo), 0)) {
    bar
  }
}
```

I would expect the query to either return a single node (with the "aoeu" field), or an error message saying that there isn't support for using zero count index. Currently, the query just returns no results.

**Comment by pawanrawal** [comment]
This is expected. Only if an `S P` had a non-zero count and then upon a deletion, the count went to zero would it be indexed with zero count.

**Comment by peterstace** [comment]
I can see how it could be expected behaviour for people who know how the count indexing works internally for Dgraph.

But regular users won't know about that (and shouldn't have to know in my opinion). If we can't accurately calculate a zero count index (e.g. for performance reasons or whatever other reason), then I think it's best to tell the user via an error message when they try to use the count index with zero. If we just return an empty result set (as we do now), then this looks the same to the user as if there were *no* `SP`s with zero count.

**Comment by manishrjain** [comment]
We shouldn't have zero counts. That information doesn't sound like it would be complete.

**Comment by peterstace** [comment]
@manishrjain , in that case I think it's best to give an error to the user if they request a zero count. If we're in agreement there, I can make that change.

**Comment by manishrjain** [comment]
Yeah, sounds good to me. Also check with @pawanrawal .

**Comment by pawanrawal** [comment]
Let's return an error for now as the current behaviour is a bit ambiguous.

**Comment by peterstace** [comment]
In master as of 1758b3a - we no longer track zero count indexes (at all, even partially). We also give an error if the query explicitly asks for zero count index, or would only contain zero count index (e.g. asks for count less than 1).
