### ISSUE TITLE
Support variables in recurse query

### ISSUE THREAD

**Issue by matth3wga0** [dgraph-io/dgraph#1501]
The normal recurse query returns all of the edges from `0x1` vertex, works as expected.
```
mutation {
  set {
     _:a <edge> <0x1> .
     _:b <edge> <0x1> .
     _:c <edge> _:a .
  }
}

{
  recurse(func: uid(0x1)) {
    ~edge
  }
}

# returns a, b, c
```
But if define variables in the recurse query, only returns the first depth nodes.
```
{
  recurse(func: uid(0x1)) {
    x as ~edge
  }
  
 node(func: uid(x)) {
    _uid_
  }
}

# returns a,b but c
```

**Comment by pawanrawal** [comment]
This was done and merged to master. It would be part of the next release.
