### ISSUE TITLE
Enable expand on recursing query

### ISSUE THREAD

**Issue by matth3wga0** [dgraph-io/dgraph#1507]
The current version (0.8.2) disabled the `expand` predicate on the recursing query to prevent loading large datasets, it make sense and smart people won't do this, but someone may need this in specific scenario.

So I suggest to enable this feature with limitations, as depth parameter is always required if expand predicate in recursing query.
```
{
  recurse(func: uid(0x1), depth: 3) {
    expand(_all_)
  }
}
```

**Comment by pawanrawal** [comment]
This has been merged to master and would be part of the next release.
