### ISSUE TITLE
bulkloader cannot deal with compressed schemas

### ISSUE THREAD

**Issue by niemeyer** [dgraph-io/dgraph#1509]
Would be nice to make sure that bulkloader can easily take in what was generated by the export routine, to simplify automated migration procedures. Right now it cannot deal with the rdf.gz schema file generated by /admin/export. It's easy to uncompress, but it's even easier not to.

**Comment by peterstace** [comment]
PR #1511

**Comment by peterstace** [comment]
In master as of c37e05e
