### ISSUE TITLE
Proposal on default value of schema index

### ISSUE THREAD

**Issue by matth3wga0** [dgraph-io/dgraph#1520]
Dgraph should support default value while creating index, my prososal as below:

```
mutation {
  schema {
    name: string @index(exact) @default("Matt") .
  }
}
```

**Comment by manishrjain** [comment]
Can you expand a bit more about the purpose of default? Should it provide a default value for names which don't exist in the graph? How does creating an index play into this default?

Most likely, this won't be added, but I just want to make sure I understand the motivation.

**Comment by matth3wga0** [comment]
Maybe I was meaning the default value of edge facets.

```
mutation {
  schema {
    name: string @index(exact) @default(locale: "en") .
  }
}
```

**Comment by manishrjain** [comment]
If there's a need to add a default or locale to a value, it should be handled at the client side. It would make things unnecessarily complex to provide this at server side.
