### ISSUE TITLE
Drop all data from Dgraph

### ISSUE THREAD

**Issue by calummoore** [dgraph-io/dgraph#1522]
For testing purposes, it would be useful to be able to delete all data from dgraph, so we can make sure tests are isolated.

At the moment, I have to get the schema:
```
schema {
  predicate
}
```

And then loop through each of the responses (excl system predicates) and create a delete mutation:
```
mutation {
  delete {
    * <returned_predicate> * .
    ... and so on
  }
}
```

Could we not just have a delete all mutation?
```
mutation {
  delete {
    * * * .
  }
}
```

This combined [with this other issue](https://github.com/dgraph-io/dgraph/issues/1473) would allow us to reset the entire DB.

**Comment by ddibiase** [comment]
You can just delete the p and w folders as I'm doing right now, but I do agree would be handy to have this as a query feature.

**Comment by manishrjain** [comment]
We can build a drop all instruction.

**Comment by peterstace** [comment]
Planning to add a drop-all instruction to GRPC. We can just iterate over all keys and delete them, effectively removing all data and schemas.

**Comment by peterstace** [comment]
PR: #1547

**Comment by peterstace** [comment]
Merged to master in 33154f4

**Comment by felixfbecker** [comment]
When I execute  `{"drop_all": true}`, I still see metrics for old predicates under http://localhost:8080/debug/vars. How can I reset those?

**Comment by gitlw** [comment]
@felixfbecker In our latest code, the dgraph_predicate_stats are removed from /debug/vars
Can you please explain your use case in a little more details, so that we can decide whether this is a must-have feature? If not, I guess it's not worth fixing this problem in the current release.
Let us know, thanks!

**Comment by felixfbecker** [comment]
@gitlw I was looking to get a sense of how many triplets the DB contains overall. This can be a useful metric for a variety of things, measuring how much data users have added overall and how fast that is growing (reporting some numbers), how well DGraph performs with Nx more nodes/edges compared to before, whether it's reasonable to provision more resources, how long till we'll likely hit scaling limits. It is not a hard requirement, but I would find it a nice thing to have.
