### ISSUE TITLE
"checkpwd" breaks with "expand(_all_)"

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#1526]
There's a way to filter checkpwd?

`Attribute "password" of type password cannot be fetched`

**Comment by pawanrawal** [comment]
Thanks for the report @MichelDiz. Yes, password should be filtered.

**Comment by MichelDiz** [comment]
@pawanrawal I thought a little bit about that bug. Filtering would be great, but could you add an option to execute the "expand (_all_)" if we pass a password? For example, passing the password through a variable.

I believe it would be more useful for this "checkpwd" function we could bind the client password through a function up to the query variable.

Cheers

**Comment by pawanrawal** [comment]
Yeah, I think we can exclude password by default from `expand(_all_)` so that error is not returned. And if the user wants to check it then they can supply it like you did.
