### ISSUE TITLE
Passing int via gRPC throws parsing error

### ISSUE THREAD

**Issue by ddibiase** [dgraph-io/dgraph#1527]
I'm sending the following RDF as a mutation. Apologies that it's in JSON, this is how my gRPC client accepts the values.
```
{
    "subject": "_:venue_dec253d4-68df-470b-b8fc-d663a7fa4704",
    "predicate": "Capacity",
    "object_value": {
        "int_val": 18230
    }
}
```
The error I receive it:
```
Unhandled rejection Error: failed to apply mutations error: internal error: strconv.ParseInt: parsing "\\D\x00\x00\x00\x00\x00\x00": invalid syntax
```
Note that the schema defines `Capacity` as an int. Speaking to pawan on Slack, it's either a bug or a documentation issue.

**Comment by janardhan1993** [comment]
@ddibiase 
You have to specify the object_type along with object_value. Based on the specified object_value we try to parse the value.

Here is a lis of object_types. We will update the documentation for the same.

```
default_val = 1;
 bytes_val = 2;
 int_val = 3;
bool_val = 4;
str_val = 5;
double_val = 6;
geo_val = 7;  // Geo data in WKB format
date_val = 8;
datetime_val = 9;
password_val = 10;
uid_val=11;
```

The input can have different type compared to the schema and we store it in whichever format the user wants us to store. Before storing we check whether the value is compatible with schema type, if it's not then we throw error.

Example: You can have the schema set as int, but if you give us float values in the input we will store it as float but while reading it it would be converted to schema type(in this case float is converted to int) and processed. Later if you want to change the schema to float, you would get whatever you stored.
You could even give the input as string and we will try to parse it as int before storing. If parsing is successful we would still store it as string.

**Comment by pawanrawal** [comment]
We should see if we can get the ObjectType based on the ObjectValue that the user set so that they don't have to pass it in.

**Comment by pawanrawal** [comment]
This looks possible. Infact, we already do it https://github.com/dgraph-io/dgraph/blob/master/gql/mutation.go#L158 but then later just use the `ObjectType`. We should just infer ObjectType from ObjectValue for mutations coming via gRPC.

**Comment by pawanrawal** [comment]
ObjectType has been removed from the NQuad struct as this information can be derived from the ObjectValue. The corresponding change has been merged to master. From the next release, there would be no need to specify the ObjectType.
