### ISSUE TITLE
Checking the existence of a node

### ISSUE THREAD

**Issue by ddibiase** [dgraph-io/dgraph#1542]
I was chatting with pawan on Slack and we were discussing how to consistency determine if a value exists via a query. Going back to an example I've used a few times:
```
{
  CheckUsername(func: has(Account)) @filter(eq(Username, "foobar")) {
    Exists : count(Email)
  }
  CheckEmail(func: has(Account)) @filter(eq(Email, "foobar@gmail.com")) {
    Exists : count(Account)
  }
}
```
What I'd like to check is the existence of a record that has the Username or Email attached to an account node. I recommended adding exists() or turning has() into a method that would turn true/false. I could easily do this with cond() and pass back true/false but the issue is that the body wont return a value if you haven't filtered an existing record.

What would be ideal is something similar to this:
```
{
  CheckAccount(func: has(Account)) {
    UsernameExists : exists(eq(Username, "foobar"))
    EmailExists : exists(eq(Email, "foobar@gmail.com"))
  }
}
```
That way the response will always return two properties with true/false booleans. The syntax I'm proposing may not totally make sense but it communicates the concept. Perhaps there's a better way to structure the query with the current language tools, I just can't seem to easily factor it.

Keep in mind this would be a consistent edge case for anyone creating an app-based authentication engine on top of Dgraph. So it seems pretty relevant.

**Comment by pawanrawal** [comment]
```
{
  CheckAccount(func: has(Account)) {
    UsernameExists : exists(eq(Username, "foobar"))
    EmailExists : exists(eq(Email, "foobar@gmail.com"))
  }
}
```

Regarding the above query, you could have two query blocks and check the length of the response returned. Now we always return the block even if it doesn't return any records. 
```
{
  CheckUsername(func: has(Account)) @filter(eq(Username, "foobar")) {
    Username
  }
  CheckEmail(func: has(Account)) @filter(eq(Email, "foobar@gmail.com")) {
     Email
  }
}
```

Then in the response, you could check the length of the response returned under `CheckUsername` and `CheckEmail`. Would that work for you?

**Comment by ddibiase** [comment]
Yeah that makes sense. From a performance perspective, wouldn't it be more efficient to allow for a true/false return? I realize that this is so minuscule of a performance consideration but if we had the option of sending less data over the wire, wouldn't that be a preferred option? :-)

Aside from that, yeah this totally works as an option.

**Comment by pawanrawal** [comment]
How about the below?

```
{
  CheckUsername(func: has(Account)) @filter(eq(Username, "foobar")) {
    count()
  }
  CheckEmail(func: has(Account)) @filter(eq(Email, "foobar@gmail.com")) {
     count()
  }
}
```

**Comment by ddibiase** [comment]
That's much better. Awesome!
