### ISSUE TITLE
Datalog querying?

### ISSUE THREAD

**Issue by samuell** [dgraph-io/dgraph#1555]
As DGraph is still new, and query language is in the works, I wanted to raise the issue:

Any plans for supporting datalog as the query language? It is AFAIK pretty close to the holy grail in graph querying, and definitely state of the art, and is supported by a few modern tools like Rich Hickey's [Datomic](http://www.datomic.com/) database and [Cascalog](http://cascalog.org/) Hadoop querying system.

What I like most about datalog is how it's support for named queries (similar to SQL Views, but way more flexible and useful in practice) makes it possible to build up queries that are based upon other queries ... and in this way basically build up a "vocabulary" of queries, since the query name becomes a term which can be used to retrieve a certain class of stuff. So it is essentially a way to put data in a class, but based on its properties rather than based on a strict schema or anything.

What this ultimately gives you is increased modeling power,  since you can capture low-level concepts into queries, and then work with those when building up "higher level" queries, etc etc.

And all of this with one very simple language.

Would be so awesome to have support for this in a Go-based system!

**Comment by peterstace** [comment]
We currently don't have any plans to support datalog as a query language. It looks interesting though and used in some other graph products - Profium and Stardog (any others?).

'Building up' queries from smaller queries seems like a very nice feature to have for datasets with complex relationships (many predicates)e

If we decide to implement something like datalog, it would be post v1.0.

**Comment by samuell** [comment]
@peterstace Aight, thanks for the info! Cheers
