### ISSUE TITLE
question about your solution

### ISSUE THREAD

**Issue by publicocean0** [dgraph-io/dgraph#1557]
hi i met this project casually.
I saw to to use rocksdb KV persistence engine.
But how do you save the links ? 
do you save all links per node inside the rocksdb data value for specific node (data and links embedded in the same KV )or do you save links in specific space?

**Comment by peterstace** [comment]
We no longer use RocksDB. Instead we are using our own [Badger](https://github.com/dgraph-io/badger/) for KV persistence. We recently wrote a [blog post](https://blog.dgraph.io/post/badger/) about it.

We store the links (also known as edges) in posting lists. Posting lists are split up per subject-predicate with each being stored in its own key/value. So the data associated with a single node is spread out between different key/values in the KV store. In fact, when Dgraph is set up to run as a cluster (multiple dgraph instances working together), data for a single node might not even be on the same physical machine.

**Comment by publicocean0** [comment]
wow , to realize a LSM is not trial. It requites time and energies. I saw now you are part of a company. Sorry just a last question. All code is opensource. But how does your company earn if all is open-source?

**Comment by manishrjain** [comment]
We have plans to add commercial features past v1.0 release.
