### ISSUE TITLE
Add @distance for geo

### ISSUE THREAD

**Issue by davedbase** [dgraph-io/dgraph#1559]
It would be really great if there was a function to call and return distance between points or polygons. ie. @distance(PointA, PointB). If it were to return the result in meters that could be really, really handy!

**Comment by paul-ylz** [comment]
Agreed, this would be awesome to facilitate sorting geo queries by distance to a particular point.

**Comment by wildan2711** [comment]
Just came across the need for this feature, in tandem with the `near`, that would be cool.

**Comment by wildroco** [comment]
any updates here?

I want to sort nodes by distance from fixed location. Is it possible without distance function?

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8406). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
