### ISSUE TITLE
SetObject and client.Unmarshal should use json tag

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1560]
User Bob on Slack mentioned that he would like the flexibility to have different keys for dgraph and for json marshalling. This is especially handy for the `Id` as dgraph calls it `_uid_` whereas his clients would prefer it to be `id`.  So we should use the value defined as part of `dgraph` key and not the `json` key while marshalling the object.

**Comment by manishrjain** [comment]
Would make sense to use Dgraph key if available, otherwise use JSON key. That'd be better than enforcing a user to specify both.

**Comment by pawanrawal** [comment]
We have decided that we are going to get rid of the `dgraph` key and just use the `json` key for both marshalling and unmarshalling because
1. We are using `json.Marshal` under the hood in `SetObject` and `DeleteObject`. Having our own Marshal function would just mean adding a lot of unnecessary code to solve a small problem.
2. Users don't have to define another dgraph key and can just use the json key.

The only problem seems to be that user doesn't have control over the name of the `_uid_` field. We can look into adding the option to specify an alias for `_uid_` through the schema and then all queries would take that and responses could return the id under that key. Also, `SetObject` and `DeleteObject` could look for that key.

@sporkmonger ^

**Comment by pawanrawal** [comment]
This change is in master.
