### ISSUE TITLE
Run go-fuzz for gql and query package

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1566]
https://github.com/dvyukov/go-fuzz generates random inputs and calls the code with those inputs. This can help find invalid inputs that might cause a crash. It takes an initial corpus which could be the queries from our tests.

https://github.com/dgraph-io/dgraph/pull/1565 helped find some such issues. It would be nice to run this tool for a longer duration for `gql` and `query` package so that we can find more such issues.

**Comment by gitlw** [comment]
Closing this issue as the go-fuzz tool has been included in the dgraph repo.
