### ISSUE TITLE
dgraph-live-loader is slow when starting two dgraphzero nodes and one dgraph node

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1571]
Start two dgraphzero nodes and a dgraph instance.
```
./dgraphzero --id 1
./dgraphzero -id 2 -peer 127.0.0.1:8888 -w w2 -port 8890
./dgraph -memory_mb 10000 -peer 127.0.0.1:8888
```

Try to load 21 million data with schema

```
➜  dgraph-live-loader git:(master) ✗ ./dgraph-live-loader -r ../../../benchmarks/data/21million.rdf.gz -s ../../../benchmarks/data/21million.schema

Processing ../../../benchmarks/data/21million.schema

Processing ../../../benchmarks/data/21million.rdf.gz
[Request:      9] Total RDFs done:     9000 RDFs per second:     161 Time Elapsed: 56s 
```

The starting rate is very low and it keeps on going down. This doesn't happen when only one dgraphzero node is running.

**Comment by manishrjain** [comment]
Is this because of Raft?

**Comment by janardhan1993** [comment]
Leader changes in zero were not getting updated in state. AssignUids from client was going to wrong server(it was not the leader). zero was throwing error since it was not the leader and client got stuck.
