### ISSUE TITLE
Export prints keys for predicates even after they have been moved to some other node

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1575]
Say a predicate moved from Node A => B and you try to do an export after the move but before deletion happens on the first node then the export prints duplicate data (corresponding to the predicate) on the two nodes. This is an issue because export would have blank nodes and the user might end up with duplicate data when he imports these.

**Comment by manishrjain** [comment]
Export needs to be coordinated via dgraph zero.

**Comment by pawanrawal** [comment]
Fixed via 7be91b513734903053c64c000212b2c38fb539e0
