### ISSUE TITLE
Share XID map between bulk loader and live loader

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1578]
The XID to UID map in the bulk loader has some performance improvements over the one in live loader. It would be nice to share the map code between the two loaders.

We would need to make some modifications to the map though since the live loader needs some extra features:

The only extra feature we would need to add to the map is allowing it to give a single new unmapped UID. This is easy to add, just increment the global lease and give that value.

Another thing to consider is checkpoints, which the live loader integrates into its XID map. We probably don't want to add checkpoints explicitly to the UID map (doesn't make sense to have them there...). We could instead just store the checkpoints in the same badger. We still need a way to separate the keys though - user meta would be a quick and easy way to do this.

**Comment by manishrjain** [comment]
I agree. I think anything that's specific to these loaders can be done directly via exposing Badger. No need to provide a unified viewfront. Just the intersected list of features should be exposed via common API.

**Comment by peterstace** [comment]
PR #1622

**Comment by peterstace** [comment]
In master as of 879d630
