### ISSUE TITLE
It is unclear about configuring groups.conf 

### ISSUE THREAD

**Issue by jzhu077** [dgraph-io/dgraph#1592]
[data-sharding](https://docs.dgraph.io/master/deploy#data-sharding )
Introduced the groups.conf but I was confused about the configuration. 
1. `default: fp % N + k, where N = number of shards you want, and k = starting shard id. ` Does N also reference to the number of groups that are sharding the data?
2. In this example:
```
A valid groups.conf is:

// Matching is by prefix when * is used, and by equality otherwise

1: type.object.name
2: type.object.name*, film.performance.*

// Default formula for getting group where fp is the fingerprint of a predicate.
default: fp % 10 + 2
COPY
For this groups.conf:

Predicate type.object.name is assigned to group 1.
Any predicate with prefix type.object.name and film.performance. will be assigned to group 2.
type.object.name belongs to group 1 and not 2 despite matching both, because 1 is lower than 2.
The remaining predicates are assigned by the formula: fingerprint(predicate) % 10 + 2, and thus occupy groups [2, 3, 4, 5, 6, 7, 8, 9, 10, 11].
Group 2 will serve predicates matching the specified prefixes and those set by the default rule.
```
Does that means there are 12 groups in total??? 
What is default rule and where can I find it?  e.g. `Group 2 will serve predicates matching the specified prefixes and those set by the default rule.`

**Comment by pawanrawal** [comment]
Hey @jzhu077 

We have heard your feedback. From next release which should be out today/tomorrow you won't have to specify a group config. Dgraph would handle distribution of data for you based on the size of predicates.

**Comment by jzhu077** [comment]
@pawanrawal cheers. I will wait for that :)

**Comment by pawanrawal** [comment]
`v0.8.3` is out. Now you just start [`dgraphzero`](https://docs.dgraph.io/deploy/#dgraphzero-1) and it manages the cluster for you.
