### ISSUE TITLE
Add examples for User authentication

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#1600]
We support storing encrypted passwords. We should probably add a page titled how to do various things with Dgraph, one of them should be about user authentication (or could be part of the current graph query language doc), where we explain how to do password storage and verification for a user.

**Comment by peterstace** [comment]
There's an example of how to do this in the how-tos section of the docs. https://docs.dgraph.io/howto/

**Comment by peterstace** [comment]
I added a few extra details to the how-to for a login system, I think that covers everything needed here.
