### ISSUE TITLE
can't set -expand_edges false in bulkloader 

### ISSUE THREAD

**Issue by tamerh** [dgraph-io/dgraph#1609]
Hi,
in new release 0.8.3 bulkloader looks much better but it seems i can't set -expand_edges parameter to false. by default value is true and i can't set to false when i try "-expand_edges false". 
am i missing something?

Thanks
Tamer

**Comment by pawanrawal** [comment]
Hi @tamerh 

You need to set like `expand_edges=false`

From https://golang.org/pkg/flag/, the syntax that you used doesn't work for boolean flags.
```
-flag x  // non-boolean flags only
```

**Comment by tamerh** [comment]
thanks a lot.
