### ISSUE TITLE
Make Linearizability optional using a request level flag

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1612]
Queries can become slow when a lot of data is being loaded. Users can request for linearizability based on a flag in the request.

**Comment by manishrjain** [comment]
We should just take the whole raft stuff out of Dgraph. Doing master-slave replication is straightforward, avoids code and design complexity and the performance hits to both reads and writes caused by consensus. I'll try it out in the next few weeks.

**Comment by manishrjain** [comment]
Okay. Decided to keep consistent replication, it's clearly amazing for the end user. And made Lin reads something that are controlled at the client level, which is more performant than doing it globally at the server.
