### ISSUE TITLE
Restarting dgraph fails if tried within 10 seconds of stopping it

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1613]
This is the error message it gets from dgraphzero

```
2017/10/10 02:04:18 groups.go:109: Error while connecting with group zero: rpc error: code = Unknown desc = Node is already part of group
```

Its because dgraphzero does a health check every 10 seconds to dgraph nodes. So since the dgraph node was restarted before 10 seconds, dgraphzero thinks the old node still exists and hence the error.

We should fix this, either by storing the `id` in the dgraph nodes or by some other mechanism.

**Comment by manishrjain** [comment]
Assuming Dgraph server provided the same id, if the server has the same IP and port, then it should be able to reconnect within the health check period.

**Comment by manishrjain** [comment]
This was fixed. https://github.com/dgraph-io/dgraph/commit/8ec25854f136c331f5be90ca8997a65be5eac911
