### ISSUE TITLE
It is unclear what I should configure the flag "my" to, when it is set up in a container

### ISSUE THREAD

**Issue by jzhu077** [dgraph-io/dgraph#1615]
`dgraphzero -w wz --bindall=true --my "ip-address-others-should-access-me-at"`
In the dgraphzero setup above passes an IP address as flag "my", but what if I am not sure what I should put down there if I running a bunch of containers(dgraph intances) in GKE. 

Or is it possible to run all instances in one container?

Also https://docs.dgraph.io/get-started/ does not mention the `--my` flag as https://docs.dgraph.io/deploy/#dgraphzero-1 so which is preferred?

**Comment by janardhan1993** [comment]
--my flag should point to the ip address and port. By default dgraphzero listens on port 8888.
It's possible to run all instances in one container by specifying different ports and p and w directory. but we wouldn't recommend it. You should keep the different instances isolated.
