### ISSUE TITLE
Query for total number of nodes

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1619]
Lots of users have asked for this feature (or some variant of it). New users may get a bad impression of Dgraph since it cannot currently support 'basic' operations that other graph databases have. The answer that a 'count all nodes' function doesn't scale well may not be satisfactory for people who don't understand the technical details as to why this is the case.

One solution that @pawanrawal and I discussed:

- Use the `_predicate_` predicate to find all nodes. Then we can just return the count of those nodes.

**Comment by manishrjain** [comment]
Sounds good.

**Comment by SrinathG910** [comment]
Current version is "v1.0.6", is this feature implemented or planned?

**Comment by manishrjain** [comment]
You should be able to run something like this to get the total number of nodes.

```
{ total(func: (has, "_predicate_") { count(uid) } }
```

@kdsgambhir : Can you test this, and document this in how to section?

**Comment by kdsgambhir** [comment]
This query gives you the total count of nodes in your data: 
```
{
  total (func: has (_predicate_) ) {
    count(uid)
  }
} 
```

**Comment by manishrjain** [comment]
Being done in Ratel.

**Comment by koenvanderveen** [comment]
How is this done in v1.1? Since _predicate_ doesnt exist anymore.

**Comment by martinmr** [comment]
You could assign all you nodes with a dummy type, and then run.

```
{
  total (func: eq (dgraph.type, DummyType) ) {
    count(uid)
  }
} 
```
