### ISSUE TITLE
dgraphzero address in Docker container

### ISSUE THREAD

**Issue by Pasquinell** [dgraph-io/dgraph#1629]
When I run:

`docker run -it -p 8080:8080 -v ~/dgraph:/dgraph --name dgraph dgraph/dgraph dgraph --bindall=true --memory_mb 2048`

I get this message in the terminal window

```
Dgraph version   : v0.8.3
Commit SHA-1     : 68e482a3
Commit timestamp : 2017-10-10 15:54:57 +1100
Branch           : HEAD

2017/10/12 04:42:33 Providing dgraphzero address is mandatory.
github.com/dgraph-io/dgraph/x.AssertTruef
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:67
github.com/dgraph-io/dgraph/worker.StartRaftNodes
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/groups.go:92
runtime.goexit
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/asm_amd64.s:2337

```

So I can't follow the tutorial because I am getting this message

`Error: Is Dgraph running locally?`

**Comment by pawanrawal** [comment]
Hey @Pasquinell 

Thanks for reporting this. I have fixed the instructions. Can you please try again? 

If you get an error that container name "/dgraph" is already in use, then try to remove it `docker rm dgraph` before trying the command.

**Comment by Pasquinell** [comment]
@pawanrawal 
Now works only by executing 
`docker run -it -p 8080:8080 -p 9080:9080 -v ~/dgraph:/dgraph --name dgraph dgraph/dgraph dgraphzero -w zw`
first and 
`docker exec -it dgraph dgraph --bindall=true --memory_mb 2048 -peer 127.0.0.1:8888`
in another terminal window. Is that ok? If so, the instructions should aware that.

Great work by the way!

**Comment by pawanrawal** [comment]
Yeah, that's right it has to be run in another window and that's why it's on a different line. I will add a comment though.
