### ISSUE TITLE
Fulltext search with 'alloftext' functions sometimes fail

### ISSUE THREAD

**Issue by johnciocoiu** [dgraph-io/dgraph#1632]
Dgraph seems to have an issue:

Doing the following query **doesn't** respond any data:
```{
      	things(func: alloftext(schema.testString, "patc")) {
            expand(_all_) {
                expand(_all_)
            }
        }
    }
```

Doing the following query **does** respond data:
```{
      	things(func: alloftext(schema.testString, "patch")) {
            expand(_all_) {
                expand(_all_)
            }
        }
    }
```
_The only difference is 'patc' and 'patch' as search text_

But, according to the docs, when searching with _alloftext_, every node has to be found with the predicate `schema.testString` that contains the given string.

The `schema.testString` edge of several nodes in the database contains `New name patched!`, so:

1. These things should be found when using `patc` as search term
2. These things should be found when using `patch` as search term
3. These things should be found when using `patched` as search term

Case 1 fails, case 2 and 3 succeed. In all cases, the search term is part of the word `patched`.

**Comment by peterstace** [comment]
The documentation for using full-text search is here: https://docs.dgraph.io/query-language/#full-text-search

I'm curious where did you find the documentation you quoted? It doesn't appear to be correct, and I couldn't find it at docs.dgraph.io anywhere (if there's bad documentation floating around somewhere, we'd like to fix it).

In particular, `New name patched!` stems down to `new name patch`, which explains why `patc` isn't showing up anything.

To see how stemming works interactively, there are a few different stemming calculators available online, e.g. http://9ol.es/porter_js_demo.html

**Comment by johnciocoiu** [comment]
I think it may be more my interpretation of the documentation, but in the documentation is mentioned:

_Apply full text search with stemming and stop words to find **strings matching all or any of the given text**._ 

This suggests that you can also find sub-strings of indexed words.

Is it correct that the only way to search on sub-strings is with regex?

**Comment by peterstace** [comment]
> Is it correct that the only way to search on sub-strings is with regex?

Yes, that's correct.
