### ISSUE TITLE
go client broken

### ISSUE THREAD

**Issue by advancedlogic** [dgraph-io/dgraph#1637]
Hi,
just recloned on another computer my project and now protos.Response looks broken ... 
This is the error when I try to build the project:

`type *protos.Response has no field or method N`

Any suggestions?
Thanks

**Comment by manishrjain** [comment]
Please don't use the client from master. We're making huge changes to it, so master would stay broken for a bit. Use the client from the latest release.

**Comment by advancedlogic** [comment]
thanks :)
