### ISSUE TITLE
Dgraph-live-loader throwing an error when importing string values containing quotes?

### ISSUE THREAD

**Issue by lazharichir** [dgraph-io/dgraph#1638]
I have a small program generating my initial RDFs to insert in Dgraph using dgraph-live-loader. It works unless the predicate value contains a quote or slash? I run 0.8.3 on MacOS.

For example the below:
```
_:1051 <wikipedia.name> "Alexis_Carrel" .
_:1051 <label> "Alexis Carrel"@en .
_:1054 <xid> "All_Saints\'_Day" .
_:1054 <kind> "topic" .
_:1054 <wikipedia.name> "All_Saints\'_Day" .
_:1054 <label> "All Saints\' Day"@en .
```

Will trigger:
```
2017/10/15 15:57:14 While processing file Error while parsing RDF: while unquoting error: invalid syntax, on line:1009 _:1054 <xid> "All_Saints\'_Day" .
```
How to import these values as is, with the quote(s)?

**Comment by lazharichir** [comment]
Fixed - only escaped double quotes

**Comment by peterstace** [comment]
For anyone wondering about the technical reason for not having to escape apostrophes:

Dgraph uses `strconv.Unquote` when parsing strings in RDFs. So the RDFs should follow Go (interpreted) literal syntax. https://golang.org/ref/spec#String_literals
