### ISSUE TITLE
dgraphassigner crashed with numCpu>=2

### ISSUE THREAD

**Issue by jchiu0** [dgraph-io/dgraph#164]
My config:
8G ram, Macbook Pro
go version go1.6.3 darwin/amd64

We clear away the "u" directory and ran the following command:
dgraphassigner --numInstances 1 --instanceIdx 0 --rdfgzips rdf-films.gz --uids u --numCpu=2

After getting to:
INFO[0025] Counters                                      ignored=0 len_cnq=9744 package=loader parsed=621296 pending=12740 processed=608556 read=631180
INFO[0026] Counters                                      ignored=0 len_cnq=10000 package=loader parsed=643131 pending=12997 processed=630134 read=653132

We got errors beginning with:

runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7fff91ed4f06 m=2

goroutine 0 [idle]:

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc82013e90c)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc82013e900)
	/usr/local/Cellar/go/1.6.3/libexec/src/sync/waitgroup.go:127 +0xb4
github.com/dgraph-io/dgraph/loader.AssignUids(0x5680550, 0xc820162000, 0x0, 0x1, 0x0, 0x0, 0x0)
	/Users/jchiu/go/src/github.com/dgraph-io/dgraph/loader/loader.go:321 +0x2ac
main.main()
	/Users/jchiu/go/src/github.com/dgraph-io/dgraph/cmd/dgraphassigner/main.go:93 +0x1520

......

**Comment by kostub** [comment]
Fixed with commit 8f54f52.  

See 
https://wiki.dgraph.io/Beginners_Guide#Dgraph_assigner_fails_with_.27runtime.2Fcgo:_pthread_create_failed:_Resource_temporarily_unavailable.27_error

to resolve.
