### ISSUE TITLE
Possibility For Lighter Golang Client

### ISSUE THREAD

**Issue by willcj33** [dgraph-io/dgraph#1643]
It would be nice if the Golang client didn't have so many dependencies. It seems like some may be able to be trimmed out. All I really want is the protos, and the client just to make the call to the server. We use Glide for our dep management and it just seems like it takes very long, and it brings in a lot of stuff.

**Comment by manishrjain** [comment]
We have stripped out the Go client pretty considerably in master. You can take a look at the client in master for an idea of where it's going.

**Comment by pawanrawal** [comment]
It should be super lite with 99cac529e608efc1c879e2195a64b567c1b6d145.
