### ISSUE TITLE
Recurse query doesn't show any predicate (but shows facet) on last depth level?

### ISSUE THREAD

**Issue by lazharichir** [dgraph-io/dgraph#1648]
The below query (with or without `@ignorereflex` after further tests) seems to always show the right predicates until we reach the last level where it then shows the facets (`_`) but no other predicates like other nodes.

I used `first: 5` just to limit the returned dataset otherwise it would be very long, but without it the problem remains the exact same.
```
{
    recurse( func: eq(xid, "Pen"), depth: 2 ) @ignorereflex {
    	xid
    	_uid_
    	related (first:5) @facets(weight)
    }
}
```
Results in:
```
{
    "data": {
        "recurse": [
            {
                "xid": "Pen",
                "_uid_": "0x15ded8",
                "related": [
                    {
                        "xid": "Ancient_Egypt",
                        "_uid_": "0x155d53",
                        "@facets": {
                            "_": {
                                "weight": 0.720318
                            }
                        }
                    },
                    {
                        "xid": "Austria-Hungary",
                        "_uid_": "0x156178",
                        "@facets": {
                            "_": {
                                "weight": 0.249904
                            }
                        }
                    },
                    {
                        "xid": "Brass",
                        "_uid_": "0x156205",
                        "@facets": {
                            "_": {
                                "weight": 0.99991
                            }
                        }
                    },
                    {
                        "xid": "Ball",
                        "_uid_": "0x1562ff",
                        "@facets": {
                            "_": {
                                "weight": 0.397426
                            }
                        }
                    },
                    {
                        "xid": "Ballpoint_pen",
                        "_uid_": "0x15643b",
                        "related": [
                            {
                                "@facets": {
                                    "_": {
                                        "weight": 0.532933
                                    }
                                }
                            },
                            {
                                "@facets": {
                                    "_": {
                                        "weight": 0.99991
                                    }
                                }
                            },
                            {
                                "@facets": {
                                    "_": {
                                        "weight": 0.876172
                                    }
                                }
                            },
                            {
                                "@facets": {
                                    "_": {
                                        "weight": 0.99991
                                    }
                                }
                            },
                            {
                                "@facets": {
                                    "_": {
                                        "weight": 0.989025
                                    }
                                }
                            }
                        ],
                        "@facets": {
                            "_": {
                                "weight": 0.914943
                            }
                        }
                    }
                ]
            }
        ]
    }
}
```

And now another example that goes deeper:
```
{
    recurse( func: eq(xid, "Algeria"), depth: 4 ) @ignorereflex {
    	xid
    	_uid_
    	related @facets(weight)
    }
}
```
Results is linked in the below text file: search for `"xid": "Calligraphy"` to see its children predicate-free. You can also search for `"xid": "French_Revolution"` in the same file further down for another example.

Larger file (1.4mb): [results.txt](https://github.com/dgraph-io/dgraph/files/1391879/results.txt)

**Using expand(_all_) works better but...** I cannot see the facets for my predicate ‘related’. also I had to use depth 3 instead of 2 to see the level I wanted to see.

```
{
    recurse( func: eq(xid, "Pen"), depth: 3 ) {
    	expand(_all_)
    }
}
```
![image](https://user-images.githubusercontent.com/12215372/31677971-dff1f0ac-b36c-11e7-9de9-3322686edda8.png)

**Comment by peterstace** [comment]
I suspect this is related to #1642. Makes sense to sort this issue out once that one has been resolved.

**Comment by peterstace** [comment]
Smaller example to reproduce:

```
mutation{
  schema{
    xid: string @index(exact) .
  }
  set{
    _:lvl0 <xid> "lvl0" .
    _:lvl1 <xid> "lvl1" .
    _:lvl2 <xid> "lvl2" .

    _:lvl0 <to> _:lvl1 (weight=0.2) .
    _:lvl1 <to> _:lvl2 (weight=0.3) .
  }
}
```

```
{
  recurse(func: eq(xid, "lvl0"), depth:1) {
    _uid_
    xid
    to @facets(weight)
  }
}
```

```
{
  "data": {
    "recurse": [
      {
        "_uid_": "0x1",
        "xid": "lvl0",
        "to": [
          {
            "@facets": {
              "_": {
                "weight": 0.2
              }
            }
          }
        ]
      }
    ]
  }
}
```

We shouldn't be showing the facets, since we're already at the maximum depth now.

**Comment by peterstace** [comment]
I discussed this with @manishrjain , we decided this is working as intended.

In the Wikipedia example, the maximum depth is set to 2. The "Pen" level and the "Ballpoint_pen" levels are both expanded (this is the two levels). The facets on the edges leading to the 3rd level are also shown. This is because those facets are part of the predicates on the 2nd level (although for your usecase, the facets aren't useful unless the edges they lead to are also expanded - this might not be the case for other use cases depending on the semantic meaning of the facets/nodes/edges).

What you probably want to do in your case is set the max depth to 3 and ignore the facets shown in the 3rd (last) level.

**Comment by manishrjain** [comment]
Just to add a bit more explanation for why it's working as intended.

Extending @peterstace's query above:

```
{
  recurse(func: eq(xid, "lvl0"), depth:1) {
    _uid_
    xid
    x as to @facets(weight)
  }
  getUid(func: uid(x)) {
    _uid_
  }
}
```
Here the variable `x` is assigned the UIDs correspoding to `to`, as expected. The only reason the UIDs corresponding to `to` don't show up in results, is because there's no explicit `_uid_` call to add them to results; because of the depth limitation. Thus, we retrieve to's edges, including the facets. Because facets were explicitly asked for, we add them to results, but because `_uid_` was not asked for, we don't.

However, if we store them in the variable x, and ask for it in the separate block as shown, you can see the UIDs.

```
{
  "data": {
    "recurse": [
      {
        "_uid_": "0x1",
        "xid": "lvl0",
        "to": [
          {
            "@facets": {
              "_": {
                "weight": 0.2
              }
            }
          }
        ]
      }
    ],
    "getUid": [
      {
        "_uid_": "0x2"
      }
    ]
  }
}
```

**Comment by lazharichir** [comment]
Alright, I can see it now, it does make sense as well even if at first it seems unintuitive. And easy to fix by adding one to the original depth.

Thanks a lot for the clarification to you both @peterstace and @manishrjain !
