### ISSUE TITLE
Repeated Subgraph Error

### ISSUE THREAD

**Issue by BlakeMScurr** [dgraph-io/dgraph#1652]
Any query query with `expand(_all_)` and another predicate at the same level fails with "`Repeated subgraph: [<pred>] while using expand()`". Just as [this unit test](https://github.com/dgraph-io/dgraph/blob/babb4cabb6866b07fc965eac799f594e91067e88/cmd/dgraph/main_test.go#L1150) fails.

This prevents us from writing queries like:

```
{
	me(func:anyofterms(name, "Alice")) {
		expand(_all_)
		friend {
                     name
                }
	}
}
```

From my point of view, it would be nice to implicitly exclude the friend predicate from `expand(_all_)`, so that you can get all values of a node *and* particular values of its children.

**Comment by peterstace** [comment]
This seems pretty reasonable to me.

**Comment by manishrjain** [comment]
This could be done by blocks.

```
{
  alice as anyofterms(name, "Alice")
  all(func: uid(alice)) {
    expand(_all_)  
  }
  friends(func: uid(alice)) {
    friend { name }
  }
}
```
