### ISSUE TITLE
configure timeout for query

### ISSUE THREAD

**Issue by jzhu077** [dgraph-io/dgraph#1657]
It would be nice if there is a configuration I can set to extend the [timeout](https://github.com/dgraph-io/dgraph/blob/master/dgraph/server.go#L231 ) when there is an enormous amount of nodes to query.

**Comment by manishrjain** [comment]
Yeah, that's something we can let the user decide by passing in an appropriate context, instead of us doing this for them.

**Comment by peterstace** [comment]
PR: #1662

**Comment by peterstace** [comment]
Merged to master in 9d6dd6e

**Comment by JuliardiDev** [comment]
I have been using dgraph v0.7.7 with set the context timeout. In small data it fine, but in tons of data it will makes grpc connection was lost. How I can handle that ?

**Comment by pawanrawal** [comment]
Ideally, you should migrate to the latest version and set the timeout according to your needs.
