### ISSUE TITLE
support alias in group by query.

### ISSUE THREAD

**Issue by janardhan1993** [dgraph-io/dgraph#1661]
The following query throws error.
{
  var(func: has(Store)) @filter(eq(Province, "ON")) {
    parents as ~PickedAt @filter(
      gt(Created, "2017-10-22T13:00:00.000Z") AND
      lt(Created, "2017-10-28T13:59:59.999Z")
    )
  }
  Vals(func: uid(parents)) @groupby(Owner) {
    sum(TeamScore)
    abc:count(_uid_)
  }
}

**Comment by pawanrawal** [comment]
This is in master as of 35c8157604b892f24064755493d7bb2f096c9d53.
