### ISSUE TITLE
Comments in schema mutation causes error

### ISSUE THREAD

**Issue by calummoore** [dgraph-io/dgraph#1667]
I can create comments in `set` mutations, but not `schema` mutations.
Dgraph: v0.8.3

**Schema**
The following will throw an error:
```
mutation {
  schema {
    # All Nodes
    name: string @index(term) .
  }
}
```

Error: `failed to parse schema error: invalid request: Invalid schema. Unexpected #`

**Set**
The following works fine:
```
mutation {
  set {
    # All Nodes
    _:node <name> "John" .
  }
}
```

I'm working around it by removing any comments before sending the request, but I guess it should be consistent.

**Comment by manishrjain** [comment]
In v0.9 release, we're separating out mutations from queries, so mutations won't be part of the query string, and won't be specified in text form (instead using JSON). So, no point fixing this, please use the workaround for now.
