### ISSUE TITLE
Split proto file up into "internal" and "api"

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1674]
This will make it a bit clearer which parts of the gRPC api are intended for clients vs internal communication.

Users who are dealing with gRPC directly (or client authors) will find this easier to grok.

**Comment by peterstace** [comment]
for the `java_package` option:
```option java_package = "io.dgraph.proto.api";
```
and
```option java_package = "io.dgraph.proto.internal";```

**Comment by manishrjain** [comment]
That's a good point. Maybe do it right away before v0.9.

**Comment by peterstace** [comment]
Going to use `intern` instead of `internal`, due to [this](https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit).

**Comment by peterstace** [comment]
In master at 0a01c52
