### ISSUE TITLE
Use semantic version for dgraph

### ISSUE THREAD

**Issue by jalberto** [dgraph-io/dgraph#1675]
trying to upgrade from 0.8.1 to 0.8.3 I notice this patch bump (patch as in versioning numbers) breaks compatibility.

Will be great if dgraph follows http://semver.org so users knows what to expect.

**Comment by manishrjain** [comment]
We plan to follow it strictly after v1.0 release. Right now, most releases break backward compatibility. So, we insist users export their data before upgrading.
