### ISSUE TITLE
Dgraph terminates while inserting data using dgraphloader 

### ISSUE THREAD

**Issue by priyanshujain** [dgraph-io/dgraph#1676]
on running 
```
 docker exec -it dgraph dgraphloader -r "data.rdf.gz" -x
```
this is giving an error, 

```Dgraph version   : v0.8.1
Commit SHA-1     : 8ea4b0a5
Commit timestamp : 2017-09-18 10:56:37 +1000
Branch           : HEAD

2017/10/25 16:09:54 mkdir c: no such file or directory
```
please help what I'm missing

**Comment by peterstace** [comment]
You'll need to mount a volume that the loader can use to write to (temp scratch space for keeping the xid to uid mapping). Try passing `-v ~/path/on/host:/dgraph` as an additional argument.

**Comment by priyanshujain** [comment]
It worked thanks @peterstace @manishrjain
