### ISSUE TITLE
dgraph doesn't start with tls on

### ISSUE THREAD

**Issue by serebrov** [dgraph-io/dgraph#1691]
I found this issue while looking at [this stackoverflow question](https://stackoverflow.com/questions/46836434/trouble-starting-dgraph-with-tls).
While checking the problem I discovered that this is a bug, which can be reproduced this way:

1. Run `dgraphzero -w zw`
2. Run `dgraph --config ~/web/dgraph-test/dgraph-min.yml`

It fails with `open : no such file or directory` error.

And the `dgraph-min.yml`:

    memory_mb: 4096
    peer: localhost:8888
    tls.on: true
    tls.cert: /home/seb/web/dgraph-test/test2.crt
    tls.cert_key: /home/seb/web/dgraph-test/test2.key

This can also be confirmed with the [tls test suite](https://github.com/dgraph-io/dgraph/tree/master/contrib/tlstest).
Running it confirmed the error, shell files to start the server required small adjustments (add ` --memory_mb 2048`) and then it fails with same error:

    $ cd contrib/tlstest 
    $ make
    -e 

    TESTING...

    Basic TLS communication, unencrypted keys
    ./server_nopass.sh <-> ./client_nocert.sh: 127 (expected: 0)
    Makefile:8: recipe for target 'test' failed
    make: *** [test] Error 1

    $ ./server_nopass.sh 
    ./server_nopass.sh: line 3: ../../cmd/dgraph/dgraph: No such file or directory

The issue seems to be in the [main.go](https://github.com/dgraph-io/dgraph/blob/master/cmd/dgraph/main.go#L438-L447).
Here the tls config is created, but not all the parameters are passed, for example, `tlsKey` and `tlsKeyPath` are missing.

Later, in the [tls_helper.go](https://github.com/dgraph-io/dgraph/blob/master/x/tls_helper.go#L187) there is an attempt to use these parameters and pass them over to the [parseCertificate](https://github.com/dgraph-io/dgraph/blob/master/x/tls_helper.go#L82), which fails on reading the certificate file because the path is empty.

**Comment by pawanrawal** [comment]
Hi @serebrov 

Thanks for the bug report and a detailed analysis. You were correct that tlsKey and tlsKeyPass were not being passed down from the flags. I have submitted a fix to master and the release/v0.8.3 branch. 
The releases binaries should be updated shortly.
