### ISSUE TITLE
It would be nice if the 10mins predicate balancing and the suggested workaround is clearly stated in the documentation

### ISSUE THREAD

**Issue by jzhu077** [dgraph-io/dgraph#1694]
https://discuss.dgraph.io/t/what-grpc-address-should-i-use-to-access-the-dgraph-cluster/1898/10
Q:
Does Predicate balance/transfer is only considered around once per 10 min. mean I should wait for 10 mins after I set up the schema?

A:
From Manish R Jain
Yeah, currently just one move per 10 mins. If you want to evenly spread them out during ingestion, you could give the address of all the Dgraph servers to the client. It would then randomly pick up a dgraph server to send data to. That way, all servers would see new predicates and get to serve them.

For various reasons, if Dgraph server X is the first one to see a new predicate, it would be the one to serve it. That’s why doing this at the client level helps.

**Comment by peterstace** [comment]
Added a note to the wiki at a50de0cf
