### ISSUE TITLE
What time can support Chinese search?

### ISSUE THREAD

**Issue by konding** [dgraph-io/dgraph#1695]
Hi.
Bleve looks like it already supports Chinese.
 
[https://github.com/blevesearch/bleve/issues/128](https://github.com/blevesearch/bleve/issues/128)

**Comment by peterstace** [comment]
I'll look into Japanese at the same time.

**Comment by peterstace** [comment]
Merged to master at 623638c. This will appear in the upcoming v0.9.0 release.
