### ISSUE TITLE
Error countered with strange message

### ISSUE THREAD

**Issue by ddibiase** [dgraph-io/dgraph#1702]
Reporting an issue on our production servers. Earlier today we started receiving reports of functionality that formerly worked perfectly. Upon investigation the query we were running was throwing:

    3|OTC      | { Error: failed to apply mutations error: internal error: Temporary Error. Please retry.
    3|OTC      |     at /var/srv/node_modules/grpc/src/node/src/client.js:554:15 code: 2, metadata: Metadata { _internal_repr: {} } }

After a few further attempts we decided to update the schema and see if that helped and noted the following error in Dgraph's logs:

    goroutine 1202 [running]:
    encoding/binary.binary.bigEndian.Uint64(...)
            /home/travis/.gimme/versions/go1.9.linux.amd64/src/encoding/binary/binary.go:124
    github.com/dgraph-io/dgraph/x.Parse(0xc468560750, 0xc, 0x10, 0xc4cc453dc0)
            /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/keys.go:271 +0x235
    github.com/dgraph-io/dgraph/posting.compareAttrAndType(0xc468560750, 0xc, 0x10, 0xc548293a97, 0x7, 0x1446a02, 0xc578c7c780)
            /home/travis/gopath/src/github.com/dgraph-io/dgraph/posting/index.go:417 +0x5d
    github.com/dgraph-io/dgraph/posting.DeleteIndex.func1(0xc468560750, 0xc, 0x10, 0x0)
            /home/travis/gopath/src/github.com/dgraph-io/dgraph/posting/index.go:642 +0x56
    github.com/dgraph-io/dgraph/posting.(*listCache).clear(0xc42030ae40, 0xc420051898, 0x0, 0x0)
            /home/travis/gopath/src/github.com/dgraph-io/dgraph/posting/lru.go:182 +0x155
    github.com/dgraph-io/dgraph/posting.DeleteIndex(0x145b4e0, 0xc455af9680, 0xc548293a97, 0x7, 0x0, 0x0)
            /home/travis/gopath/src/github.com/dgraph-io/dgraph/posting/index.go:641 +0x78
    github.com/dgraph-io/dgraph/worker.(*node).rebuildOrDelIndex(0xc42018ebd0, 0x145b4e0, 0xc455af9680, 0xc548293a97, 0x7, 0x0, 0x10001, 0xc548293a97)
            /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/index.go:43 +0x13f
    github.com/dgraph-io/dgraph/worker.runSchemaMutation(0x145b4e0, 0xc455af9680, 0xc5e813a540, 0x0, 0x0)
            /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/mutation.go:142 +0x774
    github.com/dgraph-io/dgraph/worker.(*node).processSchemaMutations(0xc42018ebd0, 0xc50238131e, 0x1e54e1, 0xc5e813a540, 0x0, 0x0)
            /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:337 +0x102
    github.com/dgraph-io/dgraph/worker.(*scheduler).schedule(0xc4201722c0, 0xc420051f38, 0x1e54e1, 0x8ac, 0x0)
            /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/scheduler.go:128 +0x11a
    github.com/dgraph-io/dgraph/worker.(*node).processApplyCh(0xc42018ebd0)
            /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:400 +0x4e4
    created by github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode
            /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:714 +0x1c3

Upon applying the schema again and rebooting the issue resolved itself. Following is the schema applied. Unfortunately due to the nuance of the issue we aren't able to provide any further detail. The query that was failing however was being sent over the gRPC query endpoint.

    mutation { schema {
      Pin:string @index(term,exact) @count .
      Zip:string .
      City:string .
      Game:string @index(term,exact) @count .
      Name:string .
      Role:string @index(term) .
      Team:string @index(term,exact) @count .
      Used:string @index(exact) .
      Alias:string .
      Email:string @index(exact) @count .
      Owner:uid @reverse @count .
      Round:string .
      Score:float .
      Sport:string @index(term,exact) @count .
      Staff:default .
      State:string .
      Store:string @index(term) @count .
      Token:string @index(term,exact) @count .
      Venue:string .
      Width:int .
      Assets:string .
      Height:int .
      Jersey:string .
      League:string @index(term,exact) @count .
      Market:string @index(exact) .
      Period:string .
      Player:string @index(term,exact) @count .
      Statis:default .
      Status:string @index(exact,hash) @count .
      Street:string .
      UsedAt:uid .
      UsedBy:uid @reverse @count .
      UsedOn:datetime @index(hour) .
      Weight:default .
      Account:string @index(term,exact) @count .
      Address:string .
      Country:string .
      Created:datetime @index(hour) .
      ForGame:uid @count .
      HasTeam:uid .
      Network:string @index(term,exact) @count .
      ConnectedTo:uid @count @reverse .
      Broadcaster:string .
      TestPin:default .
      Updated:datetime @index(hour) .
      UsedPin:uid .
      Website:default .
      AwayGame:uid .
      AwayTeam:uid .
      Birthday:default .
      Capacity:int .
      Coverage:string .
      Createed:datetime .
      Division:string @index(term,exact) @count .
      FaveTeam:string .
      FromGame:uid @reverse .
      FromTeam:uid .
      GameStat:uid @count .
      HasVenue:uid .
      HomeGame:uid .
      HomeTeam:uid .
      Language:string .
      LastName:string @index(fulltext) .
      Location:geo @index(geo) .
      Password:string .
      PickedAt:uid @reverse @count .
      Position:string @index(exact) @count .
      Province:string @index(exact) @count .
      TimeZone:string .
      Timezone:default .
      Username:default .
      FirstName:string .
      HasLeague:uid .
      HasPlayer:uid .
      Headshots:string .
      LastLogin:datetime @index(hour) .
      Reference:string .
      Scheduled:datetime @index(hour) .
      TeamScore:float .
      Telephone:string .
      AllowEmail:default .
      AwayPoints:int .
      Conference:string @index(term,exact) @count .
      CustomTeam:string @index(term) @count .
      Handedness:default .
      HomePoints:int .
      IsEmployee:default .
      OwningTeam:uid .
      PlayerStat:uid @count .
      PostalCode:string @index(exact) .
      Statistics:uid @reverse @count .
      TokenOwner:uid .
      CreatedTeam:uid @reverse .
      HasDivision:uid .
      PlayerStats:uid .
      StoreNumber:string .
      SubmittedAt:datetime @index(hour) .
      TeamPlayers:uid .
      Abbreviation:default .
      HomeLocation:uid @reverse @count .
      LocationName:string .
      MobileNumber:string .
      PlayerPoints:float .
      Administrator:default .
      HasConference:uid .
      OwnsCustomTeam:uid @reverse @count .
      SelectedPlayer:uid .
      CurrentLocation:geo @index(geo) .
      IsParticipating:default .
    } }

**Comment by peterstace** [comment]
Some background from Slack:

In particular I was concerned about the following sequence causing a crash: 1. data exists against a predicate set to string in schema. 2. predicate changed to password in schema. 3. queries against that schema causing a crash.

**Comment by manishrjain** [comment]
We should probably disallow switching from string -> password. Password would require us to rewrite the data, encrypting it in the process. No other conversion makes us do that. The right steps to achieve this should be: delete the predicate, set the schema of the predicate to password, rewrite the data.

**Comment by peterstace** [comment]
Agreed, disallowing a string->password schema change seems like the most sensible way to do this. If a user wants to repurpose the predicate name then they can use the existing mechanisms to do that.

I'll close this ticket, I don't think there's anything more to do here. See #1703
