### ISSUE TITLE
Disallow string to password schema mutation

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1703]
This transition would require us to rewrite the data, which is significantly different from other schema conversions.

A simpler approach is to just disallow this particular type of schema mutation.

**Comment by nikolakanacki** [comment]
I'm sorry, but disallow meaning.. in order to change schema type for a particular field one would need to drop the database and recreate it, or am I not getting this right?

**Comment by peterstace** [comment]
Yes, that's correct. If you have a predicate and wish to switch it to the password type, you would have to drop and recreate the database.

**Comment by manishrjain** [comment]
Let's get this done before the release.

**Comment by peterstace** [comment]
In master at 67c54b7
