### ISSUE TITLE
unable to build postingiterator

### ISSUE THREAD

**Issue by jzhu077** [dgraph-io/dgraph#1709]
go build -o ./postingiterator  github.com/dgraph-io/dgraph/cmd/postingiterator
\# github.com/dgraph-io/dgraph/cmd/postingiterator
../../cmd/postingiterator/main.go:44: undefined: badger.NewKV

**Comment by manishrjain** [comment]
That's a tool that we use internally. The master is in flux, so this broke. Do you need this tool?

**Comment by jzhu077** [comment]
Ah, my mistake. I will close this issue.
