### ISSUE TITLE
undefined: client.Node after upgrade to latest version

### ISSUE THREAD

**Issue by bobvanluijt** [dgraph-io/dgraph#1711]
The following issue started after updating to the latest version.

```
import (
...
    dgraphClient "github.com/dgraph-io/dgraph/client"
...
)
```

The following function:

`func (f *Dgraph) addNewNode(nType string, UUID strfmt.UUID) (dgraphClient.Node, error) { ... }`

gives an error on `dgraphClient.Node`: `undefined: client.Node`

**Comment by peterstace** [comment]
>> latest version

master isn't too stable right now, I would recommend to use the latest version from the branch `release/v0.8.3`.
