### ISSUE TITLE
client.Req no longer exists

### ISSUE THREAD

**Issue by bpmason1** [dgraph-io/dgraph#1720]
https://github.com/dgraph-io/dgraph/blob/ec272f005d416e7a224a393fab673c1b73b21523/client_test/client_test.go#L88

the client.Req struct, which is used in all of the example code, no longer exists.  So, none of the examples even compile.

**Comment by peterstace** [comment]
The `master` branch is undergoing some major changes at the moment (upcoming support for transactions has required major API and internal changes). We recommend to use the latest release branch, `release/v0.8.3` for now. We will make sure all examples are consistent with the new API before the next official release (which will be `release v0.9.0`).
