### ISSUE TITLE
Comparing value whose type list (INEXACT MATCH)

### ISSUE THREAD

**Issue by calvindoro** [dgraph-io/dgraph#1732]
for instance:
i stored ["India", "Indonesia", "Hong Kong", "Japan", "Korea"] on edge named "country" and i want to check whether "India" is in the list or ["India", "Indonesia"] intersect with the list which stored previously.
Are these possible to be done in Dgraph ?

**Comment by peterstace** [comment]
You can't do that when your data is stored as a list. Lists generally aren't good for modelling data that effects how a query is executed.

There are other ways to do it though. Generally it's easier to write queries if you just use nodes and edges. So in this case, you would model each country as its own node (with a `name` predicate). Then your main object would have a `country` edge to the relevant countries.

If you give a more specific example of what sort of input/output the query should have, I could help to guide you in the right direction with a query.

**Comment by calvindoro** [comment]
allofterms can't be used when i stored the data in a list
for instance:
languages: [string] @index(term) ..

**Comment by peterstace** [comment]
@calvindoro , are you getting a particular error message?

**Comment by peterstace** [comment]
I'm going to close this as "timed out". @calvindoro , if you're still having trouble with this we can reopen this issue. Thanks! :smile:
