### ISSUE TITLE
Deleting edges is too agressive

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1744]
If we add an edge `<0x1> <name> "foo"`, and then delete a (non existant edge) `<0x1> <name> "bar"`, then the original edge that we added gets erroneously deleted.

**Comment by janardhan1993** [comment]
Fixing this, we will disallow the syntax <0x1> <name> "bar" for scalar non-list types. We could still do <0x1> <name> *, or transactions can be used to delete only if value hasn't changed. 
Doing this check on server with transactions is complicated.

**Comment by janardhan1993** [comment]
Fixed in master, we throw error now
