### ISSUE TITLE
group by should allow filters

### ISSUE THREAD

**Issue by abbas-zaidi** [dgraph-io/dgraph#1747]
RIDE is a node and DRIVER and RIDER are edges coming out of RIDE. Driver and RIDER are different nodes as well. I need to query the rides which has the same driver-rider pair.

```
{
   q(func:eq(name,"RIDE")) @groupby(rider,driver) {
     count(_uid_)
   }
}
```

I should be able to filter the query as i want to display the rides having count greater than 1. Otherwise i am getting a big list of rides and i need to write application logic.

**Comment by manishrjain** [comment]
If many users are looking for this feature, we could add it.

**Comment by mehdiym** [comment]
I have [the same request](https://discuss.dgraph.io/t/how-to-find-duplicate-nodes-based-on-a-scalar-attribute-value/3247) in order to remove duplicate nodes in my database.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8407). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
