### ISSUE TITLE
Support for @cascade and @normalize directives for subqueries

### ISSUE THREAD

**Issue by jeffkhull** [dgraph-io/dgraph#1755]
Per original thread at: https://discuss.dgraph.io/t/support-for-cascade-and-normalize-directives-for-subqueries/1944

I have a lot of situations where I would benefit from being able to use `@cascade` and `@normalize` not at the top level of the query, but on subqueries.  Would it be possible to support uses like:

```
{
  results (func: ...) {
    predicate1 @cascade {
      ...
    }
    predicate2 @normalize {
      ...
    }
  }
}
```

The error I get when trying this on v0.8.3 is:

```
"errors": [
        {
            "code": "ErrorInvalidRequest",
            "message": "Cannot have children for attr: [predicate] with lang tags: [cascade]"
        }
    ]
```

(or similar error for normalize)

**Comment by labs20** [comment]
Hi, is this one still active. When working serving data to web templates, be able to @normalize at subqueries would make the templates much more natural.

```
{
  user(func: has(__is_users)){
    uid
    user
    person @normalize{
      name: name
    }
    profiles{
      profile
    }
  }
}
```

I woud like to map 

```
{{user.user}} - {{user.person.name}}
{{user.profiles[0].profile}}
{{user.profiles[1].profile}}
etc...
```

**Comment by labs20** [comment]
Any news on that?

Cascade in subqueries is becoming VERY important to me as I have to build more complex queries

**Comment by ahopkins** [comment]
+1 For this feature.

**Comment by xenophilicibex** [comment]
Another request for this feature!

**Comment by Necmttn** [comment]
another request for this feature.

**Comment by ohenley** [comment]
+1

**Comment by ahmedbrandver** [comment]
+1

**Comment by rickytyho** [comment]
+1
