### ISSUE TITLE
Alias facets

### ISSUE THREAD

**Issue by WolfDan** [dgraph-io/dgraph#1777]
Could be amazing if it's possible to alias a direct facet result for example actually this

```
{
  data(func: eq(name, "Alice")) {
     name
     mobile_since: mobile @facets(since)
  }
}
```
return this

```
  "data": {
    "data": [
      {
        "name": "Alice",
        "mobile_since|since": "2006-01-02T15:04:05Z",
        "mobile_since": "040123456",
      }
    ]
  }
```

In my proposal should return this 

```
  "data": {
    "data": [
      {
        "name": "Alice",
        "mobile_since": "2006-01-02T15:04:05Z",
        "mobile": "040123456",
      }
    ]
  }
```

So instead of do a big change on `@facets` since is used in many things this functionality can be called `@facet` or something like that

**Comment by pawanrawal** [comment]
Support for this has been added to master from 7d3ceea1fa5276f4e901100e2bd64a92ec66c7c2 and would be part of the next release.
