### ISSUE TITLE
The is a difference between graph display and json response

### ISSUE THREAD

**Issue by weickdev** [dgraph-io/dgraph#1782]
When I run this command in web console:
```
{
  everyone(func: anyofterms(name, "Michael")) {
		expand(_all_)
  }
}
```

I get below result
<img width="577" alt="graph_display" src="https://user-images.githubusercontent.com/31640567/32877468-4e2f33ca-ca67-11e7-9762-390ae51a67bb.png">

It contains the node information about Michael and his relations, but when I check the json response, it contains only node info:
<img width="1074" alt="json_result" src="https://user-images.githubusercontent.com/31640567/32877627-0b476c66-ca68-11e7-9cc2-13c9cea9f096.png">

That is to say, json response doesn't contain edge information. If the response doesn't contains any edge informations how can the web console display them?

**Comment by pawanrawal** [comment]
A fix has been merged to master with a71e91c7daedb1163acdda67a1c5851fdb37ccbc.
