### ISSUE TITLE
support external etcd cluster?

### ISSUE THREAD

**Issue by hanbing0715** [dgraph-io/dgraph#1787]
i found that dgraph use raft and use etcd's go implement in vendor (maybe)?
etcd's go implement of raft is the standard in fact
so this is may be a good idea that dgraph have option to connect external etcd cluster instead of bundle raft implement?
a external etcd cluster maybe have better disk, more cpu core or better SLA than bundle raft implement.
but,a external etcd clusterm maybe means network delay, more config and other questions.
so,i sounds that let administrator make this choise is a good idea?

**Comment by manishrjain** [comment]
We only use the Raft library and have no connection whatsoever to Etcd. Dgraph can't be pointed to work with Etcd.
