### ISSUE TITLE
Support a particular language query on the string list type.

### ISSUE THREAD

**Issue by w4-hyunseok** [dgraph-io/dgraph#1788]
On the Dgraph v0.9.0, there was no way to get a untagged values of the string list type. 
Could you support this features? 

The original thread is [this](https://discuss.dgraph.io/t/support-list-type-for-language-specific-string/1963). 

I hope that the dgraph will support multiple language string list type by one predicate.

**Comment by peterstace** [comment]
When showing a list, only untagged values will be shown. To get tagged values, you now have to ask for that language explicitly.

Fixed in master at 2572712 and will appear in the next release.
