### ISSUE TITLE
Windows Installation Instruction: Doesn't work

### ISSUE THREAD

**Issue by enamoni** [dgraph-io/dgraph#1792]
I was trying to install it...but following the instruction for "dgraph.exe" binary and "assets" it is not running.
And in the doc:
https://docs.dgraph.io/get-started/

it's written: ./dgraph.exe --memory_mb 2048 --zero localhost:5080 --ui path-to-assets-folder

I wrote it:

C:\degraph> dgraph --memory_mb 2048 --zero localhost:8080 --ui C:\assets

(shoudn't it be 8080?)

but it's not running... browser is showing : 404 page no found that means it's not getting the assets folder.

**Comment by MichelDiz** [comment]
Is `--zero localhost:5080` not 8080
the 8080 port is for ui.

try first 
`cd to my path`
`dgraph zero --port_offset -2000`
and then with other terminal
`dgraph server --memory_mb 2048 --zero localhost:5080`

**Comment by manishrjain** [comment]
Based on your commands, @enamoni , it looks like you're running an older version of Dgraph. Can you confirm the version you're running?

**Comment by pawanrawal** [comment]
@enamoni We release `v0.9.2` today. Can you try with that? There was a bug in `v0.9.0` because of which `--ui` flag wasn't parsed properly.

**Comment by pawanrawal** [comment]
Closing this as we tested that it works.
