### ISSUE TITLE
Documentation and Rancher community catalog PR.

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#1793]
As mentioned in Issue https://github.com/dgraph-io/dgraph/issues/1790 support for Docker and Kubernetes, it would be interesting to have a PR for the Rancher community catalog. It's interesting in the sense that you open up a wider range of possibility of adopting Dgraph by more people.

It is not much different to create a YAML for Rancher Compose from a Docker composer. The logic is the same. The difference comes in the settings of the Rancher itself. Things like replicas, secrets, labels, environment labels and etc.

Rancher is a very powerful orchestrator. Version 2.0 of it will use Kubernetes as a standard. It is able to run Swarm, Mesos, Cattle and Kubernetes. For this reason I believe that it is worth the investment in standardizing an official support of the Dgraph to the public catalog of them.

Cheers

**Comment by MichelDiz** [comment]
Small article on how to create templates for Rancher.

https://nrvale0.github.io/posts/rancher-catalogs-part1/

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated. This issue has been moved to [link](https://discuss.dgraph.io/t/8408).** 
 **You can follow the conversation there and also subscribe to updates by changing your notification preferences.** 


 ![SetNotifications](https://github.com/dgraph-io/pydgraph/blob/master/.github/SetNotifications.png?raw=true)
