### ISSUE TITLE
use http-client insert data become slower and slower.

### ISSUE THREAD

**Issue by lxwithgod** [dgraph-io/dgraph#1795]
dgraph server give me some message,but i can't understand:
 asking if i can server tablet for:phone
 asking if i can server tablet for:phone
 asking if i can server tablet for:_dummy_
已杀死

**Comment by lxwithgod** [comment]
this is error when number of node reach 10million.

**Comment by lxwithgod** [comment]
2017/11/20 13:47:56 groups.go:291: Asking if I can serve tablet for: phone
2017/11/20 13:51:32 node.go:400: WARN: A tick missed to fire. Node blocks too long!
2017/11/20 13:51:55 node.go:400: WARN: A tick missed to fire. Node blocks too long!
2017/11/20 13:52:42 node.go:400: WARN: A tick missed to fire. Node blocks too long!
2017/11/20 13:52:49 node.go:400: WARN: A tick missed to fire. Node blocks too long!
已杀死

**Comment by peterstace** [comment]
Hi @lxwithgod .

Messages like `asking if i can server tablet for:phone` are normal and don't mean that anything is going wrong.

On the other hand, `WARN: A tick missed to fire. Node blocks too long!` is more concerning. It's not a fatal error (it should recover eventually), but it could indicate there is some kind of communication problem between nodes.

Could you tell a bit about what you are trying to do and how your have your dgraph cluster set up?

**Comment by lxwithgod** [comment]
hi,I didn't install cluster,i use client in the other machine.i am testing dgraph for my project.maybe because of http-client.but
i use dgraph4j,insert become slower and slower.I don't use index for this node.

**Comment by peterstace** [comment]
Hi @lxwithgod , could you give more details about how you are using HTTP and dgraph4j? How many mutations are you making per transaction?

**Comment by lxwithgod** [comment]
ManagedChannel channel = ManagedChannelBuilder.forAddress(TEST_HOSTNAME, TEST_PORT).usePlaintext(true).build();
        DgraphBlockingStub blockingStub = DgraphGrpc.newBlockingStub(channel);
        DgraphClient dgraphClient = new DgraphClient(Collections.singletonList(blockingStub));

        // Set schema
//        Operation op = Operation.newBuilder().setSchema("name: string @index(exact) .").build();
//        dgraphClient.alter(op);

        // Add data

//        System.out.println(json.toString());
        LinkedList<HashMap> lj=new LinkedList<>();

        for(int i=1;i<100000000L;i++) {
            HashMap<String,String> json = new HashMap<>();
            json.put("name", "Alice");
            lj.add(json);
            if(i%20000==0){

                Mutation mu =
                        Mutation.newBuilder()
                                .setSetJson(ByteString.copyFromUtf8(Common.objectAsString(lj)))
                                .build();
                DgraphClient.Transaction transaction = dgraphClient.newTransaction();
                transaction.mutate(mu);
                transaction.commit();
                System.out.println(i);
                lj.clear();

            }

        }

**Comment by lxwithgod** [comment]
ubuntu 16.04
i7-3610m
20gb ram

**Comment by peterstace** [comment]
I'm going to close this ticket, I didn't realise this was a crosspost until just now. Let's solve the issue over at https://github.com/dgraph-io/dgraph4j/issues/30
