### ISSUE TITLE
v0.9.1 and v0.9.2 --config string not read by dgraph server

### ISSUE THREAD

**Issue by ansham22** [dgraph-io/dgraph#1801]
Hi Team,

I am getting an error when i am starting my dgraph server with --config file. I don't think it is reading config.yaml.

please see below error. 

`2017/11/20 16:11:35 Allotted memory (--memory_mb) must be specified, with value greater than 1024 MB
2017/11/20 16:11:35 Allotted memory (--memory_mb) must be specified, with value greater than 1024 MB
2017/11/20 16:11:35 Allotted memory (--memory_mb) must be specified, with value greater than 1024 MB
2017/11/20 16:11:35 Allotted memory (--memory_mb) must be specified, with value greater than 1024 MB
2017/11/20 16:11:35 Allotted memory (--memory_mb) must be specified, with value greater than 1024 MB
2017/11/20 16:11:35 Allotted memory (--memory_mb) must be specified, with value greater than 1024 MB`

This is the file i am using 
export: export

gentlecommit: 0.33

idx: 1

port: 8080

grpc_port: 9090

workerport: 12345

memory_mb: 4096

trace: 0.33

p: p

w: w

debugmode: False

bindall: True

my: "10.0.11.162:12345"

peer: "10.0.11.162:8888"

command used:-- dgraph server --config config.yaml.

**Comment by peterstace** [comment]
Viper might be a good solution for this. https://github.com/spf13/viper

It's designed to pair with Cobra.

**Comment by manishrjain** [comment]
Yeah, let's fix this and for all the tools.

**Comment by peterstace** [comment]
Taking a look at this now.

**Comment by peterstace** [comment]
This is solved by #1857
