### ISSUE TITLE
Removal of dead nodes v0.9.2

### ISSUE THREAD

**Issue by ansham22** [dgraph-io/dgraph#1802]
Hi Guys,

Even after removing dead node from Dgraph. zeros are still contacting that node. please find state below{
  "removed": [
    {
      "lastUpdate": "1511170597",
      "leader": true,
      "addr": "localhost:5080",
      "groupId": 1,
      "id": "1"
    }
  ],

zero logs. 

2017/11/20 16:43:17 pool.go:168: Echo error from localhost:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/11/20 16:43:26 oracle.go:372: No healthy connection found to leader of group 1
2017/11/20 16:43:27 pool.go:168: Echo error from localhost:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/11/20 16:43:36 oracle.go:372: No healthy connection found to leader of group 1
2017/11/20 16:43:37 pool.go:168: Echo error from localhost:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/11/20 16:43:46 oracle.go:372: No healthy connection found to leader of group 1
2017/11/20 16:43:47 pool.go:168: Echo error from localhost:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/11/20 16:43:56 oracle.go:372: No healthy connection found to leader of group 1
2017/11/20 16:43:57 pool.go:168: Echo error from localhost:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/11/20 16:44:06 oracle.go:372: No healthy connection found to leader of group 1
2017/11/20 16:44:07 pool.go:168: Echo error from localhost:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure

this shouldn't be the case for zeros.

{
  "removed": [
    {
      "lastUpdate": "1511171280",
      "leader": true,
      "addr": "10.0.11.162:5080",
      "groupId": 1,
      "id": "1"
    }
  ],

2017/11/20 16:49:15 oracle.go:372: No healthy connection found to leader of group 1
2017/11/20 16:49:20 pool.go:168: Echo error from 10.0.11.162:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/11/20 16:49:25 oracle.go:372: No healthy connection found to leader of group 1
2017/11/20 16:49:30 pool.go:168: Echo error from 10.0.11.162:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/11/20 16:49:35 oracle.go:372: No healthy connection found to leader of group 1
2017/11/20 16:49:40 pool.go:168: Echo error from 10.0.11.162:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/11/20 16:49:45 oracle.go:372: No healthy connection found to leader of group 1
2017/11/20 16:49:50 pool.go:168: Echo error from 10.0.11.162:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/11/20 16:49:55 oracle.go:372: No healthy connection found to leader of group 1
2017/11/20 16:50:00 pool.go:168: Echo error from 10.0.11.162:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure

**Comment by janardhan1993** [comment]
After the removal of node, the connection to dead node was still present in connection pool. Will fix a push to remove it from the connection pool in zero.

**Comment by janardhan1993** [comment]
@ansham22: Can you please share your setup and what you did.  `No healthy connection found to leader of group 1` shouldn't come in log as group 1 should elect a new leader eventually. Are you running with --replication=2 ?

Also note that dead node would only be removed if you have majority of the nodes belonging to the group are fine. **In case you have only two nodes in group 1 and one of them dies, it can't be removed from quorum unless you add a new node.**

**Comment by janardhan1993** [comment]
Fix to remove the connection from connection pool has been merged to master.
@ansham22 : Please reopen the issue if you still notice the issue.
We are going to do changes to allow removing dead nodes when replication is 2 and one of the node dies with #1815
