### ISSUE TITLE
Don't write examples that build queries w/ Sprintf

### ISSUE THREAD

**Issue by sporkmonger** [dgraph-io/dgraph#1803]
Since injection attacks are a thing, and examples are quite liable to be copied-and-pasted, Dgraph should be trying to ensure that all examples are written in a secure way. The https://godoc.org/github.com/dgraph-io/dgraph/client#ex-Txn-Mutate example code builds a query using `fmt.Sprintf`. It pulls the value from a source the attacker can't control (so the example itself isn't vulnerable), but there's no guarantee that someone copying-and-pasting won't use snippets of the code in a different way and might not understand the danger that `fmt.Sprintf` poses in the context of a query. Examples should be written to use `QueryWithVars` or some other function that is safe from injection attacks.

**Comment by pawanrawal** [comment]
They have been updated in master.
