### ISSUE TITLE
what 'The smallest unit of data is one predicate' means?

### ISSUE THREAD

**Issue by weickdev** [dgraph-io/dgraph#1806]
> Dgraph colocates data per predicate (* P *, in RDF terminology), thus the smallest unit of data is one predicate. To shard the graph, one or many predicates are assigned to a group. Each node in the cluster serves a single group. Dgraph zero assigns a group to each node.

I read this description in dgraph document. There is a question I need some help to understand it: `The smallest unit of data is one predicate`.

If I have a predicate `A-like->B`, it is a unit, right? If I have another predicate `A-like->C`, It is another unit. If dgraph stores both units, is there two node information about A?

**Comment by peterstace** [comment]
The documentation is talking about units of storage. It's saying that the data for a single predicate (e.g. `like`) has to exist on a single dgraph node. It cannot be split between nodes. So in your example, `A->like->B` and `A->like->C` are stored together on a single node, they can't be split apart.

**Comment by colorant** [comment]
Hi, Is this assert still hold for true now? (2019-03)? If it is , is there any plan to support split predicate onto multiple nodes , in case that one single huge predicate outgrow one node's memory?

**Comment by MichelDiz** [comment]
Yeah, it is true. A predicate can be split between Alpha nodes in an Alpha Group. But this is about predicate itself not "parts" of it. So about what you questioned, Dgaph already does this automatically.

See "Sharding" and "Shard rebalancing" https://docs.dgraph.io/deploy/#understanding-dgraph-cluster

**Comment by rahst12** [comment]
> A predicate can be split between Alpha nodes in an Alpha Group

How does Dgraph split the predicate?..

**Comment by MichelDiz** [comment]
As you could read from Peterstace's comment. Fundamentally predicates can't be split.

What I meant by using the word "split" was in the sense of Sharding. But not in the atomic sense of splitting a predicate. This is not possible at this time.

**Comment by maximmold** [comment]
Is this only for relationship predicates or does it also apply to property predicates?
