### ISSUE TITLE
Errors when querying for paths between nodes

### ISSUE THREAD

**Issue by magallardo** [dgraph-io/dgraph#1809]
I am running a query to retrieve paths between 2 nodes. I was able to get good results for paths of length 2, 3, 4 and 5. When I configure the query to retrieve paths of length 6 (and consequently very large number of paths to be returned), I saw the following errors on the console for dgraph zero and dgraph server. Also I run top on my machine and noticed that all the mdworker processes were "stuck". The processes run for a very long time and never got a response.

[2:06] 
dgrqaph zero console
2017/11/21 10:59:51 oracle.go:347: No healthy connection found to leader of group 1
2017/11/21 11:10:06 oracle.go:347: No healthy connection found to leader of group 1
2017/11/21 11:14:00 oracle.go:347: No healthy connection found to leader of group 1

dgraph server console
2017/11/21 11:04:11 node.go:400: WARN: A tick missed to fire. Node blocks too long!
2017/11/21 11:16:32 node.go:400: WARN: A tick missed to fire. Node blocks too long!
2017/11/21 11:19:00 node.go:400: WARN: A tick missed to fire. Node blocks too long!

I think the issue definitely has to do with the size of the result. I was also able to get similar issue when using the k-shortest-path query for scenarios when k is larger than 10000.

I can easily reproduce the issue in both cases.

**Comment by manishrjain** [comment]
The server could go OOM trying to run such expensive queries, but I don't understand why it became unhealthy.

**Comment by janardhan1993** [comment]
@magallardo: Which version of dgraph are you using ?

**Comment by magallardo** [comment]
Initially I started the dgraph server with 4 GIG, then I used 8 GIG and finally I changed to 16 GIG. In all cases, it ended up with the same result. Also, note that the data set is not that big. It has only about 350000 RDFs.
All my tests were run using version 0.9.2

**Comment by janardhan1993** [comment]
@magallardo : Can you please share the heap profile of dgraph data server when this issue happens and the output of /debug/vars.
https://docs.dgraph.io/master/howto/#retrieving-debug-information

**Comment by janardhan1993** [comment]
@magallardo: Are you using mac ? You said that `Also I run top on my machine and noticed that all the mdworker processes were "stuck"`, i think mdworker is some indexing process in mac. It has not relation to dgraph. Can you try turning off indexing in dgraph data directories and try. 

The following logs tell that Zero was able to connect to the dgraph node but the echo call took more than 20 seconds. I think something else is eating away cpu/memory. 
Can you please try to reproduce the same on master/nightly binary.  
`
2017/11/21 10:59:51 oracle.go:347: No healthy connection found to leader of group 1
2017/11/21 11:10:06 oracle.go:347: No healthy connection found to leader of group 1
2017/11/21 11:14:00 oracle.go:347: No healthy connection found to leader of group 1
`

**Comment by magallardo** [comment]
@janardhan1993 First just wanted to confirm that I am running on MacOS. Following your suggestion I disabled indexing on the dgraph data folders zw, x, p and w and rerun the test using dgraph 0.9.2

The results are as follow:
- I don't see mdworker processes stuck
- The dgraph query still taking forever and saw the same messages on the dgraph zero and dgraph server as shown below
- I noticed that the server process goes to stuck state from time to time. Following is the entry from top 
30731  dgraph       32.8      31:59.15 134     0     421   1799M+ 0B     39G-   30731 29970 stuck    *0[

dgraph zero output:
2017/11/29 15:25:52 zero.go:352: Connected
2017/11/29 15:26:12 oracle.go:69: purging below 4 6 0
2017/11/29 15:26:22 oracle.go:69: purging below 60 34 0
2017/11/29 15:42:11 oracle.go:347: No healthy connection found to leader of group 1
2017/11/29 15:47:02 oracle.go:347: No healthy connection found to leader of group 1


dgraph server output:
2017/11/29 15:26:11 groups.go:283: Asking if I can serve tablet for: to
2017/11/29 15:26:11 groups.go:283: Asking if I can serve tablet for: use
2017/11/29 15:27:28 lru.go:76: LRU cache max size is being set to 50 MB
2017/11/29 15:31:12 groups.go:283: Asking if I can serve tablet for: _dummy_
2017/11/29 15:45:20 node.go:400: WARN: A tick missed to fire. Node blocks too long!
2017/11/29 15:47:01 node.go:400: WARN: A tick missed to fire. Node blocks too long!
2017/11/29 15:47:01 node.go:400: WARN: A tick missed to fire. Node blocks too long!
2017/11/29 15:47:02 node.go:400: WARN: A tick missed to fire. Node blocks too long!

Following is the query I am trying to run:
{
        routequery(func: eq(type, "Airport")) @filter(eq(airport, "SFO")) @cascade @ignorereflex {
          airportid
          airport
          use {
            airline
            airlineid
            to  {
              airportid
              airport
              use {
                airline
                airlineid
                to  {
                  airportid
                  airport
                  use {
                    airline
                    airlineid
                    to {
                      airportid
                      airport
                      use {
                        airline
                        airlineid
                        to {
                          airportid
                          airport
                          use {
                            airline
                            airlineid
                            to @filter(eq(airport, "CDG")) {
                              airportid
                              airport
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }

I will try to run against the latest build as suggested as soon as possible.
Thanks

**Comment by magallardo** [comment]
@janardhan1993 I just upgraded my system to the latest build using 
curl https://nightly.dgraph.io -sSf | bash

Now, when I run my client, I am getting the following and the query is not executed.
2017/11/29 16:07:35 rpc error: code = Unimplemented desc = unknown service protos.Dgraph

Did anything change on the client libraries on the latest build?

Thanks

**Comment by janardhan1993** [comment]
@magallardo: Which client are you using ? We cleaned up the protocol buffer definition files to hide the internal messages from the users. Go and java clients are updated.
Aso please run the script again after updating client. `curl https://nightly.dgraph.io -sSf | bash`

**Comment by magallardo** [comment]
@janardhan1993 I resolved the client issue and run my query test using the nightly build. Following are the observations:

- Query run for more than 12 hours and had to kill it as the query was taking all resources on my machine
- The query seems to behave better initially compared to 0.9.2. I got similar messages on the console of the dgraph zero and dgraph server but it took much longer.
- I also observed that there were several mdworker processes stuck. After I killed the dgraph processes, they stuck mdworker processes went away

Please let me know if there is anything else that I can do to get the query to return.

Thanks

**Comment by janardhan1993** [comment]
@magallardo : Thanks for providing the info. Can you please provide your data and client code, so that we can reproduce the issue and resolve it faster.

**Comment by magallardo** [comment]
[query.go.zip](https://github.com/dgraph-io/dgraph/files/1519845/query.go.zip)

[AirportschemaRefine.rdf.gz](https://github.com/dgraph-io/dgraph/files/1519840/AirportschemaRefine.rdf.gz)
I am attaching the data and schema I am using. Also including the go client that i use to issue the queries.
Once you compile the client, you can execute with an arg (0, 1, 2, 3, 4) that indicates the number of nodes in between two nodes. For example: $./dgraphclient 3


[AirportdataRefine.rdf.gz](https://github.com/dgraph-io/dgraph/files/1519837/AirportdataRefine.rdf.gz)
[AirportschemaRefine.rdf.gz](https://github.com/dgraph-io/dgraph/files/1519841/AirportschemaRefine.rdf.gz)

**Comment by janardhan1993** [comment]
@magallardo: I was able to reproduce this. Your result set is very huge and causing the process to use swap and hence it is getting stuck.

**Comment by magallardo** [comment]
@janardhan1993 That dataset has only 350K predicates. For graph database, that should be considered small. Please let me know if you find a better way to do the query.

**Comment by janardhan1993** [comment]
@magallardo: Even though the number of predicates is less, the number of paths with 3 stops can be lot higher. So say if you have 1000 possibilities for each stop, then total number of routes would be 10^9. The amount of memory consumed just by the json would be too large(In GB). 
Even grpc has a max limit of 4GB for a response.  

Streaming of large results is something we don't support yet. We plan to do it after v1.0.

**Comment by magallardo** [comment]
@janardhan1993 I tried in another graph db and the number of routes with 3 stops is ~17 million.

**Comment by manishrjain** [comment]
@janardhan1993 : Can you shed some light on what's the main reason for memory usage here? If it's the JSON conversion step that's taking up all the memory, then let's figure out if there's a way we can optimize our JSON conversion.

**Comment by janardhan1993** [comment]
The final json output had around 90-100 million key value pairs. Internally we create a fastJsonNode for each key value pair and the size of struct is 80 bytes. 
So just the struct consumed around 100*80 ~= 8GB. The intermediate representation of key/value was creating another 4-8GB overhead.

**Comment by janardhan1993** [comment]
Peter has some ideas to optimize the json conversion, assigning this to him.

**Comment by BlankRain** [comment]
`A tick missed to fire. Node blocks too long`
I also meet the problem. 
```
2018/09/03 02:05:55 groups.go:509: Unable to sync memberships. Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/09/03 02:06:41 groups.go:564: Error while updating tablets size rpc error: code = Canceled desc = context canceled
2018/09/03 02:24:54 groups.go:509: Unable to sync memberships. Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/09/03 02:25:21 groups.go:509: Unable to sync memberships. Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/09/03 02:25:33 node.go:400: WARN: A tick missed to fire. Node blocks too long!
2018/09/03 02:26:36 node.go:400: WARN: A tick missed to fire. Node blocks too long!
2018/09/03 02:56:47 groups.go:509: Unable to sync memberships. Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/09/03 02:57:14 groups.go:564: Error while updating tablets size rpc error: code = Canceled desc = context canceled

```

**Comment by manishrjain** [comment]
This is an old issue, which is around the optimization of the JSON conversion process. We have fixed a bunch of tick missed to fire issues in v1.0.7 and v1.0.8. If you're seeing issues around that, feel free to file a new Github issue so we can investigate. Optimizing JSON conversion process isn't a priority as of now. So, closing this issue.
