### ISSUE TITLE
Allow adding zero as witness node for groups with even replication.

### ISSUE THREAD

**Issue by janardhan1993** [dgraph-io/dgraph#1815]

**Comment by janardhan1993** [comment]
I couldn't think of a simpler solution. We would need to store somethings like the last index of the log etc in raft storage. Not sure what's the best way to do it. I have raised an issue on etcd/raft repo.

**Comment by manishrjain** [comment]
Isn't that easy, to store the last index of the log in our WAL?

**Comment by manishrjain** [comment]
Not a priority for now. If we need it, we'll build it later.
