### ISSUE TITLE
Dgraph live loader not considering existing uids (Creating new nodes instead)

### ISSUE THREAD

**Issue by ajayktkp** [dgraph-io/dgraph#1833]
- What version of Dgraph are you using?
0.9.2

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?
8gb ram, mac os(sierra)

- Steps to reproduce the issue (command/config used to run Dgraph).

I'm trying to use live-loader to upload the data. Following is my sample rdf. Here, I've fetched the uid from dgraph first and then created the rdf file.
`<0x3> <buyer> <0x1> .`
`<0x3> <seller> <0x4> .`
`<0x2> <buyer> <0x7> .`
`<0x2> <seller> <0x8> .`

But above is not creating the relationship with correct uids. uid(0x3) has added some other node as buyer (uid (0x72d9) and similar thing happened in the case of seller too. I was using below live loader command:
`dgraph live -r /pathToRDF/relationship.rdf --zero localhost:5080 -d localhost:9080`

I was going through the code for live-loader. I put some debug statements. I have found that, 
it successfully gets subject uid but when it goes to the db to fetch the assigned-uid it always gets 0, so it assign a new uid. Following is the sample rdf, I was exploring:
`<31001> <name> "ajay" .`
(I tried providing hex code too)
Later, i tried to provide newly assigned uid too but it never gets the existing one.
Following are the files and function I was exploring:
`xidmap/xidmap.go (func (m *XidMap) AssignUid(xid string) (uid uint64, isNew bool, err error) {
)`

- Expected behaviour and actual result.

**Comment by peterstace** [comment]
I've been able to reproduce this, definitely a problem.

PR: #1848 

Best to have this only for live loader and not bulk loader, since there is much less protection against accidentally using a UID that hasn't been leased while bulk loader (and the feature wouldn't be very useful when bulk loading anyway).

**Comment by peterstace** [comment]
A fix was put in master at 8d71924c. This will go into the next release.
