### ISSUE TITLE
Data is not available immediately after commit

### ISSUE THREAD

**Issue by raitraidma** [dgraph-io/dgraph#1841]
Using dgraph docker: dgraph/dgraph:v0.9.2
OS: Ubuntu 14.04 LTS
OS type: 64-bit
RAM: 16 GB
Processor: Intel® Xeon(R) CPU E5-2620 0 @ 2.00GHz × 12
Disk: 250GB SSD
Docker: 17.03.1-ce

Example java project to reproduce (NB docker must be installed):
[dgraphtest.zip](https://github.com/dgraph-io/dgraph/files/1505193/dgraphtest.zip)
`mvn clean test`

When adding `Thread.sleep(50);` after `transaction.commit();` in `dgraph.test.EmbeddedDgraph#addDataFromFile`, then all tests pass. Without it, only first test passes and others fail (same test is running 4 times). Expecting all tests to pass.

How tests run:
- At the beginning dgraph container is started.
- Before every test database is deleted and schema is added.
- In every test new data set is added and queried.

(Might be also a Dgraph java client issue)

**Comment by janardhan1993** [comment]
@raitraidma: Can you please share you code used for reading or code for the whole test including reading.

**Comment by raitraidma** [comment]
dgraphtest.zip in my first message contains whole example. Or do mean anything else?

**Comment by janardhan1993** [comment]
My bad, i didn't notice the other file ExampleTest.java which had the query.

**Comment by janardhan1993** [comment]
Fixed in master.
