### ISSUE TITLE
Group by result depends on predicate name

### ISSUE THREAD

**Issue by raitraidma** [dgraph-io/dgraph#1842]
# Problem
When grouping by one field, then aggregation works. When grouping by other field, that contains upper case letter, then it does not.

# Environment
Using dgraph docker: dgraph/dgraph:v0.9.2
OS: Ubuntu 14.04 LTS
OS type: 64-bit
RAM: 16 GB
Processor: Intel® Xeon(R) CPU E5-2620 0 @ 2.00GHz × 12
Disk: 250GB SSD

# Reproduce
## Schema
```
type: string @index(hash) .
```
## Data
```
_:subject1 <type> "A" .
_:subject1 <rait> "hi" .

_:subject2 <type> "A" .
_:subject2 <rait> "hi" .

_:subject3 <type> "A" .
_:subject3 <rait> "hi" .

_:subject4 <type> "A" .
_:subject4 <raitRaidma> "bye" .

_:subject5 <type> "A" .
_:subject5 <raitRaidma> "bye" .

_:subject6 <type> "A" .
_:subject6 <raitRaidma> "bye" .
```
## Query 1
```
{
  result(func: eq(type, "A")) @groupby(rait) {
    count(uid) 
  }
}
```
## Query 2
```
{
  result(func: eq(type, "A")) @groupby(raitRaidma) {
    count(uid) 
  }
}
```
# Expected result
Query 1 works and returns:
```
    "result": [
      {
        "@groupby": [
          {
            "rait": "hi",
            "count": 3
          }
        ]
      }
    ]
```
However, Query 2 returns "Your query did not return any results", but it should return:
```
    "result": [
      {
        "@groupby": [
          {
            "raitRaidma": "bye",
            "count": 3
          }
        ]
      }
    ]
```

When `raitRaidma` is replaced with `raitraidma` in data and query, then everything works and the result is:
```
    "result": [
      {
        "@groupby": [
          {
            "raitraidma": "bye",
            "count": 3
          }
        ]
      }
    ]
```

**Comment by peterstace** [comment]
Thank you for the detailed report. We'll look into this.

**Comment by peterstace** [comment]
I've been able to reproduce the issue, and have made a fix in master at ea2a2ff5. This will be available in the next release.

**Comment by raitraidma** [comment]
Can you please estimate, when the next release will be available? Then I know whether to wait for it or implement a workaround.

**Comment by pawanrawal** [comment]
Expect a release by Friday.
