### ISSUE TITLE
python  Driver

### ISSUE THREAD

**Issue by xhochipe** [dgraph-io/dgraph#1847]
希望能提供一份基于python的最新驱动

**Comment by manishrjain** [comment]
Translation: "Hope to provide a latest python-based driver."

We'll try our best to provide an official Python client by early next year.

**Comment by aqzwy** [comment]
I also want to have a python-based driver   -.-

**Comment by jimanvlad** [comment]
Python driver would be game-changing. I'll be following this issue keenly.

**Comment by MichelDiz** [comment]
Now we have a Python cliente. https://docs.dgraph.io/clients/#python

Feel free to reopen if necessary.
