### ISSUE TITLE
Async Indexes

### ISSUE THREAD

**Issue by calummoore** [dgraph-io/dgraph#1854]
Feature request to optionally allow indexes to update in the background. Currently, indexes are always part of the transaction, but that can lead to higher aborts.

This feature would allow for indexes to be updated async where they are not critical (e.g. adding a type flag), whilst keeping them within the transaction when they are (e.g. upsert).

Following on from the discussion on the [Dgraph forum](https://discuss.dgraph.io/t/indexes-and-transactions/1986).

**Comment by janardhan1993** [comment]
We implemented this change in master. Index would be consistently updated along with the mutations. We have added an option in client api to ignore conflicts for index keys. 
So users can use that option for some workloads where there are no upserts and would solve the problem of higher aborts.
