### ISSUE TITLE
Zero should forward timestamp and lease requests to the leader

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1856]
This is especially important for things such as bulk loader and live loader, that interact with zero directly.

**Comment by manishrjain** [comment]
Hmm.. Couldn't the live and bulk loader get the list of Zeros, and talk to the leader directly? I suppose that might be a problem if Zero is behind a load balancer, but there won't be much benefit in having load balancing in front of Zero anyway.

**Comment by peterstace** [comment]
You're right, it could get the membership state stream (from any zero), then it will know which zero is the leader and direct its interactions to that instance.

**Comment by peterstace** [comment]
Merged to master at 7cfd577
