### ISSUE TITLE
gRPC communication max size

### ISSUE THREAD

**Issue by magallardo** [dgraph-io/dgraph#1859]
Queries currently can only return messages of up to 256MB. I have had a couple of scenarios where my queries fail due to that limitation. I tried using (first: N) option in the query but did not work quite well for very nested recursive structures.

**It will be nice if the user is able to configure the gRPC max size as a parameter when starting the dgraph server.**

**Comment by manishrjain** [comment]
We could set it to max, and let users decide how to use them.

**Comment by peterstace** [comment]
GRPC max frame size is 4GB (this is a technical limitation inherent to GRPC). If we set max size to 4GB on the server side, then the client can essentially choose what size they would like when they set their dial options.

**Comment by magallardo** [comment]
Setting the max on the server side will be the best. The client API has the already the capabilities to control the desired size.

**Comment by peterstace** [comment]
I've increased the max msg size to 4GB on the server side (in master at 1014364 , will appear in the next release).

**Comment by magallardo** [comment]
@peterstace Thanks for the prompt response. Will this be available on tomorrow!s build?

**Comment by peterstace** [comment]
Yes, it will be available in tomorrow's nightly build. I expect that we'll do another patch release soon as well.
