### ISSUE TITLE
Error while installing dgraph

### ISSUE THREAD

**Issue by SumanSingh4** [dgraph-io/dgraph#1869]
Hello,

I am installing dgraph on Mac version 10.11.6.

I follow the steps instructed:-
1. Run [curl https://get.dgraph.io -sSf | bash]
2. On dgraph I got version **Dgraph version   : v0.9.4**
3. Then Run, dgraph zero --port_offset -2000
I got error
`Setting up listener at: 0.0.0.0:5080
Setting up listener at: 0.0.0.0:6080
2017/12/04 16:18:53 Error while opening WAL store error: manifest has unsupported version: 2 (we support 4)`.

I don't have any idea regarding this.Please help.

Thanks in advance

**Comment by peterstace** [comment]
Hi @SumanSingh4 ,

The error looks like an incompatibility between dgraph v0.9.4 and an existing data directory.

Can you confirm that you have existing dgraph data directories? They should look like `w`, `p`, `wz`. If you don't care about the data in them, they can safely be deleted.

**Comment by SumanSingh4** [comment]
Hi @peterstace 

Thanks for your response.

How can I confirm that I have existing dgraph data directories. I have started working on dgraph and installed yesterday . SO I have no idea how can I have already existing dgraph data directories.

Thanks in advance.

**Comment by peterstace** [comment]
By default, the data directories are called `w`, `p`, and `wz`. Can you copy/paste a directory listing from the directory where you ran `dgraph zero --port_offset -2000`? It shouldn't have `w`, `p`, or `wz`. If they're there, you can run `rm -r w p wz` to get rid of them.

**Comment by SumanSingh4** [comment]
Thanks @peterstace 

Now its working now.

**Comment by peterstace** [comment]
Awesome! Feel free to reach out on Slack or Discuss if you run into any more problems.
