### ISSUE TITLE
Not able to load datasheet in dgraph as per instruction

### ISSUE THREAD

**Issue by SumanSingh4** [dgraph-io/dgraph#1890]
Hi,

I am taking tour in dgraph.
I am just stuck in step [https://tour.dgraph.io/moredata/1/](url), can't load the datasheet on my dgraph, getting error
`docker: command not found`

I am not using docker, but there is no other way to upload data for non-docker user.
Is there any other way to upload datasheet?

Thanks in advance.

**Comment by janardhan1993** [comment]
@SumanSingh4: The tour uses the dgraph running locally on your machine. 
You can install dgraph using the instructions at https://docs.dgraph.io/get-started/#step-1-install-dgraph on your machine and use the commands without docker.

**Comment by SumanSingh4** [comment]
@janardhan1993 
Thanks for your response.

So how can I load the external datasheet in my dgraph?

There's no other command for that.

Thanks in advance.

**Comment by janardhan1993** [comment]
What  do you mean by datasheet, is it in csv format? Either you need to use our client api to import json or you can search for some csv to n triples converter online and use dgraph live/bulk loader.

**Comment by SumanSingh4** [comment]
I have just download the file you have provided on [https://github.com/dgraph-io/tutorial/blob/master/resources/1million.rdf.gz](url).

**Comment by SumanSingh4** [comment]
@janardhan1993  Thanks for your time, I already got the command

[dgraph live -r 1million.rdf --zero localhost:5080](url)
