### ISSUE TITLE
Dgraph leader not able to contact other peers

### ISSUE THREAD

**Issue by ansham22** [dgraph-io/dgraph#1891]
We have a 3 node cluster with 3 zero and 3 dgraph. We have upgraded our cluster to v0.9.4 as we were facing issue as mentioned in https://github.com/dgraph-io/dgraph/issues/1832. This has fixed our leader lost issue.

But today we faced an issue where leader wasn't able to contact other nodes and gave this error. 

2017/12/07 14:41:30 node.go:338: Error while sending message to node Id: 1, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/12/07 14:41:30 node.go:338: Error while sending message to node Id: 1, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/12/07 14:41:30 node.go:338: Error while sending message to node Id: 1, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/12/07 14:41:30 node.go:338: Error while sending message to node Id: 1, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/12/07 14:41:30 node.go:338: Error while sending message to node Id: 1, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/12/07 14:41:30 node.go:338: Error while sending message to node Id: 1, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/12/07 14:41:30 node.go:338: Error while sending message to node Id: 1, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/12/07 14:41:30 node.go:338: Error while sending message to node Id: 1, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/12/07 14:41:30 node.go:338: Error while sending message to node Id: 1, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/12/07 14:41:30 node.go:338: Error while sending message to node Id: 1, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/12/07 14:41:30 node.go:338: Error while sending message to node Id: 1, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/12/07 18:52:02 node.go:338: Error while sending message to node Id: 2, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded

state of my cluster was pretty fine. what i did is restart node 1 and node 2 and it started working again. Networking between the nodes was also fine when issue come up.

Dgraph version   : v0.9.4
Commit SHA-1     : 779fc787
Commit timestamp : 2017-12-04 17:17:23 +1100
Branch           : HEAD

For Dgraph official documentation, visit https://docs.dgraph.io.
For discussions about Dgraph     , visit https://discuss.dgraph.io.
To say hi to the community       , visit https://dgraph.slack.com.

**Comment by ansham22** [comment]
I want to add here is i can see in my system monitoring graph that at times dgraph usage on all nodes is high and almost 100%.

![image](https://user-images.githubusercontent.com/8057362/33718037-0bce2dde-db82-11e7-88a4-f2ba2fba63a8.png)

![image](https://user-images.githubusercontent.com/8057362/33718069-330c5ae2-db82-11e7-842b-cac238aee2c2.png)

**Comment by janardhan1993** [comment]
@ansham22 : It would be great if you could share some steps to reproduce the issue

**Comment by ansham22** [comment]
@janardhan1993 we have observed high load and cpu consumption of dgraph process increasing with time, this causes machine responding slow and dgraph starts choking. the above graph shows the same. Whenever I restart, it becomes stable but does increase with time

**Comment by janardhan1993** [comment]
I am closing this issue. We can track the high load issue at #1914
