### ISSUE TITLE
dgraph server gets confused about who the leader is

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1893]
**To reproduce:** (I've managed to reproduce this reliably)

I used the `peter/use-only-leader-zero` branch which allows bulk/live loader to use multiple dgraph zero's correctly, but this would apply to master as well.

1. Start 3 dgraph zeros.
2. Start a single dgraph.
3. Run live loader.

Repeatedly:
1. Find out which zero is the leader via the `/state` endpoint.
2. Kill the leader.
3. Bring back up the loader after a short while.

Eventually, dgraph will get confused about who the loader is, and repeatedly show the following in its log between steps 2 and 3:
```
2017/12/08 13:01:42 pool.go:167: Echo error from localhost:5082. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/12/08 13:01:44 Error while retrieving timestamps: rpc error: code = Unknown desc = Assigning IDs is only allowed on leader.. Will retry...
2017/12/08 13:01:52 pool.go:167: Echo error from localhost:5082. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/12/08 13:01:54 Error while retrieving timestamps: rpc error: code = Unknown desc = Assigning IDs is only allowed on leader.. Will retry...
2017/12/08 13:02:02 pool.go:167: Echo error from localhost:5082. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/12/08 13:02:04 Error while retrieving timestamps: rpc error: code = Unknown desc = Assigning IDs is only allowed on leader.. Will retry...
```

Even after bringing back up the killed dgraph zero (so all 3 are now running ok), we still get the following in the log:

```
2017/12/08 13:03:34 Error while retrieving timestamps: rpc error: code = Unknown desc = Assigning IDs is only allowed on leader.. Will retry...
2017/12/08 13:03:44 Error while retrieving timestamps: rpc error: code = Unknown desc = Assigning IDs is only allowed on leader.. Will retry...
2017/12/08 13:03:54 Error while retrieving timestamps: rpc error: code = Unknown desc = Assigning IDs is only allowed on leader.. Will retry...
2017/12/08 13:04:04 Error while retrieving timestamps: rpc error: code = Unknown desc = Assigning IDs is only allowed on leader.. Will retry...
```
The continues indefinitely.

The only way I've found to fix the situation is to randomly kill and restart dgraph zero instances (or more reliably, shut them all down and restart).

**Comment by janardhan1993** [comment]
This was related to the stream getting stuck on linerizable read(Raft can reject read index request internally in async way and we would be waiting on the channel indefinitely). Since the dgraph server didn't receive any update on the stream it doesn't know who is the new leader of group zero now and keeps sending request to wrong server. 

But when we kill the zero to which the stream is connected, the dgraph node would see error and try to  create a new stream to other zero server. So it starts working after restart.
This should have been fixed by my change where i added a timeout for waitlinearizable read in zero.

**Comment by peterstace** [comment]
Are you talking about d9ec2e4f in master? I saw this issue after that.

**Comment by peterstace** [comment]
^^ Nevermind, I got a bit confused about different branches. Confirming this is now fixed.
