### ISSUE TITLE
Dgraph zero doesn't always respond to SIGTERM

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1898]
Using dgraph v0.9.4.

To reproduce:

1. `dgraph zero -o -1999 --idx 1`
2. (wait a few seconds)
3. `dgraph zero -o -1998 --peer localhost:5081 --idx 2`
4. (wait a few seconds)
5. `dgraph bulk -r ~/r/benchmarks/data/21million.rdf.gz -s ~/r/benchmarks/data/21million.schema -z localhost:5081`
6. (wait a few seconds)
7. Attempt to kill the leader using Ctrl-C (the first one that started). Nothing happens, no matter how many SIGTERMs are sent.

Seems to be triggered when the signal is caught while zero is doing something like handing out a uid range (the bug doesn't happen if zero is idle).

Logs from the leader:
```
2017/12/08 15:06:01 node.go:191: 		SENDING: MsgApp 1-->2
2017/12/08 15:06:01 node.go:536: RECEIVED: MsgAppResp 2-->1
2017/12/08 15:06:01 node.go:536: RECEIVED: MsgAppResp 2-->1
2017/12/08 15:06:01 node.go:191: 		SENDING: MsgApp 1-->2
^CShutting down...
2017/12/08 15:06:01 gRpc server stopped : accept tcp [::]:5081: use of closed network connection
2017/12/08 15:06:01 Stopped taking more http(s) requests. Err: accept tcp [::]:6081: use of closed network connection
2017/12/08 15:06:01 All http(s) requests finished.
2017/12/08 15:06:01 node.go:191: 		SENDING: MsgApp 1-->2
2017/12/08 15:06:03 raft.go:793: WARN: 1 stepped down to follower since quorum is not active
2017/12/08 15:06:03 raft.go:567: INFO: 1 became follower at term 2
2017/12/08 15:06:03 node.go:307: INFO: raft.node: 1 lost leader 1 at term 2
2017/12/08 15:06:07 raft.go:749: INFO: 1 is starting a new election at term 2
2017/12/08 15:06:07 raft.go:580: INFO: 1 became candidate at term 3
2017/12/08 15:06:07 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 3
2017/12/08 15:06:07 raft.go:651: INFO: 1 [logterm: 2, index: 662] sent MsgVote request to 2 at term 3
2017/12/08 15:06:07 node.go:191: 		SENDING: MsgVote 1-->2
^C2017/12/08 15:06:09 raft.go:749: INFO: 1 is starting a new election at term 3
2017/12/08 15:06:09 raft.go:580: INFO: 1 became candidate at term 4
2017/12/08 15:06:09 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 4
2017/12/08 15:06:09 raft.go:651: INFO: 1 [logterm: 2, index: 662] sent MsgVote request to 2 at term 4
2017/12/08 15:06:09 node.go:191: 		SENDING: MsgVote 1-->2
^C^C^C^C^C^C^C^C^C^C^C^C2017/12/08 15:06:12 raft.go:749: INFO: 1 is starting a new election at term 4
2017/12/08 15:06:12 raft.go:580: INFO: 1 became candidate at term 5
2017/12/08 15:06:12 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 5
2017/12/08 15:06:12 raft.go:651: INFO: 1 [logterm: 2, index: 662] sent MsgVote request to 2 at term 5
2017/12/08 15:06:12 node.go:191: 		SENDING: MsgVote 1-->2
^C^C^C^C^C^C^C^C^C^C^C^C^C2017/12/08 15:06:16 raft.go:749: INFO: 1 is starting a new election at term 5
2017/12/08 15:06:16 raft.go:580: INFO: 1 became candidate at term 6
2017/12/08 15:06:16 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 6
2017/12/08 15:06:16 raft.go:651: INFO: 1 [logterm: 2, index: 662] sent MsgVote request to 2 at term 6
2017/12/08 15:06:16 node.go:191: 		SENDING: MsgVote 1-->2
^C^C^C^C^C^C^C^C^C^C^C^C^C^C2017/12/08 15:06:19 raft.go:749: INFO: 1 is starting a new election at term 6
```

`^CShutting down...` was the first time I sent a SIGTERM via Ctrl-C. Additional Ctrl-Cs have no effect.

**Comment by janardhan1993** [comment]
Fixed in master.

**Comment by peterstace** [comment]
This is still happening (reproducible in the same way).

**Comment by pawanrawal** [comment]
I have been trying to reproduce this but haven't been able to. I tried reducing the size of the batch for assigning uids to `100` so that it happens more often with no luck. @peterstace have you noticed this happening recently?

**Comment by peterstace** [comment]
Yeah, I've still seen it happen occasionally using the latest master. Although it's not as easily reproducible as it was before (it used to happen every single time). That suggests to me that there is another place in the code where things aren't being cancelled correctly when we intercept SIGINT (other than the place when Jan made a fix).

**Comment by pawanrawal** [comment]
Have been able to reproduce this. Its much easier to reproduce it with the Dgraph Server running and using the live loader.

**Comment by pawanrawal** [comment]
This isn't easily reproducible. So moving it to `v1.x`. Also doing a `kill -9` should be ok with Zero.

**Comment by peterstace** [comment]
I managed to reproduce enough times to work out what was going and create a fix. It's happening because `GracefulStop()` blocks until all pending RPCs have been completed. For some reason (not really sure why... some other unrelated problem it seems) RPCs sometimes fail to complete.

A solution is to only wait a fixed amount of time for `GracefulStop()` to complete. If it doesn't complete quickly enough, then just do a `Stop()`.
