### ISSUE TITLE
runtime error during long lasting data load process

### ISSUE THREAD

**Issue by vseledkin** [dgraph-io/dgraph#1903]
Reproducing is problematic because it took 2 days before data load process was interrupted by node failure; Mac Hight Sierra 16gb; data loaded from remote machine through golang client

./dgraph --help
Dgraph version   : v0.9.4-dev
Commit SHA-1     : a84e22c9
Commit timestamp : 2017-12-08 22:08:50 +1100
Branch           : HEAD

# start zero
./dgraph zero --my=192.168.1.27:7080 --wal zw
----------- zero log --------
2017/12/10 19:43:43 oracle.go:85: purging below ts:229810, len(o.commits):8, len(o.aborts):0
2017/12/10 19:43:53 oracle.go:85: purging below ts:229826, len(o.commits):8, len(o.aborts):0
2017/12/10 19:44:03 oracle.go:85: purging below ts:229842, len(o.commits):8, len(o.aborts):0
2017/12/10 19:44:13 oracle.go:85: purging below ts:229858, len(o.commits):8, len(o.aborts):0
2017/12/10 19:44:23 oracle.go:85: purging below ts:229874, len(o.commits):9, len(o.aborts):0
2017/12/10 19:44:33 oracle.go:85: purging below ts:229894, len(o.commits):10, len(o.aborts):0
2017/12/10 19:44:43 oracle.go:85: purging below ts:229908, len(o.commits):7, len(o.aborts):0
2017/12/10 19:44:54 pool.go:167: Echo error from 192.168.1.27:7081. Err: rpc error: code = Unavailable desc = transport is closing
2017/12/10 19:44:54 oracle.go:381: Error while fetching minTs from group 1, err: rpc error: code = Unavailable desc = transport is closing
2017/12/10 19:45:03 oracle.go:375: No healthy connection found to leader of group 1
2017/12/10 19:45:04 pool.go:167: Echo error from 192.168.1.27:7081. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/12/10 19:45:13 oracle.go:375: No healthy connection found to leader of group 1
2017/12/10 19:45:14 pool.go:167: Echo error from 192.168.1.27:7081. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/12/10 19:45:23 oracle.go:375: No healthy connection found to leader of group 1
2017/12/10 19:45:24 pool.go:167: Echo error from 192.168.1.27:7081. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
------------
#start single data node
./dgraph server \
--memory_mb=1024 \
--my=192.168.1.27:7081 \
--zero=192.168.1.27:7080 \
--port_offset=1 \
 --ui ../assets

..... last log output lines .......
2017/12/10 19:43:34 lru.go:79: LRU cache max size is being set to 50 MB
2017/12/10 19:43:44 lru.go:79: LRU cache max size is being set to 50 MB
2017/12/10 19:43:54 lru.go:79: LRU cache max size is being set to 50 MB
2017/12/10 19:44:04 lru.go:79: LRU cache max size is being set to 50 MB
2017/12/10 19:44:14 lru.go:79: LRU cache max size is being set to 50 MB
2017/12/10 19:44:24 lru.go:79: LRU cache max size is being set to 50 MB
2017/12/10 19:44:34 wal.go:118: Writing snapshot to WAL, metadata: {ConfState:{Nodes:[1] XXX_unrecognized:[]} Index:11605681 Term:2 XXX_unrecognized:[]}, len(data): 30
2017/12/10 19:44:34 lru.go:79: LRU cache max size is being set to 50 MB
2017/12/10 19:44:44 lru.go:79: LRU cache max size is being set to 50 MB
panic: runtime error: index out of range

goroutine 1222 [running]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.(*ValueStruct).Decode(0xc48fa51a20, 0xc4a4282720, 0x0, 0x10)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/iterator.go:62 +0x10b
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.(*Iterator).Value(0xc4a98fbb60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/iterator.go:390 +0x72
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.(*MergeIterator).Value(0xc43e32b4a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/iterator.go:206 +0x94
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Iterator).parseItem(0xc4a99e03f0, 0xc498166b01)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:401 +0x131
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Iterator).Next(0xc4a99e03f0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:322 +0x158
github.com/dgraph-io/dgraph/worker.(*groupi).calculateTabletSizes(0xc420134080, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/worker/groups.go:211 +0x33e
github.com/dgraph-io/dgraph/worker.(*groupi).periodicMembershipUpdate(0xc420134080)
	/ext-go/1/src/github.com/dgraph-io/dgraph/worker/groups.go:488 +0x52a
created by github.com/dgraph-io/dgraph/worker.StartRaftNodes
	/ext-go/1/src/github.com/dgraph-io/dgraph/worker/groups.go:131 +0x7b6
----------------

**Comment by janardhan1993** [comment]
Can you please share your p directory ?

**Comment by vseledkin** [comment]
It is huge, but i’ll try to i bit later

**Comment by vseledkin** [comment]
hm it is over 30GB may be you need just some of the files from directory? here is a list of:

-rw-r--r--  1 vseledkin  staff  1073742073  9 дек 21:28 000000.vlog
-rw-r--r--  1 vseledkin  staff  1073741923  9 дек 22:32 000001.vlog
-rw-r--r--  1 vseledkin  staff  1073741969  9 дек 23:47 000002.vlog
-rw-r--r--  1 vseledkin  staff  1073741948 10 дек 01:06 000003.vlog
-rw-r--r--  1 vseledkin  staff  1073741908 10 дек 02:27 000004.vlog
-rw-r--r--  1 vseledkin  staff  1073741935 10 дек 03:37 000005.vlog
-rw-r--r--  1 vseledkin  staff  1073741892 10 дек 04:39 000006.vlog
-rw-r--r--  1 vseledkin  staff  1073741937 10 дек 05:26 000007.vlog
-rw-r--r--  1 vseledkin  staff  1073742763 10 дек 06:19 000008.vlog
-rw-r--r--  1 vseledkin  staff  1073741967 10 дек 07:21 000010.vlog
-rw-r--r--  1 vseledkin  staff  1073742459 10 дек 08:39 000014.vlog
-rw-r--r--  1 vseledkin  staff  1073741889 10 дек 10:07 000016.vlog
-rw-r--r--  1 vseledkin  staff  1073741859 10 дек 10:47 000017.vlog
-rw-r--r--  1 vseledkin  staff  1073741935 10 дек 11:34 000018.vlog
-rw-r--r--  1 vseledkin  staff  1073741960 10 дек 12:42 000019.vlog
-rw-r--r--  1 vseledkin  staff  1073741917 10 дек 13:46 000020.vlog
-rw-r--r--  1 vseledkin  staff  1073741898 10 дек 14:48 000021.vlog
-rw-r--r--  1 vseledkin  staff  1073741984 10 дек 15:40 000022.vlog
-rw-r--r--  1 vseledkin  staff  1073741944 10 дек 16:19 000023.vlog
-rw-r--r--  1 vseledkin  staff  1073754725 10 дек 16:57 000024.vlog
-rw-r--r--  1 vseledkin  staff  1073741909 10 дек 17:54 000026.vlog
-rw-r--r--  1 vseledkin  staff  1073744361 10 дек 18:07 000027.vlog
-rw-r--r--  1 vseledkin  staff  1073776407 10 дек 18:21 000028.vlog
-rw-r--r--  1 vseledkin  staff  1073749606 10 дек 18:59 000029.vlog
-rw-r--r--  1 vseledkin  staff  1073767398 10 дек 19:12 000030.vlog
-rw-r--r--  1 vseledkin  staff  1073763944 10 дек 19:22 000031.vlog
-rw-r--r--  1 vseledkin  staff  1073744036 10 дек 19:37 000033.vlog
-rw-r--r--  1 vseledkin  staff  1073741989 11 дек 03:02 000034.vlog
-rw-r--r--  1 vseledkin  staff    90197578 11 дек 06:10 000035.vlog
-rw-r--r--  1 vseledkin  staff    72701341  9 дек 23:54 000052.sst
-rw-r--r--  1 vseledkin  staff    72701316 10 дек 05:13 000154.sst
-rw-r--r--  1 vseledkin  staff    72701322 10 дек 11:36 000312.sst
-rw-r--r--  1 vseledkin  staff    72701317 10 дек 13:39 000367.sst
-rw-r--r--  1 vseledkin  staff    78293715 10 дек 13:39 000368.sst
-rw-r--r--  1 vseledkin  staff    72701315 10 дек 13:39 000369.sst
-rw-r--r--  1 vseledkin  staff    72701339 10 дек 14:43 000383.sst
-rw-r--r--  1 vseledkin  staff    72701322 10 дек 14:43 000385.sst
-rw-r--r--  1 vseledkin  staff    72701320 10 дек 16:46 000421.sst
-rw-r--r--  1 vseledkin  staff    72701336 10 дек 18:11 000458.sst
-rw-r--r--  1 vseledkin  staff    72701328 10 дек 18:11 000459.sst
-rw-r--r--  1 vseledkin  staff    57933602 10 дек 18:11 000460.sst
-rw-r--r--  1 vseledkin  staff    72701310 10 дек 19:13 000467.sst
-rw-r--r--  1 vseledkin  staff    72701324 10 дек 19:13 000468.sst
-rw-r--r--  1 vseledkin  staff    56072189 10 дек 19:13 000470.sst
-rw-r--r--  1 vseledkin  staff    72701337 10 дек 19:13 000471.sst
-rw-r--r--  1 vseledkin  staff    72701334 10 дек 19:13 000472.sst
-rw-r--r--  1 vseledkin  staff    78293715 10 дек 19:13 000473.sst
-rw-r--r--  1 vseledkin  staff    72701337 10 дек 19:13 000474.sst
-rw-r--r--  1 vseledkin  staff    72701371 10 дек 19:13 000475.sst
-rw-r--r--  1 vseledkin  staff    72701333 10 дек 19:13 000476.sst
-rw-r--r--  1 vseledkin  staff    72701330 10 дек 19:13 000477.sst
-rw-r--r--  1 vseledkin  staff    72701332 10 дек 19:13 000478.sst
-rw-r--r--  1 vseledkin  staff    72701340 10 дек 19:13 000479.sst
-rw-r--r--  1 vseledkin  staff    72701327 10 дек 19:13 000480.sst
-rw-r--r--  1 vseledkin  staff    72701315 10 дек 19:13 000481.sst
-rw-r--r--  1 vseledkin  staff    72701333 10 дек 19:13 000482.sst
-rw-r--r--  1 vseledkin  staff    72701343 10 дек 19:13 000483.sst
-rw-r--r--  1 vseledkin  staff    72701334 10 дек 19:14 000484.sst
-rw-r--r--  1 vseledkin  staff    72701335 10 дек 19:14 000485.sst
-rw-r--r--  1 vseledkin  staff    72701310 10 дек 19:14 000486.sst
-rw-r--r--  1 vseledkin  staff    72701335 10 дек 19:14 000487.sst
-rw-r--r--  1 vseledkin  staff    72701338 10 дек 19:14 000488.sst
-rw-r--r--  1 vseledkin  staff    42998786 10 дек 19:14 000489.sst
-rw-r--r--  1 vseledkin  staff    72701314 10 дек 19:14 000490.sst
-rw-r--r--  1 vseledkin  staff    72701324 10 дек 19:14 000491.sst
-rw-r--r--  1 vseledkin  staff    45631950 10 дек 19:14 000492.sst
-rw-r--r--  1 vseledkin  staff    27203309 10 дек 19:22 000493.sst
-rw-r--r--  1 vseledkin  staff    22750180 10 дек 19:33 000494.sst
-rw-r--r--  1 vseledkin  staff    24261737 11 дек 03:02 000495.sst
-rw-r--r--  1 vseledkin  staff    34406268 11 дек 03:02 000496.sst
-rw-r--r--  1 vseledkin  staff           6 11 дек 00:50 LOCK
-rw-r--r--  1 vseledkin  staff        8024 11 дек 03:02 MANIFEST

**Comment by janardhan1993** [comment]
@vseledkin Can you please share just the *.sst files and MANIFEST

**Comment by vseledkin** [comment]
@janardhan1993 sent link to archive to your graph.io mail

**Comment by janardhan1993** [comment]
@vseledkin: I was not able to reproduce the error, are you still getting this error ? Can you share the sst files at the moment when you see this error.

**Comment by vseledkin** [comment]
I’ll try to reproduce, but as I mentioned earlier it took two days of continuous data load process

**Comment by janardhan1993** [comment]
We will look into it again after v1.0 release as i was not able to reproduce the issue.

**Comment by janardhan1993** [comment]
I couldn't reproduce this in latest version, please reopen it if you still see the issue.
