### ISSUE TITLE
Sparse / partial indexes

### ISSUE THREAD

**Issue by nikolakanacki** [dgraph-io/dgraph#1904]
How hard would it be (and could it be possible?) to implement [sparse indexes](https://docs.mongodb.com/v3.4/core/index-sparse/) (which may already exist) or better yet [partial indexes](https://docs.mongodb.com/v3.4/core/index-partial/) from MongoDB?

Im just thinking about the features Dgraph has to offer as a general purpose database (think CMS and all the things people do with it, ecommerce and whatnot) and it seams like it could be a pretty good fit, I think I even read in one of your blog posts that this was your idea originally.. but the "everything falls into the same basket as a node in a graph" paradigm is hard for me to wrap my head around.

Since we have no collections / tables, there is no real way to tell different "types" of records from one another - we are determining it from it's shape. For an example, we are not querying for a Post, we are querying for whatever node has a "body" field (just an example). So, I figured, to make this more robust and explicit one could add a "type" field to the global schema, put an index on it, all good - now all posts have `"type": "user"` and, say, attachments have `"type": "attachment"`.

Now, I want to index fields only on certain "types" but not the others. For an example I would like to be able to lookup "Post" type by "createdAt" date field but, altho I need the field to be present, I don't need the "createdAt" index on the "Attachment" type and all of its nodes since I wont be querying it in such a way. It is my understanding that the index is needed for sorting capabilities as well, so this is pretty crucial, and we cannot just index everything *on everything* since OOM shutdown is just around the corner.

Sparse indexes could help this - I could make "createdAt" field named differently for the attachment type, lets say "attachmentCreatedAt" - and it wouldn't be picked up by an index created for "createdAt" field (this may be how things work now). Partial indexes would go the extra mile of doing this in a nicer, non-hacky way, and would also introduce extra features like "index only featured posts". Think `@index` directive joined with a `@filter` directive.

**Comment by nikolakanacki** [comment]
While at it - I would be nice to have some guidelines on how this (broad?) use case could be tackled, like a recommended way, "best practices", or an example of managing different collections of data in dgraph.

**Comment by sorenhoyer** [comment]
Considering dgraph for a new CMS so i'd be interested to hear if there are any plans to implement this any time soon?

**Comment by srfrog** [comment]
@nikolakanacki after reading the MongoDB description of partial indexes, I think this is something that could be accomplished now (to some degree) using hash index and filtering on facets.
e.g.,
```
{
  data(func: eq(type, "Attachment")) {
    file @facets(lt(timestamp, "2019-01-01")) {
      name
    }
  }
}
```
There's some more work to do with facets that can expand on this.You can also write your own custom tokenizer that implements a new type of index - https://docs.dgraph.io/query-language/#indexing-with-custom-tokenizers

**Comment by manishrjain** [comment]
I think what this issue wants is to partially only index docs based on certain criterion. A good solution that you can have right now, is to set the property (/edge) on the node as `post.createdAt` separately from `attachment.createdAt`. And index that.

In general, what's not clear to me, is what are the savings here, and if those savings are worth the logic that'd need to be put in place. Dgraph works differently from MongoDB, and their storage requirements would be quite different from how Dgraph stores things. All our indices are essentially sorted int lists, with a great compression ratio, for e.g.

I'd say, if this becomes an issue, file an experience report, so we can look into it. For now, I'm closing this old issue.
