### ISSUE TITLE
GraphQL+ grammar / syntax specs

### ISSUE THREAD

**Issue by nikolakanacki** [dgraph-io/dgraph#1905]
Is there any docs for GraphQL+ grammar? Thinking about implementing a query / mutation builder in js.

**Comment by peterstace** [comment]
There aren't any docs right now for the grammar. That's something we could look at adding though (any grammar documentation would be descriptive rather than prescriptive though).

**Comment by manishrjain** [comment]
➤ Manish Jain commented:

Sorry, we don't have any plans to write an official GraphQL\+\- grammar. We're also looking at supporting other languages, like Cypher and Gremlin.
