### ISSUE TITLE
Allow `has` function to receive multiple parameter values 

### ISSUE THREAD

**Issue by liqweed** [dgraph-io/dgraph#1909]
Allow the `has` function to receive multiple parameter values (similarly to how `anyofterms` us used or with different syntax). 

I'm trying to use the `has` function to identify "types" as suggested in https://docs.dgraph.io/howto/#giving-nodes-a-type but it's common for the query to narrow on any of a few possible options for the type.

We are generating dynamic queries and rendering a single `func` or several combinations of `func` and `@filter` (with `or`s in between) is very awkward.

**Comment by manishrjain** [comment]
You can use `@filter` if you want to intersect, or using variable assignment and `uid` to merge two invocations to `has`. I think all the ingredients are already there, there's no need to extend has function itself.
