### ISSUE TITLE
DGraph not able to handle load after apprx 1.5mil nodes creation

### ISSUE THREAD

**Issue by ajayktkp** [dgraph-io/dgraph#1910]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
0.9.4

- Have you tried reproducing the issue with latest release?
using the latest release

- What is the hardware spec (RAM, OS)?
16gb ram/30gb ssd

- Steps to reproduce the issue (command/config used to run Dgraph).
I'm running a single server dgraph node on (16 gb ram and 30gb ssd).  
1. When the dgraph was freshly created, the search and mutation query was taking <1sec
2. After pushing around 1.5mil nodes, the search was taking between 3mins to59 mins and mutation query even taking around 5mins to 10hrs.

The average no. of dgraph queries which I'm trying are **10 per sec**. (This query is upsert, so first it fetches existing node's id and then creates relationship with the id. )

A sample mutation query is:
_:u <user_id> "2523532" .
_:f <phone_number> "071212626112113" .
_:f <name> "PHONE" .
_:u <name> "USER" .
_:u <user_name> "NONE" .
_:u <PhoneNumber> _:f .

Program which is pushing data to DGraph is running since Friday.

The error which I was getting from dgraph clients are:
%of Time            ERROR
0.21%    rpc error: code = Unavailable desc = all SubConns are in TransientFailure
0.37%    rpc error: code = Unavailable desc = stream terminated by RST_STREAM with error code: REFUSED_STREAM
85.61%    rpc error: code = Unavailable desc = the server stops accepting new RPCs
12.44%    rpc error: code = Unavailable desc = transport is closing
1.36%    rpc error: code = Unknown desc = No connection exists

- Expected behaviour and actual result.
Ideally dgraph should be able to read/write data after inserting 1/2 mil nodes but it's not working as expected.

**Comment by ajayktkp** [comment]
[dgraphtosend.log](https://github.com/dgraph-io/dgraph/files/1547662/dgraphtosend.log)
[dgraphzerotosend.log](https://github.com/dgraph-io/dgraph/files/1547663/dgraphzerotosend.log)

**Comment by ajayktkp** [comment]
if you start a pipeline with 9-10 upsert queries/sec, you will get the same scenario around after about 1.5 mil nodes insertion.

**Comment by MichelDiz** [comment]
I have the same settings. I got over 75,000 nodes after that image below. And it only had a little more latency delay because the query asks for an absurd amount of users. Others Query have had an ok time latency. But as my environment is testing I do not know if it counts. ps. The terminal sometimes gives many errors.

![esboco 8](https://user-images.githubusercontent.com/6570955/33848208-cf5bca70-de8b-11e7-807e-8471ae0c1f7f.png)

**Comment by janardhan1993** [comment]
@MichelDiz : Can you please share your queries and mutations.

**Comment by MichelDiz** [comment]
@janardhan1993 sure, but I have no problem. I Just commented to have it an "positive example" to ajayktkp. I did not comment to say that I have an error. I should have made that clear. Do you still wanna the queries and mutations? cheers

**Comment by janardhan1993** [comment]
If you feel there is a preformance issue, please feel free to share or raise a separate issue.

**Comment by MichelDiz** [comment]
No preformance issue for me but here
https://gist.github.com/MichelDiz/a33715eba824b92e0021f21b61de97a4

**Comment by janardhan1993** [comment]
@ajayktkp : Can you please try your load on a fresh instance and using dgraph built from latest master. The load issue should be fixed now.

**Comment by janardhan1993** [comment]
@ajayktkp : I tried loading using the program you shared, was able to load without much cpu usage.

Please reopen the issue if you still face any problems.
