### ISSUE TITLE
Confusing environment based mutation bug

### ISSUE THREAD

**Issue by dpeek** [dgraph-io/dgraph#1912]
I'm experiencing what I think is a bug that only occurs on my CI environment (Travis). I'm running dgraph:latest in docker (both locally and on CI) and seeing consistent failure of two tests in a ~70 test suite.

The basic issue seems to be that edges aren't being created for new nodes, such that with this mutation:

```
mutate: { set {
  <0x1> <children> <0x2> .
  <0x1> <children> _:node0 .
  _:node0 <name> "Eve" .
}}
```

The edge `0x1 -> 0x2` gets created but not `0x1 -> node0`. I don't think it's a transaction issue as the response from dgraph says the mutation is successful (including the uid for node0).

Here is the isolated test case failing on Travis:
https://travis-ci.org/dpeek/dgraphql/builds/315401258

And here is the test in question (which is more or less dependency free – just remove the jest `test()` call and call `testcase()` directly:
https://github.com/dpeek/dgraphql/blob/dgraph9/src/__tests__/travis.test.js

On Travis the response from the query is:

```
{
  "data": {
    "person": [
      {
        "__typename": "Person",
        "name": "Tim",
        "children": [
          {
            "__typename": "Person",
            "name": "Tom",
            "parents": [
              {
                "__typename": "Person",
                "name": "Tim"
              }
            ]
          }
        ]
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 30622,
      "processing_ns": 3498088,
      "encoding_ns": 587423
    },
    "txn": {
      "start_ts": 8,
      "lin_read": {
        "ids": {
          "1": 10
        }
      }
    }
  }
}
```

Run locally, the response from the query is, as expected:

```
{
  "data": {
    "person": [
      {
        "__typename": "Person",
        "name": "Tim",
        "children": [
          {
            "__typename": "Person",
            "name": "Eve",
            "parents": [
              {
                "__typename": "Person",
                "name": "Tim"
              }
            ]
          },
          {
            "__typename": "Person",
            "name": "Tom",
            "parents": [
              {
                "__typename": "Person",
                "name": "Tim"
              }
            ]
          }
        ]
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 17800,
      "processing_ns": 4220600,
      "encoding_ns": 604800
    },
    "txn": {
      "start_ts": 16,
      "lin_read": {
        "ids": {
          "1": 17
        }
      }
    }
  }
}
```

Any thoughts on what might be going on?

**Comment by dpeek** [comment]
Here's my `docker-compose.yml` (used locally and on Travis), incase that helps:
https://github.com/dpeek/dgraphql/blob/dgraph9/docker-compose.yml

**Comment by peterstace** [comment]
Can you add logging from dgraph server and dgraph zero to the travis output?

**Comment by dpeek** [comment]
Not sure how I'd do that.. do you mean stdout from server/zero? That might be beyond my docker skills but I can investigate... I guess you would have to pipe output to a log file and then dump those at the end. Will investigate unless you have some helpful suggestions :)

**Comment by janardhan1993** [comment]
@dpeek: Which version of dgraph are you using, can you please try it on latest version 0.9.4.

**Comment by dpeek** [comment]
@janardhan1993 I assume it's the latest, as per the `docker-compose.yml`

```
...
services:
  zero:
    image: dgraph/dgraph:latest
    command: dgraph zero --port_offset -2000 --my=zero:5080
...
```

**Comment by janardhan1993** [comment]
Sorry for the confusion, This issue has been fixed in master. Can you please try using dgraph:master on travis.

**Comment by dpeek** [comment]
You fixed it, thank you! What was the issue, out of interest? I can't see a commit that seems like it's the one that fixed it...

**Comment by janardhan1993** [comment]
@dpeek Here's the commit https://github.com/dgraph-io/dgraph/commit/1d0d5019f060b48605618a96a74cc3ffbdd145ec. It was due to slow disk writes on travis hard disk.
