### ISSUE TITLE
Add a helm chart for using Dgraph

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1917]
Now that we have a config for running Dgraph using Kubernetes, we should also add a helm chart at https://github.com/kubernetes/helm.

**Comment by AceHack** [comment]
This would be a great feature

**Comment by pawanrawal** [comment]
@sboorlagadda do you have experience with this or would like to take a look at it?

**Comment by sboorlagadda** [comment]
I can pick it up.

**Comment by llonchj** [comment]
@sboorlagadda what is the status of this task?

**Comment by clanstyles** [comment]
Any updates?

**Comment by george-oakling** [comment]
Can I help with helm chart?

**Comment by manishrjain** [comment]
Sure.

**Comment by danielmai** [comment]
@george-oakling do you have any updates with the helm chart?

**Comment by SandeepVaman** [comment]
I am interested in contributing to this task.  I will work on it this weekend.

**Comment by goern** [comment]
Maybe its also worth having a look at https://github.com/operator-framework

**Comment by danielmai** [comment]
#3264 added a Dgraph helm chart in the contrib directory.

**Comment by goern** [comment]
we started working on a Dgraph operator is you are interested have a look at https://github.com/thoth-station/dgraph-operator

**Comment by markmssd** [comment]
I would love to help creating a Helm chat. I could start with a minimal working version, then work toward a production grade one.

I’m also a fan of DGraph and I think its adoption would be much faster with a better DX.

That could potentially help for the DaaS later on.

**Comment by danielmai** [comment]
Hey @markmssd. A Dgraph Helm chart is already available at https://github.com/dgraph-io/dgraph/tree/master/contrib/config/kubernetes/helm. We're definitely open to any suggestions you have for improving the existing chart.
