### ISSUE TITLE
Getting an error while doing go get for dgraph

### ISSUE THREAD

**Issue by avinassh** [dgraph-io/dgraph#1926]
I am following the instructions here: https://docs.dgraph.io/contribute/#setup-dgraph-from-source-repo

I am using go version 1.9.2 and when I did go get, I got the following error:

```
$ go get -t -v github.com/dgraph-io/dgraph/...

dgraph-io/dgraph/wiki/resources/examples/goclient/crawlerRDF/crawler.go:96:2: no Go files in /Users/avi/.go/src/github.com/dgraph-io/dgraph/protos
```

**Comment by peterstace** [comment]
Thanks for bringing this to our attention. The crawler code looks like it hasn't been maintained at all and doesn't work with dgraph 0.9.x. I'll work out if we want to upgrade it or just remove it.

**Comment by peterstace** [comment]
I've updated the instructions as well (there are a few extra commands that need to be run rather than just `go get`.

**Comment by avinassh** [comment]
Actually, that also fails. I updated the instructions: https://github.com/dgraph-io/dgraph/compare/master...avinassh:install-inst?expand=1 

I think we need to install those in $GOPATH. If this change is correct, would you like a PR?

**Comment by peterstace** [comment]
> would you like a PR?

Yes please.

**Comment by svmhdvn** [comment]
I'm actually getting these errors again on a fresh checkout of dgraph using the instructions listed in CONTRIBUTING.md. Are the docs out of date again? I would like to get this working so I can start working on a PR.

```sh
$ pwd
/Users/siva.mahadevan
$ go get -u -v -t github.com/dgraph-io/dgraph/...
[...]
$ cd ~/go/src/github.com/dgraph-io/dgraph
$ ./test.sh
contrib/scripts/functions.sh: line 5: pushd: /src/github.com/dgraph-io/dgraph/dgraph: No such file or directory
Password:
can't load package: package github.com/dgraph-io/dgraph: no Go files in /Users/siva.mahadevan/go/src/github.com/dgraph-io/dgraph
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
[...]
```

Environment:

```sh
$ go version
go version go1.11.1 darwin/amd64
```
