### ISSUE TITLE
Allow entities to have UIDs automatically generated

### ISSUE THREAD

**Issue by Rahul-Sagore** [dgraph-io/dgraph#193]
@manishrjain Currently the user has to specify the UIDS manually for entities. Need to write the code to generate it automatically every time new entity gets created.

**Comment by ashwin95r** [comment]
This feature has been added to master in 5dad80b23ca0caff57daaa45ac4abab3d123e5f8.

**Comment by manishrjain** [comment]
@ashwin95r -- please close the issue when you implement it.
