### ISSUE TITLE
Mutation gets stuck if in progress when leader dies

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1931]
Occurs in master at dc3f4601, run on the dgraph workstation.

Easy to consistently reproduce:

1. 1 dgraph zero, with replicas set to 3.
2. 3 dgraph servers.
3. Run the `bigdata` binary (in `contrib/integration`) with `--mode=mutate`.
4. Kill the leader.
5. The mutation that is currently in progress will block forever (neither the error or success counters increase). It remains stuck even after several minutes, even after a new leader has been elected. If I kill the `bigdata` binary and restart it, everything works again, so _new_ mutations aren't stopped, only ones that are running while the leader dies.

Note: new mutations aren't blocked and users should have timeouts on their requests anyway, so this shouldn't affect anyone (unless they aren't using timeouts). It _does_ indicate that something a bit weird is going on though.

**Comment by pawanrawal** [comment]
This happens when a follower received a request and a leader was killed. The follower is stuck waiting on the channel for proposal to be marked as done. Since there is no timeout, the mutation is stuck.

**Comment by pawanrawal** [comment]
On further investigation, I have found that since the `send` method fails, the proposal isn't retried by Raft. Proposals with type `MsgProp` have to be handled by the network library. See https://github.com/coreos/etcd/issues/3380. Etcd has a timeout on proposals and doesn't retry them in such cases.

**Comment by pawanrawal** [comment]
Fixed via 6a24586e3f9bf359109b2e8975bae7b35a4192b8.
