### ISSUE TITLE
StartTs doesn't need to be part of api.Operation

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1933]
Since it's set as 1 everywhere.

**Comment by janardhan1993** [comment]
We need it for postings, schema change can cause the index to be rebuild that needs a timestamp.
Only schema changes are uses fixed timestamp(1)

**Comment by pawanrawal** [comment]
Ok, so it still doesn't need to be part of `protos.Operation`. It can just be set as part of `protos.Mutation` when doing a schema mutation. The user shouldn't have the option to set it directly as part of `Operation` message.

**Comment by pawanrawal** [comment]
In master as of 46f7825b09c6ba82cf05ca3c13b1bcbe3d4841c7.
