### ISSUE TITLE
Tried changing posting-lists without read-update-write ?

### ISSUE THREAD

**Issue by ddorian** [dgraph-io/dgraph#1936]
What I saw from some docs is that badger is like rocksdb (lsm) and not lmdb (btree) so you have custom merge functions and non-reading-inserts.

Have you tried doing:
1. add another field to the PostingList called (operation='remove/set/update/add').
2. On every update/delete, actually just put another PostingList but the operation changes based on what it is, without reading the current PostingList.

On read/merge:
1. retrieve all PostingList on the same key ordered by timestamp
2. merge them , in the end you'll have only 1 PostingList which you save on `merge` or use on `read`

Makes sense ?

**Comment by manishrjain** [comment]
Thanks for the suggestion. We're doing something similar.

Given this is a suggestion and not an issue, I'll close this.
