### ISSUE TITLE
High CPU usage in dgraph v1.0.0 when I don't do any queries/mutations

### ISSUE THREAD

**Issue by sgon00** [dgraph-io/dgraph#1938]
**Dgraph version:**

```
Dgraph version   : v1.0.0
Commit SHA-1     : 7a64f54b
Commit timestamp : 2017-12-18 15:04:40 +0530
Branch           : HEAD
```

**Dgraph linux binary:** `dgraph-linux-amd64-v1.0.0.tar.gz`

**OS:** `Manjaro` (Based on `Arch Linux`. I consider it's the same as arch linux)

**How do I run dgraph:**

```
dgraph zero --port_offset -2000 -w ${db_path}/zw/ >> ${log_file_zero} 2>&1 &
sleep 10
dgraph server --memory_mb 1024 --zero localhost:5080 -p ${db_path}/p/  -w ${db_path}/w/ >> ${log_file_server} 2>&1 &
```

1. Create the schema by following https://tour.dgraph.io/moredata/1/
2. Load the dataset with `dgraph live -r 1million.rdf.gz --zero localhost:5080`
3. Shutdown and Restart dgraph zero and server to free up RAM.
4. Apply the schema mutation at https://tour.dgraph.io/search/1/

After the above 4 steps, the CPU usage is high about 40% busy when I don't do anything. I tried to shutdown and restart the dgraph zero and server many times. The CPU usage is always high when idle. It's not high all the time. It follows some kind of patterns. The CPU usage is high for several minutes, low for several minutes and then high again.

This never happens in pre v1.0.0 versions such as v0.9.4, v0.9.2 etc...

BTW,  when I shutdown the dgraph server properly with `curl http://localhost:8080/admin/shutdown`, I always see the following snippet:

```
goroutine 511 [running]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).sendToWriteCh(0xc420444300, 0x0, 0x0, 0x0, 0x10, 0x10, 0xc43218e460)
    /home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:609 +0x15f
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).batchSet(0xc420444300, 0x0, 0x0, 0x0, 0x0, 0x10)
    /home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:679 +0x4d
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).purgeVersionsBelow(0xc420444300, 0xc43345d290, 0xc43218e460, 0x10, 0x10, 0x8, 0x0, 0x0)
    /home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:931 +0x453
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*ManagedDB).PurgeVersionsBelow(0xc42014e138, 0xc43218e460, 0x10, 0x10, 0x8, 0x0, 0x0)
    /home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/managed_db.go:79 +0x127
github.com/dgraph-io/dgraph/posting.periodicPurgeOldVersions.func1()
    /home/travis/gopath/src/github.com/dgraph-io/dgraph/posting/lists.go:244 +0x2a2
github.com/dgraph-io/dgraph/posting.periodicPurgeOldVersions()
    /home/travis/gopath/src/github.com/dgraph-io/dgraph/posting/lists.go:254 +0x40
created by github.com/dgraph-io/dgraph/posting.Init
    /home/travis/gopath/src/github.com/dgraph-io/dgraph/posting/lists.go:211 +0xe1
```

I am not sure if this is related or not. This never appears before version 1.0.

One more werid part in version 1.0.0 is if I remove `sleep 10` in the above script when I start dgraph, that means dgraph zero and server start at the same time. I can see about **9000 lines** of:

```
2017/12/19 15:39:27 groups.go:673: Error in oracle delta stream. Error: rpc error: code = Unknown desc = Node is no longer leader.
```

in the dgraph server log (stdout). 

I don't think this is expected and never see such behavior before version 1.0. I am not sure if I should open another bug for this or not. 

I attached three CPU profiles:

[pprof.dgraph.samples.cpu.001.pb.gz](https://github.com/dgraph-io/dgraph/files/1571828/pprof.dgraph.samples.cpu.001.pb.gz)

[pprof.dgraph.samples.cpu.002.pb.gz](https://github.com/dgraph-io/dgraph/files/1571830/pprof.dgraph.samples.cpu.002.pb.gz)

[pprof.dgraph.samples.cpu.003.pb.gz](https://github.com/dgraph-io/dgraph/files/1571865/pprof.dgraph.samples.cpu.003.pb.gz)

**Comment by janardhan1993** [comment]
@sgon00 
`2017/12/19 15:39:27 groups.go:673: Error in oracle delta stream. Error: rpc error: code = Unknown desc = Node is no longer leader.` error is expected when there's no active leader of group zero. During restart it takes some time for zero to become leader and hence dgraph servers try to find a zero which is leader.
I have added sleeps between retries now so you shouldn't see this. 
You didn't see this issue before because of bug which was fixed in v1.0, but since there was only one zero and it eventually became leader so the system worked fine at the end.

The panic is due to some background goroutine, i will make a fix to stop it during clean shutdown. But it doesn't affect anything.

**Comment by sgon00** [comment]
@janardhan1993 thanks a lot for the quick reply and investigation. About 9000 error messages in the log within a second made me feel bad. :) 
What about the CPU usage problem? I hope that can be fixed soon. It's burning my laptop. I can not use dgraph if it uses too much CPU constantly when I don't anything to it. Thanks a lot.

**Comment by selmeci** [comment]
I have same problem with docker compose environment on my desktop.
It began when I imported about 14M data-set.  
CPU usage goes up after I make first query on DB.

**Comment by janardhan1993** [comment]
We are working on it, will fix it in next release.

**Comment by mbn18** [comment]
Have the same problem with 1.1

Every few minutes the `dgraph` process CPU utilization get to around 170% for a minute or so.

The machine is: Intel `i7-4790k` With `SSD` & `16GB RAM` + the 1mil DB from the tutorial

From the machine/OS (fedora 27) perspective other DBs like `PostgreSQL` & `ElasticSearch` work as expected. Let me know if you need more info

**Comment by janardhan1993** [comment]
@mbn18 Can you please share the cpu profile when it goes high.

Most probably it's related to purging older versions which happens in background. We changed the way purge works in badger to make it efficient and fast. Will vendor in the change in dgraph after some testing.

**Comment by mbn18** [comment]
@janardhan1993 ,
No problem.
Any doc on how to profile the CPU?

**Comment by janardhan1993** [comment]
https://docs.dgraph.io/howto/#retrieving-debug-information @mbn18

**Comment by mbn18** [comment]
The CPU profile is attached. Its started few sec before the load start and finish few sec after the load get down.

I also noticed that the load/offload takes 30 seconds.

[pprof.dgraph.samples.cpu.004.pb.gz](https://github.com/dgraph-io/dgraph/files/1638726/pprof.dgraph.samples.cpu.004.pb.gz)

**Comment by janardhan1993** [comment]
Fixed in master, @mbn18 Can you please try using master.

**Comment by mbn18** [comment]
@janardhan1993 , 
By master you mean the latest docker that is tagged as master?

**Comment by janardhan1993** [comment]
Yeah dgraph:master, please pull again it has been updated just now

**Comment by samhuss** [comment]
I'm having the same cpu issue, however I couldn't find dgraph:master, only dgraph/dgraph is available. Would you please point to the correct one marked as master?

**Comment by mbn18** [comment]
@samhuss 
`docker pull dgraph/dgraph:master`

@janardhan1993 
Something is broken or maybe changed since `1.0.2`

`docker run --rm -it -p 8081:8081 -p 8080:8080 -p 9080:9080 -v /home/miki/Projects/Epoch/dgraph/db:/dgraph --name dgraph dgraph/dgraph:master dgraph zero --port_offset=-2000`

	Setting up grpc listener at: 0.0.0.0:3080
	Setting up http listener at: 0.0.0.0:4080
	2018/02/01 11:53:12 node.go:258: Group 0 found 0 entries
	2018/02/01 11:53:12 raft.go:567: INFO: 1 became follower at term 0
	2018/02/01 11:53:12 raft.go:315: INFO: newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
	2018/02/01 11:53:12 raft.go:567: INFO: 1 became follower at term 1
	Running Dgraph zero...
	2018/02/01 11:53:12 node.go:127: Setting conf state to nodes:1
	2018/02/01 11:53:16 raft.go:749: INFO: 1 is starting a new election at term 1
	2018/02/01 11:53:16 raft.go:580: INFO: 1 became candidate at term 2
	2018/02/01 11:53:16 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 2
	2018/02/01 11:53:16 raft.go:621: INFO: 1 became leader at term 2
	2018/02/01 11:53:16 node.go:301: INFO: raft.node: 1 elected leader 1 at term 2

`docker exec -it dgraph dgraph server --bindall=true --memory_mb 2048 --zero localhost:5080`

	2018/02/01 11:54:21 groups.go:86: Current Raft Id: 0
	2018/02/01 11:54:21 gRPC server started.  Listening on port 9080
	2018/02/01 11:54:21 HTTP server started.  Listening on port 8080
	2018/02/01 11:54:21 worker.go:99: Worker listening at address: [::]:7080
	2018/02/01 11:54:21 pool.go:168: Echo error from localhost:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
	2018/02/01 11:54:21 pool.go:118: == CONNECT ==> Setting localhost:5080
	2018/02/01 11:54:21 groups.go:102: Error while connecting with group zero: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
	2018/02/01 11:54:21 groups.go:102: Error while connecting with group zero: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
	2018/02/01 11:54:22 groups.go:102: Error while connecting with group zero: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
	2018/02/01 11:54:22 groups.go:102: Error while connecting with group zero: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
	2018/02/01 11:54:22 groups.go:102: Error while connecting with group zero: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
	2018/02/01 11:54:23 groups.go:102: Error while connecting with group zero: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
	2018/02/01 11:54:25 groups.go:102: Error while connecting with group zero: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
	2018/02/01 11:54:28 groups.go:102: Error while connecting with group zero: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
	2018/02/01 11:54:31 pool.go:168: Echo error from localhost:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
	2018/02/01 11:54:34 groups.go:102: Error while connecting with group zero: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
	2018/02/01 11:54:41 pool.go:168: Echo error from localhost:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
	2018/02/01 11:54:47 Unable to join cluster via dgraphzero
	github.com/dgraph-io/dgraph/x.Fatalf
		/home/pawan/go/src/github.com/dgraph-io/dgraph/x/error.go:103
	github.com/dgraph-io/dgraph/worker.StartRaftNodes
		/home/pawan/go/src/github.com/dgraph-io/dgraph/worker/groups.go:107
	runtime.goexit
		/usr/local/go/src/runtime/asm_amd64.s:2337

**Comment by samhuss** [comment]
@mbn18 
Thanks, that worked

**Comment by samhuss** [comment]
After pulling the latest from master, still having the same cpu issue and now even worse. The cpu runs in 200+ without executing any queries in the browser

[pprof.dgraph.samples.cpu.001.pb.gz](https://github.com/dgraph-io/dgraph/files/1685788/pprof.dgraph.samples.cpu.001.pb.gz)

**Comment by janardhan1993** [comment]
@mbn18, the default port for zero has been changed, it now runs at 3080 instead of 5080, so please use -zero="localhost:3080"

**Comment by janardhan1993** [comment]
@samhuss  DId you take the cpu profile when the cpu usage was high, i don't see anything except http requests in the profile, can you please send a png if possible.

**Comment by samhuss** [comment]
@janardhan1993 
unfortunately I had to figure out the new ports myself, I removed "--port_offset" option from the zero command to keep the old ports as is 5080,6080 

running dgraph/dgraph:master on empty folder is not working, gives the following errors, as a work around I imported data using :latest then running :master on the same folder, which also didn't work properly

I'm using 2 docker-compose files for "latest" and "master" with the same volume of data, I'm not sure whether "master" can read the same data generated by "latest" or not as currently "master" doesn't run on "latest" data

server_1  | 2018/02/03 11:33:38 pool.go:118: == CONNECT ==> Setting localhost:5080
server_1  | 2018/02/03 11:33:38 draft.go:140: Node ID: 1 with GroupID: 1
server_1  | 2018/02/03 11:33:38 node.go:258: Group 1 found 0 entries
server_1  | 2018/02/03 11:33:38 draft.go:672: New Node for group: 1
server_1  | 2018/02/03 11:33:38 raft.go:567: INFO: 1 became follower at term 0
server_1  | Error while proposing initial schema:  Tablet isn't being served by this instance.
server_1  | 2018/02/03 11:33:38 raft.go:315: INFO: newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
server_1  | 2018/02/03 11:33:38 raft.go:567: INFO: 1 became follower at term 1
server_1  | 2018/02/03 11:33:38 groups.go:296: Asking if I can serve tablet for: _predicate_
server_1  | 2018/02/03 11:33:38 groups.go:434: WARNING: We don't have address of any dgraphzero server.
server_1  | 2018/02/03 11:33:38 groups.go:653: WARNING: We don't have address of any dgraphzero server.
server_1  | 2018/02/03 11:33:38 node.go:127: Setting conf state to nodes:1
server_1  | 2018/02/03 11:33:38 raft.go:749: INFO: 1 is starting a new election at term 1
server_1  | 2018/02/03 11:33:38 raft.go:580: INFO: 1 became candidate at term 2
server_1  | 2018/02/03 11:33:38 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 2
server_1  | 2018/02/03 11:33:38 raft.go:621: INFO: 1 became leader at term 2
server_1  | 2018/02/03 11:33:38 node.go:301: INFO: raft.node: 1 elected leader 1 at term 2
server_1  | Error while proposing initial schema:  Tablet isn't being served by this instance.
server_1  | 2018/02/03 11:33:38 groups.go:296: Asking if I can serve tablet for: _predicate_
server_1  | 2018/02/03 11:33:38 groups.go:296: Asking if I can serve tablet for: _predicate_
server_1  | Error while proposing initial schema:  Tablet isn't being served by this instance.
server_1  | Error while proposing initial schema:  Tablet isn't being served by this instance.
server_1  | 2018/02/03 11:33:38 groups.go:296: Asking if I can serve tablet for: _predicate_
server_1  | Error while proposing initial schema:  Tablet isn't being served by this instance.
server_1  | 2018/02/03 11:33:39 groups.go:296: Asking if I can serve tablet for: _predicate_
server_1  | 2018/02/03 11:33:39 groups.go:296: Asking if I can serve tablet for: _predicate_
server_1  | Error while proposing initial schema:  Tablet isn't being served by this instance.
server_1  | 2018/02/03 11:33:39 groups.go:296: Asking if I can serve tablet for: _predicate_
server_1  | Error while proposing initial schema:  Tablet isn't being served by this instance.
server_1  | 2018/02/03 11:33:39 groups.go:296: Asking if I can serve tablet for: 
......
etc......

**Comment by mbn18** [comment]
@janardhan1993 
Tested with a `master` that pulled on feb 5. Seems to be fixed. Thanks

Also, plz fix relevant info in doc and [tutorial](https://tour.dgraph.io/intro/2/) regarding the new ports. both `zero` `5080->3080` and `dgraph-ratel` `8081->8000`.

**Comment by samhuss** [comment]
@pawanrawal 
attached docker-compose and the console output log for master pulled on Feb 2. I'm using zero without port offset to keep using 5080,6080 as usual

will try latest master of today and check whether the error still there or not

[master-log.txt](https://github.com/dgraph-io/dgraph/files/1695408/master-log.txt)

[dc-master.yml.txt](https://github.com/dgraph-io/dgraph/files/1695410/dc-master.yml.txt)

**Comment by samhuss** [comment]
The commands below work only when executed directly to console but never inside docker-compose (attached)

I'm using dgraph/dgraph:master updated Feb 5
still sever can not catch up with zero and gives the previous error, however currently I'm running the instance using the following commands to run :master


docker run --rm -it -p 8081:8081 -p 8080:8080 -p 9080:9080 -v ~/dgraph:/dgraph --name dgraph dgraph/dgraph:master dgraph zero --port_offset=-2000

docker exec -it dgraph dgraph server --bindall=true --memory_mb 1048 --zero localhost:3080

docker exec -it dgraph dgraph-ratel


[dc-master.yml.txt](https://github.com/dgraph-io/dgraph/files/1695607/dc-master.yml.txt)

**Comment by sboorlagadda** [comment]
> The commands below work only when executed directly to console but never inside docker-compose (attached)

@samhuss Could you try adding `--my=zero:5080(or 3080) & --my=server:7080` to respective commands in the compose file. The commands are working because they are all running in a single container (where the grpc addr is set to localhost if `--my` is left out and so works as server can reach zero on localhost). But when run in compose these are 3 separate containers and thus needs `--my`.

Use [docker-compose](https://github.com/dgraph-io/dgraph/blob/master/contrib/config/docker/docker-compose.yml) for your reference and let me know if that works.

**Comment by sboorlagadda** [comment]
@mbn18 I will get the tutorial docs fixed. The default port of Zero is changed to 5080 from 7080 and so user does not have to provide an offset `--port_offset -2000`. When you containue to provide an offset of `-2000` then the port becomes (5080-2000=3080). 

Please see #2042

**Comment by mbn18** [comment]
@sboorlagadda , just curios. Why there is an option for an offset?

**Comment by sboorlagadda** [comment]
> just curios. Why there is an option for an offset?

@mbn18 It is to avoid port conflicts when dgraph is run on a single host (non-containerized). Earlier to this #2042 change there is a single default port(7080) among zeros & servers and users has to set offset depending on their topology (no of zeros & servers), but now with this change users can still use offset between zero(and its peers) or servers(and its peers).

**Comment by samhuss** [comment]
@sboorlagadda I've tried all the options for almost an hour with no luck, I don't know when "zero" runs it listens to ports 5080, 6080, 8080, 9080, while "server" listens to only 8080, 9080, and ratel listens to 8080.
May that explains why it runs on single container from console while not running by compose from 3 different containers
I'm giving up this as it took so much time. I believe that the new port numbers are not fixed everywhere and some places still not refactored

**Comment by sboorlagadda** [comment]
@samhuss If you are using :master tagged docker image then I see that only ratel's port is not set to new default, though its fixed in code to be 8000 (may be it is not fully rolled into the docker image). I will get this verified and fix it (if required). The ports that you listed that respective container is listening seems to be confusing and are exposed in the actual Dockerfile though zero & ratel does not use 8080/9090. 

The actual ports are published from with in the docker-compose file by explicitly setting `-ports`. So for now you can ignore if `docker ps` shows 8080/9090 for zero & ratel, but in-addition they should also show they are listening on 5080, 6080 & 8081 respectively.

The actual problem can be seen from the logs:
```
server_1  | 2018/02/05 18:38:21 groups.go:109: Connected to group zero. Connection state: member:<id:1 group_id:1 addr:"server:7080" > state:<counter:4 groups:<key:1 value:<members:<key:1 value:<id:1 group_id:1 addr:"server:7080" > > > > zeros:<key:1 value:<id:1 addr:"localhost:5080" > > maxRaftId:1 >
```
See here the state shows zero's addr is `localhost:5080` instead of `zero:5080`, so is why I asked to use `--my` option.

Also could be due to re-using the /tmp/data or existing docker volume as the state is persisted).
Could you try these to see if the problem still persists?

1. Try deleting these directories:
- /tmp/data (if any)
- /tmp/dgraph (if any)

2. Remove docker volumes (if any):
```docker volume rm docker_dgraph```

3. Make sure no dgraph containers are running.

4. Save this docker-compose to a file.
```
version: "3.2"
services:
  zero:
    image: dgraph/dgraph:master
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  server:
    image: dgraph/dgraph:master
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph server --my=server:7080 --memory_mb=2048 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:master
    ports:
      - 8081:8081
    command: dgraph-ratel
```
5. docker-compose up

**Comment by samhuss** [comment]
@sboorlagadda 
Thanks for your thorough explanation. I tried your compose with no luck, seems the problem in ratel now not in zero or server as both are running without errors. 

Let's not deviate from the main problem which is the high CPU after running any query. I was advised to use dgraph/dgraph:master to avoid this issue. 

I will be waiting for a fix in dgraph/dgraph:latest

**Comment by pawanrawal** [comment]
@samhuss high CPU usage could happen when running a query. The usage is high because we make good use of concurrency to get good performance out of the system. The original issue was about high CPU usage when **not** running a query/mutation.

**Comment by janardhan1993** [comment]
I am closing this issue as it was about high CPU usage when not running a query/mutation. 

@samhuss  If you are seeing high cpu usage while doing query please file a different issue with details about the query.
