### ISSUE TITLE
Bulk loader cannot handle double typed literals

### ISSUE THREAD

**Issue by tomsaleeba** [dgraph-io/dgraph#1951]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.1. Zero and Server running in Docker and bulk loader directly on the host.

- Have you tried reproducing the issue with latest release?
Yes, 1.0.1 is the latest at the time of writing.

- What is the hardware spec (RAM, OS)?
Intel I7, 16GB ram, Linux Mint 18.2

- Steps to reproduce the issue (command/config used to run Dgraph).
  1. start a Dgraph cluster to load to
  1. create an RDF file `double-literal.rdf` with a single triple:
  ```
  <http://www.example.com#thing1> <http://www.example.com#value> "11.96"^^<http://www.w3.org/2001/XMLSchema#decimal> .
  ```
  1. create an empty file to be the schema, call it `blank.schema`
  1. perform a bulk load with something like
  ```
  ./dgraph bulk -r double-literal.rdf -s blank.schema -z localhost:7080
  ```

- Expected behaviour and actual result.
I expect that the data loads as the input is a valid NQuad. The actual result is an error complaining about the typing for the literal:
```
2017/12/22 17:33:22 Unrecognized rdf type http://www.w3.org/2001/XMLSchema#decimal
while parsing line "<http://www.example.com#thing1> <http://www.example.com#value> \"11.96\"^^<http://www.w3.org/2001/XMLSchema#decimal> ."
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*mapper).parseRDF
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/mapper.go:180
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*mapper).run
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/mapper.go:133
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*loader).mapStage.func1
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/loader.go:217
runtime.goexit
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:2337

github.com/dgraph-io/dgraph/x.Wrap
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:79
github.com/dgraph-io/dgraph/x.Check
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:41
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*mapper).run
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/mapper.go:133
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*loader).mapStage.func1
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/loader.go:217
runtime.goexit
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:2337
```

You link to the spec on NQuads at https://www.w3.org/TR/n-quads/#sec-literals. The typed literals are mentioned here https://www.w3.org/TR/rdf11-concepts/#dfn-recognized-datatype-iris and the list of supported types is at https://www.w3.org/TR/rdf11-concepts/#xsd-datatypes.

If you removed the typing and try to load:
```
<http://www.example.com#thing1> <http://www.example.com#value> "11.96" .
```
It all works as expected. Also, changing the typing to integer (and removing the decimal place) works too:
```
<http://www.example.com#thing1> <http://www.example.com#value> "11"^^<http://www.w3.org/2001/XMLSchema#integer> .
```

**Comment by janardhan1993** [comment]
We don't support decimal type yet. You can use xs:double or <http://www.w3.org/2001/XMLSchema#double" instead of that. Double rdf type should be sufficient for most of the use cases unless you require very high precision(too many digits after decimal).

**Comment by janardhan1993** [comment]
I am closing this issue now, you can use double type instead of decimal. Please feel free to reopen the issue if your usecase requires decimal type.

**Comment by tomsaleeba** [comment]
Thanks @janardhan1993. My choice for decimal was arbitrary, I don't need to precision, so changing to double is a perfect fix for this.
