### ISSUE TITLE
Self building schema can't support RDF bags with varying contents

### ISSUE THREAD

**Issue by tomsaleeba** [dgraph-io/dgraph#1952]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.1. Zero and Server running in Docker and bulk loader directly on the host.

- Have you tried reproducing the issue with latest release?
Yes, 1.0.1 is the latest at the time of writing.

- What is the hardware spec (RAM, OS)?
Intel I7, 16GB ram, Linux Mint 18.2

- Steps to reproduce the issue (command/config used to run Dgraph).
  - start a fresh Dgraph cluster
  - create an RDF input file with two RDF bags. One contains an element that points to another resource, the second bag contains an element that is a literal. Use the following contents for the file `bags.rdf`:
  ```
    <http://example.com#objectbag1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag> .
    <http://example.com#objectbag1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#_1> <http://example.com#thingy2> .
    <http://example.com#thingy2> <http://example.com#name> "foo" .
    <http://example.com#literalbag1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Bag> .
    <http://example.com#literalbag1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#_1> "bar" .
  ```
  - create an empty file for the schema, call it `blank.schema`
  - perform a bulk load with something like:
  ```
  ./dgraph bulk -r bags.rdf -s blank.schema -z localhost:7080
  ```
- Expected behaviour and actual result.
This could totally be my fault and I need to learn how to define a schema that can support multiple types. I'm still learning Dgraph. I expected that I could load this valid RDF but it fails with the message:
```
RDF doesn't match schema: Input for predicate http://www.w3.org/1999/02/22-rdf-syntax-ns#_1 of type uid is scalar
```

If you swap the order of the two bags in the file, you get the opposite error as you'd expect:
```
RDF doesn't match schema: Input for predicate http://www.w3.org/1999/02/22-rdf-syntax-ns#_1 of type scalar is uid
```
That is, uid and scalar have switched places. This is what you'd expect as Dgraph is building the schema as it sees the data.

Nobody wants to write a schema that handles every possible bag index number as property names so perhaps my real mistake is that I shouldn't be loading RDF bags. Does Dgraph have support for unordered lists that I could use somehow?

**Comment by janardhan1993** [comment]
Dgraph can handle different types for same predicate as long as they are compatible. Example: If you specify the schema type as string then everything can be converted to string and so all types can be loaded. If you specify the schema type as integer, then when you try to load a string which doesn't parse as int, dgraph would throw error.

Dgraph doesn't allow changing from uid to scalar as it is not compatible. Example you can't do something like this,
<0x1> <friend> <0x2>
<0x1> <friend> "alice". 
you need to use different predicates. Dgraph derives schema based on first mutation for a predicate if its not set  and hence you are seeing those errors.

We do have support for list type, here are the docs for that
https://docs.dgraph.io/query-language/#list-type

**Comment by janardhan1993** [comment]
The error message you saw is expected behaviour, Please feel free to reopen the issue or create a new issue if you feel the current type system is not sufficient for your use case.

**Comment by tomsaleeba** [comment]
Thanks for the information @janardhan1993.

My data uses RDF bags a lot so I can't use the Dgraph RDF loader. I'll look into writing something that converts the RDF bags into Dgraph lists.
