### ISSUE TITLE
[string] schema, Go client returns string, not []string for single element list

### ISSUE THREAD

**Issue by sporkmonger** [dgraph-io/dgraph#1956]
- What version of Dgraph are you using?
0.9.2

- Have you tried reproducing the issue with latest release?
No, haven't had a chance to upgrade yet

- What is the hardware spec (RAM, OS)?
16GB, macOS 10.12.6

- Steps to reproduce the issue (command/config used to run Dgraph).
```
docker run -it -p 8080:8080 -p 9080:9080 -v /tmp/data:/dgraph --name diggy dgraph/dgraph:v0.9.2 dgraph zero --port_offset -2000
docker exec -it diggy dgraph server --memory_mb 2048 --zero localhost:5080
```

- Expected behaviour and actual result.
With a field with a `[string]` schema, the Go client gets a `string` value, not a `[]string` for a single element list. Since the field has a `[]string` type, this results in an error on deserialization for single element lists.

**Comment by pawanrawal** [comment]
A fix has been merged to master with 99d1acebaedcdb8b3934515a88b9a2d915b07962. It would be available as part of the nightly release and also from the next release.
