### ISSUE TITLE
Edges without facet values filtered out when sorting by facet

### ISSUE THREAD

**Issue by smkhalsa** [dgraph-io/dgraph#1960]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v0.9.4

- Have you tried reproducing the issue with latest release?
no (unavailable with dgraph.js)

- What is the hardware spec (RAM, OS)?
8GB Ram, OSX

- Steps to reproduce the issue (command/config used to run Dgraph).
I have a problem node connected to many solutions nodes
I've created a facet on the edge called "sortOrder" which I'll use to sort the solutions

```
`query problemSolutions {
  problemSolutions(func: uid(<0xcceb>)) {
    solutions : solution @facets(orderasc: sortOrder, sortOrder: sortOrder) {
      ...SolutionFragment
    }
  }
}
${SolutionFragment}
`
```

When I run the above query, I only receive back edges to solutions for which the edge has a sortOrder value

- Expected behaviour and actual result.

I'd expect that all edges are returned. If I want to filter out edges with null facet values I can use a facet filter.

**Comment by pawanrawal** [comment]
A fix has been merged to master with 3a1a250425ed1d1182293794dde75d6dd05657db and would be part of the next release and nightly build.
