### ISSUE TITLE
Support stub instead of blockingStub on client initialization

### ISSUE THREAD

**Issue by gfsilva92** [dgraph-io/dgraph#1961]
I would like to be able to initialize a dgraph client without using the blockingStub, like this:

DgraphStub blockingStub = DgraphGrpc.newStub(channel);

At the moment is not possible. But I think it could be a nice improvement on your tool.

Thanks,
Gonçalo.

**Comment by janardhan1993** [comment]
This is related to java client right ? Can you please create this issue in client's repository. dgraph-io/dgraph4j

**Comment by gfsilva92** [comment]
Yes, sure! Thaks.
