### ISSUE TITLE
Generate binaries for FreeBsd and NetBsd

### ISSUE THREAD

**Issue by zilti** [dgraph-io/dgraph#1963]
For some reason it seems you *really* don't want anyone to compile the code themselves. `get.sh` says "Sorry. Binaries not available for your platform. Please compile manually: https://docs.dgraph.io", but there's nothing to be found on that page.

**Comment by janardhan1993** [comment]
we will update the link in the script.

You can compile it like any other go project.
go get -u -v -t github.com/dgraph-io/dgraph/...
This will put the source code in a Git repo under $GOPATH/src/github.com/dgraph-io/dgraph and compile the binaries to $GOPATH/bin

@zilti Which platform are you using ? Our ui is not open source so we would need to publish the binary for your platform.

**Comment by pawanrawal** [comment]
Hey @zilti 

The instructions for installing from source are mentioned at https://docs.dgraph.io/deploy/#building-from-source. I have updated the script to point to this link. As @janardhan1993 mentioned, Ratel is not open source so you won't be able to compile it manually.

**Comment by zilti** [comment]
Thank you! Ah, I didn't know that... I actually wanted to make a pkg for NetBSD, but that way, it's probably not that good an idea.

**Comment by MichelDiz** [comment]
I think this question is done, I'll close. Feel free to ask to reopen or please open a discussion in Discuss. And ref this issue.

Cheers.
