### ISSUE TITLE
Ratel dashboard sidebar and feedback sections overlays incorrectly in Safari 

### ISSUE THREAD

**Issue by vespertilian** [dgraph-io/dgraph#1972]
If you suspect this could be a bug, follow the template.

Do you support Safari? This doesn't happen in Chrome, and I can work around it, so feel free to close this issue if you don't. 

- What version of Dgraph are you using?

1.0.1

- Have you tried reproducing the issue with latest release?

Yes

- Steps to reproduce the issue (command/config used to run Dgraph).

Visit the Ratel Dashboard in Safari 11.0.2
It also happens on the dashboard on your website: https://play.dgraph.io
Press the ? or the speech bubble right hand side icon. 

- Expected behaviour and actual result.

There is an overlay that covers the sidebar when it pops out, so you cannot click any of the links. 

![screen shot 2018-01-02 at 5 04 32 pm](https://user-images.githubusercontent.com/441418/34475454-5de160a6-efe0-11e7-96e5-1bfbd3b1e213.png)

**Comment by manishrjain** [comment]
We don't currently support Safari. All of us are on Linux, so don't have a way to test this.

**Comment by MichelDiz** [comment]
Now seem to be working.
![captura de tela 2018-12-09 as 22 55 30](https://user-images.githubusercontent.com/6570955/49706599-96cf3c80-fc05-11e8-8831-fb34b8324593.png)
