### ISSUE TITLE
Add a schema quick link query to Ratel Dashboard

### ISSUE THREAD

**Issue by vespertilian** [dgraph-io/dgraph#1973]
As a new user I find the generic query below super helpful to understand what the database schema looks like, especially after I have run a few different example mutations. I feel it would be worthwhile to have this query as a quick link in your Ratel Dashboard for other newbies. I found the query on your docs site but it's a bit hidden away. 

```query 
schema {
  type
  index
  reverse
  tokenizer
}
```

![screen shot 2018-01-02 at 5 19 26 pm](https://user-images.githubusercontent.com/441418/34476283-7f6479ea-efe3-11e7-898a-ca14a086759f.png)

If you want to go even further, you could have a tab that just runs this query and returns clickable predicate. These clickable predicates could autogenerate a sample query, so you can explore the data mostly just by clicking around.

Just a though.
Dgraph seems really great so far.

**Comment by pawanrawal** [comment]
We could also think about building the functionality to mark certain queries as the favorite so that they can be accessed quickly.

**Comment by gpahal** [comment]
A schema tab has been added to the dashboard that you might useful.
