### ISSUE TITLE
Document JSON serialization for UID references

### ISSUE THREAD

**Issue by sporkmonger** [dgraph-io/dgraph#1984]
Ran into an error for `Input for predicate created_by_ref of type uid is scalar`, was extremely confused because I was passing in a json object akin to `{"uid":"0x3", "ref":"0x2"}`. Turns out I needed to pass: `{"uid":"0x3", "ref":{"uid": "0x2"}}` This doesn't appear to be documented anywhere currently.

**Comment by peterstace** [comment]
I've added some documentation (at 6e9df2b). Can be viewed here: https://docs.dgraph.io/master/mutations/#json-mutation-format
