### ISSUE TITLE
Blank nodes in JSON mutations

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1985]
Allowing blank nodes in JSON mutations would make JSON mutations easier to use.

Currently if inserting highly referential data, mutations must be applied in several steps. If we had blank nodes, it could be done in one go.

E.g.

To represent the following graph:

```
A ----> B
|       |
|       |
v       v
C ----> D
```

You would need to create D first in its own mutation, then create the other nodes using Ds UID to reference it.

But if we had blank nodes, you could just do the following mutation:

```
{
  "blank": "A",
  "link": [
    {
      "blank": "B",
      "link": {
        "blank": "D"
      },
    },
    {
      "blank": "C",
      "link": {
        "blank": "D"
      }
    }
  ]
}
```

`"blank"` would play the same role as blank nodes in RDFs.

**Comment by pawanrawal** [comment]
I think a cleaner syntax might be
```
{
  "uid": "_:A",
  "link": [
    {
      "uid": "_:B",
      "link": {
        "uid": "_:D"
      },
    },
    {
      "uid": "_:C",
      "link": {
        "uid": "_:D"
      }
    }
  ]
}
```

So if the uid starts with `_:`, we consider it as a blank node.

**Comment by pawanrawal** [comment]
Added support for this in master as of 1390aaf86aa31b50ea3f9900d943cba118775b9e.
