### ISSUE TITLE
Export count mismatch

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#1990]
CI often fails while trying to match export count.

```
[17:38:58][Step 2/3] {"code": "Success", "message": "Export completed."}
[17:38:58][Step 2/3] Export done.
[17:38:58][Step 2/3] Export test failed. Expected: 1120879 Got: 1120982
```

In this case, we get more results than expected.

https://teamcity.dgraph.io/viewLog.html?buildId=101&buildTypeId=Dgraph_Ci&tab=buildLog&_focus=3556

**Comment by peterstace** [comment]
I noticed another problem during export:

I'm seeing `2018/01/10 13:56:35 unexpected meta: 0` which is a fatal error.

**Comment by janardhan1993** [comment]
It's related to badger directory getting reused across runs and xidmap not being flushed after live loader is done loading data.

**Comment by pawanrawal** [comment]
Closing this for now. Will reopen if we notice it again in CI.
