### ISSUE TITLE
bulk: schema not loaded

### ISSUE THREAD

**Issue by llonchj** [dgraph-io/dgraph#1991]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

Dgraph 1.0.1

- Have you tried reproducing the issue with latest release?

yes

- What is the hardware spec (RAM, OS)?

MacOS 10.13.2: 16gb, 1Tb SSD

- Steps to reproduce the issue (command/config used to run Dgraph).

Using the files in: https://gist.github.com/llonchj/dda68e41680f76f9e769d523dafc57fe

1. Start Zero in a zero folder: `dgraph zero --port_offset -2000`
2. Create and cd a folder for server
3. Bulk load with ```dgraph bulk --zero_addr localhost:5080 \
                --rdfs rdfs \
                --schema_file schema.txt```
4. Start server `dgraph server --memory_mb 1024 --zero localhost:5080`
5. Query `curl http://localhost:8080/query -d 'schema {}'|jq`

- Expected behaviour and actual result.

I would expect a schema response as per `schema.txt`, Instead it appears to me an empty schema.

```json
{
  "data": {
    "schema": [
      {
        "predicate": "_predicate_",
        "type": "string",
        "list": true
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 2000,
      "processing_ns": 2000,
      "encoding_ns": 661000
    },
    "txn": {
      "start_ts": 5,
      "lin_read": {}
    }
  }
}
 ```

**Comment by llonchj** [comment]
In the above example works, but in other cases i tested does not work.

**Comment by peterstace** [comment]
Something must be happening non-deterministically... Using your RDF and schema files I've been able to reproduce this.

**Comment by peterstace** [comment]
Oh woops, when I was trying to reproduce this, I forgot to start the `dgraph server` up pointing to the output dir from the bulk loader.

When I do `$ dgraph server --memory_mb 1024 --zero localhost:5080 -p out/0/p` instead of `$ dgraph server --memory_mb 1024 --zero localhost:5080`, it works as expected.

Can you confirm that you're supplying the postings dir to `dgraph server` via the `-p` flag?

**Comment by llonchj** [comment]
I am using `mv out/0/p .` instead of `-p` or changing directory

**Comment by peterstace** [comment]
Ok, yeah that shouldn't be a problem.

I've done a review of the surrounding code, and can't see any missed error handling etc. I don't think there's much we can do to go further with this until there's a reproducible example.

**Comment by janardhan1993** [comment]
@llonchj In the other cases you tested, did you clear the p directory and did bulk loading again. 
Can you please try it with build from master. Should be fixed now.

**Comment by llonchj** [comment]
@janardhan1993 yes, i rm'd p and w. Will try master, thanks.

**Comment by llonchj** [comment]
@janardhan1993 it works. Thank you!
