### ISSUE TITLE
Support UIID in Mutate.

### ISSUE THREAD

**Issue by JimmyCheng** [dgraph-io/dgraph#1994]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.1

- Have you tried reproducing the issue with latest release?
yes.

- What is the hardware spec (RAM, OS)?
4G RAM, macOS

- Steps to reproduce the issue (command/config used to run Dgraph).
DGraph supports to import rdf format data. e.g. from the tour document:
https://tour.dgraph.io/moredata/1/
It supports to import data tuples with UIID or URI id.
But if the same statement is input from the console as a query (mutate), it failed. e.g.
`{
      set {
             <b8ee3d65-f4d2-11e7-b6df-b10a7d9e45c1> <name> "ABC" .
             <b8ee3d60-f4d2-11e7-b6df-b10a7d9e45c1> <program> <b8ee3d62-f4d2-11e7-b6df-b10a7d9e45c1> .
       }
 } 
`
Error message:
strconv.ParseUint: parsing "b8ee3d60-f4d2-11e7-b6df-b10a7d9e45c1": invalid syntax

- Expected behaviour and actual result.
I expect the query supports to read the UIID and behaves the same as importing from the rdf file.

**Comment by pawanrawal** [comment]
Dgraph doesn't support UUID as part of mutations. Dgraph live has a special behavior where it allocates a new uid(uint64) when it encounters something that it cant parse as a `uint64`.

**Comment by JimmyCheng** [comment]
Thanks @pawanrawal.

Is it possible to support UUID in mutations?

I am trying to import a set of tuples, in which the later tuples rely on the previous one. Currently I use the similar way as creating movies, actors database in [here](https://tour.dgraph.io/moredata/1/). 

But I want to do this in Java/Javascript client with dgraph transaction. In this way the database initialization is easier to manage.

**Comment by peterstace** [comment]
If you only need to refer to the nodes during graph initialisation, you could use [blank nodes](https://docs.dgraph.io/query-language/#blank-nodes-and-uid).

**Comment by tamerh** [comment]
good to know about blank nodes @peterstace a bit off the topic but what if i have 2 bulk loader which connects to same zero. are  blanks nodes works? i mean generate same uid for a blank node for both 2 bulk loader?

**Comment by JimmyCheng** [comment]
Thanks @peterstace!
