### ISSUE TITLE
Possible Ordering Option In Shortest Path Query

### ISSUE THREAD

**Issue by willcj33** [dgraph-io/dgraph#1997]
Currently, in the shortest path query, if I understand correctly, the lower the number, the higher that path is ranked. This causes me to store my "scores" on facets as the regular value, and a negative weight, which seems odd to me. It also, over time leads to useless data replication. 

Would it be possible to allow for an ```asc/desc``` option on the shortest path so I could not have to store negative weights, but instead just store my score as I will show it in the app, and rank the higher value as the more preferable path to take?

Using 1.0.1 and the Golang Client.

**Comment by campoy** [comment]
Hi there, @willcj33 

Sorry for the delay, I'm working on Dgraph now and going over all issues and just saw yours.
If I understand correctly, what you're trying to do is basically find the path with the highest value on the facets.

Unfortunately, the algorithm we support (Djikstra) does not support negative values, as any loop with a negative intrinsic value would cause an infinite path.
So, even your own solution of storing negative weights will not work.
