### ISSUE TITLE
Need for Java Driver 

### ISSUE THREAD

**Issue by hackintoshrao** [dgraph-io/dgraph#20]
As mentioned in #3 , To go ahead with establishing the performance evaluation,comparison of Dgraph with the rest of the Graph databases in the list we need a way to drive Dgraph from a Java client. And yes, Dgraph anyway needs utilities to be driven from host languages and definitely Java is on the list.  Please create a timeline/milestone/label and assignment.

**Comment by manishrjain** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JEFKKHKG&#x2F;3-java-driver"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Java Driver</a>

**Comment by manishrjain** [comment]
Tracking in Trello. Closing here.
