### ISSUE TITLE
Missing concept document

### ISSUE THREAD

**Issue by mbn18** [dgraph-io/dgraph#2010]
I think it will be beneficial for new comers if there will be a `concept document` that will explain terms like:
- node
- edge
- predicate

I read the docs and watched the Youtube clips but still find it hard to answer questions like:
> `edge` is just a named link? If so how in one of the clips I saw that `edge` is associated with value?

Or

> `Node` has a type? and what exactly is `predicate`? an indexed value in a `node`?

I think it will be much more easy to grasp if first time users will read about the system claims, its concepts and elements.

## Update
As an example: neo4j have a document that explain the concept.
Check [From Relational to Graph Databases](https://neo4j.com/developer/graph-db-vs-rdbms/#_from_relational_to_graph_databases) and its sequal topic [Data Model Transformation](https://neo4j.com/developer/graph-db-vs-rdbms/#_data_model_transformation)

**Comment by campoy** [comment]
I think this is something that either @hackintoshrao or @MichaelJCompton should work on.

Currently https://docs.dgraph.io/design-concepts/ defines edges but not nodes or facets. I wonder if that'd be a good place to define them or maybe somewhere more prominent like in the "getting started"

**Comment by danielmai** [comment]
Introductory concepts are now covered in the introductory tutorial series that's in the blog and documentation. Here's the link to the first tutorial: https://docs.dgraph.io/tutorial-1/.
