### ISSUE TITLE
add edges be very slow or impossible with 80000 nodes exist

### ISSUE THREAD

**Issue by yupengfei** [dgraph-io/dgraph#2021]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
1.0.1

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?
15.7 GiB
AMD® Ryzen 7 1700 eight-core processor × 16 
Ubuntu 17.10

- Steps to reproduce the issue (command/config used to run Dgraph).
1. Add 80000 nodes to dgraph
2. add edge through
{ 
  set{
    <0x2716>  friend  <0x2717> .
  }
}
3. it blocks

- Expected behaviour and actual result.

expected: edges can be added very quickly
actual: it blocks for a very long time, and randomly success by try and error.

**Comment by janardhan1993** [comment]
@yupengfei Can you please share your schema. Also if possible can you please share the data if it's not confidential. Are you using live loader to load the data ?

**Comment by yupengfei** [comment]
Here is the schema

`
const DSchema string = 

user_id: string @index(exact) .
user_code: string @index(exact) .
uname: string @index(exact) .
real_name: string @index(exact) .
university_name: string @index(exact) .
academy_name: string @index(exact) .
home_town: string @index(exact) .
province_name: string @index(exact) .
city_name: string @index(exact) .
phone: string @index(exact) .
talent: bool @index(bool) .
last_beckon_date: dateTime .
label: [string] @index(term) .
total_score: int @index(int) .
`

I put data like this

// PutData 插入数据
func (c *GraphClient) PutData(data interface{}) error {
	mu := &api.Mutation{
		CommitNow: true,
	}
	pb, err := json.Marshal(data)
	if err != nil {
		alog.Error(err.Error())
	}
	mu.SetJson = pb
	fmt.Println("SetJson", string(pb))
	_, err = c.Client.NewTxn().Mutate(context.Background(), mu)
	if err != nil {
		alog.Error(err.Error())
	}
	return err
}


and the data is select from mongodb

func TestSyncAllUsers(t *testing.T) {
	antmongo.OPC("userlist", func(c *mgo.Collection) {
		// var queryCount = 1000
		// var currentIndex = 0
		query := bson.M{"STATUS": "1"}

		var users []*models.User
		err := c.Find(query).All(&users)

		if err != nil {
			fmt.Println("cc")
			t.Error(err.Error())
			return
		} else if len(users) > 0 {
			c := dgraphUtil.NewClient()
			c.PutData(users)
		} else {
			fmt.Println("bb")
		}

	})
}


where models.User reads 

`

type User struct {
	// Uid
	UserID         string    `json:"user_id" bson:"UID"`
	UserCode       string    `json:"user_code" bson:"USERCODE"`
	UName          string    `json:"uname" bson:"UNAME"`
	RealName       string    `json:"real_name" bson:"REALNAME"`
	UniversityName string    `json:"university_name" bson:"UNIVERSITYNAME"`
	AcademyName    string    `json:"academy_name" bson:"ACADEMYNAME"`
	HomeTown       string    `json:"home_town" bson:"HOMETOWN"`
	ProvinceName   string    `json:"province_name" `
	CityName       string    `json:"city_name"`
	Phone          string    `json:"phone"`
	Talent         bool      `json:"talent"`
	LastBeckonDate time.Time `json:"last_beckon_date"`
	Label          []string  `json:"label"`
	TotalScore     int       `json:"total_score,omitempty" bson:"SCORE"`
}
`

and I put edges like this, first I search for the ids, and then I use SetNquads

`
// PutRelation uidA指向uidB
func (c *GraphClient) PutFriendList(relationList []*models.ContactList) error {
	ctx := context.Background()
	txn := c.Client.NewTxn()
	defer txn.Discard(ctx)

	var result []string = make([]string, 0)
	for index, item := range relationList {
		if index == 0 {
			continue
		}
		userIDA := item.UID
		userIDB := item.LISTUID
		fmt.Println("userIDA" + userIDA)
		fmt.Println("userIDB" + userIDB)

		var q = fmt.Sprintf(`
			{
				userIDEq(func: eq(user_id, "%s")) {
					uid
				}
				userIDEq(func: eq(user_id, "%s")) {
					uid
				}
			}
			`, userIDA, userIDB)
		resp, err := txn.Query(ctx, q)
		if err != nil {
			fmt.Println("什么都没查到")
			continue
		}
		var uidRepos UidRepos
		fmt.Println("bbb", string(resp.GetJson()))
		if err = json.Unmarshal(resp.GetJson(), &uidRepos); err != nil {
			// log.Fatal("ccc", err)
			fmt.Println("查询出错 " + userIDA + " " + userIDB + err.Error())
			continue
		}
		if len(uidRepos.UserIDs) != 2 {
			buf, _ := json.Marshal(uidRepos)
			fmt.Println("返回的userlist长度不对" + string(buf))
			continue
		}
		pb := fmt.Sprintf(`<%s> <%s> <%s> .`, uidRepos.UserIDs[0].UID, "friend", uidRepos.UserIDs[1].UID)
		_, err = txn.Mutate(ctx, &api.Mutation{
			SetNquads: []byte(pb),
		})
		// fmt.Println("after")
		// if err != nil {
		// 	log.Println(err.Error())
		// 	// continue
		// }
		result = append(result, pb)
	}
	fmt.Println("before")
	_, err := txn.Mutate(ctx, &api.Mutation{
		SetNquads: []byte(strings.Join(result, "\n")),
	})
	// fmt.P

	txn.Commit(ctx)
	fmt.Println("after")
	if err != nil {
		log.Println(err.Error())
		// continue
	}
	return nil
}
`

Since the data is a bit confidential, so I can not put it here.

**Comment by yupengfei** [comment]
@janardhan1993 After insert the first edge, the insertion became very fast.

**Comment by weickdev** [comment]
@yupengfei How many nodes  and edges can you insert per second？

**Comment by yupengfei** [comment]
@weickdev Above one thousand node per second, and I think the edge insertion can be hundreds, after the first insertion, which always hangs for more than ten minutes.

**Comment by weickdev** [comment]
@yupengfei comparing to the blog says [Loading close to 1M edges/sec into Dgraph](https://blog.dgraph.io/post/bulkloader/), 1000 nodes per second is too slow.

**Comment by yupengfei** [comment]
@weickdev I may have mislead you, I do not care of the speed, this average time is calculated by records count divided by the total time that my test cost. Since the terrible network and monkey code, it is not that fast. If you load big files into dgraph, it is lightning fast.

**Comment by yupengfei** [comment]
I think there is something wrong with my code, I create the same edge twice at the same time, after reimplement the logic, everything goes well, so sorry to bother.
