### ISSUE TITLE
Stacking multiple mutations within a transaction causing observable slowdown

### ISSUE THREAD

**Issue by Levatius** [dgraph-io/dgraph#2022]
- Version: 
Dgraph 1.0.1, utilising a modified version of kochhar's python client (original: https://github.com/dgraph-io/pydgraph/pull/19)

- Reproduced issue on latest: 
Yes

- Hardware specs: 
16GB, Intel Core i7-6560U @ 2.20GHz, Windows 7 (64-bit)

- Steps to reproduce: 
Run the provided test rig (scripts/mutate_slowdown_rig.py) in Python 3.6

- Expected behaviour and actual result: 
Expected there to be no increase in time taken to perform mutates over the transaction's lifespan; instead we see that the time taken to mutate X rows increases until the transaction is committed.

[mutate_slowdown_files.zip](https://github.com/dgraph-io/dgraph/files/1635064/mutate_slowdown_files.zip)

**Comment by Levatius** [comment]
@pawanrawal @vladjiman

**Comment by jimanvlad** [comment]
Massive speed gains on multiple mutations within the same transaction, thank you @janardhan1993 !
