### ISSUE TITLE
Unable to elect a new leader

### ISSUE THREAD

**Issue by jzhu077** [dgraph-io/dgraph#2024]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.1

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
A Google cloud instance with 64 CPU and 240GB of memories. 
The dgraph instances operate in docker containers. 

- Steps to reproduce the issue (command/config used to run Dgraph).
1. All dgraph servers and zeros are running in a Kubernetes pod. There are 5 dgraph zeros and 20 dgraph servers. Each of them runs in its own container. Each server and zero has an unique group ID assigned via flag idx

2. Ingest a large amount of data ~31GB 

3. Stop the running dgraph pod. (kubectl delete deployment < dgraph-cluster> )

4. Restart the pod. (kubectl apply -f <dgraph.yaml>)

- Expected behaviour and actual result.
Expected: Dgraph servers and zeros restart properly.
Actural result: 
Every dgraph zero and server errors the same message repetitively as following:

Dgraph zero:
raft.go:1070: INFO: 1 no leader at term 7; dropping index reading msg

dgraph server:
Unable to sync memberships. Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
groups.go:673: Error in oracle delta stream. Error: rpc error: code = Unknown desc = Node is no longer leader.

[More information](https://discuss.dgraph.io/t/dgraph-runs-into-a-error-loop-and-freezes-the-host/2055)

**Comment by pawanrawal** [comment]
Are you still facing this issue with `v1.0.2` @jzhu077

**Comment by jzhu077** [comment]
This is solved.
