### ISSUE TITLE
Document how to start Kubernetes cluster with data loaded by bulk loader

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#2030]
We should add instructions on how to bootstrap a Kubernetes cluster using data that was already loaded using `dgraph bulk`. This would involve modifying volumes attached to the pods.

**Comment by jsihota** [comment]
Any updates on this?

**Comment by manishrjain** [comment]
No. But, I've been using docker compose lately, and it does a pretty good job too (I'm personally not that familiar with k8s, so can't comment).
