### ISSUE TITLE
On startup, server update predicates more then once

### ISSUE THREAD

**Issue by mbn18** [dgraph-io/dgraph#2033]
###  version of Dgraph are you using?
1.0.2

### hardware spec (RAM, OS)?

Intel I7 CPU, 16GB RAM, SSD, Fedora-27 64x

### Steps to reproduce the issue

- Load the users data from the tutorial
- Load the comapny data from tutorial
- Load the 1milMovies data from tutorial

Restart server
`docker exec -it dgraph dgraph server --bindall=true --memory_mb 2048 --zero localhost:5080`

### Expected behaviour and actual result.

The output show that the server update some predicate twice. like `name`

    2018/01/18 13:55:07 mutation.go:176: Done schema update predicate:"_predicate_" value_type:STRING list:true                                                                             
    2018/01/18 13:55:07 mutation.go:176: Done schema update predicate:"name" value_type:STRING directive:INDEX tokenizer:"term"                                                             
    2018/01/18 13:55:07 mutation.go:176: Done schema update predicate:"age" value_type:INT directive:INDEX tokenizer:"int"                                                                  
    2018/01/18 13:55:07 mutation.go:176: Done schema update predicate:"friend" value_type:UID count:true                                                                                    
    2018/01/18 13:55:07 mutation.go:176: Done schema update predicate:"name" value_type:STRING directive:INDEX tokenizer:"term"                                                             
    2018/01/18 13:55:07 mutation.go:176: Done schema update predicate:"age" value_type:INT directive:INDEX tokenizer:"int"                                                                  
    2018/01/18 13:55:07 mutation.go:176: Done schema update predicate:"friend" value_type:UID count:true                                                                                    
    2018/01/18 13:55:07 mutation.go:176: Done schema update predicate:"name" value_type:STRING directive:INDEX tokenizer:"term"                                                             
    2018/01/18 13:55:07 mutation.go:176: Done schema update predicate:"age" value_type:INT directive:INDEX tokenizer:"int"                                                                  
    2018/01/18 13:55:07 mutation.go:176: Done schema update predicate:"friend" value_type:UID count:true                                                                                    
    2018/01/18 13:55:07 mutation.go:176: Done schema update predicate:"industry" value_type:STRING directive:INDEX tokenizer:"term"                                                         
    2018/01/18 13:55:07 mutation.go:176: Done schema update predicate:"boss_of" value_type:UID  
    2018/01/18 13:55:07 mutation.go:176: Done schema update predicate:"boss_of" value_type:UID directive:REVERSE

**Comment by janardhan1993** [comment]
@mbn18 Can you please list down the steps you did to load data and alter schema before restart ?

**Comment by mbn18** [comment]
@janardhan1993 , Its kinda straight forward

### [Intro page 3](https://tour.dgraph.io/intro/3/)

    name: string @index(term) .
    age: int @index(int) .
    friend: uid @count .

### [Intro page 4](https://tour.dgraph.io/intro/4/)

    {
      set {
        _:michael <name> "Michael" .
        _:michael <age> "39" .
        _:michael <friend> _:amit .
        _:michael <friend> _:sarah .
        _:michael <friend> _:sang .
        _:michael <friend> _:catalina .
        _:michael <friend> _:artyom .
        _:michael <owns_pet> _:rammy .
    
        _:amit <name> "अमित"@hi .
        _:amit <name> "অমিত"@bn .
        _:amit <name> "Amit"@en .
        _:amit <age> "35" .
        _:amit <friend> _:michael .
        _:amit <friend> _:sang .
        _:amit <friend> _:artyom .
    
        _:luke <name> "Luke"@en .
        _:luke <name> "Łukasz"@pl .
        _:luke <age> "77" .
    
        _:artyom <name> "Артём"@ru .
        _:artyom <name> "Artyom"@en .
        _:artyom <age> "35" .
    
        _:sarah <name> "Sarah" .
        _:sarah <age> "55" .
    
        _:sang <name> "상현"@ko .
        _:sang <name> "Sang Hyun"@en .
        _:sang <age> "24" .
        _:sang <friend> _:amit .
        _:sang <friend> _:catalina .
        _:sang <friend> _:hyung .
        _:sang <owns_pet> _:goldie .
    
        _:hyung <name> "형신"@ko .
        _:hyung <name> "Hyung Sin"@en .
        _:hyung <friend> _:sang .
    
        _:catalina <name> "Catalina" .
        _:catalina <age> "19" .
        _:catalina <friend> _:sang .
        _:catalina <owns_pet> _:perro .
    
        _:rammy <name> "Rammy the sheep" .
    
        _:goldie <name> "Goldie" .
    
        _:perro <name> "Perro" .
      }
    }

### [Intro schema 1](https://tour.dgraph.io/schema/1/)

    industry: string @index(term) .
    boss_of: uid .

### [Intro schema 2](https://tour.dgraph.io/schema/2/)

    {
      set {
        _:company1 <name> "CompanyABC" .
        _:company2 <name> "The other company" .
    
        _:company1 <industry> "Manufacturing" .
        _:company1 <industry> "Fabricated Metal" .
        _:company1 <industry> "Machinery" .
    
        _:company2 <industry> "Manufacturing" .
        _:company2 <industry> "High Tech" .
    
        _:jack <works_for> _:company1 .
        _:ivy <works_for> _:company1 .
        _:zoe <works_for> _:company1 .
    
        _:jose <works_for> _:company2 .
        _:alexei <works_for> _:company2 .
    
        _:ivy <boss_of> _:jack .
    
        _:alexei <boss_of> _:jose .
      }
    }

### [Intro schema 5](https://tour.dgraph.io/schema/5/)

    boss_of: uid @reverse .

### [Intro more-data 5](https://tour.dgraph.io/moredata/1/)

    director.film: uid @reverse @count .
    genre: uid @reverse .
    initial_release_date: dateTime @index(year) .
    name: string @index(term) .
    starring: uid @count .

+ load the 1milMovies data

**Comment by mbn18** [comment]
@janardhan1993 

Will try again. It is strange that sending twice the same mutation create two seperate predicates with same name.
I would expect the second to alter the first (or rejected)

**Comment by mbn18** [comment]
@janardhan1993 ,

Tested again with latest `master`. Now it seems ok.

So, is it possible to create two predicate with the **same name**?

**Comment by pawanrawal** [comment]
You can't have two predicates with the same name in the schema. Usually, if you send two schema mutations for the same name, the second one would overwrite the first.

**Comment by pawanrawal** [comment]
Schema alter operation doesn't change the edges. It adds/removes indexes on the edges depending on the alter operation.
