### ISSUE TITLE
Best practice to load data exported by Neo4j

### ISSUE THREAD

**Issue by thetuxedo** [dgraph-io/dgraph#2034]
- What version of Dgraph are you using?
1.0

- Questions on data loading
I have some data which is exported from neo4j by my colleague and I want to load into Dgraph
Basically I have two csv files, one for node, one for relation.
Node File is like:
```
{"id":0,"properties":{"name":"Department-0"},"labels":"Department"}
{"id":1,"properties":{"name":"Department-1"},"labels":"Department"}
{"id":2,"properties":{"name":"Department-2"},"labels":"Department"}
{"id":3,"properties":{"name":"Department-3"},"labels":"Department"}
```

Relation File:
```
{"start":0,"end":316,"id":32370633,"type":"PAYMENT","properties":{"time":"2016-11-10 14:14:37","value":"2400.00","tips":""}}
{"start":0,"end":730,"id":32283270,"type":"PAYMENT","properties":{"time":"2016-05-04 11:23:17","value":"1000.00","tips":"32283270fd"}}
{"start":0,"end":1601,"id":32410514,"type":"PAYMENT","properties":{"time":"2016-03-02 11:45:47","value":"77370.73","tips":"32410514fd"}}
{"start":0,"end":1235,"id":32418774,"type":"PAYMENT","properties":{"time":"2016-12-23 16:55:26","value":"79991.00","tips":"32418774ss"}}

```

- Expected behaviour and actual result.
Questions:
1. What is the best way to load these files? The files are huge, and I am confused how to handle the unique id that will be assigned by dgprah to vertex.

2. What interface is recommended if not using go?
I am comfort with java and python, but newbie to go. Other than learning go, what's the recommendation for writing code to load data?

Thanks.

**Comment by pawanrawal** [comment]
There are many ways to load this data into Dgraph. 

1. If this is only for initial bulk load, you could you use [`dgraph bulk`](https://docs.dgraph.io/deploy/#bulk-loader) command. For that, you would have to convert the data into RDF format. This is the fastest way to perform bulk initial import into Dgraph. Your data in RDF format would look something like

```
<1> <name> "Department-0" .
<1> <labels> "Department" .

<1> <payment> <32370633> (time=2016-11-10 14:14:37, value=2400.00, tips=32283270fd) .
```
Note - The ids generated by Dgraph would be different from the ones allocated by Neo4j. If you want to preserve the Neo4j ids, you'd have to add another edge with the external id value. For example, 
`<1> <xid> "1" .`

2. The second approach is to use a client and build mutations. Mutations could take a JSON object or RDF's. We have some examples in the Java repo. You'd have to maintain the mapping between the external id and the uid allocated by Dgraph (store it in a map or something).

Right now we have a lease (which is the maximum uid allocated by Dgraph). If you send a mutation which has a uid > lease, we throw an error. We could allow the option to update the lease by the user. Then you could set the lease to be the maximum id you expect to insert. Then you could get the same ids as given by Neo4j and you won't have to maintain the mapping when using the second approach.

**Comment by thetuxedo** [comment]
thanks for the prompt reply. I will try.
