### ISSUE TITLE
ratel can't connect w/ trailing slash on URL

### ISSUE THREAD

**Issue by alexmilowski** [dgraph-io/dgraph#2039]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

1.0.2

- Have you tried reproducing the issue with latest release?

Yes

- What is the hardware spec (RAM, OS)?

N/A

- Steps to reproduce the issue (command/config used to run Dgraph).

1. Change the database URL and use a trailing slash (e.g., http://localhost:8080/)
2. Check the console and you'll see requests to ...//health?debug=true (e.g., http://localhost:8080//health?debug=true) that fail due to CORS; the result is the UI says it can't connect.
3. Change the database URL w/o the trailing slash  (e.g., http://localhost:8080)
4. Everything should work fine.

- Expected behaviour and actual result.

The UI should handle the URL with or without the trailing slash.

**Comment by gpahal** [comment]
Fixed the issue. It should be reflected on your ratel dashboard now. If it doesn't work try purging your browser's cache.
