### ISSUE TITLE
Can not run dgraph after install

### ISSUE THREAD

**Issue by Pixdigit** [dgraph-io/dgraph#2040]
I installed dgraph via `curl https://get.dgraph.io -sSf | bash` on my bananapi (Based on Debian 8 jessie). But when I run `dgraph` it returns the following error message:
`exec format error: dgraph` when using zsh and 
`/usr/local/bin/dgraph: 1: /usr/local/bin/dgraph: Syntax error: "(" unexpected` when using sh.

**Comment by pawanrawal** [comment]
I tried running Dgraph on a `debian:jessie` Docker image and it worked without any problems. I don't have access to a native installation to a debian, so I am afraid I won't be able to help with that. This is what I did.

1. Get the latest debian image and run bash in a container
```
docker pull debian:jessie
docker run -it debian:jessie bash
```

2. Download and run Dgraph within the container

```
apt-get update
apt-get install curl
curl https://get.dgraph.io -sSf | bash
dgraph
```

**Comment by pawanrawal** [comment]
I checked and yes ARM is not supported for now because of some assembly code that we use within Dgraph. Unfortunately, getting Dgraph to work on ARM is not out the priority for now. Feel free to try out Dgraph on amd64 architectures.
