### ISSUE TITLE
Document isolation level of ACID property

### ISSUE THREAD

**Issue by alvarolm** [dgraph-io/dgraph#2049]
I haven't read a lot, but it seems that dgraph provides "serializable" level of isolation, according to the bank transfer example in https://discuss.dgraph.io/t/releasing-distributed-transactions-in-v0-9-dgraph-blog/1962, https://github.com/dgraph-io/dgraph/blob/99cac529e608efc1c879e2195a64b567c1b6d145/contrib/scripts/transactions.sh#L27, https://github.com/dgraph-io/dgraph/blob/master/contrib/integration/bank/main.go

It would be great to expose or at least _briefly document_ the guarantees of the isolation level in order to communicate and explain this property, which is major feature of dgraph.

I really appreciate all the work you guys have been doing, thanks!

**Comment by janardhan1993** [comment]
Dgraph implements snapshot isolation(https://en.wikipedia.org/wiki/Snapshot_isolation), it's a bit weaker guarantee than "serializable" level of isolation.
But for most of the cases you can avoid the write skew issue present in snapshot isolation by writing to a common key(like index) to trigger write-write conflict. Please have a look at the Wikipedia article to get more details about the isolation guarantee.
