### ISSUE TITLE
Add notice about snapshot isolation weaknesses 

### ISSUE THREAD

**Issue by alvarolm** [dgraph-io/dgraph#2051]
I believe that having "bank" like testing and indirectly promoting distributed transactions as safe with out mentioning edge cases its very misleading (https://github.com/dgraph-io/dgraph/issues/2049).

It should be noted in a non discrete manner, explicitly, before mention the benefits of the current snapshot isolation implementation the weaknesses or edge cases that lead to inconsistencies and other major issues.

As a bonus point it would be nice to understand if the "Blitzkrieg approach" described in one of the blog posts could be the culprit of such lack of documentation.

Despite all the above I must tell you guys how greatly grateful I am for the project itself and all the contrinutions to the open source community.

(very good read in case someone its interested: https://wiki.postgresql.org/wiki/SSI)

**Comment by manishrjain** [comment]
We already have the Jepsen report, which details Dgraph's support for transactions.

http://jepsen.io/analyses/dgraph-1-0-2
