### ISSUE TITLE
Dgraph live loader reports unexpected results

### ISSUE THREAD

**Issue by unknown321** [dgraph-io/dgraph#2052]
According to the tour (https://tour.dgraph.io/moredata/1/), `dgraph live` reports back exactly how many triples were loaded. However, it reports the number of rdf lines processed, not the amount of triples. I might be wrong, but according to the standard (https://www.w3.org/TR/rdf-plain-literal/), empty strings can be considered literals and are probably counted by `live` (but not recorded in database).

- What version of Dgraph are you using?
v1.0.2

- Have you tried reproducing the issue with latest release?
yes, this is the latest stable release

- What is the hardware spec (RAM, OS)?
three kvm virtual machines in docker swarm cluster, ~2gb ram each.

- Steps to reproduce the issue (command/config used to run Dgraph).

```
root@server-1:/dgraph# wget "https://github.com/dgraph-io/tutorial/blob/master/resources/1million.rdf.gz?raw=true" -O 1million.rdf.gz -q
root@server-1:/dgraph# gunzip 1million.rdf.gz
root@server-1:/dgraph# head -n 100000 1million.rdf > 100k_all.rdf
root@server-1:/dgraph# grep -P "\t\t<" 100k_all.rdf | wc -l  # the amount of strings with actual triplets, no comments or empty strings
99742
root@server-1:/dgraph# grep -P "\t\t<" 1million.rdf | head -n 100000 > 100k.rdf 
root@server-1:/dgraph# grep -P "\t\t<" 100k.rdf | wc -l 
100000
root@server-1:/dgraph# gzip 100k.rdf 100k_all.rdf 
root@server-1:/dgraph# dgraph live -r 100k.rdf.gz --zero=zero-1:5080

Processing 100k.rdf.gz
Total Txns done:        1 RDFs per second:    4975 Time Elapsed: 2s, Aborts: 0
Total Txns done:        3 RDFs per second:    7488 Time Elapsed: 4s, Aborts: 0
Total Txns done:        5 RDFs per second:    8327 Time Elapsed: 6s, Aborts: 0
Total Txns done:        7 RDFs per second:    8745 Time Elapsed: 8s, Aborts: 0
Total Txns done:        9 RDFs per second:    8997 Time Elapsed: 10s, Aborts: 0
Number of mutations run   : 10                                                                      
Number of RDFs processed  : 100000
Time spent                : 10.76087764s
RDFs processed per second : 10000
root@server-1:/dgraph# dgraph live -r 100k_all.rdf.gz --zero=zero-1:5080

Processing 100k_all.rdf.gz
Total Txns done:        2 RDFs per second:    9983 Time Elapsed: 2s, Aborts: 0
Total Txns done:        3 RDFs per second:    7493 Time Elapsed: 4s, Aborts: 0
Total Txns done:        5 RDFs per second:    8331 Time Elapsed: 6s, Aborts: 0
Total Txns done:        7 RDFs per second:    8748 Time Elapsed: 8s, Aborts: 0
Total Txns done:        9 RDFs per second:    8994 Time Elapsed: 10s, Aborts: 0
Number of mutations run   : 10                                                                      
Number of RDFs processed  : 100000
Time spent                : 10.502147864s
RDFs processed per second : 10000
```

- Expected behaviour and actual result.

As you can see, after importing both files with different amount of triplets (with and without empty lines) live loader reports: `Number of RDFs processed  : 100000`. This is a correct statement if empty strings and comments are counted as RDFs. However, I expect to see the _actual_ amount of triplets that were recorded, not just the amount of processed lines.

Possible solutions:

  - Add another line in `live` output with amount of recorded triplets
  - Fix the documentation so it would state what does the output mean

**Comment by pawanrawal** [comment]
Hey @unknown321 

Thanks for the issue. Dgraph live is supposed to print the total number of RDF's processed but it was instead printing `num(transactions_done) * batch_size`. I have submitted a fix in d972318a12ad7a4a09091ccbcc0abea73c3bc05d and it would be part of the next release.
