### ISSUE TITLE
Update homepage (1.0)

### ISSUE THREAD

**Issue by ShalokShalom** [dgraph-io/dgraph#2053]
https://blog.dgraph.io/post/benchmark-neo4j/

**Comment by sboorlagadda** [comment]
@ShalokShalom Could you describe your ask?

**Comment by ShalokShalom** [comment]
Sorry, it seems like I forgot to add the screenshot: 

![screenshot_20180210_190254](https://user-images.githubusercontent.com/6344099/36065027-0e1ee8a8-0e95-11e8-8fb8-b21d4ffd58c7.png)

1.0 is out

**Comment by ShalokShalom** [comment]
This is still outdated. It makes less sense to add features, if your documentation lies about

**Comment by pawanrawal** [comment]
Updated the table for you. There might be other aspects of the blog post that may still be outdated as the API has changed since `v0.8`.

**Comment by ShalokShalom** [comment]
I see. I guess the comparison to the leader in the field of graph based databases is important to you? :)

**Comment by pawanrawal** [comment]
Its important to users apparently and users being happy with Dgraph is important for us.

**Comment by ShalokShalom** [comment]
Thanks, I appreciate that

As other tests show, is neo4j now faster, while it consumes much more RAM.

I think the info note about the changed API makes this blog post now solid, thanks a lot. 

:D
