### ISSUE TITLE
Wiki content on recurse query is missing text

### ISSUE THREAD

**Issue by volinthius** [dgraph-io/dgraph#2055]
The section on recurse query is missing text after:

> Be careful as the result size could explode quickly and an error would be returned if the result set gets too large. In such cases use more filter, limit resutls using pagination, or provide a depth parameter at root as follows:

See [https://github.com/dgraph-io/dgraph/blob/master/wiki/content/query-language/index.md](url).

**Comment by janardhan1993** [comment]
Thanks for reporting the typo, the example was present above. I have fixed the docs to reflect the same.
