### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by tigp** [dgraph-io/dgraph#2057]
Hi guys, first of all would like to say that the projects is outstanding.

One thing though, the mktemp template is missing in the installation script https://get.dgraph.io/, and installation stops on that line.

**Comment by janardhan1993** [comment]
@tigp Which platform/OS are you using ? It seems like that mktemp command is not present on your OS.

**Comment by tigp** [comment]
@janardhan1993, I'm using OSX Mavericks. I had an error ``usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix``` and I changed the line from ```temp_dir=$(mktemp -d)``` to ```temp_dir=$(mktemp -d /tmp/temp.XXXX)```

**Comment by janardhan1993** [comment]
Apparently mktemp doesn't work on osx without specifying the template. (https://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x)
Thanks for reporting this, we will fix our script.

**Comment by tigp** [comment]
@janardhan1993 happy to help!

**Comment by janardhan1993** [comment]
Fixed the script.
