### ISSUE TITLE
Team City build fails in TestClusterSnapshot

### ISSUE THREAD

**Issue by janardhan1993** [dgraph-io/dgraph#2063]
https://teamcity.dgraph.io/viewLog.html?buildId=305&buildTypeId=Dgraph_Ci&tab=buildLog&_focus=2915

**Comment by sboorlagadda** [comment]
From the stacktrace:
```github.com/dgraph-io/dgraph/x.Fatalf
    /Users/sboorlagadda/go/src/github.com/dgraph-io/dgraph/x/error.go:103
github.com/dgraph-io/dgraph/worker.(*node).retrieveSnapshot
    /Users/sboorlagadda/go/src/github.com/dgraph-io/dgraph/worker/draft.go:419
github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode
    /Users/sboorlagadda/go/src/github.com/dgraph-io/dgraph/worker/draft.go:672
github.com/dgraph-io/dgraph/worker.StartRaftNodes
    /Users/sboorlagadda/go/src/github.com/dgraph-io/dgraph/worker/groups.go:120
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:2337
```
I see that retrieveSnapshot (from draft.go) is looking for a connection pool to the group leader
```func (n *node) retrieveSnapshot() {
    pool := groups().Leader(groups().groupId())
```
But then `groups().Leader()` blew with "No connection exists", so I looked into when a connection is made to other members.

From groups.go `func StartRaftNodes(walStore *badger.ManagedDB, bindall bool) {` we do three things....
1) Retrieve state from zero
2) Connect to other group members `applyState` (https://github.com/sboorlagadda/dgraph/blob/master/worker/groups.go#L111)
3) Retrieve snapshot (https://github.com/sboorlagadda/dgraph/blob/master/worker/groups.go#L120)

Here I see that connection to other members happens in a go routine which may not be established before retrieving the snapshot. Why are the connections made in a go routine?

**Comment by janardhan1993** [comment]
@sboorlagadda I think it's safe to do them outside go routine. I am not sure why there were done in goroutine.

**Comment by janardhan1993** [comment]
Fixed in master.
