### ISSUE TITLE
IRC Gateway for Slack

### ISSUE THREAD

**Issue by robertmeta** [dgraph-io/dgraph#2066]
This is a request for turning on the IRC gateway for Slack so people who prefer IRC clients can use them over using slack directly.  The setup is simple: https://get.slack.help/hc/en-us/articles/201727913-Connect-to-Slack-over-IRC-and-XMPP

**Comment by pawanrawal** [comment]
I have enabled IRC. @robertmeta please give it a try now.

**Comment by robertmeta** [comment]
Works like a charm @pawanrawal thanks!

**Comment by Swoorup** [comment]
what is the IRC network and channel?
