### ISSUE TITLE
One of count example is not working

### ISSUE THREAD

**Issue by farscape2012** [dgraph-io/dgraph#2084]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.2 (latest)

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?
Mac OS

- Expected behaviour and actual result.
Look at this figure. The request is not correct. This is from online tutorial (Query Language section.)
![image](https://user-images.githubusercontent.com/20615375/35767607-3fc70ee6-08f8-11e8-8e13-af20d41ed407.png)

**Comment by pawanrawal** [comment]
Thanks for the report @farscape2012. I have updated the schema and the query should work now.
