### ISSUE TITLE
Reverse edges not being added despite @reverse keyword in schema

### ISSUE THREAD

**Issue by aryzing** [dgraph-io/dgraph#2087]
### What version of Dgraph are you using?
1.0.2

### Have you tried reproducing the issue with latest release?
yes

### What is the hardware spec (RAM, OS)?
16GB, Ubuntu LTS 16.04

### Steps to reproduce the issue (command/config used to run Dgraph).

1. Create a blank instance with the following schema:

```
name: string @index(term) .
works_with: uid @reverse .
```

2. Add the following nodes

```
{
  set {
    _:alice <name> "Alice" .
    _:alice <works_with> _:bob .
    _:bob <name> "Bob" .
  }
}
```

3. Issue a query that, starting from Bob, gets all the people he works with

```
{
  bob_coworkers(func: eq(name, "Bob")) {
    name@.
    works_with {
      name@.
    }
  }
}
```

### Expected behaviour and actual result.

**Expected**: I would have expected that the reverse edge be added allowing me to get from Bob to Alice via the `works_with` edge.

**Actual**: The query returns and empty set

**Comment by pawanrawal** [comment]
The way you access a reverse edge is using `~predicate`. https://docs.dgraph.io/query-language/#reverse-edges

```
{
  bob_coworkers(func: eq(name, "Bob")) {
    name@.
    ~works_with {
      name@.
    }
  }
}
```

**Comment by aryzing** [comment]
Perhaps I did not explain myself sufficiently. To avoid turning this issue into a question, I've followed up with a more comprehensive version of this question in the [dgraph forum](https://discuss.dgraph.io/t/what-does-adding-reverse-edges-really-mean-reverse/2205). Thanks!
