### ISSUE TITLE
Cannot use same transaction for delete and set mutations

### ISSUE THREAD

**Issue by tamethecomplex** [dgraph-io/dgraph#2090]
This is an issue to track https://github.com/dgraph-io/dgraph-js/issues/21, originally submitted for the js client, but which belongs to dgraph server per @pawanrawal .

@pawanrawal , this issue happens 100% of the time on my setup.  One possible difference between your and my setups is that my dgraph server is actually hosted remotely, and network latency is pretty high (50-100ms).  I'm not sure whether there's any link between my high latency and consistent reproduction of the issue, but FYI just in case it's significant.

**Comment by pawanrawal** [comment]
The issue is reproducible when running Dgraph in a VM. I am investigating this and will update the cause here soon.

**Comment by pawanrawal** [comment]
I have a fix for this in #2105 which will be merged soon.

**Comment by pawanrawal** [comment]
A fix has been pushed to master in 42b01677b29ae7a99acf629d2e086a993325f912 and would be part of the nightly/next release.

**Comment by tamethecomplex** [comment]
Looks good!  Confirmed fix on docker hub tag 'master'.
