### ISSUE TITLE
Relative performance measure

### ISSUE THREAD

**Issue by hackintoshrao** [dgraph-io/dgraph#21]
Need relative performance measure  for Heap and Query method for Rock's DB merge by @ashwin95r . I'm on it tonight. As @manishrjain  had suggested in gitter I'll start with a very simple test and stop there if performance difference is evident. Since its the battle of time complexities and run time measurements sometimes the difference would be evident only on working with large datasets/nodes so that the other factors get abstracted and the run time can be truly judged to be dependent on the core operation under scrutiny.  Mark assignment/label

**Comment by manishrjain** [comment]
Let me know if you need anything from my side -- GCE instance etc.

**Comment by hackintoshrao** [comment]
Sure...

**Comment by hackintoshrao** [comment]
As discussed in Gitter, Waiting for @ashwin95r  and @manishrjain decision on rewriting the merger in Golang using the RocksDb CGO wrapper. Meanwhile I would want to pick up a new ask, May be writing the Golang Driver or whatever that is of priority - @manishrjain

**Comment by manishrjain** [comment]
Let me get back to you on that.

**Comment by manishrjain** [comment]
Think we all agree that doing the heap based approach is faster. And we're going to rewrite the code in Go. So, I doubt we need to do this benchmark -- clearly doing disk lookups isn't going to be as fast as O(log k) provided by an in-memory heap. So, let's punt on this.

@hackintoshrao -- If you agree with the above, please close this issue. Think we should have another issue to track the rewrite in Go, if not, feel feel to create one.

**Comment by manishrjain** [comment]
Ah.. sorry, didn't mean to close this, until you confirmed @hackintoshrao

**Comment by hackintoshrao** [comment]
Sure, I agree..Will create a new issue for this.
