### ISSUE TITLE
Out of date documentation on transactions

### ISSUE THREAD

**Issue by Venryx** [dgraph-io/dgraph#2103]
On the page here: https://docs.dgraph.io/design-concepts/#note-on-transactions

It states:
> Dgraph does not support transactions at this point. A mutation can be composed of multiple Edges, each edge might belong to a different Posting List. Dgraph acquires RWMutex locks at a posting list level. It DOES NOT acquire locks across multiple posting lists.
> 
> What this means for writes is that some edges would get written before others, and so any reads which happen while a mutation is going on would read partially committed data. However, there’s a guarantee of durability. When a mutation succeeds, any successive reads will read the updated data in its entirety.
> 
> On the other hand, if a mutation fails, it’s up to the application author to clean the partially written data or retry with the right logic. The response from Dgraph would make it clear which edges weren’t written so that the application author can set the right edges for retry.

However, just scroll up to the top of that page, and it says:
> Dgraph supports distributed ACID transactions through snapshot isolation.

It also says Dgraph supports transactions on the home page and elsewhere. Thus, I'm assuming the section above is just leftover content that was forgotten to be removed.

If so, can it please be removed from the docs page? It was pretty confusing for me when I first read it.

**Comment by sboorlagadda** [comment]
Thanks! some of these concepts are outdated. I will get this removed.
