### ISSUE TITLE
High CPU Load and Slow Query When Do Filtering

### ISSUE THREAD

**Issue by essapermana** [dgraph-io/dgraph#2111]
- What version of Dgraph are you using?
`1.0.3`

- Have you tried reproducing the issue with latest release?
`Yes`

- What is the hardware spec (RAM, OS)?
`Ubuntu 16.04 with 8 Core CPU and 16 GB RAM`

- Steps to reproduce the issue (command/config used to run Dgraph).
`Dgraph running on single node (zero and server on same machine), with data for about 66 million and then running the following query`

```
{
    var(func:eq(iduser,%d)) {
        favorite @filter(NOT eq(deleted,true)){
            A AS doing
        }
    }
    result(func:uid(A), orderdesc:create_time, first:%d) @filter(lt(create_time, %s)) {
        idactivity
        create_time
    }
}
```
`iduser` and `create_time` is integer and indexed using `hash`

- The result.
`CPU went high and then the result shown after for about 8s, the behaviour occurred every we do the query, even with the same one. But if we remove this filter : @filter(lt(create_time, %s)) , this issue not happened`

Attached is CPU profile when the query is running

[pprof.dgraph.samples.cpu.001.pb.gz](https://github.com/dgraph-io/dgraph/files/1714667/pprof.dgraph.samples.cpu.001.pb.gz)

**Comment by pawanrawal** [comment]
From the profile, I can see that most of the time is spent in finding inequalityTokens

```
ROUTINE ======================== github.com/dgraph-io/dgraph/worker.getInequalityTokens in /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/tokens.go
     140ms      7.20s (flat, cum) 68.77% of Total
         .          .    161:	indexPrefix := x.IndexKey(attr, string(tokenizer.Identifier()))
         .          .    162:	seekKey := x.IndexKey(attr, ineqToken)
         .          .    163:	it := posting.NewTxnPrefixIterator(txn, itOpt, indexPrefix, seekKey)
         .          .    164:	ineqTokenInBytes := []byte(ineqToken) //used for inequality comparison below
         .          .    165:	defer it.Close()
      40ms      5.53s    166:	for ; it.Valid(); it.Next() {
         .          .    167:		key := it.Key()
      10ms      1.22s    168:		k := x.Parse(key)
         .          .    169:		if k == nil {
         .          .    170:			continue
         .          .    171:		}
         .          .    172:		// if its lossy then we handle inequality comparison later
         .          .    173:		// on in handleCompareAttr
         .       20ms    174:		if tokenizer.IsLossy() {
         .          .    175:			out = append(out, k.Term)
         .          .    176:		} else {
         .          .    177:			// for non Lossy lets compare for inequality (gt & lt)
         .          .    178:			// to see if key needs to be included
         .          .    179:			if f == "gt" {
         .          .    180:				if bytes.Compare([]byte(k.Term), ineqTokenInBytes) > 0 {
         .          .    181:					out = append(out, k.Term)
         .          .    182:				}
         .          .    183:			} else if f == "lt" {
      50ms      140ms    184:				if bytes.Compare([]byte(k.Term), ineqTokenInBytes) < 0 {
      40ms      290ms    185:					out = append(out, k.Term)
         .          .    186:				}
         .          .    187:			} else { //for le or ge or any other fn consider the key
         .          .    188:				out = append(out, k.Term)
         .          .    189:			}
         .          .    190:		}
```

What is the schema that you have on `create_time`? Is `create_time` stored as a Unix timestamp? Do you have 66 million nodes, each having a value for `create_time`? Does the machine have SSD/HDD? Is it possible to share your dataset so that we can reproduce the slowness?

**Comment by essapermana** [comment]
Yes @pawanrawal create_time is stored as UNIX timestamp, and it's only arround 8 million nodes  who have the create_time predicate, the machine is SSD and unfortunately we can't share the dataset.

**Comment by pawanrawal** [comment]
And what about the schema, what tokenizer do you have?

**Comment by essapermana** [comment]
Here is our schema
```
doing: uid @reverse @count .
favorite: uid @reverse @count .
idshop : int @index(int) .
iduser : int @index(int) .
idactivity : int @index(int) .
create_time:int @index(int) .
```

**Comment by pawanrawal** [comment]
Storing it as an int UNIX timestamp is not a great idea as the indexes won't help much and there would be too many index buckets. Store the data as [datetime](https://docs.dgraph.io/query-language/#schema-types) and have a `year` tokenizer. 

```
create_time: datetime @index(year)
```

**Comment by essapermana** [comment]
Ok pawan, we'll try to change the data type, and will do the experiment again. Thank you.

**Comment by pawanrawal** [comment]
@essapermana Did you try the experiment and did it help? If so, can we close this issue?

**Comment by pawanrawal** [comment]
Feel free to reopen if changing schema didn't help.
