### ISSUE TITLE
Leader is SPOF while snapshot retrieval when initialize huge data using bulk loader

### ISSUE THREAD

**Issue by munisystem** [dgraph-io/dgraph#2120]
I try to import huge data using bulk loader for purpose of transition from RDB. But replication of huge data takes time, and leader node is SPOF while snapshot retrieval.

I want to be skipped snapshot retrieval in the case of copying `out/0/p` generated from bulk loader in same group instances.

**Comment by sboorlagadda** [comment]
Are you suggesting a command line option to facilitate skipping? I would rather suggest (if its not already the case) consider recovering first from disk before initiating a snapshot from peers.

So in this particular case when `out/0/p` is copied to each group instance, then every instance first recovers from the provided data directory and initiate retrieving  only a `delta` snapshot.

**Comment by munisystem** [comment]
> I would rather suggest (if its not already the case) consider recovering first from disk before initiating a snapshot from peers.

Sounds good to me!

**Comment by danielmai** [comment]
Like @sboorlagadda said, after a bulk load, copy the bulk load output p directories (e.g., `out/0/p`) to each of the replicas within a group before starting `dgraph server` on each.

Closing this issue.
