### ISSUE TITLE
Node crashed due to badger error

### ISSUE THREAD

**Issue by mpires** [dgraph-io/dgraph#2121]
- What version of Dgraph are you using?
1.0.2

- Have you tried reproducing the issue with latest release?
No

- What is the hardware spec (RAM, OS)?
16GB, Debian 9

- Steps to reproduce the issue (command/config used to run Dgraph).
Can't understand the root cause and am unable to find the query - if any - that triggered this.

- Expected behaviour and actual result.
After this crash, this particular node was unable to receive mutations and data updates in the cluster were not replicated to it.

[issue.log](https://github.com/dgraph-io/dgraph/files/1720121/issue.log)

**Comment by pawanrawal** [comment]
I see that these are not the full logs for the crash. Do you have logs from a bit before, like the transition from healthy to crash?

**Comment by mpires** [comment]
Right, that's the first time I've seen unhealthy logs.
I've attached a logfile, this time with logs with many hours before the error mark (around Feb 11 22:38)
[issue2.log.zip](https://github.com/dgraph-io/dgraph/files/1722142/issue2.log.zip)

**Comment by pawanrawal** [comment]
I can't see much about what caused this in the logs. Could you check if Dgraph was killed by Linux OOM killer? Here is how you can check it.
https://stackoverflow.com/questions/624857/finding-which-process-was-killed-by-linux-oom-killer

**Comment by pawanrawal** [comment]
Closing the issue because of lack of activity. Seems like this was caused by OOM. If memory is a constraint you could start dgraph with the following option.

```
--posting_tables memorymap
```
