### ISSUE TITLE
Support logical replication / change data capture (CDC) with Kafka

### ISSUE THREAD

**Issue by fritzblue** [dgraph-io/dgraph#2122]
The following workflow is becoming more and more common in streaming architectures:

![image](https://user-images.githubusercontent.com/6473463/36156774-5033a9fc-1095-11e8-8d7c-56b308f3e925.png)

If Dgraph is to be used as a primary data store in a production system, it must support logical replication / change data capture.

Is this currently possible? If not, is it planned for the future?

**Comment by pawanrawal** [comment]
It's not possible right now but we can do something like this in the future. Some users have asked for [subscriptions](https://github.com/dgraph-io/dgraph/issues/824).  This would be a similar feature I suppose.

**Comment by manishrjain** [comment]
We could potentially support this at Badger level first, and then expose it via Dgraph.

**Comment by campoy** [comment]
After chatting with @gitlw, it seems like this could be implemented relatively easily on top on our current plans for datacenter to datacenter replication, which already uses Kafka.

Adding it to our 1.X plans!

**Comment by user453584** [comment]
For an example of a distributed DB that's doing this in what I would argue is the Right Way™, see CockroachDB https://www.cockroachlabs.com/docs/stable/change-data-capture.html

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8747). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
