### ISSUE TITLE
Node crash while doing Live Data Load

### ISSUE THREAD

**Issue by veludurai106** [dgraph-io/dgraph#2126]
**DGraph Version - 1.0.3**

**OS - Centos 7**

**Steps to reproduce the issue**
 - Started zero in 3 nodes 
     _nohup dgraph zero --my=10.111.111.101:5080 --replicas=3  --idx=01 & 
     nohup dgraph zero --my=10.111.111.104:5080 --peer=10.111.111.101:5080 --replicas=3 --idx=02  & 
     nohup dgraph zero --my=10.111.111.103:5080 --peer=10.111.111.101:5080 --replicas=3 --idx=03  &_ 
   
  - Started dgraph server in 3 nodes 
      _nohup dgraph server --memory_mb=16000 --my=10.111.111.101:7080 --zero=10.111.111.101:5080 &
      nohup dgraph server --memory_mb=16000 --my=10.111.111.104:7080 --zero=10.111.111.101:5080 &
      nohup dgraph server --memory_mb=16000 --my=10.111.111.103:7080 --zero=10.111.111.101:5080 &_ 
 - Started Live Loader
    _dgraph live -r /home/mapr/DgraphResources/merchantIrvine50000_1.rdf -s /home/mapr/DgraphResources/merchantIrvine50000.schema -z 10.111.111.101:5080 -d 10.111.111.101:9080_

**Issue Facing**
    Out of 3 nodes, one node crashing, whereas other  2 nodes are fine. 

**Error Trace**
	

> 2018/02/14 20:18:34 ERROR in Badger::writeRequests: Unable to write to value log file: "p/000000.vlog": write p/000000.vlog: input/output error
> 	2018/02/14 20:18:34 ERROR in Badger::writeRequests: Unable to write to value log file: "p/000000.vlog": write p/000000.vlog: input/output error
> 	2018/02/14 20:18:35 ERROR in Badger::writeRequests: Unable to write to value log file: "p/000000.vlog": write p/000000.vlog: input/output error
> 	2018/02/14 20:18:35 ERROR in Badger::writeRequests: Unable to write to value log file: "p/000000.vlog": write p/000000.vlog: input/output error
> 	2018/02/14 20:18:36 ERROR in Badger::writeRequests: Unable to write to value log file: "p/000000.vlog": write p/000000.vlog: input/output error
> 	2018/02/14 20:18:36 ERROR in Badger::writeRequests: Unable to write to value log file: "p/000000.vlog": write p/000000.vlog: input/output error
> 	2018/02/14 20:18:37 ERROR in Badger::writeRequests: Unable to write to value log file: "p/000000.vlog": write p/000000.vlog: input/output error
> 	2018/02/14 20:18:37 ERROR in Badger::writeRequests: Unable to write to value log file: "p/000000.vlog": write p/000000.vlog: input/output error

**Comment by veludurai106** [comment]
I am  facing one more issue on that node. When I restart node, its failing to join back to cluster. 
   
I did restart without giving -p and -w and got **Invalid Address** error. 
After that tried those options but same error. 
   
This is the command I used 
      _dgraph server --memory_mb=16000 --my=10.111.111.103:7080 --zero=10.111.111.101:5080 -p /tmp/data/p -w /tmp/data/w_

Output of http://10.111.111.101:6080/state

```
{ "counter": "182638",
 "groups": {
   "1": {
     "members": {
       "1": {
         "id": "1",
         "groupId": 1,
         "addr": "10.111.111.101:7080",
         "lastUpdate": "1518625532"
       },
       "2": {
         "id": "2",
         "groupId": 1,
         "addr": "10.111.111.104:7080"
       },
       "3": {
         "id": "3",
         "groupId": 1,
         "addr": "10.111.111.103:7080",
         "lastUpdate": "1518620017"
       }
     }
   }
 },
 "zeros": {
   "1": {
     "id": "1",
     "addr": "10.111.111.101:5080",
     "leader": true
   },
   "2": {
     "id": "2",
     "addr": "10.111.111.104:5080"
   },
   "3": {
     "id": "3",
     "addr": "10.111.111.103:5080"
   }
 },
 "maxLeaseId": "1010000",
 "maxTxnTs": "10000",
 "maxRaftId": "58"
}
```

**Error Trace**

      
> nown desc = Invalid address
> 	2018/02/14 22:43:21 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
> 	^C2018/02/14 22:43:22 run.go:341: Caught Ctrl-C. Terminating now (this may take a few seconds)...
> 	2018/02/14 22:43:22 admin.go:61: Got clean exit request
> 	2018/02/14 22:43:22 Stopped taking more http(s) requests. Err: accept tcp [::]:8080: use of closed network connection
> 	2018/02/14 22:43:22 All http(s) requests finished.
> 	2018/02/14 22:43:22 gRpc server stopped : accept tcp [::]:9080: use of closed network connection
> 	2018/02/14 22:43:23 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
> 	2018/02/14 22:43:26 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
> 	panic: runtime error: invalid memory address or nil pointer dereference
> 	[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1095e67]
> 	goroutine 1 [running]:
> 	github.com/dgraph-io/dgraph/worker.(*node).Stop(0x0)
> 			/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:577 +0x37
> 	github.com/dgraph-io/dgraph/worker.BlockingStop()
> 			/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/worker.go:117 +0xa5
> 	github.com/dgraph-io/dgraph/dgraph/cmd/server.run()
> 			/home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/server/run.go:356 +0x829
> 	github.com/dgraph-io/dgraph/dgraph/cmd/server.init.0.func1(0xc4203d4480, 0xc4203a69a0, 0x0, 0x7)
> 			/home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/server/run.go:63 +0x52
> 	github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203d4480, 0xc4203a6930, 0x7, 0x7, 0xc4203d4480, 0xc4203a6930)
> 			/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
> 	github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1a03c00, 0xc420159ee8, 0x8f1dc0, 0x1a0b2d0)
> 			/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783 +0x30e
> 	github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute(0x1a03c00, 0x1a0b2d0, 0x1513407bcebd1e11)
> 			/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736 +0x2b
> 	github.com/dgraph-io/dgraph/dgraph/cmd.Execute()
> 			/home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:52 +0x31
> 	main.main()
> 			/home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/main.go:34 +0xad
>

**Comment by pawanrawal** [comment]
> 2018/02/14 20:18:37 ERROR in Badger::writeRequests: Unable to write to value log file: "p/000000.vlog": write p/000000.vlog: input/output error

This seems to be a hardware issue. As the first answer [here](https://unix.stackexchange.com/questions/39905/input-output-error-when-accessing-a-directory) mentions, check `dmesg`.

> Type dmesg and check the last few lines of output. If the disc or the connection to it is failing, it'll be noted there.

Regarding the second issue, when you restart a dead node you have to do it with the same `p` and `w` directories (that you used initially) otherwise it is considered a new node. Are you starting with the same directories as those on the first start? What error do you get when you do that?

You should not try to replace a dead node without first removing it from the cluster otherwise you will get `Invalid address` error.

**Comment by veludurai106** [comment]
Hi @pawanrawal  When I type `dmesg` , I cloud see messages indicating some error.

> [2453421.087021] buffer_io_error: 246462 callbacks suppressed
[2453421.087026] Buffer I/O error on dev dm-5, logical block 30499216, lost async page write
[2453421.087300] Buffer I/O error on dev dm-5, logical block 30499217, lost async page write
[2453421.087447] Buffer I/O error on dev dm-5, logical block 30499218, lost async page write
[2453421.087600] Buffer I/O error on dev dm-5, logical block 30499219, lost async page write
[2453421.087749] Buffer I/O error on dev dm-5, logical block 30499220, lost async page write
[2453421.087919] Buffer I/O error on dev dm-5, logical block 30499221, lost async page write
[2453421.088072] Buffer I/O error on dev dm-5, logical block 30499222, lost async page write
[2453421.088217] Buffer I/O error on dev dm-5, logical block 30499223, lost async page write
[2453421.088354] Buffer I/O error on dev dm-5, logical block 30499224, lost async page write
[2453421.088496] Buffer I/O error on dev dm-5, logical block 30499225, lost async page write
[2453452.403756] buffer_io_error: 211845 callbacks suppressed
[2453452.403759] Buffer I/O error on dev dm-5, logical block 30711072, lost async page write
[2453452.404039] Buffer I/O error on dev dm-5, logical block 30711073, lost async page write
[2453452.404194] Buffer I/O error on dev dm-5, logical block 30711074, lost async page write
[2453452.404340] Buffer I/O error on dev dm-5, logical block 30711075, lost async page write
[2453452.404481] Buffer I/O error on dev dm-5, logical block 30711076, lost async page write
[2453452.404632] Buffer I/O error on dev dm-5, logical block 30711077, lost async page write
[2453452.404773] Buffer I/O error on dev dm-5, logical block 30711078, lost async page write
[2453452.404910] Buffer I/O error on dev dm-5, logical block 30711079, lost async page write
[2453452.405041] Buffer I/O error on dev dm-5, logical block 30711080, lost async page write
[2453452.405185] Buffer I/O error on dev dm-5, logical block 30711081, lost async page write

**Comment by veludurai106** [comment]
**Regarding second issue, below is the steps I did.** 

**Started dgraph server (no issue faced, started as expected )**    

       nohup dgraph server --memory_mb=16000 --my=10.111.111.103:7080 --zero=10.111.111.101:5080 &


**Started Live Loader in another node using below**

      dgraph live -r /home/mapr/DgraphResources/merchantIrvine50000_1.rdf -s /home/mapr/DgraphResources/merchantIrvine50000.schema -z 10.111.111.101:5080 -d 10.111.111.101:9080


**After that I started seeing Error (first issue) in 10.111.111.103 logs. So killed the process**


     kill -9 <pid>


**Started again using the same command and I got "Invalid address error" and failed to start**


      nohup dgraph server --memory_mb=16000 --my=10.111.111.103:7080 --zero=10.111.111.101:5080 &

**Again started with -p and -w options, but same error**

 
      dgraph server --memory_mb=16000 --my=10.111.111.103:7080 --zero=10.111.111.101:5080 -p /tmp/data/p -w /tmp/data/w

**Comment by veludurai106** [comment]
Facing the same issue when I restart other 2 nodes also

> 2018/02/15 14:16:16 draft.go:661: Restarting node for group: 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1096ff8]
goroutine 1171 [running]:
github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode(0xc4201a6e00, 0xc46851d450)
  /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:667 +0x668
github.com/dgraph-io/dgraph/worker.StartRaftNodes(0xc420194020, 0x1)
  /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/groups.go:120 +0x719
created by github.com/dgraph-io/dgraph/dgraph/cmd/server.run
  /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/server/run.go:354 +0x81f


Now entire cluster is down and couldn't start any server.

**Comment by pawanrawal** [comment]
This seems to be because of hardware failure, hence I am closing this issue.
