### ISSUE TITLE
Total weight calculation on k-shortest-path-query

### ISSUE THREAD

**Issue by swagluke** [dgraph-io/dgraph#2127]
Hey team, so I’m digging more into the K-Shortest-Path-Query and wondering if there is a way to find the facets weight on each path.
For example, DGraph has the set as

```
{
  set {
    _:a <friend> _:b (weight=0.1) .
    _:b <friend> _:c (weight=0.2) .
    _:c <friend> _:d (weight=0.3) .
    _:a <friend> _:d (weight=1) .
    _:a <name> "Alice" .
    _:b <name> "Bob" .
    _:c <name> "Tom" .
    _:d <name> "Mallory" .
  }
}
```

K-Shorest-Path query 
```
{
 path as shortest(from: 0x2, to: 0x5) {
  friend @facets(weight)
 }

 path(func: uid(path)) {
  name
 }
}
```

It would be nice to get a total weight on each path.

https://docs.dgraph.io/query-language/#k-shortest-path-queries

**Comment by martinmr** [comment]
This can be closed. I merged in the fix but I forgot to close the issue.
