### ISSUE TITLE
K-Shortest-Path between Group of Nodes.

### ISSUE THREAD

**Issue by swagluke** [dgraph-io/dgraph#2131]
It will be nice to run K-Shortest-Path between two group of nodes.
For example:  
      GroupA has node A,B,C,D
      GroupB has node 1,2,3,4

Running K-Shortest-Path between GroupA and GroupB will return 
k-shortest between node A - node 1, node A - node 2, node A- node3, etc.

K-Shortest-Path Go Code Link:
(https://github.com/dgraph-io/dgraph/blob/master/query/shortest.go)

**Comment by sboorlagadda** [comment]
@swagluke When K-Shortest path supports variables (#2130), then its easy for a client application to loop through a set of nodes. So I would think this is a lower priority for now.

**Comment by campoy** [comment]
Closing as duplicate of #1243
