### ISSUE TITLE
syntax highlight issue

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [dgraph-io/dgraph#2133]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
103

- Have you tried reproducing the issue with latest release?

- What is the hardware spec (RAM, OS)?

- Steps to reproduce the issue (command/config used to run Dgraph).
go to http://localhost:8000/ 
put alter
and try enter new schema without '{' braces

- Expected behaviour and actual result.
syntax highlight does not works

**Comment by MichelDiz** [comment]
Altering Schema via Alter is working normally in my last tests.

PS. without '{' braces it's working

Feel free to reopen if necessary.
