### ISSUE TITLE
Unable to sync memberships error

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#2139]
Dgraph server often logs the following error even when Zero is up and running.

```
server_1  | 2018/02/16 18:34:40 groups.go:474: Unable to sync memberships. Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

It's coming from https://github.com/dgraph-io/dgraph/blob/master/worker/groups.go#L474. We should investigate why this happens so often and if it needs to be logged every time.

**Comment by janardhan1993** [comment]
This was due to snapshot being in the run loop. Fixed in master

**Comment by BlakeMScurr** [comment]
Any insights on this one? I'm hitting is as part of my test suite - how did running snapshot in a loop cause this?

**Comment by manishrjain** [comment]
Can you create a new Github issue? And fill out the issue template?
