### ISSUE TITLE
Return all languages for a string

### ISSUE THREAD

**Issue by lazharichir** [dgraph-io/dgraph#2141]
I believe this is not yet supported - could you add a feature so that I could request a string predicate to return all the `@lang` it has.

So far, we can query for particular languages using the `@en:.` or `@.` or else. But the idea here is to return all existing languages for this predicate.

An example of query syntax could be:
```
{
    query(func: eq(topic.label@en, "Graph database")) {
        topic.label@_all_
    }
}
```

The returned data could either be flattened like it is now, or with an array of paired `"lang": "value"` :
```
{
    "query": {
        "topic.label@en": "Graph database",
        "topic.label@fr": "Base de donnee graphique",
        "topic.label@pl": "Blah blah blah"
    }
}

{
    "query": {
        "topic.label": [
            "en": "Graph database",
            "fr": "Base de donnee graphique",
            "pl": "Blah blah blah"
        ]
    }
}
```

**Comment by lazharichir** [comment]
Is this (still) considered for sometime this year 2018?

**Comment by manishrjain** [comment]
I don't see much demand for this. So, it's low on the priority list.
