### ISSUE TITLE
K-Nearest-Neighbors in DGraph

### ISSUE THREAD

**Issue by swagluke** [dgraph-io/dgraph#2142]
Neo4j has query that does K-Nearest-Neighbors
BlogPost link: 
https://neo4j.com/graphgist/movie-recommendations-with-k-nearest-neighbors-and-cosine-similarity#_view_your_nearest_neighbors

@pawanrawal has read the blogpost and figure the missing part from DGraph is the ability to do a cross product between two vectors. 

It would be nice to have documentations or blogpost after this new feature is developed.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8748). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
