### ISSUE TITLE
Return latency for mutations made via GRPC

### ISSUE THREAD

**Issue by tamethecomplex** [dgraph-io/dgraph#2146]
The latency stats returned for query operations over GRPC are very helpful.  It would be great to have those same metrics available for mutation operations.

**Comment by pawanrawal** [comment]
Support for this has been merged to master with 2485b652a9471be64a4b69fa8db6bfe7832801ed.

**Comment by tamethecomplex** [comment]
@pawanrawal, can I get this from dockerhub using the master tag?
