### ISSUE TITLE
Delete leaves dangling entities, allows double-upserts

### ISSUE THREAD

**Issue by aphyr** [dgraph-io/dgraph#2148]
On the current Dgraph nightly (2018/02/20), in a healthy five-node cluster, without any faults, concurrently upserting, deleting, and reading records by a single, indexed integer attribute `key` can result in queries for `key` returning long-lasting records with only a UID and no key attached; as if the UID were still present in that key's index, even though the triple has been deleted. Moreover, reads may actually see one of these dangling deleted records *concurrently* with a new record for that key. Moreover, reads may observe two *complete* records, even though one has been deleted.

This violates snapshot isolation, since reads are clearly not seeing a consistent point-in-time representation of state. It breaks internal consistency, since you can query for a record with `eq(key, 4)` and get back a record which doesn't have a `key` at all. Since a single process can actually see deleted data, it's definitely not sequential.

You can reproduce this on Jepsen 282623ca5b733097b9a524f70a451ca40151310e by running

```
lein run test -w delete -f --package-url https://github.com/dgraph-io/dgraph/releases/download/nightly/dgraph-linux-amd64.tar.gz --time-limit 120 --concurrency 100`.
```

For future users: you'll need 1.0.3 or 1.0.4, since this is on the nightlies and I don't think those have stable URLs. Test code is [here](https://github.com/jepsen-io/jepsen/blob/282623ca5b733097b9a524f70a451ca40151310e/dgraph/src/jepsen/dgraph/delete.clj#L35-L56).

The schema for this test is `key: int @index(int) .`. We read keys by querying

```
{ q(func: eq(key, $key)) {
  uid
  key
}}
```

... delete by querying for just the UID and issuing a delete for every attribute with `{uid: 0x123}`, and upsert by reading for an existing record with that key, and if none exists, inserting a new one. All operations occur within a transaction.

In [this run](https://github.com/dgraph-io/dgraph/files/1742617/20180220T182514.000-0600.zip), for key 0, an entity 0x298 already exists for the key, but is deleted by process 2. Processes 0, 1, 6, and 8 confirm the deletion of that entity: they find no matches for that query. Process 2 upserts a new record, which is visible on reads by process 5 and 6: `{:uid "0x2ab", :key 0}`. Concurrently with that upsert, process 4 deletes the key. Concurrent reads return dangling records: `{:uid "0x2ab"}` *with no key*. Other processes continue trying to delete key 0; their queries observe uid 0x2ab and issue a delete for it, but apparently with no effect. This dangling record, 0x2ab, persists for the remainder of the test--just over two minutes.

![screenshot from 2018-02-20 19-41-38](https://user-images.githubusercontent.com/3748/36459805-f54376ee-167a-11e8-90b7-3c1bf8a63e60.png)

In this diagram, time flows down, each process is a vertical track, operations are colored bars. Blue means success, pink is a known failed operation; e.g. it did not occur.

Moreover, queries may return multiple dangling records:

```clj
[{:uid "0xcf"} {:uid "0x110"}]
```

... a dangling record and a complete record:

```clj
[{:uid "0xcf"} {:uid "0x177", :key 1}]
```

... or multiple complete records for the same key:

```clj
[{:uid "0x148b"} {:uid "0x14f6", :key 13}]
[{:uid "0x148b"} {:uid "0x150c", :key 13}]
[{:uid "0x148b", :key 13} {:uid "0x150c", :key 13}]
```

For instance, in [this run](https://github.com/dgraph-io/dgraph/files/1742707/20180220T203635.000-0600.zip), shortly after an upsert, process 33 manages to observe two complete, coexisting records for the same key: 0x25fb, and 0x26e0. Note that 0x25fb was already deleted, which means it went from dangling to non-dangling. Note also that in order for the upsert to take place, it must have *failed* to observe 0x25fb, or it wouldn't have inserted anything. Something really odd is going on here.

![screenshot from 2018-02-20 20-49-11](https://user-images.githubusercontent.com/3748/36460769-95155af8-167f-11e8-8dfc-9a6b6c04c0d2.png)

Even weirder, in [20180220T205917.000-0600.zip](https://github.com/dgraph-io/dgraph/files/1742740/20180220T205917.000-0600.zip), 0x7e7 is a dangling record which process 36 can *see* and apparently successfully delete (although the deletion doesn't actually delete the dangling record). However, right after reading 0x7e7, process 36 attempts a delete and finds nothing to delete. Then 0x7e7 goes right back to being a dangling pointer and is visible to process 36 again--this time as a *full* record, in conjunction with the newly upserted 0x808. 0x808 turns out to be deletable. 0x707 goes back to being a full record, then a dangling record after that.

![screenshot from 2018-02-20 21-06-11](https://user-images.githubusercontent.com/3748/36461225-f6f55b7c-1681-11e8-8f0e-b451bd996674.png)

**Comment by janardhan1993** [comment]
#2220 Should fix some of the cases where this test was failing.

**Comment by janardhan1993** [comment]
We have only client level linerizability and if we do upserts with multiple clients, then read might not see the uid even if it's present if the follower is lagging. So we were seeing multiple records. I could reproduce this issue using multiple clients in our integration tests. 

I tweaked the `--replicas` flag to 1 in jepsen test and strangely i was still seeing the multiple records issue. I will confirm and update this tomorrow

**Comment by janardhan1993** [comment]
3. The invariant that all commits proposals should have been done before updating max pending fails with network partitions(most probably on leader change).

I can see some proposals with commitTs < maxPending being executed when network partitions are present

**Comment by janardhan1993** [comment]
The test is passing now with 'https://transfer.sh/13hS3v/dgraph-linux-amd64.tar.gz', Fixed by #2261

**Comment by janardhan1993** [comment]
This passes now with server_side_sequencing hardcoded in server.
@aphyr Need to add @upsert directive for this test as well.  
We also need to use latest client and set sequencing mode after this PR (https://github.com/dgraph-io/dgraph4j/pull/54/files) is merged.

**Comment by aphyr** [comment]
I'm going to build the new client and give that a shot. :)
