### ISSUE TITLE
expand(_all_) doesn't work in some dgraph servers in a cluster

### ISSUE THREAD

**Issue by jzhu077** [dgraph-io/dgraph#2155]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
dgraph/dgraph:master 

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?
480GB RAM and 128 cores

- Steps to reproduce the issue (command/config used to run Dgraph).
After setting up a dgraph cluster of 5 zeros and 30 servers divided into 10 groups, I ingest some data, and try to run a query:

{yield(func: eq(___kind,"foobar")) 
{

uid
  expand(_all_)
}
}
Some dgraph server are able to execute expand all but some only show the uid,
If I query a particular property all dgraph servers are working as expected. My guess is there is a bug in the expand all function.

{yield(func: eq(___kind,"foobar")) 
{

uid
name
}
}

- Expected behaviour and actual result.

expand(_all_) function works on all dgraph servers

Also a predicate (___kind) is corrupted, sometimes it will error with no predicate defined, other times it will not be returned on some results, other times it won’t be returned at all, other times it will be returned on all results.

**Comment by pawanrawal** [comment]
There was a bug in `expand(_all_)` which was related to deletions. Were you doing deletions when you observed this? If so, then shifting to master should help.
