### ISSUE TITLE
A bug related to Facets

### ISSUE THREAD

**Issue by farscape2012** [dgraph-io/dgraph#2158]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.03

- Have you tried reproducing the issue with latest release?

- What is the hardware spec (RAM, OS)?

- Steps to reproduce the issue (command/config used to run Dgraph).
As I have stated in stack, 

> I am following examples in official website. 
> Is this a bug?
> 
> It does not show first facet.
> If I remove (since, first), the shows all facets.
> pawan [11:53 PM]
> that does look like a bug. Can you file an issue and we can get it checked.

![image](https://user-images.githubusercontent.com/20615375/36541955-384a61dc-17e8-11e8-9f5e-84313451c069.png)

![image](https://user-images.githubusercontent.com/20615375/36541941-2fce6918-17e8-11e8-95e2-47ae298b25e7.png)

**Comment by pawanrawal** [comment]
This was happening because bulk loader was not sorting the facets before loading them into Dgraph, hence they couldn't be found while querying. I have pushed a fix with 3a576c187c2adf0b3b5384cd1c50c1dda99f3ea6.
