### ISSUE TITLE
Question: Go client?

### ISSUE THREAD

**Issue by cemremengu** [dgraph-io/dgraph#2164]
Is there an official/community go client for dgraph?

**Comment by 1l0** [comment]
https://github.com/dgraph-io/dgraph/tree/master/client

**Comment by pawanrawal** [comment]
We don't have a specific community for Go client but most of our users hang out on [Discourse](https://discuss.dgraph.io) or  [Slack](https://dgraph.slack.com/).

**Comment by pawanrawal** [comment]
You can also checkout the [GoDoc](https://godoc.org/github.com/dgraph-io/dgraph/client) and [documentation](https://docs.dgraph.io/clients/#go).

**Comment by cemremengu** [comment]
Thanks will do!

**Comment by cemremengu** [comment]
Just checked and looks great however it would be great (and maybe better?) to have a DSL style querying functionality
