### ISSUE TITLE
add numedges limit as a flag

### ISSUE THREAD

**Issue by jzhu077** [dgraph-io/dgraph#2174]
Feature request:
It would be nice if numEdges limit can be set as a flag because we have to set it to math.MaxUint64 to fit our use case.
https://github.com/dgraph-io/dgraph/blob/master/query/shortest.go#L214
https://github.com/dgraph-io/dgraph/blob/master/query/recurse.go#L167

**Comment by pawanrawal** [comment]
This was added to master.
