### ISSUE TITLE
add predicates rebalancing time as a flag

### ISSUE THREAD

**Issue by jzhu077** [dgraph-io/dgraph#2175]
Feature request:
Could you add a flag to configure the rebalancing time in https://github.com/dgraph-io/dgraph/blob/master/dgraph/cmd/zero/tablet.go#L55, please

**Comment by pawanrawal** [comment]
PR #2177

**Comment by pawanrawal** [comment]
Merged to master with de670f8ab36922a5ee66c3af75a7cbf54f6cb26a.
