### ISSUE TITLE
Properties cannot have the same name as edge labels

### ISSUE THREAD

**Issue by jereynolds** [dgraph-io/dgraph#2178]
- DGraph version v1.0.3 (via the docker latest tag)
- Amazon Linux AMI 2017.09.1.20180115 x86_64 HVM GP2
- AWS c5.large instance type

1. Insert vertices with some property predicate (eg named `group`)
2. Attempt to create edges whose label is the same predicate `group`

I receive the error `rpc error: code = Unknown desc = Input for predicate instance of type scalar is uid`

I expect to be able to create properties and vertices with the same name. Currently because of the treatment of properties as predicates there is a schema type mismatch which prevents this. This is fundamental to our use-case as we don't control the underlying data sources which feed our graph inputs.

**Comment by manishrjain** [comment]
Dgraph treats all vertex attributes as edges. This is built into the design. There's no such thing as creating a vertex in Dgraph. A vertex exists solely by its usage in an edge.

You can modify the predicates before storing them, by appending some prefix, so the predicate names don't collide. For e.g., `attribute.group`, and `edge.group`, or something on those lines.
