### ISSUE TITLE
Query returns empty result in a few dgraph servers of the cluster

### ISSUE THREAD

**Issue by jzhu077** [dgraph-io/dgraph#2179]
In my case, query func: eq(name,"foobar") returns empty result in dgraph server 2,5,and 10, when server-10’s group peers 9 and 11 are working correctly.

For more information:
https://discuss.dgraph.io/t/query-returns-empty-result-in-a-few-dgraph-servers-of-the-cluster/2271

**Comment by pawanrawal** [comment]
Is the query done by the same client that is also writing the data or are these different clients? This is possible if the writes and reads are done by different clients as Dgraph assures client level linearizability i.e. a client will see all the writes done by it.

**Comment by pawanrawal** [comment]
Not enough information, so closing this.
