### ISSUE TITLE
Dgraph recreated a deleted node after a schema alter

### ISSUE THREAD

**Issue by gpahal** [dgraph-io/dgraph#2182]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
Dgraph v1.0.3

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
RAM: 16GB
OS: Arch Linux (4.15.3-2-ARCH)

- Steps to reproduce the issue (command/config used to run Dgraph).
  - Steps used to run dgraph
  ```sh
  docker run -it -p 8080:8080 -p 9080:9080 -v ~/data/dgraph:/dgraph --name dgraph 
  dgraph/dgraph:v1.0.3 dgraph zero

  docker exec -it dgraph dgraph server --memory_mb 2048 --zero localhost:5080
  ```
  - Code to reproduce the issue: https://gist.github.com/gpahal/cc164707610bd12088ca02a0a8cba20f

- Expected behaviour and actual result.
After schema update, Alice should have no friends edges. But, somehow a node is created with no name and age.

Output:
```console
query: total friends of alice = 1 (after creation)
friend 0: uid = 0x2

query: total friends of alice = 1 (before deletion)
friend 0: uid = 0x2

query: total friends of alice = 0 (after deletion)

query: total friends of alice = 1 (after schema update)
friend 0: uid = 0x2
```

**Comment by pawanrawal** [comment]
This seems to be a bug with the rollup function. The schema update calls syncIfDirty. The immutable layer has the delete posting whereas the mutable layer still has the set posting. Now while doing rollup, we skip this delete posting as `mpost.CommitTs == l.CommitTs`. 

https://github.com/dgraph-io/dgraph/blob/8cb805db531700f3ea0226d4b074d9086c486426/posting/list.go#L714-L716

One solution is to include it if it is a delete posting. Thoughts @janardhan1993?
