### ISSUE TITLE
Are atomic transactions supported?

### ISSUE THREAD

**Issue by qm3ster** [dgraph-io/dgraph#2183]
The documentation is confusing, in the sense that:

[The go client docs say Dgraph (not Dgraph go client or anything) supports ACID transactions since v0.9
](https://docs.dgraph.io/clients/#create-a-transaction) (and not just snapshot isolation, but actually returning an error on conflicts and not leaving a dirty database)
[Comparison with Neo4j says that Dgraph has distributed ACID transactions
](https://docs.dgraph.io/dgraph-compared-to-other-databases/#transactions)
[Design Concepts says ACID transactions through snapshot isolation, with no links or details](https://docs.dgraph.io/design-concepts/#transactions-faq)
[Then, on the very same page, Note on Transactions says that transactions are not supported "at this point", and then it never mentions _doing a transaction_, only mutations (during the application of which there may be inconsistent reads)](https://docs.dgraph.io/design-concepts/#note-on-transactions)

PLZ HALP

[Then there's also an example of read-then-write transaction in the "Raw HTTP" client](https://docs.dgraph.io/clients/#start-a-transaction)

It seems that it's just the Note on Transactions that's wrong?

Or can reads during the successful application of a transaction end up with non-atomic results?

**Comment by manishrjain** [comment]
Fully ACID transactions with snapshot isolation are supported. The confusing note on transactions was old and was recently removed from master. I've removed it from the latest branch as well.
