### ISSUE TITLE
dgraph keeps crashing when trying to insert new nodes

### ISSUE THREAD

**Issue by zboralski** [dgraph-io/dgraph#2184]
I am trying to import about 250,000 unique nodes. If the uid for the node doesn't exist I created it or skip otherwise.

First it crashed with 

```
dgraph-server.log-2018/03/02 19:32:06 raft.go:664: INFO: 1 received MsgVoteResp 
from 1 at term 5   
dgraph-server.log-2018/03/02 19:32:06 raft.go:621: INFO: 1 became leader at term
 5
dgraph-server.log-2018/03/02 19:32:06 node.go:301: INFO: raft.node: 1 elected le
ader 1 at term 5   
dgraph-server.log:fatal error: runtime: out of memory
dgraph-server.log- 
dgraph-server.log-runtime stack:
dgraph-server.log-runtime.throw(0x131c5df, 0x16)
dgraph-server.log-      /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/run
time/panic.go:605 +0x95
```

It runs on a Compute Engine instance with 8GB of ram ... I start the server like this:

dgraph server --memory_mb 4096 --zero localhost:5080 

then I tried using --posting_tables memorymap

It crashed again with `runtime: out of memory`.

I tried running dgraph server in debugmode and now it just hangs:

2018/03/03 13:02:16 server.go:398: Received query: query ID($n: string){
                instagram(func: eq(pk, $n)) {
                        uid
                }  
        }
2018/03/03 13:02:28 draft.go:616: Couldn't take snapshot, txn watermark: [108183], applied watermark: [142292]
2018/03/03 13:02:58 draft.go:616: Couldn't take snapshot, txn watermark: [108183], applied watermark: [142292]
2018/03/03 13:03:28 draft.go:616: Couldn't take snapshot, txn watermark: [108183], applied watermark: [142292]
2018/03/03 13:03:58 draft.go:616: Couldn't take snapshot, txn watermark: [108183], applied watermark: [142292]
2018/03/03 13:04:28 draft.go:616: Couldn't take snapshot, txn watermark: [108183], applied watermark: [142292]
2018/03/03 13:04:58 draft.go:616: Couldn't take snapshot, txn watermark: [108183], applied watermark: [142292]
2018/03/03 13:05:28 draft.go:616: Couldn't take snapshot, txn watermark: [108183], applied watermark: [142292]
2018/03/03 13:05:58 draft.go:616: Couldn't take snapshot, txn watermark: [108183], applied watermark: [142292]

I tried using the nightly build and I have the same issue.

**Comment by zboralski** [comment]
Just tried restarting the server and it hangs in the same place.

**Comment by zboralski** [comment]
tried again with another instance with 32GB .. it ran longer but ultimately it crashed again with `runtime: out of memory.`

**Comment by zboralski** [comment]
Everything worked with `dgraph server --memory_mb 16000 --zero localhost:5080 --posting_tables memorymap`

Is there anyway to know how to plan memory requirements, etc?

**Comment by janardhan1993** [comment]
Can you please share your p and w directory

**Comment by janardhan1993** [comment]
Closing this issue, not enough information.
