### ISSUE TITLE
Dgraph Questions

### ISSUE THREAD

**Issue by candysmurf** [dgraph-io/dgraph#2191]
1. Differences between `name` and `name@.`?

eg. query returns `Michael` as his friend's friend only. When using `name@.`, it returned a list of friends including himself. 
```
{
  michael_friends_and_pet(func: eq(name, "Michael")) {
    name
    age
    friend {
      name@.
      friend {
        name
      }
    }
    owns_pet {
      name
    }
  }
}
```

2. When running the same query twice, it creates the duplicate nodes/graphs. How to make it unique?

**Comment by pawanrawal** [comment]
1. The documentation should give some clarity about the language rules: https://docs.dgraph.io/query-language/#language-support.

2. Could you clarify what you mean there with an example? Are you talking about a query or mutation?

For future, I would recommend posting questions about the query language on https://discuss.dgraph.io/. We prefer to have issues/feature requests on Github.
