### ISSUE TITLE
about vendoring libraries

### ISSUE THREAD

**Issue by llonchj** [dgraph-io/dgraph#2192]
It is well known that vendoring libraries has some issues.

The application I use imports  `github.com/dgraph-io/dgraph/client` and `github.com/dgraph-io/dgraph/protos/api`.

Adding prometheus instrumentation in my application, I get the following panic:

```goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(0x1a1d39b, 0x1f, 0xc4204b8660, 0xc4204b8690)
	/Users/llonchj/go/src/github.com/golang/protobuf/proto/properties.go:815 +0x135
github.com/dgraph-io/dgraph/vendor/github.com/prometheus/client_model/go.init.0()
	/Users/llonchj/go/src/github.com/dgraph-io/dgraph/vendor/github.com/prometheus/client_model/go/metrics.pb.go:363 +0x4e
exit status 2```

A temporary fix has been to remove `/Users/llonchj/go/src/github.com/dgraph-io/dgraph/vendor/github.com/prometheus` to let golang import this package from GOPATH.

I understand this is a issue is correlated with prometheus project.

Any ideas?

**Comment by pawanrawal** [comment]
That is a bit strange. What commit version are you at for the dgraph/client? The client used to import `dgraph/x` package earlier, which in turn used to import `prometheus` but the dependency of the client on the `x` package was removed long back.

The full panic log is shown below for anyone else looking at the issue.

panic: proto: duplicate enum registered: io.prometheus.client.MetricType

```
goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(0xa5a264, 0x1f, 0xc420159e60, 0xc420159e90)
	/home/pawan/go/src/github.com/golang/protobuf/proto/properties.go:815 +0x13e
github.com/prometheus/client_model/go.init.0()
	/home/pawan/go/src/github.com/prometheus/client_model/go/metrics.pb.go:363 +0x4e
github.com/prometheus/client_model/go.init()
	<autogenerated>:1 +0x35c
github.com/prometheus/client_golang/prometheus.init()
	<autogenerated>:1 +0x50
main.init()
	<autogenerated>:1 +0x71
exit status 2
```

**Comment by llonchj** [comment]
I use commit 5dbb7dbcecc0720ceea5bfbea0a51e8a383d9dd8

I removed `/Users/llonchj/go/src/github.com/dgraph-io/dgraph/vendor/github.com/prometheus` as a temporary workaround.

**Comment by pawanrawal** [comment]
@llonchj mentioned that he is using the `types` package which depends on `x`, which in turn imports `prometheus` from vendor folder that is why this issue occurs.

**Comment by pawanrawal** [comment]
I have removed prometheus from vendor, so if pull the latest `dgraph` this issue should be resolved. A lot of these issues would automatically be solved when the community moves to `dep` which does a better job of handling these.

**Comment by llonchj** [comment]
It works. Thank you @pawan!

2018-03-21 11:48 GMT+11:00 Pawan Rawal <notifications@github.com>:
