### ISSUE TITLE
TiKV

### ISSUE THREAD

**Issue by ShalokShalom** [dgraph-io/dgraph#2196]
Absolutely astonishing idea, also applyable to your project: https://github.com/cayleygraph/cayley/issues/688 :D

TiKV is a key value store, which is written in Rust.

**Comment by manishrjain** [comment]
Dgraph implements the distributed layer as opposed to Cayley which expects the underlying DB to provide that. So, this isn't applicable to Dgraph. We use Badger (previously RocksDB) to do data storage locally.

**Comment by ShalokShalom** [comment]
Oh fine
