### ISSUE TITLE
Add '@async' modifier to index creation section of docs

### ISSUE THREAD

**Issue by tamethecomplex** [dgraph-io/dgraph#2199]
Maybe I'm missing it, but I don't see any documentation in the 1.0.3 docs (or master) about how to use the async index feature ([https://github.com/dgraph-io/dgraph/issues/1854](https://github.com/dgraph-io/dgraph/issues/1854)).

**Comment by manishrjain** [comment]
The change was done as part of the mutation, not as part of the schema. Though, we're actually going to make an inverse change. Indices would always be part of the txn, but with this new change, a user would have to indicate if they should be part of the conflict detection. That would decrease the number of conflicts significantly.

**Comment by manishrjain** [comment]
@pawanrawal Do we have a Github issue to that effect. If so, can you please link it here, and close this issue?

**Comment by pawanrawal** [comment]
Just created the issue https://github.com/dgraph-io/dgraph/issues/2200. Closing this one.
