### ISSUE TITLE
Replicas shouldn't fetch snapshot when they start with same data in p directory as the leader

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#2202]
The typical use case is that say you want to load some data using bulk loader and start three nodes (one leader and 2 follower replicas) using this data. At the moment the 2 nodes which become the follower still fetch the snapshot although the data in their `p` directory is same as the leader. This is unnecessary and slow. 

This is because `minTs` is still `0` for the replicas as we start getting deltas from Zero after the node is part of a group.

**Comment by manishrjain** [comment]
Hmm.. it would be hard to determine if the data is the same or not. It's almost better to just let the replicas copy over the data from the leader.

**Comment by pawanrawal** [comment]
Ok, closing this.
