### ISSUE TITLE
Downloading the go client is too slow

### ISSUE THREAD

**Issue by sjama** [dgraph-io/dgraph#2203]
`go get -u -v github.com/dgraph-io/dgraph/client` is painfully slow. 
It seems the entire Dgraph source tree is been pulled when all I want is the client.

I think there is good case to made to break the client out into a separate repo. Because the wait time is acting as major hinderance to getting started with Dgraph especially for new users.

**Comment by manishrjain** [comment]
Maybe it makes sense to break the client out, now that we already have a bunch of clients which are all in separate repos.

**Comment by pawanrawal** [comment]
Adding steps here so that I remember.

- [ ] Move all code for the client along with the integration tests to [https://github.com/dgraph-io/dgo](https://github.com/dgraph-io/dgo).
- [ ] Update README for the client to be in sync with how it is for other clients.
- [ ] Setup CI on TeamCity.

**Comment by pawanrawal** [comment]
The client has been moved and doesn't have any dependence on `dgraph-io/dgraph` anymore.

**Comment by sjama** [comment]
+1
