### ISSUE TITLE
Expanding predicates example in docs freezes then crashes browser tab

### ISSUE THREAD

**Issue by armaneous** [dgraph-io/dgraph#2207]
Running the last example under "Expand Predicates" seems to freeze then crash my browser tab. Seems the process hangs.

https://docs.dgraph.io/query-language/#expand-predicates

**Comment by manishrjain** [comment]
➤ Garvit Pahal commented:

The browser tries to retrieve and render a lot of data. On my machine, Chome hanged after retrieving about 3.5 MB of data. I have updated the query to not so resource consuming by removing the last nesting.
