### ISSUE TITLE
Documentation Bug : Getting started should have a query to show all movies

### ISSUE THREAD

**Issue by Graphpinto** [dgraph-io/dgraph#2208]
Hi everyone, just starting with dgraph…AWESOME so far…One question, in the movies example from the docs, how can I get all the movies (*)?

>> We should capture this in the docs, as an example.
pawan [7:38 PM]
All movies have a `starring` edge, so you could do something like this.
```{
  me(func: has(starring), first:10) {
   name@en
  }
}```

**Comment by Graphpinto** [comment]
@pawanrawal - Can you please point me to the documentation repository for this one so I can try my hand at adding it in?

**Comment by pawanrawal** [comment]
Its part of the Dgraph repo at https://github.com/dgraph-io/dgraph/tree/master/wiki. You would probably add the example to the [query language page](https://github.com/dgraph-io/dgraph/blob/master/wiki/content/query-language/index.md).

**Comment by Graphpinto** [comment]
Hey Pawan, I have put a bit of more context into the getting started page, and added this example there after index creation example
