### ISSUE TITLE
CPU maxes out randomly during cleaning operation / batch loading

### ISSUE THREAD

**Issue by Graphpinto** [dgraph-io/dgraph#2210]
CPU on one node seems to max out totally during a "cleaning operation" which happens randomly.  If this happens during your initial batch load the results can be catastrophic.  If you only have one node then the results are especially catastrophic.

**- What version of Dgraph are you using?**

**- Have you tried reproducing the issue with latest release?**

**- What is the hardware spec (RAM, OS)?**

**- Steps to reproduce the issue (command/config used to run Dgraph).**

**Comment by manishrjain** [comment]
No reproducible steps.
