### ISSUE TITLE
HA on k8s gets into crash backoff cycle on one of the dgraph-server groups

### ISSUE THREAD

**Issue by JessicaCGlenn** [dgraph-io/dgraph#2214]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
1.0.3

- Have you tried reproducing the issue with latest release?
yes (tried with 1.0.4)

- What is the hardware spec (RAM, OS)?
Running on GCE n1-standard-8, 8 CPUs and 30GB

- Steps to reproduce the issue (command/config used to run Dgraph).

Run a DGraph HA cluster on K8s. (3 x 0, 9 x server, with a replication factor of 3) - just using the 

Run at a steady 80 mutations per second

Increase to ~100 mutations per second

Wait approximately 2 hours

- Expected behaviour and actual result.

Expected behaviour: Continue to run smoothly

Actual Behaviour: After a while one of the groups begins to crash and then causes a crash loop backoff cycle. Even after restarting the pods, the issue remains and 2 of the three pods in the group continue to crash.

Removing the nodes from the cluster and then creating them again doesn't seem to work either.

The only way I have been able to fix this so far is to destroy the entire cluster and then start again.
![image](https://user-images.githubusercontent.com/2882043/37267446-74f0413a-2614-11e8-8eed-da9648bb5d83.png)

**Comment by janardhan1993** [comment]
Can you please share your w directory

**Comment by pawanrawal** [comment]
PR: #2309 solves the issue, it will be merged right before releasing `v1.1`.

**Comment by pawanrawal** [comment]
Fixed via 9951c98f7c1880743994820263b08a73f943c8e7.
