### ISSUE TITLE
Documentation for configuration with TLS authentication is unclear.

### ISSUE THREAD

**Issue by ospaarmann** [dgraph-io/dgraph#2216]
I started writing a [Dgraph client for Elixir](https://github.com/ospaarmann/exdgraph) and am struggling to implement TLS authentication. In general more explaining regarding the TLS config is in order. I find the documentation quite unclear. An example setup with TLS enabled and also maybe a separate client auth via TLS would be nice to have. 

[I know that there is a section about TLS in the documentation.](https://docs.dgraph.io/deploy/#tls-configuration). But it mainly states the available config options without giving examples, stating precisely which ones are needed for which setup and what values are in general expected for each parameter. 

**What is expected here for example?**

```
# Enable TLS client authentication
tls_client_auth string
```

An improvement of the documentation or an example posted in here would be of great help. Thank you!

**Comment by Graphpinto** [comment]
Hey @pawanrawal  -- Happy to help with this one. Please assign this to me.

Thanks,

**Comment by pawanrawal** [comment]
Done, also have a look at https://github.com/dgraph-io/dgraph/issues/2222 where I provided some details.
