### ISSUE TITLE
Int predicate outputted as float in rdf exports

### ISSUE THREAD

**Issue by zboralski** [dgraph-io/dgraph#2217]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

Dgraph version   : v1.0.3
Commit SHA-1     : e28847e7
Commit timestamp : 2018-02-08 10:43:50 +1100
Branch           : HEAD

- Have you tried reproducing the issue with latest release?

yes

- What is the hardware spec (RAM, OS)?

32GB, Debian

- Steps to reproduce the issue (command/config used to run Dgraph).

curl localhost:8080/admin/export

- Expected behaviour and actual result.

I should get something like :
<_:uid3c6> <pk> "123123123123"^^<xs:int> .

instead I get :

<_:uid3c6> <pk> "2.84904199E+08"^^<xs:float> .

**Comment by pawanrawal** [comment]
Related post on discourse: https://discuss.dgraph.io/t/how-come-int-predicates-outputted-as-float-in-the-export/2304

**Comment by pawanrawal** [comment]
How do you do your mutations (JSON/RDF/Nquads)? Do you explicitly use RDF types?

**Comment by zboralski** [comment]
the nodes and edges were created using the go api and json marshalled structures... the schema was created using the UI in dgraph-ratel.

**Comment by pawanrawal** [comment]
Ok, so while deserializing the JSON we assume `float` [RDF type](https://docs.dgraph.io/query-language/#rdf-types) for all numbers. The RDF type is used to make the internal encoding more efficient. This shouldn't affect your query and you should still get back results in your schema type.
