### ISSUE TITLE
has function doesnt support predicate with "-" in it

### ISSUE THREAD

**Issue by coolguru** [dgraph-io/dgraph#2226]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.4

- Have you tried reproducing the issue with latest release?

- What is the hardware spec (RAM, OS)?

- Steps to reproduce the issue (command/config used to run Dgraph).

- Expected behaviour and actual result.

**Comment by pawanrawal** [comment]
Fixed in master with 1df58ac04f6d039d472230d437ca23155655faf2.
