### ISSUE TITLE
Leader not copying snapshots to replicas if replicas start almost immediately after first server

### ISSUE THREAD

**Issue by emhagman** [dgraph-io/dgraph#2236]
I have a fairly large dataset (700+ MB of a text RDF file). I bring up the first server (leader) with this exported data via the bulk loader (map 2, shard 1). Once I start the second server after the first is up, data will not copy over to it even though the first server was determined to be the leader.

However, if I do the exact same thing but wait a few minutes for the "leader" to presumably catch up, then bring up the second server, it copies the data over. It takes roughly 1.5 hours for the data to copy (2.4GB) to the replica but it appears to work.

What version of Dgraph are you using? 1.04
Have you tried reproducing the issue with latest release? Yes
What is the hardware spec (RAM, OS)? Ubuntu 16.04, Docker, 32GB Ram
Steps to reproduce the issue (command/config used to run Dgraph). Large dataset for leader (700+MB RDF)
Expected behaviour and actual result: Leader to immediately start sending data to followers

**Comment by janardhan1993** [comment]
Thanks for reporting this, i was able to reproduce it. Will fix the issue
