### ISSUE TITLE
Colons and URIs in predicates for schemas

### ISSUE THREAD

**Issue by alexmilowski** [dgraph-io/dgraph#2237]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

1.04

- Have you tried reproducing the issue with latest release?

Yes

- Steps to reproduce the issue (command/config used to run Dgraph).

Attempt to define a schema for a predicate that is a URI or CURIE 

- Expected behaviour and actual result.

You can insert data like:

_:n11 <osv:amount> "5350"

but you can't defined a schema for the CURIE:

osv:amount: int .

Similarly issues if the predicate is a full URI.

**Comment by janardhan1993** [comment]
@alexmilowski  You need to surround the predicates with <> if the predicate contains ":" since ":" is used as a separator while parsing schema.

The following should work
```<os:amount>: int . ```

**Comment by pawanrawal** [comment]
Added a note at https://docs.dgraph.io/master/query-language/#adding-or-modifying-schema.
