### ISSUE TITLE
Performance drop on filtering

### ISSUE THREAD

**Issue by inoc603** [dgraph-io/dgraph#2239]
I'm using dgraph 1.0.3, on a 8 core 16G RAM CentOS 7 instance, with a small data set of 10k nodes and 60k edges.

The query I use is like this:

```
{  
  v(func: eq(pred1, "value1")) {
    pred2 @filter(eq(pred3, "value2")) {
      pred4
    }
  }
}
```

This query is taking around 160ms when the server is idle. If I run this query with multiple clients concurrently, it takes awfully more time as concurrency increases. In my case, 8 clients make the query takes up to 1s.

If I remove the `@filter(eq(pred3, "value2"))` filter, it only takes 2ms, and the time will not increase with much more concurrent clients.

The schema on `pred3` is `string @index(hash) .`, which is said to have the best indexing performance in the docs.

I profiled dgraph server, and find that `filterStringFunction` and `handleCompareFunction` are taking up most of the CPU time. I'm not familiar with the codebase, and didn't have the time to dig further. Would you please investigate this performance issue?

[pprof.dgraph.samples.cpu.007.pb.gz](https://github.com/dgraph-io/dgraph/files/1823671/pprof.dgraph.samples.cpu.007.pb.gz)

**Comment by pawanrawal** [comment]
Hi @inoc603 

In this case, the time spent in `handleCompareFunction` could mostly be avoided by having an `exact` index instead. Regarding the `filterStringFunction`, do any of your predicates have language tags, like `name@en`?

**Comment by inoc603** [comment]
Using an `exact` index indeed makes `handleCompareFunction` go away. The query time improved a little bit, but no significant difference when I use 8 clients.

There are no language tags in any of my predicates.

The new profile with `exact` index: 
[pprof.dgraph.samples.cpu.009.pb.gz](https://github.com/dgraph-io/dgraph/files/1827806/pprof.dgraph.samples.cpu.009.pb.gz)

**Comment by pawanrawal** [comment]
I think for your use case you don't need to pay the performance penalty of `filterStringFunction` (it's only important if your predicate had language tags). I will see how we can come up with a construct that avoids this penalty by next release.

**Comment by inoc603** [comment]
Thanks! 

We're moving a project from MySQL to dgraph, and we currently use filters to replace most of the `WHERE` in SQL. While you guys are working on this improvement, I'll try to re-model our data to reduce filter usage.

Looking forward to the next release. Please keep me updated.

**Comment by pawanrawal** [comment]
So we only need to do this check if a predicate can have values with lang tags. For other predicates, we can skip the `filterStringFunction` for an `eq` query.  

We will have a `@lang` directive in the schema. Only predicates with this directive can add mutation and query for a predicate with any language tag. This would avoid the unnecessary second lookup for predicates which would never have a value with a language tag.

**Comment by pawanrawal** [comment]
An improvement has been merged to master with f455229d773e9168002ad3d5ccc8ac083c54d91a.

**Comment by inoc603** [comment]
@pawanrawal I tried the latest master, and can confirm that filtering performance has improved tremendously on the same setup I had before. Now the query with filter can run as fast as the one without filter.

Good Job! Thanks!

**Comment by pawanrawal** [comment]
Awesome! Closing this issue.
