### ISSUE TITLE
Mutation failures with large uid values

### ISSUE THREAD

**Issue by neilpa** [dgraph-io/dgraph#2242]
- What version of Dgraph are you using?
1.0.4

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
Linux, 8MB

- Steps to reproduce the issue (command/config used to run Dgraph).
Running a single dgraph zero and dgraph server process on the same box

- Expected behaviour and actual result.
Imported a few million nodes and edges into a DB. Subsequent attempts to mutate values fail with an error like `Uid: [6846115] cannot be greater than lease: [10000]`

```
$ curl localhost:8080/query -s -XPOST \
   -d '{ q(func: uid(0x6876A3)) { uid, expand(_all_) } }' | jq .
{
  "data": {
    "q": [
      {
        "uid": "0x6876a3",
        "person.dob": "1973-03-22T00:00:00Z",
        "person.name": "John Doe",
        "person.public_id": "082eb02f32e213f9e21fe1a2c0306d29",
        "type.person": true
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 50,
      "processing_ns": 20647269,
      "encoding_ns": 317983
    },
    "txn": {
      "start_ts": 1635,
      "lin_read": {
        "ids": {
          "1": 15
        }
      }
    }
  }
}

$ curl -s -H 'X-Dgraph-CommitNow: true' localhost:8080/mutate -XPOST \
      -d '{ set { <0x6876A3> <person.name> "Jane Doe" . } }' | jq .
{
  "errors": [
    {
      "code": "ErrorInvalidRequest",
      "message": "Uid: [6846115] cannot be greater than lease: [10000]"
    }
  ],
  "data": null
}
```

**Comment by pawanrawal** [comment]
> Imported a few million nodes and edges into a DB.

How did you import the data? `Zero` maintains and stores the lease in `zw` directory. I suspect you are not using the same `zw` directory for Zero which was used while importing the nodes and edges and hence the lease is starting fresh.

**Comment by neilpa** [comment]
I did a bulk import locally and moved the resulting `p` directory to a different machine but not `zw`. Didn't realize this was necessary. Thanks.

**Comment by cyy0523xc** [comment]
```sh
curl "localhost:8080/mutate" -H "X-Dgraph-CommitNow: true" -XPOST -d $'{set {<0x50000> <name> "hello Princess Leia" .}}'|json_pp

{
   "data" : null,
   "errors" : [
      {
         "code" : "ErrorInvalidRequest",
         "message" : "Uid: [327680] cannot be greater than lease: [200000]"
      }
   ]
}
```

dgraph was started like this:

```sh
# Directory to store data in. This would be passed to `-v` flag.
mkdir -p /tmp/data

# Run Dgraph Zero
docker run -it -p 5080:5080 -p 6080:6080 -p 8080:8080 -p 9080:9080 -p 8000:8000 --name diggy dgraph/dgraph dgraph zero

# Run Dgraph Server
docker exec -it diggy dgraph server --memory_mb 2048 --zero localhost:5080
```

**Comment by pawanrawal** [comment]
Was that uid returned by Dgraph? If not, then you can't use uids not returned by Dgraph.

**Comment by cyy0523xc** [comment]
oh...i get it. The uid must be returned by Dgraph! 
It can not be specified by mysql?

**Comment by shanghai-Jerry** [comment]
@cyy0523xc  i also want to know how to specify a uid myself.
