### ISSUE TITLE
Authentication support in badger

### ISSUE THREAD

**Issue by asimpatnaik** [dgraph-io/dgraph#2247]
Hi,
Currently there is no authentication support. It will be a great feature to have. 
We are using badger for developing a banking solution and data privacy is a requirement.
Kindly let me know if you can incorporate the security feature.

Regards,
Asim.

**Comment by MichelDiz** [comment]
In part you can do it https://docs.dgraph.io/howto/#a-simple-login-system
Any protected node can be filtered by business logic.

You can add a "kind/label" to a protected node and then make some protection filtering by "has":
```
{
  q(func: has(__protected)) {
    pred @filter(__strictly.protected) {
      ...
    }
  }
}
```

**Comment by asimpatnaik** [comment]
I'm closing this issue as I have raised one issue under badger. Thanks for your pointer.
