### ISSUE TITLE
Dgraph bulk setting up cluster 

### ISSUE THREAD

**Issue by sameervitian** [dgraph-io/dgraph#2252]
dgraph version using - 1.0.4

OS - ubuntu 14.04 / 16 core 32GB

I am generating the bulk load data by using - 
`dgraph bulk -s=schema.rdf.gz -r=data.rdf.gz -z=zero_ip:5080 --map_shards=4 --reduce_shards=3`

To run above I am running just 1 dgraph-zero and none of the dgraph server(total is 3). 

Do I need to copy the generated output to `p` folder of each server manually. Will it not sync if I copy to one server and  bring up all the 3  dgraph servers.

I tried to copy the output folder to 1 server and start others. It seems that the sync among server does not happen. Just curious if I am doing something wrong?

**Comment by janardhan1993** [comment]
You need to copy for each group. For replicas you needn't copy they will fetch it automatically from the first node(leader) which was started for each group.

**Comment by sameervitian** [comment]
I tried but it did not happen . 
I have put replicas=3 in dgraphzero and used `dgraph bulk -s=schema.rdf.gz -r=data.rdf.gz -z=zero_ip:5080` for data import. And then poined -p directory to `out/0/p` folder on a dgraph node . And then started this dgraph server. And then started other dgraph servers. The data sync does not happen among other nodes.

**Comment by janardhan1993** [comment]
Can you please try with master.

**Comment by pawanrawal** [comment]
You can get the nightly binaries from https://docs.dgraph.io/deploy#nightly. Also, make sure the first server that you start with the `p` directory becomes a leader before starting other replicas.

**Comment by sameervitian** [comment]
@janardhan1993 should I build from master? is there some issue  https://github.com/dgraph-io/dgraph/releases/download/v1.0.4/dgraph-linux-amd64.tar.gz 

@pawanrawal how to check if the dgraph started has become leader? also seems the `/state` endpoint on https://docs.dgraph.io/deploy#more-about-dgraph-zero doesnt work .

**Comment by janardhan1993** [comment]
@sameervitian  There was a issue which was fixed in master when you start all instances at same time.

You can see in stdout logs when a node becomes leader. You can build from master or get our nightly build as suggested by pawan

**Comment by sameervitian** [comment]
@janardhan1993 will it be safe to use nightly build in production system

**Comment by sameervitian** [comment]
@janardhan1993 @pawanrawal  using nightly binary did not help. 

Dgraph version   : v1.0.4-dev
Commit SHA-1     : 807976c4
Commit timestamp : 2018-03-22 14:55:24 +1100
Branch           : HEAD


The `p` directory on the leader node is of 11 GB. Data sync to remaining node did not happen. 
Following is the log for the first node on which the `/p` directory was copied. 

2018/03/23 16:36:46 groups.go:86: Current Raft Id: 0
2018/03/23 16:36:46 gRPC server started.  Listening on port 9080
2018/03/23 16:36:46 HTTP server started.  Listening on port 8080
2018/03/23 16:36:46 worker.go:99: Worker listening at address: [::]:7080
2018/03/23 16:36:46 pool.go:118: == CONNECT ==> Setting 172.21.252.29:5080
2018/03/23 16:36:46 groups.go:109: Connected to group zero. Assigned group: 1
2018/03/23 16:36:46 draft.go:139: Node ID: 1 with GroupID: 1
2018/03/23 16:36:46 node.go:259: Group 1 found 0 entries
2018/03/23 16:36:46 draft.go:756: New Node for group: 1
2018/03/23 16:36:46 raft.go:567: INFO: 1 became follower at term 0
2018/03/23 16:36:46 raft.go:315: INFO: newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2018/03/23 16:36:46 raft.go:567: INFO: 1 became follower at term 1
2018/03/23 16:36:46 node.go:128: Setting conf state to nodes:1
2018/03/23 16:36:46 raft.go:749: INFO: 1 is starting a new election at term 1
2018/03/23 16:36:46 raft.go:580: INFO: 1 became candidate at term 2
2018/03/23 16:36:46 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 2
2018/03/23 16:36:46 raft.go:621: INFO: 1 became leader at term 2
2018/03/23 16:36:46 node.go:301: INFO: raft.node: 1 elected leader 1 at term 2
2018/03/23 16:36:46 groups.go:340: Serving tablet for: _predicate_
2018/03/23 16:36:46 groups.go:340: Serving tablet for: doing
2018/03/23 16:36:46 mutation.go:191: Done schema update predicate:"_predicate_" value_type:STRING list:true
2018/03/23 16:36:55 groups.go:340: Serving tablet for: iskol
2018/03/23 16:36:55 groups.go:340: Serving tablet for: idshop
2018/03/23 16:36:57 groups.go:340: Serving tablet for: iduser
2018/03/23 16:37:03 groups.go:340: Serving tablet for: category
2018/03/23 16:37:03 groups.go:340: Serving tablet for: favorite
2018/03/23 16:37:07 groups.go:340: Serving tablet for: idactivity
2018/03/23 16:37:34 groups.go:340: Serving tablet for: create_time
2018/03/23 16:40:09 pool.go:118: == CONNECT ==> Setting 172.21.252.28:7080
2018/03/23 16:40:14 predicate.go:260: Sending SNAPSHOT: Time elapsed: 05s, bytes sent: 0 B, bytes/sec 0
2018/03/23 16:40:19 predicate.go:260: Sending SNAPSHOT: Time elapsed: 10s, bytes sent: 0 B, bytes/sec 0

2018/03/23 16:40:24 predicate.go:260: Sending SNAPSHOT: Time elapsed: 15s, bytes sent: 0 B, bytes/sec 0
2018/03/23 16:40:25 node.go:128: Setting conf state to nodes:1 nodes:2


Is there any better way to troubleshoot?

**Comment by sameervitian** [comment]
here is the conf for the dgraph zero 
```
idx: 1
replicas: 3
wal: /data/dgraph/wz
bindall: true
my: 172.21.252.29:5080
```

**Comment by janardhan1993** [comment]
@sameervitian  Are you using the same zw directory of zero.

**Comment by sameervitian** [comment]
I was able to solve it. It happened because I created the p folder using a dgraph zero and latter on deleted the zw folder. And restarted the dgraph zero again.
