### ISSUE TITLE
upsert feature do not work as documented

### ISSUE THREAD

**Issue by arunparmar007** [dgraph-io/dgraph#2253]
Summary: the upsert feature does not seem to work as documented or maybe I am missing something here.

- What version of Dgraph are you using?

version: 1.0.4

- Have you tried reproducing the issue with latest release?

Yes

- What is the hardware spec (RAM, OS)?

Microsoft Windows 10

- Steps to reproduce the issue (command/config used to run Dgraph).

The following code which tries to use upsert does not seem to work.
The main java class for testing upsert is as follows:
  https://gist.github.com/arunparmar007/b7edd4fac17813da4730fc1e326b5951

The data class sd source code is as follows:
  https://gist.github.com/arunparmar007/17cdad500d4d46deeb81898566e1c8d6

- Expected behavior and the actual result.

Multiple executions of the above source code result into multiple nodes with same upsert property.

**Comment by janardhan1993** [comment]
@arunparmar007 Are you using replicas or using single node ?

**Comment by arunparmar007** [comment]
single node,but yes planing to use cluster .
