### ISSUE TITLE
Transaction incomplete due to "moving predicate"

### ISSUE THREAD

**Issue by alexmilowski** [dgraph-io/dgraph#2255]
While inserting a lot of content I got the response:

"[{'code': 'ErrorInvalidRequest', 'message': 'Predicate is being moved, please retry later'}]"

In the "errors" attribute of the JSON response.

Having to retry a transaction because the database is shuffling storage seems very unfortunate. Why wouldn't the database just delay the transaction till the reorganization is incomplete.

Further, a 200 response over HTTP for a request that is not honored seems inconsistent.

**Comment by alexmilowski** [comment]
Possibly a 409 response should have been used.

**Comment by manishrjain** [comment]
Blocking a transaction for the duration of a predicate move isn't necessarily better. By rejecting it quickly, the user can react to this information. For e.g., retry with a backoff, or switch to other predicate, etc.

The HTTP code, we had many debates about that early on, and the consensus is to use 200 as long as the request was processed, and indicate the errors in JSON format -- this is also the GraphQL spec.

**Comment by alexmilowski** [comment]
There is no way in the JSON response to understand that the transaction just needs to be retried. It just indicates there is an error.  That error could have been caused by a bad mutation, the predicate move, or some other error.

For a reliable system in an enterprise environment, you need to be able to differentiate between operations that should be retried from those that are not.  At least you should put into the operation some property that would allow a client to decide.

In this particular case, this is most certainly akin to a "503 Service Unavailable" or "409 Conflict" response status codes. You need to replicate that kind of information in the JSON so a client can understand that their request was denied because the server was "busy".

The need for this in the response still stands.
