### ISSUE TITLE
200 response for errors

### ISSUE THREAD

**Issue by alexmilowski** [dgraph-io/dgraph#2256]
When errors occur the HTTP protocol the server still returns a response with a 200 status code. It would be good for the status codes for the HTTP protocol to be more meaningful and track along with whether the transaction completely or had issues.

**Comment by manishrjain** [comment]
As per the GraphQL spec, using the same HTTP response code, but with the right error message is the best practice. If we use different codes, then it gets hard to judge whether the problem was with the system or with the query.

http://facebook.github.io/graphql/October2016/#sec-Errors

**Comment by alexmilowski** [comment]
That decision is contrary to the architecture of the web. It is most certainly not hard to judge as the status code helps the client differentiate between "success" and "not success".

See "Architecture of the World Wide Web, Volume One", specifically the section on error handling:
https://www.w3.org/TR/2004/REC-webarch-20041215/#error-handling

**Comment by manishrjain** [comment]
GraphQL spec passes errors in JSON. If HTTP 200 code isn't passed, then that detailed error would be lost. This definitely deviates from REST architecture, but there are valid reasons to use this approach. See comment here:

https://github.com/graphql/express-graphql/issues/116#issuecomment-356322764

**Comment by alexmilowski** [comment]
That comment presents a rather week argument. Clients not parsing the entity body because they do a full stop when they encounter a non-200 status code is just poor coding.  Interpretation of non-200 responses has been around for a very long time and is considered normal behavior.

Meanwhile, this seems to be the way GraphQL is specified. C'est la vie.
