### ISSUE TITLE
DQL variables don't seem to be supported in arrays

### ISSUE THREAD

**Issue by ondrowan** [dgraph-io/dgraph#2272]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

1.0.4

- Steps to reproduce the issue (command/config used to run Dgraph).

```
query all($a: string, $b: string) {
  all(func: eq(whatever, [$a, $b])) {
    uid,
  }
}
```

> Expected comma or language but got: a

- Expected behaviour and actual result.

Either I'm doing something wrong or GraphQL variables that are used in arrays don't work. And since it's not possible to define variable as arrays, it also seems impossible to do something like:

```
query all($a: [string]) {
  all(func: eq(whatever, $a)) {
    uid,
  }
}
```

**Comment by jmaeso** [comment]
Same happened me, trying the function for getting near locations:
```
query test($long: string, $lat: string, $radius: string){
	test(func: near(loc, [$long, $lat] , $radius)){
		uid
	}
}
```
It returns: `rpc error: code = Unknown desc = Found invalid item: $ while parsing geo arguments.`

As a workaround:
```
// Create the string with the array inside:
lat := "1.0"
lon := "-2.0"
radius := "200000"
variables := map[string]string{
	"$coords": "[" + lon + ", " + lat + "]", // aka: "[1.0, -2.0]"
	"$radius": radius,
}

// And pass the string to the query:
query test($coords: string, $radius: string){
	test(func: near(loc, $coords , $radius)){
		uid
	}
}
```

Hope this help someone

**Comment by manishrjain** [comment]
I don't think this is supported. You'd have to run this in 2-queries.

**Comment by F21** [comment]
Just a quick note that @jmaeso 's solution unfortunately does not work with `eq()`.

Query:
```
query Assets ($ids: string){
	asset(func: eq(name, $ids)){
		uid
		name
	}
}
```
Variables:
```
"$ids": "[\"a1\", \"a2\"]"
```

This returns nothing, because dgraph is probably treating `["a1", "a2"]` as the string it's trying to match.

**Comment by MichelDiz** [comment]
Just an update on this thread.

```
query geoq($loca:string = "[-122.469829, 37.771935]") {
  tourist(func: near(loc, $loca, 1000) ) {
    name
  }
}
```
>Run this query in https://play.dgraph.io/

That's the right way to use geo arguments in Dgraph, for who's trying that.

For the Inequality issue you can always use [ ] and set multiple values. Like so:

```
{
  me(func: eq(name@en, ["Ridley Scott", "Steven Spielberg"])) {
    name@en
    director.film @filter(lt(initial_release_date, "1980-01-01"))  {
      initial_release_date
      name@en
    }
  }
}
```
>Run this query in https://play.dgraph.io/

However I do not understand why eq does not work with GraphQL Variables in this case.
We could mimic the process used in "near" to "eq".

**Comment by srfrog** [comment]
Unfortunately, the geo array is not supported. The eq var array is a bug.
