### ISSUE TITLE
How to query all edges of a node?

### ISSUE THREAD

**Issue by omurbekjk** [dgraph-io/dgraph#2275]
How to query outgoing or incoming or both edges of a node?
Let's say we have `Person` and it has relationships with `Vehicle` and `Friendship`, also person has fields like `name` & `surname`. Querying `_predicate_` returns `name, surname, vehicle, friendship`.
How to return only `vehicle` and `friendship`?

**Comment by janardhan1993** [comment]
_predicate_ returns predicates with scalar values also, unfortunately we don't have a way to get only vehicle and friendship.
