### ISSUE TITLE
Count all node's edges if edge predicates are unknown

### ISSUE THREAD

**Issue by nmolchanova** [dgraph-io/dgraph#2276]
Is it possible to count all edges that node has if edge predicates are unknown?

Example: 
```
f(func: condition) {
  expand(_all_){
     single_object_count: counter as count(uid)
  }
  total_edges: sum(val(counter))
}  
```

**Comment by armaneous** [comment]
+1

In a dynamic use-case, vertices and edges can be unique. A vertex with label of `typeA` and another with label of `typeB` can have a `A_to_B` edge. Similarly, with a `typeC`, I'd like to know if `A_to_C` exists. Or, more importantly, if _any_ `A_to_*` exists where `*` is any vertex. I don't think this is currently possible.

**Comment by pawanrawal** [comment]
Seems like assigning variable to `count` is not possible. For e.g. this works.

```
{
  f(func: allofterms(name@en, "Steven Spielberg")) {
    expand(_all_){
     object_count: count(uid)
    }
  }  
}
```

Though since variable can't be assigned to `count` right now, the sum doesn't work on it. If you knew the edges then you could do something like

```
{
  f(func: allofterms(name@en, "Steven Spielberg")) {
    a as count(director.film)
    b as count(producer.film)
    s: math(a + b)
  }  
}
```

**Comment by pawanrawal** [comment]
@armaneous - As shown above, you could use something like the first query to see if any `A_to_*` edges exist (count > 0) from A.

**Comment by armaneous** [comment]
@pawanrawal This assumes you know what values `*` can be, but what if you don't? Using that same example you provided, I'd like to know `*.film` since I don't know what `*` _could_ be.

**Comment by pawanrawal** [comment]
That is not possible right now and is equivalent to querying predicates using a regex. I would suggest creating a separate issue for that. It seems like an advanced feature, we can do it if other people find it useful.

**Comment by manishrjain** [comment]
This should do it:

```
{
  uids(func: has(director.film), first: 1) {
    uid
    expand(_all_) { u as uid }
  }

  result(func: uid(u)) {
    count(uid)
  }
}
```

https://docs.dgraph.io/master/tips#count-number-of-connecting-nodes
