### ISSUE TITLE
Strict Mode - Only allow creation of predicates set in schema

### ISSUE THREAD

**Issue by vespertilian** [dgraph-io/dgraph#2277]
From this forum thread: [Dgraph forum](https://discuss.dgraph.io/t/strict-mode-only-allow-creation-of-predicates-set-in-schema/2383/2)

Feature idea:  Strict mode for DGraph that would only allow the creation of predicates that have already been added via SetSchema.

Reason: Strict mode is a useful feature to take advantage of the type safety the schema can provide, preventing accidentally adding predicates with typos and improving the developer experience.

**Comment by fletcherist** [comment]
Hello guys! Just interesting... are there any practises how to avoid predicates not defined in schema? Strict mode could handle this cases very easily, but if it's not implemented yet, how do you solve this issue?

**Comment by srfrog** [comment]
No, Dgraph is designed to take the data as the user sends it. And only applying type values when a schema exists. The default type is string so anything without type is assumed as string. We tested a type-hinting feature that is almost the inverse of strict types but it was not well received - https://discuss.dgraph.io/t/testing-mutation-type-changes/3352

I personally think strict schema mode would be great as it will simplify a lot of client-side logic, not to mention help with performance and memory use. So if strict mode is something the community wants to add to Dgraph we welcome any patches or design ideas to make it happen.

**Comment by manishrjain** [comment]
This should be a simple change at our end. If a user has set strict schema checking, with a flag, we just don't accept a mutation unless the predicate already has a schema.
