### ISSUE TITLE
: parsing time "Thu Mar 29 2018 10:15:19 GMT+0530 (IST)" as "2006": cannot parse "Thu Mar 29 2018 10:15:19 GMT+0530 (IST)" as "2006"

### ISSUE THREAD

**Issue by SumanSingh4** [dgraph-io/dgraph#2280]
I have imported data from other database, in which
last_access value is Thu Mar 29 2018 10:15:19 GMT+0530 (IST).

In dgraph, I have declared last_access: datetime

On fetching data I am getting error
`: parsing time "Thu Mar 29 2018 10:15:19 GMT+0530 (IST)" as "2006": cannot parse "Thu Mar 29 2018 10:15:19 GMT+0530 (IST)" as "2006"`.

Any suggestion where I am going wrong.

Thanks.

**Comment by manishrjain** [comment]
`dateTime` has to be in RFC3339 format.

https://docs.dgraph.io/query-language/#schema-types
