### ISSUE TITLE
Integrate Jepsen tests in Teamcity.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#2282]
Initially we can just use Docker to run these tests as it's simpler to setup.

**Comment by danielmai** [comment]
Jepsen tests are now running in TeamCity using https://github.com/dgraph-io/dgraph/blob/5794bd6e6c0a4ef349a3ed4ec5935fa3782d8142/contrib/jepsen/main.go, which spins up a Jepsen cluster with Docker Compose and then runs the tests. The script can also be used to run Jepsen tests locally.
