### ISSUE TITLE
Feature request: Add local accessible shutdown REST endpoint to zero nodes

### ISSUE THREAD

**Issue by Pixelfahnder** [dgraph-io/dgraph#2285]
On Windows it is not possible to use Signals like SIGINT to stop processes. Also the golang documentation features this in different documents regarding Signal handling.

A big benefit for starting up the zero instance as a background service would be to add a /admin/shutdown endpoint that is locally accessible like the one for the server nodes.

- What version of Dgraph are you using?
1.0.4 - Windows

**Comment by srfrog** [comment]
@Pixelfahnder i created a shutdown endpoint, but then the team realized this could become a security issue. In production environments it's simpler to access the VM or container and kill the process via signals. On the other side, I improved the shutdown process by looking at this issue. So thank you for reporting it.

**Comment by Pixelfahnder** [comment]
@srfrog After a long time I finally realized the work on this. Thank you very much. Following along the other discussions in #2928 as far as I understood, all "/shutdown" mechanisms are removed from all components, is this correct? So what about a proper SIGINT handling on Windows then or how would a proper stop be operated?
