### ISSUE TITLE
Loading movie data has many Aborts and seems to never finish (4+ minutes)

### ISSUE THREAD

**Issue by aryzing** [dgraph-io/dgraph#2291]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
```
Dgraph version   : v1.0.4
Commit SHA-1     : aad59072
Commit timestamp : 2018-03-09 17:37:44 +1100
Branch           : HEAD
```

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?
Ubuntu 16.04 LTS, 16GB ram

- Steps to reproduce the issue (command/config used to run Dgraph).
Follow the tutorial "More Data" chapter

- Expected behaviour and actual result.
**Expected**: Load data in about 15 secs (that's what it was before I upgraded to 1.0.4)
**Actual**: After 3+ minutes I end up killing the data loading process, many errors:

```Total Txns done:      301 RDFs per second:    1087 Time Elapsed: 4m36s, Aborts: 15284
Total Txns done:      304 RDFs per second:    1090 Time Elapsed: 4m38s, Aborts: 15411
Total Txns done:      306 RDFs per second:    1089 Time Elapsed: 4m40s, Aborts: 15523
Total Txns done:      308 RDFs per second:    1089 Time Elapsed: 4m42s, Aborts: 15643
Total Txns done:      309 RDFs per second:    1085 Time Elapsed: 4m44s, Aborts: 15700
Total Txns done:      309 RDFs per second:    1077 Time Elapsed: 4m46s, Aborts: 15822
```

and

```
2018/03/31 14:21:58 oracle.go:85: purging below ts:20248, len(o.commits):12, len(o.aborts):876, len(o.rowCommit):14621
2018/03/31 14:21:58 raft.go:502: Writing snapshot at index: 39566, applied mark: 40251
2018/03/31 14:21:58 wal.go:118: Writing snapshot to WAL, metadata: {ConfState:{Nodes:[1] XXX_unrecognized:[]} Index:39566 Term:2 XXX_unrecognized:[]}, len(data): 513
```

PS. can't remember what version I was on before, but it loded just fine. I'm using **docker**.

**Comment by aryzing** [comment]
I pulled the docker image `dgraph/dgraph:master` and the `XXX_unrecognized` error is gone, but still getting a high number of aborts and the process does not finish loading the data.

**Comment by aryzing** [comment]
I then tried with v1.0.3 and it worked flawlessly:

```
[...]
Total Txns done:       74 RDFs per second:   32083 Time Elapsed: 24s, Aborts: 0
Total Txns done:       79 RDFs per second:   31538 Time Elapsed: 26s, Aborts: 0
Number of mutations run   : 85                                                                      
Number of RDFs processed  : 844056
Time spent                : 27.895492881s
RDFs processed per second : 31261
Total Txns done:       85 RDFs per second:   30145 Time Elapsed: 28s, Aborts: 0
```

**Comment by pawanrawal** [comment]
> I pulled the docker image dgraph/dgraph:master and the XXX_unrecognized error is gone, but still getting a high number of aborts and the process does not finish loading the data.

The reason that you don't get aborts in `v1.0.3` is because `dgraph live` has default value of concurrency set to 1, so there is a single mutation (with 1000 RDF's) going on at any time. In master, the default value of `c` is `100` which should be faster even with aborts.

**Comment by aryzing** [comment]
> In master, the default value of c is 100 which should be faster even with aborts.

What I'm getting is that with `master`, the data appears to never finish loading (and there are many aborts). With `v1.0.3`, there are no aborts and the movie database is correctly loaded in under 30 seconds.

**Comment by aryzing** [comment]
Great, thanks! Leaving the command here for reference

```
docker exec -it dgraph dgraph live -r 1million.rdf.gz --zero localhost:5080 -c 1
```
