### ISSUE TITLE
go get fails due to absence of main.main in systest plugins and used func in tests

### ISSUE THREAD

**Issue by kortschak** [dgraph-io/dgraph#2292]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
c414fd048430ee617855022f12856e27165f9220

- Have you tried reproducing the issue with latest release?
c414fd048430ee617855022f12856e27165f9220 is current master

- What is the hardware spec (RAM, OS)?
16GB linux amd64

- Steps to reproduce the issue (command/config used to run Dgraph).
`go get github.com/dgraph-io/dgraph/...` (as seen [here](https://discuss.dgraph.io/t/go-get-github-com-dgraph-io-dgraph-dgraph-blog/1701)).

- Expected behaviour and actual result.
Clean install expected, got
```
~ $ go get github.com/dgraph-io/dgraph/...
# github.com/dgraph-io/dgraph/systest/customtok/anagram
runtime.main_main·f: relocation target main.main not defined
runtime.main_main·f: undefined: "main.main"
# github.com/dgraph-io/dgraph/systest/customtok/factor
runtime.main_main·f: relocation target main.main not defined
runtime.main_main·f: undefined: "main.main"
# github.com/dgraph-io/dgraph/systest/customtok/rune
runtime.main_main·f: relocation target main.main not defined
runtime.main_main·f: undefined: "main.main"
# github.com/dgraph-io/dgraph/systest/customtok/cidr
runtime.main_main·f: relocation target main.main not defined
runtime.main_main·f: undefined: "main.main"
# github.com/dgraph-io/dgraph/systest
src/github.com/dgraph-io/dgraph/systest/cluster_setup.go:32:8: undefined: freePort
src/github.com/dgraph-io/dgraph/systest/cluster_setup.go:33:8: undefined: freePort
src/github.com/dgraph-io/dgraph/systest/cluster_setup.go:104:20: undefined: freePort
```

Moving `customtok` to `_customtok` and updating `systest/plugin_test.go` to point to the new location fixes this.

The issue with `freePort` not being found is that it is defined in a test file and so while `go get` sees `cluster_setup.go`, it does not see the function definition in `bulk_live_fixture_test.go`.

**Comment by gedw99** [comment]
Add draph to the end of the URL :)

**Comment by kortschak** [comment]
@gedw99 Thanks. The issue is not that I can't get the binary installed, but rather then documentation (as it exists and was referred to in the original issue text) in conjunction with a little bit of source messiness results in a bad user experience.

**Comment by pawanrawal** [comment]
Hey @kortschak, do you want to send a PR with the changes? We can change the name of the file `cluster_setup.go` to `cluster_setup_test.go`.

**Comment by kortschak** [comment]
Sure. Give me a couple of days.
