### ISSUE TITLE
How to run dgraph-ratel outside a docker container

### ISSUE THREAD

**Issue by kortschak** [dgraph-io/dgraph#2293]
I have dgraph running locally but I am unable to use dgraph-ratel since it AFAICS only exists as a docker image. This means that dgraph-ratel cannot see the locally-running dgraph server. Is there a way around this?

**Comment by gpahal** [comment]
If you installed Dgraph from the binary, it should also contain the ratel binary. See: https://docs.dgraph.io/get-started/#from-installed-binary

**Comment by kortschak** [comment]
Wanting to install from source since this allows me to mess around with dgraph.

**Comment by gpahal** [comment]
You can use the ratel binary provided with the Dgraph binary and connect to any Dgraph instance. Ratel is closed source right now, so you cannot build it from source. But you can do that for Dgraph and connect through ratel.

**Comment by MichelDiz** [comment]
Just run a Docker container only for Ratel. You have to open the ports also and set the local domain or just use the Docker IP (if it's not in "localhost") with the http port. Obviously, if you do not want to install the binaries manually.

**Comment by pawanrawal** [comment]
Since Ratel is closed source, you cannot install it from source for now.

**Comment by kortschak** [comment]
My original reason for wanting to install from source is my intrinsic antibodies to curl-to-bash installation; adding a comment that for some parts can only be installed from the github releases would make things better (not everyone want to have everything done for them - but it is nice to be told where things can be pulled from).

**Comment by pawanrawal** [comment]
@gpahal Can you please add a note to the docs for Building from the source at https://docs.dgraph.io/deploy/#install-dgraph?

**Comment by gpahal** [comment]
Added to master.
