### ISSUE TITLE
Count does not match number of entries

### ISSUE THREAD

**Issue by fungl164** [dgraph-io/dgraph#2294]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
Latest

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
16gb OSX High Sierra

- Steps to reproduce the issue (command/config used to run Dgraph).
go to https://tour.dgraph.io/basic/10/ and run this query:
```
{
  michael_number_friends(func: allofterms(name, "Michael")) {
    name
    age
    friend {
      name
    }
    count(friend)
  }
}
```

- Expected behaviour and actual result.
count: 5
friend should be a list of 5 entries.  Only shows two entries.  
Expect count to match list size or the list to match count...

**Comment by fungl164** [comment]
New to this.  Using the following with "name@." works fine...
```
{
  michael_number_friends(func: allofterms(name, "Michael")) {
    name
    age
    friend {
      name@.
    }
    count(friend)
  }
}
```
Can anyone explain the significance of @.?

Thnxs!

**Comment by manishrjain** [comment]
https://docs.dgraph.io/query-language/#language-support
