### ISSUE TITLE
Querying `schema {}` doesn't return the value of the upsert directive

### ISSUE THREAD

**Issue by gpahal** [dgraph-io/dgraph#2298]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
Dgraph v1.0.4

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
16 GB, 4.15.13-1-ARCH

- Steps to reproduce the issue (command/config used to run Dgraph).
Query `schema {}`

- Expected behaviour and actual result.
Expected the JSON response to have `upsert: true` for predicates indexed with the upsert directive. But, the JSON response has no such field.

**Comment by pawanrawal** [comment]
PR: #2300

**Comment by pawanrawal** [comment]
Fixed via f762888ec0467845878c68178c2c5081d0a1ad9a
