### ISSUE TITLE
Querying schema: boolean to indicate list type?

### ISSUE THREAD

**Issue by tamethecomplex** [dgraph-io/dgraph#2299]
Using Dgraph 1.0.4 and corresponding Ratel version, it appears querying schema does not return a boolean to indicate whether a given predicate is a list type.  This is the same behavior I see when using the node client.  Example from Ratel for a [string] predicate type:

Schema type is [string]

![image](https://user-images.githubusercontent.com/17109209/38209112-46a02390-3681-11e8-96d9-00264e279dcb.png)

Query response gives no way to tell if this predicate is type [string] or string.

![image](https://user-images.githubusercontent.com/17109209/38209123-58a16860-3681-11e8-931c-7b2766bcab40.png)

**Comment by pawanrawal** [comment]
I think this isn't in the docs but can be queried like this. It returns `list` key in the response only if it has value `true`, which is similar to the behaviour for `index` and `count` keys.

```
schema(pred: [property.effectiveDate]) {
  predicate
  list
}
```

**Comment by tamethecomplex** [comment]
This works fine as described, thanks!
