### ISSUE TITLE
dgraph/x - tlsCfg.VerifyPeerCertificate undefined

### ISSUE THREAD

**Issue by mbudge** [dgraph-io/dgraph#2308]
I installed this one another instance fine this morning. 

We just tried again on another system and got the following error. 

    go get github.com/dgraph-io/dgraph/x
    # github.com/dgraph-io/dgraph/x
    ../github.com/dgraph-io/dgraph/x/tls_helper.go:215: tlsCfg.VerifyPeerCertificate undefined (type.      *tls.Config has no field or method VerifyPeerCertificate)
    ../github.com/dgraph-io/dgraph/x/tls_helper.go:305: undefined: tls.CertificateRequestInfo

**Comment by pawanrawal** [comment]
What go version is the server using? I tried with the `golang` docker image which has Go 1.9.2 and it worked fine.

**Comment by mbudge** [comment]
Rebuilt out base image and re-installed packages and the issue didn't reoccur. 

please close the ticket.
