### ISSUE TITLE
Documentation: Facet support in JSON

### ISSUE THREAD

**Issue by ekkis** [dgraph-io/dgraph#2314]
the current documentation for facet support: https://docs.dgraph.io/query-language/#facets-edge-attributes, unlike as with nodes, makes no mention of how to address in a JSON context.  could we have that fixed?

**Comment by pawanrawal** [comment]
We do have docs about how to set facets using JSON but they are at https://docs.dgraph.io/mutations/#facets.

**Comment by ekkis** [comment]
oh.  you're right.  my bad.  thank you
