### ISSUE TITLE
Support multiple live load

### ISSUE THREAD

**Issue by pl7y** [dgraph-io/dgraph#2325]
Use case: I'd like to insert some big data into dgraph using sequential live load batches by splitting data in smaller chunks.
Problem: each live load batch has no way of knowing previous batches `uid`s, so it's not possible to reference any existing node to add edges or attributes.
A solution would be manually specifying `uid`s, but as of v1.04 it's not possible to do so. When using statements like 
```rdf
<0x6bc818dc89e78754> <student> <0xc3bcc578868b719d> .
<0x6bc818dc89e78754> <student> <0xb294fb8464357b0a> .
<0x6bc818dc89e78754> <name> "awesome class" .
<0xc3bcc578868b719d> <name> "Alice" .
<0xc3bcc578868b719d> <planet> "Mars" .
<0xc3bcc578868b719d> <friend> <0xb294fb8464357b0a> .
<0xb294fb8464357b0a> <name> "Bob" .
```
you always get
```sh
2018/04/10 12:50:45 batch.go:135: Error while mutating Uid: [7766484892885944148] cannot be greater than lease: [20000]
```

Edit: In issue #2134 is mentioned that `uid` can't be made custom to avoid collisions.

Am I missing something? Is there a way to have such sequential live loads?

**Comment by pl7y** [comment]
`dgraph live --help` gives in particular:
```
  -x, --xidmap string                    Directory to store xid to uid mapping
```
I already read dgraph docs for [External IDs](read https://docs.dgraph.io/master/mutations/#external-ids) but I don't really get how to use those xid->uid mappings, because I couldn't really understand what are `xid`s for and how they can be used.

1. I have triplets like `_:some_id <predicate> literal/node`. At first live load execution, I use this RDF and everything is ok, uid `0x01` is created. At a later live load, say the third, I would like to add an edge to `_:some_id` but I don't know the uid `0x01`. Is this possible using `-x`? If yes, how can I do it?
2. Are these xid-uid mappings cumulated so that, say, the fifth live load sees all the xid/uids mappings of previous four runs?

Thank you very much for your replies!

**Comment by pl7y** [comment]
Skimming through [Loader test](https://github.com/dgraph-io/dgraph/blob/ddd7414f9b3ec7382a4aa521e9ba2d6e5cd81af7/systest/loader_test.go) source code shed some light: one can use `_:some_id` uuids in following live loader commands, e.g.:
```
_:node <name> "Alice" .
_:node <age> "13" .
_:node_2 <name> "Bob" .
```
```
_:node <location> "Wonderland" .
_:node <friend> _:node_2 .
```
```
_:node_3 <name> "Carry" .
_:node <friend> _:node_3 .
_:node_3 <location> "USA" .
```

What I still don't get is: how are `xid`s involved in this? Executing above RDFs creates three nodes, non of which has a `xid` attribute/edge.

**Comment by pawanrawal** [comment]
When live loader, loads an edge like

```
_:some_id <predicate> literal/node .
```

It assigns a uid corresponding to `some_id`. This mapping is persisted. The correct term for `some_id` in the above RDF is a blank literal. So subsequent runs which use the same blank node literal would be assigned the same uid. You just have make sure you pass the `-x` flag every time while running `dgraph live` and it should point to the same directory. The mappings are cumulated yes since they are written to badger (KV store).

If your RDF was
```
<some_id> <predicate> "value" .
```

then `some_id` would be an xid.

No xid edge is created. Live loader just stores a mapping of blank-node-literal/xid => uid in the `x` directory.
