### ISSUE TITLE
k8s - Port 7080 not exposed

### ISSUE THREAD

**Issue by alexmilowski** [dgraph-io/dgraph#2328]
When running on Kubernetes, the servers can't talk unless you add a hostPort to expose port 7080. This is generally a practice that should be avoided. 

The problem is that 7080 is not exposed in the default docker image:

   dgraph/contrib/nightly/Dockerfile

Added another EXPOSE directive fixes this.

I created this for testing and the k8s deployment works without adding the hostPort:

```
FROM dgraph/dgraph:latest

EXPOSE 7080
```

**Comment by pawanrawal** [comment]
This should be easy to do though I want to understand is this something that changed in the latest version of kubernetes? The pods were communicating fine in the previous version without a `hostPort` and exposing `7080` using the config listed at https://docs.dgraph.io/deploy/#using-kubernetes-v1-8-4.

**Comment by danielmai** [comment]
The current Dgraph images work with the following k8s pod configuration that's set in our k8s configs.

```
ports:
- containerPort: 7080
  name: alpha-grpc-int
```

This sets the internal gRPC communication port for the Alphas to 7080.
