### ISSUE TITLE
Regex query with variables using Go client QueryWithVars

### ISSUE THREAD

**Issue by mbudge** [dgraph-io/dgraph#2333]
Is it possible to use variables with regex search in Go?

We could built the query with SprintF but that would be insecure.

`
q := `query Search($searchterm: string) {
			subdomains(func: regexp(name, /^.*$searchterm/)) {
				uid:uid
				name:name
			}
		}`
`

**Comment by pawanrawal** [comment]
You might want to have a look at https://discuss.dgraph.io/t/variables-in-regex-is-this-an-acceptable-use-for-dgraph/2193.

**Comment by mbudge** [comment]
Still can't get this to work when I call QueryWithVars using the Go client.

searchterm := vars["searchterm"]

variableMap := map[string]string{"$searchterm": searchterm}

txn.QueryWithVars(ctx, q, variableMap)

**Comment by alexthomas93** [comment]
Hi @pawanrawal I'm also having trouble with this issue. Any advice you have would be much appreciated.

**Comment by zboralski** [comment]
@mbudge have you tried `subdomains(func: regexp(name, $searchterm))` and set searchterm to `/REGEXP/`.

**Comment by pawanrawal** [comment]
Looks like GraphQL variables aren't supported in arguments for regex function. I am working on a fix.

**Comment by pawanrawal** [comment]
PR: #2353

**Comment by pawanrawal** [comment]
This should be available in the nightly build soon. Here is an example of how to use it.
https://github.com/dgraph-io/dgraph/blob/6ba8f288d12fc0b937e24d921ad73a396d62dc15/systest/mutations_test.go#L1295-L1300

**Comment by ondrowan** [comment]
Does this really work? I've just tried basically the same scenario as in `dgraph/systest/mutations_test.go`, but with JS client and it keeps returning error "Function 'regexp' requires 2 arguments, but got 1 ([/test/]". I'm using version 1.0.9-v.
