### ISSUE TITLE
Feature request: Pick random node

### ISSUE THREAD

**Issue by mehdiym** [dgraph-io/dgraph#2335]
Hello,

It would be very useful in some use cases to be able to pick randomly a node from a set of nodes.

Today I can only do it by returning all the UIDs for the set and then doing a second request with the randomly chosen one.

This feature as been previously asked [here](https://discuss.dgraph.io/t/feature-request-random-pick-node/2141).

Thank you for your great work.

**Comment by manishrjain** [comment]
You can use the `has(predicate)` function to get a random node with a certain predicate. Ratel uses this in data explorer.

**Comment by mehdiym** [comment]
Thank you but I don't want to pick any node. I need a node that matches some restrictions, so I cannot use that at the root query.
Anyway I found a way with 2 queries.

**Comment by manishrjain** [comment]
You can add a filter at root as well.

**Comment by mehdiym** [comment]
I don't understand how to use it.
Suppose I'd like to find words a specific user knows.
If I execute the following query, I'll always get the same word:

```
{
	var(func: eq(name, "John")) {
		words as knows @filter(has(label)) (first: 1) {
			uid
		}
	}
	random(func: uid(words)) {
		label
	}
}
```

**Comment by rr32btg** [comment]
> You can use the `has(predicate)` function to get a random node with a certain predicate. Ratel uses this in data explorer.

Could you provide some examples or documentation links which describe this behaviour, please? I also tried use "has(predicate)" construction in several conditions and I always got same nodes. Also I didn't find any clue in documentation which describes this "has" behaviour or usage.

**Comment by MichelDiz** [comment]
Hello guys, if anyone need a solution for this, check the answer in https://github.com/dgraph-io/dgraph/issues/3226
