### ISSUE TITLE
Question: Endpoint for usage statistics?

### ISSUE THREAD

**Issue by deckarep** [dgraph-io/dgraph#2340]
Is there a documented endpoint that we can query to get Dgraph statistics even if they are simply estimates of things like: index sizes, edge counts, vertex counts, badger on-disk size?

This would be immensely helpful in understanding how certain data-sets are actually represented when they are ingested into Dgraph.

Thanks!

**Comment by deckarep** [comment]
Actually I think I answered my own question:

```sh
# Dgraph zero has these stats
curl http://localhost:6080/debug/vars
```

**Comment by MichelDiz** [comment]
Wow, you see? you can close now dude LOLLL

**Comment by deckarep** [comment]
I haven't closed because there may be additional endpoints that I'm not aware about.

**Comment by MichelDiz** [comment]
Did you tried https://docs.dgraph.io/ ?

**Comment by deckarep** [comment]
Thanks @pawanrawal - that’s exactly what I was looking for!
