### ISSUE TITLE
Ratel: Clear entire local storage

### ISSUE THREAD

**Issue by deckarep** [dgraph-io/dgraph#2342]
Since Ratel is closed source I'm not sure where to file this ticket.

User Story:
As a user of ratel, I'd like a UI button that allows me the ability to clear the entire Local Storage history in a single click.

Details:
- Please provide a button for the Ratel UI that allows you to clear the entire local storage of all previously executed queries.
- I can clear it manually by opening Chrome Developer tools but when the local storage gets significantly large, the UI becomes a bit sluggish, especially if some of the queries are complex.
- I'd like to clear the local storage with one shot.

Thanks!

**Comment by gpahal** [comment]
The local storage mainly stores the query history and there is a `Close All` button at the top right of the editor. Do you require something different?

**Comment by deckarep** [comment]
Ah, didn't realize that is what `Close All` was for.  I'll close this.
