### ISSUE TITLE
prometheus no token found

### ISSUE THREAD

**Issue by yupengfei** [dgraph-io/dgraph#2344]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

1.0.4

- Have you tried reproducing the issue with latest release?

yes

- What is the hardware spec (RAM, OS)?
ubuntu 17.10
15.7 GiB
AMD® Ryzen 7 1700 eight-core processor × 16 
Radeon RX 580 Series (AMD® Polaris10 / drm 3.18.0 / 4.13.0-38-generic, llvm 5.0.0)

- Steps to reproduce the issue (command/config used to run Dgraph).
follow the steps https://docs.dgraph.io/deploy/#monitoring

- Expected behaviour and actual result.
I hope prometheus can read data from metrics_path, but it does not. With errors like

> level=warn ts=2018-04-18T14:39:57.882265764Z caller=scrape.go:697 component="scrape manager" scrape_pool=dgraph target=http://localhost:6080/debug/vars msg="append failed" err="no token found

I think it due to - in 

"dgraph-bulk-loader_badger_writes_pending": 0,
"dgraph-bulk-loader_num_reducers_total": 0,
"dgraph-bulk-loader_reduce_queue_size": 0,

which may not be supported by prometheus 2.1.0

**Comment by rifki192** [comment]
any info regarding this issue ?
I have the same problem too on my side

**Comment by manishrjain** [comment]
If it's just about fixing the dashes to underscores, can you just make a change, test it, and send me a PR?

**Comment by rifki192** [comment]
actually when I try to make a change, I found from the code that the endpoint for prometheus metrics is not on `/debug/vars` but on `/debug/prometheus_metrics`, you can change your prometheus config to use this endpoint instead @yupengfei , I'm already try it and it's works.

maybe we need to change dgraph documentation regarding this prometheus metrics things @manishrjain

**Comment by manishrjain** [comment]
@rifki192 : If you can send me a documentation PR, that'd be great :-).

**Comment by danielmai** [comment]
The text-format metrics that are accepted by Prometheus v2.0 and newer is exposed at `/debug/prometheus_metrics`.
