### ISSUE TITLE
How to use uid(uidvalues) as intersection not union.

### ISSUE THREAD

**Issue by ghost** [dgraph-io/dgraph#2349]
Hi,

As am reading your block regarding use of function uid(uidvalue)

>  With two or more variables, uid(a,b,...) represents the union of all the variables.

But my requirement is get result intersection of uid(a,b,...) not union.

Any idea how I can do this.

Thanks

**Comment by lapwat** [comment]
I think that you should compute the intersection `X = a ∩ b ∩ ...`

 Then you can query the database with `uid(X)`

**Comment by pawanrawal** [comment]
@SumanSingh4 did you get your answer from https://discuss.dgraph.io/t/get-output-of-uid-a-b-as-intersection-not-union/2496/16?

**Comment by MichelDiz** [comment]
As this issue is an old and the discussion under discuss channel is closed. 
I suggest you reopen a new thread there. if still need support for this.

Cheers.
