### ISSUE TITLE
Error while using "After" argument in a query

### ISSUE THREAD

**Issue by Rahul-Sagore** [dgraph-io/dgraph#235]
I was trying to test "after" argument query to get paginated data, but got errors. This is the link for this feature's wiki: ["After" argument](https://wiki.dgraph.io/Queries_and_Mutations#Supported_from_version_0.4.3)

**How to reproduce:**

I created db entries with this: (Change the "Content 1" string for different text)
```bash
curl localhost:8080/query -XPOST -d $'mutation { set { <root> <content> <_new_:c> .
  <_new_:c> <text> "content 1" .
  }
}'
```

Then this was the query I was running to get first 3 entries:

```bash
curl localhost:8080/query -XPOST -d '{ 
    root(_xid_: root) { 
       content (after: 0x0, first: 3) { 
          _uid_ 
          text  
       }  
    }
}' 
```

It returned first 3 entries successfully:

```bash
{"root":{
   "content":[{
        "_uid_":"0xb05b747ccd23c34",
        "text":"content 1"
     },{
         "_uid_":"0x191a956b7d22db92",
         "text":"content 2"
     },{
        "_uid_":"0x1c9c592751305454",
        "text":"content 3"
    }]
  }
}
```

Then I used "\_uid\_" of last element to fetch the next 3 entries with this query:
```bash
curl localhost:8080/query -XPOST -d '{
  root(_xid_: root) { 
     content (after: 0x1c9c592751305454, first: 3) { 
         _uid_ 
         text  
      }  
   } 
}' 
```

But got this error : 
```bash
{
   "code":"ErrorInvalidRequest",
   "message":"strconv.ParseInt: parsing \"0x1c9c592751305454\": value out of range"
}
```

This is the parse error, I don't know if I am doing something wrong, but it seems the dgraph's code is trying to parse "0x1c9c592751305454" with ParseInt, but the uid is not in form of integer and too long, that's why it failed.

**Comment by ashwin95r** [comment]
Hey @Rahul-Sagore, The after expects a integer and doesn't accept hexadecimal format as of now. We'll fix this. Thanks for reporting!

**Comment by manishrjain** [comment]
You can use ParseInt with base zero. It would infer the base from the string. @ashwin95r Can you fix this one quickly? Should be an easy one.

**Comment by Rahul-Sagore** [comment]
Please check same thing with, delete query, was getting the same error.

```
$ curl localhost:8080/query -XPOST -d $'mutation {
  delete {
     <lewis-carrol> <died> "1998" .
  }
}'

```

I'll have uid with hexadecimal format now so will it handle that? Should it be a separate bug?

**Comment by pawanrawal** [comment]
Hey @Rahul-Sagore. So this is how I ran the delete query.
```
curl localhost:8080/query -XPOST -d $'mutation {
  delete {
     <_uid_:0xf11168064b01135b> <born> "1998" .
  }
}'
```
and it works. Can you please try this? I am adding to Wiki how to run and set and delete mutations with uids.

**Comment by Rahul-Sagore** [comment]
Yeah, tested. This is working, thanks.

**Comment by pawanrawal** [comment]
Thanks @Rahul-Sagore . Closing this issue.
