### ISSUE TITLE
Shortest path: filtering nodes by index

### ISSUE THREAD

**Issue by lapwat** [dgraph-io/dgraph#2350]
Hello everyone,

Is it possible to filter a node in 'shortest path' query depending of its postion in the path ? I need to filter the predicate of the first node of the path (node after the first hop).

Something like:
```
{
  path as shortest(from: 0x1234, to: 0xabcd) {
    edge @filter(index(1, eq(name, "Bob")))
  }
  path(func: uid(path)) {
    uid
  }
}
```

I would love to see it implemented.
Thanks a lot,
lapwat

**Comment by campoy** [comment]
The way to do this is by using `first: 1, offset: 1` but unfortunately there's an issue with this feature.
I filed #3663 to track that fix, so we can close this issue.
