### ISSUE TITLE
Between operator for func and filter

### ISSUE THREAD

**Issue by camway** [dgraph-io/dgraph#2351]
So I'm curious if it would be possible to get a `between` operator that may function something like this (for datetimes):

```
entities(func: between(timestamp, "2017-01-01T00:00:00", "2017-12-31T23:59:59")) {
}
```

I think this operator could be used with ints, floats, and datetimes. Maybe someone can make an argument for a datatype I'm not considering here.

The main motivation I have for doing this is that I'm having to do quite a few restrictions on data based on date, and I'm hoping that if we had a between operator in the main function, we would be able to use an index on the between statement. Currently I have to use a `gt` or `lt` followed by the other in order to do a between, but this means that the second operation is not using an index (if my understanding is correct).

**Comment by manishrjain** [comment]
You can do:

`entities(func: gt(timestamp, X)) @filter(lt(timestamp, Y)) { .. }`

Both would use an index in this case.
