### ISSUE TITLE
How to find two entities that are not related

### ISSUE THREAD

**Issue by tangzhenquan** [dgraph-io/dgraph#2354]
example：
There are 5 entities:a,b,c,d,e.
a like b
c like b
c like e
How to find the entities that not like b?

**Comment by pawanrawal** [comment]
I am assuming all entities have a name, if not you could use some other predicate for `has`.
```
{
  # First get all entities
  me(func: has(name)) @casade {
    name
    like @filter(NOT eq(name, "b"))
  }
}
```

**Comment by shanghai-Jerry** [comment]
index consume so many time while putting too many data into dgraph, but function should be used in some predicates which have been indexed,  i am  in trouble now.

**Comment by manishrjain** [comment]
Sorry, I'm not following the concern here, @shanghai-Jerry .

**Comment by tangzhenquan** [comment]
@pawanrawal  Thanks,Will this lead to full tables scan？

**Comment by manishrjain** [comment]
`  allEntities as var(func: has(name)) @filter(NOT eq(name, "b"))`

This would lead to a scan over the keys of predicate name. Key scans are really fast though. This isn't a bug, but questions. So, closing the issue.
