### ISSUE TITLE
Dgraph Go client documentation out of date

### ISSUE THREAD

**Issue by mbudge** [dgraph-io/dgraph#2356]
Just wanted to let you know the documentation for the dgraph go client is out of date, which might catch new users out. 

The imports have changed to: 

"github.com/dgraph-io/dgo"
"github.com/dgraph-io/dgo/protos/api"

https://docs.dgraph.io/query-language

**Comment by pawanrawal** [comment]
Thanks for letting us know. I have fixed this now.
