### ISSUE TITLE
Output server logs to a file instead of stdout

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#2366]
It would be good if the logs were output to a file instead of stdout. They can be stored inside the logs folder and the timestamp of when the server was started can be part of the name of the log file. 

E.g. - `logs/dgraph-server-2018-04-30T02_09_34Z.009094.log`

This would be useful as a lot of times users lose the logs, without which it can be harder to debug issues. An example is issue #2327.

**Comment by manishrjain** [comment]
The glog library does this for now, and also does log rotation.
