### ISSUE TITLE
what is "Invalid index specification" error?

### ISSUE THREAD

**Issue by rebootcode** [dgraph-io/dgraph#2367]
- What version of Dgraph are you using?
1.0.5

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?
8GB Ram, MacOS

I am creating some schema and I am receiving error with message "Invalid Index Specification"

Schema as below:-

```
name: string @index(term) .
username: string @index(exact) @count @upserts .
email: string @index(exact) @count @upserts .
pass: password .
aboutMe: string .
location: string .
reputation: int .
userTitle: uid .
postTitle: uid .
follow: uid @count .
text: string @index(fulltext) .
qType: string @index(exact) .
tagText: string @index(term) .
viewCount: int @index(int) .
score: int .
timestamp: datetime .
post: uid @reverse .
author: uid @reverse .
owner: uid @reverse .
title: uid @reverse .
body: uid @reverse .
tags: uid @reverse .
upVote: uid @reverse .
downVote: uid @reverse .
hasAnswer: uid @reverse @count .
chosenAnswer: uid @reverse .
createdAt: uid .
updatedAt: uid .
birth: uid .
```

I am not sure, what is the error and which above predicate this error is titled for!

**Comment by sboorlagadda** [comment]
@rebootcode I think the typo `@upserts` is causing the error. The directive is *@upsert* (without 's')

Try this
```
name: string @index(term) .
username: string @index(exact) @count @upsert .
email: string @index(exact) @count @upsert .
...
...
...
```
I will make this as a bug to fix the error to display which predicate specification is erroneous.
