### ISSUE TITLE
queries do not return

### ISSUE THREAD

**Issue by rosshpayne** [dgraph-io/dgraph#2369]
* Doc page: [_index.md](https://docs.dgraph.io/)
* Doc version: `release/v1.0.5`

Guys,  the queries in the dgraph documentation do not return - I presume they timeout at some point.

This issue appears to be in the latest  build.  When I rebuilt my app it too failed to return when calling the api

resp, err := dg.NewTxn().QueryWithVars(context.Background(),q,variables)

This was working a week or so ago.  

Please confirm.

**Comment by sboorlagadda** [comment]
Are you still not able to run queries on the website? I can run them.

**Comment by MichelDiz** [comment]
As there was no response and it is an issue open months ago. Sounds like a settled case.

Feel free to reopen.
