### ISSUE TITLE
Input for predicate Location of type scalar is uid

### ISSUE THREAD

**Issue by rebootcode** [dgraph-io/dgraph#2370]
Hi, I am using dgraph client - https://github.com/dgraph-io/dgo

I am getting error as:- **rpc error: code = Unknown desc = Input for predicate Location of type scalar is uid** - Below is Code
```
...
type loc struct {
	Type   string
	Coords []float64
}
type Users struct {
	Name   string
	Location  loc
}
func main() {
    ...
p := Users{
			Name:  "Alice",
			Location: loc{
				Type:   "Point",
				Coords: []float64{1.1, 2},
			},
		}

op := &api.Operation{}
op.Schema = `
			Name: string @index(term) .
			Location: geo .
		`
   ...
}
...
```

And if I change type to `uid` for `location` predicate, all seems to work fine.

How can I use geo type with predicate without getting error of `input for predicate Location for type scalar is uid`

**Comment by sboorlagadda** [comment]
@rebootcode I think marshaled json should have field `coordinates`. So probably try this.
```
type loc struct {
    Type     string   `json:"type"`
    Coords []float64 `json:"coordinates"`
}
```
Refer this [complete](https://docs.dgraph.io/clients/#complete-example) example.

**Comment by rebootcode** [comment]
This didn't work and examples work without full example code, but not with my code. I am surprised, why it doesn't work, when I am using it my code exactly how it is shown.

I am using 1.0.5, I am closing it for now, as it looks like bug to me, If other people finds similar bug, they can re-open the issue.

Thanks, I am investigating on my own to see, If i missed anything.

Thanks
