### ISSUE TITLE
has(predicate) query at root level sometimes leaks nodes that do _not_ have the predicate 

### ISSUE THREAD

**Issue by billylindeman** [dgraph-io/dgraph#2371]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
```
Dgraph version   : v1.0.5
Commit SHA-1     : 82787414
Commit timestamp : 2018-04-20 15:50:53 +1000
Branch           : HEAD

For Dgraph official documentation, visit https://docs.dgraph.io.
For discussions about Dgraph     , visit https://discuss.dgraph.io.
To say hi to the community       , visit https://dgraph.slack.com.
```
Licensed under Apache 2.0 + Commons Clause. Copyright 2015-2018 Dgraph Labs, Inc.```
- Have you tried reproducing the issue with latest release?
yes

- Steps to reproduce the issue (command/config used to run Dgraph).
Intermittently a has() query at root level will return nodes that do not have the predicate in it.

In the following screenshot, I have a query that should return all nodes with `has(type.company)`, but sometimes will return nodes of a different type.

This seems to happen after a long running query of that other type.  I'd suspect it has something to do with the caching layer?

![screen shot 2018-05-03 at 6 46 42 pm](https://user-images.githubusercontent.com/227376/39610106-e97f4fa2-4f02-11e8-9d2a-f63b1def9ec7.png)

**Comment by sboorlagadda** [comment]
is it not consistent and does happen _sometimes_?

**Comment by billylindeman** [comment]
Unfortunately it is not consistently reproducible . It seems that shutting down / starting the `dgraph server` node fixes it when it starts happening.

**Comment by billylindeman** [comment]
Pinging on this @sboorlagadda @manishrjain 
Any insight into what is happening?

**Comment by manishrjain** [comment]
Sorry, haven't had a chance to look at this yet. If you have steps that we could take to reproduce this problem, they'd help.

**Comment by billylindeman** [comment]
@manishrjain this happens on our dataset only with `has(predicate)` queries, and only after dgraph has been running for a long time.  If I reboot the `dgraph server` it does not happen.  I can't really provide reproduction steps more than that, but that should give some indication of where to look?  It must be a caching issue of some sort?

**Comment by manishrjain** [comment]
This should be fixed by https://github.com/dgraph-io/dgraph/pull/2585.
