### ISSUE TITLE
Go client - problem with false boolean predicate 

### ISSUE THREAD

**Issue by mbudge** [dgraph-io/dgraph#2380]
When we create a new domain with Active bool value set to false, the active predicate is not set in dgraph. The predicate is only set when Active is set to true.

```
d := &Domain{
		Name:      name,
		Active:   false,
	}
```

No results are returned when we do the following query:

```
{
  isactive(func: eq(active, false)) {
    name
    active
  }
}
```

But they are returned when we query for true, even though we definitely set some domains active state to false:

```
{
  isactive(func: eq(active, true)) {
    name
    active
  }
}
```
There is no mention of false not matching any results, or boolean false not being set in dgraph in the documentation.

https://docs.dgraph.io/master/query-language/#inequality

Is this a bug?

**Comment by pawanrawal** [comment]
I have a hunch that you probably have `omitempty` set to true for `Active` because of which it is not marshalled and sent to the server. This can be confirmed if you share your struct definition.

**Comment by mbudge** [comment]
I made the active predicate in dgraph-ratel by selecting bool and enabling indexing.

Does ratel enable omitempty by default?

**Comment by pawanrawal** [comment]
I was talking about the struct in Go. Do you have `omitempty` as part of your JSON tag for Active field. Read about `omitempty ` at https://golang.org/pkg/encoding/json/

**Comment by mbudge** [comment]
Yes. Sorry.

Thanks for clearing that up.
