### ISSUE TITLE
When updating a node, the node's uid isn't returned to signal successful update

### ISSUE THREAD

**Issue by nikkon226** [dgraph-io/dgraph#2386]
When creating a node, the new uid is returned to signal a successful creation, but when updating, there is no indication that things have been successful by returning the changed uid. I'm not sure how the expected result should look, but it would be in line with node creation to have the key and value of the `uids` object to be the existing uid.

Fake Uid was used (0x1234), but the point is valid.

- What version of Dgraph are you using?
v1.0.5-dev
Commit: e6c3e769

- Have you tried reproducing the issue with latest release?
Most current

- What is the hardware spec (RAM, OS)?
Docker

- Steps to reproduce the issue (command/config used to run Dgraph).
Taken from the tour (also tested from the tour and received same output).
```
Schema:
name: string @index(term) @lang .
```
```
{
    set {
        _:michael <name> "Michael" .
    }
}
```
```
{
    set {
        <0x1234> <name> "Other name" .
    }
}
```

- Expected behaviour and actual result.
Expected result:
```
{
  "data": {
    "code": "Success",
    "message": "Done",
    "uids": {
        "0x1234": "0x1234"
    }
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 9130,
      "processing_ns": 11763538
    },
    "txn": {
      "start_ts": 170022,
      "commit_ts": 170023,
      "lin_read": {
        "ids": {
          "1": 5792
        }
      }
    }
  }
}
```
Actual result:
```
{
  "data": {
    "code": "Success",
    "message": "Done",
    "uids": {}
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 9130,
      "processing_ns": 11763538
    },
    "txn": {
      "start_ts": 170022,
      "commit_ts": 170023,
      "lin_read": {
        "ids": {
          "1": 5792
        }
      }
    }
  }
}
```

**Comment by manishrjain** [comment]
Given that the user passes in the UIDs, why do you need them to be reflected in the assigned map? Assigned map is for newly assigned UIDs.

The change went through because the returned code was success.

**Comment by nikkon226** [comment]
Getting a response on what nodes were modified would be useful on the user's end. Dgraph already issues a response indicating all successful creations (by providing a mapping between identifier and new uid), but does not provide any mechanism for more detail in updates or deletes. The way that you have it seems like a purposeful omission of information rather than a bug, so I suppose that asking to be able to return uids (at least) on successful update and/or deletion for use by the user would be helpful.
I suggested the key/value as the existing `uid` because that would already fall in line with the existing response data.

I can submit a separate feature request asking for more data to be returned on create/update/delete actions.

**Comment by ohenley** [comment]
I know this is close but ...

> Given that the user passes in the UIDs, why do you need them to be reflected in the assigned map? 

1. For consistency/simplicity of expected from calling. Assigned is the explicit result of Mutate(...).  Empty content eg. assigned.Uids["blank-0"] is contrived and misleading. As a client, any form of 'confirmation' is great. Look at it the way you want, it is symmetric and thorough to receive the uid/uids of the node I 'mutated'. 

2. Assigned: 'designate or set (something) aside for a specific purpose.' I effectively 'designate' a node. From our 'discord' about the meaning of 'assigned', IMO your naming is improper. What about newlyAssigned.Uids to properly communicate your logic?
> Assigned map is for **newly assigned** UIDs.
Ah! kk

3. Maybe its more code forks for both you and me. My code path would ideally just return the content of assigned.Uids["blank-0"] in all cases. Simple and done.
