### ISSUE TITLE
make bulk loader resumable from errors

### ISSUE THREAD

**Issue by xinstein** [dgraph-io/dgraph#2387]
I tried to bulk load several times, each time stopped by some special character present in some string contained in my big big rdf file.
I could fix them one by one, but it doesn't make sense that I have to start over each time and re-import everything. This is too long a debug cycle.
I think a solution to this problem is stdout the problematic line, and block until the user chooses what to do with that line (skip the line/cancel the import/edit the line).

Excellent software, excellent performance, best I've ever used, just needs a little decoration.

**Comment by manishrjain** [comment]
I think we now have this flag in Bulk loader:

```
      --ignore_errors              ignore line parsing errors in rdf files
```
