### ISSUE TITLE
When to close client connection?

### ISSUE THREAD

**Issue by ondrowan** [dgraph-io/dgraph#2388]
I know questions should be posted to forums, but I stumbled on [something similar](https://discuss.dgraph.io/t/do-i-have-to-close-dgraphclientstub-after-every-tx/2353) with no answers. I couldn't find anything about this in official documentation, so maybe it could be also improved.

When should I close the connection to Dgraph when working on a web application? After each request or after application is exited? Javascript client mentions that I should cleanup resources, but it doesn't mention when.

**Comment by manishrjain** [comment]
You close a connection when you're done with your client, i.e. application exits.
