### ISSUE TITLE
Dgraph stops accepting new live loads after some amount loaded.

### ISSUE THREAD

**Issue by xinstein** [dgraph-io/dgraph#2389]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
1.0.5

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
3 machines:
        * 128G, 24Cores, Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz, CentOS release 6.3 (Final)
                       runs 1 server with lru_mb set to 8192.
        * 128G, 32Cores, Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, CentOS Linux release 7.3.1611 (Core). 
                       runs 1 zero and 1 server with lru_mb set to 32768
        * 128G, 32Cores, Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, CentOS Linux release 7.0.1406 (Core)
                       runs 1 server with lru_mb set to 16384

- Steps to reproduce the issue (command/config used to run Dgraph).
bulk load 80M rdfs
then live load 2.5M rdfs

- Expected behaviour and actual result.
expected the live load to finish normally. but It gets stuck somewhere: stdout like below

> 
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m16s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m18s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m20s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m22s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m24s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m26s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m28s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m30s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m32s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m34s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m36s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m38s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m40s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m42s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m44s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m46s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m48s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m50s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m52s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m54s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m56s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h44m58s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h45m0s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h45m2s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h45m4s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h45m6s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h45m8s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h45m10s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h45m12s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h45m14s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h45m16s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h45m18s, Aborts: 8422426
> Total Txns done:      773 RDFs per second:      15 Time Elapsed: 14h45m20s, Aborts: 8422426
> 

aborts increases very very slowly, and total txns done increases like once per day.....

Below is the zero:6080/state

> {
>     "counter": "247432",
>     "groups": {
>         "1": {
>             "members": {
>                 "1": {
>                     "addr": "tj-hadoop-dl35.kscn:7080",
>                     "groupId": 1,
>                     "id": "1",
>                     "lastUpdate": "1526369887",
>                     "leader": true
>                 }
>             },
>             "tablets": {
>                 "connect.loc": {
>                     "groupId": 1,
>                     "predicate": "connect.loc",
>                     "space": "67524144808"
>                 }
>             }
>         },
>         "2": {
>             "members": {
>                 "3": {
>                     "addr": "c3-miui-fi-admin01.bj:7081",
>                     "groupId": 2,
>                     "id": "3",
>                     "lastUpdate": "1526370068",
>                     "leader": true
>                 }
>             },
>             "tablets": {
>                 "_share_hash_": {
>                     "force": true,
>                     "groupId": 2,
>                     "predicate": "_share_hash_",
>                     "space": "70"
>                 },
>                 "connect.counts": {
>                     "force": true,
>                     "groupId": 2,
>                     "predicate": "connect.counts",
>                     "space": "1339643059"
>                 },
>                 "connect.last_n_time": {
>                     "force": true,
>                     "groupId": 2,
>                     "predicate": "connect.last_n_time",
>                     "space": "3393825683"
>                 },
>                 "dev.connect": {
>                     "force": true,
>                     "groupId": 2,
>                     "predicate": "dev.connect",
>                     "space": "1121946356"
>                 },
>                 "dev.login": {
>                     "groupId": 2,
>                     "predicate": "dev.login",
>                     "space": "21031254"
>                 },
>                 "dummy": {
>                     "force": true,
>                     "groupId": 2,
>                     "predicate": "dummy",
>                     "space": "17"
>                 },
>                 "login.firsttime": {
>                     "groupId": 2,
>                     "predicate": "login.firsttime",
>                     "space": "18868810"
>                 },
>                 "login.lasttime": {
>                     "groupId": 2,
>                     "predicate": "login.lasttime",
>                     "space": "18728523"
>                 },
>                 "miid": {
>                     "groupId": 2,
>                     "predicate": "miid",
>                     "space": "15059711"
>                 },
>                 "miid.login": {
>                     "groupId": 2,
>                     "predicate": "miid.login",
>                     "space": "21590726"
>                 },
>                 "wifi.bsip": {
>                     "force": true,
>                     "groupId": 2,
>                     "predicate": "wifi.bsip",
>                     "space": "205634389"
>                 },
>                 "wifi.ssids": {
>                     "force": true,
>                     "groupId": 2,
>                     "predicate": "wifi.ssids",
>                     "space": "2442257"
>                 }
>             }
>         },
>         "3": {
>             "members": {
>                 "2": {
>                     "addr": "tj-hadoop-dl36.kscn:7080",
>                     "groupId": 3,
>                     "id": "2",
>                     "lastUpdate": "1526370133",
>                     "leader": true
>                 }
>             },
>             "tablets": {
>                 "_predicate_": {
>                     "force": true,
>                     "groupId": 3,
>                     "predicate": "_predicate_",
>                     "space": "3242912972"
>                 },
>                 "connect.last_n_ip": {
>                     "force": true,
>                     "groupId": 3,
>                     "predicate": "connect.last_n_ip",
>                     "space": "1484962435"
>                 },
>                 "dev.imei": {
>                     "force": true,
>                     "groupId": 3,
>                     "predicate": "dev.imei",
>                     "space": "463363279"
>                 },
>                 "wifi.connect": {
>                     "force": true,
>                     "groupId": 3,
>                     "predicate": "wifi.connect",
>                     "space": "1125055670"
>                 }
>             }
>         }
>     },
>     "maxLeaseId": "24930000",
>     "maxRaftId": "1",
>     "maxTxnTs": "270000",
>     "zeros": {
>         "1": {
>             "addr": "tj-hadoop-dl35.kscn:5080",
>             "id": "1",
>             "leader": true
>         }
>     }
> }

And attachment is the debug/vars of zero and servers

**Comment by xinstein** [comment]
[debugvarsserver0.txt](https://github.com/dgraph-io/dgraph/files/2007259/debugvarsserver0.txt)
[debugvarsserver1.txt](https://github.com/dgraph-io/dgraph/files/2007260/debugvarsserver1.txt)
[debugvarsserver2.txt](https://github.com/dgraph-io/dgraph/files/2007261/debugvarsserver2.txt)
[debugvarszero.txt](https://github.com/dgraph-io/dgraph/files/2007262/debugvarszero.txt)

**Comment by xinstein** [comment]
Sorry, forgot to mention that after I interrupted the live load, I also stopped and restarted the servers and zero by ctrl-c. the debug vars are obtained afterwards.
I hope this is helpful information

**Comment by xinstein** [comment]
by the way, the server also stops responding to any queries.

**Comment by xinstein** [comment]
> {
>   "data": {
>     "schema": [
>       {
>         "predicate": "_predicate_",
>         "type": "string",
>         "list": true
>       },
>       {
>         "predicate": "_share_hash_",
>         "type": "string",
>         "index": true,
>         "tokenizer": [
>           "exact"
>         ]
>       },
>       {
>         "predicate": "connect.counts",
>         "type": "int",
>         "index": true,
>         "tokenizer": [
>           "int"
>         ]
>       },
>       {
>         "predicate": "connect.last_n_ip",
>         "type": "int",
>         "list": true
>       },
>       {
>         "predicate": "connect.last_n_time",
>         "type": "datetime",
>         "index": true,
>         "tokenizer": [
>           "hour"
>         ],
>         "list": true
>       },
>       {
>         "predicate": "connect.loc",
>         "type": "geo",
>         "index": true,
>         "tokenizer": [
>           "geo"
>         ]
>       },
>       {
>         "predicate": "dev.connect",
>         "type": "uid",
>         "reverse": true,
>         "count": true
>       },
>       {
>         "predicate": "dev.imei",
>         "type": "string",
>         "index": true,
>         "tokenizer": [
>           "exact"
>         ]
>       },
>       {
>         "predicate": "dev.login",
>         "type": "uid",
>         "reverse": true
>       },
>       {
>         "predicate": "login.firsttime",
>         "type": "datetime"
>       },
>       {
>         "predicate": "login.lasttime",
>         "type": "datetime"
>       },
>       {
>         "predicate": "miid",
>         "type": "int"
>       },
>       {
>         "predicate": "miid.login",
>         "type": "uid",
>         "reverse": true
>       },
>       {
>         "predicate": "wifi.bsip",
>         "type": "int"
>       },
>       {
>         "predicate": "wifi.connect",
>         "type": "uid",
>         "reverse": true,
>         "count": true
>       },
>       {
>         "predicate": "wifi.ssids",
>         "type": "string",
>         "list": true
>       }
>     ]
>   },
>   "extensions": {
>     "server_latency": {
>       "parsing_ns": 440,
>       "processing_ns": 433,
>       "encoding_ns": 3721569
>     },
>     "txn": {
>       "start_ts": 261225,
>       "lin_read": {}
>     }
>   }
> }

**Comment by manishrjain** [comment]
Can you try without the count indices, and check if you see the throughput getting better?

**Comment by xinstein** [comment]
I will try your suggestion.
but if this is a performance issue, why is it not taking any system resources? (cpu, disk io, network io, none of the above has a noticeable difference from 0)

**Comment by xinstein** [comment]
I also have another confusion: why does dgraph generate 20G+ edges from my 80M rdf ?
that's 250 edges per rdf! This is surprising to me.
It would help if I could know which schema directive is causing the edge count explosion

**Comment by manishrjain** [comment]
It could be the geo-indexing. That can generate a lot of edges.

This is a performance issue, because some particular posting lists get too big, and become a bottleneck. We need to look more carefully at handling and optimizing those. I'm also considering ways by which the number of aborts can be significantly reduced.

**Comment by xinstein** [comment]
Thank you very much, after turning off the geo indexing, the import speed is 100x faster!
But geo indexing might become one of our major concern in the near future, is this geo-indexing provided by dgraph already nearly state of the art performance, or is there still room for substantial improvement? I heard neo4j-spatial uses the R-Tree method

**Comment by xinstein** [comment]
I think this issue can be closed since after I removed geo indexing things are smooth enough for production
