### ISSUE TITLE
Exported schema is not consistent with the original and live import is failed

### ISSUE THREAD

**Issue by ericpai** [dgraph-io/dgraph#2393]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

dgraph v1.0.5

- Have you tried reproducing the issue with latest release?

Yes, we met and reproduced the issue in a cluster consisting of 3 dgraph-zero and 3 dgraph-server.
The replica is 3.

- What is the hardware spec (RAM, OS)?

OS: CentOS7.2
RAM: 16GB

- Steps to reproduce the issue (command/config used to run Dgraph).

1. The cluster is set to empty at first: `curl -X POST dgraph-server:8080/alter -d '{"drop_all": true}'`
2. Alter schema as the [tour page](https://tour.dgraph.io/intro/3/) said.
3. Mutate data as the [tour page](https://tour.dgraph.io/intro/4/) said.
4. Export the data and schema: `curl dgraph-server:8080/admin/export` and got the following files:
  - dgraph-1-2018-05-17-11-14.schema.gz
  - dgraph-1-2018-05-17-11-14.rdf.gz
5. Clear all the data again: `curl -X POST dgraph-server:8080/alter -d '{"drop_all": true}'`
6. Use `dgraph live` import the data back but got the following infinite outputs.

```
[root@dev1 ~]# dgraph live -r dgraph-1-2018-05-17-11-14.rdf.gz -s dgraph-1-2018-05-17-11-14.schema.gz --zero=dgraph-zero:5080 --dgraph=dgraph-server:9080 -c 1
2018/05/17 11:17:19 run.go:337: Creating temp client directory at /tmp/x312076153

Processing dgraph-1-2018-05-17-11-14.schema.gz
2018/05/17 11:17:19 run.go:354: Processed schema file

Processing dgraph-1-2018-05-17-11-14.rdf.gz
2018/05/17 11:17:19 batch.go:125: Error while mutating Attr: [name] should have @lang directive in schema to mutate edge: [entity:70012 attr:"name" value:"Artyom" lang:"en" ]
2018/05/17 11:17:19 batch.go:125: Error while mutating Attr: [name] should have @lang directive in schema to mutate edge: [entity:70012 attr:"name" value:"Artyom" lang:"en" ]
2018/05/17 11:17:19 batch.go:125: Error while mutating Attr: [name] should have @lang directive in schema to mutate edge: [entity:70012 attr:"name" value:"Artyom" lang:"en" ]
...
```

7. Uncompress the schema file and check the content.

```
[root@dev1 ~]# gunzip dgraph-1-2018-05-17-11-14.schema.gz
[root@dev1 ~]# cat dgraph-1-2018-05-17-11-14.schema
age:int @index(int) .
name:string @index(term) .
friend:uid @count .
owns_pet:uid .
_share_hash_:string @index(exact) .
```

The original one, copy from [tour](https://tour.dgraph.io/intro/3/)

```
name: string @index(term) @lang .
age: int @index(int) .
friend: uid @count .
```

The `@lang` of predicate `name`  is missing, which causing the `dgraph live` error.

- Expected behaviour and actual result.

1. The `dgraph live` should be executed successfully as long as the schema and rdf files are exported successfully.
2. The exported schema should equal the original one.

**Comment by ericpai** [comment]
The above PR can fix the issue :)

**Comment by manishrjain** [comment]
Merged. Thanks for the fix, @ericpai . I'll leave it to you to close the issue.
