### ISSUE TITLE
Go client - Use variable to set predicate name?

### ISSUE THREAD

**Issue by mbudge** [dgraph-io/dgraph#2399]
Hi,

Please could you allow setting the predicate as a map variable value?

It would make the Go client easier to use, as we could reuse a generic "get predicate UID" function throughout our application. 

```
func uidFromAsnNumber(ctx context.Context, txn *dgo.Txn, predicateName, string, asnNumber string) (string, error) {

	variableMap := map[string]string{"$predicate": predicateName, "$asnNumber": asnNumber}

	q := `query Asn($asnNumber: string) {
		asnuid(func: eq($predicate, $asnNumber)) @normalize {
			uid: uid
		}
	}`

	resp, err := txn.QueryWithVars(ctx, q, vars)
	if err != nil {
		return "", err
	}
```

Even better would be a wrapper function in the go client, so we just specify the predicate and the value, and it returns the UID.

Many thanks.

**Comment by mbudge** [comment]
Sorry I did not mean search the database for predicates.

I meant setting the predicate dynamically so we could reuse a function. So instead of having a function to get urls for asn, ip and domain, we just have 1 function and pass the predicate name and search variable.

func reusableGetPredicateUid(predicateName string, predicateValue string) (uid, error) {
.... search dgraph
}

**Comment by MichelDiz** [comment]
Well this still a thing? can be closed or add a label? (help wanted)
