### ISSUE TITLE
Support for geohash

### ISSUE THREAD

**Issue by xinstein** [dgraph-io/dgraph#2403]
The current geo indexing is too resource consuming,
What we need most is just searching based on point coordinates (no polygons),
so maybe geohash is more the thing for us.
Is there already a way in dgraph to realize geohash?

**Comment by xinstein** [comment]
I think prefix search is a better thing to implement, do we have that now?

**Comment by manishrjain** [comment]
We don't do prefix search, but regexps make that obsolete. We do support regexp search.

**Comment by xinstein** [comment]
regexp indexing might consume a lot more than a simple prefix indexing I guess?

**Comment by manishrjain** [comment]
> regexp indexing might consume a lot more than a simple prefix indexing I guess?

Don't think so. We use trigrams for regexp indexing. The cost of prefix and trigram indexing should be about the same.

**Comment by manishrjain** [comment]
Also see: #2897 .
