### ISSUE TITLE
dgraph-ratel wait time not long enough

### ISSUE THREAD

**Issue by xinstein** [dgraph-io/dgraph#2408]
Whenever I run a slightly time-consuming query, the dgraph-ratel fails to render the result due to timeout. 
Other clients could wait for as long as it needs for the result to arrive.
Can you give an option to set wait timeout in dgraph-ratel UI?

**Comment by martinmr** [comment]
Not an issue with dgraph itself so I've moved it to https://github.com/dgraph-io/ratel/issues/54
