### ISSUE TITLE
dgraph-ratel UI stops responding after clicking `expand`

### ISSUE THREAD

**Issue by xinstein** [dgraph-io/dgraph#2411]
in almost all use cases, the link `Expand 500 nodes` crashes the webpage.
My env:
system: macOS sierra 10.12.6
browser: Chrome 66.0.3359.181

**Comment by MichelDiz** [comment]
Did you tested in others browsers?

**Comment by xinstein** [comment]
No luck with safari.
I'll borrow a windows pc and try again

**Comment by xinstein** [comment]
No luck with windows chrome.

**Comment by MichelDiz** [comment]
![dgraphteste](https://user-images.githubusercontent.com/6570955/40526248-aa86029a-5fbb-11e8-9f21-bae36a562157.png)

Well, as you can see on this print I have 20000 nodes running on Chrome.

**Comment by MichelDiz** [comment]
What you mean "after clicking `expand`"?

**Comment by xinstein** [comment]
`Expand 500 nodes`
![screen shot 2018-05-25 at 16 33 37](https://user-images.githubusercontent.com/10842079/40534748-a66f9fee-6039-11e8-819d-a005a8e0d64e.png)

**Comment by MichelDiz** [comment]
Can you provide some mutations or RFDs for me to simulate here?

**Comment by xinstein** [comment]
Miraculously.....
After a weekend worth of rest for my computer, it finally succeeds in rendering large graphs.
So I'm closing this issue

**Comment by xinstein** [comment]
[result.txt](https://github.com/dgraph-io/dgraph/files/2060615/result.txt)
This is the result json causing the browser crash problem.

I'm reopening this issue.

**Comment by MichelDiz** [comment]
Are you using the same machine? can be this. Some driver problem in rendering. Most of Ratel's work is in Browser rendering.

If you can't provide an dump mutation example. I can't reproduce it. I need to reproduce exacly the way you doing to demonstrate the problem.

**Comment by xinstein** [comment]
I've tried on every machine I can find, 5000 nodes and 12000 edges, have trouble expanding.
The mutations are too big, I thought the webUI rendering only relies on the result json? 
How about faking an http server and return the json I provided for every request? 
In that way you can test the webUI only

**Comment by MichelDiz** [comment]
This question has been moved to Discuss
https://discuss.dgraph.io/t/do-you-have-plans-for-gpu-accelerated-dgraph-ratel-ui/2732/3

My comments on this:

> I was able to reproduce something similar (slightly higher), there was delay (which is expected when it comes to a large scale of data), but did not prevent it from using it. In a machine with 8 Cores, 16GB of RAM and a GTX 1050ti I was able to reproduce nodes and edges even larger, delayed, but waiting to render and process everything there was a return.

Ratel uses ReactJS, so it will be limited to the Browser's limits (v8 engine and rendering capabilities).

For gigantic uses it would be recommended to use native tools (not directly supported by us) such as Gephi, Protégé, VisGraph, WebVOWL, Visual PoolParty and others.

> Ratel is not recommended to treat millions of data visually. Ratel is a surgical tool that should be used to strategize. Visualization or even treatments should be done by specific tools. Or even create a process in Python to process that data or some scientific tool (statistics?).
