### ISSUE TITLE
advice needed concerning enum values.

### ISSUE THREAD

**Issue by xinstein** [dgraph-io/dgraph#2421]
My nodes have a property `user.status` which is an enum (0,1,2,3).
I have thought of the following ways to store it in dgraph:
1. schema { 
            user.status: int @index(int) .
        }
     and store the 0,1,2,3 as an int64, indexing is necessary because I would want to retrieve users according to their status
2. schema{ 
            user.status.0: bool .
            user.status.1: bool .
            user.status.2: bool .
            user.status.3: bool .
        }
     and assign predicate user.status.x only to users with status x.

Which one is more performant and which one is more space efficient in dgraph?

**Comment by manishrjain** [comment]
I'd go with the second. More predicates perform better than just one. Could also take a bit more space.

**Comment by xinstein** [comment]
thanks, I'll choose the second then.

Another question, I have an id that could fit in an int64, but since it's an id so we'd only perform exact match on it, no ordering nor filtering on inequalities would ever be needed, so index(int) seems a bit cumbersome.

So I have two choices: 
1. store it as a string and enable index(exact)
2. store it as an int and enable index(int)

which one is more graceful for an id?

**Comment by manishrjain** [comment]
Both work the same from Dgraph perspective. Though, JSON might support strings better than ints closing uint64.
