### ISSUE TITLE
Can you add support for having Chinese characters for predicate labels? 

### ISSUE THREAD

**Issue by lichteveld** [dgraph-io/dgraph#2423]
For our team in China it's a challenge that Chinese characters are not supported as predicate labels. This means they have to translate everything into English which is not ideal if you're importing data from a database with Chinese columns

**Comment by manishrjain** [comment]
Wao! Even I didn't realize this worked. Can you please add this in our documentation?

**Comment by manishrjain** [comment]
I think we can close this issue after this is documented.

**Comment by melixir** [comment]
That's great news. I'll pass the message to my coworker who was running into this problem. Thanks guys!
