### ISSUE TITLE
Does it make sense to run multiple servers on a single host?

### ISSUE THREAD

**Issue by xinstein** [dgraph-io/dgraph#2425]
I currently run one zero and one server on one host,
I can see that most of the time this server instance doesn't consume much cpu power, I'm wondering if increasing the number of server instances could help make more use of available cpu.

To be specific which one is more performant: a single server instance with 32GB lru ? or two server instances with 16GB lru each, no replicas.

**Comment by manishrjain** [comment]
Single server with more RAM should be better. Every instance would have some constant level of RAM  overhead, which you wouldn't need to pay twice if you just run one instance per server.

If the CPU isn't being consumed that might just mean not enough query activity.
