### ISSUE TITLE
implement union of predicates

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#2430]
we are building SaaS product for thousands of customers each of them having tens of millions of highly connected resources, and resources are shared between customers, but links are custom for each customer. to use benefits of sharding we can just use link names like "linktype_customer1", so links for each customer will be placed in one shard.
but now we faced a problem that each customer can have access not only to its own links but also to links for dependent customer as well. and queries would be like "linktype_customer1 + linktype_customer2" where duplicates should be excluded. it can be customer1+customer2, or customer2+customerN, so precomputation is not possible. such query should still use benefits from sharding since it still uses only 2 link types placed on max 2 shards. but as i can see, dgraph has no possibility to union predicates.

one of my queries is like: (i used union(.., ..) pseudoclause to combine predicates)
```
{
    result(func: eq(id, "<resourceId>")) @filter(has(rel_customer1) or has(rel_customer2)) @normalize {
        union(r2mlink_customer1, r2mlink_customer2) {
            id: id
            title: title_customer1@eng:. or title_customer2@eng:.
            entity_type: entity_type
            resource_count as count(union(~r2mlink_customer1, ~r2mlink_customer2) @filter(has(rel_customer1) or has(rel_customer2)))
            union(m2mlink_customer1, m2mlink_customer2) {
                cnt as count(union(~r2mlink_customer1, ~r2mlink_customer2) @filter(has(rel_customer1) or has(rel_customer2)) (first: 1))
            }
            metadata_count as sum(val(cnt))
            all_relations_count: math(resource_count + metadata_count)
        }
    }
}
```

since it's using a lot of nested computations (and need to union predicates on each nested level), i don't see a way how to implement it using var blocks.

also it would be possible to achieve our needs using vars, but in this case we need to use uid function inside a block, which is not implemented as well:
```
{
    result(func: eq(id, "<resourceId>")) @filter(has(rel_customer1) or has(rel_customer2)) @normalize {
		m_customer1 as r2mlink_customer1
		m_customer2 as r2mlink_customer2
        uid(m_customer1, m_customer2) {
            id: id
            title: title_customer1@eng:. or title_customer2@eng:.
            entity_type: entity_type
			r_customer1 as ~r2mlink_customer1 @filter(has(rel_customer1)
			r_customer2 as ~r2mlink_customer2 @filter(has(rel_customer2)
            resource_count as count(uid(r_customer1, r_customer2))
			mm_customer1 as m2mlink_customer1
			mm_customer2 as m2mlink_customer2
            uid(mm_customer1, mm_customer2) {
				rr_customer1 as ~r2mlink_customer1 @filter(has(rel_customer1) (first: 1)
				rr_customer2 as ~r2mlink_customer2 @filter(has(rel_customer2) (first: 1)
                cnt as count(uid(rr_customer1, rr_customer2) (first: 1))
            }
            metadata_count as sum(val(cnt))
            all_relations_count: math(resource_count + metadata_count)
        }
    }
}
```

so, now we have to use one link for all customers and filter it using facets (`r2mlink @facets(anyofterms(customers, "customer1 customer2"))` and so on). it's easy to use, but is quite bad for horizontal scale. it would be great if you implement union function for predicates - for all other needs graphQL+- is cool!

thanks in advance

**Comment by manishrjain** [comment]
I think your query is hard to understand. You'd really benefit from using multiple blocks to split your query. It's possible you don't really need the `union` function, just a modular way to define variables and use them.

**Comment by makitka2007** [comment]
agreed. I redesigned schema to use nodes for every link, so customerId becomes an attribute of the link, and I just use queries like `r2mlink @filter(has(rel_customer1) or has(customer2))` and it works fine

**Comment by manishrjain** [comment]
Glad to know that!
