### ISSUE TITLE
uid variable behaviour unexpected

### ISSUE THREAD

**Issue by xinstein** [dgraph-io/dgraph#2431]
I have 3 kinds of nodes: miid node, dev node and login node. 
2 kinds of edges: miid <miid.login> login; dev <dev.login> login. BOTH have reverse edges.
 
in fact it is in essence simply miid <login> dev. Making login as nodes facilitates indexing on the login properties.

Now starting with a set of miids, I want to find the subset of miids which have a common logged-in device with at least another miid on the starting set, along with the devices that connects them.
{
  startingset as var(func: has(miid.ovd_level.3))
    
  quer(func: uid(startingset))  @ignorereflex @cascade{
    miid.login{
       ~dev.login @filter(lt(count(dev.login), 100) ){
           dev.login{
                ~miid.login @filter(uid(startingset)){
                      destmiids as miid: miid.miid
    		      ovdmd: miid.ovd_max_days
                 }
            }
         }
      }
  }
    
    ctt(func: uid(destmiids)){
      count(uid)
    }
}

The return graph of this query well fits my need, but I can't understand the result of the count(uid) in  ctt, which is much bigger than the number of returned nodes yet a bit smaller than the total number of miids in the starting set.

**Comment by MichelDiz** [comment]
Well, you don't need to use separated var block. You're using predicate as "kinds". Your query can handle it anyway.

Something like:

```yml
{
var(func: has(miid.ovd_level.3)) @ignorereflex @cascade{
miid.login{
~dev.login @filter(lt(count(dev.login), 100) ){
dev.login{
~miid.login @filter(uid(startingset)){
destmiids as miid: miid.miid
ovdmd: miid.ovd_max_days
            }
        }
    }
  }
}
```

But you need to explain your query a little more in detail and why you are using @ignorereflex @cascade guidelines. What purposes are involved and show some example mutations would already work. Open a discussion there in the forum or search me directly in Slack or even in the private forum for more details.

Cheers.
