### ISSUE TITLE
 bulk import error: too many open files

### ISSUE THREAD

**Issue by jsihota** [dgraph-io/dgraph#2432]
How to bulk import when setup dgraph using following kubernetes yaml https://github.com/dgraph-io/dgraph/blob/master/contrib/config/kubernetes/dgraph-multi.yaml

1. Do I need to stop the 3 servers then copy mapped file to each server?

**Comment by jsihota** [comment]
I am also having issue with running import on single machine.  I combined all my files into one file.

Size of rdf file is: 240 GB
Machine Info:
n1-highmem-64 (64 vCPUs, 416 GB memory)
4096 | SSD persistent disk | Google managed | Read/write | Keep disk

Running bulk import like this:
dgraph bulk -r one_big_dgraph_file.rdf.gz -s schema.txt --map_shards=1 --reduce_shards=1 --http localhost:8000
 --zero=localhost:5080

After 4 hours get this error:

runtime.goexit
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_amd64.s:2337
2018/06/12 18:56:50 open tmp/shards/shard_0/000/000977.map: too many open files

github.com/dgraph-io/dgraph/x.Wrap
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:76
github.com/dgraph-io/dgraph/x.Check
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:32
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.readMapOutput
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/shuffle.go:71
runtime.goexit
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_amd64.s:2337
2018/06/12 18:56:50 open tmp/shards/shard_0/000/001555.map: too many open files

github.com/dgraph-io/dgraph/x.Wrap
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:76
github.com/dgraph-io/dgraph/x.Check
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:32
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.readMapOutput
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/shuffle.go:71
runtime.goexit
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_amd64.s:2337
2018/06/12 18:56:50 open tmp/shards/shard_0/000/001682.map: too many open files

github.com/dgraph-io/dgraph/x.Wrap
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:76
github.com/dgraph-io/dgraph/x.Check
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:32
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.readMapOutput
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/shuffle.go:71
runtime.goexit
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_amd64.s:2337
2018/06/12 18:56:50 open tmp/shards/shard_0/000/001942.map: too many open files

github.com/dgraph-io/dgraph/x.Wrap
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:76
github.com/dgraph-io/dgraph/x.Check
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:32
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.readMapOutput
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/shuffle.go:71
runtime.goexit
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_amd64.s:2337
2018/06/12 18:56:50 open tmp/shards/shard_0/000/000624.map: too many open files

github.com/dgraph-io/dgraph/x.Wrap
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:76
github.com/dgraph-io/dgraph/x.Check
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:32
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.readMapOutput
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/shuffle.go:71
runtime.goexit
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_amd64.s:2337
2018/06/12 18:56:50 open tmp/shards/shard_0/000/002162.map: too many open files

github.com/dgraph-io/dgraph/x.Wrap
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:76
github.com/dgraph-io/dgraph/x.Check
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:32
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.readMapOutput
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/shuffle.go:71
runtime.goexit
        /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_amd64.s:2337

**Comment by manishrjain** [comment]
When bulk loader starts, it warns you about the too many open files thing. You should set your `ulimit` to allow more open files.

**Comment by jsihota** [comment]
Failed again, seems that when it gets to a certain size it fails which makes me wonder if there is a thread leak in dgraph

MAP 04h27m13s rdf_count:3.145G rdf_speed:196.1k/sec edge_count:69.54G edge_speed:4.337M/sec
REDUCE 04h27m14s [0.00%] edge_count:0.000 edge_speed:0.000/sec plist_count:0.000 plist_speed:0.000/sec
runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion
>>>MAP 04h28m10s rdf_count:3.145G rdf_speed:195.4k/sec edge_count:69.54G edge_speed:4.322M/sec
REDUCE 04h28m11s [0.00%] edge_count:0.000 edge_speed:0.000/sec plist_count:0.000 plist_speed:0.000/sec
runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion

**Comment by manishrjain** [comment]
The thread limit issue happens when your disk is too slow, that Go spawns a lot of threads to read data. I think you'd need to switch to a faster SSD/HDD.

**Comment by jsihota** [comment]
Using following:
Name | Size (GB) | Type | Encryption | Mode | When deleting instance
-- | -- | -- | -- | -- | --
dgraph-bulk-ext-ssd | 4096 | SSD persistent disk | Google managed | Read/write | Keep disk

**Comment by manishrjain** [comment]
Those will limit the number of IOPS you're doing, which is why your reads maybe getting stuck. I think we could expose a flag by which Badger (underlying KV DB) can be made to act like a traditional LSM tree, so it would reduce the number of IOPS significantly.

Btw, Local SSDs can give you unlimited IOPS.
