### ISSUE TITLE
dgraph live: Error while mutating While proposing to RAFT group, err: context deadline exceeded

### ISSUE THREAD

**Issue by QianchaoLiu** [dgraph-io/dgraph#2434]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

Dgraph version   : v1.0.5
Commit SHA-1     : 82787414
Commit timestamp : 2018-04-20 15:50:53 +1000
Branch           : HEAD

- Have you tried reproducing the issue with latest release?

- What is the hardware spec (RAM, OS)?
Ubuntu 17, RAM 128G

- Steps to reproduce the issue (command/config used to run Dgraph).

`dgraph live -r relationship.rdf --zero localhost:5080`

- Expected behaviour and actual result.

```
Total Txns done:       38 RDFs per second:      43 Time Elapsed: 14m36s, Aborts: 176
2018/06/08 16:23:56 batch.go:125: Error while mutating While proposing to RAFT group, err: context deadline exceeded
2018/06/08 16:23:56 batch.go:125: Error while mutating While proposing to RAFT group, err: context deadline exceeded
Total Txns done:       38 RDFs per second:      43 Time Elapsed: 14m38s, Aborts: 178
2018/06/08 16:23:57 batch.go:125: Error while mutating While proposing to RAFT group, err: context deadline exceeded
Total Txns done:       38 RDFs per second:      43 Time Elapsed: 14m40s, Aborts: 179
Total Txns done:       38 RDFs per second:      43 Time Elapsed: 14m42s, Aborts: 179
```

Error raised as `Error while mutating While proposing to RAFT group, err: context deadline exceeded` during batch mutation using `dgraph live`. 

### My questions
- what does this error mean? 
- what dose the term `aborts` mean?

**Comment by manishrjain** [comment]
Too much load caused a mutation to timeout. Temporary error, live loader would automatically retry.

**Comment by manishrjain** [comment]
Aborts it the number of transaction aborts seen so far.
