### ISSUE TITLE
count nodes on nested path

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#2435]
![blank diagram 17](https://user-images.githubusercontent.com/38106681/41190984-f10ecdaa-6bf0-11e8-8f58-882203ef2f68.png)

in our schema we have "resource" nodes linked to "metadata" via intermediate "r2mlink" nodes (cause links have additional parameters like "label", access settings and so on). the same metadata node can be linked to the same resource twice or more, via different link nodes.

we are trying to go with resource1, get all linked "metadata" nodes, then for each "metadata" node count linked resources. so, query could be like:
```{
    var(func: eq(id, "resource1")) @filter(has(rel_customer1) or has(rel_customer2)) {
        r2mlink @filter(has(rel_customer1) or has(rel_customer2)) {
        	r2mlink {
        		~r2mlink @filter(has(rel_customer1) or has(rel_customer2)) {
			    	counts as count(~r2mlink)
		    	}
		    	resource_count as sum(val(counts))
	    	}
        }
    }
    
    result(func: uid(resource_count), orderdesc: val(resource_count)) {
        id: id
        entity_type: entity_type
        resource_count: val(resource_count)
    }
}
```

the problem is that we get duplicate counts for resources which are linked twice or more ("3" for metadata1 node instead of "2"). and there is no way to count distinct nodes for `~r2mlink @filter(s) ~r2mlink` path (count resources linked to metadata). so, our query fragment should be like:

```    var(func: eq(id, "resource1")) @filter(has(rel_customer1) or has(rel_customer2)) {
        r2mlink @filter(has(rel_customer1) or has(rel_customer2)) {
        	r2mlink {
		    	resource_count as count(~r2mlink @filter(has(rel_customer1) or has(rel_customer2)) ~r2mlink)
	    	}
        }
    }
```

but as for now counting nodes using nested path is just impossible.

also, if implement such count, it would be very useful to have something like `approximate_count(path, 100)` which performs count in approximate manner when results are more than 100

**Comment by campoy** [comment]
Hi there,

I'm trying to understand the request here, and I'm not sure I understand it.
I think this is already doable without adding any features to the language by using variables.

Could you provide a sample of your dataset and a the query that you're running so I can try to help you with it?

Thanks, and sorry for the long delay in addressing this issue!

**Comment by shekarm** [comment]
@makitka2007 Do you have any more information that would be helpful in clarifying the OP?

**Comment by MichelDiz** [comment]
This is a very old question. And no one has been able to fully understand it even though it seems reasonable. Basically the aggregation approach in the docs should cover this.

I will close, I believe that @makitka2007 has certainly overcome this situation since then. As he is a user long ago.

Feel free to elaborate better the issue at https://discuss.dgraph.io/

Cheers.
