### ISSUE TITLE
some query conditiones on Facets

### ISSUE THREAD

**Issue by shanghai-Jerry** [dgraph-io/dgraph#2437]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
 latest v1.0.5

- Have you tried reproducing the issue with latest release?
   no

- What is the hardware spec (RAM, OS)?
    128G

- Steps to reproduce the issue (command/config used to run Dgraph).
  nohup dgraph zero -w zw5 --replicas 1 > info1 &
  nohup dgraph server -p p5 -w w5 --lru_mb 20000 --zero localhost:5080 > info2 &
  nohup dgraph-ratel > info3 &

- Expected behaviour and actual result.
   i added some edge attributes on some predicates like friend_type, friend_type is a enum, values: 0, 1 , 2 , 3, 4 etc  and i want to know the number in each friend_type, is there any operations like groupby can be used in facets? glad to get your reply.

thanks

**Comment by manishrjain** [comment]
Facets don't do groupby. They're very simple "attachments" to the edges. If you need group by, or index, etc. you should model facet data as edges.

Also, please use discuss.dgraph.io for discussions or questions.

**Comment by shanghai-Jerry** [comment]
okay
