### ISSUE TITLE
Do you have plans for gpu-accelerated dgraph-ratel UI?

### ISSUE THREAD

**Issue by xinstein** [dgraph-io/dgraph#2439]
The speed of dgraph-ratel suffers heavily from the increase of graph size,
I've been searching the net for gpu-accelerated graph visualization and learned that there are some works in progress in this direction.
Do you have plans for this?

**Comment by MichelDiz** [comment]
Thank you for your question.

The answer for this question is, no. And Ratel uses React as a technology standard. If there is any lib or other recommendation related to what you are mentioning. Feel free to open a discussion at our forum https://discuss.dgraph.io  with more details.

It would also be interesting if questions, support request and more detailed discussions were made in the "Discuss" - Thus we let the Github resource focused on Features, Bugs and other purposes. For better productivity and project growth.

Cheers.
