### ISSUE TITLE
Question about docker-Compose

### ISSUE THREAD

**Issue by choubiket** [dgraph-io/dgraph#2441]
When using Dgraph 1.0.5 with docker compose in a single server, I strat Zero, Ratel and Server. 
Fact is I can ping container from one another testing with docker exec for example and using the Alias in docker compose (zero, ratel and server),
But I Can't connect to server from Ratel in the Web interface using the same alias. I need to use 127.0.0.1 IP OR the docker generated IP i get with docker inspect (172.18.0.X for example)

Can you tell me why ratel can't use DNS alias docker compose creates while loading ?

PS : I have the same stuff with Prometheus container I add in the docker-compose file : Prometheus will need a Config file with IP and will not support DNS aliases like server:8080, zero:6080, etc..

Thanks
 
- What version of Dgraph are you using?
1.0.5

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
8gb ram, UBUNTU 16.04, Docker 18.03 and docker-compose 1.20.1

- Steps to reproduce the issue (command/config used to run Dgraph).
Just run the docker-compose up with the standard configuration I get on your website (Install / Single Host Setup / Docker-Compose)

- Expected behaviour and actual result.
I would like to be able to use DNS aliases as in every other docker container

**Comment by MichelDiz** [comment]
Choubiket, 
Thank you for your question.

Your question is not related to the development of Dgraph. But I can support you in that. Open a thread in the Dgraph forum https://discuss.dgraph.io
With that same question, but first give a search in the forum as a whole. There are some discussions about Docker over there. Maybe you'll find what you need.

I can support you there as soon as possible. It's interesting to let Github resources focused on bugs, features, and so on.

Cheers.
