### ISSUE TITLE
Provide example of importing data from CSV files / PSQL / MySQL

### ISSUE THREAD

**Issue by unoexperto** [dgraph-io/dgraph#2445]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

latest from master branch via docker image

- Have you tried reproducing the issue with latest release?

It's non-technical issue.

- What is the hardware spec (RAM, OS)?

Ubuntu 16.04 / 16 GB

- Steps to reproduce the issue (command/config used to run Dgraph).

None

- Expected behaviour and actual result.

Guys, could you please provide an example of bulk importing data from CSV files ? I'm shopping for graph DB and choosing between OrientDB/Neo4j and DGraph. Frankly I never heard of RDF N-Triples until I've read your documentation. Extensive googling didn't produce obvious tools to convert existing CSV files or PSQL DB into it. You have blog post about bulk importing StackOverflow DB but their dump is not in RDF format. So it would be great if you elaborate how you did it. It would really save time of prospecting users to evaluate dgraph.

Thank you.

**Comment by manishrjain** [comment]
We do need to have some tool do this. But for now, you could convert CSV to JSON, and load those into Dgraph.

**Comment by unoexperto** [comment]
@manishrjain Thank your for prompt response. Could you please point me to part of documentation that says what tool supports import from json files and how they should be structured ? Most importantly I'd like to see explanation how to defined unique IDs of objects and create relationship between them.

**Comment by MichelDiz** [comment]
@unoexperto Try this
https://discuss.dgraph.io/t/csv-importer-or-csv-converter-to-rdf-how-to/2322/2

and this https://docs.dgraph.io/mutations/#json-mutation-format

**Comment by manishrjain** [comment]
We have introduce JSON support in bulk loader. We're also working on adding JSON support in the live loader. So, we should just make JSON the data format for all migrations from SQL and other DBs. All CSV files can be converted to JSON, so we don't need to support CSV directly.

**Comment by danielmai** [comment]
There's now a section in the How To docs about converting CSV data into JSON that can be loaded to Dgraph: https://docs.dgraph.io/howto/#loading-csv-data
