### ISSUE TITLE
Feature request to add expand(_forward_) and expand(_reverse_) edges

### ISSUE THREAD

**Issue by mbudge** [dgraph-io/dgraph#2446]
Hi, 

Feature request to add expand(_forward_) and expand(_reverse_) so we can get either forward or reverse edges but not all edges with expand(_all_).

We want to write a query to only return forward edges and not reverse edges.

We just want to return the forward edges in the json returned via our dgraph API.

Thanks

**Comment by alexthomas93** [comment]
Hi I would also find this feature useful
