### ISSUE TITLE
Can't delete literal values via API/Mutation/NQuads

### ISSUE THREAD

**Issue by cajus** [dgraph-io/dgraph#2461]
- What version of Dgraph are you using?
v1.0.6

- Steps to reproduce the issue (command/config used to run Dgraph).

I'm using the _dgraph API_ via *dgo* to apply a list of mutations to the graph. The code collects the changes in form of _NQuads_ proto objects and applies it to .Set/.Del of a mutation object.

Now I've some bool predicate like

```
 locked: bool .
 <0x1234> locked true .
```

saved to the graph - which I want to remove now. It's not clear to me how this needs to be done, because

```golang
		nq := api.NQuad{
			Subject:   "0x1234",
			Predicate: "locked",
                        ObjectValue: &api.Value_BoolVal{BoolVal: def.Object.(bool)},
                        //ObjectValue: &api.Value_StrVal{StrVal: "*"},
                        //ObjectValue: &api.Value_StrVal{StrVal: "_STAR_ALL"},
		}
```
runs into

```
rpc error: code = Unknown desc = Please use * with delete operation for non-list type: [locked]
rpc error: code = Unknown desc = Please use * with delete operation for non-list type: [locked]
rpc error: code = Unknown desc = strconv.ParseBool: parsing "_STAR_ALL": invalid syntax
```
in order of the comments above.

What does dgraph expect me to put in there to delete that node?

**Comment by kdsgambhir** [comment]
You can try this if it works. Let me know if this works for you.
```
nq := api.NQuad{
            Subject:   "0x1234",
            Predicate: "locked",
                        ObjectValue: &api.Value_BoolVal{"_STAR_ALL"},
                        },
        }
```

For deleting you can also use this:
```
op = &api.Operation{
    DropAttr: "friend",
}
err = dg.Alter(ctx, op)
if err != nil {
    log.Fatal(err)
}
```
For the complete example, you can refer to: 
```
https://godoc.org/github.com/dgraph-io/dgo#example-Txn-Mutate-DeletePredicate
```

**Comment by kdsgambhir** [comment]
You can try this if it works. Let me know if this works for you.
```
nq: = api.NQuad{
            Subject:   "0x1234",
            Predicate: "locked",
                        ObjectValue: &api.Value_BoolVal{"_STAR_ALL"},
                        },
        }
```

For deleting you can also use this:
```
d := map[string]string{"uid": alice}
pb, err = json.Marshal(d)
if err != nil {
    log.Fatal(err)
}

mu = &api.Mutation{
    CommitNow:  true,
    DeleteJson: pb,
}
```
For the complete example, you can refer to: 
```
https://godoc.org/github.com/dgraph-io/dgo#example-Txn-Mutate-DeleteNode
```

**Comment by cajus** [comment]
Thanks for your answer @kdsgambhir , but using a string as Value_BoolVal will not work - because its bool. I know that there's a *DeleteEdges", but the code is generating a list of *NQuads* and I'd be happy to keep it straight forward.

Looking at the source, I found that this one works:

```golang
nq: = api.NQuad{
            Subject:   "0x1234",
            Predicate: "locked",
            ObjectValue: &api.Value_DefaultVal{"_STAR_ALL"},
        }
```
