### ISSUE TITLE
bring a big convenience by using 128bit integer for uid? how expensive is it?

### ISSUE THREAD

**Issue by xinstein** [dgraph-io/dgraph#2462]
the current uid is a 64bit int, if I have 10B nodes, and I choose to use hash for generating uid from xid, there's a high probability of hash collision ( of the order 10B^2 / 2^64 ~ 5).

But with a 128bit uid, 10B nodes would give a collision probability of 10B^2 / 2^128 ~  2e-19, I suppose this would suffice for all practical needs. Then mapping xid to uid would be a simple hash, obviating the need for serving a map table.

This would be a huge convenience.

If you judge that 128bit is too expensive, you could determine a fair uid size using the hash collision prob estimate formula (n^2 / N), just like I did in the above.

If the 64bit choice has sth to do with the current market cpu architect. Then I guess bad luck for me.

**Comment by manishrjain** [comment]
Dgraph does not support self-generated UIDs. They must be allocated to you by the DB, otherwise, the behavior of your queries and mutations can lead to surprises.

**Comment by xinstein** [comment]
does that mean I have to use blank nodes in bulk import? Does it not support sth like
<0xbae2124> <connects> <0xbbbeba> .
?

**Comment by xinstein** [comment]
Uid: [4294967295] cannot be greater than lease: [1385640000]
I tried to manually specify a new uid, but got the above error

**Comment by MichelDiz** [comment]
The default today is that you use Blank-Nodes.

If you're going to use BulkLoad, put "_:" in front of the uids
e.g: `<_:0x52973040>`

Manual UID insertion support maybe soon supported, perhaps after the Back-up feature. But today there is no standard for this, it is not recommended and so on.

My comments on this:
> Many times you're able to do it just because there is already a (empty?) Node created in the DB with this UID. If you are using "Drop-all" for example  (instead of deleting the folders manually) this is certainly happening. In this case in my theory you would be "allocating UIDs" as you are using Dgraph with "Drop_all". Using "Drop_all" Dgraph continues the process of creating UIDs from where it stopped and the dropped ones are indicated as disposable (however deleted) but Dgraph can use them normally if you do. Perhaps this is the source of confusion of your question about "limit".


Can work, But ignore this, it is not recommended and there is no UID manual insertion support yet. Only use UIDs created by Dgraph.

Cheers.

**Comment by manishrjain** [comment]
We could add a way by which you can just request a whole batch of UIDs by Dgraph (say 1B), and then allocate them however you'd like. But, then Dgraph won't be responsible for UID conflict detection, you'd need to handle all that.
