### ISSUE TITLE
Bulk import fails immediately after reduce starts.

### ISSUE THREAD

**Issue by xinstein** [dgraph-io/dgraph#2464]
after 3 days of waiting, the bulk loader finally failed.

`runtime: program exceeds 10000-thread limit`

this is part of the import log
the whole log is too big to upload
[part_of_bulk_import.log](https://github.com/dgraph-io/dgraph/files/2147906/part_of_bulk_import.log)

**Comment by xinstein** [comment]
I have 500GB worth of rdf-nquads.
Do you have any suggestions for importing data of such size?

**Comment by xinstein** [comment]
Is there a plan for distributed bulk importing?

**Comment by manishrjain** [comment]
Not yet. But you can squeeze a lot from a single machine for the bulk loader. More cores and better disk can speed up your load quite a lot.

**Comment by xinstein** [comment]
Thank you for the suggestion, very good reason to apply for a new piece of hardware.
Do you think using an ssd host alongside other hdd hosts would compromise a lot of ssd's performance? We don't do online mutation, only OLAP.

What's your suggested configuration? Say we have one host with a 4TB ssd and several other hosts with equally big hdd.

**Comment by manishrjain** [comment]
Ideal is 100K IOPS from the disk. If you're not able to achieve that, then I'd suggest switching the bulk loader to open Badger with LSMOnlyOption -- for that you'd need to modify the code a bit. There's no flag for it yet. LSMOnlyOptions would decrease the number of IOPS required, but also lower the write throughput.

**Comment by xinstein** [comment]
I'v got myself an ssd machine, but sadly the bulk import speed has seen no improvement than the previous hdd machine.
What is your recommended way to do benchmarks?

**Comment by manishrjain** [comment]
Will need more details to help. Can you paste the log, and more information about Dgraph version, etc. -- so I know what the problem is?
