### ISSUE TITLE
1.0.6 query error

### ISSUE THREAD

**Issue by xinstein** [dgraph-io/dgraph#2468]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
1.0.6

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
128GB ram, centos 7.3

- Steps to reproduce the issue (command/config used to run Dgraph).
dgraph zero --my=zero_1:5080 --replicas 1 --idx 1
dgraph server --my=server_1:7080 --lru_mb=32768 --zero=zero_1:5080

- Expected behaviour and actual result.

query returns:

: readTs: 7 less than minTs: 77 for key: "\x00\x00\tmiid.miid\x02\x06\x01\x00\x00\x00\x00\x00E\xa1*"

**Comment by MichelDiz** [comment]
Please inform the query used and the mutation built so we can reproduce.

**Comment by manishrjain** [comment]
Just retry with a new transaction. This is an expected error that can happen. It means that the read timestamp is older than what's allowed for the key.
