### ISSUE TITLE
Convert systest pkg to docker based test

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#2472]
Currently, tests in systest pkg try to run Dgraph locally via Go. Instead, they should be using the available docker-compose based Dgraph cluster that's already running for them.

**Comment by campoy** [comment]
Checked with @manishrjain and this should still be done.
Assigning to @martinmr

**Comment by martinmr** [comment]
Summary of the current tests and their status.

- Live loader tests are already using the cluster.
- Bulk loader tests are not but they cannot be changed as the cluster need to be down when doing a bulk load.
- Tests in `loader_test.go` can be migrated, I think.
- The group delete tests are already using a docker cluster.
- Tests in `live_pw_test.go` are already using a docker cluster.
- Tests in `mutations_test.go` are already using a docker cluster.
- Tests in `plugin_test.go` are not using a docker cluster but I am not sure if they can be migrated as they have to build and import a few plugins.
- Tests in `queries_test.go` are already using a docker cluster.

It looks like the vast majority of the tests are already using a docker setup. From the ones that are not, bulk loader and plugin tests have a legitimate reason to not use the default cluster. I think `loader_test.go` is the only file that needs and can be migrated to a docker setup.
