### ISSUE TITLE
Large mutations

### ISSUE THREAD

**Issue by StefanFransen** [dgraph-io/dgraph#2473]
Hi in my use case I got to do multiple mutations per day that can add up to 3 million objects at one time.
At the moment I'm splitting each object into arrays of 1000 objects and committing the array as a mutation.

This works and it is really fast but I there is always room for improvement.
I found the following function in the ```dgraph live``` code that looks like its unused.
https://github.com/dgraph-io/dgraph/blob/master/dgraph/cmd/live/batch.go#L87

Nothing is mentioned about reserving UIDs in the documentation and neither is the function being called anywhere.
So I am wondering if this would actually be useful and if it would improve the speed and/or take some load off dgraph.

Any thoughts would be helpful thanks!

**Comment by manishrjain** [comment]
That does UID assignment, so Dgraph doesn't need to. You could also do local UID assignments by retrieving UIDs in bulk from Zero. Not sure if that'd be faster or not.

**Comment by StefanFransen** [comment]
@manishrjain Is there any documentation available on this?

**Comment by MichelDiz** [comment]
@StefanFransen  in https://docs.dgraph.io/deploy/#more-about-dgraph-zero you'll get:

> /assignIds?num=100 This would allocate num ids and return a JSON map containing startId and endId, both inclusive. This id range can be safely assigned externally to new nodes, during data ingestion.

If this leaves your process faster, perhaps. I think the mutation already with UID can be faster. But I do not know how much. But you will have the job of inserting the UIDs into your mutation. There are no tools for this. I think a program in Python might be a way.

Any questions feel free to ask or re-open this.
