### ISSUE TITLE
Maximum unique id : 110000 : Would not letme define a uid greater than 110000, for exampled if i use uid: 110001 I get an error

### ISSUE THREAD

**Issue by angadd421** [dgraph-io/dgraph#2495]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

- Have you tried reproducing the issue with latest release?

- What is the hardware spec (RAM, OS)?

- Steps to reproduce the issue (command/config used to run Dgraph).
   Using go lang client run the following code

/**********************************************************

Run the code below in go Lang

***********************************************************/

  package main

import (
	"context"
	"encoding/json"
	"fmt"
	"hash/fnv"
	"log"

	"github.com/dgraph-io/dgo"
	"github.com/dgraph-io/dgo/protos/api"
	"google.golang.org/grpc"
)

func main() {

	type DB struct {
		Uid  string `json:"uid,omitempty"`
		Name string `json:"name,omitempty"`
	}
	type Schema struct {
		Uid  string `json:"uid,omitempty"`
		Name string `json:"name,omitempty"`
		Isin []DB   `json:"isin,omitempty"`
	}

	type Table struct {
		Uid    string   `json:"uid,omitempty"`
		Name   string   `json:"name,omitempty"`
		Isin   []DB     `json:"isin,omitempty"`
		Belong []Schema `json:"belong,omitempty"`
	}
	type Type1 struct {
		Uid  string `json:"uid,omitempty"`
		Name string `json:"name,omitempty"`
	}

	// If omitempty is not set, then edges with empty values (0 for int/float, "" for string, false
	// for bool) would be created for values not specified explicitly.

	type Column struct {
		Uid  string  `json:"uid,omitempty"`
		Name string  `json:"name,omitempty"`
		Has  []Type1 `json:"has,omitempty"`
		Isin []Table `json:"isin,omitempty"`
	}

	conn, err := grpc.Dial("127.0.0.1:9080", grpc.WithInsecure())
	if err != nil {
		log.Fatal("While trying to dial gRPC")
	}
	defer conn.Close()

	dc := api.NewDgraphClient(conn)
	dg := dgo.NewDgraphClient(dc)

	op := &api.Operation{}
	op.Schema = `
	name: string @index(exact).
	isin: uid  .
	belong: uid  .
    has: uid .
`

	ctx := context.Background()
	err = dg.Alter(ctx, op)
	if err != nil {
		log.Fatal(err)
	}

	// While setting an object if a struct has a Uid then its properties in the graph are updated
	// else a new node is created.
	// In the example below new nodes for Alice, Bob and Charlie and school are created (since they
	// dont have a Uid).

	d := DB{Name: "DB1", Uid: "110001"}
	p := Column{
		Name: "Column1",
		Has: []Type1{{
			Name: "Address",
		}},
		Isin: []Table{{
			Name:   "table1",
			Isin:   []DB{d},
			Belong: []Schema{{Name: "Schema1", Isin: []DB{d}}},
		}},
	}

	mu := &api.Mutation{
		CommitNow: true,
	}
	pb, err := json.Marshal(p)
	if err != nil {
		log.Fatal(err)
	}

	mu.SetJson = pb
	assigned, err := dg.NewTxn().Mutate(ctx, mu)
	if err != nil {
		log.Fatal(err)
	}

	// Assigned uids for nodes which were created would be returned in the resp.AssignedUids map.
	variables := map[string]string{"$id": assigned.Uids["blank-0"]}
	// deleted raw_bytes from beneath name in the query
	q := `query Me($id: string){
	me(func: uid($id)) {
		name		
		has {
			name
		}		
		
		isin {
			name
			belong{
				name
				isin{
					name
				}
			}
			isin{
				name				
			}
		}
	}
}`

	resp, err := dg.NewTxn().QueryWithVars(ctx, q, variables)
	if err != nil {
		log.Fatal(err)
	}

	type Root struct {
		Me []Column `json:"me"`
	}

	var r Root
	err = json.Unmarshal(resp.Json, &r)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(string(resp.Json))
}

func hash(s string) uint32 {
	h := fnv.New32a()
	h.Write([]byte(s))
	return h.Sum32()
}

- Expected behaviour and actual result.

2018/07/20 09:47:25 rpc error: code = Unknown desc = Uid: [110001] cannot be greater than lease: [110000]
exit status 1

So this error tells me that I cannot pre define a uid greater than 110000 which i am doing in line 76 of code. I am defining the uid as 110001. Can you please inform me why this is happening.

**Comment by MichelDiz** [comment]
`d := DB{Name: "DB1", Uid: "110001"}`
You should not set a UID manually. Only use UIDs created by Dgraph. In this case use a _: Blank-node This way you will create a UID via Dgraph. So you collect this UID and use it the way you need it.

Since it is an obj JSON, it is optional to use Blank-Nodes. (Where would you use them in more complex structure to certify relationships.)

`d := DB{Name: "DB1"}`

If you are creating a structure manually, I would recommend that you create it before starting all work. And then map the UIDs. Or even use indexing and then do a process to query and then write (mutate) with a existing UID.

You will often see that you can use UIDs manually with Dgraph. But this happens because a portion of the UIDs are already allocated (created). So the Dgraph allows its writing because the UIDs already exist. But using existing UIDs is dangerous because can happen that overwrite your data. It is always recommended to let Dgraph handle UID, for safe.
