### ISSUE TITLE
Support for setting predicate with a variable in the Go client?

### ISSUE THREAD

**Issue by mbudge** [dgraph-io/dgraph#2496]
Hi,

I'm writing code to give nodes a type https://docs.dgraph.io/howto/#giving-nodes-a-type

Would it be possible to add support for predicates to be set using variables in the Go client?

This is so we can pass the node type as a string to functions responsible to creating and querying data in our application.  

```
	func GetAddr(ctx context.Context, txn *dgo.Txn, kind string, addr string) (*Addr, error) {
		vars := make(map[string]string)
		vars["$a"] = addr
		vars["$type"] = kind

		q := `query Name($a: string, $type: string) {
			addr(func: has($type)) @filter(eq(addr, $a)) {
				uid
				addr
			}
		}`

	resp, err := txn.QueryWithVars(ctx, q, vars)

	...removed go code to unmarshall resp into addr struct
```

Doing this will reduce the amount of code we need to maintain:

vars["$type"] = kind
has($type)

Thanks

Edit:

Just found a similar ticket https://github.com/dgraph-io/dgraph/issues/2026

**Comment by manishrjain** [comment]
GraphQL variables are not really designed to set properties (predicates in this case). They're designed to set values.

https://graphql.org/learn/queries/#variables
