### ISSUE TITLE
Allow has function to find nodes with a specific edge so we can query the node predicates

### ISSUE THREAD

**Issue by mbudge** [dgraph-io/dgraph#2497]
Hi, 

We are currently adding node types https://docs.dgraph.io/howto/#giving-nodes-a-type

It would be good to allow the has function to include nodes which have a specific edge. 

Currently the has function only works with predicates https://docs.dgraph.io/master/query-language/#has

For example

```
query Email($e: string){
		addr(func: has(email)) @filter(eq(addr, $e)) {
			uid
			addr
		}
	}
```

email is an edge > email: uid @reverse .

It would probably be more useful if this only worked with forward edges, and not nodes with a reverse edge.

Thanks

**Comment by MichelDiz** [comment]
Sorry the HUGE delay, doing a Seek for simple and unanswered issues I found yours and I believe the solution is simple. I've made two examples that you can run against https://play.dgraph.io/

ps. You can perform one at a time.
```
 query tes1($EdgeUID: string = "0x78b3e6") {
   me(func: has(netflix_id), first:1)  @filter(uid_in(~director.film, $EdgeUID ))
     {
      expand(_all_)
   }
 }

query tes2($EdgeUID: string = "0x275ef6") {
  me2(func: has(director.film), first:1)  @filter(uid_in(director.film, $EdgeUID ))
    {
     expand(_all_)
  }
}
```

So the EdgeUID Variable Query would contain the Edge you wanna specify. So you use it in the "uid_in" function as a "has" filter. You will have exactly what you are looking for. But done in another way that already exists in Dgraph.

I will close this Issue, feel free to reopen it if necessary.

Cheers.
