### ISSUE TITLE
Parsing error while loading data using LIVE 

### ISSUE THREAD

**Issue by akbarafzal** [dgraph-io/dgraph#2500]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
1.0.7

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?
32GB, Centos 7.x 

- Steps to reproduce the issue (command/config used to run Dgraph).
dgraph live -r <path-to-rdf-gzipped-file> -s <path-to-schema-file> -d <dgraph-server-address:grpc_port> -z <dgraph-zero-address:grpc_port>

- Expected behaviour and actual result.
Data should load in Dgraph 
2018/07/23 22:36:40 While processing file Error while parsing RDF: Expected = after facetKey.
Found Manager, on line:939,187 <_:uid4acb5> <belongsTo> _:uid4acc6 (Bldg Manager="Bldg Manager") .

--Comments 
ooks like there's a parsing error with the data. That looks like a potential issue, caused by the space in the facet key. Typically, we shouldn't accept those at all, but looks like it did.

**Comment by MichelDiz** [comment]
Hi, can you share that bit part of your RDF? So that I can reproduce here with fidelity.

**Comment by MichelDiz** [comment]
@akbarafzal can you try this script with your RDF? https://github.com/MichelDiz/Dgraph-Bulk-Script

But At first, analyzing your case and trying to replicate here. I was able to get the same error. And it seems to me a malformed RDF. In that case it is visually truncated. The facet must have a comma separating the values. The ''` (Bldg Manager="Bldg Manager") `'' section does not have a correct syntax.

It would be necessary to fix this before starting a Bulk. You can open the RDF file in any program, VIM or VisualCode and change this section manually without problem. If it happens again after the fix, please let me know.

**Comment by manishrjain** [comment]
We need to add a test for this, and ensure that we don't accept spaces in Facet keys.
