### ISSUE TITLE
The contrib/stopwords/scraper.go generates a file licensed under AGPL-3.0

### ISSUE THREAD

**Issue by MarkAtwood** [dgraph-io/dgraph#2502]
AGP-3.0 is forbidden at most companies, which is why this project re-licenced to Apache 2.0

The program with source contrib/stopwords/scraper.go generates code that has an AGPL-3.0 license header, even though that program itself is licensed Apache 2.0.

This is still a problem for companies that forbid AGPL

Can this code generator be changed so code that it generates is Apache 2.0?

**Comment by manishrjain** [comment]
https://github.com/dgraph-io/dgraph/commit/0aa1a2c77d7a99070d9b05fdac6bc7b8bc866c4a Fixed.
