### ISSUE TITLE
Inconsistent query results between dgraph servers in same group 

### ISSUE THREAD

**Issue by coolguru** [dgraph-io/dgraph#2503]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.7

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?
AWS m5.xlarge

- Steps to reproduce the issue (command/config used to run Dgraph).
1) Create a dgraph cluster using [k8s config](https://github.com/dgraph-io/dgraph/blob/master/contrib/config/kubernetes/dgraph-ha.yaml)
2) Load movie data in this dgraph cluster
3) Perform bunch of mutation for some duration (we're seeing after hours of usage to make dgraph servers out of sync state from each other)
4) Perform query, count uid for a particular predicate from either of 2 groups.
5) Different results are generated for the same query in our case count for uids.

- Expected behaviour and actual result.
Expected - Should aways return same uid counts for the same query
Actual - Returns different uid counts for the same query

**Comment by danielmai** [comment]
> 2. Load movie data in this dgraph cluster

Can you clarify which movie data set you're loading into Dgraph?

**Comment by coolguru** [comment]
I was referring to the movie dataset used in dgraph.io tour. Also, just to be clear we saw this issue using our dataset but my guess is we should be able to see this issue using any dataset.

**Comment by danielmai** [comment]
Can you share the mutations and queries you're running with the movie data set where inconsistency happens?

**Comment by danielmai** [comment]
We're unable to replicate inconsistent query results on our side. Putting this on hold for now until we get more information.

**Comment by MichelDiz** [comment]
I wasn't able to replicate this with latest Dgraph Tag.

![captura de tela 2018-08-15 as 11 32 50](https://user-images.githubusercontent.com/6570955/44153878-b829a1cc-a07f-11e8-92a9-1d85ff27436c.png)

![captura de tela 2018-08-15 as 11 33 25](https://user-images.githubusercontent.com/6570955/44153886-bc735b06-a07f-11e8-8145-d66e4c1f4da7.png)


Using this and other queries:

```js
{
  # test(func: has(director.film), first:100){
  #   uid
  #   expand(_all_){expand(_all_)}
  # }
  total (func: has (director.film) ) {
    count(uid)
  }
  total2 (func: has (initial_release_date) ) {
    count(uid)
  }
}
```

```JSON
{
  "data": {
    "total": [
      {
        "count": 3246
      }
    ],
    "total2": [
      {
        "count": 12712
      }
    ]
  }
```

Creating random mutations and repeating the same Bulk (thus creating more nodes). And yet there were no problems.

Closing this issue, feel free to reopen it.

Cheers.
