### ISSUE TITLE
"WARNING: This entry should have been caught." during live loader

### ISSUE THREAD

**Issue by ryanvra** [dgraph-io/dgraph#2509]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.7-rc4

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
 Macbook Pro, i7 2.5 GHz, with 16 GB of RAM

- Steps to reproduce the issue (command/config used to run Dgraph).
 I am running directly on a single host with 1 zero and 1 server.  The server has the lru_mb flag set to 4096.  I ran the live loader with the schema.txt before running the live loader with the same a 1GB file three times in a row in order to test my upsert logic.  The live loader is run with the concurrency flag set to 1.

- Expected behaviour and actual result.
The live loader seems to insert correctly, but there is a warning in the server log.  The warning does not stop the live loader from completing.  The warning itself rarely even happens and is difficult to reproduce.  As you can see, it only occurs for the third run of the 1GB file.  

Note: The server log actually has hundreds more of the "WARNING: This entry should have been caught" lines after the one shown with different key and value data.  They all occur within 20 seconds.  I have removed them since I am not sure what the numbers represent and the data I am working with is sensitive.

I have provided the zero log, server log, schema, and live loader log of the third run.

[zero warning.txt](https://github.com/dgraph-io/dgraph/files/2243217/zero.warning.txt)
[server warning.txt](https://github.com/dgraph-io/dgraph/files/2243255/server.warning.txt)
[schema.txt](https://github.com/dgraph-io/dgraph/files/2243225/schema.txt)
[live_loader.log](https://github.com/dgraph-io/dgraph/files/2243232/live_loader.log)

**Comment by manishrjain** [comment]
I haven't seen this with recent versions of Dgraph. Let us know if this is still an issue.
