### ISSUE TITLE
Add option to override "Cycle detected: Fragment"

### ISSUE THREAD

**Issue by mbudge** [dgraph-io/dgraph#2510]
Hi,

I'm wrote a query which legitimately reuses fragments, but we get the cycle detected error, which means we have to copy and rename the fragment. 

Would it be possible to add an option to override the cycle detection?

```
{
     domain(func: has(domain)) @filter(eq(name, example.co.uk)) {
          ...UpdateFragment
     }
}
```

The query is quite large so I'm not going to copy the whole thing. But doing this to get round the cycle detection means we have more code to maintain, which could be buggy if we miss something.

```
fragment PortFrag {
     uid
     ...UpdateFragmentCopy
}
```

```
fragment AFragment {
	uid
	name
}
```

```
fragment AFragmentCopy {
	uid
	name
}```

**Comment by manishrjain** [comment]
I think we can have a look at this and see if this ask is in line with how GraphQL does fragments. In general, seems like circular fragments are going to be an issue.

**Comment by campoy** [comment]
Hi there,

Could you please give an example of a query that uses cyclic fragments and you would expect to work?
The fragments that you gave on the comment above are not cyclic.

Thanks

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8429). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
