### ISSUE TITLE
dgraph zero shows the wrong dgraph server hosts in k8s deployment 

### ISSUE THREAD

**Issue by animagus32** [dgraph-io/dgraph#2513]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
Dgraph version   : v1.0.6

I'm using k8s to deploy dgraph cluster , the deploy yaml is just like https://github.com/dgraph-io/dgraph/blob/master/contrib/config/kubernetes/dgraph-multi.yaml.  But dgraph zero gets the wrong dgraph server host as show in logs. It duplicates the domain like "dgraph-server-0.dgraph-server.lego.svc.cluster.local.dgraph-server.lego.svc.cluster.local" . I checked the command in container of server and it's right. 
Really don't know how to solve this

**Comment by MichelDiz** [comment]
Not sure what is happening to you, but I just tested (I'm currently loading a LIVELoad) to test this yaml you're mentioning. Every process was smooth, there were no problems. Try to clear all instances from scratch and start over. Or look for assistance in the k8s slack.

https://kubernetes.slack.com/

**Comment by MichelDiz** [comment]
Hey, just one more detail. Change the TAG to image: dgraph / dgraph: v1.0.7-rc4
There are some important modifications to it that solves some probrems in 1.0.6 - but I do not think that would be your case, just to be sure.

And if you can, paste here (or Pastebin) your LOGs help a lot always.
