### ISSUE TITLE
Error: 14 UNAVAILABLE: TCP Read failed

### ISSUE THREAD

**Issue by daft300punk** [dgraph-io/dgraph#2514]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.5

- Have you tried reproducing the issue with latest release?
No

- What is the hardware spec (RAM, OS)?
Digitalocean 2 GB Memory / 50 GB Disk / BLR1 - Ubuntu Docker 17.12.0~ce on 16.04

I'm currently seeing this issue using dgraph-js, but I also saw this with golang client, so reporting here. It happens when the connection has been idle for some time(around 3-5 mins), and you make a new request, the request then takes a long time and finally fails with the above error.  Subsequent requests work properly. I searched for similar errors and it seems this is probably an issue with grpc. I've tried flags like grpc.keepalive_timeout_ms, it didn't work, I might be missing something. Are there any best practices around managing connections? Thanks.

Detailed error log - 
```
{ Error: 14 UNAVAILABLE: TCP Read failed
    at Object.exports.createStatusError (/Users/absi/go/src/github.com/daft300punk/revisely/backend-node/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/Users/absi/go/src/github.com/daft300punk/revisely/backend-node/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/Users/absi/go/src/github.com/daft300punk/revisely/backend-node/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/Users/absi/go/src/github.com/daft300punk/revisely/backend-node/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/Users/absi/go/src/github.com/daft300punk/revisely/backend-node/node_modules/grpc/src/client_interceptors.js:841:24)
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'TCP Read failed' }
```

**Comment by MichelDiz** [comment]
Can you share Dgraph Zero and Server Logs? (pastebin or githubgist https://gist.github.com/ to be organized)

**Comment by daft300punk** [comment]
I don't see anything wrong with the recent logs(taken just after I saw the problem again). I think it's a client issue.

https://pastebin.com/XUQC50b0
https://pastebin.com/hBqCyhqd

**Comment by MichelDiz** [comment]
Yes, your logs are normal.

Can you show how you're setting the "backend-node" with Dgraph-JS? and which docker-compose you are using.

**Comment by MichelDiz** [comment]
Can you comment the lines:
```js
// const grpc = require("grpc");
// grpc.credentials.createInsecure(),
```

And do the same test. It's just a test, I think I've been through this before.

**Comment by daft300punk** [comment]
Nope, just tried it, throws the same error.

**Comment by MichelDiz** [comment]
This error appears in just one try or the whole "backend-node" unusable?

**Comment by daft300punk** [comment]
It appears consistently after some idle time(around 5mins). It also doesn't throw immediately, takes ~ 30s, and no other queries succeed during this time. Also, not using the golang client currently, but I was also seeing it there.

**Comment by MichelDiz** [comment]
are you doing this?
```
.then(() => {
	console.log("\nDONE! at " + Date());
	// Close the client stub.
	dgraphClientStub.close();
})
```

I think you should export a function that can close the stub at the end of the process.

**Comment by daft300punk** [comment]
Yes, closing the connection after each request seems to work. I'll be testing more and see if it comes back. Also, what is the performance implication of opening and closing a new connection on each request? Is this the desired result? I was expecting to open a connection, use it for all my requests, and close it only when the server shuts down.

**Comment by MichelDiz** [comment]
I'm not sure, I did not develop Dgraph-js, but I see in all tests files the use of "dgraphClientStub.close ();" then it should be the default.

**Comment by daft300punk** [comment]
Cool. I'll close this. Thanks for the help.
