### ISSUE TITLE
Filter count based on child objects

### ISSUE THREAD

**Issue by StefanFransen** [dgraph-io/dgraph#2516]
Hi in my use case I got the following object
```
brand {
  product {
    priceSpecification {
      price
    }
  }
}
```
I want to make a product view page with a list of all brands that lists the amount of available products.
This works fine but not when a filter is used because filters can't filter based on a child object currently.
Example

```
{
  brands(func: eq(type, "brand")) {
    count(~product) @filter(ge(price, 100))
  }
}
```
The example above wouldn't work because the price is a object of priceSpecification.
Can any functionality that would make filtering based on child objects possible be added to Dgraph?

Thanks in advance.
Stefan Fransen

**Comment by bandirsen** [comment]
You need to show your complete schema, but I assume priceSpecification are typed, and you must have reversed relationship product-to-priceSpesification ? if so, just introduce variable in your query

```
{
  var(func: eq(type, "priceSpesification")) {
         price @filter(ge(price, 100))
         productUID as ~productToPriceSpecification 
  } 

   brand(func: eq(type, "brand") {
      brandName
      count(~product) @filter(uid(productUID))
   }
}
```

**Comment by StefanFransen** [comment]
Thank you, I managed to get it working! @bandirsen
