### ISSUE TITLE
Graph Algorithms Support/Documentation

### ISSUE THREAD

**Issue by mbande** [dgraph-io/dgraph#2517]
As Neo4j has [implemented](https://neo4j.com/docs/graph-algorithms/current/introduction/) graph algorithms such as PageRank, is there any plan to support these algorithms?
Or provide some documentation(Best Practices) on how to do that on top of dgraph in a distributed manner?

**Comment by MichelDiz** [comment]
Can be implemented but need help for (PRs are welcome). Actually we have one algo already supported
https://docs.dgraph.io/query-language#k-shortest-path-queries

And most of the algorithms could be worked via query. It would certainly be more complex, but for anyone who already understands GraphQL + - (and RDF) and knows the algorithms from their head. You'll do well doing a mix with GraphQL + - and application (yours) level.

We have to keep in mind that GraphQL + - is very different from that used in Neo4j. If we wanna give some support, you have to think about the lang as a whole.

See:
https://github.com/dgraph-io/dgraph/commit/c9253021e7d29751d3ba3bbdd45914c83c7d4a2d
https://github.com/dgraph-io/dgraph/commit/b52041fa9fd9a52f997f2ed0e3c4a254509c2327
https://github.com/dgraph-io/dgraph/commit/d471f6df98f7981fe6f6ca88300c557b3d485ccd

**Comment by potatomasterrace** [comment]
is adding some reflexivity based syntatic sugar on classes (django orm style) in https://github.com/dgraph-io/pydgraph provide a better way to make complex algorithms application level only code ?
python seems more fitting for datascience/algorithms

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8752). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
