### ISSUE TITLE
Badger do sync write instead of async write as mentioned in the docs

### ISSUE THREAD

**Issue by iwanbk** [dgraph-io/dgraph#2518]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

v1.0.6

- Have you tried reproducing the issue with latest release?

yes

- What is the hardware spec (RAM, OS)?

8GB, mac

- Steps to reproduce the issue (command/config used to run Dgraph).

See 

https://github.com/dgraph-io/dgraph/blob/v1.0.6/edgraph/server.go#L103

It says `kvOpt.SyncWrites = true` which means badger do the write synchronously

- Expected behaviour and actual result.

From the docs, badger do async write

https://docs.dgraph.io/v1.0.7/design-concepts/#mutations

```
Note that the writes to BadgerDB are asynchronous, which means they don’t get flushed out to disk immediately, but that wouldn’t lead to data loss on a machine crash. 
```

i can help to send PR to fix the `SyncWrites` option

**Comment by danielmai** [comment]
Seems like `SyncWrites = true` is the intended setting for Dgraph, so that part of the docs needs to be clarified.

**Comment by danielmai** [comment]
Design concepts page is due for an overhaul for [a while now](https://github.com/dgraph-io/dgraph/blame/2afa0962b27e59c8d606ff89258e4ebe49c684c4/wiki/content/design-concepts/index.md#L67). Added a about the mutations design doc for now in https://github.com/dgraph-io/dgraph/commit/2afa0962b27e59c8d606ff89258e4ebe49c684c4
