### ISSUE TITLE
Pass dgraph url to ratel via command line?

### ISSUE THREAD

**Issue by Martaver** [dgraph-io/dgraph#2519]
Is there an option to pass the default dgraph url to ratel via command line? something like `--zero=somewhere:9999`?

**Comment by MichelDiz** [comment]
No, Ratel UI is a project in ReactJS. There is no way to pass commands via the command line to it (as far I know). Not even starting/run with a default address other than what already exists in the build.

if you need we have a version for installation https://discuss.dgraph.io/t/ratel-installer-for-linux-macos-and-windows-preview-version-ratel-update-from-v1-0-6/2884

Cheers
