### ISSUE TITLE
k-shortest-path with uid `0x0`

### ISSUE THREAD

**Issue by fendor** [dgraph-io/dgraph#2520]
# k-shortest-path with uid `0x0`
The version I am using is `v1.0.6`.
This is the latest release on windows, so I could not try it out on `v1.0.7`

I am using the `k-shortest-path` algorithm and allow arbitrary `from` and `to` uids. 

## Expected behaviour and actual result.

I would expect DGraph to return an empty result if no path can be found, as it normally happens when there is no path between two nodes.
However, since `0x0` seems to be kind of special, I would rather expect an error or something similar.
Something like that:
```json
{
  "data": {
    "path": []
  },
  "extensions": {
    "server_latency": {
      "encoding_ns": 3989100
    },
    "txn": {
      "start_ts": 5245,
      "lin_read": {
        "ids": {
          "1": 10706
        }
      }
    }
  }
}
```

### Actual result

I actually receive a path containing two nodes: `0x0` and the goal uid, for example:

```json
{
  "data": {
    "path": [
      {
        "nodeReference": "0x0"
      },
      {
        "nodeReference": "0x1b0c"
      }
    ],
    "_path_": [
      {
        "uid": "0x0"
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "encoding_ns": 999300
    },
    "txn": {
      "start_ts": 5244,
      "lin_read": {
        "ids": {
          "1": 10706
        }
      }
    }
  }
}
```

**Comment by MichelDiz** [comment]
I understand, but by logic the shortest path to something that does not exist is itself. Since 0x0 is not connected in any way with 0x1b0c, the result of the algorithm would be itself.

In this case the result is expected, and you would have to evaluate an application-level check.

That's my 2 cents, but obviously someone can offer a PR for this situation.

Cheers.

**Comment by gitlw** [comment]
Hi @fendor 

I tried with the latest code, and it's only returning the node with uid 0x0 in the response when querying shortest path using the uid 0x0, as shown in the added test in the linked PR.
Please try it again and see if you are still seeing the problem. Thanks for using Dgraph.

**Comment by gitlw** [comment]
Closing this ticket for lack of response. Also a note is that 0 as a uid is an invalid value since all uid values should start from 1.
