### ISSUE TITLE
@lang doesn't seem to work as expected

### ISSUE THREAD

**Issue by cajus** [dgraph-io/dgraph#2521]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
1.0.6

- Steps to reproduce the issue (command/config used to run Dgraph).

I've a schema for a `name` attribute defined like this:
```
    name: string @lang @index(term, exact, fulltext) .
```

There's an entry with language tags that can be querried using:

```
{  
  q(func: uid(0x2bf26)) {
    uid
    expand(_all_)
  }
}
```

which results in:

```json
{
  "data": {
    "q": [
      {
        "uid": "0x2bf26",
        "name@en": "English",
        "name@de": "Deutsch"
      }
    ]
  }
}
```

Then I query for `name@en` like so:
```
{  
  q(func: uid(0x2bf26)) {
    uid
    name@en
  }
}
```

- Expected behaviour and actual result.

I'd expect the `name@en` to be returned, but it isn't:

```
{
  "data": {
    "q": [
      {
        "uid": "0x2bf26"
      }
    ]
  }
}
```

The funny thing is that the docs contain a runnable demo which returns values for `edge@lang` queries. I'm wondering what's wrong on my side...

**Comment by MichelDiz** [comment]
I was not able to reproduce this issue in:

```
Dgraph version   : v1.0.7
Commit SHA-1     : f1803442
Commit timestamp : 2018-08-10 13:00:21 -0700
Branch           : HEAD
```

Using  `name: string @lang @index(term, exact, fulltext) .`

Mutation used:
```JS
{
    set {
      _:test <name> "Adelaide"@en .
      _:test <name> "Аделаида"@ru .
      _:test <name> "Adélaïde"@fr .
      _:test <name> "Deutsch"@de .
  }
}
```


```JS
{  
  q(func: has(name@en)) {
    uid
    expand(_all_)
  }
}
```
```JSON
{
  "data": {
    "q": [
      {
        "uid": "0x1",
        "name@en": "Adelaide",
        "name@ru": "Аделаида",
        "name@fr": "Adélaïde",
        "name@de": "Deutsch"
      }
    ]
  }
```
```JS
{  
  q(func: uid(0x1)) {
    uid
    name@en
  }
}
```
```JSON
{
  "data": {
    "q": [
      {
        "uid": "0x1",
        "name@en": "Adelaide"
      }
    ]
  }
```
```JS
{  
  q(func: uid(0x1)) {
    uid
    name@. 
  }
}
#OR
{  
  q(func: uid(0x1)) {
    uid
    name@en:.
  }
}
```
```JSON
{
  "data": {
    "q": [
      {
        "uid": "0x1",
        "name@.": "Adelaide"
      }
    ]
  }
```
```JS
{  
  q(func: uid(0x1)) {
    uid
    name@ru:.
  }
}
```
```JSON
{
  "data": {
    "q": [
      {
        "uid": "0x1",
        "name@ru:.": "Аделаида"
      }
    ]
  }
```
```JS
{  
  q(func: uid(0x1)) {
    uid
    name@en:pl:ru:de:.
    name@fr:hi:en
    name@en
    name@de
    name@ru
  }
}
```
```JSON
{
  "data": {
    "q": [
      {
        "uid": "0x1",
        "name@en:pl:ru:de:.": "Adelaide",
        "name@fr:hi:en": "Adélaïde",
        "name@en": "Adelaide",
        "name@de": "Deutsch",
        "name@ru": "Аделаида"
      }
    ]
  }
```

Any doubts, feel free to reopen.

Cheers

**Comment by kdsgambhir** [comment]
I tried to reproduce this Issue with the docker build tagged v1.0.7 as well as docker build v1.0.6, but I was not able to reproduce it. It was giving me the expected results.

**Comment by cajus** [comment]
So - if you can't, how can I debug it? I can erase everything and reinitialize the system with predefined data and it is 100% reproducible.

**Comment by manishrjain** [comment]
Maybe you could create a screencast, so we can see what you're seeing.

**Comment by cajus** [comment]
You would not see anything more than I wrote above. I pasted the ratel queries and results in the initial bug report. What do you want to see?

**Comment by manishrjain** [comment]
We're not able to reproduce the issue that you're seeing, crystal clear as it might be for you. So, it's hard for us to help you.

**Comment by MichelDiz** [comment]
@cajus can you please share the format of your mutation?
