### ISSUE TITLE
Integrate graphs obtained in Dgraph-Ratel in my web application. 

### ISSUE THREAD

**Issue by amandalmia14** [dgraph-io/dgraph#2523]
- What version of Dgraph are you using? 1.0.3

Hi, 
I have a .rdf file to which I load live to Dgraph and its works well and gave output in graphs, tree or json format in the Dgraph Ratel UI.

If I want to have the graphs to be displayed in my Angular UI, how it can be done? My backend application server is running on a Python Flask framework.

Thanks
Appreciate your time.

- Expected behaviour and actual result.

**Comment by MichelDiz** [comment]
Ratel-UI is a closed project. And the format used for graphs is customized (It don't uses another lib for this).

You can try using projects like D3.js, they have support for Angular, I believe. There is a lot about graphs that can be used with JSON or even RDF. In Discuss there is a lot of talk about this, just search for the topic.
