### ISSUE TITLE
Suggestions for get.sh

### ISSUE THREAD

**Issue by udf2457** [dgraph-io/dgraph#2526]
Could I make a couple of suggestions for `get.sh` ?

(1) Check for root

```
sudo_cmd=""
if hash sudo 2>/dev/null; then
    sudo_cmd="sudo"
fi
```

Surely you should be checking for root status (or whether the script is already being run as root) ?

(2) Check for `openssl`

```
digest_cmd=""
if hash shasum 2>/dev/null; then
    digest_cmd="shasum -a 256"
elif hash sha256sum 2>/dev/null; then
    digest_cmd="sha256sum"
else
    print_error "Could not find suitable hashing utility. Please install shasum or sha256sum and try again.";
exit 1
fi
```

`openssl` is widespread and almost always available if things like `sha256sum` are not. You can use `openssl dgst -sha256` to the same effect.

**Comment by MichelDiz** [comment]
I believe this question should be asked either in the https://discuss.dgraph.io or http://stackoverflow.com

It would be interesting to keep Github issues only for development related to Dgraph's scope. Or specific questions about Dgraph.

Please open a discuss thread and then paste here the URL.

Cheers.

**Comment by manishrjain** [comment]
I think this issue is relevant here. @udf2457 is making suggestions for how we could improve our get.sh script.

**Comment by MichelDiz** [comment]
Fair enough, I wasn't able to find "get.sh" searching this repo, so I though it was third parties issue to be discussed.  My bad.

**Comment by manishrjain** [comment]
@danielmai : Can you have a look at this?

**Comment by danielmai** [comment]
@udf2457 What's the reason for the root user check? The get script only runs `sudo` in a couple places, and if you run `sudo` as root it has no discernible effect.

**Comment by udf2457** [comment]
Surely its a case of avoiding sloppy programming ?

You check for presence of sudo at line 63 but you don't actually use the sudo_cmd variable until line 153 (or 150 if the conditional matches).  Meanwhile your script has downloaded and unzipped binaries and all sorts of other stuff that's a complete waste of time, resources and bandwidth if the user is unable to finish the script because they can't elevate their privileges.

Not only that, your first use of `sudo` on line 153  (or 150 if the conditional matches). has no exception handling.  You make an assumption that `sudo` works, you make no effort to check for exit status (e.g. `|| { echo "sudo failed ! "; exit 1; }`)

Therefore surely a little 
```
if [[ $EFUID -ne 0 ]]; then
    doLog "This script needs to be run as root !"
    exit 1
fi
```

Would not go amiss ?

**Comment by danielmai** [comment]
Thanks for explaining, @udf2457 . The script has been updated to check sudo privileges early on and to use openssl if available.
