### ISSUE TITLE
When the amount of data reaches a big amount, the performance of concurrent query is not ideal.

### ISSUE THREAD

**Issue by CalicoBox** [dgraph-io/dgraph#2528]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

1.0.7
- Have you tried reproducing the issue with latest release?

haven't tried v1.0.8
- What is the hardware spec (RAM, OS)?

    * centos 7
    * (E5-2640 v3 @ 2.60GHz * 32 cores ) * 4 machines 
    * 128G(10G for Dgraph) per machine
    * 1 TB HDD
- Steps to reproduce the issue (command/config used to run Dgraph).

1. run 3 zeros
```
  "replicas": 3
```
2. bulk load data (reduce shards: 1) and then move the result to the ‘p’

  type A point : about 8,900,00
  type B point : about 18,500,00
  edge A to B : about 32,500,00 
  The schema :
```
AKey string @index(exact) .
BKey string @index(exact) .
relation uid @reverse .
```
3. run 6 servers 
```
  "badger.tables": "ram",
  "badger.vlog": "mmap",
  "expand_edge": true,
  "lru_mb": 10737418240,
```
4. 1000 concurrent queries
```
{
  var(func: eq(AKey,"xxxxxxxxxxxxxxxxxx")){
    know{
      A as count(~know)
    }
  }
  test () {
    sum(val(A))
  }
} 
```
5. used time

6~7s for 90%
hummmm....  It doesn't seem good.
- Expected behaviour and actual result.

I don't know if this's  the best performance dgraph can do in my cluster. If not, how to make it faster?  
Any actions we could as users take? If not please let us know if you're going to work on this soon - otherwise we would need to look for another storage engine, since the main goal to use is performance

**Comment by CalicoBox** [comment]
In addition,:
1. when the number of concurrency is small, the performance is acceptable.

100 concurrent queries, about 400 ms for 90%.

2. I have tried to distribute the queries across 4 servers evenly and I anticipate this will make the response time a little shorter, but it doesn't seem to work.

**Comment by lazharichir** [comment]
Not sure at all but could this be linked to the HDD? Are you able to try this out with an SSD?

**Comment by manishrjain** [comment]
We narrowed down query performance issues to a lot of contention on the LRU cache. We removed it in v1.0.12-rc1, and have seen query latency drop by 5-10x.

https://github.com/dgraph-io/dgraph/commit/b9990f4619b64615c2c18bb7627d198b4397109c

Try again, and feel free to reopen if it is still an issue.
