### ISSUE TITLE
Fetch node property having space in between without using "expand(_all_)"?

### ISSUE THREAD

**Issue by AJAviJain** [dgraph-io/dgraph#2530]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.6

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
Windows 10, 16GB RAM

- Steps to reproduce the issue (command/config used to run Dgraph).
Using dGraph Browser provided by dgraph-ratel.
Query To run >> {node (func: uid(0x2) { uid name "abc xyz" }}

Here "abc xyz" is the one property name which has been put while creating node, and i can see all the properties by using "expand(_all_)" .

- Expected behaviour and actual result.
While trying to fetch property having space in between, it doesn't fetch the expected property value, as there is a space in between so it gives nothing while fetching.

As there can be number of edges and facets, so i can't use expand(_all_) because that takes a lot of time.

What could be the way to achieve this?

**Comment by MichelDiz** [comment]
I did not understand the question. Are you trying to do this?
```js
{ 
test(func: uid(0x2) {
   name "abc xyz"
   }
}
```

This usage is wrong. Please share the approximate result using `expand (_all_)`

As you mentioned Facets, maybe it's something else. And I misunderstood.

Maybe this?
```js
{ 
test(func: uid(0x2) {
   sompredicate @facets(eq(name "abc xyz")) {
      name
    }
   }
}
```

Or this?

```js
{ 
test(func: uid(0x2) {
   sompredicate @filter(eq(name "abc xyz")) {
      name
    }
   }
}
```

**Comment by Mezzure** [comment]
Hi,

Thanks for your quick reply.

Actually i am using JAVA APIs for dgraph.

and i want to put a node json like >>
nodeJsonObj = { 
                             "Name" : "abc",
                             "Country" : "India",
                             "Node Type" : "Product",
                             "Read Type": "Direct"
                          }

Now i am inserting this node like below >>
dgraphClient.newTransaction().mutate(Mutation.newBuilder().setCommitNow(true)
					.setSetJson(ByteString.copyFromUtf8(nodeJsonObj.toString())).build());

Now i want to get this json >>
So i am trying to run a query like below >>
query = "{ node (func: uid(0x12)) { Name Country Node Type Read Type } }";

This is not working, I do not want to use "expand(_all_)". So what should be my exact query in this case?

**Comment by MichelDiz** [comment]
Try not to use spaces, use underline:
```JS
{
  "Node_Type" : "Product",
  "Read_Type": "Direct"
}
```

If it's your case, let me know or close the issue.

Cheers.

**Comment by Mezzure** [comment]
No, That's not my case.

**Comment by MichelDiz** [comment]
So, please share your actual result and then the desired result.

**Comment by AJAviJain** [comment]
I have loaded below schema >>
name: string @index(term) . 

Now I am loading below data >>
{
  set {
    _:avi <first name> "Avi" .
    _:avi <last name> "Jain" .
   }
}

Now I am trying to get the same data >>
{node (func: uid(0x4e)) { uid first name last name } }

"0x4e" is the uid of data loaded.

Actual result >> : name not allowed multiple times in same sub-query.
Desired result >> {
  "data": {
    "node": [
      {
        "uid": "0x4e",
        "first name": "Avi",
        "last name": "Jain"
      }
    ]
  }

**Comment by MichelDiz** [comment]
Just to be sure, your mutation correctly is like this?

```js
{
set {
_:avi <first name> "Avi" .
_:avi <last name> "Jain" .
}
}

```

I strongly recommend you to use like this
```js
{
set {
  _:avi <first_name> "Avi"^^<xs:string> .
  _:avi <last_name> "Jain"^^<xs:string> .
  }
}
```

Spacing on predicates are not allowed. You will receive an error like this:

> while lexing _:avi <first name> "Avi" .: Unexpected character ' ' while parsing IRI

I also recommend you do our tour. https://tour.dgraph.io/

Cheers

**Comment by AJAviJain** [comment]
I think i have tried enough to explain it to you. can't really make you understand i guess. may be my requirement a bit different.

But need to tell you that if you are using JAVA APIs to work with dgraph. it takes a json format to store data, and allows spaces and everything we put.
so my data is there, as i can see from ratel browser, by using "expand(_all_)" it's giving me the exact data, but i was trying to get the exact one predicate, but i couldn't as there is a space in between the word... 

Thanks for your time.

**Comment by MichelDiz** [comment]
This is odd, should not happen. Could you open an Issue at https://github.com/dgraph-io/dgraph4j reporting in detail?

The insertion of predicates with space should not be allowed. The other clients do not seem to allow it, dgraph4j should prevent the same.

when you run 

> `schema {}`

 does the predicate with space appears in the list?

**Comment by AJAviJain** [comment]
Yes, predicates with space do appears in the list. 

you can try uploading them by using java client. and i can see on browser.
