### ISSUE TITLE
Installation instructions for nightly installation not working

### ISSUE THREAD

**Issue by deepakjois** [dgraph-io/dgraph#2532]
Link: https://docs.dgraph.io/deploy#nightly

When we do this on Linux:

```
 curl https://get.dgraph.io -sSf | bash -s nightly
```

If fails with the following error:

```
Sorry, we don't have binaries for this platform. Please build from source.
There was some problem while installing Dgraph. Please share the output of this script with us on https://dgraph.slack.com or https://discuss.dgraph.io so that we can resolve the issue for you.
```

It appears that the script is failing to find a checksum file for Dgraph nightly build.

A related problem seems to be that nightly builds are no longer being generated. There are instructions in the docs to use the nightly build, and the Java client also uses it for CI. So either the nightly build system needs to be fixed or the docs/CI need to be updated.

**Comment by MichelDiz** [comment]
Well, the nightly build is at the moment unused, but should soon be working. Anyone who needs to use Dgraph can use the command:

`curl https://get.dgraph.io -sSf | bash`

**Comment by danielmai** [comment]
Nightly option has been removed. https://github.com/dgraph-io/website/commit/bf4fb9c9d1e1e9e5295bcbec35f599b3377c4937
