### ISSUE TITLE
Has query takes 20-30 seconds on play.dgraph.io 

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/dgraph#2533]
### After a version upgrade some queries on play.dgraph.io have become very slow.

- What version of Dgraph are you using?
   sha256:8d1a1fd09a55a6539a61e3ff5389428e004698b5ed7e60d19634b34d0c58f43b
   "Image": "dgraph/dgraph:v1.0.7"
   Bulk import was performed using a slightly older version of dgraph.

- Have you tried reproducing the issue with latest release?
   It is the latest, as far as I can tell

- What is the hardware spec (RAM, OS)?
   It's the machine behind play.dgraph.io

- Steps to reproduce the issue (command/config used to run Dgraph).
   Open https://play.dgraph.io in browser
   Paste this query and click "Run":
```
{
  test(func: has(name), first:10) {
    uid
    name
    initial_release_date
  }
}
```
(other ways to reproduce are using `name@.`, `name@en` etc)

- Expected behaviour and actual result.
  A response to the above query will take anywhere between 3 to 53 seconds.
  Expected result is that query answered in 500ms or less.

**Comment by paulftw** [comment]
Still happening with docker image **v1.0.8** right after the standard 21million bulk import.

Following query takes **45 seconds** on play.dgraph.io: 

```
{
  test(func: has(name), first:10) {
    count(uid)
  }
}
```

/debug/requests:

```

2018/09/20 23:23:05.595663 | 46.392696 | GrpcQuery
           23:23:05.596403 | .   741 | ... Query received: { test(func: has(name), first:10) { count(uid) } }, variables: map[]
           23:23:05.597877 | .  1474 | ... Query parsed
           23:23:05.597889 | .    12 | ... Graph processed
           23:23:05.597906 | .    16 | ... attr: name groupId: 1, readTs: 10006
           23:23:05.597910 | .     4 | ... Done waiting for maxPending to catch up for Attr "name", readTs: 10006
           23:23:05.597916 | .     6 | ... Done waiting for applied watermark attr "name"
           23:23:05.598060 | .   145 | ... handleHasFunction: key: name:1
           23:23:05.600318 | .  2258 | ... handleHasFunction: key: name:2331
           23:23:05.602424 | .  2106 | ... handleHasFunction: key: name:4436
           23:23:05.605454 | .  3030 | ... handleHasFunction: key: name:12032
           23:23:05.607377 | .  1923 | ... handleHasFunction: key: name:14315
           23:23:05.609301 | .  1924 | ... handleHasFunction: key: name:21888
           23:23:05.611152 | .  1851 | ... handleHasFunction: key: name:24122

   ... gazillion more entries with handleHasFunction ...

           23:23:11.905678 | .  1418 | ... handleHasFunction: key: name:10220495
           23:23:11.907054 | .  1376 | ... handleHasFunction: key: name:10222751
           23:23:11.908436 | .  1382 | ... handleHasFunction: key: name:10230324
           23:23:11.909813 | .  1377 | ... handleHasFunction: key: name:10232616
2018/09/20 23:20:08.785280 | 30.504117 | GrpcQuery
           23:20:08.785315 | .    36 | ... Query received: { test(func: has(name), first:10) { uid name initial_release_date } }, variables: map[]
           23:20:08.786425 | .  1110 | ... Query parsed
           23:20:08.786437 | .    12 | ... Graph processed
           23:20:08.786452 | .    15 | ... attr: name groupId: 1, readTs: 10004
```

**Comment by manishrjain** [comment]
The `name` predicate (with `@lang` index) would still be a bit slow because it has an additional step after retrieving all UIDs. But, all the preds which don't have that index would be a lot faster now.
