### ISSUE TITLE
How to speed up the "Opening postings Badger DB with options" phase when starting the server?

### ISSUE THREAD

**Issue by lazharichir** [dgraph-io/dgraph#2540]
- OS: MacOS
 - Setup: 1 dgraph server locally
 - Browser: Chrome
 - Dgraph: 1.0.7
 - RAM available: 32GB with lru_mb 4096
 - Storage Type: Samsung EVO 1TB SSD
 - Dgraph Client: Dgraph Ratel

My data was loaded using the `dgraph bulk` utility and the server starts. However, everytime I shut down dgraph, and then restart it, the time it takes to fully load is nearing **half an hour**. I have over a billion edges, and the total size of the `p` folder is 150 GB.

When I start it:

```
$ dgraph server --lru_mb 4096 -p /Volumes/Samsung850EVO/dgraph/p/ -w /Volumes/Samsung850EVO/dgraph/w/

Dgraph version   : v1.0.7
Commit SHA-1     : f1803442
Commit timestamp : 2018-08-10 13:00:21 -0700
Branch           : HEAD

For Dgraph official documentation, visit https://docs.dgraph.io.
For discussions about Dgraph     , visit https://discuss.dgraph.io.
To say hi to the community       , visit https://dgraph.slack.com.

Licensed under Apache 2.0 + Commons Clause. Copyright 2015-2018 Dgraph Labs, Inc.

2018/08/18 11:27:28 server.go:117: Setting Badger option: ssd
2018/08/18 11:27:28 server.go:133: Setting Badger table load option: mmap
2018/08/18 11:27:28 server.go:146: Setting Badger value log load option: none
2018/08/18 11:27:28 server.go:157: Opening postings Badger DB with options: {Dir:/Volumes/Samsung850EVO/dgraph/p/ ValueDir:/Volumes/Samsung850EVO/dgraph/p/ SyncWrites:true TableLoadingMode:2 ValueLogLoadingMode:2 NumVersionsToKeep:2147483647 MaxTableSize:67108864 LevelSizeMultiplier:10 MaxLevels:7 ValueThreshold:32 NumMemtables:5 NumLevelZeroTables:5 NumLevelZeroTablesStall:10 LevelOneSize:268435456 ValueLogFileSize:1073741824 ValueLogMaxEntries:1000000 NumCompactors:3 managedTxns:false DoNotCompact:false maxBatchCount:0 maxBatchSize:0 ReadOnly:false Truncate:true}

############
# LONG WAIT #
############

2018/08/18 12:07:59 gRPC server started.  Listening on port 9080
2018/08/18 12:07:59 HTTP server started.  Listening on port 8080
2018/08/18 12:07:59 worker.go:89: Worker listening at address: [::]:7080
2018/08/18 12:07:59 groups.go:78: Current Raft Id: 1
2018/08/18 12:07:59 pool.go:108: == CONNECTED ==> Setting localhost:5080
```

While this is happening, CPU load increases a lot, and memory usage by Dgraph slowly grows to 20+ GB. Also, every time I start the server, hundreds of `.sst` files are created in the `p` folder.

It stays at this `Opening postings Badger DB` for around **half an hour** every time I start it. I am sure all this data and indexes must be loaded but is there any flag I could tweak besides `lru_mb` to speed up this process?

In production that will be ok since I do not plan on stopping the instance but it is a little bit of a hindrance locally. Just looking for some pointers to speed this up if possible :)

Thanks!

**Comment by manishrjain** [comment]
It looks like there's a long replay of value log going on, which is causing SSTs to be generated. If you do a clean shutdown, opening the DB again should be much faster, because the value log would have already been replayed. Can you check that?

**Comment by MichelDiz** [comment]
Since this is a question about an old version and there was no response, I will close it. If needed so, try to reproduce the error in the latest version and post a comment here that we will reopen.
