### ISSUE TITLE
A tick missed to fire. Node blocks too long

### ISSUE THREAD

**Issue by AJAviJain** [dgraph-io/dgraph#2541]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.7

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
16 GB windows

- Steps to reproduce the issue (command/config used to run Dgraph).
shutdown server after uploading some data, and trying to restart the server again for the same data.

- Expected behavior and actual result.
actual result >> A tick missed to fire. Node blocks too long!
This warning is coming continuously. 

Expecting a proper start of server with previous data uploaded.

I am using windows platform, so it generates 3 different folders for the server and zero >> P, W and ZW.

So i just want to take database backup without using export from browser. and the copying of folders is not working every time.

**Comment by manishrjain** [comment]
This issue indicates a bug in the system -- node blocks too long. @danielmai is looking to see if we can reproduce it at our end.

**Comment by danielmai** [comment]
> shutdown server after uploading some data, and trying to restart the server again for the same data.

@AJAviJain, are you following the same steps as [Deploy - Upgrade Database](https://docs.dgraph.io/deploy/#upgrade-database)? That is, are you exporting the data, bringing down the cluster, and using bulk loader to restore the data to a new Dgraph instance?

**Comment by danielmai** [comment]
I'm not able to reproduce the "tick missed to fire" problem with the details given in this issue. I can try again when we have more details the exact steps to reproduce the issue.

I tested with the [data set from the Getting Started docs](https://docs.dgraph.io/get-started/#storing-data-in-the-graph) or the [1million.rdf.gz data set](https://github.com/dgraph-io/tutorial/tree/master/resources).

Here's what I did with Dgraph version v1.0.7.

```
$ dgraph version

Dgraph version   : v1.0.7
Commit SHA-1     : f1803442
Commit timestamp : 2018-08-10 13:00:21 -0700
Branch           : HEAD
```

With the [data set from the Getting Started docs](https://docs.dgraph.io/get-started/#storing-data-in-the-graph):
1. Create a new ~/dgraph directory.
2. Start Dgraph Zero and Dgraph Server with ~/dgraph as working directory.
3. Run mutation to [add the data and schema like the docs](https://docs.dgraph.io/get-started/#storing-data-in-the-graph).
4. Shut down Dgraph Server (either Ctrl+C the Server process or curl the endpoint localhost:8080/admin/shutdown).
5. Run Dgraph Server again with same data directories. "A tick missed to fire" does **not** show up.
6. Force shut down Server (Ctrl+C consecutively three times).
7. Run Dgraph Server again with same data directories.  "A tick missed to fire" does **not** show up.
8. Shut down Dgraph Zero and Dgraph Server processes.
9. Start Dgraph Zero and Dgraph Server with same data directories. "A tick missed to fire" does **not** show up.

With the [1million.rdf.gz movie data set](https://github.com/dgraph-io/tutorial/tree/master/resources):
1. Create a new ~/dgraph directory.
2. Start Dgraph Zero and Dgraph Server with ~/dgraph as working directory.
3. Either bulk load or live load the data set into Dgraph.
4. Shut down Dgraph Server (either Ctrl+C the Server process or curl the endpoint localhost:8080/admin/shutdown).
5. Run Dgraph Server again with same data directories. "A tick missed to fire" does **not** show up.
6. Force shut down Server (Ctrl+C consecutively three times).
7. Run Dgraph Server again with same data directories.  "A tick missed to fire" does **not** show up.
8. Shut down Dgraph Zero and Dgraph Server processes.
9. Start Dgraph Zero and Dgraph Server with same data directories. "A tick missed to fire" does **not** show up.

**Comment by danielmai** [comment]
I didn't have any luck reproducing the problem with the [21 million movie data set](https://github.com/dgraph-io/benchmarks/blob/master/data/21million.rdf.gz) either. Followed Steps 3-9 above after bulk loading the data.

**Comment by AJAviJain** [comment]
@danielmai 
yes i have followed the tutorial given on https://docs.dgraph.io .

I have tried it by exporting even, but my requirement is a bit different so export thing won't work for me.

But it will work if i will simply take backup of folders, P and W but it sometime works and sometimes it doesn't. like on my recent work, i have uploaded large data, but after stopping the server i couldn't start with the same data. 

I am using windows platform, and for windows version of dgraph, which has nothing but just two .exe files.

**Comment by AJAviJain** [comment]
@MichelDiz , thanks for this, but i have already followed that. This issue is a bit different.

**Comment by AJAviJain** [comment]
It makes up four files in the folder after i start the server.
.vlog, .sst, Lock and Manifest

I want to know the use of every file and exactly where my data gets stored. and can i take backup of my data from these files or folder. and why there are two folders for dgraph, P and W what exactly the structure is.

I am sorry, i haven't found these answers anywhere in the docs.

Until i understand the complete structure, i won't be able to get the reason of getting this error. and couldn't solve it.

**Comment by AJAviJain** [comment]
sometimes when it starts the server normally, it gives below error while trying to fetch the data 

: Invalid value pointer offset: 1037 greater than current offset: 0

**Comment by MichelDiz** [comment]
In fact, what you are trying to reproduce is not supported. So I gave the example of "Export" mentioned in the documentation. The "Backup" feature is still being developed. That is, Backups are not officially supported.

What you are doing may work, but it is not recommended.

The errors "tick missed to fire", ": Invalid value pointer offset: 1037 greater than current offset: 0" may be happening just because you are reusing files generated by Dgraph in different versions or another situation.

As Backup feature is on the Roadmap see https://github.com/dgraph-io/dgraph/issues/1966 There is not much to do, just wait for it.

Cheers

**Comment by AJAviJain** [comment]
Simply stopping the server and starting again should not give error. that's what i am trying right now.

**Comment by danielmai** [comment]
Are you able to reproduce the issue consistently from a clean cluster setup?

**Comment by AJAviJain** [comment]
Below is my java code to create dgraph client >> 

channel = ManagedChannelBuilder.forAddress(hostname, portNo).usePlaintext(true).build();
DgraphBlockingStub blockingStub = DgraphGrpc.newBlockingStub(channel).withMaxInboundMessageSize(1000000000).withMaxOutboundMessageSize(1000000000);
dgraphClient = new DgraphClient(Collections.singletonList(blockingStub));

I am setting max inbound and outbound, will that affect ?
I am using it because it was creating problem while processing large data, during mutation.

**Comment by AJAviJain** [comment]
Below is the code to create node >> 

dgraphClient.newTransaction().mutate(Mutation.newBuilder().setCommitNow(true).setSetJson(ByteString.copyFromUtf8(nodeJsonObj.toString())).build());

Here "nodeJsonObj" is a json object.

**Comment by AJAviJain** [comment]
There is one related issue >> https://github.com/dgraph-io/dgraph/issues/1795

**Comment by AJAviJain** [comment]
I am using below configuration on dgraph server

{
"lru_mb": 4096,
"port_offset": 9191,
"zero": "localhost:5080",
"postings": "E:/Softwares/dgraph-windows-amd64/dgraph/p",
"wal": "E:/Softwares/dgraph-windows-amd64/dgraph/w",
"export": "E:/Softwares/dgraph-windows-amd64/dgraph/exportDB",
"badger.vlog": "mmap",
"badger.tables": "mmap"
}

**Comment by AJAviJain** [comment]
ok, can you suggest me, that in my case, how should i import the exported files.

schema file >>
		name: string @index(term) . 
		<0x3>:uid @reverse . 

Now I am loading below data >>
	<_:uid9d9a> <name> "abcdefg"^^<xs:string> .
	<_:uid3> <name> "Is A"^^<xs:string> .
	<_:uid16> <name> "NodeName"^^<xs:string> .
	<_:uid9d9a> <0x3> _:uid16 .
	
Here 0x3 is uid of "Is A" node, which i am handling in my client while creating relations.

Now this is giving me below data >>
"abcdefg" >> "0x3" >> "NodeName"

My expectations >>
"abcdefg" >> "0x3" >> "NodeName"
"NodeName" >> "~0x3" >> "abcdefg"

and if i will query >>
{node (func: uid(0x3)) { uid name }}
this should give me >> name = "Is A"

which i am able to get if i do not stop the server and don't try export thing and all.


Ahhhh i am sorry but i have tired of explaining.

**Comment by AJAviJain** [comment]
v1.0.6 is also giving >> No healthy connection found to leader of group 1

**Comment by AJAviJain** [comment]
I have tried enough, sometimes i get no error on starting and stopping the server.. while many times i get the same error message >> A tick missed to fire. Node blocks too long!

**Comment by AJAviJain** [comment]
Please help me in some way, as i have given a month to learn dgraph and and set up java client for my case. because it used to work on my test cases as expected. while it's not working on real cases.

**Comment by danielmai** [comment]
@AJAviJain We're aware and on top of the bug about "A tick missed to fire. Node blocks too long!". I've reopened this GitHub issue for that bug.

For non-bug related questions, please open a discussion at https://discuss.dgraph.io and we can continue the conversation there.

**Comment by AJAviJain** [comment]
ok, i will wait for the response.

**Comment by AJAviJain** [comment]
So, what am i suppose to do to get it solve in my machine? am i suppose to download the dgraph version again from https://github.com/dgraph-io/dgraph/releases or what exactly?

**Comment by manishrjain** [comment]
Pushed a binary here: https://storage.googleapis.com/dgraph-bin/dgraph-linux-amd64.tar.gz

**Comment by AJAviJain** [comment]
That's for linux i guess. 
Thanks for your time sir.

**Comment by AJAviJain** [comment]
Thank you so much! It solved many issues for me.
