### ISSUE TITLE
Query - get_all - Multiple Inputs 

### ISSUE THREAD

**Issue by amandalmia14** [dgraph-io/dgraph#2542]
Hi,

As stated over here [link,](https://github.com/dgraph-io/pydgraph#run-a-query) it query for 'Alice' and it results for all the information for 'Alice'.

What if I have 'n' inputs in order to get all information say 'Alice', 'Bob', etc.

What would be the query?
I tried with list or array but not working.

**Comment by MichelDiz** [comment]
Thanks for taking an interest in Dgraph. It would be interesting to move questions to our channel in the Discuss or Slack. This makes Issue Tracker more focused on troubleshooting technical issues. Thank you for understanding.

https://discuss.dgraph.io/

It is also highly recommended to use our Beginner's Tour.
https://tour.dgraph.io/

Follows answers according to what I understood:

If you have the UID of Alice and Bob you would do so
```JS
{
  persons(func: uid(0x146a6, 0x34a7c)) {
     uid
     expand(_all_)
  }
}

```

If you want to find Alice and Bob you would do so
```JS
{
  me(func: eq(name@en, ["Alice", "Bob"])) {
   uid
   expand(_all_)
  }
}
```
Using  "`expand (_all_)`" - You will get all attributes that exist on a given Node. It is advisable to use "`expand (_all_)`"  only to "debug" the data. And use in your end client only the format that you want to display.

About "`expand(_all_)`" : https://docs.dgraph.io/query-language/#expanding-graph-edges

Cheers

**Comment by amandalmia14** [comment]
Thanks for the quick response.

But in my case I have dynamic value of 'n' and I need to define the variables in `query(query, variables=variables)` as mentioned over the [link.](https://github.com/dgraph-io/pydgraph#run-a-query) 

In this link fetches all the data for a single string as "Alice", how can we use as multiple input as "Alice", "Bob", "Stevan".

Thanks for suggestion of using `expand(_all_)` but, I can't use it as I will fetch me too much irrelevant  details for my work.

**Comment by MichelDiz** [comment]
I get it, there in the discussion I mentioned this part of GraphQL Variables.
