### ISSUE TITLE
Website and documentation are misleading about the licensing of this project

### ISSUE THREAD

**Issue by SirCmpwn** [dgraph-io/dgraph#2545]
Dgraph is not [open source](https://opensource.org/osd).

e.g. https://dgraph.io/ states that it's "liberally licensed" under "Apache 2.0", neither of which is true.

e.g. https://docs.dgraph.io/ states that it's "open source"

If you must release your software under a proprietary license then so be it, but at least don't call it open source.

**Comment by SirCmpwn** [comment]
In the docs and on the website, "liberally licensed" is misleading and "open source" is false. Ideally both would be changed, but the latter definitely needs to be changed.

**Comment by illume** [comment]
@SirCmpwn you're being extremely disingenuous calling this proprietary software. Calling it that is false and misleading.

Just as the GPL and LGP evolved to solve the parasitic problem of the worlds richest companies not contributing back with network software, so to is the Apache license evolving. As the terms for free software were forked into Open Source, so is the open source definition changing. Fork is a feature not a bug. There is a large group of people who do not want their contributions taken by the wealthy when they do not give back, and when they take away freedoms from users - including the Free Software Foundation with the AGPL, and ALGPL licenses. Your definition is outdated, and misleading.

Which side are you on? The developers of the software, or the worlds richest companies? The worlds richest companies who conveniently pay a small amount into the OSI lobby group, but not towards many of the network software they have repackaged, changed a bit and then sold onto consumers (who also lose the rights to sell that software themselves).

**Comment by SirCmpwn** [comment]
The open source definition hasn't changed. I have an opinion on whether or not the Commons Clause is harmful or productive, but I haven't brought it to this thread. But one thing is certain: it's not open source, and the langauge should reflect that. The project does not use the Apache license, and the language should reflect that.

**Comment by lesderid** [comment]
@illume [Point 6 of the OSI's definition of open source](https://opensource.org/osd) seems pretty  
clear to me. 

By the way,  an 'ALGPL' (or 'LAGPL') does not exist.

**Comment by ahopkins** [comment]
For the sake of posterity, I am linking to a conversation on point on the forums. Still waiting to hear from the dgraph staff if they will address this is not.

https://discuss.dgraph.io/t/common-clause-on-license-dgraph-is-not-open-source/3167

**Comment by SirCmpwn** [comment]
Bump. The website still uses this phrase:

>Written entirely in Go, Dgraph is available under an Apache v2.0 based liberal license

Which is deliberately misleading and written in bad faith. I suggest something more like:

>Written entirely in Go, Dgraph is available under a source-available Apache v2.0 + Non-commercial license

And changing the header from "LIBERAL" to something like "SOURCE-AVAILABLE"

**Comment by pradeepyella19912** [comment]
@ahopkins  @SirCmpwn 
They have proved that they can't be trusted. See the above linked issue for more details. 

@illume 
I feel It's no longer a open source project, valid data loss bugs are being closed. If you point that out you will be portrayed as making person attacks. They will go to any length to avoid paying promised bounties and burying the truth about data loss issues/other issues.

I hope you guys have subscribed to emails. This comment would be deleted soon.

**Comment by danielmai** [comment]
With https://github.com/dgraph-io/dgraph/commit/3d0b2cd84f04b263f6c5128e682a63be8dcb220d, Dgraph has been relicensed back to Apache 2.0.

The website has been updated to reflect this.

**Comment by SirCmpwn** [comment]
Thank you very much!

**Comment by ahopkins** [comment]
Well done dgraph team!

**Comment by smolinari** [comment]
Although I could live with what was explained, since there was a bit of trust involved in Dgraph not pressing stupid legal actions, the Apache license is naturally a much better solution. Thank you!

Scott

**Comment by smolinari** [comment]
Just FYI to you all. Look what MongoDB did. 

https://www.mongodb.com/blog/post/mongodb-now-released-under-the-server-side-public-license

Scott

**Comment by ahopkins** [comment]
@smolinari  Thanks for sharing. I keep meaning to take some time to dig into this and understand it. I _think_ I really like this approach. But, I have only really skimmed the [FAQs](https://www.mongodb.com/licensing/server-side-public-license/faq) and not yet read the license itself.

**Comment by Swoorup** [comment]
Promising project. Keep it up.
