### ISSUE TITLE
Transaction failure when two simultaneous transactions try to add same xids then one transaction must fail.

### ISSUE THREAD

**Issue by metsv** [dgraph-io/dgraph#2546]
## Bug report

**Desktop**
 - OS: Ubuntu 16.04.3 LTS 4.10.0-28-generic
 - Dgraph Version: v1.0.7
 - RAM available: 16GB with "lru_mb 2048" for Dgraph Server instance
 - Storage Type:  SSD
 - Dgraph Client: dgraph4j
 - Java version:"1.8.0_151 
 - Main Container Software: docker 1.13.1
 - Dgraph TAG Version: v1.0.7

**Describe the bug**

When two simultaneous transactions try to add same xids then one transaction must fail, currently duplicated data is stored. This logic actually worked in version 1.0.3 but got broken in version 1.0.4 and still not working in version 1.0.7.

We have implemented business logic on top of transaction support and now we are not able to upgrade to latest version 1.0.7 from 1.0.3. 

Is this know issue? Or how to avoid transaction conflict?

It would be nice that we can guarantee that xid values are unique, we are checking in our business logic if xid exists, then we do not add it, but if 2 simultaneous client add parallel then they end up as duplicates in our database. Could not find any unique index constraint support either. 

**To Reproduce**

```Java
 @Test
  public void addMissingNodes_whenTwoSimultaneousTransactionsTryToAddSameXids_thenOneTransactionMustFail() throws Exception {
    boolean secondTransactionAborted = false;

    DgraphClient.Transaction transaction1 = dgraphClient.newTransaction();
    DgraphClient.Transaction transaction2 = dgraphClient.newTransaction();

    String xid = "_:label_1 <xid> \"xid-1\" .\n";

    addMissingXid(xid, transaction1);
    addMissingXid(xid, transaction2);

    transaction2.commit();

    try {
      transaction1.commit();
    } catch (Exception e) {
      secondTransactionAborted = true;
    }

    assertTrue(secondTransactionAborted);

    DgraphClient.Transaction transaction3 = dgraphClient.newTransaction();
    assertEquals("{\"q\":[{\"count\":1}]}", transaction3.query("{q(func: eq(xid, \"xid-1\")) {count(uid)}}").getJson().toStringUtf8());
    transaction3.commit();
  }

  void addMissingXid(String insertXid , DgraphClient.Transaction transaction) {
    DgraphProto.Mutation mutation = DgraphProto.Mutation.newBuilder().setSetNquads(ByteString.copyFromUtf8(insertXid)).build();
    transaction.mutate(mutation);
}
```
Created java project how to reproduce it:  https://github.com/metsv/dgraph-transaction-bug-reproduce

https://github.com/metsv/dgraph-transaction-bug-reproduce/blob/master/src/test/java/test/DGraphTransactionBugReproduceTest.java

If we change dgraph version back to 1.0.3 same test works (also revert --lru_mb 2048 -> --memory_mb 2048), can be test with provided test.

**Comment by srfrog** [comment]
@metsv can you reproduce this in 1.0.9 ?

**Comment by manishrjain** [comment]
The upsert directive is probably what you're looking for.

https://docs.dgraph.io/query-language/#upsert-directive

There's a test that we have here, which does a similar thing that you're doing:
https://github.com/dgraph-io/dgraph/blob/f7547e48fce76af1e2c390dcee8b4e771c12fd47/contrib/integration/testtxn/main_test.go#L469

In this test, multiple users can't have the same email id. If two concurrent txns try to create the same email id, one of them must fail.
