### ISSUE TITLE
Set up TeamCity builds for Ratel

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#2549]
Ratel builds should be moved to TeamCity because they're a pre-requisite for Dgraph releases.

**Comment by danielmai** [comment]
Ratel project created in TeamCity.

Need to install NPM and nvm on the build agents.

**Comment by danielmai** [comment]
Installed nvm during the build process for now instead of pre-installing it in the build agent image.

Ratel builds are running tests now.

**Comment by manishrjain** [comment]
Nice work!
