### ISSUE TITLE
Small bug in Getting Started example - Need help to send PR :)

### ISSUE THREAD

**Issue by karuppiah7890** [dgraph-io/dgraph#2552]
First of all, awesome database. I have tried it out in the past and it was damn cool. Now it looks cooler ;) I have recently come back to use the DB in an application and see how it works. While trying out the getting started page, I encountered an error, thought I will help out by fixing it.

---

* Doc page: [get-started/index.md](https://docs.dgraph.io/get-started/)
* Doc version: `master`

While I was trying out this section : https://docs.dgraph.io/get-started#get-all-movies

I got this error:

```
{
    "data": null,
    "errors": [
        {
            "code": "ErrorInvalidRequest",
            "message": ": Language tags can only be used with predicates of string type having @lang directive in schema. Got: [name]"
        }
    ]
}
```

From the looks of it, I think we should add some `@lang` directive in the schema, or not used `@en` language tag in the query. Doing either one of these should solve the problem. So, what do I do ? Change schema in this section https://docs.dgraph.io/get-started#adding-indexes or get rid of the `@en` language tag in the query ? Let me know so that I can help 😄

**Comment by MichelDiz** [comment]
you can simply use:
```js
{
 me(func: has(starring)) {
   name
  }
}
```
Or change the indexing in this way:

```js
  name: string @index(term) @lang .
  release_date: datetime @index(year) .
  revenue: float .
  running_time: int .
```
And use like this:

```JS
{
 me(func: has(starring)) {
   name@en: .
  }
}
```

Cheers

**Comment by karuppiah7890** [comment]
@MichelDiz I understand that, but the docs are having a wrong curl command. I raised the issue to fix the docs. This wasn't exactly a question. I was asking a question about how I should solve the issue with any one of the possible ways that you just mentioned

**Comment by karuppiah7890** [comment]
Can you please read the issue again and reopen this issue and let me know which way I should fix the docs? @MichelDiz

**Comment by MichelDiz** [comment]
oh well! you wanna help. Nice! Sorry about that, I thought you was asking how to solve this.
I was already preparing to edit, but feel free xD your help is of great value.

Just make a Dgraph fork, edit the link below and send us the PR.

https://github.com/dgraph-io/dgraph/tree/master/wiki/content/get-started

We appreciate it

Cheers.

**Comment by danielmai** [comment]
There's also an "Edit Page" button on the doc page itself you could use.

Looking forward to your PR, @karuppiah7890!

**Comment by karuppiah7890** [comment]
Sure, will send a PR :)
So for the fix, shall I just change the query to not give a language tag?

**Comment by karuppiah7890** [comment]
Cool, will do and send the PR your way :) looking forward to send more PRs
and help the docs and probably even code in the future :)

**Comment by karuppiah7890** [comment]
I sent a PR. cc @danielmai @MichelDiz

**Comment by danielmai** [comment]
Great! I'll take a look.
