### ISSUE TITLE
Cannot run dgraph : out of bound [0,28]

### ISSUE THREAD

**Issue by xlrx3** [dgraph-io/dgraph#2553]
Hi, I have dgraph running in a GCP instance for a while now, but just yesterday, it suddenlly stopped, and I cannot restart it. When I use 'docker start', and started the used to be running instance, it can be started but only to be exited as soon as I try to access it through my apps. I was suspecting that it is caused by memory full in dgraph. But then after I reboot the instance and try running the image manually, and trying to assign more memory to it, I encounter this error : 

`Dgraph version   : v0.8.2
Commit SHA-1     : f3bd25fd
Commit timestamp : 2017-10-11 14:59:55 +1100
Branch           : HEAD

2018/08/27 05:02:58 draft.go:252: Node with GroupID: 0, ID: 1
2018/08/27 05:02:58 gRPC server started.  Listening on port 9080
2018/08/27 05:02:58 HTTP server started.  Listening on port 8080
2018/08/27 05:02:58 worker.go:112: Worker listening at address: [::]:12345
2018/08/27 05:02:58 draft.go:252: Node with GroupID: 1, ID: 1
2018/08/27 05:02:58 draft.go:1086: Found hardstate: {Term:12 Vote:1 Commit:29 XXX_unrecognized:[]}
2018/08/27 05:02:58 draft.go:1069: Found Snapshot: {Data:[9 1 0 0 0 0 0 0 0 16 1 26 15 108 111 99 97 108 104 111 115 116 58 49 50 51 52 53] Metadata:{ConfState:{Nodes:[1] XXX_unrecognized:[]} Index:16537738 Term:13 XXX_unrecognized:[]} XXX_unrecognized:[]}
2018/08/27 05:02:58 draft.go:1086: Found hardstate: {Term:19 Vote:1 Commit:16538744 XXX_unrecognized:[]}
2018/08/27 05:02:58 draft.go:1098: Group 1 found 1006 entries
2018/08/27 05:02:58 draft.go:1112: Restarting node for group: 1
2018/08/27 05:02:58 raft.go:567: INFO: 1 became follower at term 19
2018/08/27 05:02:58 raft.go:315: INFO: newRaft 1 [peers: [1], term: 19, commit: 16538744, applied: 16537738, lastindex: 16538744, lastterm: 19]
2018/08/27 05:03:01 draft.go:1098: Group 0 found 28 entries
2018/08/27 05:03:01 draft.go:1112: Restarting node for group: 0
2018/08/27 05:03:01 logger.go:121: 1 state.commit 29 is out of range [0, 28]
panic: 1 state.commit 29 is out of range [0, 28]

goroutine 2192 [running]:
log.(*Logger).Panicf(0xc42006a6e0, 0xdbd017, 0x2b, 0xc459e9e000, 0x4, 0x4)
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/log/log.go:223 +0xdb
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*DefaultLogger).Panicf(0xc42ac18660, 0xdbd017, 0x2b, 0xc459e9e000, 0x4, 0x4)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/logger.go:121 +0x60
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.(*raft).loadState(0xc463cec960, 0xc, 0x1, 0x1d, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/raft.go:1200 +0x1c7
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.newRaft(0xc4594d2080, 0xc4735c3e28)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/raft.go:303 +0xc39
github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft.RestartNode(0xc4594d2080, 0x0, 0xc400000000)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/coreos/etcd/raft/node.go:219 +0x43
github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode(0xc420094280, 0xc42ac18640)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/draft.go:1117 +0x148
github.com/dgraph-io/dgraph/worker.StartRaftNodes.func2(0xc4606cff20, 0xc420094280)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/groups.go:171 +0x61
created by github.com/dgraph-io/dgraph/worker.StartRaftNodes
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/groups.go:169 +0x3a8`

what is the cause of this and how can I repair it? thanks.

**Comment by MichelDiz** [comment]
Does this error happen immediately?

**Comment by manishrjain** [comment]
Sorry, you're running a version of Dgraph (v0.8.2) that's no longer supported.

**Comment by xlrx3** [comment]
@MichelDiz apparently yes , the error happen as soon as I try running it with 

> docker run -it -p 8080:8080 -p 9080:9080 -v ~/dgraph:/dgraph --name dgraph dgraph/dgraph dgraphzero -w zw command.

@manishrjain ah, I see. So, this error happens because I use the unsupported version then? And what should I do to make it works again without losing the data?

**Comment by MichelDiz** [comment]
Try to revert the modified configuration and then do an Export and upgrade. Have you tried this?

You said 

> "it can be started but only to be exited as soon as I try to access it through my apps."

 This seems to me an OOM problem. This version you used had something of the same kind happening. In the most current versions it does not happen anymore.

From what you wrote, it seems to me that you can at least keep an instance of the Dgraph working. Until the moment that you perform an operation. So you're able to do an export.

So then bulkload and try again your app.

Btw Before you upgrade, read the changes that have occurred since that version you're using, on the releases page.

I'll close this issue since this version is no longer supported, but any doubt you can find me or others in Discuss or Slack.

Cheers.
