### ISSUE TITLE
Using geo index produces weird issue

### ISSUE THREAD

**Issue by Fohlen** [dgraph-io/dgraph#2559]
## Bug report

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser: Chrome
 - Dgraph Version: Dgraph version v1.0.7 Commit SHA-1     : f1803442
 - Dgraph Client: Dgraph-js (however it also occurs via Ratel)
 - Main Container Software: Docker version 18.06.1-ce, build e68fc7a

**Describe the bug**
I want to use the `geo` type and index alongside but it fails on data insertion.

**To Reproduce**
I want to use the following schema as per the documentation
```
position: geo @index(geo) .
```

Afterwards I am inserting a new node via the JSON import:

```js
{
    location: { 
      name: 'libero', 
      position: {
        type: 'Point',
        coordinates: [1.0, 2.0]
      }
   }
}
```

On insertion it produces:
```
{ Error: 2 UNKNOWN: Input for predicate position of type scalar is uid
    at Object.exports.createStatusError (/Users/berger/workspace/eventzimmer/api/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/Users/berger/workspace/eventzimmer/api/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/Users/berger/workspace/eventzimmer/api/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/Users/berger/workspace/eventzimmer/api/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/Users/berger/workspace/eventzimmer/api/node_modules/grpc/src/client_interceptors.js:841:24)
  code: 2,
  metadata: Metadata { _internal_repr: {} },
  details: 'Input for predicate position of type scalar is uid' }
}
```

**Expected behavior**

This should work.

**Additional context**
Apparently it seems that dgraph is expecting an actual `geo` node to link position against. This totally makes sense. However, how is the schema intended to be used then?

- should I link the actual node? But then? What for the schema? It would be impossible to define a node
- maybe the JSON importer is just not doing it right here. I haven't tested manual mutations.

**Comment by MichelDiz** [comment]
Well, using Ratel I was able to get the desired result.
You have to use a valid JSON at first.

I did not need to add Schema before executing the mutation. I just executed the way it looks below and got the expected result.

```JSON
{
  "set": [
      {
    "location": { 
      "name": "libero", 
      "position": {
        "type": "Point",
        "coordinates": [1.0, 2.0]
      }
   }
}
  ]
}
```

### Response
```JSON

{
  "data": {
    "test": [
      {
        "uid": "0x3",
        "name": "libero",
        "position": {
          "type": "Point",
          "coordinates": [
            1,
            2
          ]
        }
      }
    ]
  }
```
As you can see predicate "position" is in geo indexing
![image](https://user-images.githubusercontent.com/6570955/44860858-9e1d9c00-ac4d-11e8-9aa3-1319f59038e6.png)


Cheers

**Comment by Fohlen** [comment]
Well, but that's not the point. You will need to use the `@index` predicate in order to use e.g the `near()` filter. I can add point's, but not with the predicate. But that's the whole point of having native GeoLocation support .......... 😄

**Comment by MichelDiz** [comment]
Just clarifying, maybe this is the confusion. (just maybe)

The predicate "position" should only be used to save Geo obj. So the Geo itself is not a Node. You cannot use the predicate "position" to other types, rather than that stated in the scheme.

You create a node with the "position" predicate (with geo obj) and then link that node itself via it's UID to another predicate in the target node. If you want to relate other Nodes to that specific point.

Woulbe something like:

`User node =>  UID: Position node => geo obj`

In the User Node you can use other predicate like "Location" with UID index. Pointing to the "point node".

But never:

`User node => => geo obj`

You can also bring the point to the User Node itself. But this point will be directly linked to the user.

User node with pred "Position" => geo obj`

**Comment by Fohlen** [comment]
Hey @MichelDiz 
Thanks for the clarification. This is what I had in mind for the positions.
It turned out for me that the input values I was supplying were actually strings.
The error then of course makes sense because it violates the predicate.

So if somebody ever stumbles across this: the
`Error: 2 UNKNOWN: Input for predicate position of type scalar is uid`
means that you're potentially supplying a wrong type!

Thanks for the help @MichelDiz
