### ISSUE TITLE
Slow performance of dgraph on linux.

### ISSUE THREAD

**Issue by AJAviJain** [dgraph-io/dgraph#2560]
Running a query on ratel query browser
{node (func: has(name)) {count(uid)}}
         Here output is >> count = 200

While i am running below query >>
{node (func: has(name)) {uid name}}

Total time taken to give results
  on windows >>
          Server latency: 2ms
          Rendering latency: 179ms
  on linux >>
          Server latency: 32ms
          Rendering latency: 167ms

I am having a PC with Dual-boot (Linux and Windows), 20GB Ram, 500GB HDD.
dgraph zero and server both are running on single machine.

dgraph version - v1.0.8_rc1

For zero, i am not making any configuration just using default one.
Below configuration used to run server (file > config.json) >>
  {
   "lru_mb": "4096",
   "port_offset": "9191",
   "zero": "localhost:5080",
   "postings": "E:/Softwares/DGraph/dgraph/p",
   "wal": "E:/Softwares/DGraph/dgraph/w",
   "export": "E:/Softwares/DGraph/dgraph/exportDB"
  }

Server started by below commands >>
     dgraph zero
     dgraph server --config config.json

Everything is similar for both the OS but performance is drastically different. Linux's dgraph is responding very slow as compared to window's dgraph. No difference in configuration. No difference at all.

In linux, Tried with swap enabled and disabled both. no difference.

Tried with earlier versions of dgraph also, performance of dgraph is weak in linux as compared to windows.
I have not seen any error on logs and not anywhere, it's working fine as it should, just performance is slower.

I am expecting the same performance of dgraph in linux as windows.

**Comment by avinashjain7143** [comment]
@manishrjain
Plz have a look at this issue.

**Comment by gitlw** [comment]
Hi @AJAviJain 
IMO, in order to get a reliable benchmark, you need to run the query lots of times and see how the performance varies. Also because it's been a while since we last heard from you, I'm closing this issue for now. Please feel free test with our latest code, and reopen if this is still a problem for you. Thanks for using Dgraph.
