### ISSUE TITLE
Feature request: Filtering list values

### ISSUE THREAD

**Issue by disconsented** [dgraph-io/dgraph#2563]
Say I have a predicate `timestamps:[datetime] @index(month) @count . ` and I only want values between a range. 
Currently, since the inequality functions require a predicate of some kind you can't use it to filter values as suggested in #2271, additionally that returns everything as long as there is _a_ value within that range (rather than just the values you want). The current workaround that I have come up with is converting `timestamps` to a `UID` from `[datetime]` and then creating another `timestamp` type but this has the downside of 2 predicates + N UID's to deal with elsewhere.

**Comment by MichelDiz** [comment]
Closed - Moved to discuss. Can be reopened when there's more details or/and the consolidated discussion..
