### ISSUE TITLE
Not to use trigrams when filtering by regexp

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#2565]
it's strange that for using regexp expression in filter section, still need to create trigram index.
it's just filtering on already fetched data, not a search by some condition. when using it in filter section, it makes sense just to apply regular expression to a string value and filter out values that don't match.

as for now, trigram index is needed, so need additional space to store it, and, what's more important, is not possible to use regular expressions like `"^f.*"` to keep values starting with "f" letter only. whereas all nodes are already found by outcoming edges from some other node.

i found 1 workaround to add 2 junk letters to every string value i need to filter with "start with" condition, so `"^f.*"` condition becomes `"^AAf.*"`. it works but looks real ugly

so, why not using regular "regexp" go function when processing regular expression in "filter" section, and use trigram index when use it in "func" one?

**Comment by MichelDiz** [comment]
> Thanks for taking an interest in Dgraph. It would be interesting to move questions to our channel in the Discuss or Slack. This makes Issue Tracker more focused on troubleshooting technical issues. Thank you for understanding.

I see that you are proposing a change, but ideally you would have opened a discussion first to see where and how to apply that change. As it seems more a informal technical question I recommend a discussion first. So I'll close this.

BTW From what you wrote it seems to me that there may be two situations. One possible change to the code (feature) and one possible add to documentation. What would be two distinct issues.

Once discussed and defined, issues could be filled up and considered.

https://discuss.dgraph.io/

Cheers
