### ISSUE TITLE
has(predicate) captures nodes which had the predicate deleted

### ISSUE THREAD

**Issue by slawo** [dgraph-io/dgraph#2574]
## Bug report

**Desktop (please complete the following information):**
 - OS: Linux + dockerImage dgraph/dgraph:v1.0.8
 - Dgraph Version: v1.0.8
 - RAM available:  8GB with "lru_mb 4096" for each Dgraph Server instance
 - Storage Type:  Cloud Storage
 - Dgraph Client: ratel

**if Containerization (please complete the following information):**
 - Main Container Software: kubernetes v1.11.1
 - Dgraph TAG Version: v1.0.8 1dd8376f

**Describe the bug**

When using has(predicate) in queries we have strange results. After some debugging I found that many nodes without having the predicate were included in results.

The ones I have identified had the predicates removed.

This happens with dates, but I have not tested other predicate types.

**To Reproduce**

- create a bunch of nodes with dates
- delete the dates from those nodes
- query with had(date_predicate)
- observe nodes being returned: among the results, nodes with the predicate previously deleted are present.

```
{
  broken(func: has(obj.date_ended)) {
    uid
    obj.date_ended
  }
}
```

returns 

```

      {
        "uid": "0x5184"
      },
      {
        "uid": "0x618c"
      },
      {
        "uid": "0x6a65"
      },
      {
        "uid": "0x9c37"
      },
      {
        "uid": "0x9d28"
      },
```
...

**Expected behavior**

not receiving nodes where predicates don't exist

**Additional context**

This is a fresh install of dgraph with all data added today using the dgo driver using `api.NQuad`

**Comment by MichelDiz** [comment]
Duplicated of https://github.com/dgraph-io/dgraph/issues/2212
Should be fixed by 999a4e0c42b9a10c4111de52eb5703ad682a2bbe.
Is related to https://github.com/dgraph-io/dgraph/issues/2484

"This is a bug with has queries where empty PL's are not ignored." pawanrawal.

**Comment by slawo** [comment]
It seems related but it happens in v1.0.8 so I did not bother linking this.

Also I have not tried this on other predicate types.

The issue is quite important as I use `has()` to filter data. In most cases on dates I'm able to use `le(predicate, CURRENT_DATE)` to get away with it but in some cases I need `not has()` and there I don't believe I can go around the issue.

**Comment by manishrjain** [comment]
We changed the way Posting List Deletions are happening, so maybe that's causing it. Needs investigation.

**Comment by manishrjain** [comment]
This should now be fixed. Can you test, @slawo ?

**Comment by MichelDiz** [comment]
Hey @manishrjain  I did a test with   `  image: 'dgraph/dgraph:v1.0.9-rc1'` and is working as expected.
```JSON

{
    "set": [
 		{
        "obj.date_ended": "2018-08-14T11:56:46Z"
      },
      {
        "obj.date_ended": "2018-08-14T11:56:46Z",
      },
      {
        "obj.date_ended": "2018-08-14T11:56:46Z"
      },
      {
        "obj.date_ended": "2018-08-14T11:56:46Z"
      },
      {
        "obj.date_ended": "2018-08-14T11:56:46Z"
      }
	]
}


```
```js

{
    delete {
      <0x1> <obj.date_ended> * .
      <0x4> <obj.date_ended> * .
      <0x7> <obj.date_ended> * .
      <0x8> <obj.date_ended> * .
      <0x9> <obj.date_ended> * .
	}
}

```

And tried too

```JS
{
    delete {
      <0x1> * * .
      <0x4> * * .
      <0x7> * * .
      <0x8> * * .
      <0x9> * * .
	}
}

```

**Comment by manishrjain** [comment]
Thanks, @MichelDiz !
