### ISSUE TITLE
Invalid error for semantically correct query

### ISSUE THREAD

**Issue by armaneous** [dgraph-io/dgraph#2610]
- What version of Dgraph are you using?
dgraph:latest

- Have you tried reproducing the issue with latest release?
Yes

- Steps to reproduce the issue (command/config used to run Dgraph).
`my_id` is indexed on `exact` in schema. Performing this mutation:
```
{
  set {
    _:test <pred_one> "one" .
    _:test <test> "" .
    _:test <my_id> "123" .
  }
}
```

- Expected behaviour and actual result.
Query should return no results:
```
{
  t as var(func: eq(my_id, "123")) @filter(has(test)) @cascade {
    p as pred_test
  }
  query(func: eq(my_id, "123")) @filter(uid(t) AND eq(val(p), "my test")) {
    expand(_all_)
  }
}
```
Instead, this error appears:
`: Expected a valid value map. But got empty.`

Modifying the query to be of this format returns the expected no results found:
```
{
  t as var(func: eq(my_id, "123")) @filter(has(test)) @cascade {
    p as pred_test
  }
  query(func: uid(t)) @filter(eq(my_id, "123") AND eq(val(p), "my test")) {
    expand(_all_)
  }
}
```

**Comment by danielmai** [comment]
@srfrog Can you take a look at this?
