### ISSUE TITLE
Nightly notes truth value is inverted or unclear

### ISSUE THREAD

**Issue by kortschak** [dgraph-io/dgraph#2618]
The text describing the nightlies' reliability is either incorrect or unclear:

>  **Note** You can also use the `:master` tag when running docker image to get the nightly build. Though, nightly is thoroughly tested and could have unseen bugs.

This should be "Though, nightly is not thoroughly tested and could have unseen bugs." or "Though nightly is thoroughly tested, it could have unseen bugs." depending on which is true.

I'd send send a PR to fix this, but you don't have the source for the docs anywhere obvious anymore.

**Comment by danielmai** [comment]
Any page on the docs can be edited with the "Edit Page" button at the top.

I'll remove the note for now. Nightly builds haven't been released for the last few months. Once they're reinstated we'll put them back in the documentation.

**Comment by kortschak** [comment]
Thanks, though the situation is moot having read the discussion on your change of license and the approach you take on discuss.dgraph.io with dissenting views.
