### ISSUE TITLE
Performances Bottlenecks (GC, CalculateTabletsSize)

### ISSUE THREAD

**Issue by kri5** [dgraph-io/dgraph#2619]
- What version of Dgraph are you using?
1.0.9-rc5

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?
16GB Ram 4Vcpu (GKE), one dgraph and three dgraphzero, docker upstream image

- Steps to reproduce the issue (command/config used to run Dgraph).
I ran `go-torch --seconds 360` on our test cluster, where we were running queries against.

- Expected behaviour and actual result.
20% of the time seems to be spend in GC, 30% in computing the tablet size.

You can find the flame graph i generated just below.
[torch.svg.gz](https://github.com/dgraph-io/dgraph/files/2427761/torch.svg.gz)

Feel free to come back to me if you need more informations.

**Comment by danielmai** [comment]
Can you share more about the activity of the cluster during the performance measurement? Was in only running queries? Were there mutations happening as well?

**Comment by kri5** [comment]
There are ~20 large queries running queries at the same time (in continuous). Theses queries are only read queries (no mutations).

I re-ran the same flametorch while similar workload was running, still looks the same, so i won't attach it, but i did get a heap profile as requested.

[pprof.dgraph.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/dgraph-io/dgraph/files/2437757/pprof.dgraph.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)

**Comment by manishrjain** [comment]
It is not clear what the issue is. Dgraph does do calculateTabletSizes, which would take CPU cycles, yes. But, we can't just stop doing that.
