### ISSUE TITLE
dgraph-ratel: Cannot select "Mutate" or "Alter" in Console tab UI

### ISSUE THREAD

**Issue by Brahmasmi** [dgraph-io/dgraph#2631]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.9

- Have you tried reproducing the issue with latest release?
Latest release is v1.0.9 as of filing this bug.

- What is the hardware spec (RAM, OS)?
MacOS High Sierra 10.13, Firefox 62

- Steps to reproduce the issue (command/config used to run Dgraph).
1) dgraph zero
2) dgraph server --lru_mb 1024 --zero localhost:5080
3) dgraph-ratel
4) Open http://localhost:8000 in FF62
5) On Console tab, try to select "Mutate" or "Alter".

- Expected behaviour
"Mutate" or "Alter" radio buttons get selected.

- Actual Result
"Mutate" or "Alter" radio buttons do not get selected. There is no error or feedback.

**Comment by MichelDiz** [comment]
I can confirm on Firefox 62.0.3 "Quantum". To get around this temporarily use Chrome or Safary.

**Comment by paulftw** [comment]
Does play.dgraph.io work in Firefox?

**Comment by paulftw** [comment]
Just pushed a fix. 
Can confirm that mutate and alter were broken in FF 62.0.3 on play.dgraph.io but now are working as expected.
