### ISSUE TITLE
dgraph-ratel: Content Security Policy blocks loading of UI

### ISSUE THREAD

**Issue by Brahmasmi** [dgraph-io/dgraph#2632]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.9

- Have you tried reproducing the issue with latest release?
Latest release is v1.0.9 as of filing this bug.

- What is the hardware spec (RAM, OS)?
MacOS High Sierra 10.13, Firefox 62

- Steps to reproduce the issue (command/config used to run Dgraph).
1) dgraph zero
2) dgraph server --lru_mb 1024 --zero localhost:5080
3) dgraph-ratel
4) Open http://localhost:8000 in FF62
5) Page does not load, blank window
6) Right click anywhere on the blank display window, select "Inspect Element"
7) Open "Console" tab within the FF Inspector, and observe the following errors:
```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: !function(e,t,r,n,a){if(!e[a]){for(var i....
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: function isTemplateAnnotation(n){var e=n....
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: function injectUrls(t,e){var c=document.....
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: !function(){var e,t,r=document,c=r.getEl....
```

- Expected behaviour
Page loads

- Actual result
Page does not load, CSP errors seen in the FF Inspector

**Comment by paulftw** [comment]
Works for me in FF62 when I use localhost ratel but connect to the play.dgraph.io server.

Will try with a local dgraph server tomorrow, but that is unlikely to be the problem - api calls do not break loading of the client.

**Comment by paulftw** [comment]
Cannot reproduce with FF62 - tried on localhost, play.dgraph.io, with both local and remote dgraph servers.

@Brahmasmi are you still experiencing this issue? I saw you opened another FF related bug later, indicating you were able to load the page.
Could that be an issue with custom security settings or a browser extension?

I'm closing this issue for now. Please reopen if anyone sees this issue again
