### ISSUE TITLE
Incorrect info in dgraph ratel about count of nodes

### ISSUE THREAD

**Issue by neetikh** [dgraph-io/dgraph#2640]
Hello,

In Dgraph Ratel getting incorrect no of nodes returned by the query.
Same was working fine earlier.

Please let me know if you want me to add any screenshots

**Comment by danielmai** [comment]
Please add more details.

* Can you share steps to reproduce the issue?
* Do non-Ratel clients see the same issue?
* Is the count incorrect in the JSON response within Ratel?

**Comment by neetikh** [comment]
I am doing data migration to Dgraph.
At any point in time, I am running a Dgraph query to check what all records are inserted.
But when I am querying- In Json response I am getting all nodes, but output bar shows as 200 nodes found.
- Then I have to run another query to actually find the total no of nodes migrated so far.

![image](https://user-images.githubusercontent.com/41024354/46648951-cedde300-cbb4-11e8-9e28-a9e526c15aeb.png)

Actual count-
![image](https://user-images.githubusercontent.com/41024354/46648973-e87f2a80-cbb4-11e8-9791-6d9aa5bc184e.png)

**Comment by MichelDiz** [comment]
@neetikh At the top of the Frame there should be a link mentioning something like "Only a subset of graph was rendered. Expand remaining 1000 nodes." Click this link. Or simply go to the JSON tab and you'll see all nodes there.

**Comment by paulftw** [comment]
@neetikh can please share the query you are running to get the records inserted?

**Comment by MichelDiz** [comment]
As this is an old issue, a step by step procedure was not provided to reproduce the problem and as known that Ratel became public. I'll close this issue.

Please open a new issue with more details and that can be reproduced.

Ratel's issues https://github.com/dgraph-io/ratel/issues

cheers.

**Comment by neetikh** [comment]
Hello Michel

With new UI issue is now there. You can please close this issue.

Thanks for your help.

Thanks & Regards,
Neeti Khard
