### ISSUE TITLE
Can multiple edges of the same type exist between two nodes ?

### ISSUE THREAD

**Issue by CalicoBox** [dgraph-io/dgraph#2644]
If Tom saw the same movie in different theaters at different times. The RDF should be : 
```
{
  _:Tom <see> _:TheShawshankRedemption (time="20180101",theater="aaa") .
  _:Tom <see> _:TheShawshankRedemption (time="20181009",theater="bbb") .
}
```

But it seems that the latter covers the former, there is only one edge between Tom and TheShawshankRedemption.

Is that the case ?

**Comment by MichelDiz** [comment]
You will have to add an intermediary for this. Create a node for example "Session" and then each new session will point to a Theater and another Edge for a movie. From the relation of the Session to the Theater you decide whether to use Facets or not.

Please see our Tour. https://tour.dgraph.io/

**Comment by CalicoBox** [comment]
Thanks for your reply. U mean
```
{
  _:Tom <do> _:see-move-1 (time="20180101",theater="aaa") .
  _:Tom <do> _:see-move-2 (time="20181009",theater="bbb") .
  _:see-move-1 <movie> _:TheShawshankRedemption .
  _:see-move-2 <movie> _:TheShawshankRedemption .
}
```
Is that the case ?

That is, there can only be one version of edges (predicates) which are the same type between two points.

In addition, I want to understand the predicate storage principle of Dgraph and the graph query principle. Can I find these?

Cheers.

**Comment by MichelDiz** [comment]
I think that way to better understand.
```RDF

 {  
    #Create a fixed movie and Theater (keep in mind to use the same uid in nearly future)
    #e.g: _:session32 <watched> <0xf34> .
    _:TheaterGrand <name> "Le Grand Theater" .
    _:MovieSSR <name> "The Shaw shank Redemption .
    
    #Create a User
    _:USER <jobTitle> "Professor" .
    _:USER <name> "Tom Doe" .
    _:USER <sessions> _:session1 . #A list of sessions.
    _:USER <sessions> _:session2 .
    _:USER <telephone> "(425) 123-4567" .
    _:USER <watched> _:MovieSSR . # This is a list of movies that this user already watched - Only to represent it.
    
    #Add relations
    _:session1 <At_theater> _:TheaterGrand (time="20180101") .
    _:session1 <watched> _:MovieSSR .
    _:session2 <At_theater> _:TheaterGrand (time="20181009") .
    _:session2 <watched> _:MovieSSR .
    #In practice you do not need to use Facet, you can use the session node itself to add extra data.

  }
```

I'm not sure I understand the last questions. Dgraph uses BadgerDB. He keeps everything in KV.
