### ISSUE TITLE
Concern regarding usage of dgraph on production.

### ISSUE THREAD

**Issue by david1371** [dgraph-io/dgraph#2645]
This is regarding the issue in badger your underlying key value store. **The below incident shows that you don't know your code well.**

**Answer this, I promise i won't create new accounts and post again.**

You mentioned previously for Func1 that
`It is not the same. Badger has checksums in place to find if the FS has lost data, due to crash. You're writing an entry, even ensuring that it does not return an error (i.e. it has been ACKed and Fsynced to the FS), but mucking up the bits which have a certain meaning to Badger. If you find a way to reproduce this using public APIs, feel free to file a new issue. I'm closing this one.`

Now Func2 writes using public API.
After writing truncate the file to 51B using `truncate --size 51 p1/000000.vlog` Now do `diff p1/000000.vlog p2/000000.vlog` and there's no difference between files.
So there's literally no difference between Func1 and Func2(After truncating).

Both functions are doing same. Now open either badger folder using version prior to this fix.
da4f1dc
Badger can't detect data corruption.

I don't understand why the valid bug was closed, saying Func1 was mucking up some internal bits(In fact it exactly simulates what happens when you write using public api and truncate the file). You were talking about checksums, badger didn't catch it until it was fixed recently.

**Either you closed the issue intentionally or you don't know your code well.**

Func1
```
func TestDataLoss1(t *testing.T) {
        dir := "p2"
        opts := getTestOptions(dir)
        opts.SyncWrites = true

        kv, err := Open(opts)
        require.NoError(t, err)
        key := func(i int) string {
                return fmt.Sprintf("%d%10d", i, i)
        }
        data := fmt.Sprintf("%10d", 1)
        // This part simulates badger crashing before writing bitFinTx
        e := &Entry{
                Key: y.KeyWithTs([]byte(key(0)), kv.orc.nextTxnTs),
                meta: bitTxn,
                Value: []byte(data),
        }
        kv.orc.nextTxnTs++
        err = kv.batchSet([]*Entry{e})
        require.NoError(t, err)
}
```
Func2
Truncate file
```
func TestDataLoss2(t *testing.T) {
        dir := "p1"
        opts := getTestOptions(dir)
        opts.SyncWrites = true

        kv, err := Open(opts)
        require.NoError(t, err)
        key := func(i int) string {
                return fmt.Sprintf("%d%10d", i, i)
        }
        data := fmt.Sprintf("%10d", 1)
        err = kv.Update(func(txn *Txn) error {
                        return txn.Set([]byte(key(0)), []byte(data))
                })
        require.NoError(t, err)
}
```

**Comment by manishrjain** [comment]
The issue is already fixed. You can stop spamming us now.
