### ISSUE TITLE
Errors refactor and organization

### ISSUE THREAD

**Issue by srfrog** [dgraph-io/dgraph#2646]
This feature is to organize all dgraph's errors into a new Go package that will allow us to describe and inspect errors better. Currently most errors are consumed by funcs in the `x` package. We need to extract `x/error.go` into its own package (errors) and build all the features we need to track distributed issues.

Design goals:
- New error type that is stackable and has contextual info.
- Context must include file, lines, and kind of operation.
- Reflection funcs to inspect context and/or kind.
- Unwrap stacktrace to describe chained events.
- Good performance and minimal allocs. 
- (Optional) User-friendly error codes (string)
- (Optional) Pluggable logging and tracing.

Related issues:
- Export mutation errors: #2498
- Improve error messages to point at specific line and character number #2609 
- Proper catching of errors like "readTs: 60534 less than minTs: 60535 for key" #2647 
- dgraph continues answering OK after OOM #3038

**Comment by codexnull** [comment]
I would also like to have some distinction for errors based on audience. Errors meant to help developers diagnose a problem with dgraph itself should be different than those reporting a runtime error.  For example, users should not be faced with a stack trace because they mistyped a filename or command line option.

**Comment by jgoodall** [comment]
In the meantime, is there a list of temporary errors. My understanding is that `Transaction has been aborted` and `readTs: <num> less than minTs: <num>` should both be retried. Is that true, and are there others?

**Comment by campoy** [comment]
We are now using the package github.com/pkg/errors, therefore making this obsolete.
