### ISSUE TITLE
Allow using `uid_in` at the query root

### ISSUE THREAD

**Issue by sean-adler** [dgraph-io/dgraph#2649]
This would be super helpful in certain circumstances, e.g. for authorization — if you happened to implement auth by pointing all nodes owned by a user at some sort of `User` node, then `uid_in` is a natural way to filter for all of those nodes.

Supporting this at the query root would be extremely useful since most nodes in the database would not be connected to the `uid_in` target node, so presumably performing this query at the root would be much more efficient than a `@filter` (which is currently the only option).

**Comment by sean-asapp** [comment]
@danielmai can you advise on roughly how difficult this would be to implement? Happy to help if possible.

**Comment by sean-adler** [comment]
@danielmai can you advise on roughly how difficult this would be to implement? Happy to help if possible.

**Comment by sean-adler** [comment]
Thanks @manishrjain, I'm talking about this:

https://docs.dgraph.io/master/query-language/#uid-in

> `uid_in` cannot be used at root, it accepts one UID constant as its argument (not a variable).

Using a query block doesn't solve my problem because it's too slow. I assume it would be faster if supported at root. Does this make sense?

**Comment by manishrjain** [comment]
Have you looked at the `has` function? It works at root, and lets you get a list of UIDs, having a certain predicate. Seems like that's what you need?

https://docs.dgraph.io/query-language/#has

**Comment by MichelDiz** [comment]
uid_in is useful when you need to filter based on "third parties node". For example, you want to know when a particular node has connections with 2 other users through the same predicate.

E.g. The query below wants to know what movies Marc Caro and Jean-Pierre Jeunet have done together.

```graphql
{
  caro(func: eq(name@en, "Marc Caro")) {
    name@en
    director.film @filter(uid_in(~director.film, 0x6506bd)){
      name@en
    }
  }
}
```

However, I believe the idea "Allow using` uid_in` at the root query" was already possible. But through "@filter at root". 

 _By Doing "`query(func: uid_in(~nodes_owned,"0x9c6716"))`" Doesn't make sense with the logic aplied today in uid_in- Not even in a sense or `@reverse`. You necessaryly need an intermediary node (mean, an edge) for the job. So you need the `@filter`._

Doing this query (check Mutation in JSON at the end) you will have the expected result of the question you brought.

```graphql
{
  #test(func: eq(name, "Alice")){uid} "0x9c6716"
  #test(func: eq(name, "Alice 2")){uid} "0x9c6719"
  
    
  query(func: has(~nodes_owned)) @filter(uid_in(~nodes_owned,"0x9c6716"))
    {
    uid
    name
  }
   query2(func: has(~nodes_owned)) @filter(uid_in(~nodes_owned,"0x9c6719"))
    {
    uid
    name
  }   

}
```
## Result

```
{
  "data": {
    "query": [
      {
        "uid": "0x9c6711",
        "name": "box1"
      },
      {
        "uid": "0x9c6712",
        "name": "box2"
      },
      {
        "uid": "0x9c6713",
        "name": "box3"
      },
      {
        "uid": "0x9c6714",
        "name": "box4"
      }
    ],
    "query2": [
      {
        "uid": "0x9c6717",
        "name": "box42"
      },
      {
        "uid": "0x9c671a",
        "name": "box12"
      },
      {
        "uid": "0x9c671b",
        "name": "box22"
      },
      {
        "uid": "0x9c671c",
        "name": "box32"
      }
    ]
  }
}
```
## Mutation
```
{
      "set": [
        {
          "name": "Alice",
          "User": "true",
          "nodes_owned":[
            {
              "name": "box1"
            },
            {
              "name": "box2"
            },
            {
              "name": "box3"
            },
            {
              "name": "box4"
            }
          ]
        },
        {
          "name": "Alice 2",
          "User": "true",
          "nodes_owned":[
            {
              "name": "box12"
            },
            {
              "name": "box22"
            },
            {
              "name": "box32"
            },
            {
              "name": "box42"
            }
          ]
        },
        {
          "name": "Bob",
          "User": "true"
        }
      ]
    }

```

If you still have questions, please open a discussion in the https://discuss.dgraph.io

Cheers.
