### ISSUE TITLE
Accept multiline input as part of value in a mutation.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#265]
For Gru, question text will usually be multiple lines. 

On running a mutation like
```
curl localhost:8080/query -XPOST -d $'mutation {
  set {
    <question> <text> "Line 1\t\n\n Line 2" .
  }
}'
```

We get an error
`{"code":"Error","message":"Invalid end of input. Input: [\u003cquestion\u003e \u003ctext\u003e \"Line 1]"}`
It takes `\` as end of input.

I think the parser logic needs to be modified a bit to accept tabs and newlines.

**Comment by pawanrawal** [comment]
Ok looks like https://github.com/dgraph-io/dgraph/blob/master/cmd/dgraph/main.go#L118 is where the issue is. We split mutations by `\n` and hence the issue. I think we'd have to modify the code here to not split by the `\n` within a object value. Will send a fix.

**Comment by manishrjain** [comment]
But, that's by definition of RDF NQuad.

> However, as only the STRING_LITERAL_QUOTE production is allowed new lines in literals must be escaped.
https://www.w3.org/TR/n-quads/#grammar-production-STRING_LITERAL_QUOTE

**Comment by pawanrawal** [comment]
Escaping newline works. Closing this.
