### ISSUE TITLE
Dgraph on The Changelog!

### ISSUE THREAD

**Issue by jerodsanto** [dgraph-io/dgraph#2661]
Howdy from [The Changelog](https://changelog.com/podcast)!

_(Never heard of The Changelog? We've been interviewing the hackers, leaders, and innovators of software development since '09.)_

[Our listeners have suggested](https://github.com/thechangelog/ping/issues/833#issuecomment-429201474) we have @manishrjain on the show sometime soon. Interested?

Please email jerod@changelog.com to coordinate. 

Looking forward to it! 💚

**Comment by manishrjain** [comment]
Finished the interview last Friday. Thanks for having me, @jerodsanto !  Looking forward to the podcast release.

**Comment by jerodsanto** [comment]
This episode is now live! Listen here: https://changelog.com/podcast/322

💚💚💚
