### ISSUE TITLE
Investigate '@' in predicate names

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/dgraph#2664]
`/alter` does not allow creating or modifying predicates with character '@' in the name.
But the reason it isn't allowed is `/alter` parser produces a syntax error.

We need to investigate what's happening when a predicate `foo@bar` is submitted via `/mutate` and also through RDF.
And write unit tests once we understand current state.

Ideally we want to reserve `@` as a language separator, but it's unclear whether existing users had a way to create data with this character.

**Comment by srfrog** [comment]
I'm thinking maybe part of the reason is that it would be difficult to query. e.g.,
```
{
  q(func: uid(0x01)) {
    name@fr
    horse@rider
  }
}
```
perhaps if we url-encode them ? we'll need to let the user know the way to query is using the encoding. e.g.,
```
{
  q(func: uid(0x01)) {
    name@fr
    horse%40rider
  }
}
```

**Comment by paulftw** [comment]
@sfrog Our query language supports `<predicate:with//weird@chars>` but I doubt it's a well known feature.

**Comment by paulftw** [comment]
Few more experiments:

Mutation
```
{
  set {
    <0x07> <foo@bar> "foo@bar @lang en"@en .
    <0x07> <foo@bar> "foo@bar @lang ru"@ru .
    <0x07> <foo@bar> "foo@bar @lang wtf"@wtf .
    <0x07> <foo@bar> "foo@bar no lang" .
    <0x07> <foo> "foo @lang bar"@bar .
    <0x07> <foo> "foo no lang" .
    <0x07> <foo@bar@wtf> "foo@bar@wtf @lang wtf2"@wtf2 .
  }
}
```
Gets accepted, and data can be read back using `expand(_all_)`:
```
{
  node(func: uid(0x7)) {
    uid
    foo
    <foo@bar>
    <foo@bar@en>
    <foo@bar@wtf>
  }

  
  nodeExpandAll(func: uid(0x7)) {
    uid
    expand(_all_)
  }
}
```
**Response:**
```
{
  "data": {
    "node": [
      {
        "uid": "0x7",
        "foo": "foo no lang",
        "foo@bar": "foo@bar no lang"
      }
    ],
    "nodeExpandAll": [
      {
        "uid": "0x7",
        "foo@bar@en": "foo@bar @lang en",
        "foo@bar@ru": "foo@bar @lang ru",
        "foo@bar@wtf": "foo@bar @lang wtf",
        "foo@bar": [
          "foo@bar no lang",
          "foo @lang bar"
        ],
        "foo": "foo no lang",
        "foo@bar@wtf@wtf2": "foo@bar@wtf @lang wtf2"
      }
    ]
  },...
```

Note how <foo@bar> and <foo>@bar get consolidated in JSON of expand(_all_) but not when fetching <foo@bar> explicitly.

**Comment by paulftw** [comment]
While /alter with
```
foo@bar: string @lang .
```
results in a error message "Missing colon" it is possible to modify properties of a predicate with at-symbol: 
```
<foo@bar>: string @lang .
```
is accepted by Dgraph.
After some `/alter`'s and `/mutate`'s it's possible to do stuff like:
```
{
  node(func: uid(0x7)) {
    <foo@bar>@wtf
    <foo@bar@wtf>
  }

  nodeExpandAll(func: uid(0x7)) {
    expand(_all_)
  }
}
```

Response: 
```
{
  "data": {
    "node": [
      {
        "foo@bar@wtf": [
          "foo@bar @lang wtf",
          "foo@bar@wtf no lang"
        ],
        "uid": "0x7"
      }
    ],
    "nodeExpandAll": [
      {
        "foo@bar@en": "foo@bar @lang en",
        "foo@bar@ru": "foo@bar @lang ru",
        "foo@bar@wtf": "foo@bar@wtf no lang",
        "foo@bar": [
          "foo@bar no lang",
          "foo @lang bar"
        ],
        "foo": "foo no lang",
        "foo@bar@wtf@wtf2": "foo@bar@wtf @lang wtf2",
        "uid": "0x7"
      }
    ]
  },...
```

Note how foo@bar@wtf has two values when explicitly specified, but only one with `expand(_all_)`.
Value "foo@bar @lang wtf" becomes "invisible".

**Comment by paulftw** [comment]
By far the most interesting result I've found is the query:
```
{
  node(func: uid(0x7)) {
    <foo@bar>@wtf
    <foo@bar@wtf>
  }

  node2(func: uid(0x7)) {
    <foo@bar>@wtf
    <foo@bar@wtf>
    <foo@bar>@.
  }

  node3(func: uid(0x7)) {
    <foo@bar>@wtf
    <foo@bar>@.
    <foo@bar@wtf>
  }
}
```

Adding extra predicate to a query should produce same or larger response, and results of one field should not depend on other things requested in sibling lines. However, requesting more predicates can produce less data, and the exact result depends on the order of requested predicates:


```
"data": {
    "node": [
      {
        "foo@bar@wtf": [
          "foo@bar @lang wtf",
          "foo@bar@wtf no lang"
        ],
        "uid": "0x7"
      }
    ],
    "node2": [
      {
        "foo@bar@wtf": [
          "foo@bar @lang wtf",
          "foo@bar@wtf no lang"
        ],
        "foo@bar@.": "foo@bar no lang",
        "uid": "0x7"
      }
    ],
    "node3": [
      {
        "foo@bar@wtf": "foo@bar@wtf no lang",
        "foo@bar@.": "foo@bar no lang",
        "uid": "0x7"
      }
    ]
  },...
```

Note how node3 loses one value from the array, and that array becomes a scalar. This only happens when `<foo@bar>@.` is the second property requested, neither placing it first nor third causes this side effect.

**Comment by srfrog** [comment]
@paulftw thanks for the thorough testing, PR #2679 should fix this.
Predicates should not have '@' but languages directives must be handled.
