### ISSUE TITLE
Error while applying txn status to disk

### ISSUE THREAD

**Issue by sdwlig** [dgraph-io/dgraph#2680]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.9-rc4

- Have you tried reproducing the issue with latest release?
Yes.

- What is the hardware spec (RAM, OS)?
4GB VM, Ubuntu

- Steps to reproduce the issue (command/config used to run Dgraph).
dgraph server --bindall --lru_mb=2048 --port_offset=0 --zero zero${bn}:5080 --my=dgraph${bn}:7080 --idx 1

- Expected behaviour and actual result.
Database starts normally, applies transactions or discards them.
Actual: Database won't start fully because it keeps retrying the same operation many times per second:
2018/10/19 03:07:38 draft.go:446: Error while applying txn status to disk (304251 -> 304252): Key with size 72716 exceeded 65528 limit. Key:
00000000  00 00 08 63 6d 70 5f 64  61 74 61 02 02 7b 22 66  |...cmp_data..{"f|
00000010  6c 6f 6f 72 70 6c 61 6e  22 3a 7b 22 63 6f 72 6e  |loorplan":{"corn|
00000020  65 72 73 22 3a 7b 22 66  39 30 64 61 35 65 33 2d  |ers":{"f90da5e3-|
00000030  39 65 30 65 2d 65 62 61  37 2d 31 37 33 64 2d 65  |9e0e-eba7-173d-e|
...

Can't see any options to discard pending transaction.  Trying to update schema to solve this, but database is never available.  Only apparent option is to delete all data and start over which is not acceptable, and now the database server is unusable.  Checked with badger tools: no obvious way to fix things at that level.

**Comment by sdwlig** [comment]
To reproduce:
Create a schema like:
mode: string @index(exact) @upsert .

Insert data with a value for mode that is larger than 65528, commit.

**Comment by sdwlig** [comment]
I've removed indexing and upsert from predicates that may be large amounts of data, but I cannot restart the database to continue.

**Comment by manishrjain** [comment]
By default, we try infinitely to apply a committed txn, which is generally the right thing to do. However, in this case, we are stuck with a permanent failure. So, need to give up after some number of tries configurable by the user, or understand that it is indeed a permanent failure.
