### ISSUE TITLE
dgraph alpha does not work ... should be server?

### ISSUE THREAD

**Issue by sonear** [dgraph-io/dgraph#2682]
* Doc page: [get-started/index.md](https://docs.dgraph.io/get-started/)
* Doc version: `master`

the command noted throughout the Install page and noted within the docker-compose.yml says

command: dgraph **alpha** --my=server:7080 --lru_mb=2048 --zero=zero:5080

but this results in an error

**server_1  | unknown command "alpha" for "dgraph"**
server_1  | Error: unknown command "alpha" for "dgraph"
server_1  | Run 'dgraph --help' for usage.

According to dgraph help page, alpha is not an available command, but server is.

Usage:
  dgraph [command]

Available Commands:
  bulk        Run Dgraph bulk loader
  cert        Dgraph TLS certificate management
  debug       Debug Dgraph instance
  help        Help about any command
  live        Run Dgraph live loader
  **server      Run Dgraph data server**
  version     Prints the dgraph version details
  zero        Run Dgraph zero server

if I change to "server" it works fine

command: dgraph **server** --my=server:7080 --lru_mb=2048 --zero=zero:5080

then re-run docker-compose
docker-compose up -d
dgraph_zero_1 is up-to-date
Recreating dgraph_server_1 ... 
Recreating dgraph_server_1 ... done

and check logs
server_1  | 2018/10/19 22:38:57 gRPC server started.  Listening on port 9080
server_1  | 2018/10/19 22:38:57 HTTP server started.  Listening on port 8080
server_1  | 2018/10/19 22:38:57 groups.go:80: Current Raft Id: 0
server_1  | 2018/10/19 22:38:57 worker.go:85: Worker listening at address: [::]:7080
server_1  | 2018/10/19 22:38:57 pool.go:108: == CONNECTED ==> Setting zero:5080

all seems well.

Thanks

**Comment by manishrjain** [comment]
Please look at the documentation corresponding to the release you're using, i.e. v1.0.9. The changes are being made in master, and these are breaking changes. So, the docs won't be relevant for the latest release.
