### ISSUE TITLE
did dgraph server support failover

### ISSUE THREAD

**Issue by aigod** [dgraph-io/dgraph#2691]
i just install a dgraph cluster,  with three zero instances and three server instances。every server instance start with the same zero node address, 

dgraph server --my=192.168.8.106:7080 --lru_mb=2048 --zero=192.168.8.106:5080
dgraph server --my=192.168.8.230:7080 --lru_mb=2048 --zero=192.168.8.106:5080
dgraph server --my=192.168.8.231:7080 --lru_mb=2048 --zero=192.168.8.106:5080

when zero 192.168.8.106:5080 goes down, the cluster crashed, and could not be used,   i try to set --zero with three zero address seperated by comma, it did not work and throw errors。

it seems that the cluster do not support failover？

**Comment by manishrjain** [comment]
If a Zero goes down, the server shouldn't crash -- they're not dependent of each other like that. However, if a server was restarting and the zero in its flag was down, then it doesn't know who to talk to. So, when the server goes down, you need to give it the address of one healthy and alive zero.

**Comment by aigod** [comment]
@manishrjain  
hi, when i manully killed the Zero 192.168.8.106:5080, then all three server instances  throw the following error, and could not perform query in ratel ui.

2018/10/23 22:53:47 groups.go:726: Error while calling Oracle rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.8.106:5080: connect: connection refused"

so, did i need to kill all server and then give them a alive Zero to restart? I think it should automatically search a alive Zero to be more smarter.

**Comment by aigod** [comment]
@manishrjain

sorry, i did not config --peer when start Zero, now it works. thx.
