### ISSUE TITLE
query with shortest does not work

### ISSUE THREAD

**Issue by gitlw** [dgraph-io/dgraph#2709]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.10-rc1-25-g3897db23

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
8G, Fedora Linux

- Steps to reproduce the issue (command/config used to run Dgraph).
Following the steps in the doc https://docs.dgraph.io/query-language/#k-shortest-path-queries gives empty response. Using the ids of 0x1 for Alice, and 0x4 for Mallory does not help either.

- Expected behaviour and actual result.
Expected to see the response shown in the doc
`{
  "data": {
    "path": [
      {
        "name": "Alice"
      },
      {
        "name": "Mallory"
      }
    ],
    "_path_": [
      {
        "uid": "0x2",
        "friend": [
          {
            "uid": "0x5"
          }
        ]
      }
    ]
  }
}
`

**Comment by danielmai** [comment]
Did you use the UIDs that were set in your own cluster?

**Comment by gitlw** [comment]
Sorry about the false alarm. It's working now.
