### ISSUE TITLE
Regexp is not working in edge facets

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#2712]
dgraph 1.0.9

since edge facets use simple filters for eq and others instead of index lookups, so it should apply simple regexp filter. but it doesn't work actually.

```
_:node <entity_key> "entity1" .
_:node <attrs> _:node (name="Nikita") .

{
	get_entity(func: eq(entity_key, "entity1")) @cascade {
		uid
		attrs @facets(regexp(name, /Nikita/))
	}
}

{
    "errors": [
        {
            "code": "ErrorInvalidRequest",
            "message": ": One argument expected in regexp, but got 2."
        }
    ],
    "data": null
}
```

**Comment by MichelDiz** [comment]
Sorry, regexp is not supported with facets. In order to use regular expressions you need indexing. And Facets can't be indexed. 

Also such feature if predicted should be documented. So it is preferable that such questions be asked in the Community Discuss. Even opening up a possibility is interesting to start there. Due discussion matter.

Cheers.

**Comment by makitka2007** [comment]
> regexp is not supported with facets
i know, that's why I created this issue. `eq` root filter needs index as well, but for facets it works just as filter without index lookups. go language already has `regexp` function, why just not use it for filtering on edge facets?

**Comment by MichelDiz** [comment]
Is different. EQ for query function do need indexing due massive usage. But EQ in facets is another approach. As the Facets are much more simpler to deal. I believe that Dgraph does a Tokenizer on the fly. So, do a Tokenizer for regexp, on the fly, could be expensive. 

But I'm not a Dev here what I'm saying is based in what I have notion, so calling the authority @srfrog to what he has to say about it.

**Comment by makitka2007** [comment]
there is a ready `regexp` package in go, there is no need in tokens or something else, just filter my match function
