### ISSUE TITLE
Fetching a non-existent node returns the fetched uid rather than an empty result

### ISSUE THREAD

**Issue by gorjuspixels** [dgraph-io/dgraph#2715]
**If you suspect this could be a bug, follow the template.**

**- What version of Dgraph are you using?**
v1.0.9

**- Have you tried reproducing the issue with latest release?**
I've upgraded to v1.0.9 from v1.0.9-rc5. Both have the issue, but i haven't tried v1.0.10-rc1.

**- What is the hardware spec (RAM, OS)?**
RAM: 5gb
GKE: 1.10.7-gke.2
OS: Container-Optimised OS

**- Steps to reproduce the issue (command/config used to run Dgraph).**

Just run a uid query on an non-existing node.

Works as expected:
```
{
  something(func: uid(0x10000524)) {
    expand(_all_)
  }
}
```

When I add `uid` (with or without `expand(_all_)`), it returns the uid back:
```
{
  something(func: uid(0x10000524)) {
    uid
    expand(_all_)
  }
}
```

**- Expected behaviour and actual result.**

Expected result is an empty array, like it does in the first query:
```
{
  "data": {
    "something": []
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 35725,
      "processing_ns": 10055340,
      "encoding_ns": 1167598
    },
    "txn": {
      "start_ts": 150040
    }
  }
}
```

Actual result is the uid of non-existent node:
```
{
  "data": {
    "something": [
      {
        "uid": "0x10000524"
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 13144,
      "processing_ns": 14520675,
      "encoding_ns": 816140
    },
    "txn": {
      "start_ts": 150008
    }
  }
}
```

**Comment by MichelDiz** [comment]
Hi,
This is an expected behavior. If you need the answer to be empty, just do not query the UID.

BTW, This type of question can be addressed directly to the community in Discuss. http://discuss.dgraph.io

Cheers.

**Comment by gorjuspixels** [comment]
@MichelDiz When querying a node, we need the uid and a few other predicates. So we usually don't use `expand(_all_)`. And thanks for the link, i'll go there

**Comment by MichelDiz** [comment]
You can use like this to get empty returns (different from empty array):
```
{
  something(func: uid(0x10000524)) @filter(has(myPredicate)) {
    uid
    expand(_all_)
  }
}
```
