### ISSUE TITLE
"How Dgraph Search Works" Chapter is not work.

### ISSUE THREAD

**Issue by syossan27** [dgraph-io/dgraph#2723]
I was reading the hoge, but there was a chapter in which the code did not work.

Chapter: How Dgraph Search Works（https://tour.dgraph.io/basic/11/ ）

Code:
```
{
  lots_of_friends(func: ge(count(friend), 2)) @filter(ge(age, 20) AND lt(age, 30)) {
    name@.
    age
    friend {
        name@.
    }
  }
}
```

Response:

```
{
  "errors": [
    {
      "code": "ErrorInvalidRequest",
      "message": ": Need @count directive in schema for attr: friend for fn: ge at root"
    }
  ],
  "data": null
}
```

**Comment by MichelDiz** [comment]
Did you skipped this part? https://tour.dgraph.io/intro/3/

You need to run 
`friend: uid @count .`

Please, when a possible issue or suggestion of the type you have. Head it to the appropriate Repo or open a discussion in http://discuss.dgraph.io

The Tour Repo is https://github.com/dgraph-io/tutorial/

Cheers.
