### ISSUE TITLE
Make database upgrade easier

### ISSUE THREAD

**Issue by Scapal** [dgraph-io/dgraph#2728]
Upgrading a Dgraph cluster is currently cumbersome: dump, erase, bulk-import.

Would it be possible to include an automated database upgrade when starting the server? It would be much easier to update a Dgraph cluster running in orchestrated containers to a newer version.

First you would have to detect the database version, report incompatible storage, migrate if possible or propose to run an intermediate version first if it is too old.

I just hate having to put a "Under Maintenance" page.

**Comment by manishrjain** [comment]
We intend to make Dgraph upgrades easier by avoiding data layer breaking changes; so one could just restart the servers without any issues. But, it is not always possible, and therefore, requires data export and reimport.

If data reimport is required, then that's not something we can automate. Only the maintainer of the DB knows the environment it is running in, and when can it be down for an upgrade, etc.

**Comment by Scapal** [comment]
Could those breaking changes be reflected in the versioning and release notes?

**Comment by manishrjain** [comment]
We always (try and) mention them in the release notes. I noticed that we hadn't in this release, and updated the notes to reflect that.

Once we're past v1.1 release, we'll ensure that every breaking change would be a new v1.x release and tagged accordingly.
