### ISSUE TITLE
Issue found by new nilness vet check

### ISSUE THREAD

**Issue by dgryski** [dgraph-io/dgraph#2757]
Playing with the new `vet`, I found the following issue:

```
$ vet ./...
/Users/dgryski/go/src/github.com/dgraph-io/dgraph/query/query.go:544:16: impossible condition: nil != nil
```

The line is https://github.com/dgraph-io/dgraph/blob/master/query/query.go#L544 , and `facetsNode` has not been assigned a value between declaration on line 384 and the if test, so it's always nil.

**Comment by srfrog** [comment]
Hi, which new vet is this? We use the vet tool that comes with Go.

**Comment by dgryski** [comment]
It was just merged into master.

https://go-review.googlesource.com/c/go/+/149609/

**Comment by manishrjain** [comment]
Thanks for catching this, @dgryski ! Seems like a bug at our end.
