### ISSUE TITLE
After loading data with dgraph bulk , alloftext query(@lang @zh) no result

### ISSUE THREAD

**Issue by coralzu** [dgraph-io/dgraph#2775]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
   v1.0.10

- Have you tried reproducing the issue with latest release?
   yes

- What is the hardware spec (RAM, OS)?
   8GB ,  windows 10

- Steps to reproduce the issue (command/config used to run Dgraph).
 startup dgraph  
```
dgraph zero --my=localhost:5080 
dgraph alpha --lru_mb 1024 --badger.tables disk --my=localhost:7080 --zero=localhost:5080
```

add Schema
```
<name>: string @index(fulltext, term) @lang @upsert .
```

run a mutate
```
{
   set{
     _:1 <name> "Nantou Road"@en .
     _:2 <name> "南头路"@zh .
   }
}
```

now run a query with 
```
{
  A as var(func:alloftext(name@en,"Nantou")){
    uid
  }
  B as var(func:alloftext(name@zh,"南头")){
    uid
  } 
  body(func:uid(A,B)){
    name@en  name@zh 
  }
}
```
return 2 results 
![qq 20181126132044](https://user-images.githubusercontent.com/45164615/48994412-2264ba00-f17e-11e8-869f-36e41cf34ed2.png)

export dgraph 
```
localhost:8080/admin/export 
```
then use dgraph bulk to load the export file to a new dgraph 
```
dgraph bulk -r c:\Users\admin\Desktop\g01.rdf.gz -s c:\Users\admin\Desktop\g01.schema.gz --http localhost:8000 --zero=localhost:5080
```

startup dgraph from out
```
dgraph alpha --lru_mb 1024 --badger.tables disk --my=localhost:7080 --zero=localhost:5080 -p=out/0/p
```

Run the above query again , now only return 1 result
![222](https://user-images.githubusercontent.com/45164615/48994729-b71be780-f17f-11e8-91c3-1123f36534b9.png)

- Expected behaviour and actual result.
After dgraph bulk , Query returns the same value as before.
In the above example , data with @en is correct , but data using @zh undergo changes .
If suspect this could be a bug ,  Are you considering fixing him in a version?

**Comment by codexnull** [comment]
Fixed in next release.
