### ISSUE TITLE
feature: timestamping updates

### ISSUE THREAD

**Issue by glycerine** [dgraph-io/dgraph#2814]
Suppose I'm making a predicate `lastUpdateTimestamp` for my nodes. I would like a way to get `time.Now()` from a server to populate the predicate, automatically.  I'm thinking of the MySQL `ON UPDATE CURRENT_TIMESTAMP` where the server autofills the timestamp on update and the client-side clocks don't have to be accurate.

The use case here is the ability to read back all updates to a set of timestamped nodes in chronological order.  Desirable: to have the updated timestamps applied as efficiently and as automatically as possible. We don't want to depend on having the client clock be correct or very synchronized with the server's clock.  On the other hand, it doesn't need to be linearizable, but if we can piggy back on the existing linearizable infrastructure, that would be great.

An audit log would be a typical example.  That's a record trail for auditors to determine the exact sequence of changes: when and by whom.  Corresponding to this, it would be useful to have immutable predicates--to designate the creationTime of the predicate, so that matching creation and update time indicates that the audit trail has not been tampered with.  But that can certainly be a separate feature if need be.

**Comment by srfrog** [comment]
This sounds like a new feature that might be accomplished by extending facets. I think you should take this to discuss and see if other users find it useful. We don't have triggers now but we would need a general solution to build it as a feature. Immutable predicates sounds like a complete separate feature on its own.

**Comment by glycerine** [comment]
@srfrog Okay. I'm unfamiliar with discuss or its protocols.

**Comment by srfrog** [comment]
Our discuss/forum - https://discuss.dgraph.io
We use it discuss community-led features.
