### ISSUE TITLE
Not able to mutate data for existing note- Same query used to work fine earlier

### ISSUE THREAD

**Issue by neetikh** [dgraph-io/dgraph#2819]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://discuss.dgraph.io
Our Docs: https://docs.dgraph.io/
Slack Channel: https://slack.dgraph.io/

**Comment by danielmai** [comment]
Please post your question with more details at https://discuss.dgraph.io.

Helpful details include:
- Dgraph version
- What you tried to do
- What you expected to happen

**Comment by neetikh** [comment]
Hello Daniel,

I was trying to add integar value using mutate through UI.
Later I tried putting as string and it worked.

Thanks for your help!!

**Comment by danielmai** [comment]
@neetikh Glad you were able to answer your question.
