### ISSUE TITLE
Cannot query with argument valued "uid"

### ISSUE THREAD

**Issue by ArroyoAndre** [dgraph-io/dgraph#2827]
I'm using DGraph version 1.0.10

I have a schema with a predicate
`name: string @index(hash) @upsert .`

I have a node with name `"uid"` (a string).

When trying to search for that node using the index `name`:
```
{
    all(func: eq(name, "uid")) {
        uid
    }
}
```

I get an error:
```
{
  "errors": [
    {
      "code": "ErrorInvalidRequest",
      "message": "Argument cannot be \"uid\""
    }
  ],
  "data": null
}
```

**Comment by manishrjain** [comment]
@srfrog : Can you look into this?

**Comment by srfrog** [comment]
The code explicitly forbids a value of "uid", I'm trying to figure out why. Running some tests to find out.
