### ISSUE TITLE
Improve tokenization system

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#2828]
### What you wanted to do

Edit Schema types individually. Without the need to rebuild the whole index. So do it fast.

### What you actually did

1 - I had Schema ready, but needed to do a small change. So Dgraph dels and Rebuild all the tokenizers for that predicate.
```
#first attempt to edit:
I1217 23:06:34.624562    3305 index.go:33] Deleting index for name
I1217 23:06:35.809157    3305 index.go:38] Rebuilding index for name
```
2 - Later on I had a new change to do

```
#second attempt to edit:
I1217 23:12:43.390573    3305 server.go:321] Got schema: [predicate:"name" value_type:STRING directive:INDEX tokenizer:"term" tokenizer:"fulltext" tokenizer:"trigram" tokenizer:"hash" lang:true ]
I1217 23:12:43.392417    3305 index.go:33] Deleting index for name
I1217 23:12:45.014687    3305 index.go:38] Rebuilding index for name
```

So, the tokenization system need a refactoring to do efficient changes.

"Our current tokenization system invokes all the tokenizers for the predicate, instead of a specific one. Hence, they all must be recreated." mrjn

**Comment by martinmr** [comment]
PR #2883 addresses this issue.
