### ISSUE TITLE
Update LICENSE.md to match the Apache 2.0 license announced in blog post

### ISSUE THREAD

**Issue by mbrukman** [dgraph-io/dgraph#2840]
[A recent Dgraph blog post][blog-relicense] says:

> Update (Nov 2018): This post is outdated. Dgraph core is [back to][commit-license] Apache 2.0, with no restrictions.

and I see that the referenced commit made a lot of the licensing changes (thanks!). However, the [current version of `LICENSE.md`][license] says:

> Source code in this repository is variously licensed under the Apache Public License 2.0 (APL) and the Dgraph Community License (DCL). A copy of each license can be found in the licenses directory.

And we can see that the [`licenses` directory][licenses-dir] does, in fact, contain both licenses, which is confusing. Perhaps this was just missed in the large update?

Would it make sense to replace `LICENSE.md` with just a `LICENSE.txt` which is simply a copy of the [Apache 2.0 License][apache-2.0]? As it is, the main license file in the repo still refers to a non-Apache license, which conflicts with the updates in the source files. Then, the `licenses` directory can be simply removed to avoid further confusion.

Besides clarity for developers, another value of having a standard license file in the standard location (i.e., top of the repo) is that GitHub will automatically show the name of that license so that it's clear to anyone what the license is, without having to check the license file — see [this blog post][github-license] for more info. Without that marker, visitors to this repo just get a "view license" link that points to `LICENSE.md`which they (or their lawyers) have to understand and interpret.

Thanks for all your hard work on this!

[license]: https://github.com/dgraph-io/dgraph/blob/0ce513e9928b5b97d6f8503b992e9ed341048ef1/LICENSE.md
[blog-relicense]: https://blog.dgraph.io/post/relicensing-dgraph/
[commit-license]: https://github.com/dgraph-io/dgraph/commit/3d0b2cd84f04b263f6c5128e682a63be8dcb220d
[apache-2.0]: https://www.apache.org/licenses/LICENSE-2.0.txt
[github-license]: https://blog.github.com/2016-09-21-license-now-displayed-on-repository-overview/
[licenses-dir]: https://github.com/dgraph-io/dgraph/tree/0ce513e9928b5b97d6f8503b992e9ed341048ef1/licenses

**Comment by manishrjain** [comment]
The Dgraph Community License (DCL) encapsulates the open source code, under Apache 2.0 license now. The proprietary code is under the DCL and it is colocated with the open source code. That's why we have both the licenses there. Each code file mentions which license it is under.

We can't make LICENSE.txt/md only mention one license and not the other. That's why we use the current structure. In other words, the entire codebase is NOT under just one license.

**Comment by mbrukman** [comment]
[Searching for `dcl` in the repo][search-dcl], looks like what's covered under DCL are:

* files in the `ee/` directory
* some files, which appear to have `_ee` suffix
* ... maybe I missed something else?

Maybe this can be clarified in the README or LICENSE files? Otherwise, it's a bit disconcerting to not know which parts of the repo are under which license, and the blog post seems to imply that the entire repo is under Apache 2.0 license, which it's not.

E.g., see what [Neo4j does][neo4j]:

> This GitHub repository contains mixed GPL and AGPL code. Our Community edition (in the `community/` directory) is GPLv3. Our Enterprise edition (`enterprise/`) is differently licensed under the AGPLv3.

Directory-based separation is clear and simple; using a naming pattern for files to distinguish licensing is a bit confusing, as you don't know if you're depending on such a file transitively or not.

[search-dcl]: https://github.com/dgraph-io/dgraph/search?p=2&q=dcl&unscoped_q=dcl
[neo4j]: https://github.com/neo4j/neo4j/#extending-neo4j

**Comment by manishrjain** [comment]
We are using Go build flags to optionally not include enterprise features. So, if you want a pure open source version of Dgraph, you can run make oss.

We don't intend to separate out proprietary code in another repo. It's also hard to always keep the directory separation, but we try. All files mention the license they are under.
