### ISSUE TITLE
Dgraph-ratel crashes with a blank screen when clicking on an edge with a Facet

### ISSUE THREAD

**Issue by henrymontagu** [dgraph-io/dgraph#2847]
When I am trying to click on edge that has a facet, the UI v1.0.10 crashes and turns to a white screen. I have attached a screen shot of the brower and the error printed by the console is below. Any help on solving this issue will be highly appreciated ?

TypeError: "i is undefined"
	r https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:1267573
	r https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:1267519
	Rn https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:644941
	n https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:658757
	Zn https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:659138
	yr https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:665662
	mr https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:665042
	dr https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:664071
	or https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:663130
	enqueueSetState https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:693462
	setState https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:598934
	handleNodeSelected https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:1221780
	configNetwork https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:1264397
	r https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:708791
console.js:35
i/e[t]
console.js:35
jn
react-dom.production.min.js:179:186
qn/n.callback
react-dom.production.min.js:190:351
Jt
react-dom.production.min.js:128:451
Xt
react-dom.production.min.js:128:248
br
react-dom.production.min.js:229:439
yr
react-dom.production.min.js:220:232
mr
react-dom.production.min.js:219:142
dr
react-dom.production.min.js:216:195
or
react-dom.production.min.js:214:27
enqueueSetState
react-dom.production.min.js:134:227
o.prototype.setState
react.production.min.js:13:210
t/n.handleNodeSelected
FrameItem.js:250:12
t/n.configNetwork/</<
GraphContainer.js:137:24
r
raven.js:376
TypeError: i is undefined[Learn More] NodeProperties.js:71:32
r/<
NodeProperties.js:71:32
map self-hosted:286:17 r
NodeProperties.js:69:45
Rn
react-dom.production.min.js:168:101
$n
react-dom.production.min.js:204:15
Zn
react-dom.production.min.js:205:270
yr
react-dom.production.min.js:220:232
mr
react-dom.production.min.js:219:142
dr
react-dom.production.min.js:216:195
or
react-dom.production.min.js:214:27
enqueueSetState
react-dom.production.min.js:134:227
o.prototype.setState
react.production.min.js:13:210
t/n.handleNodeSelected
FrameItem.js:250:12
t/n.configNetwork/</<
GraphContainer.js:137:24
r
raven.js:376

**Comment by henrymontagu** [comment]
![screen shot 2018-12-27 at 10 32 36 am](https://user-images.githubusercontent.com/34367742/50469888-e3699480-09c7-11e9-9062-4ad033b85775.png)

**Comment by MichelDiz** [comment]
Please use just one repo to report anything.
I see that you already did the same post there https://github.com/dgraph-io/ratel/issues/49

Cheers.
