### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by selmeci** [dgraph-io/dgraph#2849]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.11

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?
AWS EC2 r5d.2xlarge, 64GB RAM, SSD disk.

- Steps to reproduce the issue (command/config used to run Dgraph).
It looks same as already reported bug in this [issue](https://github.com/dgraph-io/dgraph/issues/913).
Here is [logs](https://bitbucket.org/snippets/edocu/Leaq6o) from alpha.

- Expected behaviour and actual result.
Alpha does not crush.

**Comment by manishrjain** [comment]
The other issue is a different one. This is caused by some optimizations I made, allowing processing a particular section of the query concurrently.

**Comment by selmeci** [comment]
Any ETA for hotfix at least in master branch? Right now alpha is really unstable because I can not predict which query will crush. Unfortunately we are already launched dGraph in production environment.

**Comment by manishrjain** [comment]
Can you build a binary from `mrjn/concurrent-facet` branch? I pushed a change which I think should solve this issue. Let me know if it works, and I'll push it to master.

**Comment by selmeci** [comment]
Thanks for quick response! I built docker image with this dockerfile:
```dockerfile
FROM golang

RUN mkdir -p /dgraph/plugins
COPY tokenizer/nfd.go /dgraph/plugins
# build dgraph
RUN \
    go get -v github.com/dgraph-io/dgraph/dgraph && \
    cd /go/src/github.com/dgraph-io/dgraph/ && \
    git fetch --all --tags --prune && \
    git checkout mrjn/concurrent-facet && \
    cd dgraph/ && \
    go build && \
    chmod a+x dgraph && \
    mv dgraph /usr/local/bin/dgraph && \
    cd /dgraph/plugins && \
    go build -buildmode=plugin -o nfd.so ./nfd.go && \
    rm ./nfd.go && \
    rm -r /go/src/*

EXPOSE 9080
EXPOSE 8080
EXPOSE 6080
EXPOSE 5080

VOLUME /dgraph

WORKDIR /dgraph
```

Alpha is stable and does not stop with `fatal error: concurrent map writes` but it stop with OOM - consume 16GB of RAM. I had to switch back to v1.0.10 where everything is working - same script finish withi no OOM and no concurrent error.

**Comment by selmeci** [comment]
I have already reported possible OOM issue with profiles in discuss topic https://discuss.dgraph.io/t/is-there-oom-issue-in-v1-0-11/3792
