### ISSUE TITLE
alpha globals flag "--log_dir" in config.json is inoperative

### ISSUE THREAD

**Issue by relunctance** [dgraph-io/dgraph#2854]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
```
Dgraph version   : v1.0.11-18-g4ca67ca
Commit SHA-1     : 4ca67ca
Commit timestamp : 2018-12-24 18:53:10 -0800
Branch           : master
Go version       : go1.11
```
- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?
64G

- Steps to reproduce the issue (command/config used to run Dgraph).
-- cmd:
```
dgraph alpha --config /home/s/dgraph/conf/alpha.json
```
--alpha.json
```json
{
   ... 
   "log_dir": "/home/s/dgraph/logs"
   ... 
}
```

- Expected behaviour and actual result.
In this scene , expect all logs are writed "/home/s/dgraph/logs"  instead of  "/tmp" . 

```
log: exiting because of error: write /tmp/dgraph.dg.s.log.INFO.20181227-133013.23000: no space left on device
```

**Comment by danielmai** [comment]
Although it’s not obvious, this is the expected behavior. The log flags like `log_dir` are handled by the glog library and are only configurable as command line flags and not via config files.

To prevent log files from being written and only writing to stderr, you can use the `--logtostderr` flag.
