### ISSUE TITLE
Poor performance handling nodes with lots of outgoing edges

### ISSUE THREAD

**Issue by vincent-163** [dgraph-io/dgraph#2855]
## Experience Report

Note: Feature requests are judged based on user experience and modeled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### What you wanted to do
Efficient query/mutation on large nodes with lots of outgoing edges/reverse edges. For example, my application wants to maintain a list of "lists" that contain lots of items. The size of the list may vary from 0 to 1000000 items, though the total number of entries across all lists should be reasonable. Currently, a list is implemented as a node with lots of outgoing edges to items. But this is not very performant; every write to the list results in the whole list being read, changed, and rewritten to disk, and performance degrades when the list becomes large. A 2x larger list results in 2x slower writes.
Another use case is subscribe/publish. Even if I set limits on how many channels a single user can subscribe to, there can be a very large number of subscribers a single channel can have. This is modeled in Dgraph as reverse edges, but reverse edges are just as inefficient as normal edges, and gets slow as soon as node size increases.

### What you actually did
Seems like I have to create an exact index and abuse Dgraph as a key/value store.
Another solution is to create intermediate nodes, connecting to both the list node and the item node.  But Dgraph doesn't support indexs on uids, and converting it to int seems more of a hack. Also in my specific use case, every entry has a unique name in the list, and I need to be able to retrieve the item with the list and the name efficiently, which in other RDBMS can be implemented using a compound index on (list id, name).

### Why that wasn't great, with examples
As above.

**Comment by hewenyang** [comment]
I took a look at your article <https://blog.dgraph.io/post/scaling-dgraph/>. It seems to have mentioned the issue where a node could have too many outgoing edges, at which point re-encoding the list becomes slower and slower. Unfortunately, the story didn't have an ending. You created a bulk loader that loads things much faster (and it handles large nodes!), but the problem persists. It's not uncommon to see nodes that act like 'indexes', has many outgoing edges or reverse edges, and these nodes need to be updated and queried very quickly.

I created a simple test:
```python
with open("data.rdf","w") as f:
    for i in range(1, 100000):
        f.write("_:list <item> _:item%d (id=%d) .\n" % (i, i))``
```
The schema was:
```
item: uid @reverse .
```

I ran it and here are some lines: (My computer uses poor hdd and is slow, but the performance drops were significant)
```
I1230 16:38:55.312722    8890 init.go:88]

Dgraph version   :
Commit SHA-1     :
Commit timestamp :
Branch           :
Go version       : go1.11.4

For Dgraph official documentation, visit https://docs.dgraph.io.
For discussions about Dgraph     , visit https://discuss.dgraph.io.
To say hi to the community       , visit https://dgraph.slack.com.

Licensed variously under the Apache Public License 2.0 and Dgraph Community License.
Copyright 2015-2018 Dgraph Labs, Inc.


Creating temp client directory at /tmp/x386805971

Processing data.rdf
[    2s] Txns: 6 RDFs: 6000 RDFs/sec:  3000 Aborts: 0
[    4s] Txns: 11 RDFs: 11000 RDFs/sec:  2750 Aborts: 0
[    6s] Txns: 14 RDFs: 14000 RDFs/sec:  2333 Aborts: 0
[    8s] Txns: 17 RDFs: 17000 RDFs/sec:  2125 Aborts: 0
[   10s] Txns: 19 RDFs: 19000 RDFs/sec:  1900 Aborts: 0
[   12s] Txns: 21 RDFs: 21000 RDFs/sec:  1750 Aborts: 0
[   14s] Txns: 23 RDFs: 23000 RDFs/sec:  1643 Aborts: 0
[   16s] Txns: 24 RDFs: 24000 RDFs/sec:  1500 Aborts: 0
[   18s] Txns: 26 RDFs: 26000 RDFs/sec:  1444 Aborts: 0
[   20s] Txns: 27 RDFs: 27000 RDFs/sec:  1350 Aborts: 0
[   22s] Txns: 29 RDFs: 29000 RDFs/sec:  1318 Aborts: 0
[   24s] Txns: 30 RDFs: 30000 RDFs/sec:  1250 Aborts: 0
[   26s] Txns: 31 RDFs: 31000 RDFs/sec:  1192 Aborts: 0
[   28s] Txns: 32 RDFs: 32000 RDFs/sec:  1143 Aborts: 0
[   30s] Txns: 34 RDFs: 34000 RDFs/sec:  1133 Aborts: 0
[   32s] Txns: 35 RDFs: 35000 RDFs/sec:  1094 Aborts: 0
[   34s] Txns: 36 RDFs: 36000 RDFs/sec:  1059 Aborts: 0
[   36s] Txns: 37 RDFs: 37000 RDFs/sec:  1028 Aborts: 0
[   38s] Txns: 38 RDFs: 38000 RDFs/sec:  1000 Aborts: 0
[   40s] Txns: 39 RDFs: 39000 RDFs/sec:   975 Aborts: 0
[   42s] Txns: 40 RDFs: 40000 RDFs/sec:   952 Aborts: 0
[   44s] Txns: 40 RDFs: 40000 RDFs/sec:   909 Aborts: 0
[   46s] Txns: 41 RDFs: 41000 RDFs/sec:   891 Aborts: 0
[   48s] Txns: 42 RDFs: 42000 RDFs/sec:   875 Aborts: 0
[   50s] Txns: 43 RDFs: 43000 RDFs/sec:   860 Aborts: 0
[   52s] Txns: 44 RDFs: 44000 RDFs/sec:   846 Aborts: 0
[   54s] Txns: 45 RDFs: 45000 RDFs/sec:   833 Aborts: 0
[   56s] Txns: 46 RDFs: 46000 RDFs/sec:   821 Aborts: 0
[   58s] Txns: 46 RDFs: 46000 RDFs/sec:   793 Aborts: 0
[  1m0s] Txns: 47 RDFs: 47000 RDFs/sec:   783 Aborts: 0
...
[ 1m10s] Txns: 51 RDFs: 51000 RDFs/sec:   729 Aborts: 0
[ 1m20s] Txns: 54 RDFs: 54000 RDFs/sec:   675 Aborts: 0
[ 1m30s] Txns: 57 RDFs: 57000 RDFs/sec:   633 Aborts: 0
[ 1m40s] Txns: 60 RDFs: 60000 RDFs/sec:   600 Aborts: 0
[ 1m50s] Txns: 63 RDFs: 63000 RDFs/sec:   573 Aborts: 0
[ 2m20s] Txns: 70 RDFs: 70000 RDFs/sec:   500 Aborts: 0
[  3m6s] Txns: 80 RDFs: 80000 RDFs/sec:   430 Aborts: 0
[  4m2s] Txns: 90 RDFs: 90000 RDFs/sec:   372 Aborts: 0
[ 4m58s] Txns: 100 RDFs: 100000 RDFs/sec:   336 Aborts: 0
[ 8m14s] Txns: 148 RDFs: 148000 RDFs/sec:   300 Aborts: 0
[ 22m6s] Txns: 299 RDFs: 299000 RDFs/sec:   225 Aborts: 0
```
After 8 minutes of running the number of RDFs per second dropped from 3000 to 300. My computer doesn't have enough RAM to run the test further, but apparently the single large list was the problem (when I add edges in the other direction, i.e. from item to list, the performance would not drop).

The idea of avoiding disk seeks and reads, as mentioned in the article, is useful only if you often want to query *all* the edges of a given predicate. However, it's quite common that every node acts as an index in itself, where efficient random writes and lookups are required.
I would propose a special kind of predicate where a node is expected to have lots of outgoing edges. These would act effectively like compound indexes, where the first key is the starting node's UID, and the second key is the key for ordering, usually in facets.
So the schema might look like:
```
item uid @index_facet(name, exact)
```
And a query like this:
```
{
  list_item(func: uid(0x1)) {
    item @facets(eq(name, "1")) {
      uid
    }
  }
}
```
Would first look for the node 0x1, find the index associated with the node, look for the edge with facet `name="1"` with the index, then find its uid, without iterating through all the edges. Under the hood, an edge with name `1` might be stored as a key `item.0x1.index_name.1.0x2` in the k/v store, and the query may look for keys prefixed with `item.0x1.index_name.1`, etc. This will also allow for efficiently sorting by `name` and then paginate it.

**Comment by manishrjain** [comment]
I have ideas around doing binary splits on very long posting lists. But, how that improves performance isn't clear yet.

**Comment by srfrog** [comment]
Maybe a block-range index (BRIN) based on hash func? That's what Pg uses. Group rebalancing would affect the index, because it might have to get rebuilt. But I think the performance would be better than now for this case.

**Comment by xn3cr0nx** [comment]
Hey guys, after a discussion on Slack I add here a use case where it takes really long time to query data with pagination. I'm dealing with more than 120Gb of stored data. I stored ~260k Bitcoin blocks, and I need to go through them, hence doing a pagination, with a pagination of 500 elements (blocks) per query. This is my query, and it takes 4 minutes, for the first small blocks and it seriously get worse with higher blocks  that are actually bigger. Height is indexed, but it seems index is not used, there should definitely be a faster way to do pagination with big datasets (even if I think 100Gb is not what you could consider big). Here is my query:
`curl -H "Content-Type: application/graphql+-" localhost:8080/query -XPOST -d '
{
  blocks(func: ge(height, 0), first: 500, orderasc: height) {
    uid
    height
    id
        height
        version
        prev_block
        timestamp
        merkle_root
        bits
        nonce
        transactions {
            uid
            txid
            version
            locktime
            size
            weight
            fee
            input (orderasc: vout) {
                uid
                txid
                vout
                is_coinbase
                scriptsig
                scriptsig_asm
                inner_redeemscript_asm
                inner_witnessscript_asm
                sequence
                witness
                prevout
            }
            output (orderasc: index) {
                uid
                scriptpubkey
                scriptpubkey_asm
                scriptpubkey_type
                scriptpubkey_address
                value
                index
            }
            status {
                uid
                confirmed
                block_height
                block_hash
                block_time
            }
        }
    }
}' | python3 -m json.tool | less`

**Comment by martinmr** [comment]
Recent versions of Dgraph include a change to split very big lists into smaller lists. When reading such a list for the purpose of a mutation, only a small "header" list is read, instead of the entire list. The parts of the list are only accessed on demand.

Marking this issue as done.
