### ISSUE TITLE
anyofterms does not work for facet created by JSON mutation

### ISSUE THREAD

**Issue by birdayz** [dgraph-io/dgraph#2867]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
tried latest "latest" @ dockerhub and v1.0.12-rc1 

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
16gb, linux

- Steps to reproduce the issue (command/config used to run Dgraph).
Create any facet with a string value.

Query filter it with anyofterms

- Expected behaviour and actual result.

Expected: i can filter with anyofterms, so e.g. if the value of the facet is "READ" and i filter for anyofterms(permission, "READ WRITE"), i will get a result

Actual:
well, anyofterms does not work. the value is not returned. i can only use eq.
**BUT! This is only the case if i performed the mutation for this facet with the JSON API (from dgo). If i do it with the RDF syntax in ratel, it works!**

**Comment by srfrog** [comment]
Could you post a sample of the query you're trying to run? That will help determine if there's an issue. Thanks.

**Comment by birdayz** [comment]
Qry:
```
{
  direct(func: uid(0x9c70)) @cascade {
    access.to  @filter(uid(0x9c7c) AND eq(type, "device")) @facets(anyofterms(permission, "READ WRITE"))  @facets(permission,inherit) {
      uid
    }
  }
}
```
-> no result

If i just use eq READ (which is the value set for the facet) it works:
```
{
  direct(func: uid(0x9c70)) @cascade {
    access.to  @filter(uid(0x9c7c) AND eq(type, "device")) @facets(eq(permissions, WRITE))  @facets(permission,inherit) {
      uid
    }
  }
}
```

-> Result:
    "direct": [
      {
        "access.to": [
          {
            "uid": "0x9c7c",
            "access.to|inherit": true,
            "access.to|permission": "WRITE"
          }
        ],
        "uid": "0x9c70"
      }
    ],

And, still, the first query DOES work, but only if the mutation for the facet was done in ratel in RDF-style.

**Comment by danielmai** [comment]
I'm able to reproduce this by running a JSON mutation and NQuad mutation in dgo.

Code: https://play.golang.org/p/k6DBNXuiuHu

Output:
```
2019/01/04 11:42:08 JSON mutation: {
  "access.to": {
    "access.to|inherit": false,
    "access.to|permission": "WRITE",
    "uid": "0x2"
  },
  "uid": "0x1"
}
2019/01/04 11:42:08 Query: {
  direct(func: uid(0x1)) {
    uid
    access.to @filter(uid(0x2)) @facets(anyofterms(permission, "READ WRITE")) @facets(permission,inherit) {
      uid
    }
  }
}
2019/01/04 11:42:08 Response: {
  "direct": [
    {
      "uid": "0x1"
    }
  ]
}
2019/01/04 11:42:08 NQuads mutation: <0x1> <access.to> <0x2> (permission="WRITE",inherit=false) .

2019/01/04 11:42:08 Query: {
  direct(func: uid(0x1)) {
    uid
    access.to @filter(uid(0x2)) @facets(anyofterms(permission, "READ WRITE")) @facets(permission,inherit) {
      uid
    }
  }
}
2019/01/04 11:42:08 Response: {
  "direct": [
    {
      "access.to": [
        {
          "access.to|inherit": false,
          "access.to|permission": "WRITE",
          "uid": "0x2"
        }
      ],
      "uid": "0x1"
    }
  ]
}
```

**Comment by srfrog** [comment]
It seems to be a bug in the JSON parser. You can test with your query:
RDF:
```rdf
{set {
  _:x1 <access.to> _:x2 (permission="WRITE",inherit=false) .
}}
```
JSON:
```json
{"set": {
  "uid": "_:x1",
    "access.to": {
      "uid": "_:x2",
      "access.to|inherit": false,
      "access.to|permission": "WRITE"
    }
}}
```

**Comment by manishrjain** [comment]
@gitlw fixed a similar issue recently, where we were not parsing the facets correctly in one of the code paths. Lucas: Can you have a look?
