### ISSUE TITLE
dgo client can not get schema success  by used grpc 

### ISSUE THREAD

**Issue by relunctance** [dgraph-io/dgraph#2881]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

Dgraph version   : v1.0.11-46-g034a560
Commit SHA-1     : 034a560
Commit timestamp : 2019-01-07 19:28:39 -0700
Branch           : master
Go version       : go1.11

- Have you tried reproducing the issue with latest release?
yes

- Steps to reproduce the issue (command/config used to run Dgraph).

curl command can get success , but dgo client get result is '{}'

## curl command 
```
curl -X POST -d 'schema {}' "http://127.0.0.1:8080/query" 
```

##  dgo example 
``` go
package main
  
import (
    "context"
    "fmt"
    "log"

    "github.com/dgraph-io/dgo"
    "github.com/dgraph-io/dgo/protos/api"
    "github.com/dgraph-io/dgraph/query"
    "google.golang.org/grpc"
)

func main() {
    dg := newClient()
    txn := dg.NewTxn()
    ctx := context.WithValue(context.Background(), query.DebugKey, "true")
    defer txn.Discard(ctx)
    q := `schema {}`   // query content
    resp, err := txn.Query(ctx, q)
    if err != nil {
        panic(err)
    }
    fmt.Println(string(resp.Json)) // get response result is: '{}'
}                                   
                                    
func newClient() *dgo.Dgraph {      
    dns := "127.0.0.1:9080"
    d, err := grpc.Dial(dns, grpc.WithInsecure())
    if err != nil {                 
        log.Fatal(err)              
    }                               
    return dgo.NewDgraphClient(api.NewDgraphClient(d))
                                    
} 
```

- Expected behaviour and actual result.

expect dgo client  query   schema  return  success result

**Comment by manishrjain** [comment]
Look for a field named Schema something in response proto.

**Comment by manishrjain** [comment]
We should fill out the resp.Json instead, if possible. Common source of confusion.

**Comment by srfrog** [comment]
@manishrjain are you suggesting getting rid of resp.Schema and using only resp.Json ?

**Comment by srfrog** [comment]
@relunctance thx for the suggestion.

**Comment by relunctance** [comment]
> @relunctance thx for the suggestion.

You are welcome
