### ISSUE TITLE
Improve Facets functions. (not supported in preprocessFilter)

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#2896]
### What you wanted to do
I tried beef up the queries for facets to add in the documentation. Especially for fulltext.
https://dgraph.io/docs/query-language/facets/#filtering-on-facets

### What you actually did
Tested alloftext, anyoftext, regexp, ie, has, allofterms, anyofterms, le, lt, ge, gt, eq, AND, OR and NOT
one by one and got the following results.

alloftext => : Fn alloftext not supported in preprocessFilter.
anyoftext => : Fn anyoftext not supported in preprocessFilter.
regexp => : One argument expected in regexp, but got 2.
has => : One argument expected in has, but got 0. (added this test just in case)

what works:
allofterms, anyofterms, le, lt, ge, gt, eq, AND, OR and NOT

Some of the functions are still been discussed if are valid or not for supporting.

**Comment by manojlds** [comment]
Would like to have support for has(facet1) to check if a facet exists.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8434). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by MichelDiz** [comment]
@manojlds if you run `mobile @facets(test)`  is equivalent to `has(test)`. If it returns something it means ~True.
