### ISSUE TITLE
Optimize geo indexing

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#2897]
The current geo indexing is very heavy because it creates too many tokens. We need to decrease the number of tokens created during geo indexing, so it can perform better.

**Comment by campoy** [comment]
Setting to P1 since some customers have requested this.

**Comment by joshuabezaleel** [comment]
Are there any recommendations on where to start and references if someone is interested in this?
Thank you very much! :slightly_smiling_face:

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8435). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
