### ISSUE TITLE
Increase speed and decrease memory usage of algo.IntersectSorted etc.

### ISSUE THREAD

**Issue by covrom** [dgraph-io/dgraph#2911]
## Experience Report
Perfomance of joining operations on sets in package `algo` is not good.

### What you wanted to do
Increase speed of intersect multiple sets in algo.IntersectSorted:

-  switch from sort.Search to inlined binary search function with adjust search boundaries by linear interpolation. Now, sort.Search has ~100% overhead on execute f(i) as a parameter (versus inlined binary search algo).

- switch from pair-to-pair intersect to multiple arrays intersection algo, i.e. search a maximal element in current seeing positions and jump all positions to above it or equal.

Decrease usage of memory in sets joining operations:

- use stream iterators with conditions and limits on multiple sets instead of usage resulting slices. I.e. intersect iterator, merging iterator etc. Each iterator may jump to position or value, for using it in joining operations. Iterators may be include another iterators inside. Iterators do not require additional memory when executing large data with large results.

### What you actually did
Execute big data queries and streaming its results from many users now is inefficient - need extra memory and too slow.

### Why that wasn't great, with examples
We need to minimize usage of resources for 100-2000 RPS with the complexity of querying large data.

### Any external references to support your case
Now I am creating similar functionality in another project.

**Comment by manishrjain** [comment]
Hey @covrom , if you're creating similar functionality, could you possibly send us a (as small as possible) PR with a change that you think would improve performance, along with any benchmarks? We have code already written which does benchmarking on list intersection that you could use.

**Comment by campoy** [comment]
Closing this issue, as #2966 was abandoned.
