### ISSUE TITLE
Support for Dgraph exported data with original UIDs

### ISSUE THREAD

**Issue by zhuyaoyhj** [dgraph-io/dgraph#2934]
## Experience Report

often use fixed UID to process the data. When upgrading the database, when exporting the data, it is found that the exported .rdf file uses an identifier instead of the original UID. The resulting exported data is not directly usable.

### What you wanted to do

Provide a data to configure the export database by fixed UID

### What you actually did

I find worker/export.go has code for export database
fmt.Sprintf("<_:uid%x>", p.Uid)；to fmt.Sprintf("<_0x%x>", p.Uid)

### Why that wasn't great, with examples
UID consistency cannot be guaranteed when restoring database data

### Any external references to support your case
none

**Comment by MichelDiz** [comment]
Sorry but that is not possible right now. There is other things that we should work to support this, but this will be supported with the binaries Backup.

Therefore, this is not supported in favor of:
https://github.com/dgraph-io/dgraph/pull/2710
https://github.com/dgraph-io/dgraph/commit/b845363a5c837930d9d1c4e9382088cbdeb9ce34

And also I believe this issue is duplicated of https://github.com/dgraph-io/dgraph/pull/2850

**Comment by danielmai** [comment]
Let's support this. This situation comes up enough that preserving UIDs in exports should be the default. There can also be an options to not preserve UIDs for backward compatibility.

Live Loader and Bulk Loader should correctly handle UID literals in the exported RDFs.

**Comment by codexnull** [comment]
I would actually vote for keeping the blank UIDs as the default in order to discourage thinking that they will be preserved when the export is reloaded.

**Comment by MichelDiz** [comment]
Yeah, me too. Cuz the binaries backup that Guz is working on alrady does this job. 

And this could be problematic for "Live Load". If this were adopted by Live Load. For a DB that is already in use, may end up being overwritten on the hypothesis of a load the RDF with predetermined UIDs.

It could be catastrophic. Maybe not for BulkLoad, but for Live load it certainly does.

This could be useful in a controlled ingestion hypothesis and the user would assume the risks of having the overwritten data. But it would not be safe in the hypothesis of exporting to a DB in use.

**Comment by manishrjain** [comment]
Sorry, I didn't see these comments before. I can explain why the UID
exports make sense, instead of blank nodes.
