### ISSUE TITLE
support BC date for datetime 

### ISSUE THREAD

**Issue by zhuyaoyhj** [dgraph-io/dgraph#2935]
## Experience Report
Dgraph specifies the datetime type using the format specified by RFC3339. However, Dgraph could not solve the birth date of the character before BC, such as "-138-10-26".

### What you wanted to do
support BC date for datetime 
### What you actually did
none
### Why that wasn't great, with examples
Can't solve the data of BC characters well

### Any external references to support your case
none

**Comment by srfrog** [comment]
Your best alternative is to change this to seconds and store it as an int. Ironically, the Go function `time.Unix()` will handle BC dates ok, but it can't parse them.
