### ISSUE TITLE
Possible bug in posting list logic.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#294]
Another one observed from Gru. I think this a bug, @manishrjain would be good if you can verify this.

Isolated it in a test case here. We perform two set operations, merge posting list. Delete the previous two sets and set a new value.
https://github.com/dgraph-io/dgraph/compare/bugfix/posting2?expand=1

**Comment by manishrjain** [comment]
Looking!

**Comment by pawanrawal** [comment]
Resolved with the new logic for posting lists.
