### ISSUE TITLE
Docs: unneeded --zero flag when launching alpha

### ISSUE THREAD

**Issue by marigonzes** [dgraph-io/dgraph#2946]
* Doc page: [get-started/index.md](https://docs.dgraph.io/master/get-started/#from-installed-binary)
* Doc version: `release/v1.0.11`

In the section "Run Dgraph data server" of the chapter above, the documentation tells the developer to run alpha with "--zero localhost:5080", but this is the default, so it should not be needed. That way, the command to run alpha would be simpler "dgraph alpha --lru_mb 2048".

**Comment by danielmai** [comment]
It may be unnecessary since `localhost:5080` is the default value. But having it in the docs makes it clear that Alpha depends on a connection to Zero to run it. It's better for the developer to understand this upfront than getting stumped later on.
