### ISSUE TITLE
High CPU when No Query

### ISSUE THREAD

**Issue by Puneeth-Kadamba** [dgraph-io/dgraph#2958]
We are facing high CPU issue even when there are no queries running on the server.
We are using Dgraph version   : v1.0.11
Attached is the CPU profile.
[profile.zip](https://github.com/dgraph-io/dgraph/files/2816718/profile.zip)

**Comment by manishrjain** [comment]
This file is 8KB in size, and doesn't have any useful data.

**Comment by Puneeth-Kadamba** [comment]
[pprof.dgraph.samples.cpu.006.pb.gz](https://github.com/dgraph-io/dgraph/files/2824553/pprof.dgraph.samples.cpu.006.pb.gz)
Can you check this file?

**Comment by manishrjain** [comment]
From what I can tell, it just looks like there's a rollup operation going on when the CPU is high. Those are still very useful operations to consolidate the recent mutations into a state and do use up CPU.
