### ISSUE TITLE
Cannot delete predicate from schema

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#2971]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
1.0.10

- Have you tried reproducing the issue with latest release?
no

- What is the hardware spec (RAM, OS)?
3x amazon m5x.large

- Steps to reproduce the issue (command/config used to run Dgraph).
```
[ec2-user@ip-<ip> ~]$ curl -X POST http://localhost:8080/alter -d '{ "drop_attr": "dummy" }'
{"errors":[{"code":"Error","message":"Please use * with delete operation for non-list type: [_predicate_]"}]}
```

previously it worked. but since some moment i started getting his error

**Comment by martinmr** [comment]
Yes this behavior was changed at some point. I was not working on Dgraph at the time so I do not know the reasons.

However, starting in one of the next versions (1.1 I think but maybe 1.0.12, I would need to verify) the behavior would be restored. Here's how deletions of non-list predicates will work in the near future.

`<subject> <pred> *` will still work
`<subject> <pred> <object>` will work. If object and the existing value are equal, then the triple will be deleted. Otherwilse the triple will be ignored and the transaction will succeed. We chose to do this to err on the side of safety and avoid undesired deletions. If you want to guarantee that a triple with a non-list predicate is deleted, you can still use the star notation.

For now, you will need to use the star notation.

**Comment by martinmr** [comment]
Just checked the git logs. The first version with the new behavior will be 1.1

**Comment by makitka2007** [comment]
please, pay attention:
i am not trying to delete predicate value, i am dropping predicate via `/alter -> drop_attr`
on the same machine it worked before, and after few minutes, it throws this error

**Comment by manishrjain** [comment]
@martinmr : Can you test whether this is still an issue and either fix it or close it accordingly?

**Comment by makitka2007** [comment]
i think you can close it because we didn't have it again
