### ISSUE TITLE
Benchmark and Optimize Raft

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#2975]
I'm seeing that after proposing a mutation, it is taking over 130ms just to see it back in `CommitedEntries`. We should try to figure out why it takes this long to see the mutation back via Raft. What is the slowdown here? `SaveToStorage`, the comms, or something else?

![2019-02-04-174622_1243x422_scrot](https://user-images.githubusercontent.com/1782324/52248765-d41e1680-28a4-11e9-87b4-05e87e1ec58d.png)

**Comment by manishrjain** [comment]
One of the things might be that `raft.Advance` is slow, and needs optimization -- one of the things that needs to be done there is to add a cache in front of `LastEntry` API call in raft storage.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8436). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
