### ISSUE TITLE
loader.go issue

### ISSUE THREAD

**Issue by trengrj** [dgraph-io/dgraph#298]
I'm getting the following error using go fetch (commit @0628a36991baebe0e3005869dc8968f0e88f6022)

```
src/github.com/dgraph-io/dgraph/loader/loader.go:231: too many arguments in call to posting.GetOrCreate
```

**Comment by pawanrawal** [comment]
Hey @trengrj 

Thanks for bringing this to our notice. We are aware of this and will fix this soon. Meanwhile, if you want to try out Dgraph the recommended way is to download the binaries. You can find more instructions on our Wiki https://wiki.dgraph.io/Beginners_Guide#Recommended_Installation.

**Comment by manishrjain** [comment]
Fixed. https://github.com/dgraph-io/dgraph/commit/d67d672ce3387bf30a1097315a40e52773b876a6
