### ISSUE TITLE
Sentry assessment

### ISSUE THREAD

**Issue by srfrog** [dgraph-io/dgraph#2988]
When a customer finds a crashing bug sometimes it is difficult to reproduce it. A monitoring tool like [Sentry](https://sentry.io) would help finding the source of these bugs.

- [ ] Investigate if Sentry would work for Dgraph
- [ ] Devise a plan and determine the effort
- [ ] Present the results

**Comment by parasssh** [comment]
We have integrated Sentry into the product starting v20.03.0.
Closing.
