### ISSUE TITLE
Exports should maintain the UIDs

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#2999]
It causes issues for the users when Dgraph exports replace UIDs with variables, and they get reassigned to different UIDs on an export back.

My PR #2998 modifies the live loader to honor the preassigned UIDs while loading data back. So, we can now make a change to our exporter to set UIDs in the data.

Bulk loader should also do the same and honor the preassigned UIDs.

**Comment by codexnull** [comment]
Fixed with PR #3004.
