### ISSUE TITLE
Benchmark against Neo4J

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#3]
[Neo4J](http://neo4j.com/) is the most popular Graph database. It would be great to see how DGraph performs against it.

**Comment by manishrjain** [comment]
https://github.com/socialsensor/graphdb-benchmarks

**Comment by hackintoshrao** [comment]
Socialsensor uses the Java driver of the each of the databases (neo4j, titan,orient and sparksee) to drive the insertions and query. I believe for Dgraph to find a place here https://github.com/socialsensor/graphdb-benchmarks/tree/master/src/main/java/eu/socialsensor/graphdatabases , we need a Java driver too so that we align to the common standard of how those tests are conducted and then we could ping the maintainers of social sensor with our addition of DGraph into the list with a PR and that would be a good establishment of comparison with the others in the list.

**Comment by hackintoshrao** [comment]
@manishrjain , All the Databases under scrutiny should implement [this interface](https://github.com/socialsensor/graphdb-benchmarks/blob/master/src/main/java/eu/socialsensor/graphdatabases/GraphDatabase.java ).Neo4J's implementation of the interfaces are [here](https://github.com/socialsensor/graphdb-benchmarks/blob/master/src/main/java/eu/socialsensor/graphdatabases/Neo4jGraphDatabase.java). [GraphDatabaseBase](https://github.com/socialsensor/graphdb-benchmarks/blob/master/src/main/java/eu/socialsensor/graphdatabases/GraphDatabaseBase.java) implements [GraphDataBase](https://github.com/socialsensor/graphdb-benchmarks/blob/master/src/main/java/eu/socialsensor/graphdatabases/GraphDatabase.java) and all other databases extends and thus overrides GraphDatabaseBase.  Most the queries are written in the extended class, but some of them are written in [Neo4JMAssiveInsertion](https://github.com/socialsensor/graphdb-benchmarks/blob/master/src/main/java/eu/socialsensor/insert/Neo4jMassiveInsertion.java) , [Neo4J single Insertion](https://github.com/socialsensor/graphdb-benchmarks/blob/master/src/main/java/eu/socialsensor/insert/Neo4jSingleInsertion.java) , [Neo4JQuery](https://github.com/socialsensor/graphdb-benchmarks/blob/master/src/main/java/eu/socialsensor/query/Neo4jQuery.java), and the primitive queries in these three files are as follows.
[Get all nodes of the graph](http://neo4j.com/docs/stable/javadocs/org/neo4j/tooling/GlobalGraphOperations.html#getAllNodes%28%29)
[Get all the relationships of a given node](http://neo4j.com/docs/stable/javadocs/org/neo4j/graphdb/Node.html#getRelationships%28%29)
[Given a node that is attached to a relationship, returns the other node](http://neo4j.com/docs/stable/javadocs/org/neo4j/graphdb/Relationship.html#getOtherNode%28org.neo4j.graphdb.Node%29
 )
[Get all relationships in the Graph](http://neo4j.com/docs/stable/javadocs/org/neo4j/tooling/GlobalGraphOperations.html#getAllRelationships%28%29)
[Given the relationship find its start node](http://neo4j.com/docs/stable/javadocs/org/neo4j/graphdb/Relationship.html#getStartNode%28%29
 )
[Given the relationship find its end node](http://neo4j.com/docs/stable/javadocs/org/neo4j/graphdb/Relationship.html#getEndNode%28%29
)
[Find all nodes with given label and property](http://neo4j.com/docs/stable/javadocs/org/neo4j/graphdb/GraphDatabaseService.html#findNodesByLabelAndProperty%28org.neo4j.graphdb.Label,%20java.lang.String,%20java.lang.Object%29
 )
[Find shortest path between 2 nodes with the configuration of relationship type and max depth set for the path](http://neo4j.com/docs/stable/javadocs/org/neo4j/graphalgo/GraphAlgoFactory.html#shortestPath%28org.neo4j.graphdb.PathExpander,%20int%29
 )
[Node creation using batch operation for massive writes](http://neo4j.com/docs/stable/javadocs/org/neo4j/unsafe/batchinsert/BatchInserter.html#createNode%28java.util.Map,%20org.neo4j.graphdb.Label...%29
 )
[Create relationship of given type between two specified nodes](http://neo4j.com/docs/stable/javadocs/org/neo4j/unsafe/batchinsert/BatchInserter.html#createRelationship%28long,%20long,%20org.neo4j.graphdb.RelationshipType,%20java.util.Map%29
 )
Again the rest are implemented here in the [extended class](https://github.com/socialsensor/graphdb-benchmarks/blob/master/src/main/java/eu/socialsensor/graphdatabases/Neo4jGraphDatabase.java)

**Comment by hackintoshrao** [comment]
If its helpful I could get it more organized by creating a Google Doc of all the queries used by social sensor and then we could have tick against the functionalities supported by Dgraph.

**Comment by manishrjain** [comment]
This looks like it was designed for Neo4J use case. DGraph is designed for a use case where the schema is well defined, not arbitrary. So, for a given node, you currently can't locate all it's properties. We could store them, if there's a strong use case (it would just mean added complexity to keep things in sync); but even our query language, GraphQL is designed to avoid that. This is a clear and simpler design decision I see in Tao (Facebook's graph db) and GraphQL, which emphasizes extensible, flexible, but well defined schema.

Here're some language clarifications:
Node is called *Entity* in DGraph.
Relationship I assume means *Attribute* in DGraph.

So, here's the verdict:
Get all entities of the graph: Not scalable, so No.
Get all attributes for a given entity: No. Schema should give you that (GraphQL type system).
Given an Entity, Attribute, return it's neighbors: Yes
Get all Attributes in a graph: Not scalable, so No.
Given an Attribute, find a (start?) node: What does start mean? Given we sort (Attribute, Entity) lexicographically, does start mean first Entity for a given Attribute? Why is that useful? I just don't see the point.
Given an Attribute, find a (end?) node: Don't see the point.
Find all Entities for a label and property: If this means RDF label, then no. That's not scalable. It's a property attached to a posting in a posting list.
Shortest path between 2 nodes, given attributes: Yes, we could do that.
Node creation, massive writes: Yes.
Create relationship between 2 nodes: Yes.

**Comment by hackintoshrao** [comment]
I believe we could close this for now and may be open a new issue for writing another benchmark.

**Comment by hackintoshrao** [comment]
Oh, I don't see a need to close this! Anyways the issue was not about using socialsensor . As discussed in Gitter it calls for a need for a new benchmark tool and will start developing it in https://github.com/dgraph-io/benchmarks .

**Comment by manishrjain** [comment]
This project was unfinished. For now, we're just going to focus on our own performance, and not waste time on comparison benchmarks.

**Comment by manishrjain** [comment]
https://open.dgraph.io/post/benchmark-neo4j/
