### ISSUE TITLE
kubedb dgraph operator/datastore

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3000]
It would be great if a operator can be provided for kubedb.

https://kubedb.com/docs/0.9.0/concepts/what-is-kubedb/overview/

**Comment by StevenACoffman** [comment]
Possibly of interest: [dgraph-operator](https://github.com/thoth-station/dgraph-operator)

**Comment by danielmai** [comment]
KubeDB looks promising, but I couldn't find any docs about how to integrate with KubeDB. If there's more demand for supporting KubeDB we can look into it further.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8437). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
