### ISSUE TITLE
Improve error message for missing `func`

### ISSUE THREAD

**Issue by a-type** [dgraph-io/dgraph#3006]
### What you wanted to do

I wanted to list the first 10 movie nodes in the example dataset

### What you actually did

I tried this query:

```
{
  movies(first: 10)
  {
    uid
    name
  }
}
```

Knowing based on my understanding of Dgraph so far in my learning, that it was most likely incorrect, but not sure why. I was interested in seeing how the parser would complain. I got the error message:

> Invalid query, query pb.id is zero and generator is nil

Googling it lead me only to the source itself, which wasn't much more readable as a JS dev.

### Why that wasn't great, with examples

This isn't really a great experience specifically for someone like me coming from an entrenched SQL-style mindset where I believe I should be able to just read 10 records from a "table." Although I know this is the wrong mental model, I'm still in the process of recalibrating for a graph database. Obviously I know I should include a `func` to filter the initial result set, but nothing in the docs or tour actually indicated it was _required_. Perhaps that could be a separate docs request.

But as for this error message itself, it just isn't really useful to anyone outside the Dgraph project.

**Comment by danielmai** [comment]
`func` isn't required, but it is used in most query blocks. For example, empty query blocks are used for aggregations—see the example queries in the [Aggregation docs](https://docs.dgraph.io/query-language/#aggregation).

I agree that the error message here can be improved, but in the query you shared "movies" is the just name of the query block. The query block name has no bearing on what nodes are queried.

**Comment by a-type** [comment]
Interesting, and helpful to learn. I have been slowly breaking out of old ideas about what names mean, so I finally 'get' that query block names are not meaningful except for the structure of the selected data. But it's taken me a good while to finally grasp how Dgraph does 'typed' nodes (a la Neo4J labels). I like it, it's very flexible, but also hard to learn for someone from a table-based mindset (or even a Neo4J mindset, where labels were first-class concepts). I'm excited to be thinking more in graphs and not relying so much on those assumptions, but I wanted to share that as a newcomer, the documentation/errors have caused some friction in me gaining understanding.
