### ISSUE TITLE
Usage of `preds` is not documented for HTTP clients

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/dgraph#3009]
[HTTP Documentation](https://github.com/dgraph-io/dgraph/blob/a1b65029cb2d62eb9ba150d891a6025bd0cef734/wiki/content/clients/index.md) mentions the `preds` list, instructs clients to keep track of it and optionally de-dup the entries.
However there's no explanation of where and how to use it.
- Should it be sent to the server during commit?
- Should it be processed on the client?
- Why store it at all if we never send it anywhere?

Only mention of its use is:
> This aids in predicate move detection

But it's not unclear how to detect it and how to handle a predicate move.

**Comment by paulftw** [comment]
@danielmai please take a look as you seem to be the most knowledgeable person on the subject

**Comment by danielmai** [comment]
Preds should be passed in via /commit like the keys. This needs to be updated in Dgraph since it currently only accepts an array of keys.

**Comment by martinmr** [comment]
The changes in dgraph are done. I also updated the documentation.

The only thing left is to update the javascript client. I have the PR and I am just waiting on the change to make it to a stable version of Dgraph. I will close this issue and follow up in the other repo.
