### ISSUE TITLE
Dgraph's CHANGELOG.md is in a wrong format

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/dgraph#3010]
Dgraph releases in the changelog file are formatted as:
```
...

## [1.0.12] - [unreleased]
...

## [1.0.11] - 2018-12-17
...
```

I believe square brackets were copy-pasted from the keepachangelog example, but currently they make no sense.

In Markdown `[foo]` creates a [reference](https://daringfireball.net/projects/markdown/syntax#link) and should be followed by `[foo](webpage for foo)` somewhere later in the document.

Since we don't include those links in the footnotes version names are rendered to users literally as `[1.0.11]`. Why do we have versions wrapped in square brackets?

There are **two way to fix** this:

1. remove the square brackets from `x.y.z` strings and `unreleased`.
2. add working URLs somewhere in the file.

Correct way of linking releases is shown at the very end of the keepachangelog example:
```
[Unreleased]: https://github.com/olivierlacan/keep-a-changelog/compare/v1.0.0...HEAD
[1.0.0]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.3.0...v1.0.0
[0.3.0]: https://github.com/olivierlacan/keep-a-changelog/compare/v0.2.0...v0.3.0
```

**Comment by danielmai** [comment]
We can add the compare links.

**Comment by danielmai** [comment]
Added the links directly under each release header instead of at the bottom of the file so that we don't forget to add them for future releases.
