### ISSUE TITLE
Bulk loader uses too much memory

### ISSUE THREAD

**Issue by codexnull** [dgraph-io/dgraph#3017]
The bulk loader's memory usage can grow beyond the size of physical RAM and cause swap space to be used. As the image below shows, memory usage grows monotonically during the map phase, is flat during the reduce phase, and is all finally released at exit.

![image](https://user-images.githubusercontent.com/35480615/52771516-f1608c80-2fea-11e9-899d-2a86f8593953.png)

The system does not appear to thrash, though, which suggests the memory is just being held by the process without it actively being accessed. Still, a big enough load may cause it to grow greater than RAM + swap and cause system instability or crashes.

Note the system was idle other than for dgraph. I did not test what would happen if concurrent processes had significant memory demands as well.

**Comment by xiangzhao632** [comment]
Could you please tell me what software in your picture？really appreciate

**Comment by shekarm** [comment]
Hi,

Thank you for the post. We have made some improvements in our software (recently) which will likely exhibit different behavior -- in other words, much less memory usage. Keep you posted on developments. Meanwhile, if you haven't already done so, would you be able to share the characteristics of your data set that you are using? 

Thanks

**Comment by ashish-goswami** [comment]
I think this issue can be closed after we fix https://github.com/dgraph-io/dgraph/issues/5361

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8760). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
