### ISSUE TITLE
 Dgraph alpha crashes when setting the parameter "--my" to the IPV6 address. 

### ISSUE THREAD

**Issue by chuerxiao** [dgraph-io/dgraph#3023]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.11

- Have you tried reproducing the issue with latest release?
v1.0.11 is the last release

- What is the hardware spec (RAM, OS)?
    * Distributor ID:	Ubuntu
      Description:	Ubuntu 16.04.5 LTS
      Release:	16.04
      Codename:	xenial
      memory 256GB
      cores 80

- Steps to reproduce the issue (command/config used to run Dgraph).
./dgraph alpha --zero [2001:ddb::64]:1139 --lru_mb 2048 -o=200 --my=[2001:ddb::64]:1142

- Expected behaviour and actual result.
```
badger2019/02/15 17:32:17 INFO: Replaying file id: 0 at offset: 0

badger2019/02/15 17:32:17 INFO: Replay took: 17.162µs

2019/02/15 17:32:17 [2001:ddb::64]:1142 is not valid address

github.com/dgraph-io/dgraph/x.AssertTruef

        /home/chujunlin/dgraph/src/github.com/dgraph-io/dgraph/x/error.go:79

github.com/dgraph-io/dgraph/worker.StartRaftNodes

        /home/chujunlin/dgraph/src/github.com/dgraph-io/dgraph/worker/groups.go:75

runtime.goexit

        /usr/local/go/src/runtime/asm_amd64.s:2361
```

**Comment by chuerxiao** [comment]
https://github.com/dgraph-io/dgraph/blob/master/x/x.go

change
```
	if err := net.ParseIP(host); err == nil {
		return true
	}
```
to
```
	if ip := net.ParseIP(host); ip!= nil {
		return true
	}
```

**Comment by jarifibrahim** [comment]
This should be fixed by https://github.com/dgraph-io/dgraph/pull/3027 (I couldn't assign the issue to myself)
