### ISSUE TITLE
How to insert data

### ISSUE THREAD

**Issue by thumbsized** [dgraph-io/dgraph#3025]
Following the docs, I tried for an hour to figure out how to actually put some data into the DB but unsuccessfully. I was hoping the JSON would save me but nope, the documentation is absolutely **useless**.

Can someone provide me with some real examples of few different entity/objects?

**Comment by MichelDiz** [comment]
We have few videos that can help. Also a Tour.
[Performing CRUD operations with Dgraph](https://youtu.be/vhatoyZ2vic) 

[Up and Running with Dgraph's Tour](https://youtu.be/sxqRGfDL7Qw)
The tour: https://tour.dgraph.io/

Btw. Please make Questions in https://Discuss.dgraph.io - We prefer issues to be tracking bugs, features and etc. This makes developing more focused.
