### ISSUE TITLE
Smarter handling of out directory by bulk loader

### ISSUE THREAD

**Issue by codexnull** [dgraph-io/dgraph#3026]
I have more than once blown away data I did not mean to with the --out option of the bulk loader because it silently deletes and re-creates the directory. It's fortunate I have not yet tried to put the bulk output in their home directory by using --out=$HOME.

The bulk command should:

1) require the --out directory not exist or to be empty, and
2) require an additional option (e.g. --replace-out) to make it explicit the the directory is being replaced, not added to.

**Comment by jarifibrahim** [comment]
Hey @codexnull :wave: , this seems like a simple change. Do you mind if I take this up?

**Comment by codexnull** [comment]
Thanks for offering, but it was indeed a simple change and I had already started working on it. I actually ended up doing something even simpler: deleting just the out/<n> subdirectories (where <n> is the shard number) rather than the whole out/ directory.

**Comment by codexnull** [comment]
Addressed in https://github.com/dgraph-io/dgraph/pull/3089.
