### ISSUE TITLE
Explain what ~ does?

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3031]
**Documentation**

```
{
  movies(func: uid(0x107b2c, 0x85f961)) {
    uid
    name@en
    initial_release_date
    netflix_id
    ~director.film {
      uid
      name@en
    }
  }
}
```

**Comment by MichelDiz** [comment]
It's a syntax for reverse edge https://docs.dgraph.io/query-language/#reverse-edges

Please make Questions in https://Discuss.dgraph.io - We prefer issues to be tracking bugs, features and etc. This makes development more focused.

**Comment by pjebs** [comment]
I'm suggesting the documentation explain that BEFORE it starts using it.

It is used at this point:

https://docs.dgraph.io/query-language/#running-examples

It is explained at this point:

https://docs.dgraph.io/query-language/#reverse-edges
