### ISSUE TITLE
Zero exposes api key

### ISSUE THREAD

**Issue by przybylski** [dgraph-io/dgraph#3033]
telemetry.go file exposes a API key to keen api, this might lead to heavy cost for project owner

If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
N/A

- Have you tried reproducing the issue with latest release?
No

- What is the hardware spec (RAM, OS)?
Any

- Steps to reproduce the issue (command/config used to run Dgraph).
N/A

- Expected behaviour and actual result.
Do not expose api key and project id

**Comment by codexnull** [comment]
Using Keen requires embedding the API key in the client, so there's no sure way keep the key totally secure. Yes, we could make it harder to find, but for now we are relying on Keen's service to manage abuse.

**Comment by codexnull** [comment]
Closing issue since there doesn't seem to be anything to do. Re-open if necessary.
