### ISSUE TITLE
Explaining schema before explaining the query language

### ISSUE THREAD

**Issue by kokizzu** [dgraph-io/dgraph#3037]
I think I know what's wrong with [this](https://docs.dgraph.io/query-language/) tutorial, it lack of explanation or picture about the example's schema (which one is edge, which one is node, which one is a property/attribute). Especially starting from this:

`~director.film`
`starring`, `performance.actor` and `performance.character`
`director.film`

It took me a while to understood the schema without a picture.

I meant, in the RDBMS/SQL world, we memorize the schema (ER diagram) before do any query. So, wouldn't it be better to increase the adoption of graph database if we also do that. Or is there any tool to do so/visualize the schema? just like [DbVisualizer](https://www.dbvis.com/), [MySQL Workbench](https://www.mysql.com/products/workbench/), etc.

**Comment by MichelDiz** [comment]
You can jump directly to:
https://docs.dgraph.io/query-language/#schema
https://docs.dgraph.io/query-language/#schema-types
https://docs.dgraph.io/query-language/#adding-or-modifying-schema

Also there's a Tour:
https://tour.dgraph.io/schema/1/

For the Visualizer We have Ratel. You can see it running in 
http://play.dgraph.io

**Comment by kokizzu** [comment]
Ratel does the visualization *after* the query, what we need is one that describe the schema *before* we write the query (to know what entities have what properties and related to which entity).

**Comment by MichelDiz** [comment]
Do you mean out completing? Well, if you have any suggestion for Ratel. Share your experiences in Ratel repo that Paul will be evaluating your propositions.

**Comment by kokizzu** [comment]
yes, it can be something like that. On RDBMS world, normal programmer/dba would see the ER diagram first (understanding the relations, what columns are there on each table), before doing any query. But since there are no "table" on graph database, this give some difficulties.
