### ISSUE TITLE
Typo in Dgraph Docs: Design-concepts: Queries

### ISSUE THREAD

**Issue by mingsterism** [dgraph-io/dgraph#3047]
If you think Dgraph's documentation at https://docs.dgraph.io is lacking, please
explain it here.

URL for page: https://docs.dgraph.io/design-concepts/#queries
Typo Error: (should be `pred_B1` and `pred_C1`  )

_The above queries would return back 3 lists of UIDs or values. The result of pred_B and pred_C would be converted into queries for **pred_Bi** and **pred_Ci**.
**pred_Bi** and **pred_Ci** would then cause at max 4 network calls, depending upon where these predicates are located. The keys for pred_Bi, for example, would be pred_Bi, res_pred_Bk, where res_pred_Bk = list of resulting UIDs from pred_B, u._

**Comment by danielmai** [comment]
This is not a typo. "pred_Bi" and "pred_Ci" can be substituted for pred_B1, pred_B2, pred_C1, pred_C2. This logically follows the note about "max 4 network calls"—one potential network call per predicate.
