### ISSUE TITLE
gRPC with TLS

### ISSUE THREAD

**Issue by srfrog** [dgraph-io/dgraph#3048]
Make all gRPC connections TLS with flags.
- Zero to Alpha(s)
- Live to Cluster

**Comment by manishrjain** [comment]
Not by default. But, give users an option to do so.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8762). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
