### ISSUE TITLE
During queries, do not make alphas ask zero to serve a tablet if predicate does not exist.

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/dgraph#3050]
Currently queries to unknown predicates are not stateless because they make alphas send zero a request to hold the tablet. This behavior should be changed to preserve the statelessness of queries.

**Comment by codexnull** [comment]
Doesn't the alpha have to query the zero to check if the predicate is being served by another node? My understanding was that an alpha only knows about *some* of the predicates in the schema. It needs to check with zero to see if another alpha is serving it, otherwise it will serve it itself.

**Comment by martinmr** [comment]
That's correct. What this issue is trying to fix is that if a pred does not exist (i.e no tablet is serving it) the alpha that received the request will ask zero to serve the tablet for that pred. This effectively makes queries affect the state of the alphas, which should not happen.
