### ISSUE TITLE
Implement approximate counts using HyperLogLog++ algorithm

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#3054]
is it possible to implement approximate counts? in our case we don't need to know exact number of linked resources, if they are 324905 or 319043. in ElasticSearch we can specify precision for counts, like, give me exact count if results are less than 100, and approximate count if results are bigger, so such count performs really faster and consume less memory than exact count which we actually don't need for big values

as i understand, HyperLogLog++ is not super hard to implement but it can significantly improve performance for counts when we don't need exact value when it's big.

having something like `count_approximate(relation, 100) @filter(...)` where 100 is a precision (value under which exact value is guaranteed) would be very useful

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8763). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
