### ISSUE TITLE
Dgraph hangs on "Group checksum mismatch for id: 1" error

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#3063]
i am trying 1.0.12rc6 on 3 nodes dgraph cluster
first 3 millions were inserted quickly, but after that it stuck on this error on mutations, and doesn't respond on every even very simply query.

**Comment by makitka2007** [comment]
i see in `/state` that both 3 checksums are different for `1` group. but what should be done here? all mutations fail. it doesn't seem to be changed. wait infinitely?

**Comment by makitka2007** [comment]
tried 2 times, but got dgraph hang on this error both times. it was throwing this error all the night, so i have to revert to 1.0.10

**Comment by manishrjain** [comment]
Can you post the logs, if you have them?

**Comment by makitka2007** [comment]
please find logs for last 15 minutes: https://drive.google.com/file/d/17jLZ7uiWlCUjfjkWuieXJ81mcVPV7ot3/view?usp=sharing

and for time interval, when it started to happen: https://drive.google.com/file/d/11-CLxvHo6voQNXp3ved5aLNuW84raj99/view?usp=sharing

**Comment by danielmai** [comment]
Can you share the commands you used to run Dgraph? The logs say that the Zero group can't communicate with the leader.

**Comment by makitka2007** [comment]
zero:
`dgraph zero --my=<ip0>:5080 --idx=10 --peer <ip1>:5080 --replicas 3 --logtostderr`
`dgraph zero --my=<ip1>:5080 --idx=11 --replicas 3 --logtostderr`
`dgraph zero --my=<ip2>:5080 --idx=12 --peer <ip1>:5080 --replicas 3 --logtostderr`
alpha:
`dgraph alpha --my=<ip0>:7080 --lru_mb=8192 --idx 1 --zero=<ip0>:5080 --logtostderr --expand_edge=false --pending_proposals=64`
`dgraph alpha --my=<ip1>:7080 --lru_mb=8192 --idx 2 --zero=<ip1>:5080 --logtostderr --expand_edge=false --pending_proposals=64`
`dgraph alpha --my=<ip2>:7080 --lru_mb=8192 --idx 3 --zero=<ip2>:5080 --logtostderr --expand_edge=false --pending_proposals=64`

IPs are static

**Comment by makitka2007** [comment]
we have 3 nodes cluster, and each node contains zero and alpha running on it

**Comment by manishrjain** [comment]
I suspect that one of the Alphas is talking to the wrong Zero for some reason. That Alpha might be the one which is blocking queries. We have code to defend against network partitions, so I'm not entirely sure why this would happen.

I'd recommend restarting the Alpha which has issues.

**Comment by makitka2007** [comment]
i am not sure that need for manual node restart is a normal case for production..
is there a way to debug which zero address is used by alpha?

actually we have the same problem on 1.0.10 version as well, i think the only difference is that in rc6 checksum checks are introduced, so mutations are failing. for 1.0.10 version we just have 2 nodes working and third one just asking `OK` on all health checks but mutations and all queries run forever, so all inserts are going to that 2 working nodes.

could you please check start commands if they are correct? instances are started by amazon in random order

**Comment by makitka2007** [comment]
so, every time we have the same picture - clear cluster starts working, both 3 nodes are asnwering ok and running mutations. but then one node hangs and all queries there run infinitely, mutations hang as well

**Comment by makitka2007** [comment]
okay, i got this again - now i have both 3 nodes being stuck
3 zero nodes saying via `/state` that leader is `xxx.xxx.10.237`, but in alpha logs i see:

```

Feb 27 16:40:14.536 | i-xxx860a | dgraph-alpha | Got address of a Zero server: xxx.xxx.9.69:5080
-- | -- | -- | --
  | Feb 27 16:39:31.648 | i-xxxcb08 | dgraph-alpha | Got address of a Zero server: xxx.xxx.9.69:5080
  | Feb 27 16:39:08.011 | i-xxx09be | dgraph-alpha | Got address of a Zero server: xxx.xxx.9.69:5080
  | Feb 27 16:38:18.023 | i-xxx860a | dgraph-alpha | Got address of a Zero server: xxx.xxx.9.69:5080
  | Feb 27 16:38:17.023 | i-xxx860a | dgraph-alpha | Got address of a Zero server: xxx.xxx.9.69:5080
  | Feb 27 16:38:16.022 | i-xxx860a | dgraph-alpha | Got address of a Zero server: xxx.xxx.9.69:5080
```

so, *all* 3 alpha nodes are pointing to wrong zero node

after 3 alphas restart i got following in logs:
```

Feb 27 16:48:20.315 | i-xxx1ba9 | dgraph-alpha | Got address of a Zero server: xxx.xxx.9.69:5080
-- | -- | -- | --
  | Feb 27 16:47:40.600 | i-xxxcb08 | dgraph-alpha | Got address of a Zero server: xxx.xxx.9.69:5080
  | Feb 27 16:47:30.037 | i-xxx09be | dgraph-alpha | Got address of a Zero server: xxx.xxx.10.237:5080
```
wheres currently leader is `xxx.xxx.8.135` (for both 3 zero nodes state)

**Comment by manishrjain** [comment]
Hi @makitka2007 , it's hard to debug with snippets of logs. Can you reach out to me via email, and we can dig deeper.

**Comment by gorjuspixels** [comment]
We saw a similar issue yesterday. Restarting alphas fixed it. It'd be great to see the solution in here. I'll try and post something useful later today

**Comment by manishrjain** [comment]
I'd like to schedule a video chat, so we can have a deeper look at what's going on. So, please do reach out by email.

**Comment by makitka2007** [comment]
that would be great. unfortunately, i have day off tomorrow (and today i already called it a day), so, will contact you on Friday

**Comment by manishrjain** [comment]
Hi @makitka2007 ,

Thanks a lot for doing the call and helping us understand the issue. I've pushed a new docker version: v1.0.12-rc7, with the fixes. Can you try it out?

This commit fixes (or at least should fix) the issue you encountered: https://github.com/dgraph-io/dgraph/commit/fe3da12fcbec6e9727ea2476353cc534f0726078

**Comment by makitka2007** [comment]
testing on rc7 - that bug seems to be solved. thank you
