### ISSUE TITLE
jdbc/odbc support

### ISSUE THREAD

**Issue by rdinnik** [dgraph-io/dgraph#3081]
I need to support of jdbc/odbc for several reasons:

to connect to dgraph from etl-tools
to connect to dgraph from BI
to have dgraph as a backed for existing metadata repository solution which can be represented as any datasource supporting jdbc/odbc connection. In other words I need a bridge between regulare sql queries including ddl and dgraph. The bridge should be represented as a jdbc/odbc driver.
One of important question and challedge would be: how to map/interprete "create table..." statement to dgraph structures/api.

p.s.
neo4j has implemented the feature, but this graph db is not our choice for some reasons.

**Comment by danielmai** [comment]
We have no plans to support a JDBC/ODBC interface with Dgraph.

You can readily use the official Java client [dgraph4j][] to connect to Dgraph from Java.

[dgraph4j]: https://github.com/dgraph-io/dgraph4j
