### ISSUE TITLE
Autocomplete dgraph tools

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#3083]
We should make bash and zsh auto complete dgraph tool and arguments on tab press.

**Comment by danielmai** [comment]
Looks like this might be easy: https://github.com/spf13/cobra/blob/master/bash_completions.md

**Comment by srfrog** [comment]
bash works fine, just need to source the bash-completion scripts if haven't done it. Zsh seems a bit different as each user can have their setup. So we generate a file and let them install. There's a zsh plugin called `compinstall` that handles that using their `$fpath` and `_compdir` settings.

**Comment by martinmr** [comment]
This looks like it's done so closing this issue.
