### ISSUE TITLE
"Missing values/constant in math expression" error in logs

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#3087]
dgraph version: 1.0.12rc6

prerequisites:
```
{
  set {
    _:node1 <start> "" .
    _:node1 <link> _:link1 .
    _:node1 <link> _:link2 .
    _:link1 <link> _:node2 .
    _:link2 <link> _:node2 .
  }
}
```

so, for node1 `link` predicate does exist, but `link2` doesn't.
when i am running such query:
```
{
  var(func: has(start)) {
    c as math(1)
    link {
      link {
        nodes as math(c)
      }
    }

    c2 as math(1)
    link2 {
      link2 {
        nodes2 as math(c2)
      }
    }
  }
  
  q(func: uid(nodes)) {
    uid
    val(nodes)
  }

  q2(func: uid(nodes2)) {
    uid
    val(nodes2)
  }
}
```

```
{
    "extensions": {
        "server_latency": {
            "parsing_ns": 15680,
            "processing_ns": 1938690,
            "encoding_ns": 574145
        },
        "txn": {
            "start_ts": 25
        }
    },
    "data": {
        "q": [
            {
                "uid": "0x3",
                "val(nodes)": 2
            }
        ],
        "q2": []
    }
}
```

it provides correct results, but every time i run this query, dgraph alpha logs this error: 
> Missing values/constant in math expression

it's annoying, because such queries are running very frequently, so in logs there will be a lot of flood. using variable propagation shouldn't lead to such error just because of `link2` predicate missing. some predicates are present for some nodes, some not, it's a usual case

**Comment by srfrog** [comment]
Thanks, this shouldn't be an error but a warning. What is happening is that you are trying to access a unset uid value, in this case `nodes`, and Dgraph will use default values for the evaluation so it ~warns~ prints that error.

I have increased the level so it shouldn't show unless you really want to see it.
