### ISSUE TITLE
create /usr/local/bin in install script if doesn't exist

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/dgraph#3090]
There's this [really old bug](https://github.com/dgraph-io/website/issues/12) in our private website repo. I think it refers to the dgraph curl install script.

Moving it here as it's way more relevant to the Dgraph code than the website pixels.

### create /usr/local/bin in install script if doesn't exist

On some Mac setups, this dir is missing and the script fails.

Remember to do nightly script as well.

**Comment by martinmr** [comment]
https://github.com/dgraph-io/website/pull/22

**Comment by martinmr** [comment]
Fixed.
