### ISSUE TITLE
oom when import data 

### ISSUE THREAD

**Issue by fjbreeze** [dgraph-io/dgraph#3095]
```
docker run -d -p 5080:5080 -p 6080:6080 -p 8080:8080 -p 9080:9080 -p 8000:8000 -m 4096M -v /home/dgraph:/dgraph -v /home/rdf:/rdf --name diggy dgraph/dgraph dgraph zero
docker exec -d diggy dgraph-ratel
docker exec diggy dgraph alpha --lru_mb 1024 --zero localhost:5080 --badger.vlog=disk --badger.tables=disk
dgraph live -r /rdf/data.rdf
```

I0305 10:51:25.555688   52500 pool.go:140] CONNECTED to localhost:5080
E0305 10:51:26.556301   52500 pool.go:206] Echo error from localhost:5080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:5080: connect: connection refused"
I0305 10:51:40.161563   53137 init.go:88] 

Dgraph version   : v1.0.11
Commit SHA-1     : b2a09c5b
Commit timestamp : 2018-12-17 09:50:56 -0800
Branch           : HEAD
Go version       : go1.11.1

For Dgraph official documentation, visit https://docs.dgraph.io.
For discussions about Dgraph     , visit https://discuss.dgraph.io.
To say hi to the community       , visit https://dgraph.slack.com.

Licensed variously under the Apache Public License 2.0 and Dgraph Community License.
Copyright 2015-2018 Dgraph Labs, Inc.

I0305 10:51:40.167012   53137 run.go:98] Setting up grpc listener at: 0.0.0.0:5080
I0305 10:51:40.167240   53137 run.go:98] Setting up http listener at: 0.0.0.0:6080
I0305 10:51:40.176341   53137 node.go:151] Setting raft.Config to: &{ID:1 peers:[] learners:[] ElectionTick:100 HeartbeatTick:1 Storage:0xc00046c960 Applied:0 MaxSizePerMsg:1048576 MaxInflightMsgs:256 CheckQuorum:false PreVote:true ReadOnlyOption:0 Logger:0x1f94370 DisableProposalForwarding:false}
I0305 10:51:40.176722   53137 node.go:290] Group 0 found 1 entries
I0305 10:51:40.176780   53137 node.go:83] 1 became follower at term 0
I0305 10:51:40.176821   53137 node.go:83] newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
I0305 10:51:40.176835   53137 node.go:83] 1 became follower at term 1
I0305 10:51:40.177504   53137 run.go:265] Running Dgraph Zero...
E0305 10:51:40.177966   53137 raft.go:464] While proposing CID: Not Zero leader. Aborting proposal: cid:"d9fb6926-eab1-4425-b560-bbc4c83838e8" . Retrying...
I0305 10:51:40.179256   53137 node.go:173] Setting conf state to nodes:1 
I0305 10:51:40.179305   53137 raft.go:596] Done applying conf change at 1
I0305 10:51:40.562289   52500 pool.go:217] Connection established with localhost:5080
I0305 10:51:41.178337   53137 node.go:83] 1 no leader at term 1; dropping index reading msg
I0305 10:51:41.368537   53137 zero.go:368] Got connection request: cluster_info_only:true 
I0305 10:51:42.918581   53137 node.go:83] 1 is starting a new election at term 1
I0305 10:51:42.918640   53137 node.go:83] 1 became pre-candidate at term 1
I0305 10:51:42.918652   53137 node.go:83] 1 received MsgPreVoteResp from 1 at term 1
I0305 10:51:42.918695   53137 node.go:83] 1 became candidate at term 2
I0305 10:51:42.918703   53137 node.go:83] 1 received MsgVoteResp from 1 at term 2
I0305 10:51:42.918743   53137 node.go:83] 1 became leader at term 2
I0305 10:51:42.918754   53137 node.go:83] raft.node: 1 elected leader 1 at term 2
I0305 10:51:42.919813   53137 raft.go:613] I've become the leader, updating leases.
I0305 10:51:42.919855   53137 assign.go:44] Updated Lease id: 1. Txn Ts: 1
E0305 10:51:43.179589   53137 raft.go:464] While proposing CID: Not Zero leader. Aborting proposal: cid:"e0d4cd17-9aab-411d-801d-72289ceac9a2" . Retrying...
W0305 10:51:44.178512   53137 node.go:550] [1] Read index context timed out
I0305 10:51:44.178792   53137 zero.go:386] Connected: cluster_info_only:true 
I0305 10:51:44.180116   53137 zero.go:368] Got connection request: addr:"localhost:7080" 
I0305 10:51:44.185650   53137 pool.go:140] CONNECTED to localhost:7080
I0305 10:51:44.202096   53137 zero.go:495] Connected: id:1 group_id:1 addr:"localhost:7080" 
I0305 10:51:44.202704   52500 groups.go:112] Connected to group zero. Assigned group: 1
I0305 10:51:44.205024   52500 draft.go:72] Node ID: 1 with GroupID: 1
I0305 10:51:44.205159   52500 node.go:151] Setting raft.Config to: &{ID:1 peers:[] learners:[] ElectionTick:100 HeartbeatTick:1 Storage:0xc0003cea50 Applied:0 MaxSizePerMsg:1048576 MaxInflightMsgs:256 CheckQuorum:false PreVote:true ReadOnlyOption:0 Logger:0x1f94370 DisableProposalForwarding:false}
I0305 10:51:44.205316   52500 node.go:290] Group 1 found 1 entries
I0305 10:51:44.205343   52500 draft.go:1117] New Node for group: 1
I0305 10:51:44.205413   52500 node.go:83] 1 became follower at term 0
I0305 10:51:44.205493   52500 node.go:83] newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
I0305 10:51:44.205509   52500 node.go:83] 1 became follower at term 1
I0305 10:51:44.206002   52500 groups.go:695] Got address of a Zero leader: localhost:5080
I0305 10:51:44.206139   52500 groups.go:708] Starting a new membership stream receive from localhost:5080.
I0305 10:51:44.208613   52500 node.go:173] Setting conf state to nodes:1 
I0305 10:51:44.209081   52500 node.go:83] 1 is starting a new election at term 1
I0305 10:51:44.209113   52500 node.go:83] 1 became pre-candidate at term 1
I0305 10:51:44.209128   52500 node.go:83] 1 received MsgPreVoteResp from 1 at term 1
I0305 10:51:44.209181   52500 node.go:83] 1 became candidate at term 2
I0305 10:51:44.209196   52500 node.go:83] 1 received MsgVoteResp from 1 at term 2
I0305 10:51:44.209312   52500 node.go:83] 1 became leader at term 2
I0305 10:51:44.209333   52500 node.go:83] raft.node: 1 elected leader 1 at term 2
I0305 10:51:44.212110   52500 groups.go:388] Serving tablet for: _predicate_
I0305 10:51:44.212063   52500 groups.go:725] Received first state update from Zero: counter:4 groups:<key:1 value:<members:<key:1 value:<id:1 group_id:1 addr:"localhost:7080" > > tablets:<key:"_predicate_" value:<group_id:1 predicate:"_predicate_" > > > > zeros:<key:1 value:<id:1 addr:"localhost:5080" leader:true > > maxRaftId:1 
I0305 10:51:44.215537   52500 mutation.go:158] Done schema update predicate:"_predicate_" value_type:STRING list:true 
I0305 10:51:44.221598   52500 groups.go:388] Serving tablet for: dgraph.xid
I0305 10:51:44.223310   52500 index.go:33] Deleting index for dgraph.xid
I0305 10:51:44.223398   52500 index.go:38] Rebuilding index for dgraph.xid
I0305 10:51:44.223461   52500 mutation.go:158] Done schema update predicate:"dgraph.xid" value_type:STRING directive:INDEX tokenizer:"exact" 
I0305 10:51:44.226559   52500 groups.go:388] Serving tablet for: dgraph.password
I0305 10:51:44.227585   52500 mutation.go:158] Done schema update predicate:"dgraph.password" value_type:PASSWORD 
I0305 10:51:44.230098   52500 groups.go:388] Serving tablet for: dgraph.user.group
I0305 10:51:44.231175   52500 index.go:48] Deleting reverse index for dgraph.user.group
I0305 10:51:44.231223   52500 index.go:54] Rebuilding reverse index for dgraph.user.group
I0305 10:51:44.231264   52500 mutation.go:158] Done schema update predicate:"dgraph.user.group" value_type:UID directive:REVERSE 
I0305 10:51:44.234151   52500 groups.go:388] Serving tablet for: dgraph.group.acl
I0305 10:51:44.236028   52500 mutation.go:158] Done schema update predicate:"dgraph.group.acl" value_type:STRING 
I0305 10:51:45.206902   52500 groups.go:850] Leader idx=1 of group=1 is connecting to Zero for txn updates
I0305 10:51:45.206967   52500 groups.go:859] Got Zero leader: localhost:5080
I0305 10:51:46.181361   53137 raft.go:458] CID set for cluster: bb8c0f17-1224-4577-a05b-a90e40df2112
I0305 10:52:05.054637   53137 zero.go:368] Got connection request: cluster_info_only:true 
I0305 10:52:05.054885   53137 zero.go:386] Connected: cluster_info_only:true 
I0305 10:52:05.061038   52500 groups.go:388] Serving tablet for: id
I0305 10:52:05.062743   52500 groups.go:388] Serving tablet for: state
I0305 10:52:05.064257   52500 groups.go:388] Serving tablet for: create_time
I0305 10:52:05.066484   52500 groups.go:388] Serving tablet for: update_time
I0305 10:52:05.069609   52500 groups.go:388] Serving tablet for: group_id
I0305 10:52:05.075209   52500 groups.go:388] Serving tablet for: out_nick
I0305 10:52:05.080432   52500 groups.go:388] Serving tablet for: platform
I0305 10:52:05.081557   52500 groups.go:388] Serving tablet for: mobile
I0305 10:52:05.082715   52500 groups.go:388] Serving tablet for: mix_mobile
I0305 10:52:05.084323   52500 groups.go:388] Serving tablet for: ext
I0305 10:52:05.086680   52500 groups.go:388] Serving tablet for: sys_customer_id
I0305 10:52:05.088602   52500 groups.go:388] Serving tablet for: es_party_time
I0305 10:52:05.101581   53137 zero.go:368] Got connection request: cluster_info_only:true 
I0305 10:52:05.102293   53137 zero.go:386] Connected: cluster_info_only:true 
I0305 10:52:05.137891   53137 zero.go:368] Got connection request: cluster_info_only:true 
I0305 10:52:05.138140   53137 zero.go:386] Connected: cluster_info_only:true 
I0305 10:52:05.174465   53137 zero.go:368] Got connection request: cluster_info_only:true 
I0305 10:52:05.174767   53137 zero.go:386] Connected: cluster_info_only:true 
I0305 10:52:14.669797   52500 draft.go:323] Creating snapshot at index: 249. ReadTs: 436.
I0305 10:52:16.357336   53137 oracle.go:103] Purged below ts:436, len(o.commits):52, len(o.rowCommit):61000
I0305 10:53:16.974291   52500 draft.go:323] Creating snapshot at index: 1559. ReadTs: 2816.
I0305 10:53:20.423920   53137 oracle.go:103] Purged below ts:2816, len(o.commits):102, len(o.rowCommit):111000
I0305 10:53:30.232807   53137 raft.go:552] Writing snapshot at index: 1533, applied mark: 1811
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x1463913, 0x16)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc0bc000000, 0x8000000, 0x1f96318)
	/usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x1f7c680, 0x8000000, 0x60003208b5, 0x7fb5acbaacf8)
	/usr/local/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x1f7c680, 0x2001, 0x0)
	/usr/local/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x1f7c680, 0x2001, 0x1f96328, 0x0)
	/usr/local/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x1f7c680, 0x2001, 0x101, 0x1662e00)
	/usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x1f7c680, 0x2001, 0x7fb5ac010101, 0x891985)
	/usr/local/go/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x400071c, 0x8d0101, 0x7fb5b32ead80)
	/usr/local/go/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1229

goroutine 167 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc00ca88a30 sp=0xc00ca88a28 pc=0x8d6450
runtime.mallocgc(0x400071c, 0x12c6ac0, 0x7fb52268c501, 0xc00ca88b08)
	/usr/local/go/src/runtime/malloc.go:913 +0x896 fp=0xc00ca88ad0 sp=0xc00ca88a30 pc=0x8876e6
runtime.makeslice(0x12c6ac0, 0x400071c, 0x400071c, 0xc0b760a007, 0xc0a997f020, 0x969037)
	/usr/local/go/src/runtime/slice.go:70 +0x77 fp=0xc00ca88b00 sp=0xc00ca88ad0 pc=0x8bf237
bytes.makeSlice(0x400071c, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:231 +0x6d fp=0xc00ca88b40 sp=0xc00ca88b00 pc=0x9693fd
bytes.(*Buffer).grow(0xc0ae77b730, 0x16c, 0x1)
	/usr/local/go/src/bytes/buffer.go:144 +0x15a fp=0xc00ca88b90 sp=0xc00ca88b40 pc=0x968d6a
bytes.(*Buffer).Write(0xc0ae77b730, 0xc09b06ae71, 0x16c, 0x4940488, 0x1, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:174 +0xdc fp=0xc00ca88bc0 sp=0xc00ca88b90 pc=0x96904c
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.(*ValueStruct).EncodeTo(0xc00ca88d30, 0xc0ae77b730)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/iterator.go:86 +0xf5 fp=0xc00ca88c18 sp=0xc00ca88bc0 pc=0xcb13c5
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.(*Builder).addHelper(0xc03b2c0120, 0xc09b06ae4f, 0x1f, 0x49404aa, 0x440, 0x0, 0xc09b06ae71, 0x16c, 0x4940488, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/builder.go:147 +0x21f fp=0xc00ca88d10 sp=0xc00ca88c18 pc=0xcb6b7f
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.(*Builder).Add(0xc03b2c0120, 0xc09b06ae4f, 0x1f, 0x49404aa, 0x440, 0x0, 0xc09b06ae71, 0x16c, 0x4940488, 0x0, ...)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/builder.go:169 +0x83 fp=0xc00ca88d78 sp=0xc00ca88d10 pc=0xcb6e53
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.writeLevel0Table(0xc022a1bac0, 0xc0ae9be2a0, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:794 +0x1f6 fp=0xc00ca88e48 sp=0xc00ca88d78 pc=0xcc7ba6
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).handleFlushTask(0xc000057880, 0xc022a1bac0, 0x2d00000004, 0x2e05783, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:831 +0x133 fp=0xc00ca88f38 sp=0xc00ca88e48 pc=0xcc7dc3
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*DB).flushMemtable(0xc000057880, 0xc0004300c0, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:879 +0xf5 fp=0xc00ca88fc0 sp=0xc00ca88f38 pc=0xcc85b5
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00ca88fc8 sp=0xc00ca88fc0 pc=0x8d8531
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.Open
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:275 +0xe01

goroutine 1 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc0005dc0f8)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc0005dc0f0)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.setupServer()
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:387 +0x688
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.run()
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:504 +0xb0f
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.init.1.func1(0xc00022e240, 0xc000178d80, 0x0, 0x8)
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:81 +0x52
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute(0xc00022e240, 0xc000178c80, 0x8, 0x8, 0xc00022e240, 0xc000178c80)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702 +0x2d3
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1ecd680, 0x9, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute(0x1ecd680, 0x8ac98d, 0x1ed5868)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/dgraph-io/dgraph/dgraph/cmd.Execute()
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:58 +0x36
main.main()
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/main.go:33 +0x88

**Comment by MichelDiz** [comment]
What is the size of your RDF? how much RAM is available to the docker instance?

**Comment by fjbreeze** [comment]
The size of rdf is 15GB and RAM is 4GB

**Comment by MichelDiz** [comment]
It's very little memory available for the size of the RDF as I see it. You should use Bulkloader instead.
And move the Bulk OUT/0/p like `-v /home/out/0/p:/dgraph/p`and make sure you're using the right path.

`docker exec diggy dgraph alpha --lru_mb 1024 --zero localhost:5080 --badger.vlog=disk --badger.tables=disk -p /dgraph/p -w /dgraph/w`

**Comment by fjbreeze** [comment]
RAM: 8GB
```
root@5c3f3e69c7cb:/dgraph# dgraph bulk -r /rdf/ecrp.rdf -s ecrp --map_shards=4 --reduce_shards=2 --http localhost:8000 --zero=localhost:5080
I0306 01:05:42.561515     110 init.go:88] 

Dgraph version   : v1.0.11
Commit SHA-1     : b2a09c5b
Commit timestamp : 2018-12-17 09:50:56 -0800
Branch           : HEAD
Go version       : go1.11.1

For Dgraph official documentation, visit https://docs.dgraph.io.
For discussions about Dgraph     , visit https://discuss.dgraph.io.
To say hi to the community       , visit https://dgraph.slack.com.

Licensed variously under the Apache Public License 2.0 and Dgraph Community License.
Copyright 2015-2018 Dgraph Labs, Inc.


{
        "RDFDir": "/rdf/ecrp.rdf",
        "JSONDir": "",
        "SchemaFile": "ecrp",
        "DgraphsDir": "out",
        "TmpDir": "tmp",
        "NumGoroutines": 8,
        "MapBufSize": 67108864,
        "ExpandEdges": true,
        "SkipMapPhase": false,
        "CleanupTmp": true,
        "NumShufflers": 1,
        "Version": false,
        "StoreXids": false,
        "ZeroAddr": "localhost:5080",
        "HttpAddr": "localhost:8000",
        "IgnoreErrors": false,
        "CustomTokenizers": "",
        "MapShards": 4,
        "ReduceShards": 2
}

The bulk loader needs to open many files at once. This number depends on the size of the data set loaded, the map file output size, and the level of indexing. 100,000 is adequate for most data set sizes. See `man ulimit` for details of how to change the limit.
Current max open files limit: 65536

Connecting to zero at localhost:5080
Processing file (1 out of 1): /rdf/ecrp.rdf
MAP 01s nquad_count:3.512k err_count:0.000 nquad_speed:3.508k/sec edge_count:7.024k edge_speed:7.016k/sec
MAP 02s nquad_count:16.12k err_count:0.000 nquad_speed:8.057k/sec edge_count:32.25k edge_speed:16.11k/sec
MAP 03s nquad_count:366.5k err_count:0.000 nquad_speed:122.1k/sec edge_count:733.1k edge_speed:244.2k/sec
MAP 04s nquad_count:1.080M err_count:0.000 nquad_speed:269.9k/sec edge_count:2.160M edge_speed:539.8k/sec
MAP 05s nquad_count:1.755M err_count:0.000 nquad_speed:350.9k/sec edge_count:3.511M edge_speed:701.8k/sec
MAP 06s nquad_count:2.471M err_count:0.000 nquad_speed:411.7k/sec edge_count:4.943M edge_speed:823.3k/sec
MAP 07s nquad_count:3.154M err_count:0.000 nquad_speed:450.3k/sec edge_count:6.308M edge_speed:900.6k/sec
MAP 08s nquad_count:3.824M err_count:0.000 nquad_speed:477.7k/sec edge_count:7.647M edge_speed:955.4k/sec
MAP 09s nquad_count:4.525M err_count:0.000 nquad_speed:502.5k/sec edge_count:9.051M edge_speed:1.005M/sec
MAP 10s nquad_count:5.183M err_count:0.000 nquad_speed:517.9k/sec edge_count:10.37M edge_speed:1.036M/sec
MAP 11s nquad_count:5.819M err_count:0.000 nquad_speed:528.5k/sec edge_count:11.64M edge_speed:1.057M/sec
MAP 12s nquad_count:6.231M err_count:0.000 nquad_speed:518.8k/sec edge_count:12.46M edge_speed:1.038M/sec
MAP 13s nquad_count:6.607M err_count:0.000 nquad_speed:507.9k/sec edge_count:13.21M edge_speed:1.016M/sec
MAP 14s nquad_count:7.158M err_count:0.000 nquad_speed:510.9k/sec edge_count:14.32M edge_speed:1.022M/sec
MAP 15s nquad_count:7.830M err_count:0.000 nquad_speed:521.6k/sec edge_count:15.66M edge_speed:1.043M/sec
MAP 16s nquad_count:8.506M err_count:0.000 nquad_speed:531.3k/sec edge_count:17.01M edge_speed:1.063M/sec
MAP 17s nquad_count:9.080M err_count:0.000 nquad_speed:533.7k/sec edge_count:18.16M edge_speed:1.067M/sec
MAP 18s nquad_count:9.463M err_count:0.000 nquad_speed:525.4k/sec edge_count:18.93M edge_speed:1.051M/sec
MAP 19s nquad_count:9.622M err_count:0.000 nquad_speed:506.0k/sec edge_count:19.24M edge_speed:1.012M/sec
MAP 20s nquad_count:9.750M err_count:0.000 nquad_speed:485.4k/sec edge_count:19.50M edge_speed:970.8k/sec
MAP 21s nquad_count:9.907M err_count:0.000 nquad_speed:469.7k/sec edge_count:19.81M edge_speed:939.4k/sec
MAP 22s nquad_count:10.09M err_count:0.000 nquad_speed:456.4k/sec edge_count:20.17M edge_speed:912.8k/sec
MAP 23s nquad_count:10.26M err_count:0.000 nquad_speed:444.2k/sec edge_count:20.52M edge_speed:888.4k/sec
MAP 24s nquad_count:10.44M err_count:0.000 nquad_speed:433.2k/sec edge_count:20.89M edge_speed:866.3k/sec
MAP 25s nquad_count:10.78M err_count:0.000 nquad_speed:429.4k/sec edge_count:21.56M edge_speed:858.9k/sec
MAP 26s nquad_count:10.97M err_count:0.000 nquad_speed:420.3k/sec edge_count:21.94M edge_speed:840.5k/sec
MAP 27s nquad_count:11.64M err_count:0.000 nquad_speed:429.4k/sec edge_count:23.28M edge_speed:858.8k/sec
MAP 28s nquad_count:12.40M err_count:0.000 nquad_speed:441.1k/sec edge_count:24.80M edge_speed:882.2k/sec
MAP 29s nquad_count:13.25M err_count:0.000 nquad_speed:455.2k/sec edge_count:26.50M edge_speed:910.3k/sec
MAP 30s nquad_count:14.07M err_count:0.000 nquad_speed:467.2k/sec edge_count:28.14M edge_speed:934.5k/sec
MAP 31s nquad_count:14.87M err_count:0.000 nquad_speed:477.1k/sec edge_count:29.74M edge_speed:954.2k/sec
MAP 32s nquad_count:15.64M err_count:0.000 nquad_speed:486.3k/sec edge_count:31.28M edge_speed:972.6k/sec
Killed

```

**Comment by MichelDiz** [comment]
Again, 8GB is very little memory for 15GB of RDF. Dgraph does several different tasks that requires memory and disk space. See this publication here to better understand:  https://blog.dgraph.io/post/bulkloader/

Bulk or Liveloader need to expand graphs, need to map UIDs, need to go through processing phases. And all this requires resources. You need to test the memory need ratio for 15GB of RDF. This can vary greatly from RDF to RDF. But 8GB is nothing.

In Peter's post the time to run 50GB of RDF was one hour and four minutes. It used 488GB RAM and 500GB NVMe and is running 64 cores. Today Bulkloader and Dgraph have evolved a lot since version v0.8.3. You probably need 20% less resources than that.

From what Peter says it would be necessary, for safety, to have 150GB of free disk space for 15GB of RDF in your case. But this at first moment.

BTW - you don't need "--reduce_shards=2" if you gonna use a single instance. And I would recommend you to use a extension for "ecrp" `-s ecrp.schema`

**Comment by fjbreeze** [comment]
Can I split file that the size is 15GB to 512MB, then import one by one?

**Comment by fjbreeze** [comment]
The docker instance which has 8GB RAM, then i import 512MB of rdf, it also has the same problem.

**Comment by MichelDiz** [comment]
Reduce to small pieces that would be great. And you can use LiveLoad normally. In this case I would recommend using the flag xidmap: " -x, --xidmap string: Directory to store xid to uid mapping". 

Using xidmap you will preserve the UIDs by BlankNode. So you can pick up where you left off and keep the data consistent. (always using the same xidmap path for all loads)

Using 21million.rdf.gz from https://github.com/dgraph-io/benchmarks/tree/master/data/release
this RDF has 167,4 MB - It consumed almost 21GB in total (counting with my running applications like chrome) at a peak moment (I have 32GB in local machine - not docker) - So it needs like 13GB so I would recommend 20GB or at least 16GB for 167,4 MB RDF.

It took 3 min to finish.

![captura de tela 2019-03-06 as 00 46 43](https://user-images.githubusercontent.com/6570955/53854820-bb8b4400-3fa9-11e9-88cf-c646cef7b1c0.png)

![captura de tela 2019-03-06 as 00 45 19](https://user-images.githubusercontent.com/6570955/53854826-c2b25200-3fa9-11e9-81b5-3f172b24a864.png)
![captura de tela 2019-03-06 as 00 44 01](https://user-images.githubusercontent.com/6570955/53854848-d362c800-3fa9-11e9-915b-9925da60824a.png)

**Comment by fjbreeze** [comment]
Thanks. I have a try.

**Comment by fjbreeze** [comment]
I split 15GB of RDF to many RDF file that every file contains 1000000 records (about 50MB), then use `Liveloader` to import data one by one with `-x ./xmap`, it works well.

**Comment by MichelDiz** [comment]
In that case you would have to wait for a cooling down. OR I would recommend you to shutdown the Dgraph Alpha, so check this https://docs.dgraph.io/deploy/#shutdown-database - this will shutdown Dgraph safely. And then you restart the container for a new load (keeping the xidmap). 

The easiest solution would be to give the container proper resources.
Maybe more cores, a faster Disk like a NVMe with high IOPS (like 100K IOPS +) and more RAM.
It is interesting to have a balanced machine, because if something is missing it will require more RAM so...

I gonna close this, if you need more support open a discussion at https://discuss.dgraph.io
We already have a issue to track improvement in Bulkload see the list: 
https://github.com/dgraph-io/dgraph/issues/3017
https://github.com/dgraph-io/dgraph/issues/2628

If you make a new report for LiveLoader based on #3017 it would be very welcome. I can do it, but if you want to do it, feel free. I think he is using 21mi.RDF

PS. + Recommended read https://blog.dgraph.io/post/scaling-dgraph/

Cheers
