### ISSUE TITLE
"This entry should have been caught" warning during data ingestion

### ISSUE THREAD

**Issue by jgoodall** [dgraph-io/dgraph#3098]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

1.0.12rc6 and rc7

- Have you tried reproducing the issue with latest release?

Yes, rc7.

- What is the hardware spec (RAM, OS)?

3 alpha nodes on Ubuntu 16.04.6 LTS, 1 zero node on Ubuntu 16.04.6 LTS. 128gb ram, `DGRAPH_ALPHA_LRU_MB` set to 65536.

- Steps to reproduce the issue (command/config used to run Dgraph).

Ingest a large amount of data.

- Expected behaviour and actual result.

Cluster to not throw warnings.

Log files on two of the three alpha nodes have entries like this:

```
I0304 23:23:38.457831       1 node.go:83] Rolling up Created batch of size: 2.8 MB in 125.105917ms.
I0304 23:23:40.718801       1 node.go:83] Rolling up Created batch of size: 4.2 MB in 2.139981537s.
W0304 23:23:55.356076       1 node.go:85] This entry should have been caught. {Key:[0 0 4 78 97 109 101 2 1 99 114 121 115 116 97 108 255 2
55 255 255 255 255 189 176] Value:[10 146 141 4 8 128 2 18 233 3 8 192 85 18 227 3 68 233 9 200 178 1 170 17 220 80 252 182 1 211 42 215 35 ... ] UserMeta:8 ExpiresAt:0 meta:68 offset:22155878}
```

(There are pages and pages I elided for readability.)

I dont know if this warning is because I am trying to ingest bad data or if the server/cluster is having issues, but it is not a helpful error message.

**Comment by srfrog** [comment]
This is a warning from the Badger API. It sometimes means that the value is no longer needed although it was scheduled for write.

I wouldn't worry about it unless you see an abnormal amount of these.
