### ISSUE TITLE
Bug: "After" func from Pagination started to miss behave since v1.0.10.

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#3109]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
Tested in:
```
Dgraph version   : v1.0.8
Commit SHA-1     : 1dd8376f
Commit timestamp : 2018-08-31 10:47:07 -0700
Branch           : HEAD
```
```
Dgraph version   : v1.0.9
Commit SHA-1     : 22c13fce
Commit timestamp : 2018-10-02 16:45:53 -0700
Branch           : HEAD
```

Started at v1.0.10
```
Dgraph version   : v1.0.10
Commit SHA-1     : 8b801bd7
Commit timestamp : 2018-11-05 17:52:33 -0800
Branch           : HEAD
```

- Have you tried reproducing the issue with latest release?
Yes, not working as supposed since v1.0.10

- What is the hardware spec (RAM, OS)?
Darwin - 32GB

- Steps to reproduce the issue (command/config used to run Dgraph).
Run a paging query.
```
{
  me(func: allofterms(name@en, "Baz Luhrmann")) {
    name@en
    director.film (first:5, after: 0x5488ac) 
    {
      uid
      name@en
    }
  }
}
```
The bad result shows the movie was setup to be a parameter for "after".
So the results for latests Dgraph's versions is more like a “since” than an “after”.

It show the 0x55730d "Strictly Ballroom" movie in the result.
![captura de tela 2019-03-08 as 13 22 37](https://user-images.githubusercontent.com/6570955/54041851-86e4db80-41a7-11e9-8e6d-65f9464aa135.png)

- Expected behaviour and actual result.

This is the expected
![captura de tela 2019-03-08 as 13 08 54](https://user-images.githubusercontent.com/6570955/54041929-bbf12e00-41a7-11e9-8bd9-bdd8fd851406.png)

It should behave as says docs and as behaved in old versions.

PS. Nice finding with @danielmai after doing some updates in Docs.

**Comment by srfrog** [comment]
Is `0x5488ac` part of the result set? What you are describing is `after: 0x55730d, first 5`.

**Comment by MichelDiz** [comment]
Ignore this, it should be "0x55730d". 
This is probably from another test that I paste wrong.

**Comment by MichelDiz** [comment]
@srfrog No Guys, I didn't mean that the case was closed. This still persist and was Dmai who found it.
