### ISSUE TITLE
SrcUIDs shouldn't be nil - irrecoverable error

### ISSUE THREAD

**Issue by afarqu** [dgraph-io/dgraph#3110]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

v1.0.12

- Have you tried reproducing the issue with latest release?

Yes

- What is the hardware spec (RAM, OS)?

Kubernetes, Docker https://hub.docker.com/r/dgraph/dgraph
AWS t2-medium %GB RAM

- Steps to reproduce the issue (command/config used to run Dgraph).

I am really not sure what query was run, but I suspect that it was something like:

```
{
  "set": [
    {
      "uid": "0x3",
      "user_id": "d9931e32-fb31-432d-bb0b-465c70bc9efc",
      "score": 0
    }
  ]
}
```

Then I ran:

```
{
  set: {
    <0x3> <in_campaign> <0xa> (objectId="2c77eb4b-4bbe-475d-801f-e88af2a310f8") .

  }
}

```
Which gave me the error: "Invalid mutation formatting."

The server then stopped responding and throws the error on all node and fails to restart:

```
SrcUIDs shouldn't be nil.
github.com/dgraph-io/dgraph/x.AssertTruef
	/ext-go/1/src/github.com/dgraph-io/dgraph/x/error.go:79
github.com/dgraph-io/dgraph/query.ProcessGraph
	/ext-go/1/src/github.com/dgraph-io/dgraph/query/query.go:1912
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333
```

**Comment by srfrog** [comment]
Thank for reporting this. I'm having trouble trying to reproduce the bug. Do you mind sharing your `schema{}` ? Or at least any indexes used in that query? Cluster configuration? Any specific Zero/Alpha flags?

I did try the second mutation as RDF and got `Invalid mutation formatting` as expected, but no crash. Anything else you can think of would be helpful.

**Comment by afarqu** [comment]
I deployed using: https://github.com/dgraph-io/dgraph/blob/master/contrib/config/kubernetes/dgraph-ha.yaml

Our schema is:

<business_id>: string @index(hash) @upsert .
<campaign>: uid .
<campaign_id>: string @index(hash) @upsert .
<has_interest>: uid @reverse .
<in_business>: uid @reverse .
<in_campaign>: uid @reverse .
<interest_id>: string .
<location>: geo .
<name>: string @index(fulltext, hash, term, trigram) @lang .
<sent>: uid @reverse .
<shared>: uid @reverse .
<type>: string .
<user_id>: string @index(hash) @upsert .

There is not much data in the system, so perhaps I can export it without a running server?

**Comment by afarqu** [comment]
After 11 restart attempts, it came back - not sure why. I am attaching the current logs to see if that might shed some light.

[logs-from-alpha-in-dgraph-alpha-0.txt](https://github.com/dgraph-io/dgraph/files/2947340/logs-from-alpha-in-dgraph-alpha-0.txt)
[logs-from-alpha-in-dgraph-alpha-1.txt](https://github.com/dgraph-io/dgraph/files/2947341/logs-from-alpha-in-dgraph-alpha-1.txt)
[logs-from-alpha-in-dgraph-alpha-2.txt](https://github.com/dgraph-io/dgraph/files/2947342/logs-from-alpha-in-dgraph-alpha-2.txt)

**Comment by srfrog** [comment]
Thanks for that, I will take a look. I have reopened the issue because this is a bug. Nobody should be required to restart X times to fix problems.

**Comment by mooncake4132** [comment]
I also encountered this issue today. I can reproduce the issue quite reliably by making the following queries. No additional schema required.
```
{
  q(func: ge(uid, 1)) {}
}
```
This should give a `"Argument cannot be \"uid\""` error.

```
{
  q(func: eq(uid, 1)) {}
}
```
This should give a `"Could not connect to the server: Failed to fetch"` error.

Then, in the logs I can see alpha crashed:
```
server_1  | 2019/03/09 00:29:57 SrcUIDs shouldn't be nil.
server_1  | github.com/dgraph-io/dgraph/x.AssertTruef
server_1  |     /ext-go/1/src/github.com/dgraph-io/dgraph/x/error.go:79
server_1  | github.com/dgraph-io/dgraph/query.ProcessGraph
server_1  |     /ext-go/1/src/github.com/dgraph-io/dgraph/query/query.go:1912
server_1  | runtime.goexit
server_1  |     /usr/local/go/src/runtime/asm_amd64.s:1333
```

**Comment by srfrog** [comment]
@mooncake4132 that triggers the assertion, but IMO due to a different reason. The recommended way is to use the `uid()` function.
```
{
  q(func:uid(1)) {}
}
```
I do agree it shouldn't get too far from parsing, since we dont allow "uid" as attribute in `eq()`. You can use the value `"uid"` though.
```
{
  q(func:eq(name, "uid")) {}
}
```
Thanks for pointing this out.

**Comment by danielmai** [comment]
Someone ran this query on Play:
```
query {
  kid(func: eq(uid, "_:michael")) {
    uid
    age
  }
}
```

Alpha log showed this correspending error log (introduced in v1.0.13):
```
E0311 20:09:54.819921       1 query.go:1913] SrcUIDs is unexpectedly nil. Subgraph: &{ReadTs:781391 Attr: Params:{Alias:kid Count:0 Offset:0 AfterUID:0 DoCount:false GetUid:true Order:[] Var: NeedsVar:[] ParentVars:map[] FacetVar:map[] uidToVal:map[] Langs:[] Normalize:false Recurse:false RecurseArgs:{Depth:0 AllowLoop:false} Cascade:false IgnoreReflex:false From:0 To:0 Facet:<nil> FacetOrder: FacetOrderDesc:false ExploreDepth:0 isInternal:false ignoreResult:false Expand: isGroupBy:false groupbyAttrs:[] uidCount:false uidCountAlias: numPaths:0 parentIds:[] IsEmpty:false expandAll:false shortest:false} counts:[] valueMatrix:[] uidMatrix:[] facetsMatrix:[] ExpandPreds:[] GroupbyRes:[] LangTags:[] SrcUIDs:<nil> SrcFunc:0xc0389b3a70 FilterOp: Filters:[] facetsFilter:<nil> MathExp:<nil> Children:[0xc01e2a82c0 0xc01e2a8580] DestUIDs: List:false}
```

**Comment by srfrog** [comment]
The attached PR will trigger an error for that, instead of panic. The problem is using `uid` as function attribute.
