### ISSUE TITLE
Dgraph got stuck on TryAbort

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#3113]
dgraph version: v1.0.12-rc7

after some time both 3 nodes in a cluster (`replicas` is set to 3) got stuck on queries and mutations.
on one node there were repeated 5 messages all the time, other 2 nodes were silent:
```
  | Mar 09 10:44:48.578 | i-0a1dee3345f5ac69a | dgraph-alpha | TryAbort selectively proposing only aborted txns: txns:<start_ts:2768399 > txns:<start_ts:2764094 > txns:<start_ts:2766829 > txns:<start_ts:2763437 > txns:<start_ts:2771222 > txns:<start_ts:2771295 > txns:<start_ts:2763699 > txns:<start_ts:2762973 > txns:<start_ts:2771291 > txns:<start_ts:2766012 > txns:<start_ts:2766353 > txns:<start_ts:2768769 > txns:<start_ts:2766843 > txns:<start_ts:2761654 > txns:<start_ts:2765734 > txns:<start_ts:2770411 > txns:<start_ts:2771288 > txns:<start_ts:2761024 > txns:<start_ts:2767084 > txns:<start_ts:2770081 > txns:<start_ts:2765745 > txns:<start_ts:2762561 > txns:<start_ts:2763424 > txns:<start_ts:2764691 > txns:<start_ts:2771076 > txns:<start_ts:2771293 > txns:<start_ts:2761306 > txns:<start_ts:2769567 > txns:<start_ts:2764983 > txns:<start_ts:2764674 > txns:<start_ts:2762200 > txns:<start_ts:2765309 > txns:<start_ts:2769909 > txns:<start_ts:2762182 > txns:<start_ts:2769235 >
  | Mar 09 10:44:48.578 | i-0a1dee3345f5ac69a | dgraph-alpha | TryAbort returned with delta: txns:<start_ts:2768399 > txns:<start_ts:2764094 > txns:<start_ts:2766829 > txns:<start_ts:2763437 > txns:<start_ts:2771279 commit_ts:2771285 > txns:<start_ts:2771222 > txns:<start_ts:2771295 > txns:<start_ts:2763699 > txns:<start_ts:2762973 > txns:<start_ts:2771291 > txns:<start_ts:2771309 commit_ts:2771319 > txns:<start_ts:2766012 > txns:<start_ts:2766353 > txns:<start_ts:2768769 > txns:<start_ts:2766843 > txns:<start_ts:2761654 > txns:<start_ts:2765734 > txns:<start_ts:2770411 > txns:<start_ts:2771288 > txns:<start_ts:2771277 commit_ts:2771281 > txns:<start_ts:2771278 commit_ts:2771282 > txns:<start_ts:2771308 commit_ts:2771317 > txns:<start_ts:2761024 > txns:<start_ts:2767084 > txns:<start_ts:2770081 > txns:<start_ts:2765745 > txns:<start_ts:2762561 > txns:<start_ts:2763424 > txns:<start_ts:2764691 > txns:<start_ts:2771296 commit_ts:2771298 > txns:<start_ts:2771076 > txns:<start_ts:2771293 > txns:<start_ts:2761306 > txns:<start_ts:2769567 > txns:<start_
  | Mar 09 10:44:48.578 | i-0a1dee3345f5ac69a | dgraph-alpha | TryAbort 43 txns with start ts. Error: <nil>
  | Mar 09 10:44:48.336 | i-0a1dee3345f5ac69a | dgraph-alpha | Found 43 old transactions. Acting to abort them.
  | Mar 09 10:44:48.336 | i-0a1dee3345f5ac69a | dgraph-alpha | Skipping snapshot at index: 1406976. Insufficient discard entries: 0. MinPendingStartTs: 2761024
```
we had yesterday an issue with loading to dgraph, we didn't escape `\` symbol in one place, so that mutation failed with `header size exceeded` error and was repeated infinitely until we fixed this bug. maybe it was the case of further problems. but anyway, it shouldn't lead to overall cluster stuck

**Comment by manishrjain** [comment]
It's not clear from these snippets what's the issue. Can you share full logs?

**Comment by makitka2007** [comment]
these 5 messages were repeating in a sequence for all the night, and all nodes were hanging on queries/mutations
please find full log here https://drive.google.com/file/d/1Gq1nKE8MKd3NmknCUYqxuhhd4ZI-d-Ic/view?usp=sharing
so you can check what was there before it starts

**Comment by manishrjain** [comment]
Are you sure it's rc7 and not v1.0.12?

**Comment by manishrjain** [comment]
Actually this might be because of the writes to disk failing repeatedly -- until the write happens, all future proposals would not have a chance to run. Have a look at this flag: `--max_retries`. You can set it to a positive number, and see if that fixes the issue.

**Comment by makitka2007** [comment]
why do you think it's 1.0.12? we switched back to 1.0.12-rc7 because i thought that this issue was related to GA release only.

header size error was on client size, seems like it's GRPC error, we had it when we used dgraph4j and didn't escape special character in a query or a mutation. in this case we did `eq` query with not escaped `\\` character inside a string parameter. so we got this error:
```
io.grpc.StatusRuntimeException: INTERNAL: http2 exception
...java stacktrace...
Caused by: io.netty.handler.codec.http2.Http2Exception: Header size exceeded max allowed size (10240)
```

yes, when i restarted nodes, it helped, but we need self-healing system, so it doesn't need human intervention to continue work.
we can try to set `max_retries` to avoid such cases in future. what value do you suggest here not to loose data in case of network/node failure/other temporarily issues?

**Comment by manishrjain** [comment]
> but we need self-healing system, so it doesn't need human intervention to continue work.

You'd need to put some mechanism in place to achieve that. You could use `dgraph increment` tool to check if each Alpha is able to successfully process a simple counter increment. If not, you could raise an alert or automatically restart that Alpha.

Of course, I'm more interested in why it happened, but hard to say why it happened from the logs.

> we can try to set max_retries to avoid such cases in future. what value do you suggest here not to loose data in case of network/node failure/other temporarily issues?

This would only be triggered if Badger returns an error, most likely due to failing to write to disk. Network issues, etc. won't factor in that, they're a layer above.

**Comment by makitka2007** [comment]
ok, thank you.
so, some value like `10` there would be enough?

i'll try to create some testcase which can reproduce this issue

**Comment by makitka2007** [comment]
@manishrjain ok, seems like i am able to reproduce my case. it's quite simple
i just ran 1 zero and 1 alpha (v.1.0.13)
```
dgraph zero --replicas 3 --idx 10 --my 10.66.10.49:5080 -o 0
```
```
dgraph alpha --lru_mb 1024 --my 10.66.10.49:7080 -o 0 --zero 10.66.10.49:5080
```
then i just ran mutation using HTTP interface but *without* `X-DGraph-CommitNow` header. so i didn't commit a transaction:
```
POST 10.66.10.49:8080/mutate
{
    set {
        _:node <p> "" .
    }
}
```
after that i just wait for 10 minutes or a little bit more
then all queries on this node got stuck. for example this one:
```
POST 10.66.10.49:8080/query?ro=true
{
    q(func: has(p)) {
        count(uid)
    }
}
```

in the logs on alpha there are following messages:
```
I0311 14:15:59.739153   16283 groups.go:394] Serving tablet for: p
I0311 14:21:25.824778   16283 draft.go:925] Found 1 old transactions. Acting to abort them.
I0311 14:21:25.827384   16283 draft.go:885] TryAbort 1 txns with start ts. Error: <nil>
I0311 14:21:25.827397   16283 draft.go:892] TryAbort returned with delta: txns:<start_ts:1 >
I0311 14:21:25.827450   16283 draft.go:909] TryAbort selectively proposing only aborted txns: txns:<start_ts:1 >
I0311 14:21:25.829625   16283 draft.go:928] abortOldTransactions for 1 txns. Error: <nil>
```

with `be=true` it hangs as well.

i think it's the case why we have all our problems for last time. nodes got stuck for all the time and i have to restart them manually because they answer `OK` for healthcheck. but all mutations and queries just run forever
it would be cool if you fix this issue in next release or at least some rc

**Comment by makitka2007** [comment]
i created separate issue with this test case to track it: https://github.com/dgraph-io/dgraph/issues/3128

**Comment by manishrjain** [comment]
#3128 is now fixed. Closing this issue.
