### ISSUE TITLE
provide more details for processing time

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#3114]
it would be great if you add possibility to track how much time is processed for each part of work when running a query. for now there are parse and encoding time, which are usually pretty low, and processing time which can be high or low without any details why is it such.
for example, i loaded all my data to 3 nodes cluster. when it finished loading, i was running complex queries on both 3 nodes and they were pretty fast (few hundreds of milliseconds which is good for such queries). but then, after some time without any reason, queries began to take more than 10 seconds to complete. also, one node was even slower then others. i restarted all nodes, and now my queries are running fast again.
so, i was trying to understand what was the problem. the one thing i could observe is `processing_ns` field, which said that processing took 100ms or 20 seconds for the same query. was it alpha waiting an answer from zero? or it was just reading a lot of sstables, or something else? it was hard to debug and determine the initial case of this problem.
if `processing_ns` could be split to some parts like "waiting for zero", "index read", "posting list read" and other parts, it would be useful to debug problems with query performance

**Comment by manishrjain** [comment]
At this point, you're looking for distributed query tracing. Dgraph integrates with OpenCensus and we recommend setting up Jaeger instance, so you can take a sample of queries via the `--trace ` flag, and see why they took long.

https://docs.dgraph.io/deploy/#examining-traces-with-jaeger
