### ISSUE TITLE
No warning on bulk import without existing schema / no schema creation on bulk load...

### ISSUE THREAD

**Issue by niravmehta** [dgraph-io/dgraph#3117]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
1.0.12

- Have you tried reproducing the issue with latest release?
Yes, on the latest release

- What is the hardware spec (RAM, OS)?
Mac OS, 16gb RAM

- Steps to reproduce the issue (command/config used to run Dgraph).

1. Reset existing db with `curl -s localhost:8080/alter -d '{ "drop_all": true }'`
2. Followed the [Bulk loading docs](https://docs.dgraph.io/deploy/#bulk-loader) and Graphoverflow [data setup instructions](https://github.com/dgraph-io/graphoverflow). 
3. Except one thing: I forgot to create the schema before importing the data. Or rather, I assumed that the bulk loader will create the schema automatically, since I was passing it in the command line argument.
4. Shut down dgraph zero, moved the out/0/p folder and started zero, alpha and ratel.

- Expected behaviour and actual result.

1. Ratel showed the schema, but counts were zero for all predicates.
2. Altering and recreating the schema did not work. 
3. Removing the p folder, starting over again, creating the schema, pasting back the p folder and starting servers again did not work either.
4. I had to do the entire process again. Reset db, create schema, bulk load, restart servers. Then the data showed up.

First of all, I expected bulk loader will create the schema. Which it probably did - because I could see the schema in Ratel. But counts were 0 all over.

Secondly, there was no warning in bulk loader that schema is not already defined (if that's what it expected).

**Comment by MichelDiz** [comment]
hmmm,

Well Bulkload doesn't create the schema. It only asks for it to create indexing and so on. Your schema will be setup with "defaults" when you start your Alpha group.

Other point is, .schema is mandatory in Bulkload. If you put a different one or an empty. You gonna have a "schema" only when start your Alpha group.

Can you share the commands you used to run Bulkload? You case may related to this fix https://github.com/dgraph-io/dgraph/pull/3065

Cheers.

**Comment by niravmehta** [comment]
```
curl -s localhost:8080/alter -d '{ "drop_all": true }'
curl localhost:8080/admin/shutdown
dgraph bulk -r ./graphoverflow/data/output/ -s ./graphoverflow/schema.txt -z localhost:5080 --http localhost:8000

pkill dgraph-ratel
pkill dgraph
mv ./out/0/p ./
dgraph zero &
dgraph alpha --lru_mb 2048 --zero localhost:5080 &
dgraph-ratel &
```

That's how I ran bulk loader the first time around, when counts showed 0 all over.

Creating the schema before running the bulk loader worked.

**Comment by MichelDiz** [comment]
Nice!

BTW, try to let the schema file as *.schema
