### ISSUE TITLE
password type

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3118]
Can the documentation make clear that the password type automatically encrypts or hashes the password data. From the text, I'm not sure if I pass in plain text and dgraph calculates the hash and stores it behind the scenes.

Also can the documentation state whether it is using bcrypt (the old industry standard) or argon2 (the new industry standard): https://godoc.org/golang.org/x/crypto/argon2

That way if it is using brcypt, I can take care of encoding the password myself using argon2.

**Comment by srfrog** [comment]
Yes, you would create the password type and assign values to it. Dgraph will take your plain text and encrypt it in the background using Bcrypt.

```
# Schema
pass: password .
```

**Comment by pjebs** [comment]
There should be a way to configure hashing algorithm for dgraph.

**Comment by srfrog** [comment]
If you have a suggestion I would start by gathering user support in our forum. From there we can turn it into a feature request that will go into a release.

Dgraph forum - https://discuss.dgraph.io

**Comment by pjebs** [comment]
Django docs - https://docs.djangoproject.com/en/2.1/topics/auth/passwords/
Laravel docs - https://laravel.com/docs/5.8/hashing

**Comment by srfrog** [comment]
I understand, but what I mean is that we like to get other users' input before making changes to API functions. It's part of the process of turning requests into features.
