### ISSUE TITLE
Embedded dgraph

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3132]
What would need to happen for embedded dgraph to come back. What was the last version that contained it?

**Comment by manishrjain** [comment]
Sorry, we have no intention to build an embedded Dgraph. Dgraph is a complex distributed system -- it's hard to push all that into a library.

**Comment by manishrjain** [comment]
Dockerization is very easy these days, so I'd recommend running Dgraph in a Docker container if the need is around easy deployment.

**Comment by pjebs** [comment]
The space I was thinking about was mobile.
Cayley with sqlite is probable the only way forward for mobile for me.
