### ISSUE TITLE
Feature: Connection Pool

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3136]
Sample Code
```
conn, err := grpc.Dial("127.0.0.1:9080", grpc.WithInsecure())
	if err != nil {
		log.Fatal("While trying to dial gRPC")
	}
	defer conn.Close()

	dc := api.NewDgraphClient(conn)
	dg := dgo.NewDgraphClient(dc)

	op := &api.Operation{}
	op.Schema = `
		user: bool .
	`

	err = dg.Alter(context.Background(), op)
	if err != nil {
		log.Fatal(err)
	}
```

**Comment by pjebs** [comment]
It would be nice if rather than every time wanting to make a query, create a grpc connection and then close.

The other alternative is the store `conn` or `dc` globally.

In that case, can the documentation be updated to show how to best do that? Perhaps in `readme` of Go client repo. Is it `dc` we should store globally? Or `dg`? Or just the `conn`?


Even better still, can we have a "connection pool" that also deals with redialling in case of disconnection etc. Perhaps the pool can contain multiple connections to database for extra performance.

**Comment by pjebs** [comment]
Maybe even a `Ping()` function to test the connection.

**Comment by pjebs** [comment]
The `database/sql` pool we know we just have to keep a `*sql.DB` around globally and everything just works.

**Comment by pjebs** [comment]
https://github.com/processout/grpc-go-pool

**Comment by codexnull** [comment]
Connection pooling is currently outside the scope of the Dgraph client. There is no need to create and destroy a gRPC connection for every request, however. You can do something like

```
var apiClients []api.DgraphClient
for _, sockAddr := range []string{"alpha:9080", "beta:9080", "gamma:9080",
                                  "alpha:9080", "beta:9080", "gamma:9080"} {
    conn, err := grpc.Dial(sockAddr, grpc.WithInsecure())
    // error checking...
    apiClients = append(apiClients, api.NewDgraphClient(conn))
}
dc := dgo.NewDgraphClient(apiClients...)
```

to create a client with a pool of six backing gRPC connections. You can then either store `dc` globally or pass it to functions that access the database.
