### ISSUE TITLE
first: 0 is same as first: 1

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3153]
first: 0 is same as first: 1
Obviously there is no reason to ever apply first:0 in practice but it's inconsistent.

**Comment by srfrog** [comment]
`first: 0` effectively disables the pagination counter. It is not intended to return an empty set.

**Comment by pjebs** [comment]
I can only assume the behind the scenes it is due to Go's zero value. I still think this is wrong. first 0 should return an empty set as intuition dictates.

**Comment by srfrog** [comment]
The `first:` argument takes negative and positive values to return results from the end or the start. I'm not disagreeing with you on this. But the change would affect users that depend on this functionality. I think it would be best to post this on our forum and get others' feedback to turn it into a new feature.

Please post your idea here and let others comment: https://discuss.dgraph.io/
