### ISSUE TITLE
feature request: in

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3155]
The `uid( )` function allows a list of uid's.
It would be great for a way to do that with any indexed predicate:

`name ("Harry", "Sally", "Tom")`

I think it is a lot more convenient than `@filter`

Right now I need to build the @filter string for each item:

```
@filter(  
eq(node.hashid, "n6i6zujsqq") or eq(node.hashid, "7nil4u7sw2")    or eq(node.hashid, "y1il9u7sk5") ...
)
```

It is much more cleaner to just do (amongst other ways):

```
in(node.hashid, "n6i6zujsqq", "7nil4u7sw2", "y1il9u7sk5", ...)

```

**Comment by MichelDiz** [comment]
GraphQL +- is based on GraphQL and now as Dgraph is part of [GraphQL foundation](https://www.linuxfoundation.org/press-release/2019/03/the-graphql-foundation-announces-collaboration-with-the-joint-development-foundation-to-drive-open-source-and-open-standards/)  we do not think in change the query syntax in short time.

**Comment by pjebs** [comment]
so is GraphQL+- getting deprecated as "preferred syntax" in favour of GraphQL?

**Comment by MichelDiz** [comment]
Not exactly, It means that Dgraph gonna focus in make GraphQL 100% compatible with Dgraph. Not sure if GraphQL+- would be deprecated. But definitely GraphQL will come up.

**Comment by manishrjain** [comment]
We'll align GraphQL+- more closely with the official spec of GraphQL. It might still not be 100% compatible.

Functions are not defined in the official spec. That's something we introduced in GraphQL+-.

Equality function allows this: `eq(predicate, [val1, val2, ..., valN])` https://docs.dgraph.io/query-language/#inequality

**Comment by MichelDiz** [comment]
BTW @pjebs by the link that Manish shared I remembered that you can do what you wanna to do just like this:

`@filter( eq(node.hashid, ["n6i6zujsqq","7nil4u7sw2","y1il9u7sk5"]) )`

**Comment by MichelDiz** [comment]
I think this is solved by Manish's link.

If you need more questions please do at Discuss https://discuss.dgraph.io 
or Slack https://dgraph.slack.com
