### ISSUE TITLE
Support for OpenCypher

### ISSUE THREAD

**Issue by shunpeizhang** [dgraph-io/dgraph#3157]
Hello!  What is the current progress of dgraph support Open Cypher and Gremlin? We currently want to implement dgraph support Open Cypher. If the official has already implemented some, we want to continue development on your basis .support Open Cypher from the implementation difficulty, How long does it take?

**Comment by MichelDiz** [comment]
The official answer you can find in the roadmap issue. https://github.com/dgraph-io/dgraph/issues/2894#issuecomment-454955797

**Comment by wuyanxing** [comment]
When can  be achieved ?@MichelDiz

**Comment by MichelDiz** [comment]
Quote from the Roadmap Issue.
> "No concrete plans for Open Cypher yet. We'll see about that if that changes and the year progresses". Manish.
