### ISSUE TITLE
What about the architecture?

### ISSUE THREAD

**Issue by wuyanxing** [dgraph-io/dgraph#3158]
The issue tracker is not for questions.

If you have a question, please ask it on https://discuss.dgraph.io
Our Docs: https://docs.dgraph.io/
Slack Channel: https://slack.dgraph.io/

**Comment by MichelDiz** [comment]
We gonna have several blog posts about Dgraph features and architecture. Just follow https://twitter.com/dgraphlabs or keep one eye on https://blog.dgraph.io/

**Comment by ccorcos** [comment]
@wuyanxing I believe Dgraph works a lot like Datomic which has some nice reading about how it works here: https://docs.datomic.com/cloud/whatis/data-model.html
