### ISSUE TITLE
documentation: NewReadOnlyTxn()

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3159]
Can Go client docs specify if a transaction derived from  `NewReadOnlyTxn()` requires a commit or discard?

**Comment by martinmr** [comment]
You cannot call Commit on a read-only transaction but you can call Discard (although it's a no-op in transactions that do not have mutations). I'll update the dgo docs.

**Comment by pjebs** [comment]
what about godoc. It is empty.
