### ISSUE TITLE
Bug report: recurse doesn't seem to return intuitively expected results.

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3160]
To illustrate the issue, I removed the "recursive" nature of the query. In my actual query, I also follow a edge. Either way, this query illustrates the problem.

```
{  
	find(func: eq(node.hashid, "7nil4uzhw5"))  @recurse(loop: false) {
    uid
    node.owner {
      uid
      user.name
      user.email
    }
  }
}
```

Returns:

```
{
  "data": {
    "find": [
      {
        "uid": "0x4e78",
        "node.owner": [
          {
            "uid": "0x4e3b"
          }
        ]
      }
    ]
  }
}
```

**Comment by pjebs** [comment]
```
{  
	find(func: eq(node.hashid, "7nil4uzhw5"))   {
    uid
    node.owner {
      uid
      user.name
      user.email
    }
  }
}
```

returns

```
{
  "data": {
    "find": [
      {
        "uid": "0x4e78",
        "node.owner": [
          {
            "uid": "0x4e3b",
            "user.name": "thehonestscoop",
            "user.email": "thehoddsnestscoopd2@gmail.com"
          }
        ]
      }
    ]
  }
}

```

**Comment by pjebs** [comment]
The `@recurse` directive makes me loose the `user.name` and `user.email` but I require those information.

**Comment by manishrjain** [comment]
Try without putting them in a nested list.

```
{  
	find(func: eq(node.hashid, "7nil4uzhw5"))  @recurse(loop: false) {
    uid
    node.owner
    user.name
    user.email
  }
}
```

**Comment by pjebs** [comment]
That worked. Can you explain in the docs why that is the case.
The inconsistency I see is: 
If I remove `@recurse`, it doesn't work. When it's there, it works.

**Comment by danielmai** [comment]
The recurse docs say it only takes in a single level of predicated to traverse.

https://docs.dgraph.io/query-language/#recurse-query

> You can specify only one level of predicates after root. These would be traversed recursively.
