### ISSUE TITLE
@recurse depth and facets producing intuitively wrong results

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3163]
If I do a recurse query with a depth that prevents an edge from getting traversed, but the edge contains a facet, the produced outout seems wrong:

```
spew (main.RootChain) {
 Chain: ([]main.ChainModel) (len=1 cap=4) {
  (main.ChainModel) {
   UID: (string) (len=6) "0x4e78",
   HashID: (string) (len=10) "7nil4uzhw5",
   XData: (string) (len=35) "{\"test\":\"xxx\",\"sdagsdg\":[\"sdgsdg\"]}",
   Parent: ([]main.ChainModel) (len=1 cap=4) {
    (main.ChainModel) {
     UID: (string) "",
     HashID: (string) "",
     XData: (string) "",
     Parent: ([]main.ChainModel) <nil>,
     Facet: (*string)(0xc0002aa030)((len=8) "required")
    }
   },
   Facet: (*string)(<nil>)
  }
 }
}

```

**Comment by pjebs** [comment]
What you are meant to see from above is: 

1. Parent is a edge.
2. Depth value prevents expansion of edge
3. Edge has a facet

Produces intuitively wrong output.

**Comment by pjebs** [comment]
To makes parsing the json and transforming it trickier in my use-case.

**Comment by pjebs** [comment]
Perhaps another parameter in `@recurse( )` can address this.

**Comment by pjebs** [comment]
Perhaps the recursion depth can be conceptually viewed in terms of "depth of edge traversal" instead of "depth of nodes traversal". Under that interpretation, there is no ambiguity in what the results should be.

**Comment by martinmr** [comment]
Can you provide us with the query you ran and its results in the format Dgraph outputted? The data in the first comment seems to be in some other format.

Also, can you be more specific in what seems wrong with the output? Maybe it'll be more clear to me once I see the output in JSON. From what I can gather, you didn't expect the parent field to contain that member but it does because there's an edge facet even though the node it links to is not traversable due to the value of the depth parameter.

**Comment by pjebs** [comment]
@martinmr I'm not saying it's a necessarily a bug. I'm saying that the result is not necessarily intuitive and may require a rethink for v1.1.

Your interpretation of what I'm highlighting is correct.

Essentially, a new (unexpanded/empty*) "node" is returned in order to return the facet details of the edge. This extra node where all fields are empty except for the facet seems unintuitive. If that node is to be excluded due to depth, then intuitively the edge (and it's facet data) is irrelevant and shouldn't be returned.

See: 
https://github.com/dgraph-io/dgraph/issues/3163#issuecomment-474257439

For actual query:

https://github.com/thehonestscoop/lemma-chain/blob/master/find_chain.go#L172

**Comment by martinmr** [comment]
Thanks for the clarification. I was able to observe the behavior in one of our tests. I agree the current behavior is quite unexpected.

I created a PR to fix this issue.
