### ISSUE TITLE
feature request: config to store files in separate places

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3175]
It would be great if I can configure DGraph to store all files required for persistence in 1 location and all temporary files that it may generate in another location.

The docs doesn't state it is possible so I assume it's not. I have a use case where it would be greatly appreciated.

**Comment by MichelDiz** [comment]
You can use `-p` and `-w` flags to do this. 
Can you share what part of the Docs you are seeing this?

**Comment by pjebs** [comment]
Which of these are for persistent data which is absolutely required and which are for temporary data which can be cleared with not major repercussions

**Comment by pjebs** [comment]
I don't know hat those params even mean

**Comment by danielmai** [comment]
Both the postings directory (p) and wal directory (w) are necessary for persistence. The postings directory stores the data and the wal directory stores Raft membership information and is the write-ahead log for all Raft logs.

As @MichelDiz mentioned, there are options to let you choose where to store these directories.

**Comment by MichelDiz** [comment]
Hm,
There's no temporary data. -w and -p are the only persisted  directory to care about.
Only LiveLoad and BulkLoad have something equivalent to temporary. But they are not the issue here.
 
Could You elaborate a bit more? because the question was not clear. What you suggest seems to me already exists. So I replied by suggesting the above-mentioned flags.

**Comment by pjebs** [comment]
> Both the postings directory (p) and wal directory (w) are necessary for persistence. 

> There's no temporary data.

That's all I needed to know. I just assumed that DGraph would be producing some sort of data that isn't strictly needed for persistence or backup purposes. The documentation didn't specify that.
