### ISSUE TITLE
dgraph cluster rpc error

### ISSUE THREAD

**Issue by 478682649** [dgraph-io/dgraph#3191]
Create a cluster using dgraph
Use the command dgraph zero -w /data --my 192.168.1.102:5080 --replicas 3
When the first node joins,
Dgraph alpha --lru_mb 1024 --my 192.168.1.102:7080 -w /dgraph/wlog1/ -p /dgraph/posting-list1/ -z 192.168.1.102:5080 -o 1
Everything is normal, the UI schema can also operate normally.
But I add a second node
Dgraph alpha --lru_mb 1024 --my 192.168.1.103:7080 -w /dgraph/wlog1/ -p /dgraph/posting-list1/ -z 192.168.1.102:5080 -o 1
After all log output
5I0322 10:53:44.260804 21639 pool.go:136] CONNECTED to 192.168.1.103:7080
W0322 10:53:44.761544 21639 pool.go:212] Connection lost with 192.168.1.103:7080. Error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.1.103:7080: connect: connection refused.

After the schema hint in the UI
Error while trying to fetch schema
After that, even if it is restarted

Is there a problem with this operation?

**Comment by 478682649** [comment]
the new alpha log is 
E0322 11:04:36.344908   18384 draft.go:1108] Error while calling hasPeer: Error while joining cluster: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.1.103:7080: connect: connection refused"
. Retrying...
W0322 11:04:36.844081   18384 pool.go:212] Connection lost with 192.168.1.102:7080. Error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.1.102:7080: connect: connection refused"
I0322 11:04:37.345426   18384 draft.go:1075] Calling IsPeer
E0322 11:04:37.345528   18384 draft.go:1108] Error while calling hasPeer: Error while joining cluster: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 192.168.1.103:7080: connect: connection refused"
. Retrying...
E0322 11:04:38.346646   18384 draft.go:1108] Error while calling hasPeer: Unable to reach leader in group 1. Retrying...
E0322 11:04:39.347642   18384 draft.go:1108] Error while calling hasPeer: Unable to reach leader in group 1. Retrying...



zero log is
I0322 11:06:23.470299   12783 zero.go:396] Got connection request: cluster_info_only:true
I0322 11:06:23.470631   12783 zero.go:414] Connected: cluster_info_only:true
I0322 11:06:24.471443   12783 zero.go:396] Got connection request: cluster_info_only:true
I0322 11:06:24.471878   12783 zero.go:414] Connected: cluster_info_only:true
I0322 11:06:25.472794   12783 zero.go:396] Got connection request: cluster_info_only:true
I0322 11:06:25.473326   12783 zero.go:414] Connected: cluster_info_only:true
I0322 11:06:26.474201   12783 zero.go:396] Got connection request: cluster_info_only:true
I0322 11:06:26.474822   12783 zero.go:414] Connected: cluster_info_only:true
I0322 11:06:27.475765   12783 zero.go:396] Got connection request: cluster_info_only:true
I0322 11:06:27.476046   12783 zero.go:414] Connected: cluster_info_only:true
I0322 11:06:28.476955   12783 zero.go:396] Got connection request: cluster_info_only:true
I0322 11:06:28.477435   12783 zero.go:414] Connected: cluster_info_only:true
I0322 11:06:29.478429   12783 zero.go:396] Got connection request: cluster_info_only:true
I0322 11:06:29.478865   12783 zero.go:414] Connected: cluster_info_only:true
I0322 11:06:30.479811   12783 zero.go:396] Got connection request: cluster_info_only:true
I0322 11:06:30.480145   12783 zero.go:414] Connected: cluster_info_only:true
I0322 11:06:31.480910   12783 zero.go:396] Got connection request: cluster_info_only:true
I0322 11:06:31.481199   12783 zero.go:414] Connected: cluster_info_only:true

**Comment by MichelDiz** [comment]
If you use  `-o 1` flag, you have to change the ports accordly.
In your case ` --my 192.168.1.103:7081`

**Comment by martinmr** [comment]
Also, the `-o` flag cannot have the same value for the two nodes. They have to have different values or they will try to use the same port.
