### ISSUE TITLE
@facets @facets(filters)

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3199]
When you just type `@facets`, you get all the facets AND facet details.
When you type `@facets(<filters>)`, it filters based on facets but doesn't return facet details.

In order to get both, you need to type `@facets @facets(<filters>)`.

The documentation should state this.
Alternatively, It should be done like `@facets @filters(<filters>)`

**Comment by martinmr** [comment]
I checked the documentation and it does in fact state this in this section: https://docs.dgraph.io/query-language/#filtering-on-facets

I think the syntax you suggested would be confusing as the @filters directive is not explicit about filtering on facets and might confuse users.
