### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3220]
Is there a reason why the docker hub official page for DGraph doesn't reveal the Dockerfile? 

Redis: https://hub.docker.com/_/redis
Neo4j: https://github.com/neo4j/docker-neo4j-publish/blob/2bf521bddb65542f583f157f798afa636660b712/3.5.3/community/Dockerfile
MySQL: https://hub.docker.com/_/mysql?tab=description

DGraph: https://hub.docker.com/r/dgraph/dgraph

I have no idea if DGraph is doing malicious things to my computer.

**Comment by MichelDiz** [comment]
Here https://github.com/dgraph-io/dgraph/blob/master/contrib/Dockerfile
> Is there a reason why the docker hub official page for DGraph doesn't reveal the Dockerfile?

Probably because the image is not listed in https://github.com/docker-library/official-images
https://docs.docker.com/docker-hub/official_images/

**Comment by pjebs** [comment]
Neo4j is not official image.

**Comment by pjebs** [comment]
https://forums.docker.com/t/how-can-i-view-the-dockerfile-in-an-image/5687/3

> It wasn't auto built

**Comment by danielmai** [comment]
This simply requires us to update and maintain a link to the [Dockerfile](https://github.com/dgraph-io/dgraph/blob/master/contrib/Dockerfile) on the Docker Hub README, which has now been done. https://hub.docker.com/r/dgraph/dgraph/

**Comment by pjebs** [comment]
When I look at the Dockerfile you linked to, the only line that seems relevant to installing Dgraph is:
```
ADD linux /usr/local/bin
```

I can't find the linux folder anywhere.

I can only assume that someone is running some script locally which creates the linux folder and then pushes it to Docker hub.

I don't think that is how a "good" Dockerfile should work for a product like DGraph. It should start from scratch `FROM:` and then build DGraph or what ever it has to do get it ready.

**Comment by pjebs** [comment]
In summary, adding a link to the `Dockerfile` in the Docker Hub readme seems very different to the official way the others are doing it.

And the Dockerfile itself is mysterious because all the magic happens in `ADD linux /usr/local/bin` and the linux directory getting added doesn't explain much.

**Comment by pjebs** [comment]
@danielmai @MichelDiz Am I misunderstanding something on how Docker images and Docker Hub work?

**Comment by danielmai** [comment]
The `linux` directory simply contains the dgraph and dgraph-ratel binaries after they are built. As written in the Dockerfile, this is done in the release.sh script.

You can run the release.sh script yourself and see how it works.

**Comment by pjebs** [comment]
I had a look at release.sh. I thought that was the case. That is unfortunate.

**Comment by danielmai** [comment]
We're always open to PRs for improvements.
