### ISSUE TITLE
Docker alpine

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3221]
Is it possible for official docker image to use alpine distribution of linux.

All the other main databases provided at a minimum an alpine version.

Alpine simply has a smaller size footprint.

**Comment by mangalaman93** [comment]
For now, you could use the following Dockerfile for creating an alpine based image. We will see if it is possible to add this to official docker images.
```
######################
# STEP 1 build dgraph
######################
FROM golang:1.12-alpine3.9 AS builder

# build custom branch
ARG DGRAPH_BRANCH=master

# Install git
RUN apk update && apk add --no-cache git

# build dgraph binary
RUN go get -d -v github.com/dgraph-io/dgraph/dgraph
RUN cd $GOPATH/src/github.com/dgraph-io/dgraph && git checkout ${DGRAPH_BRANCH}
RUN CGO_ENABLED=0 go build -v -o /dgraph github.com/dgraph-io/dgraph/dgraph

#####################
# STEP 2 build image
#####################
FROM alpine

COPY --from=builder /dgraph /usr/local/bin/dgraph

RUN mkdir /dgraph
WORKDIR /dgraph

EXPOSE 8080
EXPOSE 9080

CMD ["dgraph"]
```

**Comment by mangalaman93** [comment]
Possible reasons to use Alpine image -
 * Alpine based image reduce the attack surface area
 * Smaller in size compared to Ubuntu based image

**Comment by mangalaman93** [comment]
Todo: Need to install ca-certificates in the image so that telemetry can work.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8767). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
