### ISSUE TITLE
Replace MD5 in cert command

### ISSUE THREAD

**Issue by codexnull** [dgraph-io/dgraph#3234]
MD5 stopped being considered cryptographically secure at least 10 years ago. It should not be used in modern software. The dgraph cert command should be updated to issue new certificates using something else, like SHA-256.

**Comment by srfrog** [comment]
Actually you want to use ECDSA, but it's not considered a priority ATM. But I agree.

Related: #2642

**Comment by danielmai** [comment]
`dgraph cert` uses MD5 to output checksums. MD5 is **not** being used to generate certificates. The certificates are generated with a 2048-bit RSA key by default. The key size is configurable with the `--keysize` flag.

**Comment by srfrog** [comment]
MD5 is fine for what we use it now, fingerprint matching. I think @codexnull is correct that we can improve our certs. There's a couple of things we can change to make our certs better. We should use a a) cryptographically secure random number generator and have the b) ECDSA option.

The issue with a) is that it's a limited resource so we would need the logic in case we drain our entropy. b) is easy to add but we need to add the logic to detect and use it.

**Comment by codexnull** [comment]
I hadn't looked at the code, only the dgraph cert output, while in the middle of something else, so I filed this to remind myself to come back to it.

It's great if it's using a 2048-bit RSA key, that's should be secure enough unless it's really not using a cryptographically strong RNG. One is built in to Linux (and Windows and Mac, I'm sure), so there's no excuse for not using it.

Also, I disagree that MD5 is OK for even fingerprint matching. It is pretty easy to generate MD5 collisions now, from what I remember.

In any case, if all we need to do is output SHA fingerprints intead of MD5 it would be a trivial change.

**Comment by codexnull** [comment]
As pointed out in a previous comment, MD5 is not actually being used for certificate issuance, only for displaying a key digest to the user. That is being addressed in #3254.
