### ISSUE TITLE
Improve performance of schema creation

### ISSUE THREAD

**Issue by mooncake4132** [dgraph-io/dgraph#3236]
We currently have about 3k predicates in our schema. It will probably grow to about 10k within the next 6 months.

Here is the benchmark of schema creation on a i7-8750 + SSD (full script comes after):
```
Schema with 1000 predicates:
Schema Dropped in 0.024006366729736328 seconds.
Schema created in 6.779448986053467 seconds.

Schema with 3000 predicates:
Schema Dropped in 0.023997783660888672 seconds.
Schema created in 15.981102228164673 seconds.

Schema with 5000 predicates:
Schema Dropped in 0.04499959945678711 seconds.
Schema created in 23.053693532943726 seconds.

Schema with 10000 predicates:
Schema Dropped in 0.06827473640441895 seconds.
Schema created in 64.15074300765991 seconds.
```

The performance of schema creation isn't an issue in production as it only needs to happen once, but it is an issue when developers are running unit & integration tests. Since we drop and recreate the schema (to truncate the database) before running any tests, running a single test case would have a 16 seconds (3k predicates) overhead due to schema creation.

I asked this question on slack before, and @danielmai suggested that I could identify the predicates I need for each test case and only create those so running a single test case would be less expensive. But it became obvious to us very quickly that maintaining this list of predicates used by each test case is very cumbersome.

Right now, we worked around the problem by not dropping the schema at test start. This is fine for the most part, except for tests involving upserts (as the data would have existed). We could specifically drop all the predicates that are involved in upsert operations but that would be most of them (>80%) so this won't work out as well.

It would be very useful for us if the performance of schema creation can be improved, or if an efficient truncate operation (that drops all data but does not drop the schema) can be implemented.

Setup:
One alpha + one zero on the same machine.
```
Dgraph version   : v1.0.13
Commit SHA-1     : 691b3b35
Commit timestamp : 2019-03-09 19:33:59 -0800
Branch           : HEAD
Go version       : go1.11.5
```

Benchmark script:
```py
import time

import pydgraph


client_stub = pydgraph.DgraphClientStub('localhost:9080')
client = pydgraph.DgraphClient(client_stub)


sizes = (1_000, 3_000, 5_000, 10_000)
for n in sizes:
    print('Schema with {} predicates.'.format(n))
    schema = '\n'.join(f'test{i}: string .' for i in range(n))

    start_time = time.time()
    client.alter(pydgraph.Operation(drop_all=True))
    print('Schema Dropped in {} seconds.'.format(time.time() - start_time))

    start_time = time.time()
    client.alter(pydgraph.Operation(schema=schema))
    print('Schema created in {} seconds.'.format(time.time() - start_time))
    print()
```

**Comment by martinmr** [comment]
I don't think there's much we can do to significantly speed up the schema creation. I have made changes to only do partial reindexing during schema changes but that wouldn't come into play in this situation as there's no data to index when the schema is created. I suspect the bottleneck is in the fact that schema updates need to go through our raft consensus algorithm.

However, I think a DropData operation (drops data but keeps schema intact) might not be too difficult to implement. I'll look through the code in order to confirm this.

**Comment by mooncake4132** [comment]
Thank you! A DropData operation will great.
