### ISSUE TITLE
Support deleting a single language entry

### ISSUE THREAD

**Issue by mooncake4132** [dgraph-io/dgraph#3237]
It seems like there is no way to delete a single language entry for a predicate. Please let me know if I'm doing this wrong as I couldn't find the [documentation](https://docs.dgraph.io/master/mutations/#delete) on how to delete i18n entries.

Setup:
one alpha + one zero on the same compupter
```
Dgraph version   : v1.0.13
Commit SHA-1     : 691b3b35
Commit timestamp : 2019-03-09 19:33:59 -0800
Branch           : HEAD
Go version       : go1.11.5
```

Schema:
```
<name>: string @lang .
```

1. Create two language entries:
```
{
  set {
    <_:x> <name> "en"@en .
    <_:x> <name> "fr"@fr .
  }
}
```

2. Verify
```
{
  node(func: has(name@.)) {
    uid
    expand(_all_)
  }
}
```
```
"data": {
  "node": [
    {
      "uid": "0x10",
      "name@en": "en",
      "name@fr": "fr"
    }
  ]
}
````

3. Attempt to remove `name@fr`:
```
{
  delete {
    <0x10> <name> "fr"@fr .
  }
}
```
```
"Please use * with delete operation for non-list type: [name]"
```
```
{
  delete {
    <0x10> <name@fr> "fr" .
  }
}
```
```
"Please use * with delete operation for non-list type: [name]"
```
```
{
  delete {
    <0x10> <name@fr> * .
  }
}
```
```
Done
```

4. Query again:
```
{
  node(func: has(name@.)) {
    uid
    expand(_all_)
  }
}
```
```
"data": {
  node: []
}
```
```
{
  node(func: uid(0x10)) {
    uid
    expand(_all_)
  }
}
```
```
"data": {
  node: []
}
```

`name@en` was also removed.

**Comment by MichelDiz** [comment]
That's odd, I thought this procedure was just like the [list] type on Dgraph. I could not find a way to do that. I found one just to edit.

PS. I've set as enhancement, but actually I think is a bug. For it would be the logical behavior to expect.

```
{
  set {
    <0x11> <name> "test"@en .  #Even if you put empty string, the language will still be there.
  }
}
```

The correct would be:

```
{
  delete {
    <0x10> <name> "name in fr"@fr .
  }
}
```

and in JSON:


```
{
      "delete": [
        {
          "uid": "0x11",
         "name@zh": "金孝珍"
        }
      ]
    }
```

**Comment by martinmr** [comment]
I made a change to allow deletion of non-list predicates without having to use *. I don't know if it works with language tags so I'll check.

This change is considered an enhancement and was merged to the master branch so it won't make it out until version 1.1

**Comment by mooncake4132** [comment]
While this syntax makes sense:
```
{
  delete {
    <0x10> <name> "fr"@fr .
  }
}
```
Is it possible to support a syntax that can delete language tags *without* knowing the value at the language tag? For example, something like this:
```
{
  delete {
    <0x10> <name@fr> * .
  }
}
```
This way I don't have to query the value of `name@fr` ahead of time.

**Comment by martinmr** [comment]
Ok. Just checked and my change works fine with language tags. Starting with version 1.1, you can delete a tagged value with the syntax mentioned in your post.

I'll keep the issue open to see if the syntax you propose is doable. I don't see a reason why it shouldn't work but I need to check first.
