### ISSUE TITLE
Improve TLS handling

### ISSUE THREAD

**Issue by codexnull** [dgraph-io/dgraph#3239]
When dgraph increment is without credentials against a server that requires them, the output is a repeating

```
Query error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed. Retrying...
```

which is not indicative of the actual problem.

Also, when it is run WITH credentials against a server that DOES NOT require them, the program succeeds without any notification, which can lead to the false impression that it is using a secure connection.

**Comment by tharun208** [comment]
I like to work on this @campoy

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8768). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
