### ISSUE TITLE
Error on nil slice for predicate list (master branch).

### ISSUE THREAD

**Issue by Vliro** [dgraph-io/dgraph#3255]
This is on latest master as of today (2019-04-04 16:00 gmt+1).

Trying to mutate from the dgraph-dgo client on a predicate of type [int] from a marshalled map[string]interface{} where the value is nil yields the following error:

`panic: rpc error: code = Unknown desc = Unexpected type for val for attr: userEBodies while converting to nquad`

And the mutation is halted. Expected behaviour in this case is no change for the predicate (I would believe). 
Version:
`Dgraph version   : v1.0.12-rc3-279-g23709b7d
Commit SHA-1     : 23709b7d
Commit timestamp : 2019-04-03 19:23:54 -0700
Branch           : master
Go version       : go1.10.4`

Example code(type IntType int)

`	
       m := make(map[string]interface{})
       var slice []IntType
       m["pred"] = slice
       Mutate(m)
`
where Mutate serializes with json.Marshal and sends it to dgraph.

**Comment by danielmai** [comment]
Can you share the output for `dgraph version`? If you build with `make install` then you should have version info in the dgraph binary.

It would also be helpful to share example code that reproduces the issue, and more detail if this works in the latest release. I think you said it had worked before in Slack.

**Comment by danielmai** [comment]
Here's a runnable example where this happens:
```
package main

import (
	"context"
	"encoding/json"
	"flag"
	"log"

	"github.com/dgraph-io/dgo"
	"github.com/dgraph-io/dgo/protos/api"
	"google.golang.org/grpc"
)

var (
	addr = flag.String("addr", "localhost:9180", "Address of Dgraph Alpha.")

	ctx = context.Background()
)

func newClient(addr string) *dgo.Dgraph {
	// Dial a gRPC connection. The address to dial to can be configured when
	// setting up the dgraph cluster.
	d, err := grpc.Dial(addr, grpc.WithInsecure())
	if err != nil {
		log.Fatal(err)
	}
	return dgo.NewDgraphClient(
		api.NewDgraphClient(d),
	)
}

type Person struct {
	Name   string   `json:"name,omitempty"`
	Friend []Person `json:"friend"`
}

func main() {
	flag.Parse()

	dg := newClient(*addr)

	log.Println("Running DropAll.")
	dg.Alter(ctx, &api.Operation{DropAll: true})

	txn := dg.NewTxn()
	defer txn.Discard(ctx)

	mu := &api.Mutation{
		CommitNow: true,
	}
	p := Person{
		Name:   "Name",
		Friend: nil,
	}
	pb, err := json.Marshal(p)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Running JSON Mutation: %v\n", string(pb))
	mu.SetJson = pb

	assigned, err := txn.Mutate(ctx, mu)
	if err != nil {
		log.Fatal(err)
	}
	uid := assigned.Uids["blank-0"]
	log.Printf("Successfully added node with UID %v\n.", uid)

}
```
Output:
```
2019/04/04 17:16:40 Running DropAll.
2019/04/04 17:16:41 Running JSON Mutation: {"name":"Name","friend":null}
2019/04/04 17:16:41 rpc error: code = Unknown desc = Unexpected type for val for attr: friend while converting to nquad
```
