### ISSUE TITLE
@* notation on language predicates doesn't work.

### ISSUE THREAD

**Issue by mooncake4132** [dgraph-io/dgraph#3263]
In the [documentation](https://docs.dgraph.io/master/query-language/#language-support) it states that
```
name@* => Look for all the values of this predicate and return them along with their language. For example, if there are two values with languages en and hi, this query will return two keys named “name@en” and “name@hi”.
```
But when I tried the notation on play.dgraph.io:
```
{
  q(func: allofterms(name@en, "Farhan Akhtar")) {
    name@*
  }
}
```
It fails with an error:
```
{
  "errors": [
    {
      "code": "ErrorInvalidRequest",
      "message": "Expected directive or language list"
    }
  ],
  "data": null
}
```

**Comment by MichelDiz** [comment]
That feature isn't part of v1.0 releases. You're sharing a documentation link from Master
The correct one is https://docs.dgraph.io/v1.0.12/query-language/#language-support

Cheers.

**Comment by mooncake4132** [comment]
Thanks for correcting. I didn't realize this is a new feature.
