### ISSUE TITLE
One node is answering much slower than others

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#3277]
dgraph 1.0.14-rc1

i am running 3 queries on
3 dgraph nodes on our env, and count query takes the same time on both
nodes.
but if query is a bit more complex, like get 20 nodes and calculate
counts for them with filtering - then on 2 nodes it runs fast (400ms),
and on a node in the middle it takes 63 seconds
only restart helps but after some time this problem comes back. all
nodes are idle, no loads there

```
[ec2-user@ip-172-16-xxx-xxx ~]$ for ip in $ips; do ssh $ip 'curl -s
localhost:8080/query -X POST -d "{ q(func: has(entity_key)) {count(uid)} }"; echo'; done

{"extensions":{"server_latency":{"parsing_ns":5413,"processing_ns":4601263848,"encoding_ns":2559588213},"txn":{"start_ts":1331230}},"data":{"q":[{"count":8848018}]}}

{"extensions":{"server_latency":{"parsing_ns":5742,"processing_ns":4176820528,"encoding_ns":2366213900},"txn":{"start_ts":1331233}},"data":{"q":[{"count":8848018}]}}

{"extensions":{"server_latency":{"parsing_ns":10193,"processing_ns":2999623098,"encoding_ns":1497617700},"txn":{"start_ts":1331236}},"data":{"q":[{"count":8848018}]}}

[ec2-user@ip-172-16-xxx-xxx ~]$ for ip in $ips
> do
> ssh $ip 'curl -s localhost:8080/query -X POST -d "{ q(func: has(type_Concept), first: 20) {count(~r2mlink) @filter(has(rel_50cb4eff-ff4d-470a-97b1-918fecfeaf5b))} }"; echo'
> done

{"extensions":{"server_latency":{"parsing_ns":9042,"processing_ns":439483204,"encoding_ns":425783},"txn":{"start_ts":1331243}},"data":{"q":[{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0}]}}

{"extensions":{"server_latency":{"parsing_ns":12031,"processing_ns":63103360638,"encoding_ns":709735},"txn":{"start_ts":1331244}},"data":{"q":[{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0}]}}

{"extensions":{"server_latency":{"parsing_ns":10010,"processing_ns":430634372,"encoding_ns":1023284},"txn":{"start_ts":1331257}},"data":{"q":[{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0},{"count(~r2mlink)":0}]}}
```

**Comment by makitka2007** [comment]
trace query on slow node while query is running (the query itself appears for short time, then line with a query disappears): https://drive.google.com/file/d/1prCA9cT7btqWIW7YE1ptjvked6eILNFj/view?usp=sharing

trace query on slow node when it's idle (1 query is always showing): https://drive.google.com/file/d/1xb-ENbU4eWF1QRs5UAyUDHSX7xoatV3Y/view?usp=sharing

on other nodes (which are not slow) query is 0 while they are idle

**Comment by manishrjain** [comment]
Is it possible that one of the alphas has a slower disk or more memory pressure than the other two? I'm looking at the traces and it's not clear why it takes 19s to look up ~1M uids.

**Comment by makitka2007** [comment]
19s - this value was taken in the middle of query execution, actually it took >60seconds
both 3 nodes are equal. whats important - if i restart a cluster, then both 3 nodes run such query fast, but after some time problem comes back

**Comment by makitka2007** [comment]
so looks like it's waiting for something, and it happens only on quite complex queries, on simple ones without filtering on other predicates it runs fast on both 3 nodes as well

**Comment by makitka2007** [comment]
(there is only one group replicated to 3 nodes)

**Comment by manishrjain** [comment]
We tried to debug this. Seemed like one of the Alphas had many zombie goroutines which seemed to be affecting the performance of that Alpha. Fix was added here: https://github.com/dgraph-io/dgraph/commit/9fd8bb96362084bcccdfa5d0f45f6b6c10f6b44d and another fix was added to deal with another goroutine leak by @gitlw . 

Closing this issue for now. If this happens again, we'll reopen.
