### ISSUE TITLE
Weird error messages in log

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3290]
I've been seeing these logs from DGraph. What does it mean? Are they dangerous. Does it mean that my writes are not persisting?

```
W0412 22:34:53.946988      14 raft.go:697] Raft.Ready took too long to process: 782ms. Most likely due to slow disk: 782ms. Num entries: 1. MustSync: true
W0412 22:34:54.011575      34 draft.go:842] Raft.Ready took too long to process: 849ms. Most likely due to slow disk: 849ms. Num entries: 0. MustSync: true
...
W0412 22:34:57.452596      14 raft.go:697] Raft.Ready took too long to process: 1.567s. Most likely due to slow disk: 1.567s. Num entries: 1. MustSync: true

```

**Comment by danielmai** [comment]
Writes are fine, but these logs show that you may observe a slow down likely due to slow disk IOPS. It indicates some investigation into your disk configuration if the log message persists to appear.

**Comment by pjebs** [comment]
so no dangers to data persistence. Just slow writes. If that's the case, feel free to close.
