### ISSUE TITLE
Write a tool to summarize w directory data

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#3300]
When an Alpha restarts it replays entries from the write-ahead log in the w directory. We need to be able to inspect the entries in the w directory to understand what would be replayed. This should be a tool that works like `dgraph debug` and prints out for each WAL entry the type (e.g., a mutation, commit, etc.), the size of each entry, the total number of entries, and so on.

**Comment by codexnull** [comment]
Would it make sense to add that as a feature to `dgraph debug` rather that writing a new tool?

**Comment by manishrjain** [comment]
Yes, in dgraph debug. I'm working on this.

**Comment by manishrjain** [comment]
Merged https://github.com/dgraph-io/dgraph/pull/3319 .
