### ISSUE TITLE
QueryWithVars doesn't receive int variable in @recurse()

### ISSUE THREAD

**Issue by stevenayers** [dgraph-io/dgraph#3301]
I would have raised this in dgo, but it looks like it could be more to do with the parser. I saw that even though you have to pass a `map[string]string` into `QueryWithVars`, if you specify it as an int in `withvar()`, it should be able to take it.

Code ref: https://github.com/dgraph-io/dgraph/blob/master/gql/parser.go#L303

- What version of Dgraph are you using?
1.0.14

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?
rd5.large

- Steps to reproduce the issue (command/config used to run Dgraph).
You can only pass a string map as the variables map.
```	
         queryDepth := strconv.Itoa(1)
	variables := map[string]string{"$id": Id, "$depth": queryDepth}
	q := `query withvar($id: string, $depth: int){
			result(func: eq(id, $id)) @recurse(depth: $depth, loop: false){
 				id
                                 links
			}
		}`
	resp, err := txn.QueryWithVars(*ctx, q, variables)
```

- Expected behaviour and actual result.

Error: `Expected value inside @recurse() for key: depth`

**Comment by martinmr** [comment]
I checked the code and variables inside recurse have never been supported. Most likely an oversight but since this is not breaking existing features I have tagged it as a feature.

**Comment by stevenayers** [comment]
I'll raise a PR for this

**Comment by hamada969** [comment]
hey guys, appreciate the hard work.

Any updates on this issue.

This breaks with the same error using the python version as well

`query = """query relation($node_id: string, $depth: int) {{
                relation(func: eq(id, $node_id)) 
                @recurse(depth: $depth, loop: true)
                {{
                    {expand}
                }}
            }}""".format(expand=EXPAND_PROPERTIES)

    variables = {'$node_id': node_id, '$depth': "3"}
`

**Comment by stevenayers** [comment]
It's messy, but you can use string interpolation as a workaround for now.

**Comment by amandalmia14** [comment]
@campoy Any updates on this issue?

@stevenayers It will be helpful if you share an example. Thanks.

**Comment by stevenayers** [comment]
@amandalmia14 
`
depth := strconv.Itoa(5)
variables := map[string]string{"$id": Id}
q := `query withvar($url: string, $depth: int){
		result(func: eq(id, $id)) @recurse(depth: ` + depth + `, loop: false){
 			uid
    			links
		}
	}`
resp, err := txn.QueryWithVars(*ctx, q, variables)
`
