### ISSUE TITLE
When streaming snapshot, only stream a delta

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#3316]
Currently, if a follower falls behind the leader and Raft asks for a snapshot, Dgraph would wipe out everything in follower's p directory and stream a full snapshot. Instead, Dgraph can look at the last snapshot the follower had and only stream updates since then. This would result in a lot smaller data set being streamed out and would allow for a much faster recovery.

**Comment by martinmr** [comment]
Change has been made in master and the 1.0 branch.
