### ISSUE TITLE
[feature] String type external ids

### ISSUE THREAD

**Issue by codelipenghui** [dgraph-io/dgraph#3321]
### What you wanted to do

External ids is powerful for incremental data write and query by uid. Generally speaking, the data from business application have it's own id system, such as User has user_id and Student has student_id, but these ids can only guarantee local uniqueness. If we wan't to import these data to dgraph, we have two ways to achieve:

1. Let dgraph to generic uid, and store the local id as a predicate(e.g. user_id)
2. Rearrange the allocation strategy of uid, User's uid start with 100000000000, Student's uid start with 200000000000.

But these two methods are not very friendly to developers. 

For the first solution, In order to get the uid, developer have to query the uid by local_id, If every piece of data needs such a query, I believe this is not a small overhead and this also complicates development.

For the second solution, developer must design the allocation strategy of uid , whether writing or querying, you need to stick to this strategy. Such uid allocation strategy will become more and more complicated

So, I am thinking that using String as a uid will make this simple. We can use the same uid encoding rule (user_1, user_2, student_1, student_2).

Of course, I am not sure if this will bring more harm.

**Comment by martinmr** [comment]
This is not something we want to support. uids are uint64 and that assumption is so basic that trying to support strings as uids would require a very big redesign.

But we understand that having to query for the internal uid every time is not exactly user friendly. For now, I would suggest sticking to the first strategy (external ids could go into a predicate callled `xid`) as it's much more flexible. We are working on supporting a "query then mutate" feature to have users write a query and execute a mutation based on the results of that query in a single transaction. This should make the use of external IDs more user-friendly.

**Comment by codelipenghui** [comment]
> We are working on supporting a "query then mutate" feature to have users write a query and execute a mutation based on the results of that query in a single transaction. This should make the use of external IDs more user-friendly.

Is this friendly for incremental data import using live loader?

**Comment by martinmr** [comment]
That feature is only for mutations from the client, not the live loader since it does not perform queries.
