### ISSUE TITLE
Replacing a Dgraph Alpha assigns it to a new group.

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#3326]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
master, latest (v1.0.14)

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
n/a

- Steps to reproduce the issue (command/config used to run Dgraph).

1. Run Dgraph cluster with 1 Zero, 1 Alpha.
2. Remove the Alpha with removeNode. Check it's ID and group membership with Zero's /state.

```sh
curl localhost:6080/removeNode?group=1&id=1
```

3. The Alpha is removed and will stop running. It's removal can be checked by looking at Zero's /state.
4. Start a new Alpha. The Alpha will join the cluster under Group 2.

Continuing steps 2 to 4 will assign the Alpha to a new group.

- Expected behaviour and actual result.

I expected the Alpha to replace the previous Alpha's membership.

In a two node cluster, when an Alpha is added to the cluster Zero should assign membership to the empty group 1.

In the general case, Zero should add Alphas to fill in empty membership spots in existing groups first before creating another group.

**Comment by sch00lb0y** [comment]
I like to take this if no one is working on it.

**Comment by manishrjain** [comment]
@sch00lb0y : Feel free.

**Comment by sleto-it** [comment]
Hi @balajijinnah - was this fixes or is it still open?
I see a PR from you, which was then closed and not merged

Please could you share an update on this. If this is fixed, in which version did the fix go

Thanks,

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8439). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
