### ISSUE TITLE
Remove unused and undocumented binary schema type

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#3328]
#### What version of Dgraph are you using?
latest, master

#### Have you tried reproducing the issue with latest release?
Yes

#### Steps to reproduce the issue (command/config used to run Dgraph).

Alter the schema to set a predicate to a `binary` type.

#### Expected behaviour and actual result.

Dgraph no longer needs a `binary` type exposed as an available predicate type. They were originally sent as bytes from the client and are returned as base64-encoded strings in JSON responses. Everything that's possible with binary types including custom tokenizers is already available for strings.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8440). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
