### ISSUE TITLE
Connection load / Nginx example

### ISSUE THREAD

**Issue by emhagman** [dgraph-io/dgraph#3376]
Do you know how many concurrent connections each alpha can handle? Also, do you have any tips on loadbalancing with `nginx`?

I have an example config here:

```
# all servers
upstream grpcservers {
    zone grpc 64k;
    server cluster0-node0:9080;
    server cluster0-node1:9081;
    server cluster0-node2:9082;
}

# dgraph grpc proxy
server {

  listen 9080 http2;
  access_log /var/log/nginx/access.log grpc;

  location / {
    grpc_pass grpc://grpcservers;
    error_page 502 = /error502grpc;
  }

  location = /error502grpc {
    internal;
    default_type application/grpc;
    add_header grpc-status 14;
    add_header grpc-message "unavailable";
    return 204;
  }

}
```

**Comment by williamsandytoes** [comment]
@emhagman are you currently using Nginx to load-balance queries + mutations to a cluster? If so, how's it going? I'm looking to do the same, but I'm wondering if I would see any significant performance gains - specifically for writes.

**Comment by MichelDiz** [comment]
We have these examples. We need to check how we can add them to docs.

Original https://gist.github.com/danielmai/0cf7647b27c7626ad8944c4245a9981e

Fork https://gist.github.com/MichelDiz/42954e321620159c872c35c20e9d85c6

**Comment by danielmai** [comment]
This is covered in docs with #5110 merged. https://dgraph.io/docs/howto/#load-balancing-queries-with-nginx
