### ISSUE TITLE
DGraph Zero: Endpoint Queries Not Working

### ISSUE THREAD

**Issue by damienstamates** [dgraph-io/dgraph#3379]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.14

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
Macbook Pro (Mid 2015)
Mojave Version 10.14.4 (18E226)
Processor: 2.2 GHz Intel Core i7
Memory: 16GB 1600 MHz DDR3
Graphics: Intel Iris Pro 1536 MB

- Steps to reproduce the issue (command/config used to run Dgraph).
For me I installed Dgraph and without any configuration or anything I ran...
`dgraph zero`
`dgraph alpha --lru_mb 2048 --zero localhost:5080`
`dgraph-ratel`

- Expected behaviour and actual result.
I'm not able to use any of the `POST` queries for DGraph Zero.
Whilst running `localhost:6080/state` it can get all the information perfectly fine, but when it comes to trying anything else it reports back with a `404 page not found` error.

**Comment by MichelDiz** [comment]
if you're using Docker or K8s you have to whitelist your IP https://docs.dgraph.io/deploy/#whitelist-admin-operations

**Comment by damienstamates** [comment]
I'm hosting this locally on my machine.

**Comment by MichelDiz** [comment]
I'm too and I can access it.

**Comment by MichelDiz** [comment]
I guess this is solved (saw it in Slack)
