### ISSUE TITLE
Dockerfile should create a directory instead of starting up in root

### ISSUE THREAD

**Issue by the42** [dgraph-io/dgraph#338]
and set WORKDIR accordingly before issuing CMD[""], otherwise it's cumbersome to map the p / u / m directories from the host with docker run -v

https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-volume

**Comment by manishrjain** [comment]
@pawanrawal Can you have a look at this?

**Comment by pawanrawal** [comment]
Hi @the42 

I had a look at this, we create already a working directory `/dgraph`. I can change the `WORKDIR` to it before the `CMD` command. Then you should be able to run and mount dgraph like
`docker run -it -p 8080:8080 -v $(pwd)/p:/dgraph/p -v $(pwd)/m:/dgraph/m -v $(pwd)/u:/dgraph/u dgraph/dgraph`

Is this what you had in mind?

Note - The path for both source and destination (container) must still be absolute paths. (https://github.com/docker/docker/issues/15526)

**Comment by the42** [comment]
Yes, that was exactly I had in mind. The directories get created but they should be created within the /data and /dgraph - folder. I guess setting the Workdir accordingly should be all that is required in order to specify a local directory as a DGraph wokingdir for a Docker-scenario

**Comment by pawanrawal** [comment]
Thanks @the42, I have changed the Dockerfile and pushed the updated Docker image.

**Comment by the42** [comment]
Installed, tested and directory pickup works now.

Seems however the query syntax compared to the documentation changed? I consistently get a

    {"code":"ErrorInvalidRequest","message":"Expected variable start. Got: lex.Item [11] \"me\""}

back now for this query

    curl localhost:8080/query -XPOST -d '{
	me(_xid_: alice-in-wonderland) {
		type
        }
    }'

Time to wait for documentation update and 0.7 maybe ...

**Comment by manishrjain** [comment]
Emm.. looks like a bug or something. We'll test it in v0.7.

**Comment by pawanrawal** [comment]
Hey @the42 

I tried to reproduce this but couldn't. Could you verify that you the latest dgraph docker image? What OS are you on?

**Comment by the42** [comment]
I tested again an this was a fault at my side. Queries work just fine, sorry for the noise!
