### ISSUE TITLE
Fix 21million tests

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/dgraph#3389]
After the `_predicate_` pred is removed, the 21million tests that use expand queries will not work anymore. In order to make them work again, type information needs to be added to the dataset.

- [x] Add dgraph.type triples to 21million dataset.
- [x] Add types to the schema (from the original freebase dataset).
- [ ] Fix fuzz-data tests.

**Comment by MichelDiz** [comment]
About Schema Type, I have part of the work started here https://github.com/dgraph-io/benchmarks/pull/23/files
I've tried to find better information about freebase schema structure, but not accomplished. So I did manually and still to do some checks.
