### ISSUE TITLE
empty object literal causes an error

### ISSUE THREAD

**Issue by the42** [dgraph-io/dgraph#339]
this simple Triple fails

    curl localhost:8080/query -XPOST -d $'mutation {
      set {
    		<S> <P> "" .
      }
    }

with error message `{"code":"Error","message":"No Object in NQuad. Input: [\u003cS\u003e \u003cP\u003e \"\" .]"}`

Using dgraph from latest docker image docker pull dgraph/dgraph:0.4.4

**Comment by manishrjain** [comment]
This makes sense. You must pass a valid triple; which would contain either a value, or an entity as the object.

The triple that you're passing is invalid.

**Comment by the42** [comment]
The spec does not disallow the empty literal which is implicitly of type xsd:string https://www.w3.org/TR/n-triples/.

So does this RDF validation service accept empty literals. http://www.easyrdf.org/converter

If I am unable to pass an empty string how am I supposed to state that a <product> <has an> empty description?

**Comment by manishrjain** [comment]
In graphs, an absence of a field is the same as that field being set to nil or empty. So, if you were to delete this quad, `<S> <P> "prev value" .`, it should give you the absence property; which could be taken as an empty description. This might be a bit tricky, but I'd say in graph world, this is correct behavior.

Reopening the issue, until we have a convincing resolution.

**Comment by the42** [comment]
I disagree with this explanation in is as much as a NULL is not the same as an empty string. But I think you agree that this issue requires a solution. Thank you for accepting the report.

**Comment by manishrjain** [comment]
No worries! I personally find it annoying when other projects close an issue without a proper resolution, so this is a good reminder to self not to do the same thing.

You're right that if RDF spec allows it, we should allow this as well. @ashwin95r -- can you work on this as part of the upcoming release?

Expect this to be either part of v0.7, if not v0.7.1 or something.

**Comment by manishrjain** [comment]
@ashwin95r did an initial attempt at this. But, then it causes non-existent predicates to be returned as empty values on query. This would need more thought.

**Comment by ashwin95r** [comment]
Fixed by 6892e122248227bab95624cec28d8be6a6b43570
