### ISSUE TITLE
Support Point in Time Recovery in Dgraph

### ISSUE THREAD

**Issue by mangalaman93** [dgraph-io/dgraph#3404]

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8770). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
