### ISSUE TITLE
String field collation

### ISSUE THREAD

**Issue by Scapal** [dgraph-io/dgraph#3446]
Let specify the collation for string fields (Ie. the way it is compared hence sorted).
For the moment lowercase and uppercase are handled differently when applying a sort.
This could also be used by text filters, the field collation determining if a letter with an accent should be considered as different or not.

**Comment by campoy** [comment]
Thanks for the proposal, @Scapal!

We will consider it and it to the roadmap if enough people request it.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8771). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
