### ISSUE TITLE
DGraph has to support IRIs for queries as by the spec

### ISSUE THREAD

**Issue by the42** [dgraph-io/dgraph#347]
Currently DGraph doesn't allow  predicates  (subjects too?) to contain all of the allowed characters as defined by [the specification](https://www.w3.org/TR/n-quads/). 

As DGraph loads data from triples/quads it should be equally possible to query/retrieve these elements which were also accepted for loading/import.

**Comment by manishrjain** [comment]
Once v0.7 release is done, I'll work on moving RDF stuff to ANTLR grammar. Will tackle this as part of that change.

**Comment by manishrjain** [comment]
ANTLR is slow, so we'll just have to do this as part of the Go codebase.

**Comment by ashishnegi** [comment]
Looking at the IRIs grammar :

predicate 	::= 	IRIREF
IRIREF 	::= 	'<' ([^#x00-#x20<>"{}|^`\] | UCHAR)* '>'  

In our code, we seem to be allowing any char in IRI. We need to restrict that.

@the42 Your bug description was `doesn't allow predicates (subjects too?) to contain all of the allowed characters` . Can you give example of what characters were not allowed ?

**Comment by the42** [comment]
I think the ':' as in http://www.w3.org/2000/01/rdf-schema# was offending.

**Comment by ashishnegi** [comment]
@the42  An IRIRef has to start with `<` and end with `>` .
In the `rdf-schema` link you shared, i can not see any predicate following it.
If i add `:` in predicate of any of rdf tests we have, they still pass.

**Comment by the42** [comment]
I meant <http://www.w3.org/2000/01/rdf-schema#> of course. These did not work like in the following:
S - P - O:
<http://data.bmf.gv.at/application#AE> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.bmf.gv.at/application> .

**Comment by ashishnegi** [comment]
@the42 We have fixed parsing of rdf as per spec.
Can you confirm the fix on latest master ? Or report any new bugs that you face.

**Comment by pawanrawal** [comment]
Closing this for now. Feel free to open if there is any issue.
