### ISSUE TITLE
JSON export on Master is producing artifacts

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#3478]
If you suspect this could be a bug, follow the template.

Ref: https://github.com/dgraph-io/dgraph/pull/3309

- What version of Dgraph are you using?
Master

- Steps to reproduce the issue (command/config used to run Dgraph).

Add any data to Dgraph and run `curl 'localhost:8080/admin/export?format=json'`

- Expected behaviour and actual result.
A clean valid JSON.

![Captura de Tela 2019-05-29 às 11 50 09](https://user-images.githubusercontent.com/6570955/58566966-de737000-8207-11e9-9b76-c0ee7dd46614.png)

**Comment by danielmai** [comment]
Fixed by #3682.
