### ISSUE TITLE
Dgraph zero doesn't always respond to SIGTERM (2)

### ISSUE THREAD

**Issue by dpkirchner** [dgraph-io/dgraph#3479]
This is similar to https://github.com/dgraph-io/dgraph/issues/1898, and it might be the same bug. However, the reproduction steps are easier.

If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

1.0.14

- Have you tried reproducing the issue with latest release?

Yeah

- What is the hardware spec (RAM, OS)?

Docker-for-desktop running on macOS 10.14.5. Running dgraph in a Kubernetes cluster.

Docker version 2.0.0.3, Kubernetes 1.10.11

- Steps to reproduce the issue (command/config used to run Dgraph).

* Create a dgraph-ha cluster using `kubectl create -f https://raw.githubusercontent.com/dgraph-io/dgraph/master/contrib/config/kubernetes/dgraph-ha.yaml`
* Wait until every pod is running
* Open another terminal and watch logs for a zero pod: `kubectl logs -f dgraph-zero-0`
* Delete that zero pod (to recreate it): `kubectl delete pod dgraph-zero-0`. This sends a SIGTERM to the process.

Note: There's no data loaded into this cluster, so traffic should be minimal, and few if any in-flight gRPC calls. However, I have verified that the cluster is in a healthy state and is capable of processing data.

- Expected behaviour and actual result.

Expected: Log entries indicating the signal was received and processed (from `glog.Infof("--- Received %s signal", sig)`, `glog.Infof("gRPC server stopped : %v", err)`) and then eventually the process dying naturally.

Actual: No log entries occur when the process is SIGTERM'd. There's no sign that the signal was received. It's as though the signal handler is being unregistered somewhere. Eventually, after the grace period lapses, the process is SIGKILL'd.

When using the single host k8s example, dgraph zero dies correctly (logs the signal, closes connections, etc). This issue only happens when the zeros are clustered.

**Comment by campoy** [comment]
Hey @pawanrawal, since you worked on the issue linked by this one I wonder if you could have a look and decide whether this should be closed.

**Comment by danielmai** [comment]
Dgraph Zero pods now receive SIGTERM correctly with #3972. The latest dgraph-ha.yaml and Helm chart configurations have this fix.
