### ISSUE TITLE
Flaky test: TestNodes/test_query_2

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#3485]
Every single one of my previous PRs has failed due to a test which is completely unrelated to my changes.

How do I know it's unrelated? The latest one was adding a link to a Markdown document 😄 

The output is the following:

```
[11:09:47][Step 3/5] TestNodes/test_query_2
[11:09:47][TestNodes/test_query_2] [Test Output]
        assertions.go:237: 
                        
	Error Trace:	group_delete_test.go:211
            
			group_delete_test.go:47
            
	Error:		Received unexpected error:
            	rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:9180: connect: connection refused"
```

I think you might be able to access the logs in [here](https://teamcity.dgraph.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=13020)

But just in case I'm also attaching the log in here: [dgraph_CI_7078.log](https://github.com/dgraph-io/dgraph/files/3238300/dgraph_CI_7078.log)

The test seems to be part of [this file](https://github.com/dgraph-io/dgraph/blob/089e7ca1a116d10e462ddbca501a310e6043892e/systest/group-delete/group_delete_test.go#L41)

**Comment by martinmr** [comment]
Opened https://github.com/dgraph-io/dgraph/pull/3498 to hopefully fix this issue. I ran it multiple times without running into any issues.

**Comment by martinmr** [comment]
I have submitted a few PRs in the past days and didn't see this issue once. I'll close this issue for now as it appears to be fixed.
