### ISSUE TITLE
Auth header is not consistent with the rest of the HTTP API

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/dgraph#3510]
dgraph:master

ACL enterpirse feature uses a custom http header `X-Dgraph-AccessToken`.
We have [stopped using all other custom headers](https://github.com/dgraph-io/dgraph/commit/a2610875b0d478371e0bc1ae2b319793a1fb7a28#diff-b1980ee16e5e86589390571c8eb02069)

For consistency (and for all the reasons http headers are a PITA) the auth token should also be moved into another part of the protocol

CC @gitlw  @mangalaman93

**Comment by mangalaman93** [comment]
We had a discussion about this. We concluded that for security reasons, we cannot have auth token as part of the URL parameters. We decided to keep the `X-Dgraph-AccessToken` as is.

**Comment by paulftw** [comment]
Seems like this is a wontfix but I cannot find how to properly mark that in github

**Comment by martinmr** [comment]
@campoy mentioned this. It's ok to just close an issue if we won't fix it.
