### ISSUE TITLE
Backup doesn't write back all the data that was input

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#353]
I used the mutation script to load the goldendata.gz into Dgraph. 1124693 RDF's were loaded.

Then I backed up Dgraph after everything was written to disk. The backed up file had 1120879 RDF's. This a bug possibly.

**Comment by manishrjain** [comment]
I'm working on that. I realized that the golden data set has duplicates. I'm fixing those.

**Comment by pawanrawal** [comment]
Fixed by removing duplicates from the goldendata set.
