### ISSUE TITLE
Value changes from source to backup

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#354]
This is what I'm getting in the source:
`<m.03z94ts>	<type.object.name>	"Chetzemoka's Curse"@en	.`

And this is the equivalent in the backup:
`3233add61be96 type.object.name.en 0 Chetzemoka"s Curse [m.03z94ts,]`

Ignoring the conversion from xid to uid, just look at the value. The source contains single-quote, the backup prints double-quotes. This looks like a bug.

**Comment by ashwin95r** [comment]
Yeah. This is wrong behaviour. The `'` has to be replaced by `"` only for geo strings so that it can be decoded. Moved it to Marshal/UnmarshalText of geo type. Also changed the suffix for geo type in backup.
16051820641d27fbd53a03bdc3997fcbc9bd626d

**Comment by manishrjain** [comment]
These match up now.
