### ISSUE TITLE
Expected a value variable in cond but missing

### ISSUE THREAD

**Issue by quanghaisoft** [dgraph-io/dgraph#3544]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
1.0.15

- Have you tried reproducing the issue with latest release?

YES
- What is the hardware spec (RAM, OS)?

12G,unbutu
- Steps to reproduce the issue (command/config used to run Dgraph).

- Expected behaviour and actual result.
Result return null but thow exeption :Expected a value variable in cond but missing
{ 
  rs as var (func:  anyoftext(name, "nonexists")  )  
  {  
    uid   
   }   
 getdata (func:  uid (rs ) ) 
  {  
    uid ,  
       cat1 as  cateid, 
        r1 as math(cond( cat1==9 , 1,0 )),
        score1  : math(100+r1)
        }         
  }
OR dgraph docs sample
{
  var(func:allofterms(name@en, "nonexitsdata")) {
    films as director.film {
      p as count(starring)
      q as count(genre)
      date as initial_release_date
      years as math(since(date)/(365*24*60*60))
      score as math(cond(years > 10, 0, ln(p)+q-ln(years)))
    }
  }

  TopMovies(func: uid(films), orderdesc: val(score)) @filter(gt(val(score), 2)){
    name@en
    val(score)
    val(date)
  }
}
The code throw exception "Expected a value variable in cond but missing" so i can not  join this to other  list 
(Sorry my bad english)

**Comment by quanghaisoft** [comment]
This code not run with is ls1 non exits data, throw exception

{
  
   ls1 as  var(func: has(product_category ))  
  @filter(
       regexp(product_productname, /samsung-nonExits data.*/i) 
  ) 
  { 
    product_category{
      uid
      
    }
   
    uid ,
    
     cat1 as  product_categoryid,
     r1 as math(cond(cat1 == 42, 1,0 )),
     score1  as math(100+r1)
    } 
    ls2 as  var(func: has(product_category ))  
  @filter(
        alloftext(product_productname, "samsung")  
  ) 
  {  product_category{
      uid
      
    }
    uid ,
  
     cat2 as  product_categoryid,
     r2 as  math(cond(cat2 == 42, 1,0 )),
      score2  as math(10+r2)
    } 
   ls3 as  var(func: has(product_category))  
  @filter(
      anyoftext(product_productname, "samsung")  
  ) 
  { 
      product_category{
      uid
      
    }
    uid ,
    cat3 as  product_categoryid,
     r3 as  math(cond(cat3 == 42, 1,0 )),
      score3  as math(3+r3)
    } 
  
   lsall as var(func: uid(  ls1,ls3, ls2)   )    {  
    
     
 uid,
  score as  math(score1+score2+score3) ,
   catlistX as  product_category {
   category_categoryid,
    uid
  }
  
 }
  
  #----------------
   
  
  
  rs as var(func:  uid( catlistX )    ) {
 
    uid,
   ~product_category  @filter( uid( lsall) )     
      { 
   
         m1  as product_productid
       # m0  as math(product_productid)
    c as  count(product_productid),
   r as math(1)#cond(m1 == 23369, 1,0)),
   #  scorex  as math(score) 
  }
    m  as  min(val(m1)),
  xx as  sum(val(c)) ,
    sr as  sum(val(r)) 
  }
    
    
    catelist(func: uid(  rs ) 
  
    ,first:100   ,orderdesc: val(xx) ) # @filter(   eq(val(sr), 0) #filter again
 
      {    
 category_categoryid,
   category_categoryname
  uid,
  val(xx),
      val(m),
         val(sr)
 }
  
  sanpham(func: uid(  lsall ) 
  
    ,first:15  ,orderdesc: val(score ) ) 
    
    
    {    
      product_categoryid
 product_productname,
   product_contentsrh
  uid,
       val(score),
       product_category {
        category_categoryname
        category_categoryid
      }
 }
    
  
}

**Comment by MichelDiz** [comment]
I did not quite understand the use case here. It still seems valid to me at first. As the Root Query returns empty, it should not perform any other functions below it.

However, the error is correct.

**Comment by quanghaisoft** [comment]
I want to join 3 list search result , first is empty , but second and 3th is has data, so my function still run correctly, but first list throw  exception, and this code can not return any result.

**Comment by MichelDiz** [comment]
Check my response in https://discuss.dgraph.io/t/expected-a-value-variable-in-cond-but-missing/4596/4

**Comment by quanghaisoft** [comment]
thanks you very much .
