### ISSUE TITLE
RAFT: node.raft isn't protected by mutex locks

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#356]
node.raft is being accessed by many goroutines simultaneously, but isn't protected by mutex locks. Fix that.

**Comment by dmonay** [comment]
Hi @manishrjain. I'd like to work on this.

**Comment by manishrjain** [comment]
This would addressing really quickly, because we're releasing v0.7 within a week. Might be better to pick some other task. But, if you think you can send a PR within a couple of days, sure! Note that this PR would need to be against the release/v0.7 branch.

**Comment by dmonay** [comment]
I won't be able to submit a PR within that time frame. Will look for another task.

**Comment by ankurayadav** [comment]
Hi @manishrjain. I would like to take this up.
Again, few pointers will make it easier for me to start working on this.

**Comment by manishrjain** [comment]
https://github.com/dgraph-io/dgraph/pull/410 fixes this.
