### ISSUE TITLE
Live loader fails (permission denied) if there are any ACL rules for the related importing data

### ISSUE THREAD

**Issue by nodeworks** [dgraph-io/dgraph#3566]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.15

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
Mac, 16gb ram

- Steps to reproduce the issue (command/config used to run Dgraph).
Using the live loader to import, there is no way to specify auth for loading in RDF's/JSON data, even though there is for altering the schema.

- Expected behaviour and actual result.
The auth token should be used for mutations as well as schema alters but right now it's only being used for schema alters and all mutations are denied based on ACL permissions.

**Comment by gitlw** [comment]
Hi @nodeworks , thanks for letting us know your experience.
The auth token is intended for open source users who don't have access to the ACL feature, which is an enterprise feature. If you do have a contract with us and are using ACL, you don't need to use the auth token anymore as the mechanisms in ACL is more secure than the auth token. 

In the live loader, I’ve just added the support of user login through the `--user` and `--password` options. Please try it out and let us know if you still have issues.

**Comment by gitlw** [comment]
The change for live loader is in #3600

**Comment by campoy** [comment]
Hey @gitlw, can you verify whether this is already fixed and close it if necessary?

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8778). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
