### ISSUE TITLE
Investigate value compression in Dgraph

### ISSUE THREAD

**Issue by Himan000** [dgraph-io/dgraph#3587]
Original RDF data size is 5.7G, after bulk, size of _p_ folder in _out_ is 14G, which is about 2.5 times of original RDF data size.

zero replicas is default to 1 and bulk command is :
`dgraph bulk -r rdf_folder -s test.schema --http localhost:8000 --zero=localhost:5080 --num_go_routines=8`

This is toy data, I have real data which is over 100 times of toy data. If replicas 3 and reduce_shards is 2, then need more nodes and ssd disk. That's too expensive.

Is there any way to reduce disk size? Thanks

**Comment by manishrjain** [comment]
We have plans to introduce compression in Badger (underlying data store). Not to undermine your concerns, but, is disk space a big concern for you? TBs of disk is **not** that expensive to get these days.

**Comment by Himan000** [comment]
Hi @manishrjain,

Thanks for replying so soon. Yes, we just a small company, and the budget is limited. When will you implement the plan and how much the compression rate about?

**Comment by Himan000** [comment]
Hi @manishrjain,

Thanks for replying so soon. Yes, we just a small company, and the budget is limited. When will you implement the plan and how much the compression rate about?

**Comment by manishrjain** [comment]
No ETAs. We'll start to work on it after Badger v2.1 release. So, maybe in a quarter or so. I wouldn't hold my breath on it. FWIW, Dgraph already compresses posting lists. It sounds like your data might be heavy in strings. We could try to do some value level compression and see how things are.

**Comment by Himan000** [comment]
Yes, my data is heavy in strings. Sound great if you can do some value level compression.

**Comment by Himan000** [comment]
Thanks, no more question for this moment. I close this issue.

**Comment by manishrjain** [comment]
I'd like to keep it open to investigate doing value compression in Dgraph.

@gitlw : Can you look into this? It shouldn't be too much work to sometimes do cheap compression on larger values (BitCompletePosting). We can indicate if the value is compressed or not via the meta bit (like BitCompletePosting).

**Comment by niravmehta** [comment]
FWIW, we had to abort our Dgraph plans due to two reasons. 1. Slow ingestion times and 2. Disk space usage. 

I don't think our use case was extreme - about 100k items to be ingest every day with 30-40 properties each. Our tests showed  1gb disk space addition every day - at that rate we'd run out of space on our SSDs fairly quickly. 

I wish we could use Dgraph.. I was so excited about it..

We will try it with ZFS a bit later just to see if that helps with disk space, but ingestion speed is another issue.

**Comment by campoy** [comment]
Hi @niravmehta,

What do you mean my slow ingestion times? I'd love to know more about what you were trying to do and the issues you faced.
Feel free to file a new issue or send me an email to francesc at dgraph.io.

Thanks

**Comment by insanitybit** [comment]
Disk space is actually a potentially large cost for me, so just want to say I would be happy to see this.

**Comment by insanitybit** [comment]
Hey, I see that Badger now supports compression.

What would it look like to enable this for dgraph? I would consider contributing code as this is something quite important for me.

**Comment by manishrjain** [comment]
We do have compression in Badger now. It is also enabled by default. @jarifibrahim can you comment and close this issue?

**Comment by jarifibrahim** [comment]
We added compression in Badger in v2.0.0 release and the same was added to Dgraph a while ago. The compression is enabled by default in dgraph.
