### ISSUE TITLE
Help maintain and create documentation

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#359]
We put all our documentation down in wiki.dgraph.io. We'd really like someone to help maintain, update and extend the documentation there, from the perspective of the user.

If you want to do this full time, talk to us! We can potentially hire you as a contractor.

**Comment by davcdhanesh1** [comment]
Can you please elaborate exactly what kind of help you need in terms of which part of documentation needs immediate attention? Or what is exactly that you are looking for?

**Comment by manishrjain** [comment]
We need a contributor to help maintain and extend our documentation with use cases, tutorials about how to use various features, etc. Like a technical documentation role.
