### ISSUE TITLE
Investigate and fix Cgo memory leak

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#361]
I found and fixed a memory leak when retrieving values from RocksDB, which immediately brought memory usage down by 2GB (from 6GB to 4GB). C layer is still taking up 2GB of space -- of course, some of this is warranted by RocksDB; but we need to systematically look through our Cgo code, check for more leakage and fix it.

Potentially using a tool like Valgrind or GDB might be useful.

**Comment by manishrjain** [comment]
@jchiu0 Added some fixes as well, which now show that the memory doesn't increase monotonically anymore. There's a missing Gig of RAM usage, that we can't account for yet. Most likely it's being used by RocksDB, but we can't confirm it.

Have asked RocksDB team for help.

**Comment by manishrjain** [comment]
@pawanrawal is working on checking if we can switch away from RocksDB entirely. Our access pattern is sort of suited for BoltDB -- given we currently batch our writes, while our reads are instantaneous.

**Comment by manishrjain** [comment]
Put on hold, while I'm working on a RocksDB replacement.

**Comment by manishrjain** [comment]
Rocksdb Cgo no longer leaks memory.

**Comment by vitalyisaev2** [comment]
@manishrjain Could you please share your experience of debugging RocksDB memory leaks? I'm working on a similar service and trying to find out what cause high memory consumption. `pprof` shows that heap is almost empty, whereas `RSS` size is about 2-4 GB.
