### ISSUE TITLE
Allow multiple values per Posting List

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#362]
Allow multiple values per PL, one per label; so we can support language labels easily.

```
<_uid_:0x01> <name> "english-name"@en
<_uid_:0x01> <name> "Жанна"@ru
```

2. Allow filtering value by label or retrieving any one of these multiple values.
3. When returning value, also return label.
4. Allow looking for any value with label preference. If no preference is provided, any value would be returned. If preference is provided, the value with first available label in the list would be provided. For e.g., looking (ru, en) in above would return the russian name, while (en, ru) would return english name. looking for (hi, ru, en) would still return Russian name, because Hindi name is not available.

**Comment by manishrjain** [comment]
Thinking more about this, the query could be like this:

```
{ me(_uid_: 0x01) { age, name@en:ru:hi, name@en, name }}
```

- `name@en:ru:hi`, will look for names in those languages in order; and return the first available one.
- `name@en` will look for names in just English, and return that if available.
- `name` will look for the name in any language present. The first language in the PL would be picked up.

Note that the value PLs would now contain multiple values one for each language, and one when no language is present -- I think the existing `math.Uint64Max` value should be set for no language specified, and the rest calculated from a hash of language tag.

- Note that backup code would need to be modified to output multiple RDFs per value PL, where multiple lang tags are present.

**Comment by manishrjain** [comment]
Moving this to v0.8. Ideally, we do this after we make a decision about query parsing using ANTLR etc.

**Comment by ankurayadav** [comment]
@manishrjain I want to take this up!

**Comment by manishrjain** [comment]
@ankurayadav -- This is going to be a big change affecting the entire code base. So, one of the core team members is better suited for this.
