### ISSUE TITLE
Grafana support

### ISSUE THREAD

**Issue by joshhopkins** [dgraph-io/dgraph#3636]
Be great to use Dgraph with Grafana for analytics and monitoring. Hoping to get both communities working towards this. Collecting votes here: https://github.com/grafana/grafana/issues/17933

**Comment by gitlw** [comment]
Hi @joshhopkins , thanks for filing this request. We already have support for monitoring the metrics from graphana, and you can find the docs at https://docs.dgraph.io/deploy/#monitoring.
For a quick start, you can even generate a docker-compose.yml file containing dgraph nodes working with prometheus+grafana by running the following commands inside the $GOPATH/src/github.com/dgraph-io/dgraph/compose directory
```
go build
./compose -a 1 -z 1 -m
```
