### ISSUE TITLE
Sorting by multiple facets

### ISSUE THREAD

**Issue by KevOrr** [dgraph-io/dgraph#3638]
## Experience Report

Note: Feature requests are judged based on user experience and modeled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### What you wanted to do

You can use `orderasc` to sort by multiple predicates, which will combine their orderings using lexicographic ordering:

```
{
  asdf(func: has(DOB), orderasc: DOB, orderasc: name) {
    uid
    DOB
    name
  }
}
```

It would be nice if we could lexicographically sort by multiple facets in the same way:

```
{
  asdf(func: has(edge)) {
    uid
    edge @facets(kind, index, orderasc: kind, orderasc: index) {
      uid
    }
  }
}
```

### What you actually did

Sort by one facet, and then sort by the other on the client side, or leave unsorted and handle all sorting client-side.

### Why that wasn't great, with examples

In complex, deeply nested queries, it can be cumbersome to post-process results. It divides the intended query into two steps: the actual query, and then a sorting phase. This is trickier to maintain. Besides, graphql(+-) already lends itself nicely to things such as sorting.

### Any external references to support your case

https://discuss.dgraph.io/t/sorting-by-multiple-facets/4670

**Comment by campoy** [comment]
This seems like a pretty straight forward request that makes total sense.

We'll consider it for the roadmap in v1.2.

Thanks for the report, @KevOrr !

**Comment by campoy** [comment]
Another user requested this via https://discuss.dgraph.io/t/do-facets-support-multi-sorting/5587/4

**Comment by ashish-goswami** [comment]
Hey @KevOrr, we have merged PR for this change in master. Please let us know you feedback.
