### ISSUE TITLE
DELETE node with where condition

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3651]
It would be nice to have syntax to delete nodes with a "Where" condition like in SQL.
Currently I first need to do a query to fetch the uids. Then I need to delete those uids.

More specifically, I want to delete all nodes where the created_at is after a certain interval.

**Comment by ashim-k-saha** [comment]
It should have "Time to Live (TTL)" feature also.

**Comment by mangalaman93** [comment]
We are working on Conditional Upsert Block which provides you exactly what you want. This should be available in v1.1 which we plan to release end of this month. For more details, you can check out the following links -
* PR for Conditional Upsert https://github.com/dgraph-io/dgraph/pull/3612 - In Progress
* PR for Upsert Block https://github.com/dgraph-io/dgraph/pull/3412 - Already merged to master
* GitHub issue https://github.com/dgraph-io/dgraph/issues/3059

Please feel free to let me know if you have more questions or features (functions) that you would like us to support in Upsert Block.

**Comment by pjebs** [comment]
Will this be able to do conditional deletes?

**Comment by MichelDiz** [comment]
@pjebs yes, you will be able to do cond deletes.

**Comment by MichelDiz** [comment]
Just use https://dgraph.io/docs/mutations/upsert-block/#sidebar
