### ISSUE TITLE
dgraph help command fails

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#3661]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

Latest as July 12th (fc8bcde77107b92f5eb08f991c2e6616cf4b3291)

- Have you tried reproducing the issue with latest release?

Yes

- What is the hardware spec (RAM, OS)?

MacBook Air - OSX

- Steps to reproduce the issue (command/config used to run Dgraph).

`dgraph help acl`

- Expected behaviour and actual result.

I should see some output explaining how to use `acl`, instead I see:

```
[Decoder]: Using assembly version of decoder
Error: unknown command "acl" for "dgraph help"
```

**Comment by martinmr** [comment]
Somebody with access to a OSX machine is going to need to debug this issue because the command works fine in Linux.

One idea, maybe the library responsible for the help command is not vendored in and you are using a different version of it when you build Dgraph in OSX.

**Comment by jmftrindade** [comment]
(Passing by, and thought I'd comment here since I just installed Dgraph on OSX with `curl https://get.dgraph.io -sSf | bash`)

Is `acl` a valid command?  The list of commands in the tree doesn't currently include it:
https://github.com/dgraph-io/dgraph/tree/05eec2787cc4b681c4d1507b2ed7933436285263/dgraph/cmd

The list of commands in the source tree also matches what I get with `dgraph`:
```
 $ dgraph

(...)

Dgraph version   : v1.0.16
Commit SHA-1     : 0590ee95
Commit timestamp : 2019-07-11 11:52:54 -0700
Branch           : HEAD
Go version       : go1.12.5

(...)

Usage:
  dgraph [command]

Available Commands:
  alpha       Run Dgraph Alpha
  bulk        Run Dgraph bulk loader
  cert        Dgraph TLS certificate management
  conv        Dgraph Geo file converter
  debug       Debug Dgraph instance
  help        Help about any command
  increment   Increment a counter transactionally
  live        Run Dgraph live loader
  restore     Run Dgraph (EE) Restore backup
  version     Prints the dgraph version details
  zero        Run Dgraph Zero

(...)
Use "dgraph [command] --help" for more information about a command.
```

If I follow the `dgraph [command] --help` syntax from above, and pick one of the commands from the list, it works as expected, e.g.,:
```
$ dgraph bulk --help
Run Dgraph bulk loader

Usage:
  dgraph bulk [flags]
(...)
```

Hope that helps.

**Comment by martinmr** [comment]
@jmftrindade If you build Dgraph from master, you should see the acl command. Can you try that?

**Comment by jmftrindade** [comment]
Yup, `acl` shows up as a command on the latest from master.  Fetched source as per README.md:

```
go get -v github.com/dgraph-io/dgraph/dgraph
```

Then using that binary, acl shows up as a valid cmd, and help works fine for it (NOTE: I have $GOPATH/bin in my $PATH):
```
$ dgraph acl --help
[Decoder]: Using assembly version of decoder
Run the Dgraph acl tool

Usage:
  dgraph acl [command]

Available Commands:
  add         Run Dgraph acl tool to add a user or group
  del         Run Dgraph acl tool to delete a user or group
  info        Show info about a user or group
  mod         Run Dgraph acl tool to modify a user's password, a user's group list, or agroup's predicate permissions

(...)

Use "dgraph acl [command] --help" for more information about a command.
```

**Comment by gitlw** [comment]
@campoy I think the correct command should be "dgraph acl help", instead of "dgraph help acl".
And the latter shows the same error on Linux.

**Comment by campoy** [comment]
let me close this issue while importing a suitable GIF while I realize that I was running the command in the wrong order

![facepalm](https://media.giphy.com/media/3og0INyCmHlNylks9O/giphy.gif)
