### ISSUE TITLE
Specify number of nearest entities to return

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#369]
Instead of always passing a distance for `nearby` query, we should have a `nearest:N` query, which can return the nearest N results.

**Comment by kostub** [comment]
Here is a blogpost from MongoDB describing what they did:
https://www.mongodb.com/blog/post/geospatial-performance-improvements-in-mongodb-3-2

**Comment by dmonay** [comment]
@manishrjain I'd like to take this on.

**Comment by manishrjain** [comment]
Go for it.

**Comment by dmonay** [comment]
@manishrjain I'm still working on this.

**Comment by dmonay** [comment]
@manishrjain I'd like to get your input on implementation details. I’m operating under the assumption that a `nearest` query would look something like this:
 ```
{
  tourist( nearest("loc", "[-122.4140288, 37.8083504]", "10" ) ) {
    name
  }
}
```
with the last parameter being `N`, the query returning the nearest N queries to the provided point. We could maybe include an optional parameter `maxD` that could serve as another termination condition.

Following what the mongo blog post sketched out: the logic for the `nearest` query would have to wrap around the `near` query, and recurse in growing intervals. The current logic for the `near`query is a pipeline:
1. `processTask` gets tokens from `GetGeoTokens`
2. `processTask` then gets or creates the posting list
3. `processTask` then calls `FilterGeoUids`
4. `FilterGeoUids` iterates over the values in the PL, and for each one, checks whether it is contained by the cap (created from the provided point)

The recursive algorithm would need to wrap this whole pipeline in a function that can then be called recursively until some termination condition is met (either have found `N` results or traversed `maxD` distance). How performant do we need v1 of this query to be? If the answer is very, I think the pipeline will either have to be refactored or partly duplicated into the recursive algorithm. If the answer is not very, then we can just run multiple iterations of the full pipeline and select a big enough initial search radius
