### ISSUE TITLE
The default prometheus metrics are missing in current master branch

### ISSUE THREAD

**Issue by gitlw** [dgraph-io/dgraph#3717]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
version 1.1 (not released yet)

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
32G RAM, Fedora

- Steps to reproduce the issue (command/config used to run Dgraph).
In the compose directory, do ./run.sh -a 1 -z 1 -m
Check the prometheus metrics at localhost:8180/debug/prometheus_metrics
and the default premetheus metrics such as go_goroutines, go_memstats_heap_alloc_bytes are not there (these stats are available in the release/v1.0 branch) 

- Expected behaviour and actual result.
The stats should still be there as they can be very important for troubleshooting.

**Comment by danielmai** [comment]
Looks like we'll need to collect the metrics ourselves and push them through OpenCensus stats: https://github.com/census-instrumentation/opencensus-go/issues/784

**Comment by gitlw** [comment]
It turns out that the github.com/prometheus/client_golang/prometheus/registry.go has a init that would register a collector for the default runtime metrics
https://github.com/prometheus/client_golang/blob/master/prometheus/registry.go#L61
In release/v1.0, the "github.com/prometheus/client_golang/prometheus" package is imported in the x/metrics.go file, and that's how we get the default runtime metrics.

In this PR https://github.com/dgraph-io/dgraph/pull/2932/files#diff-410b1798298c6520d0200ec988ff3d13
while integrating with opencensus, we switched all the stats from prometheus to opencensus and thus removed the default runtime metrics that's part of prometheus.
Today OC does not yet support the common runtime metrics (the feature request is being tracked in the link posted above by @danielmai , and it's been pending there for over one year).

It seems like to resolve this for now, we need to switch back to prometheus metrics, and only use OpenCensus for tracing.
