### ISSUE TITLE
dgraph bulk load 100G rdf.gz files met  fatal error: runtime: out of memory at reduce phase 

### ISSUE THREAD

**Issue by tiankonghewo** [dgraph-io/dgraph#3726]
I want to import 1000 rdf.gz file into dgraph through dgraph bulk load,
 each file about 100M,total about 102G,
machine configurations are：
>16core
64G RAM
2T SSD

I pull docker 
`docker pull dgraph/dgraph `
`docker run -itd -v /root/dgraph:/opt --name dgraph dgraph/dgraph dgraph zero
`
`
docker exec -it dgraph bash
`

below is command  I lanuched in container

`dgraph bulk \  `                   
`--rdfs  merge \`
`--schema_file a.schema \`
`--num_go_routines=8 \`
`--mapoutput_mb=64   \`
`--map_shards=4 \`
`--shufflers=1  \`
`--reduce_shards=3 \   `      
`--out g2 \`
`--ignore_errors \`
`--http localhost:8000 \`
`--zero=localhost:5080`

the map phase about 14 hours，
When running to the reduce stage, there are always  out of memory problems.

> REDUCE 09h01m56s edge_count:11.13G edge_speed:342.3k/sec plist_count:1.861G plist_speed:57.24k/sec
REDUCE 09h01m57s edge_count:11.13G edge_speed:342.3k/sec plist_count:1.861G plist_speed:57.24k/sec
REDUCE 09h01m58s edge_count:11.13G edge_speed:342.3k/sec plist_count:1.861G plist_speed:57.23k/sec
REDUCE 09h01m59s edge_count:11.13G edge_speed:342.3k/sec plist_count:1.861G plist_speed:57.23k/sec
REDUCE 09h02m00s edge_count:11.13G edge_speed:342.3k/sec plist_count:1.861G plist_speed:57.23k/sec
REDUCE 09h02m01s edge_count:11.13G edge_speed:342.2k/sec plist_count:1.861G plist_speed:57.23k/sec
fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x1558892, 0x16)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xceb4000000, 0x4000000, 0x1f88458)
	/usr/local/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x1f6f740, 0x2000, 0x1f6f750, 0x1)
	/usr/local/go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x1f6f740, 0x1, 0x0)
	/usr/local/go/src/runtime/mheap.go:1222 +0x42
runtime.(*mheap).allocSpanLocked(0x1f6f740, 0x1, 0x1f88468, 0x7ec6cdbe8700)
	/usr/local/go/src/runtime/mheap.go:1150 +0x37f
runtime.(*mheap).alloc_m(0x1f6f740, 0x1, 0xc00151000c, 0x7ec6cdbe8701)
	/usr/local/go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:1048 +0x4c
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1153
goroutine 24183032 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc13a741c70 sp=0xc13a741c68 pc=0x946030
runtime.(*mheap).alloc(0x1f6f740, 0x1, 0x1000c, 0x7ec6cdbe8940)
	/usr/local/go/src/runtime/mheap.go:1047 +0x8a fp=0xc13a741cc0 sp=0xc13a741c70 pc=0x90f0fa
runtime.(*mcentral).grow(0x1f6fdc0, 0x0)
	/usr/local/go/src/runtime/mcentral.go:256 +0x95 fp=0xc13a741d08 sp=0xc13a741cc0 pc=0x902045
runtime.(*mcentral).cacheSpan(0x1f6fdc0, 0x7ec6cdbe8940)
	/usr/local/go/src/runtime/mcentral.go:106 +0x2ff fp=0xc13a741d68 sp=0xc13a741d08 pc=0x901b4f
runtime.(*mcache).refill(0x7f44b6da5f80, 0xc)
	/usr/local/go/src/runtime/mcache.go:135 +0x86 fp=0xc13a741d88 sp=0xc13a741d68 pc=0x9015e6
runtime.(*mcache).nextFree(0x7f44b6da5f80, 0xc13a741e0c, 0xa953db, 0xc0a9699000, 0xc064578314)
	/usr/local/go/src/runtime/malloc.go:786 +0x88 fp=0xc13a741dc0 sp=0xc13a741d88 pc=0x8f5d68
runtime.mallocgc(0x50, 0x14c7c40, 0x1, 0xceb3feff01)
	/usr/local/go/src/runtime/malloc.go:939 +0x76e fp=0xc13a741e60 sp=0xc13a741dc0 pc=0x8f667e
runtime.newobject(0x14c7c40, 0x0)
	/usr/local/go/src/runtime/malloc.go:1068 +0x38 fp=0xc13a741e90 sp=0xc13a741e60 pc=0x8f6a88
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.readMapOutput(0xc082b92ea0, 0x21, 0xc19d4041e0)
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/shuffle.go:100 +0x28e fp=0xc13a741fc8 sp=0xc13a741e90 pc=0x125d41e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc13a741fd0 sp=0xc13a741fc8 pc=0x948101
created by github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*shuffler).run.func1
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/shuffle.go:53 +0x13e
goroutine 1 [chan receive, 17 minutes]:
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*reducer).run(0xc00000e7e0)
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/reduce.go:38 +0x20a
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*loader).reduceStage(0xc000145800)
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/loader.go:280 +0x119
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.run()
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/run.go:207 +0xbbc
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.init.0.func1(0xc0000d7d40, 0xc000444600, 0x0, 0x10)
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/run.go:44 +0x52
github.com/dgraph-io/dgraph/vend

But there are only a few parameters that can adjust the amount of memory used.

> --num_go_routines=8 \
--mapoutput_mb=64   \
--map_shards=4 \
--shufflers=1  \
--reduce_shards=3 \

I've adjusted very low. I don't know how to adjust it next.
But it only uses  about 20G of memory.
Observed by docker command
>docker stats

The total memory is 64G.
There's still a lot of memory available, and it's not clear why the error out of  memory is reported

**Comment by manishrjain** [comment]
Try setting GOGC to 50 or something. We realized Go isn't fast enough in reclaiming space back.

**Comment by manishrjain** [comment]
Also, might make sense for us to investigate using sync.Pool in bulk loader to reuse memory.

**Comment by tiankonghewo** [comment]
> Try setting GOGC to 50 or something. We realized Go isn't fast enough in reclaiming space back.

I only saw three executable files, under **dgraph-darwin-amd64** directory
>badger		dgraph		dgraph-ratel

I know not much about golang，Where can I set this parameter？

>Try setting GOGC to 50 or something

Thank you

**Comment by tiankonghewo** [comment]
> > Try setting GOGC to 50 or something. We realized Go isn't fast enough in reclaiming space back.
> 
> I only saw three executable files, under **dgraph-darwin-amd64** directory
> 
> > badger		dgraph		dgraph-ratel
> 
> I know not much about golang，Where can I set this parameter？
> 
> > Try setting GOGC to 50 or something
> 
> Thank you

maybe， I should learn some about go

**Comment by niravmehta** [comment]
Did this work finally? 

What was the disk size of the data after import?

**Comment by tiankonghewo** [comment]
> Did this work finally?
> 
> What was the disk size of the data after import?

the tmp file about 920G, I set 3 group, each group about 150~200G, total 600G
I use aliyun cloud ,
>128G
64core
2T SSD

Eventually it succeeded
