### ISSUE TITLE
how dgraph bulk set  GOGC=40?

### ISSUE THREAD

**Issue by tiankonghewo** [dgraph-io/dgraph#3736]
dgraph is go program, so how I set this GOGC=40 parameter when execute
>dgraph bulk \
--rdfs  graph_data \
--schema_file a.schema \
--num_go_routines=8 \
--mapoutput_mb=64   \
--map_shards=8 \
--shufflers=1  \
--reduce_shards=3 \
--out g2 \
--ignore_errors \
--http localhost:8000 \
--zero=localhost:5080

**Comment by martinmr** [comment]
It's an environmental variable. To run it one time do `GOGC=40 dgraph ...` or set it in your shell by doing `export GOGC=40`.

**Comment by tiankonghewo** [comment]
> set it in your shell by doing `export GOGC=40`.

I understand this sentence.

but 
>GOGC=40 dgraph ...

What does this sentence mean？
you mean when I 
> docker run -d dgraph/dgraph

set 
>GOGC=40 dgraph

But what exactly to do it？
Can you give an example?
thank you very much！

**Comment by campoy** [comment]
You can run

```
> GOGC-40 dgraph bulk \
--rdfs graph_data \
--schema_file a.schema \
--num_go_routines=8 \
--mapoutput_mb=64 \
--map_shards=8 \
--shufflers=1 \
--reduce_shards=3 \
--out g2 \
--ignore_errors \
--http localhost:8000 \
--zero=localhost:5080```

Alternatively, you can run the environment variable setting first:

On Linux or Mac:

```bash
> GOGC=40
```

On Windows:

```bash
> SET GOGC=40
```

Then run the `dgraph` command in the same terminal.

Alternatively, if you're using docker (which it seems you are according to your question) you can pass the environment variable to Docker by setting it through the -e flag.

```bash
> docker run -e GOGC=40 -d dgraph/dgraph
```

Let us know if you need more help.
