### ISSUE TITLE
Use blank nodes instead of _new_

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#374]
```
mutation {
 set {
  <_new_:class> <student> <_new_:x> .
  <_new_:x> <name> "alice" .
 }
}
```

Nquads syntax allows to specify file/request-local IDs called blank nodes (bnodes). This is a standard approach, and I think it will be better to use them to auto-assign internal IDs:

```
mutation {
 set {
  _:class <student> _:x .
  _:x <name> "alice" .
 }
}
```

**Comment by ashwin95r** [comment]
Addressed with 046ace657bf51cf395f64ab1237da486a1457f12.
