### ISSUE TITLE
Possible to add corrupted data to DB which crash the server when trying to query it

### ISSUE THREAD

**Issue by felixfbecker** [dgraph-io/dgraph#3740]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

Dgraph version   : v1.0.16
Commit SHA-1     : 0590ee95
Commit timestamp : 2019-07-11 11:52:54 -0700
Branch           : HEAD
Go version       : go1.12.5

- Have you tried reproducing the issue with latest release?

should be latest

- What is the hardware spec (RAM, OS)?

macOS

- Steps to reproduce the issue (command/config used to run Dgraph).

I tried to figure out how to use the `geo` type. The API takes either a Base64 string or a `UInt8Array`. I wasn't sure how to encode coordinate in that, so I tried
```ts
value.setGeoVal(Buffer.from(JSON.stringify({ type: 'Point', coordinates: [0, 1] }).toString('base64'))
```
The mutation succeeded, but when I then queried for the UID, the server crashed with
```
2019/07/31 16:12:59 Error while interpreting appropriate type from binary error: wkb: unknown byte order: 1111011
```

- Expected behaviour and actual result.

This seems like it should not happen, the server should validate data before inserting so that corrupted data cannot crash the server.

**Comment by campoy** [comment]
Hi @felixfbecker,

Thanks for the report! Can you reproduce the issue on v1.1.0?

**Comment by campoy** [comment]
In the meantime, could you have a look @prashant-shahi?
Also, could you confirm whether this is a dgraph-js issue or something that could happen in other clients / curl?

**Comment by mangalaman93** [comment]
I am able to reproduce this issue using Go code. Looking into it to figure out what is going on.
