### ISSUE TITLE
incorrect regex for docker swarm hostnames

### ISSUE THREAD

**Issue by sandys** [dgraph-io/dgraph#3748]
https://github.com/dgraph-io/dgraph/blob/60b2b15240c676639f80428837344c3cb19c2fdb/x/x.go#L71

this regex is incorrect for docker swarm. The service names in swarm (which are prepended by stack names) carry underscores.

for example if the stack name is "mystack" and you service name defined in compose file is "svc1", the actual running service is called "mystack_svc1". This regex fails in that case.

This is happening on latest master.

**Comment by mangalaman93** [comment]
Not sure why hostname regex generally does not support underscore https://stackoverflow.com/questions/106179/regular-expression-to-match-dns-hostname-or-ip-address. Looking into it more.

**Comment by ptsilva** [comment]
This also happen here. Maybe the regex could be change to accept underscore. But for now set `--my` with `0.0.0.0:port`, it's works.

**Comment by danielmai** [comment]
The doc fix #4418 addresses this by fixing the Docker Compose file service names. #3027 had fixed a bug to correctly parse IPs, and this then led to the hostname regex check failing for hostnames with underscores. Dgraph is doing the right thing here. Underscores are not valid in hostnames.

Although Docker Compose / Docker Swarm can name services as `mystack_svc1`, the correct DNS name would be `svc1`. So the right way to configure Dgraph's `--my` flag would be to set the address part as `svc1`.
