### ISSUE TITLE
Use <0xid> instead of <_uid_:0xid> in RDFs

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#375]
We can avoid redundancy that way.

**Comment by manishrjain** [comment]
If it starts with a digit, treat it as a UID. If it starts with a letter, then it's an xid.

**Comment by dennwc** [comment]
May I suggest to use bnodes instead? IRIs are meant to be globally unique, thus <0x01> for two datastores should mean the same node. Blank nodes on other hand are local to file/store.
XIDs might be called IRIs, if they are stable.

**Comment by ashwin95r** [comment]
Addressed with 046ace657bf51cf395f64ab1237da486a1457f12.
