### ISSUE TITLE
Dgraph-ratel is not able to connect when running example docker-compose script

### ISSUE THREAD

**Issue by kfyhn** [dgraph-io/dgraph#3776]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.16 (I have also tried with v1.0.15)

- Have you tried reproducing the issue with latest release?
This is the latest release.

- What is the hardware spec (RAM, OS)?
Ubuntu 18.04.2 LTS
Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
16GB RAM

- Steps to reproduce the issue (command/config used to run Dgraph).
1. Run the docker-compose example at: https://docs.dgraph.io/get-started#docker-compose
2. Browse to http://localhost:8000

- Expected behaviour and actual result.
Expected behaviour: Ratel is able to connect to cluster
Actual result: Ratel cannot connect to cluster (see screenshot)
![Screenshot from 2019-08-08 11-34-10](https://user-images.githubusercontent.com/42058844/62692201-82c81e80-b9d0-11e9-9856-637bb6fd5d74.png)

I am able to communicate with Dgraph Alpha via curl, e.g. by running the example mutations in https://docs.dgraph.io/get-started#storing-data-in-the-graph, so I believe the server is running.

Output from docker-compose up:
```
Recreating dgraph_zero_1 ... 
Recreating dgraph_ratel_1 ... 
Recreating dgraph_ratel_1
Recreating dgraph_server_1 ... 
Recreating dgraph_zero_1
Recreating dgraph_server_1 ... done
Attaching to dgraph_ratel_1, dgraph_zero_1, dgraph_server_1
ratel_1   | 2019/08/08 09:24:31 Listening on port 8000...
zero_1    | I0808 09:24:32.566014       1 init.go:88] 
zero_1    | 
server_1  | I0808 09:24:33.417523       1 init.go:88] 
server_1  | 
zero_1    | Dgraph version   : v1.0.16
server_1  | Dgraph version   : v1.0.16
zero_1    | Commit SHA-1     : 0590ee95
server_1  | Commit SHA-1     : 0590ee95
zero_1    | Commit timestamp : 2019-07-11 11:52:54 -0700
server_1  | Commit timestamp : 2019-07-11 11:52:54 -0700
zero_1    | Branch           : HEAD
server_1  | Branch           : HEAD
zero_1    | Go version       : go1.12.5
server_1  | Go version       : go1.12.5
zero_1    | 
server_1  | 
zero_1    | For Dgraph official documentation, visit https://docs.dgraph.io.
server_1  | For Dgraph official documentation, visit https://docs.dgraph.io.
zero_1    | For discussions about Dgraph     , visit https://discuss.dgraph.io.
server_1  | For discussions about Dgraph     , visit https://discuss.dgraph.io.
server_1  | To say hi to the community       , visit https://dgraph.slack.com.
server_1  | 
server_1  | Licensed variously under the Apache Public License 2.0 and Dgraph Community License.
zero_1    | To say hi to the community       , visit https://dgraph.slack.com.
server_1  | Copyright 2015-2018 Dgraph Labs, Inc.
zero_1    | 
server_1  | 
zero_1    | Licensed variously under the Apache Public License 2.0 and Dgraph Community License.
server_1  | 
zero_1    | Copyright 2015-2018 Dgraph Labs, Inc.
zero_1    | 
zero_1    | 
server_1  | I0808 09:24:33.417802       1 run.go:461] x.Config: {DebugMode:false PortOffset:0 QueryEdgeLimit:1000000 NormalizeNodeLimit:10000}
server_1  | I0808 09:24:33.417816       1 run.go:462] worker.Config: {ExportPath:export NumPendingProposals:256 Tracing:1 MyAddr:server:7080 ZeroAddr:zero:5080 RaftId:0 ExpandEdge:true WhiteListedIPRanges:[] MaxRetries:-1 StrictMutations:false SnapshotAfter:10000 AbortOlderThan:5m0s}
server_1  | I0808 09:24:33.417833       1 run.go:463] edgraph.Config: {PostingDir:p BadgerTables:mmap BadgerVlog:mmap WALDir:w MutationsMode:0 AuthToken: AllottedMemory:2048}
zero_1    | I0808 09:24:32.566994       1 run.go:98] Setting up grpc listener at: 0.0.0.0:5080
server_1  | I0808 09:24:33.417858       1 server.go:115] Setting Badger table load option: mmap
server_1  | I0808 09:24:33.417864       1 server.go:127] Setting Badger value log load option: mmap
zero_1    | I0808 09:24:32.567648       1 run.go:98] Setting up http listener at: 0.0.0.0:6080
server_1  | I0808 09:24:33.417869       1 server.go:155] Opening write-ahead log BadgerDB with options: {Dir:w ValueDir:w SyncWrites:false TableLoadingMode:1 ValueLogLoadingMode:2 NumVersionsToKeep:1 ReadOnly:false Truncate:true Logger:0x1f86470 MaxTableSize:67108864 LevelSizeMultiplier:10 MaxLevels:7 ValueThreshold:65500 NumMemtables:5 NumLevelZeroTables:5 NumLevelZeroTablesStall:10 LevelOneSize:268435456 ValueLogFileSize:1073741823 ValueLogMaxEntries:10000 NumCompactors:2 CompactL0OnClose:true LogRotatesToFlush:2 managedTxns:false maxBatchCount:0 maxBatchSize:0}
zero_1    | badger 2019/08/08 09:24:32 INFO: All 1 tables opened in 2ms
zero_1    | badger 2019/08/08 09:24:32 INFO: Replaying file id: 0 at offset: 25521
server_1  | I0808 09:24:33.430260       1 node.go:88] All 1 tables opened in 9ms
zero_1    | badger 2019/08/08 09:24:32 INFO: Replay took: 34.574µs
zero_1    | badger 2019/08/08 09:24:32 DEBUG: Value Log Discard stats: map[]
server_1  | I0808 09:24:33.433617       1 node.go:88] Replaying file id: 9 at offset: 338842
server_1  | I0808 09:24:33.433636       1 node.go:88] Replay took: 10.688µs
zero_1    | I0808 09:24:32.594120       1 node.go:157] Setting raft.Config to: &{ID:1 peers:[] learners:[] ElectionTick:100 HeartbeatTick:1 Storage:0xc0005a4510 Applied:0 MaxSizePerMsg:262144 MaxCommittedSizePerReady:67108864 MaxUncommittedEntriesSize:0 MaxInflightMsgs:256 CheckQuorum:false PreVote:true ReadOnlyOption:0 Logger:0x1f86470 DisableProposalForwarding:false}
server_1  | I0808 09:24:33.433688       1 server.go:115] Setting Badger table load option: mmap
server_1  | I0808 09:24:33.433697       1 server.go:127] Setting Badger value log load option: mmap
zero_1    | I0808 09:24:32.597125       1 node.go:317] Found hardstate: {Term:14 Vote:1 Commit:132 XXX_unrecognized:[]}
server_1  | I0808 09:24:33.433702       1 server.go:169] Opening postings BadgerDB with options: {Dir:p ValueDir:p SyncWrites:false TableLoadingMode:2 ValueLogLoadingMode:2 NumVersionsToKeep:2147483647 ReadOnly:false Truncate:true Logger:0x1f86470 MaxTableSize:67108864 LevelSizeMultiplier:10 MaxLevels:7 ValueThreshold:1024 NumMemtables:5 NumLevelZeroTables:5 NumLevelZeroTablesStall:10 LevelOneSize:268435456 ValueLogFileSize:1073741823 ValueLogMaxEntries:1000000 NumCompactors:2 CompactL0OnClose:true LogRotatesToFlush:2 managedTxns:false maxBatchCount:0 maxBatchSize:0}
server_1  | I0808 09:24:33.439673       1 node.go:88] All 1 tables opened in 4ms
zero_1    | I0808 09:24:32.597891       1 node.go:326] Group 0 found 133 entries
zero_1    | I0808 09:24:32.597925       1 raft.go:433] Restarting node for dgraphzero
server_1  | I0808 09:24:33.453617       1 node.go:88] Replaying file id: 0 at offset: 6848731
server_1  | I0808 09:24:33.453645       1 node.go:88] Replay took: 17.3µs
server_1  | I0808 09:24:33.453840       1 groups.go:96] Current Raft Id: 0x1
server_1  | I0808 09:24:33.453901       1 worker.go:81] Worker listening at address: [::]:7080
server_1  | I0808 09:24:33.453917       1 run.go:392] gRPC server started.  Listening on port 9080
server_1  | I0808 09:24:33.453930       1 run.go:393] HTTP server started.  Listening on port 8080
server_1  | I0808 09:24:33.554197       1 pool.go:138] CONNECTED to zero:5080
zero_1    | I0808 09:24:32.598260       1 node.go:88] 1 became follower at term 14
zero_1    | I0808 09:24:32.599190       1 node.go:88] newRaft 1 [peers: [], term: 14, commit: 132, applied: 0, lastindex: 132, lastterm: 14]
zero_1    | I0808 09:24:32.600078       1 run.go:282] Running Dgraph Zero...
zero_1    | I0808 09:24:32.615141       1 node.go:193] Setting conf state to nodes:1 
zero_1    | I0808 09:24:32.615296       1 raft.go:676] Done applying conf change at 0x1
zero_1    | I0808 09:24:32.615597       1 pool.go:138] CONNECTED to server:8080
zero_1    | W0808 09:24:32.615909       1 pool.go:168] Shutting down extra connection to server:8080
zero_1    | I0808 09:24:32.616083       1 oracle.go:106] Purged below ts:25590, len(o.commits):0, len(o.rowCommit):0
zero_1    | W0808 09:24:33.558306       1 pool.go:226] Connection lost with server:8080. Error: rpc error: code = Canceled desc = context canceled
zero_1    | I0808 09:24:33.560622       1 zero.go:396] Got connection request: cluster_info_only:true 
zero_1    | I0808 09:24:33.562042       1 node.go:88] 1 no leader at term 14; dropping index reading msg
zero_1    | W0808 09:24:33.565538       1 pool.go:226] Connection lost with server:8080. Error: rpc error: code = Unavailable desc = transport is closing
zero_1    | I0808 09:24:35.560485       1 node.go:88] 1 is starting a new election at term 14
zero_1    | I0808 09:24:35.560549       1 node.go:88] 1 became pre-candidate at term 14
zero_1    | I0808 09:24:35.560564       1 node.go:88] 1 received MsgPreVoteResp from 1 at term 14
zero_1    | I0808 09:24:35.560671       1 node.go:88] 1 became candidate at term 15
zero_1    | I0808 09:24:35.560690       1 node.go:88] 1 received MsgVoteResp from 1 at term 15
zero_1    | I0808 09:24:35.560925       1 node.go:88] 1 became leader at term 15
zero_1    | I0808 09:24:35.560973       1 node.go:88] raft.node: 1 elected leader 1 at term 15
zero_1    | I0808 09:24:35.561097       1 raft.go:642] I've become the leader, updating leases.
zero_1    | I0808 09:24:35.561126       1 assign.go:42] Updated Lease id: 40001. Txn Ts: 70001
zero_1    | W0808 09:24:35.562084       1 node.go:668] [0x1] Read index context timed out
zero_1    | I0808 09:24:35.576104       1 zero.go:414] Connected: cluster_info_only:true 
zero_1    | I0808 09:24:35.577675       1 zero.go:396] Got connection request: id:1 addr:"server:7080" 
zero_1    | I0808 09:24:35.578264       1 pool.go:138] CONNECTED to server:7080
zero_1    | I0808 09:24:35.578635       1 zero.go:523] Connected: id:1 addr:"server:7080" 
server_1  | I0808 09:24:35.579265       1 groups.go:119] Connected to group zero. Assigned group: 0
server_1  | I0808 09:24:35.579309       1 groups.go:121] Raft Id after connection to Zero: 0x1
server_1  | I0808 09:24:35.579409       1 pool.go:138] CONNECTED to server:8080
server_1  | I0808 09:24:35.579858       1 draft.go:74] Node ID: 0x1 with GroupID: 1
server_1  | I0808 09:24:35.580040       1 node.go:157] Setting raft.Config to: &{ID:1 peers:[] learners:[] ElectionTick:100 HeartbeatTick:1 Storage:0xc0004f6b10 Applied:20181 MaxSizePerMsg:262144 MaxCommittedSizePerReady:67108864 MaxUncommittedEntriesSize:0 MaxInflightMsgs:256 CheckQuorum:false PreVote:true ReadOnlyOption:0 Logger:0x1f86470 DisableProposalForwarding:false}
server_1  | I0808 09:24:35.580890       1 node.go:306] Found Snapshot.Metadata: {ConfState:{Nodes:[1] Learners:[] XXX_unrecognized:[]} Index:20181 Term:5 XXX_unrecognized:[]}
server_1  | I0808 09:24:35.581029       1 node.go:317] Found hardstate: {Term:12 Vote:1 Commit:27735 XXX_unrecognized:[]}
server_1  | W0808 09:24:35.582158       1 pool.go:226] Connection lost with server:8080. Error: rpc error: code = Unavailable desc = transport is closing
server_1  | I0808 09:24:35.589854       1 node.go:326] Group 1 found 7555 entries
server_1  | I0808 09:24:35.589866       1 draft.go:1317] Restarting node for group: 1
server_1  | I0808 09:24:35.589887       1 node.go:193] Setting conf state to nodes:1 
server_1  | I0808 09:24:35.594822       1 node.go:88] 1 became follower at term 12
server_1  | I0808 09:24:35.594878       1 node.go:88] newRaft 1 [peers: [1], term: 12, commit: 27735, applied: 20181, lastindex: 27735, lastterm: 12]
server_1  | I0808 09:24:35.594899       1 groups.go:139] Server is ready
server_1  | I0808 09:24:35.594981       1 groups.go:650] Got address of a Zero leader: zero:5080
server_1  | I0808 09:24:35.595056       1 groups.go:663] Starting a new membership stream receive from zero:5080.
server_1  | I0808 09:24:35.595080       1 draft.go:716] Found Raft progress: 27729
server_1  | I0808 09:24:35.595643       1 groups.go:680] Received first state update from Zero: counter:132 groups:<key:1 value:<members:<key:1 value:<id:1 group_id:1 addr:"server:8080" leader:true last_update:1565254938 > > tablets:<key:"_predicate_" value:<group_id:1 predicate:"_predicate_" space:3271 > > tablets:<key:"age" value:<group_id:1 predicate:"age" space:1057 > > tablets:<key:"boss_of" value:<group_id:1 predicate:"boss_of" space:21 > > tablets:<key:"car" value:<group_id:1 predicate:"car" space:231 > > tablets:<key:"device" value:<group_id:1 predicate:"device" > > tablets:<key:"dgraph.group.acl" value:<group_id:1 predicate:"dgraph.group.acl" space:39 > > tablets:<key:"dgraph.password" value:<group_id:1 predicate:"dgraph.password" space:37 > > tablets:<key:"dgraph.user.group" value:<group_id:1 predicate:"dgraph.user.group" space:43 > > tablets:<key:"dgraph.xid" value:<group_id:1 predicate:"dgraph.xid" space:36 > > tablets:<key:"director" value:<group_id:1 predicate:"director" space:91 > > tablets:<key:"equipment" value:<group_id:1 predicate:"equipment" > > tablets:<key:"event" value:<group_id:1 predicate:"event" > > tablets:<key:"friend" value:<group_id:1 predicate:"friend" space:857 > > tablets:<key:"id" value:<group_id:1 predicate:"id" > > tablets:<key:"industry" value:<group_id:1 predicate:"industry" space:31 > > tablets:<key:"last_online" value:<group_id:1 predicate:"last_online" > > tablets:<key:"latitude" value:<group_id:1 predicate:"latitude" > > tablets:<key:"longitude" value:<group_id:1 predicate:"longitude" > > tablets:<key:"mobile" value:<group_id:1 predicate:"mobile" space:126 > > tablets:<key:"name" value:<group_id:1 predicate:"name" space:3941 > > tablets:<key:"organization" value:<group_id:1 predicate:"organization" > > tablets:<key:"owns_pet" value:<group_id:1 predicate:"owns_pet" space:293 > > tablets:<key:"rated" value:<group_id:1 predicate:"rated" space:533 > > tablets:<key:"release_date" value:<group_id:1 predicate:"release_date" space:232 > > tablets:<key:"revenue" value:<group_id:1 predicate:"revenue" space:111 > > tablets:<key:"running_time" value:<group_id:1 predicate:"running_time" space:136 > > tablets:<key:"serial_number" value:<group_id:1 predicate:"serial_number" > > tablets:<key:"starring" value:<group_id:1 predicate:"starring" space:91 > > tablets:<key:"status" value:<group_id:1 predicate:"status" > > tablets:<key:"system" value:<group_id:1 predicate:"system" > > tablets:<key:"type" value:<group_id:1 predicate:"type" > > tablets:<key:"works_for" value:<group_id:1 predicate:"works_for" > > snapshot_ts:25590 checksum:15224889246912594891 > > zeros:<key:1 value:<id:1 addr:"zero:5080" leader:true > > maxLeaseId:40000 maxTxnTs:70000 maxRaftId:1 cid:"7789850c-6309-4bcc-a01f-b9a17998ca6a" 
server_1  | I0808 09:24:38.115498       1 node.go:88] 1 is starting a new election at term 12
server_1  | I0808 09:24:38.115560       1 node.go:88] 1 became pre-candidate at term 12
server_1  | I0808 09:24:38.115573       1 node.go:88] 1 received MsgPreVoteResp from 1 at term 12
server_1  | I0808 09:24:38.115729       1 node.go:88] 1 became candidate at term 13
server_1  | I0808 09:24:38.115745       1 node.go:88] 1 received MsgVoteResp from 1 at term 13
server_1  | I0808 09:24:38.116011       1 node.go:88] 1 became leader at term 13
server_1  | I0808 09:24:38.116055       1 node.go:88] raft.node: 1 elected leader 1 at term 13
server_1  | I0808 09:24:38.595304       1 groups.go:725] Leader idx=0x1 of group=1 is connecting to Zero for txn updates
server_1  | I0808 09:24:38.595352       1 groups.go:734] Got Zero leader: zero:5080


```

**Comment by mangalaman93** [comment]
Not able to reproduce. Where are you running the cluster (using docker-compose), desktop or on a server?

**Comment by MichelDiz** [comment]
As I see "Recreating" from the docker compose logs. I can imagine that this is a reused env. You probably was doing some tests, changing setup params and so on. I recommend that you start it from scratch.

Do some cleanups:
```
docker-compose rm
```
```
docker stop $(docker ps -a -q)

docker rm $(docker ps -a -q)

docker volume ls

docker volume rm ${name_of_yourCOmpose}
```

**Comment by kfyhn** [comment]
Thank you for your quick feedback - I know the likelihood of this is issue being caused by or related to my setup somehow, is very high, so any tips as to how to debug and find the issue is of great value to me.

@mangalaman93 : This is running on my desktop computer.

@MichelDiz : Correct, I have run the script multiple times to correct this issue. It has been working some months ago, when I last worked on it (that was with version v1.0.15). However, something has changed with my setup, such that it no longer works, but outputs no error messages. I have now run the commands you listed, but the problem still exists - Ratel cannot connect to the cluster. The new output from docker-compose up is:

Creating volume "dgraph_dgraph" with default driver
Creating dgraph_server_1 ... 
Creating dgraph_zero_1 ... 
Creating dgraph_ratel_1 ... 
Creating dgraph_server_1
Creating dgraph_zero_1
Creating dgraph_server_1 ... done
Attaching to dgraph_zero_1, dgraph_ratel_1, dgraph_server_1
zero_1    | I0809 07:57:18.797230       1 init.go:88] 
zero_1    | 
zero_1    | Dgraph version   : v1.0.16
zero_1    | Commit SHA-1     : 0590ee95
zero_1    | Commit timestamp : 2019-07-11 11:52:54 -0700
zero_1    | Branch           : HEAD
ratel_1   | 2019/08/09 07:57:19 Listening on port 8000...
zero_1    | Go version       : go1.12.5
server_1  | I0809 07:57:20.859375       1 init.go:88] 
server_1  | 
server_1  | Dgraph version   : v1.0.16
server_1  | Commit SHA-1     : 0590ee95
server_1  | Commit timestamp : 2019-07-11 11:52:54 -0700
zero_1    | 
server_1  | Branch           : HEAD
zero_1    | For Dgraph official documentation, visit https://docs.dgraph.io.
zero_1    | For discussions about Dgraph     , visit https://discuss.dgraph.io.
zero_1    | To say hi to the community       , visit https://dgraph.slack.com.
server_1  | Go version       : go1.12.5
zero_1    | 
server_1  | 
zero_1    | Licensed variously under the Apache Public License 2.0 and Dgraph Community License.
server_1  | For Dgraph official documentation, visit https://docs.dgraph.io.
zero_1    | Copyright 2015-2018 Dgraph Labs, Inc.
server_1  | For discussions about Dgraph     , visit https://discuss.dgraph.io.
zero_1    | 
server_1  | To say hi to the community       , visit https://dgraph.slack.com.
zero_1    | 
server_1  | 
server_1  | Licensed variously under the Apache Public License 2.0 and Dgraph Community License.
server_1  | Copyright 2015-2018 Dgraph Labs, Inc.
server_1  | 
server_1  | 
zero_1    | I0809 07:57:18.798390       1 run.go:98] Setting up grpc listener at: 0.0.0.0:5080
server_1  | I0809 07:57:20.859703       1 run.go:461] x.Config: {DebugMode:false PortOffset:0 QueryEdgeLimit:1000000 NormalizeNodeLimit:10000}
server_1  | I0809 07:57:20.859716       1 run.go:462] worker.Config: {ExportPath:export NumPendingProposals:256 Tracing:1 MyAddr:server:7080 ZeroAddr:zero:5080 RaftId:0 ExpandEdge:true WhiteListedIPRanges:[] MaxRetries:-1 StrictMutations:false SnapshotAfter:10000 AbortOlderThan:5m0s}
server_1  | I0809 07:57:20.859730       1 run.go:463] edgraph.Config: {PostingDir:p BadgerTables:mmap BadgerVlog:mmap WALDir:w MutationsMode:0 AuthToken: AllottedMemory:2048}
zero_1    | I0809 07:57:18.798496       1 run.go:98] Setting up http listener at: 0.0.0.0:6080
server_1  | I0809 07:57:20.859819       1 server.go:115] Setting Badger table load option: mmap
server_1  | I0809 07:57:20.859825       1 server.go:127] Setting Badger value log load option: mmap
zero_1    | badger 2019/08/09 07:57:18 INFO: All 0 tables opened in 0s
server_1  | I0809 07:57:20.859829       1 server.go:155] Opening write-ahead log BadgerDB with options: {Dir:w ValueDir:w SyncWrites:false TableLoadingMode:1 ValueLogLoadingMode:2 NumVersionsToKeep:1 ReadOnly:false Truncate:true Logger:0x1f86470 MaxTableSize:67108864 LevelSizeMultiplier:10 MaxLevels:7 ValueThreshold:65500 NumMemtables:5 NumLevelZeroTables:5 NumLevelZeroTablesStall:10 LevelOneSize:268435456 ValueLogFileSize:1073741823 ValueLogMaxEntries:10000 NumCompactors:2 CompactL0OnClose:true LogRotatesToFlush:2 managedTxns:false maxBatchCount:0 maxBatchSize:0}
zero_1    | I0809 07:57:18.851204       1 node.go:157] Setting raft.Config to: &{ID:1 peers:[] learners:[] ElectionTick:100 HeartbeatTick:1 Storage:0xc0003fb2f0 Applied:0 MaxSizePerMsg:262144 MaxCommittedSizePerReady:67108864 MaxUncommittedEntriesSize:0 MaxInflightMsgs:256 CheckQuorum:false PreVote:true ReadOnlyOption:0 Logger:0x1f86470 DisableProposalForwarding:false}
zero_1    | I0809 07:57:18.852512       1 node.go:326] Group 0 found 1 entries
server_1  | I0809 07:57:20.897715       1 node.go:88] All 0 tables opened in 0s
zero_1    | I0809 07:57:18.852700       1 node.go:88] 1 became follower at term 0
server_1  | I0809 07:57:20.913245       1 server.go:115] Setting Badger table load option: mmap
server_1  | I0809 07:57:20.913279       1 server.go:127] Setting Badger value log load option: mmap
server_1  | I0809 07:57:20.913295       1 server.go:169] Opening postings BadgerDB with options: {Dir:p ValueDir:p SyncWrites:false TableLoadingMode:2 ValueLogLoadingMode:2 NumVersionsToKeep:2147483647 ReadOnly:false Truncate:true Logger:0x1f86470 MaxTableSize:67108864 LevelSizeMultiplier:10 MaxLevels:7 ValueThreshold:1024 NumMemtables:5 NumLevelZeroTables:5 NumLevelZeroTablesStall:10 LevelOneSize:268435456 ValueLogFileSize:1073741823 ValueLogMaxEntries:1000000 NumCompactors:2 CompactL0OnClose:true LogRotatesToFlush:2 managedTxns:false maxBatchCount:0 maxBatchSize:0}
zero_1    | I0809 07:57:18.853097       1 node.go:88] newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
zero_1    | I0809 07:57:18.853134       1 node.go:88] 1 became follower at term 1
zero_1    | I0809 07:57:18.853336       1 run.go:282] Running Dgraph Zero...
zero_1    | E0809 07:57:18.853707       1 raft.go:499] While proposing CID: Not Zero leader. Aborting proposal: cid:"00b7c19b-2807-4225-a8a8-df4492aa277d" . Retrying...
zero_1    | I0809 07:57:18.865327       1 node.go:193] Setting conf state to nodes:1 
zero_1    | I0809 07:57:18.865449       1 raft.go:676] Done applying conf change at 0x1
zero_1    | I0809 07:57:19.853584       1 node.go:88] 1 no leader at term 1; dropping index reading msg
server_1  | I0809 07:57:20.936406       1 node.go:88] All 0 tables opened in 0s
server_1  | I0809 07:57:20.954745       1 groups.go:96] Current Raft Id: 0x0
server_1  | I0809 07:57:20.955252       1 worker.go:81] Worker listening at address: [::]:7080
server_1  | I0809 07:57:20.955297       1 run.go:392] gRPC server started.  Listening on port 9080
server_1  | I0809 07:57:20.955354       1 run.go:393] HTTP server started.  Listening on port 8080
server_1  | I0809 07:57:21.055243       1 pool.go:138] CONNECTED to zero:5080
zero_1    | I0809 07:57:21.059591       1 zero.go:396] Got connection request: cluster_info_only:true 
zero_1    | W0809 07:57:21.853746       1 node.go:668] [0x1] Read index context timed out
zero_1    | I0809 07:57:21.853874       1 node.go:88] 1 no leader at term 1; dropping index reading msg
zero_1    | E0809 07:57:21.854669       1 raft.go:499] While proposing CID: Not Zero leader. Aborting proposal: cid:"1a43efc8-8e2d-417d-ad6a-ffc7197b6ec9" . Retrying...
zero_1    | I0809 07:57:22.393731       1 node.go:88] 1 is starting a new election at term 1
zero_1    | I0809 07:57:22.393777       1 node.go:88] 1 became pre-candidate at term 1
zero_1    | I0809 07:57:22.393790       1 node.go:88] 1 received MsgPreVoteResp from 1 at term 1
zero_1    | I0809 07:57:22.393819       1 node.go:88] 1 became candidate at term 2
zero_1    | I0809 07:57:22.393830       1 node.go:88] 1 received MsgVoteResp from 1 at term 2
zero_1    | I0809 07:57:22.393853       1 node.go:88] 1 became leader at term 2
zero_1    | I0809 07:57:22.393869       1 node.go:88] raft.node: 1 elected leader 1 at term 2
zero_1    | I0809 07:57:22.393946       1 raft.go:642] I've become the leader, updating leases.
zero_1    | I0809 07:57:22.393964       1 assign.go:42] Updated Lease id: 1. Txn Ts: 1
zero_1    | W0809 07:57:23.853976       1 node.go:668] [0x1] Read index context timed out
zero_1    | I0809 07:57:23.854368       1 zero.go:414] Connected: cluster_info_only:true 
zero_1    | I0809 07:57:23.855597       1 zero.go:396] Got connection request: addr:"server:7080" 
zero_1    | I0809 07:57:23.855972       1 pool.go:138] CONNECTED to server:7080
zero_1    | I0809 07:57:23.868972       1 zero.go:523] Connected: id:1 group_id:1 addr:"server:7080" 
server_1  | I0809 07:57:23.869464       1 groups.go:119] Connected to group zero. Assigned group: 1
server_1  | I0809 07:57:23.869508       1 groups.go:121] Raft Id after connection to Zero: 0x1
server_1  | I0809 07:57:23.870148       1 draft.go:74] Node ID: 0x1 with GroupID: 1
server_1  | I0809 07:57:23.870295       1 node.go:157] Setting raft.Config to: &{ID:1 peers:[] learners:[] ElectionTick:100 HeartbeatTick:1 Storage:0xc0004ee750 Applied:0 MaxSizePerMsg:262144 MaxCommittedSizePerReady:67108864 MaxUncommittedEntriesSize:0 MaxInflightMsgs:256 CheckQuorum:false PreVote:true ReadOnlyOption:0 Logger:0x1f86470 DisableProposalForwarding:false}
server_1  | I0809 07:57:23.870520       1 node.go:326] Group 1 found 1 entries
server_1  | I0809 07:57:23.870578       1 draft.go:1340] New Node for group: 1
server_1  | I0809 07:57:23.870752       1 node.go:88] 1 became follower at term 0
server_1  | I0809 07:57:23.870890       1 node.go:88] newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
server_1  | I0809 07:57:23.870923       1 node.go:88] 1 became follower at term 1
server_1  | I0809 07:57:23.871006       1 groups.go:139] Server is ready
server_1  | I0809 07:57:23.871254       1 draft.go:716] Found Raft progress: 0
server_1  | I0809 07:57:23.871473       1 groups.go:650] Got address of a Zero leader: zero:5080
server_1  | I0809 07:57:23.871887       1 groups.go:663] Starting a new membership stream receive from zero:5080.
server_1  | I0809 07:57:23.883059       1 node.go:193] Setting conf state to nodes:1 
server_1  | I0809 07:57:23.883358       1 node.go:88] 1 is starting a new election at term 1
server_1  | I0809 07:57:23.883388       1 node.go:88] 1 became pre-candidate at term 1
server_1  | I0809 07:57:23.883405       1 node.go:88] 1 received MsgPreVoteResp from 1 at term 1
server_1  | I0809 07:57:23.883442       1 node.go:88] 1 became candidate at term 2
server_1  | I0809 07:57:23.883457       1 node.go:88] 1 received MsgVoteResp from 1 at term 2
server_1  | I0809 07:57:23.883488       1 node.go:88] 1 became leader at term 2
server_1  | I0809 07:57:23.883536       1 node.go:88] raft.node: 1 elected leader 1 at term 2
server_1  | I0809 07:57:23.883782       1 groups.go:372] Serving tablet for: _predicate_
server_1  | I0809 07:57:23.883719       1 groups.go:680] Received first state update from Zero: counter:4 groups:<key:1 value:<members:<key:1 value:<id:1 group_id:1 addr:"server:7080" > > tablets:<key:"_predicate_" value:<group_id:1 predicate:"_predicate_" > > checksum:3910901543130921129 > > zeros:<key:1 value:<id:1 addr:"zero:5080" leader:true > > maxRaftId:1 
server_1  | I0809 07:57:23.913484       1 mutation.go:145] Done schema update predicate:"_predicate_" value_type:STRING list:true 
zero_1    | I0809 07:57:24.865219       1 raft.go:493] CID set for cluster: 7e949be2-9905-49af-9a80-39c6dc33911d
server_1  | I0809 07:57:24.871436       1 groups.go:725] Leader idx=0x1 of group=1 is connecting to Zero for txn updates
server_1  | I0809 07:57:24.871483       1 groups.go:734] Got Zero leader: zero:5080

**Comment by mangalaman93** [comment]
The only other thing I can think of is trying clearing browser cache or trying a different browser. I have had issues on my Mac sometimes where my DNS resolver just stops working in a browser. You could also try using 0.0.0.0 or the IP on the local network instead of localhost just in case if that works.

**Comment by kfyhn** [comment]
@mangalaman93 : That solved the issue! Thank you! I had done several Ctrl+F5 to try and reload the page completely, but when running it without browser cache it works. 0.0.0.0 also solves the problem, but not 127.0.0.1 apparently. 

Thanks a lot for the help - it was then a problem with my setup. However I would consider stating somewhere in the documentation that clearing your browser cache or changing the IP of the server can resolve issues, when Ratel browser cache gets into some kind of undefined state.
