### ISSUE TITLE
Dgraph isn't automatically setting values ​​as list in structured mutations as list.

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#3788]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
1.1RC

- Have you tried reproducing the issue with latest release?
Yes, latest RC

- Steps to reproduce the issue (command/config used to run Dgraph).
Add a list mutation in JSON before set the schema. 

- Expected behaviour and actual result.
Since Dgraph automatically recognizes Types (Like `[uid]` this is a "list") I think it should recognize a list through a structured mutation as a list. Avoiding the user lost some data from his list. In case he forgets to define the scheme before mutating.

I didn't tested it in RDF tho. Will do.

Check reference: https://github.com/dgraph-io/dgraph/issues/3787

**Comment by martinmr** [comment]
Not really a bug so I've changed the tag. The reason uid is set to list is to preserve the existing behavior (since uid used to be a list by default).

**Comment by campoy** [comment]
I do not understand this issue, @MichelDiz 

Could you give an example of a mutation with what you would expect it to create and what it actually creates?

Thanks!
