### ISSUE TITLE
Delete mutation on non-existing triple deletes index entry

### ISSUE THREAD

**Issue by prashant-shahi** [dgraph-io/dgraph#3803]
- What version of Dgraph are you using?
```
Dgraph version   : v1.0.12-rc3-649-g2883f667
Commit SHA-1     : 2883f667
Commit timestamp : 2019-08-08 18:47:40 +0530
Branch           : master
Go version       : go1.12.5
```

- Have you tried reproducing the issue with the latest release?
**Yes.**

- Steps to reproduce the issue (command/config used to run Dgraph).
    - [ ] Follow the tour to [setup Dgraph](https://tour.dgraph.io/master/intro/2/).
    - [ ] Follow the tour to [alter schema](https://tour.dgraph.io/master/intro/3/) and [load data](https://tour.dgraph.io/master/intro/4/).
    - [ ] Open Dgraph UI by visiting http://localhost:8000 and get the uid of `Michael` using following *graphql+-* query.
        ```graphql
        {
            get_michael(func: anyofterms(name, "Michael")) {
                uid
                name
            }
        }
        ```
    - [ ] Go to [delete data tour](https://tour.dgraph.io/schema/7/). Run the following :
        ```rdf
        {
            delete {
                <uid_of_michael> <name> "Asdf" .
            }
        }
        ``` 
    - [ ] Now, using the *graphql+-* query of 3rd step again, we will get empty response. But when we query using `uid` or `has`, we will see that `name` predicate with value `Michael` is still there.
        ```graphql
        {
            get_michael(func: uid(uid_of_michael)) {
                uid
                name
            }
        }
        ```
- Expected behavior and actual result.
Not affecting any data at all.

**Comment by danielmai** [comment]
This does not happen in v1.0.16 because `delete` in v1.0 only supports "S P *" for value predicates instead of specifying the same value.

**Comment by MichelDiz** [comment]
This happens in master. But if we do `<uid_of_michael> <name> "Michael" .` Works fine.
The issue is, deleting something without the correct value ("Asdf" ≠ "Michael"). We should show some error or message.

**Comment by MichelDiz** [comment]
BTW, the real issue here is that when you delete a predicate(name). It looks like it was removed from indexing. I've tested with others users. All nodes and names are still there. But I can't use `eq, anyofterms` and so on. But you can find it by other predicates, by has or by uid.
