### ISSUE TITLE
Unhandled pb.node expand with parent edge

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#3807]
### What version of Dgraph are you using?
v1.0.16. This does **NOT** happen on master.

### Have you tried reproducing the issue with latest release?
Yes (v1.0.16)

### Steps to reproduce the issue (command/config used to run Dgraph).

1. Run Dgraph cluster running v1.0.16
2. Set schema:

```
name: string @index(term) .
age: int .
friend: uid .
```

4. Run query and get error response:

```
{
  q(func: anyofterms(name, "Michael")) {
    uid
    name
    friend {
      uid
      expand(_all_)
    }
  }
}
```
```
{
  "name": "t",
  "url": "http://localhost:8080/query?debug=true",
  "errors": [
    {
      "code": "ErrorInvalidRequest",
      "message": ": Unhandled pb.node expand with parent friend"
    }
  ]
}
```

Remove `expand(_all_)` from the query and get an empty response:

```
{
  q(func: anyofterms(name, "Michael")) {
    uid
    name
    friend {
      uid
    }
  }
}
```
```
{
  "data": {
    "q": []
  }
}
```

### Expected behaviour and actual result.

An empty query response should be returned instead of an error.

**Comment by campoy** [comment]
Hey @danielmai , I'm assigning this to you but feel free to assign it to someone else if you think they could investigate.

**Comment by campoy** [comment]
Hey, @martinmr 

Since you're already working on expand, could you have a look at this one?

**Comment by martinmr** [comment]
Fixed.
