### ISSUE TITLE
1.1.0-rc1: Delete a node and its predicates don't work

### ISSUE THREAD

**Issue by mehdiym** [dgraph-io/dgraph#3811]
- What version of Dgraph are you using?
1.1.0-rc1

- Steps to reproduce the issue (command/config used to run Dgraph).
Create a node and some predicates:
```
{
  set {
    _:player <level> "1" .
    _:player <credits> "2" .
  }
}
```
Try to delete them:
```
{
  delete {
    <0x82> * * .
  }
}
```

- Expected behaviour and actual result.
Neither the node nor the predicates are deleted.
It worked with dGraph 1.0.15.

**Comment by mehdiym** [comment]
My bad, I missed the info in the doc about the required dgraph.type defining all predicates to remove.

**Comment by asa511** [comment]
@mehdiym Can you elaborate on what the new syntax should be to get the following query to work? (The documentation does not seem to be up to date yet.)

```
{
  delete {
    <0x82> * * .
  }
}
```
