### ISSUE TITLE
Add support for @unique

### ISSUE THREAD

**Issue by fridex** [dgraph-io/dgraph#3813]
### What you wanted to do

We want to filter out duplicates in the result on the server side.

### What you actually did

We have implemented queries which can result in duplicate entries in the query result; we filtered them out on the client-side.

### Why that wasn't great, with examples

In most cases we retrieve duplicate data and we experienced serialization issues (maximum size of the response) - we fixed them using pagination. The pagination works fine but it results in unnecessary additional queries to our Dgraph instance and unnecessary client-side code to filter out duplicate entries from the query result.

### An idea for solution

Introduce a new directive `@unique` similar to `@normalize` or `@cascade` which will discard duplicates in the query result on server side.

**Comment by campoy** [comment]
Thanks for the proposal, @fridex!

Could you give more details of a query that would benefit from this?

Since variables are sets, you can easily use them to remove duplicates.

For instance, if you want to get all the genres from all of the movies directed by Steven Spielberg you could do the following:

```graphql
{
  q(func: eq(name@en, "Steven Spielberg")) @normalize {
    director.film {
      genre {
        genre: name@.
      }
    }
  }
}
```

Which returns:

```json
{
  "data": {
    "q": [
      {
        "genre": "Thriller"
      },
      {
        "genre": "Horror"
      },
      {
        "genre": "Science Fiction"
      },
      {
        "genre": "Thriller"
      },
      {
        "genre": "Road movie"
      },
...
```

Or, if you don't want to have repetitions:

```graphl
{
  var(func: eq(name@en, "Steven Spielberg")) {
    director.film {
      genres as genre {
        name@.
      }
    }
  }
    
  q(func: uid(genres)) {
    name@.
  }
}
```

Which returns:

```json
{
  "data": {
    "q": [
      {
        "name@.": "Thriller"
      },
      {
        "name@.": "Film noir"
      },
      {
        "name@.": "Political thriller"
      },
      {
        "name@.": "Chase Movie"
      },
      {
        "name@.": "Crime Fiction"
      },
      {
        "name@.": "Adventure Comedy"
...
```

**Comment by fridex** [comment]
> Since variables are sets, you can easily use them to remove duplicates.

Nice! I didn't know that. IMHO worth to give an example of this feature in the Dgraph tour or in query docs. If already present, sorry for missing it.

Thanks for the reply!

**Comment by campoy** [comment]
Good idea, I'll close this issue and create #4009!
