### ISSUE TITLE
Add support for json-lines in bulk loader

### ISSUE THREAD

**Issue by dmsolow** [dgraph-io/dgraph#3819]
Json-lines (http://jsonlines.org/) is a commonly used format for storing a large number of JSON objects in a file. It's better than a single JSON array of objects because it makes it easy to read a file object by object without loading the entire thing into memory.

Popular big data processing frameworks like Apache Spark write JSON-lines natively (`df.write.json("out.json")` writes a JSON-lines file for each partition)

Support would probably be trivial to add for Dgraph and it would help people easily integrate Dgraph into existing ETL workflows.

**Comment by martinmr** [comment]
It doesn't seem like it would be too difficult to implement. We are gearing up for the 1.1 release so this issue most likely sit in the back-burner for a little while. If anybody else is interested in this feature, give a thumbs up to the issue so we can gauge interest and prioritize accordingly.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8785). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
