### ISSUE TITLE
Split out "tls_dir" into individual files so that Docker/K8s secrets management can be plugged in  

### ISSUE THREAD

**Issue by sandys** [dgraph-io/dgraph#3820]
dgraph alpha has an option parameter "tls_dir" to take in TLS certificates created in a directory. 

Usually this has CA certificates, node and user keys. 

The industry recommended way to do secret management in Docker is through Docker Secrets : https://docs.docker.com/engine/swarm/secrets/

There are equivalents in Kubernetes as well as external tools like Hashicorp Vault. Most of them work at the file level and not at the directory level.

I request for additional parameters like "tls_ca_cert", "tls_node_key", etc so that these individual files can be passed in using secret management

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8786). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
