### ISSUE TITLE
Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [dgraph-io/dgraph#3826]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by pawanrawal** [comment]
Hey @yevgenypats 

This sounds interesting. It would be nice if the integration can help us catch some bugs before our users do so. Looking forward to your PR.

**Comment by yevgenypats** [comment]
Hi @pawanrawal, cool! will put it on our near roadmap. Also, I noticed that you are part of the cncf, just as a reference you can take a look at https://github.com/coredns/coredns fuzzit integration.

Also, I need to mention that we have a reward program in case you have time/want to implement this yourself I would be happy to reward you as well as get unbiased feedback on how smooth the integration was. Let me know what you prefer.

**Comment by yevgenypats** [comment]
hi @pawanrawal , one question. where is the config for your CI (TeamCity), I would like to add another step there.

**Comment by yevgenypats** [comment]
@pawanrawal ping. can you give me some direction on how would be the best way to add another step to the CI?

**Comment by campoy** [comment]
I think fuzzing would be a great addition to our testing suite!

What do we need to do to make this happen? Do you need any help, @pawanrawal ?

**Comment by pawanrawal** [comment]
Sorry I missed this. I think our CI runs a variant of the test.sh script in the root of the project. We don't have config files for them and these instructions are inside the Teamcity agent. @danielmai or I can help you add the step if you can tell us what to do.

**Comment by campoy** [comment]
Hey @yevgenypats, I guess we're waiting on your input to help us set this up.

**Comment by yevgenypats** [comment]
hi @pawanrawal and @campoy cool. so I think the steps will be as follows:

1) sign up at https://app.fuzzit.dev
2) once you sign up let me know and I'll add you to dgraph account so you can take over
3) Essentially what you want to add is two steps in test.sh one for fuzzing and one for regression
3.1) here is a go example https://github.com/fuzzitdev/example-go you can see fuzzit.sh and .travis.yml that should give you an idea how this should look like.
4) If you need any help with that feel free to ping me here to via slack https://slack.fuzzit.dev

**Comment by yevgenypats** [comment]
friendly ping:) @pawanrawal @campoy

**Comment by pawanrawal** [comment]
Hey @campoy 

I just requested the Dgraph GitHub account to install fuzzit for dgraph. If you can approve it, I can work on the next steps here.

**Comment by danielmai** [comment]
> I just requested the Dgraph GitHub account to install fuzzit for dgraph. If you can approve it, I can work on the next steps here.

Approved.

**Comment by parasssh** [comment]
@yevgenypats 
I am working on integrating fuzzit with dgraph. I adapted the fuzzit.sh file for dgraph. However, I get the following message when I run as follows:

`paras@pshahX1:~/go/src/github.com/dgraph-io/dgraph$ ./fuzzit.sh fuzzing `
...
...
...
2019/10/25 15:19:14 Creating job...
2019/10/25 15:19:16 Uploading fuzzer...
2019/10/25 15:19:19 Starting job
2019/10/25 15:19:19 Please check that the target 'parser_fuzz_tgt' exists and you have sufficiant permissions
2019/10/25 15:19:19 Job created successfully
**_2019/10/25 15:19:19 rpc error: code = PermissionDenied desc = Missing or insufficient permissions._**

I have FUZZIT_API_KEY to an environment variable. Is there anything I am missing?

**Comment by parasssh** [comment]
@yevgenypats 
I am working on integrating fuzzit with dgraph.
Just to clarify, based on the example.go you indicated above, we basically need to do the following in order:
1. Set the env variable to FUZZIT_API_KEY  
2. ./fuzzit.sh local-regression [regression] 
3. ./fuzzit.sh fuzzing

However, when I run this,
- In Step 2, It seems to skip the run as there is no corpus or seed.
- In Step 3, it gives me "2019/10/25 15:47:06 rpc error: code = PermissionDenied desc = Missing or insufficient permissions." 

I have set the FUZZIT_API_KEY to an env variable.

**Comment by parasssh** [comment]
I figured out the issue. 
Basically, the script is missing the step to create a fuzzit target and the target-id needs to be under dgraph-io-gh account. After fixing these two, I was able to create a target and add 2 jobs (fuzzing, regression) under it.

Questions
======
- Can you tell me how to incorporate the corpus that dgraph has under dgraph/gql/fuzz-data/corpus? And how does it populate the corpus with new test-cases?
- The jobs seem to be queued. When/How will the report be generated? Do you have an example. 

I will continue to work on incorporating this into our CI in the meanwhile.

**Comment by yevgenypats** [comment]
Hey @parasssh, thanks for the details questions.

* Per the corpus incorporation there are two options: one you can manually upload a zip as a seed corpus via the ui or via `--additional-corpus`.
* I don't see any queued jobs now so look like the target running successfully.

Regarding regression - this is a legit way to run it though there is one more way that you can consider - you can run with `--local-regression` and this way it will run the regression (you must have access to the docker inside the CI) inline in your CI and if the regression fails it will be able to block the CI in real-time.

Regarding the first issue you had - yes you have to create the targets first either via the ui or via `./fuzzit create target --skip-if-exists [TARGET_NAME]`

Also I've added 3 free CPUs to your account so you should be able to run 3 fuzz targets in parallel. 

If you will need more we have a plan for OSS projects where you pay only for [raw](https://cloud.google.com/products/calculator/#id=0f8af6eb-cf1d-45af-9b93-c4de1ceb9182) compute so it's about 8$/additional cpu/month (you can drop me a line at yp[at]fuzzit.dev)

Let me know if you hit any other issues.

**Comment by parasssh** [comment]
I am a little confused on the use of corpus. 
So, there is options under the create target:
--public-corpus
--seed
and then there is option under the create job:
--additional-corpus

Which one should I be using? Also, when is the corpus required, during fuzzing or regression? Lastly, how do I get the new corpus that fuzzing finds so that I can use that for subsequent runs.

I guess a complete workflow with initial corpus and subsequent corpus will be helpful.

**Comment by parasssh** [comment]
Ok, so this is what I have done.
- Created a target with seed corpus
- Created a job with regression. It executed only inputs from the seed corpus. 
- Created a long running job with fuzzing. This, I believe, generates the additional corpus. When does this job terminate? Or does it have to be manually terminated?
- Created a job with regression. It now executed inputs from the seed corpus as well as the corpus from above step.
- When I download the corpus from the UI, it shows me the new corpus (without the seed)

Question. 
1. What is the best practice for fuzzing job? It is long running job. Clearly, it cannot be run inline with CI.
2. What is the best practice with management of the corpus?

**Comment by yevgenypats** [comment]
Sounds like this is almost ready!

- Yes it is expected for the old job to stop and new one to start as you want to fuzz only the latest code. This always start from the same "point" as the corpus is saved between runs.
- Yes, this is expected. You can download the seed corpus separately via target settings.

- the best practice is to run the fuzzing job infinitely either until a crash is introduce or until a new version is introduced (and then the old job is stopped automatically). So you don't have to wary about stopping the fuzzing jobs. The fuzzing is never running inline in the CI  as the `fuzzit create job --type fuzzing` returns immediately after the job starts.
- the corpus is growing and saved automatically in fuzzit so nothing special to do here.
- I would highly recommend local-regression as  regression was introduced before local-regression and I would like to deprecate this in the future. with local regression you get the status automatically and inline in the CI.  

If you have a public link to the `fuzzit.sh` script maybe I can help review if you want to.

**Comment by parasssh** [comment]
Merged https://github.com/dgraph-io/dgraph/pull/4233

**Comment by parasssh** [comment]
@yevgenypats  Congrats on the acquisition. Co-Incidentally, I wrote a blog about our integration with fuzzit. See, https://dgraph.io/blog/post/continuous-fuzzing-with-go/

**Comment by yevgenypats** [comment]
@parasssh thank you! very good and detailed write-up!
