### ISSUE TITLE
Make --lru_mb optional

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#3850]
Currently, alphas won't work unless you provide a value for `--lru_mb` of at least 1024MB

We should instead set the default to `1024MB`.

**Comment by MichelDiz** [comment]
Just an opinion, I think we should try catch the RAM available and set 50% of it as default.

e.g (from stackoverflow)
```go
package main

// #include <unistd.h>
import "C"

func main() {
    println(C.sysconf(C._SC_PHYS_PAGES)*C.sysconf(C._SC_PAGE_SIZE), " bytes")
}
```

Or https://godoc.org/github.com/capnm/sysinfo

If we set 1024MB as default users can think this is some kind of minimal recommendation.

**Comment by mangalaman93** [comment]
I do not think `lru_mb` is currently used at all. It was previously used when we had an LRU cache, it was removed from Dgraph at some point.

**Comment by campoy** [comment]
I don't care that much about the value, but making it compulsory when we're not even using it seems unnecessary.

Running the version on master as today I get:

```
➜  dgraph git:(master) ~/bin/dgraph alpha
[Decoder]: Using assembly version of decoder
2019/09/03 09:30:05 LRU memory (--lru_mb) must be specified. (At least 1024 MB)
```

**Comment by campoy** [comment]
After a chat with @manishrjain we decided that we should try to guess the total size of RAM and: 

- if we find the size, use 50% of it and log a warning with a link to a page explaining how to set the `lru_mb` correctly
- if we don't find the size (as it probably happens with Windows?) fail and log an error with the same link as above

This will be part of the next release, not necessary for 1.1.0
