### ISSUE TITLE
Show query progress, specifically for long running queries

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#3857]
### What you wanted to do

A massive upsert (milions of nodes). 

### Why that wasn't great, with examples

All massive upserts take some time to execute. The massive upsert works fine, but there's no visual reference during the process if it is going well or not. Sometimes Ratel could fail visually or the Browser (for some reason) and We're not sure if the Big Upsert was executed or still executing.

We could have two types of reference for this. Could be API responses (if possible) sending percentage values and a log in the Alpha's log terminal. The log would start to appear only if the transaction takes more time than usual.

### Observation

This probably would be done after we have a Query Planner.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8446). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by MichelDiz** [comment]
We could use this Task queue https://github.com/dgraph-io/dgraph/blob/main/worker/queue.go
