### ISSUE TITLE
Improve Docker public repository

### ISSUE THREAD

**Issue by djhenderson** [dgraph-io/dgraph#386]
The Docker [dgraph user](https://hub.docker.com/r/dgraph/) and public repositories [dgraph/dgraph](https://hub.docker.com/r/dgraph/dgraph/), [dgraph/neo4j](https://hub.docker.com/r/dgraph/neo4j/), and [dgraph/base](https://hub.docker.com/r/dgraph/base/) need to be customized by filling in more of the available fields. These include the short and full descriptions, adding the github dgraph user avatar as the owner's avatar, and filling any other available fields, as appropriate.

The full description (or other) field should include links to [dgraph.io](https://dgraph.io) and/or [github.com/dgraph-io](https://github.com/dgraph-io).

These fields are used to create the output of `docker search dgraph`; the results of a [Docker Dashboard search](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=dgraph&starCount=0); and also the results of a [Docker Store search](https://store.docker.com/search?q=dgraph&source=community).

**Comment by pawanrawal** [comment]
@manishrjain Do we need dgraph/neo4j and dgraph/base images or should we delete them?

**Comment by pawanrawal** [comment]
I have deleted the neo4j and base repos. I also uploaded the logo.
