### ISSUE TITLE
Spring Data integration

### ISSUE THREAD

**Issue by arabbani** [dgraph-io/dgraph#3862]
### What you wanted to do

We need Spring Data integration for Dgraph. Is there a possibility for official support in this case?

**Comment by campoy** [comment]
Hey @arabbani,

Could you tell us more about what kind of integration you'd like to see?
I'm not an expert with Spring Data, so any pointer to the kind of integration (maybe some showing us how other projects do it) would be very helpful.

Thanks!

**Comment by samyem** [comment]
The Spring Data for Neo4J will probably be a good example of integration with Spring Data: https://spring.io/projects/spring-data-neo4j 

Query examples are provided in the linked docs: https://docs.spring.io/spring-data/neo4j/docs/5.2.0.RELEASE/reference/html/#repositories.query-methods.query-lookup-strategies

**Comment by arabbani** [comment]
An integration with spring framework will help more people to use dgraph

**Comment by sparshneel** [comment]
hi I am interested in this integration too any updates??

**Comment by kostjaigin** [comment]
hi i am interested too, so count me as +1 :)

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8447). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
