### ISSUE TITLE
It is possibllity for official support for Spark or Flink

### ISSUE THREAD

**Issue by Willem520** [dgraph-io/dgraph#3882]
What you wanted to do
We need Spark or Flink integration for Dgraph. Is there a possibility for official support in this case?
What you actually did

Why that wasn't great, with examples

Any external references to support your case

**Comment by mangalaman93** [comment]
What are use cases that you are trying to solve using Spark on Dgraph?

**Comment by campoy** [comment]
Hey @Willem520 , could you tell us more about what you'd expect from this integration?

**Comment by campoy** [comment]
Actually, this seems like a duplicate of #2123.
Closing this one for now.
