### ISSUE TITLE
Error while parsing certain time formats 

### ISSUE THREAD

**Issue by eawer** [dgraph-io/dgraph#3883]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
```
Dgraph version   : master
Dgraph SHA-256   : 4f93faa8e7954e77ab3f03899e492fa8aff80a85b4701ff430d0befd0cc2ebc5
Commit SHA-1     : b99709c6
Commit timestamp : 2019-08-28 18:47:41 +0530
Branch           : master
Go version       : go1.12.5
```

- Have you tried reproducing the issue with the latest release?
Yes

- What is the hardware spec (RAM, OS)?
Ubuntu 19.04, 16Gb RAM

- Steps to reproduce the issue (command/config used to run Dgraph).
`docker exec -it dgraph dgraph bulk -f freebase.rdf.gz -s freebase.schema -v 3 --zero localhost:5080`

- Expected behavior and actual result.
Dgraph fails to parse such time-strings as "T22", "T00:00"
```
parsing time "T00:00" as "2006": cannot parse "T00:00" as "2006"
while parsing line "<http://rdf.freebase.com/ns/m.0108b_kd>\t<http://rdf.freebase.com/ns/base.schemastaging.phone_open_times.sunday_closing_time>\t\"T00:00\"^^<http://www.w3.org/2001/XMLSchema#dateTime>\t.\n"
github.com/dgraph-io/dgraph/chunker.(*rdfChunker).Parse
	/tmp/go/src/github.com/dgraph-io/dgraph/chunker/chunk.go:149
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*mapper).run.func1
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/mapper.go:142
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337

github.com/dgraph-io/dgraph/x.Check
	/tmp/go/src/github.com/dgraph-io/dgraph/x/error.go:42
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*mapper).run.func1
	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/mapper.go:145
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
```

**Comment by MichelDiz** [comment]
Can you share the part of the RDF with the time string?

BTW, it is important to note that not every dataset in RDF format is directly compatible with Dgraph. Most of them you need to treat first then make the insertion. Dgraph uses a very simple Nquads pattern, There are usually complex datasets with features that are not supported in Dgraph RDF parser. So you may have to pay attention to this.

Cheers.

**Comment by eawer** [comment]
it can be seen in the stack trace:
```
<http://rdf.freebase.com/ns/m.0108b_kd>\t<http://rdf.freebase.com/ns/base.schemastaging.phone_open_times.sunday_closing_time>\t\"T00:00\"^^<http://www.w3.org/2001/XMLSchema#dateTime>\t.\n
```

**Comment by gitlw** [comment]
@eawer The supported datetime formats are the ones that are compatible with RFC3339, e.g. 2006-01-02T15:04:05.999999999+10:00 or 2006-01-02T15:04:05.999999999)

This doc is available in https://docs.dgraph.io/query-language/#schema-types at the dateTime DgraphType line and also the Note section below.

**Comment by eawer** [comment]
@gitlw and what about time itself (without date)? RFC3339 `5.6` mentions `partial-time = time-hour ":" time-minute ":" time-second [time-secfrac]`, is it supported as well?

**Comment by gitlw** [comment]
@eawer Unfortunately that is not supported for now. I've created a feature request in #3890 .

**Comment by eawer** [comment]
@gitlw just to be clear, what I was asking about is not time interval, but the time itself - `HH:MM:SS` eg. `22:30:00`, `08:45:30`, `23:59:59` etc., and this is what  I think `5.6` of RFC3339 is about

**Comment by eawer** [comment]
actually, looks like dgraph can't handle this pattern as well. I've tried to load a file with a single line
`<http://rdf.freebase.com/ns/m.0108b_kd> <http://rdf.freebase.com/ns/base.schemastaging.phone_open_times.sunday_closing_time>   "00:00:0\"^^<http://www.w3.org/2001/XMLSchema#dateTime> .` and it failed with

```
parsing time "00:00:00" as "2006": cannot parse "0:00" as "2006"
while parsing line "<http://rdf.freebase.com/ns/m.0108b_kd>\t<http://rdf.freebase.com/ns/base.schemastaging.phone_open_times.sunday_closing_time>\t\"00:00:00\"^^<http://www.w3.org/2001/XMLSchema#dateTime>\t.\n"
github.com/dgraph-io/dgraph/chunker.(*rdfChunker).Parse
        /tmp/go/src/github.com/dgraph-io/dgraph/chunker/chunk.go:149
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*mapper).run.func1
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/mapper.go:142
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337

github.com/dgraph-io/dgraph/x.Check
        /tmp/go/src/github.com/dgraph-io/dgraph/x/error.go:42
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*mapper).run.func1
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/mapper.go:145
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
```

So right now time parsing is not supported, correct?

**Comment by gitlw** [comment]
That's correct. Time parsing is not supported.

**Comment by danielmai** [comment]
@eawer According to RFC 3339 5.6 describes the syntax for RFC 3339-compatible strings that contain date **and** time. AFAIK, it does not allow for dateless strings.


From [RFC 3339 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), the accepted format is specified by `date-time`:

>    ```
>    date-fullyear   = 4DIGIT
>    date-month      = 2DIGIT  ; 01-12
>    date-mday       = 2DIGIT  ; 01-28, 01-29, 01-30, 01-31 based on
>                              ; month/year
>    time-hour       = 2DIGIT  ; 00-23
>    time-minute     = 2DIGIT  ; 00-59
>    time-second     = 2DIGIT  ; 00-58, 00-59, 00-60 based on leap second
>                              ; rules
>    time-secfrac    = "." 1*DIGIT
>    time-numoffset  = ("+" / "-") time-hour ":" time-minute
>    time-offset     = "Z" / time-numoffset
>
>    partial-time    = time-hour ":" time-minute ":" time-second
>                      [time-secfrac]
>    full-date       = date-fullyear "-" date-month "-" date-mday
>    full-time       = partial-time time-offset
>
>    date-time       = full-date "T" full-time
>    ```

The Dgraph docs (https://docs.dgraph.io/query-language/#schema-types) has a note that `dateTime` accepts RFC 3339-compatible strings, not the same format as the RDF spec. You can either convert the times into datetimes, or use the `string` schema type.

**Comment by eawer** [comment]
probably I got it wrong, thanks for the explanation
