### ISSUE TITLE
Support a new type that represents a time interval

### ISSUE THREAD

**Issue by gitlw** [dgraph-io/dgraph#3890]
### What you wanted to do
As discussed in #3883 , the user is requesting to have a data type that represents a time interval. 
Ideally, we should support 
- operations between a dateTime and a time interval. That is adding or subtracting the interval from a dateTime should generates another dateTime.
- if a time interval predicate is indexed, we should support operations such as eq, gt, lt etc just like those on the int type

**Comment by MichaelJCompton** [comment]
This looks like a reasonable feature request.

I'm tagging it as accepted, which means it will get into our backlog of features to consider.  

If we decide to implement it, we'll post an update here.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8787). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
