### ISSUE TITLE
Support filter on expand

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#3904]
It would be very useful to filter what fields are included in an `expand` operation.

For instance, we could expand only the predicates pointing to values of type `Person` from a `Movie` as such:

```graphql
{
    q(func: type(Movie)) {
        expand(_all_) @filter(type(Person)) {
            first_name
        }
    }
}
```

This would expand the predicates of type `uid` or `[uid]` and show only the nodes associated to the type Person.

**Comment by gitlw** [comment]
@campoy It seems the syntax `expand(type(Person))` is more concise and intuitive. What do you think?

**Comment by campoy** [comment]
`expand(type(Person))` and `expand(Person) @filter(type(Person))` are different things, and they're both valid.

Given a type Person as follows:

```go
type Person {
  name: string
  age: int
  best_friend: uid   // points to a Person
  lives_with: [uid]  // holds an array of objects: some of type Person, some of type Pet
  pets: [uid]        // holds an array of objects of type Pet
}
```

### expand(Person)

`expand(Person)` is replaced by the predicates defined in the `Person` type.

```graphql
{
  q(func: eq(name, "Francesc")) {
    expand(Person)
  }
}
```

Is the same as writing

```graphql
{
  q(func: eq(name, "Francesc")) {
    name
    age
    best_friend
    lives_with
    pets
  }
}
```

You can read more on `expand(Person)` on issue #3903.

### expand(X) @filter(type(Person))

This will expand whatever is requested in the `expand` function, either `_all_` or `Person`. But then only the values of type Person will be kept.

So given a value of `Person`

```json
{
  "uid": "0x1234",
  "dgraph.type": "Person",
  "name": "Frodo",
  "age": 25,
  "best_friend": {
     "uid": "0x2345",
     "dgraph.type": "Person",
     "name": "Sam",
     "age": 24
  },
  "lives_with": [
      {
        "uid": "0x2345",
        "dgraph.type": "Person",
        "name": "Sam",
        "age": 24       
      },
      {
        "uid": "0x3456",
        "dgraph.type": "Pet",
        "name": "Milou"
      }
  ],
  "pets": [
      {
        "uid": "0x3456",
        "dgraph.type": "Pet",
        "name": "Milou"
      }
  ]
}
```

The following query:

```graphql
{
  q(func: eq(name, "Frodo")) {
    expand(_all_) @filter(type(Person)) {
       expand(Person)
    }
  }
}
```

would:

- expand all the fields in the types associated to "Frodo", in this case just those of "Person"
- filter the predicates to only those of type "Person", therefore dropping name, age, pets, and some of the values in lives_with
- expand all of the predicates in Person for each one of the nodes in pointed by the predicates expanded before

The result would be the following:

```json
{
  "best_friend": {
     "name": "Sam",
     "age": 24
  },
  "lives_with": [
      {
        "name": "Sam",
        "age": 24       
      }
  ]
}
```

I wonder if this is clear enough. I think I need to spend some time writing more specs for these changes.
For now let's keep them blocked.

**Comment by campoy** [comment]
Hey @martinmr , could you have a look at this issue?
I think you might be the best person to handle this right now.

**Comment by martinmr** [comment]
I have a PR for this already but there is a weird bug that I haven't had the chance to debug yet.

**Comment by Necmttn** [comment]
Hey, @martinmr is there any status update about this issue?

**Comment by campoy** [comment]
This issue is related to #4399, as `expand(_all_)` might expand value predicates and filters should apply on them too (or not, to be decided in that issue).
