### ISSUE TITLE
Using "expand" with "@cascade" returns no results 

### ISSUE THREAD

**Issue by erhlee-bird** [dgraph-io/dgraph#3905]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

https://play.dgraph.io

- Have you tried reproducing the issue with latest release?

No

- What is the hardware spec (RAM, OS)?

N/A

- Steps to reproduce the issue (command/config used to run Dgraph).

Run this query in Ratel

```
{
  genre(func: has(~genre)) @cascade {
    uid    
    expand(_forward_)
    
    ~genre @filter(uid(0xf))
  }
    
  #other(func: has(genre), first: 10) {
  #  uid
  #}
}
```

- Expected behaviour and actual result.

I expect my query to retrieve all forward predicates for only those nodes that have a specific reverse genre edge. If I comment out the `expand(_forward_)` line, uids are returned.

I haven't dug too deep into this, but it seems that there is a weird interaction with cascade and expand.

**Comment by gitlw** [comment]
@erhlee-bird 
The query
`
{
  genre(func:has(~genre)) @cascade {
    uid
    ~genre @filter(uid(0xf))
  }
}
`
returns the following uids
`
"genre": [
      {
        "uid": "0x13af13"
      },
      {
        "uid": "0x2a6b6b"
      },
      {
        "uid": "0x3fc823"
      },
      {
        "uid": "0x5e4ca3"
      },
      {
        "uid": "0x7297f5"
      }
    ]
`

And these nodes do not have any types set, as this query shows
`
{
  genre(func:has(~genre)) @cascade {
    uid
    dgraph.type
    ~genre @filter(uid(0xf)) {
      name@en
    }
  }
}
`
Without types, the expand(_forward_) would not capture any predicate, and hence adding a @cascade would yield no result.

**Comment by erhlee-bird** [comment]
https://docs.dgraph.io/master/query-language/#expand-predicates

> Starting with version 1.1, the keyword _predicate_ has been deprecated. Instead, to properly use the expand() function, the use of the type system is required. 

Noted, thank you.
