### ISSUE TITLE
Smarter reverse edge semantic in type system

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/dgraph#3909]
Pasted from https://reviewable.io/reviews/dgraph-io/dgraph/3907#-LntC8SaBFikss0vhpww:

This looks like a place in the type system that we can improve on. Namely, that reverse edges between two distinct types are set for the object type. i.e., for the following schema, the edge ~predicate: [A] should be implied in type B since type A has an edge to B:

```
predicate: [uid] @reverse .
name: string .

type A {
  name: string
  predicate: [B]
}

type B {
  name: string
}
```

**Comment by campoy** [comment]
How do we know whether the reverse predicate is of type `[A]` and not `A`?

**Comment by danielmai** [comment]
For reverse edges of either `uid` or `[uid]` edges, the reverse edge would always be a list. The Dgraph schema does not guarantee that there is only one incoming edge to a node.

**Comment by MichaelJCompton** [comment]
I'm a no for this.  There may be other edges into things of type B that we don't imply.  For example, in `expand` that was the big change in expand for v1.1 ... so why is this special?  

My expectation is that if the schema says

```
type B {
  name: string
}
```

then that's the edges I think are in B.  I think it would be surprising if an annotation I'd made elsewhere in the schema (or even at a different time in another schema alter) changed my type definitions.

If I'd wanted to also go backwards along `predicate` from B, then I should be able to write

```
type B {
  name: string
  ~predicate: [uid]
}
```

...I also don't think we 'know' it's of type `[A]` - there could be multiple types that include the `predicate` edge.

**Comment by campoy** [comment]
Agreed with @MichaelJCompton, and he's the expert in types at this point haha

In addition to not being clear that this applies to all cases, in the cases where the reversed edge should be part of the type you can simply add it.

Closing the issue for now. Feel free to reopen if relevant.
