### ISSUE TITLE
安装成功以后按照操作说明Java中存储/查询数据异常

### ISSUE THREAD

**Issue by 123key** [dgraph-io/dgraph#3931]
[error.txt](https://github.com/dgraph-io/dgraph/files/3582125/error.txt)

我使用的版本是V1.1.0，jdk版本1.8，实在centos7中安装成功了，页面上操作（建索引异常）成功，java上DgraphClient连接成功，在commit提交任务是出现这个异常

**Comment by gitlw** [comment]
@123key 感谢您使用Dgraph和提交这个问题.我刚刚把这个示例里的dgraph4j版本升级到了2.0.1,请您用git更新到最新的dgraph4j代码再尝试一次。如果还有问题的话请联系我们。

**Comment by 123key** [comment]
> @ 123key感谢您使用DGraph组件和提交这个问题。我刚刚把这个示例里的dgraph4j版本升级到了2.0.1，请您用的git更新到最新的dgraph4j代码再尝试一次。如果还有问题的话请联系我们。
您好，我想在请教一下我插入数据到dgraph中，如果带上索引以前的数据被删掉了，只有最新的，如果不加索引就查不到数据，我是java的，能否指点一下

**Comment by campoy** [comment]
Hey @gitlw,

Could you add some labels and an explanation of what's going on in here?

谢谢！

**Comment by mangalaman93** [comment]
Hi @123key, please let us know if you have any more questions (in English). Closing this issue for now, feel free to reopen it.
