### ISSUE TITLE
schema documentation 

### ISSUE THREAD

**Issue by objectiveous** [dgraph-io/dgraph#3935]
## Experience Report

When building tooling (think query editors, browsers, and other tools ), it would be nice have predicate descriptions available programmatically. I believe this is something graphql already supports, so I suppose I'm asking for more alignment w/ the graphql standard.

**Comment by MichaelJCompton** [comment]
Hi, thanks for the question.

We are currently building out GraphQL support.  That will come with all the normal GraphQL features built in - including schema introspection, which is what GraphQL tools use to provide those features.

So it'll just work with anything GraphQL.

**Comment by MichaelJCompton** [comment]
Closing.  Please re-open if you have further questions.
