### ISSUE TITLE
@type directive not working well with other filters

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/dgraph#3961]
### What version of Dgraph are you using?
master

### Have you tried reproducing the issue with the latest release?
yes

### Steps to reproduce the issue (command/config used to run Dgraph).
use @type directive and @filter directive in the same block. The parser will complain saying that multiple filters should be combined. @type is just an alias for filter.

### Expected behaviour and actual result.
Ideally, the two directives work well together and are combined in an AND filter.

**Comment by campoy** [comment]
After reading this I'm almost convinced we should remove the `@type` directive completely.

**Comment by martinmr** [comment]
Closing this issue since the type directive won't be doing any filtering anymore so this is no longer relevant.
