### ISSUE TITLE
Has function is painfully slow

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#3964]
# What version of Dgraph are you using?

Using play.dgraph.io

### Have you tried reproducing the issue with the latest release?

No

### What is the hardware spec (RAM, OS)?

Playground

### Steps to reproduce the issue (command/config used to run Dgraph).

Send any query, such as:

```graphql
{
  q(func: has(name), first:1) {
    name
  }
}
```

### Expected behaviour and actual result.

I expect to get an answer immediately, instead it's taking over 15 seconds!

```graphql
{
  "data": {
    "q": [
      {
        "name": "Civic Center Hotel"
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 6075,
      "processing_ns": 15714531902,
      "encoding_ns": 16423
    },
    "txn": {
      "start_ts": 485029
    }
  }
}
```

**Comment by manishrjain** [comment]
As function should understand first and offset directives. Right now it gets all the IDs which have the name predicate before it executes the first N.
