### ISSUE TITLE
Parsing error is incorrect

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#3965]
# What version of Dgraph are you using?

Dgraph 1.1.0

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, OS)?

Running on docker for Mac

### Steps to reproduce the issue (command/config used to run Dgraph).

Send this mutation:

```json
{
  "set": [
    {
      "uid": "0x1",
      "friends_with": [
        {
          "uid": "0x3",
          "friends_with|good": false,
        }
      ]
    }
  ]
}
```

There's a mistake since there's an extra `,` after `false`.

### Expected behaviour and actual result.

I expect to see a parsing error on line 8, where the extra comma is found. Maybe on line 9?

Instead, I get this error:

```
Error Name: t

Message: while lexing {
  "set": [
    {
      "uid": "0x1",
      "friends_with": [
        {
          "uid": "0x3",
          "friends_with|good": false,
        }
      ]
    }
  ]
} at line 2 column 2: Unrecognized character inside mutation: U+0022 '"'

URL: http://localhost:8080/mutate?commitNow=true
```

**Comment by campoy** [comment]
Is this then a Ratel bug since it tries to figure out the mutation format?

When sent via `curl` with the right `Content-Type` header, I get this error:

```json
{"errors":[{"message":"invalid character '}' looking for beginning of object key string","extensions":{"code":"ErrorInvalidRequest"}}]}
```

I guess it's better, but still not really helpful.

**Comment by martinmr** [comment]
It would depend on what we are using to parse the JSON. I don't think we are using the same parser as the RDF so we cannot add line numbers. But I'll look into it to see if we can improve it somehow.

**Comment by campoy** [comment]
Any update on this issue, @martinmr ?

**Comment by martinmr** [comment]
sorry, I haven't had a chance to look at it, yet. I'll get to it once I am done with the type system PRs I have open.
