### ISSUE TITLE
dgraph插入数据覆盖

### ISSUE THREAD

**Issue by 123key** [dgraph-io/dgraph#3977]
您好，我问一下这个数据库支持相同数据覆盖吗？或者有没有办法起到相同数据覆盖的方法？

**Comment by campoy** [comment]
Translation from Google:

> Hello, I am asking if this database supports the same data coverage? Or is there a way to cover the same data?

I'm not very sure what the question is about.

Maybe @gitlw can help?

**Comment by 123key** [comment]
例如：
person [name='Alice',age=15]
person [name='Alice',age=15]
这样同样的两条数据会在数据库中重复插入，怎么样在插入数据的时候把重复的替换掉

**Comment by 123key** [comment]
> Translation from Google:
> 
> > Hello, I am asking if this database supports the same data coverage? Or is there a way to cover the same data?
> 
> I'm not very sure what the question is about.
> 
> Maybe @gitlw can help?

例如：
person [name='Alice',age=15]
person [name='Alice',age=15]
这样同样的两条数据会在数据库中重复插入，怎么样在插入数据的时候把重复的替换掉

**Comment by danielmai** [comment]
@123key you can write a mutation to the same UID to have the same content.

```
{"uid": "0x1", "name": "Alice", "age": 15}
```
and then the same mutation can be run:
```
{"uid": "0x1", "name": "Alice", "age": 15}
```

If you start a mutation with a blank node, then you need to query for the uid first to insert data to the same node.

```
# Mutation #1 with blank node
{"uid": "_:blank", "name": "Alice", "age": 15}

# query for uid (for example: 0x1)
# ...

# Mutation #2 with uid
{"uid": "0x1", "name": "Alice", "age": 15}
```

Does that answer your question?

**Comment by 123key** [comment]
> @123key you can write a mutation to the same UID to have the same content.
> 
> ```
> {"uid": "0x1", "name": "Alice", "age": 15}
> ```
> 
> and then the same mutation can be run:
> 
> ```
> {"uid": "0x1", "name": "Alice", "age": 15}
> ```
> 
> If you start a mutation with a blank node, then you need to query for the uid first to insert data to the same node.
> 
> ```
> # Mutation #1 with blank node
> {"uid": "_:blank", "name": "Alice", "age": 15}
> 
> # query for uid (for example: 0x1)
> # ...
> 
> # Mutation #2 with uid
> {"uid": "0x1", "name": "Alice", "age": 15}
> ```
> 
> Does that answer your question?



Yes,Thank You!

**Comment by 123key** [comment]
> @123key you can write a mutation to the same UID to have the same content.
> 
> ```
> {"uid": "0x1", "name": "Alice", "age": 15}
> ```
> 
> and then the same mutation can be run:
> 
> ```
> {"uid": "0x1", "name": "Alice", "age": 15}
> ```
> 
> If you start a mutation with a blank node, then you need to query for the uid first to insert data to the same node.
> 
> ```
> # Mutation #1 with blank node
> {"uid": "_:blank", "name": "Alice", "age": 15}
> 
> # query for uid (for example: 0x1)
> # ...
> 
> # Mutation #2 with uid
> {"uid": "0x1", "name": "Alice", "age": 15}
> ```
> 
> Does that answer your question?


Please comment：
Why it throws an exception that "the uid cannot exceed 40000" when I set the uid manually?

**Comment by 123key** [comment]
> @123key you can write a mutation to the same UID to have the same content.
> 
> ```
> {"uid": "0x1", "name": "Alice", "age": 15}
> ```
> 
> and then the same mutation can be run:
> 
> ```
> {"uid": "0x1", "name": "Alice", "age": 15}
> ```
> 
> If you start a mutation with a blank node, then you need to query for the uid first to insert data to the same node.
> 
> ```
> # Mutation #1 with blank node
> {"uid": "_:blank", "name": "Alice", "age": 15}
> 
> # query for uid (for example: 0x1)
> # ...
> 
> # Mutation #2 with uid
> {"uid": "0x1", "name": "Alice", "age": 15}
> ```
> 
> Does that answer your question?


Please comment：
Why it throws an exception that "the uid cannot exceed 40000" when I set the uid manually?

**Comment by MichelDiz** [comment]
Also you can always use Upserts https://docs.dgraph.io/mutations/#upsert-block

**Comment by tiankonghewo** [comment]
两个node之间的边的属性是会会被覆盖的,每次写入然后再查询,都是新值,节点的属性没试过,但是应该也是可以覆盖的.自己可以用个docker,试试

**Comment by MichelDiz** [comment]
Closing, the question was answered. If there are more questions. Please do at http://discuss.dgraph.io
