### ISSUE TITLE
Broken example in docs

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#3986]
### What version of Dgraph are you using?

playground (1.1.0)

### Have you tried reproducing the issue with the latest release?

yes

### What is the hardware spec (RAM, OS)?

playground

### Steps to reproduce the issue (command/config used to run Dgraph).

Go to https://docs.dgraph.io/query-language/#after and follow the two examples.

The second query says:

> The fifth movie is the Australian movie classic Strictly Ballroom. It has UID 0x8116e4.

This is actually not accurate, the UID is now 0x99e44, so the query below doesn't return anything.

```graphql
{
  me(func: allofterms(name@en, "Baz Luhrmann")) {
    name@en
    director.film (first:5, after: 0x8116e4) {
      uid
      name@en
    }
  }
}
```

```json
{
  "data": {
    "me": [
      {
        "name@en": "Baz Luhrmann"
      }
    ]
  }
}
```

### Expected behaviour and actual result.

I would have expected to have results that match the description.

**Comment by danielmai** [comment]
Every time Play is updated the UIDs are changed when loading the data with all the blank nodes There are a handful of query examples that use UIDs that need to be updated.

In the future, we can load data from an export of the current Play database to preserve the UIDs when doing version upgrades for Play.
