### ISSUE TITLE
Broken examples should be notified

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#3987]
As seen in #3986, examples in our documentation are not verified.

We should fix this and make sure that if some example fails, an issue is automatically failed, or we get somehow notified.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8791). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
