### ISSUE TITLE
We need continuous benchmark

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#3988]
We should come up with a series of queries on a dataset that we can run frequently (for each PR, or at least nightly) and store the results so we can visualize the evolution of our performance over time.

This could be a great opportunity for dogfooding Dgraph, by storing all the results in Dgraph and exposing them with the GraphQL layer (idea proposed by @MichaelJCompton).

Each issue that appears in the `area/performance` label should have a benchmark to ensure we do not introduce regressions.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8792). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
