### ISSUE TITLE
Type system adds inherited functionality

### ISSUE THREAD

**Issue by zhuyaoyhj** [dgraph-io/dgraph#4004]
## Experience Report

Note: Feature requests are judged based on user experience and modeled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### What you wanted to do
Type system adds inherited functionality
such as:
type a{}
type b{
    type a
}

### What you actually did
I must determine the types of each node and add it to node.

### Why that wasn't great, with examples
Once a node forgets to add a type, the query will have problems.
and The schema in schema.org has an inherited relationship。

**Comment by campoy** [comment]
I'm not sure what you're really requesting on this issue.

We are not considering supporting type inheritance, you should be using attaching multiple types for a given node instead.

Could you explain a bit more in detail what your needs are?

**Comment by zhuyaoyhj** [comment]
I designed the schema to follow schema.org. The schema in schema.org has a nested relationship.
Now what I am doing is:

    schema:
    type PersonfeatureA{}
    type PersonfeatureB{}
    type Person{}

    set:
    <uid> <dgraph.type> "PersonfeatureA" .
    <uid> <dgraph.type> "PersonfeatureB" .
    <uid> <dgraph.type> "Preson" .

I want to:

    schema:
    type PersonfeatureA{}
    type PersonfeatureB{}
    type Person{
        PersonfeatureA
        PersonfeatureB
    }

    set:
    <uid> <dgraph.type> "Preson" .

So when adding a type PersonfreatureC, We can directly modify the type Person without adding PersonfreatureC one by one node.

**Comment by martinmr** [comment]
I would create a single type Person with all the predicates of feature set A and B. If you want to add another fields, you can modify the definition of the type.

We are working on something that would allow you to do `expand(PersonfeatureC)` to use only the predicates of a given types for expand queries.

**Comment by campoy** [comment]
Hey, @zhuyaoyhj. Thanks for the clarification.

How is this different from simply tagging the type with both PersonFeatureA and PersonFeatureB types?

What are the advantages of your approach over using multiple types?

I'm happy to consider the feature request, but I need to better understand what the goals are.

**Comment by MichelDiz** [comment]
Closing due a long time no interaction. Feel free to reopen (or ask to if you can't reopen)
