### ISSUE TITLE
Simplify type definitions.

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/dgraph#4014]
We have decided (see https://discuss.dgraph.io/t/should-we-remove-the-type-directive/5067/11) not to do any type enforcement for now within Dgraph and let the GraphQL layer do the enforcement after receiving the query results.

Therefore, we can simplify the type definitions.

Instead of doing
```
type Animal {
  name: string
  species: string
}
```
we can just define types as
```
type Animal {
  name
  species
}
```

The type system is not really using anything after the colon, the type system functionality would effectively not change.

Since we are supporting binary backups, we have to be careful not to change the existing protobuf. This would also allow us to re-add the types and required fields once we have a clearer idea on what the type system within dgraph should enforce.

**Comment by campoy** [comment]
That discuss issue doesn't include any decision on removing the types from the fields in our type declarations.

Let's discuss this again and clarify where we're going with types.

**Comment by martinmr** [comment]
Closing issue as we had the discussion and the change to simplify type definitions is already merged.
