### ISSUE TITLE
Live Loader: Issue with dgraph's default addr

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#4019]
### What version of Dgraph are you using?
1.1.0 (ibrahim:badger-update - but it's not related to that branch)

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, OS)?
Tested on Windows and Darwin

### Steps to reproduce the issue (command/config used to run Dgraph).
Start live load with defaults settings. Or set the addr (flag -a)

```bash
Usage:
  dgraph live [flags]

Flags:
  -a, --alpha string   Comma-separated list of Dgraph alpha gRPC server 
addresses (default "127.0.0.1:9080")
```

This issue also happened in Dgo. As Live Loader uses Dgo, I think Dgo should be checked too.

The error logs
```
Running transaction with dgraph endpoint: 127.0.0.1:9080
While trying to setup connection: context deadline exceeded. Retrying...
While trying to setup connection: context deadline exceeded. Retrying...
While trying to setup connection: context deadline exceeded. Retrying...
While trying to setup connection: context deadline exceeded. Retrying...
While trying to setup connection: context deadline exceeded. Retrying...
While trying to setup connection: context deadline exceeded. Retrying...
While trying to setup connection: context deadline exceeded. Retrying...
While trying to setup connection: context deadline exceeded. Retrying...
While trying to setup connection: context deadline exceeded. Retrying...
```

**Comment by ashish-goswami** [comment]
Caused by https://github.com/dgraph-io/dgraph/issues/4020.
Closing this.

**Comment by MichelDiz** [comment]
This still happening on master - I've build it again in Darwin and tested.
```
➜  dgraph git:(master) git rev-parse HEAD
a5dbfc80e029c096c29024d2c0b2497fff265ffd
```
git commit => https://github.com/dgraph-io/dgraph/commit/a5dbfc80e029c096c29024d2c0b2497fff265ffd
```
➜  master(18-09-19) dgraph live -f 21million.rdf.gz -s release.schema.txt                  
[Decoder]: Using assembly version of decoder
I0918 14:24:07.178355   18010 init.go:98] 

Dgraph version   : 
Dgraph SHA-256   : 22cac961c0e975b29f6f41f1255cf769eba0cca67879d8788dbcea7a929e0898
Commit SHA-1     : 
Commit timestamp : 
Branch           : 
Go version       : go1.12.9

For Dgraph official documentation, visit https://docs.dgraph.io.
For discussions about Dgraph     , visit https://discuss.dgraph.io.
To say hi to the community       , visit https://dgraph.slack.com.

Licensed variously under the Apache Public License 2.0 and Dgraph Community License.
Copyright 2015-2018 Dgraph Labs, Inc.



Running transaction with dgraph endpoint: 127.0.0.1:9080
While trying to setup connection: context deadline exceeded. Retrying...
While trying to setup connection: context deadline exceeded. Retrying...
While trying to setup connection: context deadline exceeded. Retrying...
While trying to setup connection: context deadline exceeded. Retrying...
^C
```

**Comment by MichelDiz** [comment]
I'll leave it opened to keep tracking it. And test it again after #4020 is solved.

**Comment by MichelDiz** [comment]
I did more tests around this

Same error with:
v1.1.0
don't work ➜  dgraph-darwin-amd64 ./dgraph live -f rdf.rdf -s schema.schema     
works         ➜  dgraph-darwin-amd64 ./dgraph live -f rdf.rdf -s schema.schema  -a localhost:9080

v1.0.15
don't work ➜ Dgraph v1.0.15 ./dgraph live -r 21million.rdf.gz -s release.schema.txt  
works         ➜ ./dgraph live -r 21million.rdf.gz -s release.schema.txt -d localhost:9080

v1.0.13
don't work ➜ Dgraph v1.0.13 ./dgraph live -r 21million.rdf.gz -s release.schema.txt
works         ➜ ./dgraph live -r 21million.rdf.gz -s release.schema.txt -d localhost:9080

v1.0.6 
don't work ➜  v1.0.6 ./dgraph live -r 21million.rdf.gz -s release.schema 
works         ➜  v1.0.6 ./dgraph live -r 21million.rdf.gz -s release.schema.txt -d localhost:9080   

I do not understand why this happens, because 127.0.0.1 is Localhost on any operating system.

## All the Logs

```
➜  dgraph-darwin-amd64 ./dgraph live -f rdf.rdf -s schema.schema          
[Decoder]: Using assembly version of decoder
I0920 12:56:58.569629   49642 init.go:98] 

Dgraph version   : v1.1.0
Dgraph SHA-256   : 98db2956f6dd8b7b9b88e02962d2036845b057fe5fe953190eaafac0a83dfcce
Commit SHA-1     : ef7cdb28
Commit timestamp : 2019-09-04 00:12:51 -0700
Branch           : HEAD
Go version       : go1.12.7

For Dgraph official documentation, visit https://docs.dgraph.io.
For discussions about Dgraph     , visit https://discuss.dgraph.io.
To say hi to the community       , visit https://dgraph.slack.com.

Licensed variously under the Apache Public License 2.0 and Dgraph Community License.
Copyright 2015-2018 Dgraph Labs, Inc.



Running transaction with dgraph endpoint: 127.0.0.1:9080
While trying to setup connection: context deadline exceeded. Retrying...
While trying to setup connection: context deadline exceeded. Retrying...
^C
```

```

**Comment by danielmai** [comment]
Seems like a machine config issue, @MichelDiz. I tried the same commands you shared on Mac and they work with the default `--alpha` flag value `127.0.0.1:9080`.

with Dgraph v1.1.0:
```
dgraph live -f 21million.rdf.gz -s release.schema.txt
```

**Comment by MichelDiz** [comment]
I’ve created a VM with Windows 10 and tested it there. It works fine.

So it is indeed something else very odd. I can't figure out what is it. So in case, this issue happens to other users, please set as localhost.

**Comment by polymorphic** [comment]
I ran into the same problem running self-hosted v24.0.2 on Sequoia. I solved it by running the live loader within the alpha container rather than from a new container; I had to add an additional CLI parameter specifying the zero node:

```
root@4b55410e4c5f:/dgraph# dgraph live -f data.rdf.gz -s schema.txt -a localhost:9080 -z zero:5080
```

I suspect the issue is caused by the way docker networking works on a Mac.
