### ISSUE TITLE
Panic on Windows: possible related to integer compression.

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#4020]
### What version of Dgraph are you using?
```
Dgraph version   : v1.1.0-45-g53916e18b
Dgraph SHA-256   : 4f9fcdd1819990de98f5a1f75569fd63163b67a8264e442b9cca97967df8f215
Commit SHA-1     : 53916e18b
Commit timestamp : 2019-09-17 19:30:15 +0530
Branch           : master
Go version       : go1.13
```

### Have you tried reproducing the issue with the latest release?
No, cuz it's a PR testing.

### What is the hardware spec (RAM, OS)?
Windows 10 pro

I can't reproduce it in Darwin. However, it seems to hurt the live loader performance. 

### Steps to reproduce the issue (command/config used to run Dgraph).
1 - Run zero
2 - Bulk load 21 mi RDF
2.1 - Start a single cluster/node (One Alpha, One zero).
3 - Live Load 21 mi RDF again (just to push it) with Live Loader's default settings.
4 - Repeat again the live load with the same setting until Alpha crash and live load closes the connection and throws an error.

If you decrease -c to 1
```
-c, --conc int    Number of concurrent requests to make to Dgraph (default 10)
```
This panic doesn't happen (or would take longer to happen)
 
### Expected behaviour and actual result.

[v1.1.0-45-g53916e18bLogs.txt](https://github.com/dgraph-io/dgraph/files/3624255/v1.1.0-45-g53916e18bLogs.txt)

**Comment by mangalaman93** [comment]
May be related to https://github.com/golang/go/issues/23279
