### ISSUE TITLE
ACL permission changes takes few seconds to affect

### ISSUE THREAD

**Issue by prashant-shahi** [dgraph-io/dgraph#4031]
### What version of Dgraph are you using?

```go
Dgraph version   : v1.1.0-47-gcd0e2086
Dgraph SHA-256   : 31dde15b917ec6f70ae31480c87012a33a1a2e29bb49c8c649824345dd9d99a0
Commit SHA-1     : cd0e2086
Commit timestamp : 2019-09-19 13:43:55 +0530
Branch           : master
Go version       : go1.12.9
```

### Have you tried reproducing the issue with the latest release?

**YES**

### Steps to reproduce the issue (command/config used to run Dgraph).

Dgraph cluster was brought up using the [docker-compose yaml file in *dgraph* directory](https://github.com/dgraph-io/dgraph/blob/master/dgraph/docker-compose.yml).

- Bring up the Dgraph cluster with ACL feature turned on.
- Create a new user and a new group. Add the newly created user to the new group.
- Give permission to read/write/modify.
- Try to read/write/modify right afterward.

For the ACL tests of Dgraph clients currently, the delay is set to 6 seconds, which does get the work done.

### Expected behaviour and actual result.

Expected for ACL permission change to affect as soon as the response of success is relayed.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8793). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
