### ISSUE TITLE
[standalone image]: Issue running dgraph-standalone 

### ISSUE THREAD

**Issue by hackintoshrao** [dgraph-io/dgraph#4039]
### What version of Dgraph are you using?
dgraph/standalone:latest

### What is the hardware spec (RAM, OS)?
Mac OSX, 8GB RAM.

### Steps to reproduce the issue (command/config used to run Dgraph).
`docker run --rm -it -p 8000:8000 -p 8080:8080 -p 8090:8090 dgraph/standalone:latest`

### Expected behaviour and actual result.
Here is the error, 

`2019/09/22 00:37:38 LRU memory (--lru_mb) must be at least 1024 MB. Currently set to: 666.000000`

**Comment by DeyV** [comment]
please reopen

2020.12.06 - docker master version - and this error return. 

Docker on Mac

docker run --rm -it -p 8000:8000 -p 8088:8080 -p 8090:8090 dgraph/standalone:master
LRU memory (--lru_mb) must be at least 1024 MB. Currently set to: -1.000000


docker run --rm -it -p 8000:8000 -p 8088:8080 -p 8090:8090 dgraph/standalone:latest (2 month old version) 
works correctly
