### ISSUE TITLE
Cannot parse dateTime record that is written to backup

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#404]
I tried loading up goldendata.gz using the dgraphloader (which now uses the Go client and sends storage type information to the server) without any schema. 

The line
``` 
<m.0y4vj38>	<film.film.initial_release_date>	"2013-08-07T04:00:13Z"^^<http://www.w3.org/2001/XMLSchema#dateTime>	.
```
is written as 
```
<_uid_:0x39e6b1cadcf794ec> <film.film.initial_release_date> "2013-08-07 04:00:13 +0000 UTC"^^<xs:dateTime>  .
```
which rdf.Parse fails to parse, hence the verify script fails.

**Comment by ashwin95r** [comment]
Fixed with f2ed45adc4f810a70fd829892d887de6a002950b
