### ISSUE TITLE
Backup request does not use overridden credentials

### ISSUE THREAD

**Issue by cmgreen210** [dgraph-io/dgraph#4044]
### What version of Dgraph are you using?
v1.1.0
### Have you tried reproducing the issue with the latest release?
yes

### What is the hardware spec (RAM, OS)?
n/a

### Steps to reproduce the issue (command/config used to run Dgraph).
Set expired AWS credentials env variables (or none at all) on alpha server, then make 
backup request overriding them as detailed [here](https://docs.dgraph.io/enterprise-features/#create-a-backup).

### Expected behaviour and actual result.
The credentials provided in the backup request are expected to be used throughout.
Instead, if the current env credentials are stale dgraph attempts to get the latest
manifest in s3 using the old creds instead of the provided ones.

This can be seen in source here: https://github.com/dgraph-io/dgraph/blob/master/dgraph/cmd/alpha/admin_backup.go#L103

**Comment by martinmr** [comment]
Thanks for the detailed bug report. I've opened a PR to fix this issue for backups (more work is still needed to allow credentials to be overriden during restore.
