### ISSUE TITLE
sorting improvement

### ISSUE THREAD

**Issue by jfcg** [dgraph-io/dgraph#4045]
## Experience Report
My experience with Go standard library's sort is that it is not a concurrent implementation (does not utilize multiple goroutines). This bid me once before when I tried to sort a very long array of ints. However I did not assess its affects on dgraph. Dgraph database also uses it extensively:
```
grep -Pr 'sort\.(?:IsSorted|Search|Float64s|Ints|Sort|Slice|Strings)' . | grep -c .
```
gives 252 results. I decided to open this issue to determine how it affects dgraph and how it can be improved.

### Why that wasn't great, with examples
It took literally hours to sort the very long array I was interested in. Then I decided to implement my concurrent sorting implementation.

### Any external references to support your case
Please see my concurrent [implementation](https://github.com/jfcg/sorty) and benchmarks there. It is almost api-compatible with sort.

**Comment by campoy** [comment]
Thanks for the report, @jfcg 

We'll consider working on it soon, feel free to send a PR too!

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8794). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
