### ISSUE TITLE
Doc queries failing to  run due to CORS

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#4049]
### What version of Dgraph are you using?

Play

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, OS)?

Play

### Steps to reproduce the issue (command/config used to run Dgraph).

Go to https://docs.dgraph.io/query-language/#returning-values

Click on "Run" the query below and you'll see no result.

### Expected behaviour and actual result.

I'd expect to get a response, instead I have silence unless I open the console.

If you open the console you'll see this:

```
Access to XMLHttpRequest at 'https://play.dgraph.io/query?latency=true' from origin 'https://docs.dgraph.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by danielmai** [comment]
Docs are working again. There was a disk space issue on the Play cluster.
