### ISSUE TITLE
Block access to all predicates by default in ACL

### ISSUE THREAD

**Issue by ashish-goswami** [dgraph-io/dgraph#4082]
Currently if dgraph cluster is booted up with ACL on, all predicates can be accessed until first rule is created. Ideally we should not allow access to any predicates by default if ACL is on. We can expose `acl_allow_all` flag to allow access to all predicates after the cluster boot up.

Final behaviour will look as follows -
### ACL is off
Access to all predicates is OK

### ACL is on
NO Access to any predicates for reading/writing/modifying

### ACL is on but cluster is run with the option `acl_allow_on`
Access to all predicates is OK

**Comment by campoy** [comment]
We should indeed fix this, yes. I agree with the proposed behavior.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8451). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
