### ISSUE TITLE
Is there any convenient way to import existing data from Neo4j to dgraph ?

### ISSUE THREAD

**Issue by protheusfr** [dgraph-io/dgraph#4083]
After some basic testing, I would to import my existing Neo4j (3.3.6-enterprise) data to dgraph to go further.

I understand dgraph can import RDF n-quads data but Neo4j can't export in this format...
Any experience on the subject here ?

**Comment by MichelDiz** [comment]
Not sure about this in Neo4j, it certainly can export to JSON or CSV. 

Loading CSV in Dgraph https://docs.dgraph.io/howto/#loading-csv-data
Loading JSON in Dgraph is easy. You can use either a standard client or bulkloader to import JSONs.

**Comment by campoy** [comment]
You can export from Neo4j to CSV following this article:

https://neo4j.com/blog/export-csv-from-neo4j-curl-cypher-jq/

Then you can import all the CSV data into Dgraph following this article:

https://docs.dgraph.io/howto/#loading-csv-data

Notice that you could avoid the intermediary step of going to CSV by simply exporting/importing JSON - but some modifications might be necessary.

**Comment by protheusfr** [comment]
Thank you both, will try.

**Comment by sleto-it** [comment]
Hi,

In addition to the [article](https://neo4j.com/blog/export-csv-from-neo4j-curl-cypher-jq/) mentioned in a previous comment, also check the APOC [Export to CSV](https://neo4j.com/docs/labs/apoc/current/export/csv/) and [Export to JSON](https://neo4j.com/docs/labs/apoc/current/export/json/)
