### ISSUE TITLE
Create predicates from type fields

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#4085]
## Experience Report

It is confusing that when you declare a field in a type this is not taken into account automatically by the schema.

### What you wanted to do

In issue #4080, a user created a type with a field `head` of type `uid` to keep a 1:1 relationship.

### What you actually did

Since they didn't create the corresponding predicate in the schema `head: uid .`, once they sent the first mutation with a `head` predicate pointing to a `uid`, the predicate was created. 

The problem is this predicate was created with type `head: [uid] .` therefore breaking the user's expectations.

### Why that wasn't great, with examples

This made the user think 1:1 relationships were not supported.
Their expectations were justified.

Instead, I would have expected that if you create a type with field `head uid` in a type a corresponding predicate would be created.

This also includes the fact that if two types are created with the same name but different types an error should be returned.

### Any external references to support your case

N/A

**Comment by martinmr** [comment]
We are simplifying type definitions to not have to include a type so once that is added this shouldn't be an issue.

PR: https://github.com/dgraph-io/dgraph/pull/4017

**Comment by campoy** [comment]
Then we should still fail if a type is defined with a field that doesn't have a corresponding predicate on the schema, right?

**Comment by martinmr** [comment]
Ideally yes but I think implementing that would have a lot of edge cases. For example, it would mean you have to first add all the predicates, before you can declare a type. Or, what to do with the types when a predicates is removed?

It's definitely something we could do but I am not sure if the benefits outweigh the costs. Maybe better documentation or examples would be enough. I think getting rid of the field types would make it clearer that types and predicates both have to be declared before Dgraph works correctly.

**Comment by campoy** [comment]
Thanks for the clarification, Martin.

We should sit down all together and come up with a clear design for types and their relationship with predicates before continuing any changes.

I'll schedule something for next week.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8795). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
