### ISSUE TITLE
Missing documentation on valid predicate names 

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#4087]
## Documentation

What are the valid values for a predicate name?

The intersection between what's doable in JSON vs what's doable in our predicate names is actually a very useful concept.

It allows us to have unambiguous representation of facets in JSON by separating the values with `|`.

What other characters other than `|` are rejected from predicate names?

**Comment by prashant-shahi** [comment]
## Predicate names rules

Any alphanumeric combination of a predicate name is permitted. Dgraph also supports Internationalized Resource Identifiers (IRIs) for predicate names. 

### Allowed special characters

Single special characters are not accepted. They have to be prefixed/suffixed with alphanumeric characters.

```
][&*()_-+=!#$%
```

*Note: You can use `@` suffix, but the suffix character is ignored.*

### Forbidden special characters

The special characters below are not accepted.

```
^}|{`\~
```

**Comment by prashant-shahi** [comment]
@campoy We also support different languages as predicate names as per IRIs. For special characters for [Devanagari](https://en.wikipedia.org/wiki/Devanagari), I see a similar pattern as of the allowed special characters.

Before adding documentation on the valid predicate names, it is worth having a look at the current behavior.
