### ISSUE TITLE
Dgraph can not mutate mutations

### ISSUE THREAD

**Issue by Willem520** [dgraph-io/dgraph#4097]
Hi,I used Dgraph v1.1.0 and I saw the log contains below messages
zero log
![image](https://user-images.githubusercontent.com/26085817/65847262-5fd43e00-e373-11e9-9855-542ba45021cf.png)
alpha log
![image](https://user-images.githubusercontent.com/26085817/65847627-e5a4b900-e374-11e9-8bc4-c090a51d66a2.png)

I mutated a mutation,but could not get response,from the alpha log, it was endless

**Comment by martinmr** [comment]
It looks like the rebuilding process is stuck due to some issue in zero.

What's the output of doing a GET HTTP request to `zero/state`, where `zero` is the host and port of the zero in your cluster.

**Comment by Willem520** [comment]
the output was no problem,because I need to do ohter test,So,I clean the cluster and restore it;
about the zero, I used 3 machine,and each machine has 1 zero(default host and port) and 3 alpha(use port_offset=0,port_offset=1,port_offset=2)

**Comment by martinmr** [comment]
We need more info before we can try to debug this issue. From the logs, it seems like your mutations are blocked because the rebuild of the indices is stuck.

Can you share more logs as well as the output of the state endpoint? It's very hard to try to debug these kind of issues without more info.

**Comment by Willem520** [comment]
I modified schema on ratel. and got the log. rebuild had cost 138 hours and it was not stopped.I don't have more info.

**Comment by Willem520** [comment]
@martinmr Hi，I got the error again.there was no error log.I just modified a predicate to add an index.

**Comment by martinmr** [comment]
This is not really an issue. Operations will block when doing a schema update. The problem is that the previous rebuild took a long time. How long did it take this time and how big is your data?

Also, the alpha and zero logs around the time you made the update would be useful.

**Comment by Willem520** [comment]
I saw the log，it took 1h10m31s to rebuild about 2282837 label predicate.but it always log bytes sent: 0 B, speed: 0 B/sec. maybe the log puzzled me

**Comment by martinmr** [comment]
The log is indeed confusing but the time taken to rebuild the index doesn't seem that far out of what is expected.

I'll look into the log issue and see if there's something we could do to improve the logging.

**Comment by Willem520** [comment]
Oh, thanks
