### ISSUE TITLE
Dgraph tutorial blog post #1 is invalid.

### ISSUE THREAD

**Issue by ShawnMilo** [dgraph-io/dgraph#4125]
### What version of Dgraph are you using?

Built at 2019-10-03T13:07:27.362Z
Commit: 7f20b78
Commit Info: 7f20b78 Thu Oct 3 06:06:38 2019 -0700 (HEAD -> master, origin/master, origin/HEAD)

### Have you tried reproducing the issue with the latest release?

Yes.

### What is the hardware spec (RAM, OS)?

Ubuntu 19.04, i3 window manager, 64 GB of RAM, Intel i7-6700K.
Kernel: Linux gc 5.0.0-29-generic #31-Ubuntu SMP Thu Sep 12 13:05:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce the issue (command/config used to run Dgraph).

Follow the tutorial here _exactly_:
https://blog.dgraph.io/post/tutorial-1-getting-started/

### Expected behaviour and actual result.

Running the very first query should work, but instead I receive an error about a double-quote (unicode character 22) being an "unrecognized character". This happens whether I manually type in the example or copy/paste the example. I've tried both examples (the first one that says "do not run this yet" and the modified version below it).

```
Error Name: t

Message: while lexing {
  "set": [
    {
      "name": "Karthic",
      "age": 28
    },
    {
      "name": "Jessica",
      "age": 31
    }
  ]
} at line 2 column 2: Unrecognized character in lexText: U+0022 '"'
```
URL: http://localhost:8080/query?timeout=60s&debug=true

**Comment by hackintoshrao** [comment]
Hey @ShawnMilo ,

Can you check that you're running it from the `mutation` tab, not from the `query` tab?

**Comment by ShawnMilo** [comment]
@hackintoshrao: I was running it from the `Query` tab, as displayed in all the screenshots prior to the text.

I see now that the animated gif (which I had ignored earlier) shows clicking from `Query` to `Mutate` very briefly before pasting in the text, and the prose above clearly says to "go to the Mutate tab."

Running from the `Mutate` tab works. Thank you!

**Comment by hackintoshrao** [comment]
Glad that you opened up an issue and discussed it :) Please do follow up with the next episodes and give us your feedback.

**Comment by kesor** [comment]
@hackintoshrao I was also stumped by this. Took me some googling and finding this issue to realize that I was doing something "wrong". IMHO the usability of this "Query" vs. "Mutation" tab is unintuitive, thus people get confused and seeing this weird error about the `"` being wrong is not helping.
