### ISSUE TITLE
Assigning Big External uids

### ISSUE THREAD

**Issue by mbande** [dgraph-io/dgraph#4133]
### What version of Dgraph are you using?
version 1.1.0

### Have you tried reproducing the issue with the latest release?
yes

### What is the hardware spec (RAM, OS)?
linux, 16G

### Steps to reproduce the issue (command/config used to run Dgraph).
a fresh docker installation, create a mutation with a big uid, and run it by pydgraph:
```
p = {
            'uid': 36132443,
            'dgraph.type': 'User',
            'friend': [
                {
                    'uid': 8615709837,
                    'dgraph.type': 'User',
                }
            ],
        }
```

### Expected behaviour and actual result.
it should just work. but is says:
```
Uid: [36132443] cannot be greater than lease: [10000]
```
i found that the ```Zero```'s ```MaxLeaseId``` is preventing big uids.
as i have a big database with relations it them, i have to keep uids in sync with my external database ids. so letting Dgraph to choose the uid is not an option.
as a workaround, i used ```Zero``` API ```/assign?what=uids&num=18446744073709551615``` to increase ```MaxLeaseId``` as much as possible. now MaxLeaseId is 9223372036854795807 and it works for me.
is it the right thing to to? or i made a some mistake?

**Comment by MichelDiz** [comment]
Dgraph doesn't accept external UIDs patterns. Pay attention that `8615709837` will be converted to something like "`0x201894c8d`" so, I think this isn't wanted. Or maybe you know how to convert numbers to Dgraph's UID addresses.

For external IDs or UIDs you can use https://docs.dgraph.io/mutations/#external-ids
There is also an option of doing it using Upsert Transaction, right below.

BTW, the workaround you've shared would be the only one we would recommend. You can't use UIDs not allocated by Zero instance.

Cheers.
