### ISSUE TITLE
Is Dgraph a graph database?

### ISSUE THREAD

**Issue by zhouhao-learning** [dgraph-io/dgraph#4150]
Is Dgraph a graph database that can store data with attributes and relationships, such as data that stores knowledge maps?

**Comment by danielmai** [comment]
Yes, @zhouhao-learning. Dgraph is well suited for data with many interconnected relationships. I recommend checking out our interactive [Tour of Dgraph](https://tour.dgraph.io) to try out Dgraph first-hand and our [YouTube channel](https://www.youtube.com/channel/UCghE41LR8nkKFlR3IFTRO4w/featured) to learn more.

If you have further questions, please post a new topic on our discussion forum at https://discuss.dgraph.io.
