### ISSUE TITLE
Test suite fails with a fresh checkout

### ISSUE THREAD

**Issue by adg** [dgraph-io/dgraph#4154]
The dgraph unit test suite has many failures if you try to run it from a fresh checkout with no other setup. I wasn't able to find any information about the requirements/prerequisites for running the test suite, but in general Go unit tests should just work from a fresh checkout.

I ran into this trying to debug an issue with dgraph's live loader. This is a big roadblock for me and my team.

### What version of Dgraph are you using?

master

### What is the hardware spec (RAM, OS)?

macOS, MacBook Pro

### Steps to reproduce the issue (command/config used to run Dgraph).

git clone https://github.com/dgraph-io/dgraph
cd dgraph
go test ./...

### Expected behaviour and actual result.

Passing tests.

### Actual results.

Many failing tests. See the [full log](https://gist.github.com/adg/9cff49420906f4d825efc24e2f4e412d) for details.

**Comment by danielmai** [comment]
The tests assume that a Dgraph cluster is running before running the tests. There's a `test.sh` script that builds Dgraph, spins up a Dgraph test cluster, and then runs the tests.

**Comment by adg** [comment]
I see. Having prerequisites outside of the tests themselves is a bit of a Go anti-pattern. The usual approach with these kinds of tests is to skip such tests if the external dependencies aren't available.

In my specific case, I was trying to run the tests for the chunker package, which if I understand correctly shouldn't really require a dgraph cluster (we shouldn't need a running cluster just to test a parser, right?).

--

There's another related issue, in that if the dgraph cluster isn't available, then the test binary quits with a `log.Fatal`, meaning that the other tests that don't require the cluster won't even run (if they would run after the tests that require dgraph). The more user-friendly way of aborting such tests is to call `t.Fatal`, rather that `log.Fatal`, so that the other tests may continue to run. Should I file an issue about that?

**Comment by martinmr** [comment]
We are testing a database so a lot of our tests are end-to-end tests. We can't really avoid this. I filed https://github.com/dgraph-io/dgraph/issues/4172 to make the change needed so that the test binary does not immediately panic if there is not a cluster available. That should let the rest of the tests run.

@adg Is there anything else you want or are unsure about this issue? Otherwise let me know if it's fine to close it. We will keep track of the changes to the tests in the other issue.

**Comment by campoy** [comment]
I think it'd be good to fix it if possible.

Maybe lower the priority of the bug, but let's not close it yet.

**Comment by adg** [comment]
It makes sense that you should have a lot of end-to-end tests, but it should be possible to run your unit tests without spinning up a cluster (IMO, anyway). Maybe this could be a longer term goal for the project?

**Comment by martinmr** [comment]
ok. I'll lower the priority. fixing #4172 should allow `go test ./` to run without breaking (tests that need a cluster would break but would not cause the test suite to panic).

**Comment by martinmr** [comment]
Sorry, closed the issue by mistake.

**Comment by martinmr** [comment]
Once #4188 is submitted, you can do `go test ./...`. Unit tests will complete and tests that require a cluster will fail. The one exception is the packages that initialize the client in `TestMain`, but those packages have tests that all require a cluster to work properly so I think it's fine to crash in `TestMain`.

**Comment by martinmr** [comment]
@adg closing as the issue should be fixed now that #4180 is merged. If you have more concerns let us know.
