### ISSUE TITLE
Test scripts assume GOPATH layout

### ISSUE THREAD

**Issue by adg** [dgraph-io/dgraph#4155]
Now that the project is being made to support modules, there are still some old GOPATH-isms that remain. In `test.sh` and some of the included scripts, there are assumptions that the repo will be checked out into `$GOPATH/src/github.com/dgraph-io/dgraph`, when with modules it may be checked out anywhere.

**Comment by lolcoolkat** [comment]
Hey @adg where do you see that Dgraph is going to support modules? :)

**Comment by adg** [comment]
@lolcoolkat https://github.com/dgraph-io/dgraph/commit/0e73a57baf1cccc342cde2e0087c4fe155f1e8fa

**Comment by lolcoolkat** [comment]
@adg check my comment here https://github.com/dgraph-io/dgraph/pull/4146#issuecomment-540828071

Still getting the same error as before they added go module support. Any ideas? :P

**Comment by adg** [comment]
If you saw the same error before and after modules were added, then I don't think it's related to this issue.

**Comment by martinmr** [comment]
@danielmai do you know how to go about fixing this? I am guessing we could have a dgraph-root argument the same way we do for the jepsen test binary.

**Comment by danielmai** [comment]
Something like dgraph-root that refers to the root of the repo would work. The tests and the test scripts should no longer assume that Dgraph or anything other repos (like the benchmarks repo for data files) are in GOPATH.

**Comment by martinmr** [comment]
Closing since the issue it's been addressed
