### ISSUE TITLE
Test script continues regardless of command failures

### ISSUE THREAD

**Issue by adg** [dgraph-io/dgraph#4156]
If you run `test.sh` without a required tool present, the script continues despite failures.

For example

```
$ ./test.sh
INFO: Running only unit tests
INFO: Running tests using the default cluster
/dgraph/contrib/scripts/functions.sh: line 15: pushd: /src/github.com/dgraph-io/dgraph/dgraph: No such file or directory
Rebuilding dgraph ...
/dgraph/contrib/scripts/functions.sh: line 20: make: command not found
/dgraph/contrib/scripts/functions.sh: line 22: docker: command not found
/dgraph/contrib/scripts/functions.sh: line 23: docker-compose: command not found
```

I think that the shebang line should include the `-e` flag, or the script should have `set -e` early on, so that the script doesn't continue if a command fails.

**Comment by martinmr** [comment]
I tried but it doesn't work the way you expect it. If I add `set -e` to the functions.sh script, the script ends as soon as it finds an error but it doesn't make the script calling it do the same.

I think it's better to include documentation on the prerequisites needed to successfully run the test.sh script.

**Comment by adg** [comment]
You'd need to put the `set -e` in `test.sh` itself.

The main thing is that if a command in the test script fails, for whatever reason, then the script should stop. Otherwise something could fail, but the script may continue and otherwise think it has succeeded.

**Comment by martinmr** [comment]
I tried that on Friday but it didn't work for some reason. I tried again today and the script fails even without the "set -e".

I tested it by uninstalling docker-compose from my machine.

```
INFO: Running only unit tests
INFO: Running tests using the default cluster
Rebuilding dgraph ...
Commit SHA256: 640665703ba145d8d1be7e3eb369f354dc12f9e4
Old SHA256: 6eb24dabafa8513eb61ed0cdcd2d61faf9f5cbbe01b32da51aea70b64f412882
New SHA256: 1caf4963ea9b50462bb986085416b6aeacb764acd8deeaebdaa41de305db434c
/home/martinmr/go/src/github.com/dgraph-io/dgraph/contrib/scripts/functions.sh: line 23: docker-compose: command not found
```
I'll open a PR to add the "set -e" to the script just in case.
