### ISSUE TITLE
Facebook ent

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#4159]
It would be good if there was a driver built for Facebook ent package for D graph

**Comment by pjebs** [comment]
https://github.com/facebookincubator/ent

**Comment by mangalaman93** [comment]
Thank you for creating this issue. It would be useful if someone from the community could pick this up and build a driver. I have added the `help wanted` label on this.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8452). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
