### ISSUE TITLE
Please add a note, that multiple queries with a schema query are not possible

### ISSUE THREAD

**Issue by graphpivot** [dgraph-io/dgraph#4165]
## Documentation

The please add a note [here](https://docs.dgraph.io/query-language/#multiple-query-blocks) and [here](https://docs.dgraph.io/query-language/#querying-schema) that multiple queries with a schema query are not possible. For reference, see the discussion [here](https://discuss.dgraph.io/t/multiple-query-one-for-predicates-and-one-for-shema-in-one-block/5228).

**Comment by martinmr** [comment]
The note only applies to the second link. The first link is talking about multiple queries inside a query block and the schema query docs already mention that schema queries go outside the block.

Opened up https://github.com/dgraph-io/dgraph/pull/4166 to clarify this.

**Comment by graphpivot** [comment]
Thank you for the comment. I've just tried the following on play.dgraph.io:

`{
  query(func:has(name), first:10){uid}
}
{
  query2(func:has(actor.film), first:10){uid}
}`

And this delivers also who different result sets. 

> Inside a single query, multiple query blocks are allowed. 

Maybe you could add here something like: You can choose to put all the query blocks inside curly braces or alternatively each query block must be surrounded by curly braces.

The proposed clarification to the second link if fine.

Cheers!

**Comment by martinmr** [comment]
I don't think that makes things clearer. I'll keep that section as it is right now.
