### ISSUE TITLE
Groupby does not support predicate of list type

### ISSUE THREAD

**Issue by honglicheng** [dgraph-io/dgraph#4170]
`kind: [string]`

```rdf
_:A <kind> "dog" .
_:A <kind> "animal" .
_:B <kind> "cat" .
_:B <kind> "animal" .
```

```graphql
@groupby(kind){
    count(uid)
}
```
i want to get :
```
{kind: "dog", count: 1}, {kind: "cat", count: 1}, {kind: "animal", count: 2}
```

but only get:  
```
{kind: "dog", count: 1}, {kind: "cat", count: 1}
```
it seems that only the first item in the list can be grouped.

**Comment by prashant-shahi** [comment]
Hello @honglicheng,
Could you mention the Dgraph version that you are using?

**Comment by honglicheng** [comment]
version： 1.1.0
{
    q(func: has(kind)) @groupby(kind){
        count(uid)
    }
}

**Comment by MichelDiz** [comment]
Hi there,
Internally we have a discussion about improving the group by function. This case would be something "different" tho. But thinking about this issue, I come to a conclusion that if we improve the group by function this query should look like:

```graphql
{
 var(func: has(kind)) @groupby(kind) {
    T as count(uid)
  }

q(func: uid(T)) {
  name
  age
}

}
```

## Result 

```JSON
{
  "data": {
    "q": [
      {
        "dog": [ 
              {
                "uid": "0x1",
                "name": "Bingo"
              }
      ]
      },
      {
        "animal": [
              {
                "uid": "0x1",
                "name": "Bingo"
              },
              {
                "uid": "0x3",
                "name": "Angry Purr"
              }
      ]
      },
      {
        "cat": [
              {
                "uid": "0x3",
                "name": "Angry Purr"
              }
      ]
      }
    ]
  }
```

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8453). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
