### ISSUE TITLE
Error when third node tries to join the cluster

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#418]
I am trying to start three nodes using config files. The first two work fine. The third one fails with an error.

Steps to reproduce

1. Checkout `fix/testrun` branch.
2. Move to cmd/dgraph, go build and then.
3. Start first node `./dgraph --config testrun/conf1.yaml`.
4. Start second node `./dgraph --config testrun/conf2.yaml`.
5. Start third node `./dgraph --config testrun/conf3.yaml`.

It fails with error
```
Connected with: localhost:12345
2016/12/23 17:25:31 error.go:75: Unable to find addr for peer: 1
Found 0 entries
```

Please verify that the conf files are right @manishrjain.

**Comment by manishrjain** [comment]
Looks like a new bug. Fixing.

**Comment by manishrjain** [comment]
Turns out the `--idx` flag wasn't passed which caused the node to treat itself as node 1. Closing.
