### ISSUE TITLE
启动了3个节点,每个节点的数据400G,查询总是OOM,请问400G的数据量是不是太大了,需要增加节点?

### ISSUE THREAD

**Issue by tiankonghewo** [dgraph-io/dgraph#4189]
1,Dgraph版本1.0.15
本来想用最新的1.1.0,但是数据量很大bulk loader在1.1.0版本下总是在map阶段就OOM,
使用1.0.15版本却可以平稳运行
2,节点配置信息
3台Ubuntu16.04,阿里云服务器
16core64G
3,节点数据量分别是
200G
380G
440G

使用出现的问题,查询特别慢,需要10s的时间,生产环境下根本满足不了需求.
请问是节点的数据量太大,导致的查询时间很长吗?
需要增加节点吗?
每次启动8个进程,并行的查询3个节点的dgraph集群时,dgraph的内存很快被耗尽,然后OOM
试了4次,都是这样,请问有什么解决办法吗?

**Comment by MichelDiz** [comment]
This feels like duplicated of https://github.com/dgraph-io/dgraph/issues/4190
Btw, I'm not sure if we have somebody fluent in Chinese. The translation in Google Translate seems to be precise but can be a bit confusing.

So If this isn't a duplicated of #4190 feel free to reopen it.
