### ISSUE TITLE
How to know how many node  are in the dgraph?

### ISSUE THREAD

**Issue by tiankonghewo** [dgraph-io/dgraph#4192]
neo4j display the total number of nodes on the webpage.
how is the dgraph?
I read the document in detail, but I didn't find which query sentence can achieve my goals

**Comment by MichelDiz** [comment]
You can use this query:
>https://play.dgraph.io/
```
{
  nodeCount(func: type(<Actor>)) {
    Actors: count(uid)
  }
}
```

Also, there's a panel called "Explorer" and also the panel "Schema" in Ratel UI that you can find out other stats.

Please, do questions in https://discuss.dgraph.io.

Cheers.
