### ISSUE TITLE
dgraph is distributed, but bulk loader 100G rdf data need 128GB memory server

### ISSUE THREAD

**Issue by tiankonghewo** [dgraph-io/dgraph#4193]
dgraph is distributed, but bulk loader 100G rdf data need 128GB memory, 
if rdf.gz file is  400GB, I need 256GB memory.
dgraph is distributed, but import data operate only on one machine, can‘t be distributed.
Isn't that ironic?

**Comment by MichelDiz** [comment]
We are working on it https://github.com/dgraph-io/dgraph/issues/2628
@tiankonghewo if you have questions or discussions to add it would be nice to do in already opened issues or in Discuss forum.

**Comment by linkerlin** [comment]
maybe mmap is needed for larger datasets.

**Comment by MichelDiz** [comment]
Closing due kind of duplicated (but as a question?) Any further discussion must go to #2628.
