### ISSUE TITLE
Something wrong with multi edge query shortest path

### ISSUE THREAD

**Issue by zhuyaoyhj** [dgraph-io/dgraph#4199]
### What version of Dgraph are you using?

    Dgraph version   : v1.1.0  
    Dgraph SHA-256   : 
    7d4294a80f74692695467e2cf17f74648c18087ed7057d798f40e1d3a31d2095
    Commit SHA-1     : ef7cdb28
    Commit timestamp : 2019-09-04 00:12:51 -0700
    Branch           : HEAD
    Go version       : go1.12.7

### Have you tried reproducing the issue with the latest release?

    yes

### What is the hardware spec (RAM, OS)?

    Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz ，linux， 128G

### Steps to reproduce the issue (command/config used to run Dgraph).

data:

    {
        set {
        _:a <cf> _:b .
        _:a <friend> _:b (weight=0.1) .
        _:b <friend> _:c (weight=0.2) .
        _:c <friend> _:d (weight=0.3) .
        _:a <friend> _:d (weight=1) .
        _:a <name> "Alice" .
        _:b <name> "Bob" .
        _:c <name> "Tom" .
        _:d <name> "Mallory" .
        }
    }

Find shortest path from Alice to Mallory.
query language:
1、use @facets

    {
        path as shortest(from: 0x3a981, to: 0x3a984) {
            cf
            friend @facets(weight)
       }
       path(func: uid(path)) {
           name
       }
    }

result:
    
    {
    "data": {
    "path": [
      {
        "name": "Alice"
      },
      {
        "name": "Bob"
      },
      {
        "name": "Tom"
      },
      {
        "name": "Mallory"
      }
     ],
    "_path_": [
      {
        "friend": {
          "friend": {
            "friend": {
              "uid": "0x3a984",
              "friend|weight": 0.3
            },
            "uid": "0x3a983",
            "friend|weight": 0.2
          },
          "uid": "0x3a982",
          "friend|weight": 0.1
        },
        "uid": "0x3a981",
        "_weight_": 0.6
      }
    ]
    } 
    }
  
2、reverse the order of edges
 
    {
        path as shortest(from: 0x3a981, to: 0x3a984) {
            friend @facets(weight)
            cf
    }
        path(func: uid(path)) {
            name
        }
    } 

result

    {
    "data": {
    "path": [
      {
        "name": "Alice"
      },
      {
        "name": "Mallory"
      }
    ],
    "_path_": [
      {
        "friend": {
          "uid": "0x3a984",
          "friend|weight": 1
        },
        "uid": "0x3a981",
        "_weight_": 1
      }
    ]
    }
    }

the query result is different.
    
### Expected behaviour and actual result.
Both query statements can return the shortest path. and I also submitted the edit code.
link： https://github.com/dgraph-io/dgraph/pull/4194

    {
    "data": {
    "path": [
      {
        "name": "Alice"
      },
      {
        "name": "Bob"
      },
      {
        "name": "Tom"
      },
      {
        "name": "Mallory"
      }
     ],
    "_path_": [
      {
        "friend": {
          "friend": {
            "friend": {
              "uid": "0x3a984",
              "friend|weight": 0.3
            },
            "uid": "0x3a983",
            "friend|weight": 0.2
          },
          "uid": "0x3a982",
          "friend|weight": 0.1
        },
        "uid": "0x3a981",
        "_weight_": 0.6
      }
    ]
    } 
    }

**Comment by MichelDiz** [comment]
Sorry, the huge delay. I think I didn't saw this question.

So, you wanna see the shortest path in reverse. For that, you need to use reverse edges. set "friend" as reverse in your schema and test this query below.

e.g:
```
  {
  	A as var (func: eq(name, "Alice"))
  	M as var (func: eq(name, "Mallory"))

  	path as shortest(from: uid(M), to: uid(A) ) {
  		cf
  		~friend @facets(weight)
  	}
  	path(func: uid(path)) {
  		name
  	}
  }
```

Feel free to ask if remains any doubt about it.
