### ISSUE TITLE
Publish logs in CI

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#4215]
CI request : when a CI test fails, it's sometimes nice to also have the container logs.  If a test run fails, we could publish the container logs that were running for that test as artifacts.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8454). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
