### ISSUE TITLE
Using Dgraph as a Go package fails when using Go Modules

### ISSUE THREAD

**Issue by alexkreidler** [dgraph-io/dgraph#4216]
Using the Dgraph go package in a project is broken with Go Modules. I also tried just doing it in the GOPATH like the README says, but that doesn't work per #4214.

See my project [here](https://github.com/alexkreidler/dgraph-validator), with key elements [go.mod](https://github.com/alexkreidler/dgraph-validator/blob/master/go.mod) and [root.go](https://github.com/alexkreidler/dgraph-validator/blob/master/cmd/root.go). It's a simple tool to parse/validate RDF or JSON schemas exactly like dgraph does to be able to catch errors locally instead of deploying to Kubernetes only to find the schema is invalid.

I set the version of `github.com/dgraph-io/dgraph` to `master` which resolved to `v1.1.1-0.20191023221921-97c5bcab0055` at time of writing.

### What version of Dgraph are you using?
Latest (master)
### Expected behaviour and actual result.
Expected: able to include `dgraph` in a go module program and compile sucessfully.

Actual:
```bash
alex@Alex-MBP ~/c/dgraph-validator (master)> go build
# github.com/dgraph-io/dgraph/protos/pb
../../go/pkg/mod/github.com/dgraph-io/dgraph@v1.1.1-0.20191023221921-97c5bcab0055/protos/pb/pb.pb.go:7146:29: m.Kv[iNdEx].MarshalToSizedBuffer undefined (type *pb.KV has no field or method MarshalToSizedBuffer)
../../go/pkg/mod/github.com/dgraph-io/dgraph@v1.1.1-0.20191023221921-97c5bcab0055/protos/pb/pb.pb.go:7209:29: m.Kv[iNdEx].MarshalToSizedBuffer undefined (type *pb.KV has no field or method MarshalToSizedBuffer)
alex@Alex-MBP ~/c/dgraph-validator (master) [2]> go version
go version go1.13 darwin/amd64
```

I'm really excited to use Dgraph in lots of projects, I just would hope that these basic toolchain issues be fixed and ideally tested regularly in some simple integration test (e.g. building a dummy program like mine using dgraph APIs from master using Go Modules)

**Comment by martinmr** [comment]
Right now, this will work if you use `@master` since 1.1 doesn't have modules enabled.

But as I mentioned in the other thread, it's better not to depend on dgraph altogether. dgraph is not meant to be used as a library so there's little value in doing so.

Closing the issue for now as there's no actionable items.
