### ISSUE TITLE
Add possibility to setup cors on dgraph server for demonstration purposes

### ISSUE THREAD

**Issue by aexol** [dgraph-io/dgraph#4228]
## Experience Report

Note: Feature requests are judged based on user experience and modeled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### What you wanted to do
Make CORS request to database server

**Comment by MichaelJCompton** [comment]
Closing.  We've decided to move the GraphQL endpoint onto our Alpha servers (the actual database nodes), so this becomes not an issue.
