### ISSUE TITLE
Don't return empty nodes

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#424]
``` curl localhost:8080/query -XPOST -d $'{tourist(near("loc", "{\'type\':\'Point\', \'coordinates\': [-122.469829, 37.771935]}", "10000")) {website, name}}'```

Returns empty nodes; which we shouldn't.

**Comment by ashwin95r** [comment]
Fixed. ab5d98d5a98fa1b83450e8a35f8d5a1982725946
