### ISSUE TITLE
when alpha Creating snapshot, the response time writing or querying of txn is takes several seconds

### ISSUE THREAD

**Issue by raoshuaix1** [dgraph-io/dgraph#4250]
### What version of Dgraph are you using?
 Dgraph version   : v1.1.0
Commit SHA-1     : ef7cdb28
Commit timestamp : 2019-09-04 00:12:51 -0700
 Branch           : HEAD
 Go version       : go1.12.7
### Have you tried reproducing the issue with the latest release?
yes

### What is the hardware spec (RAM, OS)?
32G ram, ubuntu18.04

### Steps to reproduce the issue (command/config used to run Dgraph).
when alpha Creating snapshot, txn rpc request will time consuming increase.
It seems that all requests have been suspended, even if NewReadOnlyTxn is called.

### Expected behaviour and actual result.
Return request results as soon as possible.
when alpha Creating snapshot, the response time writing or querying of txn is takes several seconds. Normal return takes only a few hundred milliseconds

**Comment by arijitAD** [comment]
We have observed this behavior and we are working on optimizing the snapshot creation. The fix should be out soon.

**Comment by dmitryyankowski** [comment]
Hoping we can get #4901 merged in soon! 🚀
