### ISSUE TITLE
Docs: Add mentions about Type System.

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#4263]
## Documentation

Ref: https://discuss.dgraph.io/t/how-to-delete-a-row/5310

>(2) How do I delete using a type? https://docs.dgraph.io/master/mutations/#delete doesn’t even mention type.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8455). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
