### ISSUE TITLE
Check fail if any predicate is assigned to group zero

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#427]
In the group conf, fp % N + k. Here we should assert that k >= 1. And nothing is assigned to group zero.

**Comment by pawanrawal** [comment]
We fail now if k == 0.

**Comment by manishrjain** [comment]
And how about if one sets predicate directly to zero? 0: pred

**Comment by manishrjain** [comment]
And also, can you link the relevant PR here?

**Comment by pawanrawal** [comment]
Sorry, hadn't handled that case. Should have sent a PR. I have one now https://github.com/dgraph-io/dgraph/pull/431
