### ISSUE TITLE
ip and port replace;Data cannot be exported;

### ISSUE THREAD

**Issue by lctforgit** [dgraph-io/dgraph#4301]

**Comment by shekarm** [comment]
Hi, Thank you for posting this issue. Please provide more details on what you are trying to do. What version of dgraph you are using? Have you tried reproducing with the latest release? What is the hardware spec (RAM, OS). Step to reproduct the issue. Expected and actual behavior. 

Thanks
Shekar

**Comment by lctforgit** [comment]
Thank you for answering my question. I'm sorry I didn't elaborate on it.

What version of Dgraph are you using?
v1.0.14

Have you tried reproducing the issue with the latest release?
yes .

What is the hardware spec (RAM, OS)?
8GB RAM , Windows 10

Problem description:
After starting dgraph on a machine, when the IP and port of the machine change, the data in dgraph cannot be exported?

**Comment by lctforgit** [comment]
I want the startup IP change of dgraph can also export the stored data

**Comment by danielmai** [comment]
How does IP address of the machine change? When you're logged in to the machine you can locally run `curl localhost:8080/admin/export` or `curl 127.0.0.1:8080/admin/export` to create an export.

Can you share the commands you used and any error messages you see that prevents you from exporting your data as described in the [Export Database documentation](https://docs.dgraph.io/deploy/#export-database)?

**Comment by lctforgit** [comment]
I used a virtual machine. After I reset the IP, I started dgraph with IP (1.1.1.101) specified instead of localhost

**Comment by MichelDiz** [comment]
I will close this issue. This is a community support request and usually made at https://discuss.dgraph.io/. If the problem still persists, we can help you there.
Cheers.
