### ISSUE TITLE
JSON mutation for string facet converted to datetime value

### ISSUE THREAD

**Issue by Willem520** [dgraph-io/dgraph#4302]
### What version of Dgraph are you using?
Dgraph v1.1.0
Dgraph4j 2.0.2
### Have you tried reproducing the issue with the latest release?
no

### What is the hardware spec (RAM, OS)?

docker
### Steps to reproduce the issue (command/config used to run Dgraph).
this is my code
    @Test
    public void upsert(){
        Transaction txn = dgraphClient.newTransaction();
        DgraphProto.Mutation.Builder mutateBuilder = DgraphProto.Mutation.newBuilder();
        try {
            String query = "query {\n"
                    +"v1 as var(func: eq(gid, \"8738133648736665\"))\n"
                    +"v2 as var(func: eq(gid, \"1785eefcaeef15048d19fbd170a802e6\"))\n"
                    +"v3 as var(func: eq(gid, \"8d6a4b2889bc25879d2d0fb87b8f2a78\"))\n"
                    +"v4 as var(func: eq(gid, \"9b47722eddd8089a11be1135f25394ba\"))\n"
                    +"v5 as var(func: eq(gid, \"5c8d84a3ac222177ed05267b178f6bda\"))\n"
                    +"}\n";
            /*mutateBuilder.setSetNquads(
                    ByteString.copyFromUtf8(
                              "uid(v1) <r_pharmacy> uid(v2) (distance=1034) .\n"
                            + "uid(v1) <r_pharmacy> uid(v3) (distance=1111) .\n"
                            + "uid(v1) <r_pharmacy> uid(v4) (distance=234) .\n"
                            + "uid(v1) <r_pharmacy> uid(v5) (distance=1134) .\n"));*/

            JSONArray nodeArr = new JSONArray();
            JSONObject node1 = new JSONObject();
            JSONObject node2 = new JSONObject();
            JSONObject node3 = new JSONObject();
            JSONObject node4 = new JSONObject();

            JSONObject edge1 = new JSONObject();
            JSONObject edge2 = new JSONObject();
            JSONObject edge3 = new JSONObject();
            JSONObject edge4 = new JSONObject();

            node1.put("uid","uid(v1)");
            node1.put("label","resblock");
            edge1.put("uid","uid(v2)");
            edge1.put("label","pharmacy");
            edge1.put("r_pharmacy|distance","1034");
            node1.put("r_pharmacy",edge1);

            node2.put("uid","uid(v1)");
            node2.put("label","resblock");
            edge2.put("uid","uid(v3)");
            edge2.put("label","pharmacy");
            edge2.put("r_pharmacy|distance","1111");
            node2.put("r_pharmacy",edge2);

            node3.put("uid","uid(v1)");
            node3.put("label","resblock");
            edge3.put("uid","uid(v4)");
            edge3.put("label","pharmacy");
            edge3.put("r_pharmacy|distance","234");
            node3.put("r_pharmacy",edge3);

            node4.put("uid","uid(v1)");
            node4.put("label","resblock");
            edge4.put("uid","uid(v5)");
            edge4.put("label","pharmacy");
            edge4.put("r_pharmacy|distance","1134");
            node4.put("r_pharmacy",edge4);

            nodeArr.add(node1);
            nodeArr.add(node2);
            nodeArr.add(node3);
            nodeArr.add(node4);
            mutateBuilder.setSetJson(
                    ByteString.copyFromUtf8(nodeArr.toJSONString()));
            DgraphProto.Request request =
                    DgraphProto.Request.newBuilder().setQuery(query).addMutations(mutateBuilder).build();
            DgraphProto.Response response = txn.doRequest(request);
            logLatency(response.getLatency());
            txn.commit();
        } catch (Exception e){
            e.printStackTrace();
        } finally {
            txn.discard();
        }
    }
######################
fist,I run the json format,then run the query
{
  q(func: eq(gid, "8738133648736665")) {
    uid
    gid
    label
			r_pharmacy@facets{
        uid
        gid
        label
      }
}
}
and got the result
{
  "data": {
    "q": [
      {
        "uid": "0x40a064",
        "gid": "8738133648736665",
        "label": "resblock",
        "r_pharmacy": [
          {
            "uid": "0x409ea6",
            "gid": "1785eefcaeef15048d19fbd170a802e6",
            "label": "pharmacy",
            "r_pharmacy|distance": "1034-01-01T00:00:00Z"
          },
          {
            "uid": "0x409f58",
            "gid": "8d6a4b2889bc25879d2d0fb87b8f2a78",
            "label": "pharmacy",
            "r_pharmacy|distance": "1111-01-01T00:00:00Z"
          },
          {
            "uid": "0x409ff7",
            "gid": "9b47722eddd8089a11be1135f25394ba",
            "label": "pharmacy",
            "r_pharmacy|distance": "234"
          },
          {
            "uid": "0x40a000",
            "gid": "5c8d84a3ac222177ed05267b178f6bda",
            "label": "pharmacy",
            "r_pharmacy|distance": "1134-01-01T00:00:00Z"
          }
        ]
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 18349,
      "processing_ns": 2137328,
      "encoding_ns": 58584,
      "assign_timestamp_ns": 683013
    },
    "txn": {
      "start_ts": 420434
    }
  }
}
you can see the r_pharmacy|distance was changed to look like time.
############################
second,I run the Nquads format,then run the same query
{
  q(func: eq(gid, "8738133648736665")) {
    uid
    gid
    label
			r_pharmacy@facets{
        uid
        gid
        label
      }
}
}
and got the result
{
  "data": {
    "q": [
      {
        "uid": "0x40a064",
        "gid": "8738133648736665",
        "label": "resblock",
        "r_pharmacy": [
          {
            "uid": "0x409ea6",
            "gid": "1785eefcaeef15048d19fbd170a802e6",
            "label": "pharmacy",
            "r_pharmacy|distance": 1034
          },
          {
            "uid": "0x409f58",
            "gid": "8d6a4b2889bc25879d2d0fb87b8f2a78",
            "label": "pharmacy",
            "r_pharmacy|distance": 1111
          },
          {
            "uid": "0x409ff7",
            "gid": "9b47722eddd8089a11be1135f25394ba",
            "label": "pharmacy",
            "r_pharmacy|distance": 234
          },
          {
            "uid": "0x40a000",
            "gid": "5c8d84a3ac222177ed05267b178f6bda",
            "label": "pharmacy",
            "r_pharmacy|distance": 1134
          }
        ]
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 54199,
      "processing_ns": 1895756,
      "encoding_ns": 63655,
      "assign_timestamp_ns": 689699
    },
    "txn": {
      "start_ts": 421229
    }
  }
}
this was the correct result.
### Expected behaviour and actual result.
json format can execute correctly.

**Comment by shekarm** [comment]
Thank you for the post. I  will assign an engineer to look at this.

**Comment by danielmai** [comment]
The facet types are different in the examples you shared. The facet type in the N-Quad mutation is an int `(distance=1034)` and it's a string in the JSON mutation `edge1.put("r_pharmacy|distance","1034");`. You can use a JSON int in the mutation so they're equivalent types. Seems like that's what you're looking for, and that works.

```
{"r_pharmacy|distance": 1034}
```

This bug where a facet JSON string is represented in date-time format is reproducible in other clients as well (Ratel, curl).

**Comment by Willem520** [comment]
yes，the number in json string will be converted to date-time format. I tried some case,if the value is lower than 1000, it was correct, greater than 1000, it was incorrect

**Comment by martinmr** [comment]
The code first tries to convert a string to a datetime. If this doesn't succeed then it will store the facet as a string. This doesn't look like a bug to me but it's also not clear whether it's the right thing to do. At the very least, I think it will confuse users. The reason something like "302" is parsed correctly but something like "1991" is not is becasue "302" is not considered a valid datetime.

Link to relevant code: https://github.com/dgraph-io/dgraph/blob/master/chunker/json_parser.go#L69-L72

**Comment by danielmai** [comment]
Dgraph doesn't enforce any types on facets. What we could do instead is only allow RFC 3339-valid datetime strings to be interpreted as datetime values. That would allow you to retrieve numbers like 1041 as integers. It does mean that if you want to set a date you'll need to set it as a valid RFC 3339 datetime string. Does that work for you, @Willem520?

**Comment by Willem520** [comment]
> Dgraph doesn't enforce any types on facets. What we could do instead is only allow RFC 3339-valid datetime strings to be interpreted as datetime values. That would allow you to retrieve numbers like 1041 as integers. It does mean that if you want to set a date you'll need to set it as a valid RFC 3339 datetime string. Does that work for you, @Willem520?


@danielmai hi,if there is no method to convert date string "yyyy-MM-dd hh:mm:ss" to date,I think your idea is good. at least, it could use number string correctly in json format. thx

**Comment by martinmr** [comment]
We had an internal discussion about it and we concluded that only converting strings to dates only if they match the RFC 3339 format would be too restricting. We might decide to change the criteria but it needs a bit more discussion.

 However , if you want to store numbers, you should do so by setting the value as a number. So instead of writing:

```
 edge1.put("r_pharmacy|distance","1034");
```

write

```
 edge1.put("r_pharmacy|distance",1034);
```

This stores the facet as a number and is already supported in the current version of Dgraph. I'll update the documentation to mention the existence of these facet conversions.

**Comment by Willem520** [comment]
Ok, I will try it
