### ISSUE TITLE
let math function support DQL Variables.

### ISSUE THREAD

**Issue by zhaodengchang** [dgraph-io/dgraph#4309]
### What you wanted to do
 [GraphQL Variables](https://docs.dgraph.io/query-language/#graphql-variables) can be used in math function

### What you actually did
We use GraphQL Variables to input a float value $a to the Dgraph query , and want to do some calculation with math function, e.g. : math($a + 1.23)

### Why that wasn't great, with examples
Currently it doesn't work.

**Comment by MichaelJCompton** [comment]
This looks like a reasonable feature request.

I'm tagging it as accepted, which means it will get into our backlog of features to consider.  

If we decide to implement it, we'll post an update here.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8803). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
