### ISSUE TITLE
Check fail if no tokenizer when string indexing

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#432]
If we're provided a schema which does string indexing, and there's no valid tokenizer (due to lack of data file), check fail instead of silently not indexing the values.

**Comment by jchiu0** [comment]
https://github.com/dgraph-io/dgraph/commit/6e74c4d3feb46029e759fd8ed2f10ba2ea981158

Added a check for whether ICU is disabled.

**Comment by pawanrawal** [comment]
We should also check fail if tokenizer doesn't work for some reason. Say after checking the file, we can try doing a simple tokenization of a string with two words separated by comma. If we don't get back both words we can fail. This would help us discover earlier whether embedding works properly?

**Comment by jchiu0** [comment]
Travis should run some tests in embedded mode if it is not already doing so.

That said, I am still puzzled why the tok unit test passes in embedded mode but fails in the actual run. Digging..

**Comment by jchiu0** [comment]
@pawanrawal Thanks for the suggestion. The fix has been committed. It now does the simple tokenization check. If it fails, we disable ICU. And if we try to use ICU while it is disabled, it is a fatal error.
