### ISSUE TITLE
Release process change and/or documentation error

### ISSUE THREAD

**Issue by djhenderson** [dgraph-io/dgraph#434]
In the [Beginners Guide](https://wiki.dgraph.io/Beginners_Guide), both the Automatic Download and the Manual Download methods rely on the presence of compressed tar files for linux and darwin for the latest release. These files are found at URLs that are computed using the Github API release `tag_name` only. The automatic method uses a shell script hosted at `https://get.dgraph.io`, and the manual method relies on downloading the same files. The target file for version `v0.7.1` for `linux` has the following URL:  `https://github.com/dgraph-io/dgraph/releases/download/v0.7.1/dgraph-linux-amd64-v0.7.1.tar.gz`.

For convenience, the binaries for each release should be provided at the expected locations. Otherwise, the automatic download script, and the manual download description need to be changed so the archive of binaries for the latest release can be downloaded without difficulty.

(edit to change dgraph.io to dgraph-io)

**Comment by manishrjain** [comment]
I'm not entirely sure what Doug means here.

**Comment by djhenderson** [comment]
When you follow the recommended install steps in the Beginner's Guide, either the automatic or manual download, you are expected to find the binary archives among the release files.

On the https://github.com/dgraph-io/dgraph/releases page, each release should have 4 files, 

    dgraph-darwin-amd64-v0.7.0.tar.gz
    dgraph-linux-amd64-v0.7.0.tar.gz
    Source code (zip)
    Source code (tar.gz)

When initially released, the 0.7.1 release did not include the `dgraph-OS-amd64-REL.tag.gz` files. They are now there. I got to try the Manual Installation (from source) a little earlier than I had planned, to get a copy of the 0.7.1 release.

I was not sure if there was a change in release procedures, i.e. to only release the source files, or if the binary files were missed from the release. As it now appears the binary files were missed, perhaps the process of creating the release could be automated in some way to avoid this. I haven't had a requirement to create a release on GitHub, so I have not researched the release process, to see if it can be done.

**Comment by manishrjain** [comment]
We actually release the binaries together, but had an issue due to which we had to retract the release, fix the problem and upload the binaries again. https://github.com/dgraph-io/dgraph/issues/429

**Comment by pawanrawal** [comment]
I am not sure if we can automate this more than what we have now. We should take care that we upload files for both the platforms for every release.

**Comment by pawanrawal** [comment]
The next action isn't very obvious here. The release happens infrequently enough that we don't need to spend time automating this beyond the tools we already have in place.
