### ISSUE TITLE
GraphQL interface missing implements usage 

### ISSUE THREAD

**Issue by rlancer** [dgraph-io/dgraph#4341]
## Documentation

https://graphql.dgraph.io/docs/schema/#Interfaces

Implements usage is missing in the example schema 

![image](https://user-images.githubusercontent.com/1339007/69917939-d821b300-1439-11ea-85c3-46b6c03b5aff.png)

Should be corrected to 

```graphql
interface Post {
    id: ID!
    text: String
    datePublished: DateTime
}

type Question implements Post {
    title: String!
}

type Comment {
    commentsOn: Post!
}
```

**Comment by MichaelJCompton** [comment]
Thanks for noticing.  

Fixed in the live docs.
