### ISSUE TITLE
Add informations to conflicting 1-to-1 insertions

### ISSUE THREAD

**Issue by emile-tawfik** [dgraph-io/dgraph#4348]
### What you wanted to do
Insert a single 1-to-1 associations between two nodes and hit an conflict error between uid values.
### What you actually did
Insert a single 1-to-1 associations between two nodes and hit an conflict error between uid values.
### Why that wasn't great, with examples
This is the error returned from dgraph:
```cannot add value with uid 12df1 to predicate mypredicate because one of the existing values does not match this uid, either delete the existing values first or modify the schema to 'mypredicate: [uid]'```
This message only shows the uid that we want to insert. It would be better if we could integrate the already inserted value and the uid of the node we are trying to modify in the error message.

**Comment by MichelDiz** [comment]
Duplicated of https://github.com/dgraph-io/dgraph/issues/4136

Read this topic to understand further. https://discuss.dgraph.io/t/unexpected-bahaviour-when-mutating-1-to-1-relations/5180

Cheers.
