### ISSUE TITLE
Does Dgraph Graphql have Ratel Support

### ISSUE THREAD

**Issue by mingsterism** [dgraph-io/dgraph#4369]
The issue tracker is not for questions.

If you have a question, please ask it on https://discuss.dgraph.io
Our Docs: https://docs.dgraph.io/
Slack Channel: https://slack.dgraph.io/

Hi, i load up ratel on `localhost:8000` and connect to dgraph graphql at `localhost:9000/graphql`
The server is working when using Insomnia playground, but I receive CORS error when loading on ratel. 

`Access to fetch at 'http://localhost:9000/graphql/mutate?commitNow=true' from origin http://localhost:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

any suggestions?

**Comment by harshil-goel** [comment]
Ratel is for GRPC client for Alpha. It isn't meant to be used for Graphql.
For Graphql, you would have to use playgrounds such as Insomnia or GraphIQL.
