### ISSUE TITLE
Documentation: no matter what I click, first subitem stays "active"

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/dgraph#4370]
## Documentation

There's no way to activate/highlight second or third subitem in the LHS menu, meaning that highlight isn't useful at all and often misleading

<img width="785" alt="Screen Shot 2019-12-06 at 7 20 31 PM" src="https://user-images.githubusercontent.com/769142/70342389-917af100-185d-11ea-8370-58eb0507e5e4.png">

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8457). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
