### ISSUE TITLE
[K8s / devops] Reviewing the liveness probe endpoint

### ISSUE THREAD

**Issue by hackintoshrao** [dgraph-io/dgraph#4383]
### What version of Dgraph are you using?
v1.1

The kubelet uses liveness probes to know when to restart a Container. 
For example, liveness probes could catch a deadlock, where an application is running, but unable to make progress. Restarting a Container in such a state can help to make the application more available despite bugs.

This is basically used to automate all the scenarios where an irresponsive database needs to restart.
But a wrong implementation would restart the pods when it's not necessary to do so.

It would be important to review it once and write a report on two things:

- Does the current liveness probe endpoint guarantee the detection of irresponsive database state?
- Review for any false positives.

**Comment by fristonio** [comment]
Currently, we have the readiness probe and liveness probes in our helm [configuration](https://sourcegraph.com/github.com/dgraph-io/dgraph/-/blob/dgraph/cmd/alpha/run.go#L392) for dgraph alpha. There is a probable bug in the liveness probe in the sense that when a node tries to apply the raft snapshot, it sets the health status to unhealthy([here](https://github.com/dgraph-io/dgraph/blob/master/worker/draft.go#L836)), if probed at this time, Kubernetes will restart the container which should not be the case as the container is running.

Looking at a few implementations including [cockroachdb](https://sourcegraph.com/github.com/cockroachdb/cockroach@9d69708/-/blob/pkg/server/status.go#L623:24) I think that for the liveness probe we can have a bare HTTP handler returning status 200, which can detect cases like freeze, deadlocks, etc in the server. For readiness probe, the current implementation looks good which takes into account the state DB is operating in. Being more aggressive in terms of readiness probe would mean we will have to integrate health checks deep into our source code and probably brainstorm on what we will consider a not ready state for Dgraph.
