### ISSUE TITLE
[K8s / Devops] Need to investigate OOMs of pods with setup done using Helm charts

### ISSUE THREAD

**Issue by prashant-shahi** [dgraph-io/dgraph#4384]
### What version of Dgraph are you using?
`master` and `v1.1.0`

### What is the hardware spec (RAM, OS)?

```
3 node GKE cluster
45 GB memory
```

### Steps to reproduce the issue (command/config used to run Dgraph).
Go to [contrib/config/kubernetes/helm](https://github.com/dgraph-io/dgraph/tree/master/contrib/config/kubernetes/helm).
```
cd contrib/config/kubernetes/helm
helm install my-release ./ --set alpha.service.type="LoadBalancer"
```

Use [JS Flock](https://github.com/dgraph-io/flock/tree/master/js) and point the endpoint to the Dgraph alpha load balancer IP.

### Expected behaviour and actual result.

OOMs of pods after a while of running the JS Flock app, multiple times.
There doesn't seem to be any limit set on the CPU or memory. It is worth looking into what is causing it.

**Comment by hackintoshrao** [comment]
@prashant-shahi : Can you add the monitoring metrics too?

**Comment by prashant-shahi** [comment]
@hackintoshrao Sure.

Here are some of the metrics from GKE dashboard.

![alpha-1](https://i.imgur.com/qP9masd.png)

![alpha-2](https://i.imgur.com/In6djpV.png)

![alpha-3](https://i.imgur.com/DtCq1mz.png)

I had also periodically collected memory profiles for the same. Do ping me if anyone needs it.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8805). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
