### ISSUE TITLE
[K8s / Devops] Add more configurables to Helm and publish the charts

### ISSUE THREAD

**Issue by hackintoshrao** [dgraph-io/dgraph#4386]
### What version of Dgraph are you using?
v1.1

Helm needs more options to configure the deployment, here is the list:

- [x] Configuration for anti-affinity between alphas and zero. This is required if the users want to schedule alphas and zeros on different nodes.

- [x] Configuration to set the cache size and remove the `lru_mb` option.

- [x] Publish the charts to the helm repo.

- [x] Configuration to enable Prometheus deployment, alerts, and scraping.
- [ ] Configuration for node taints. This is required if the users don't want to schedule any other pods on the nodes where the database servers are running.
- [ ] Configuration to set both the initial resources to be allocated and resource limits for both alphas and zeros.

**Comment by sleto-it** [comment]
@hackintoshrao  @prashant-shahi - see also https://github.com/dgraph-io/dgraph/issues/4616

**Comment by prashant-shahi** [comment]
@sleto-it I believe I can pick this task up. We can include this for the next sprint.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8806). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
