### ISSUE TITLE
Does it support chinese for full text search now?

### ISSUE THREAD

**Issue by heshuguo** [dgraph-io/dgraph#4429]
The issue tracker is not for questions.

If you have a question, please ask it on https://discuss.dgraph.io
Our Docs: https://docs.dgraph.io/
Slack Channel: https://slack.dgraph.io/

**Comment by danielmai** [comment]
Dgraph supports full-text search for Chinese: https://docs.dgraph.io/query-language/#full-text-search. Please try it out, and if you have any issues open a GitHub issue.
