### ISSUE TITLE
Expose badger's CompressionLevel option in Bulk loader

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/dgraph#4439]
Copied over from https://github.com/dgraph-io/badger/issues/1163

Badger supports configuring zstd compression level via options which has a huge impact on performance. Right now there is no way for the user to specify the compression level. It would be nice to have a way to set the compression level in bulk loader (maybe a flag?).

It would also make sense to expose the compression algorithm option.

**Comment by xiangzhao632** [comment]
@jarifibrahim Could you explain what benifits we can get from compression? disk space or query latency?
I haved read the blog about BadgerV2.0.0 which didn't talk about the benifits of compression。

**Comment by jarifibrahim** [comment]
The compression reduces the disk space.

**Comment by jarifibrahim** [comment]
@mangalaman93 @harshil-goel ^^

**Comment by jarifibrahim** [comment]
This has been fixed via https://github.com/dgraph-io/dgraph/pull/4669
