### ISSUE TITLE
Replace MD5 with "better" message digest, e.g. sha256

### ISSUE THREAD

**Issue by djhenderson** [dgraph-io/dgraph#446]
`MD5` has been or is being retired as the standard message digest for verifying file integrity.

The `SHA256` provides a longer and more cryptographicly secure message digest.

The suite of similar programs including `md5sum` and `sha256sum`  provide the same options and functionality so they are drop-in replacements for each other, at least in the Linux world.

On Darwin we may need to use `gmd5sum` and `gsha256sum` from ports.

**Comment by dmonay** [comment]
@manishrjain @djhenderson  I'd like to take this on.

**Comment by pawanrawal** [comment]
Hey @dmonay go fot it. Happy to accept a PR. 

The md5 sums are written while building the dgraph binaries which is in https://github.com/dgraph-io/dgraph/blob/master/build.sh and then they are read and verified as part of the `getdgraph.sh` script https://github.com/dgraph-io/website/blob/master/getdgraph.sh. Also note we had to use `md5sum` for Ubuntu and `md5` for Mac so see if you can find something which works on both the systems.
