### ISSUE TITLE
Generate command line reference docs using cobra/doc

### ISSUE THREAD

**Issue by fristonio** [dgraph-io/dgraph#4463]
## Documentation

We can make use of cobra automatic command line reference generation to generate cmdline docs for dgraph.
https://github.com/spf13/cobra/blob/master/doc/md_docs.md

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8808). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
