### ISSUE TITLE
Json paring error in web client

### ISSUE THREAD

**Issue by VictorNine** [dgraph-io/dgraph#4467]
### What version of Dgraph are you using?
Latest
Built at 2019-12-22T11:05:43.246Z
Commit: a8d7358
Commit Info: a8d7358 Sun Dec 22 13:02:31 2019 +0200 (HEAD -> master, origin/master, origin/HEAD)

Running in docker (standalone)

### Have you tried reproducing the issue with the latest release?
It's the latest

### What is the hardware spec (RAM, OS)?
Manjaro linux

### Steps to reproduce the issue (command/config used to run Dgraph).
Running a mutation with the json below in the web console throws an error

```
{
  set:[{
     test: "testing",
}
]
}
```
Error:
Error: t: while lexing { set:[{ test: "testing", } ] } at line 2 column 5: Unrecognized character inside mutation: U+003A ':'

### Expected behaviour and actual result.
Expected it to load the data

**Comment by MichelDiz** [comment]
The right syntax is

```JSON
{
  "set": [
   {"test": "testing"}
  ]
}
```
Ref: https://docs.dgraph.io/mutations/#json-mutation-format

Please, if you need support or do questions. Do it in https://discuss.dgraph.io/

Cheers.
