### ISSUE TITLE
[ACL] API for users's access info.

### ISSUE THREAD

**Issue by animesh2049** [dgraph-io/dgraph#4471]
User should have access to its own access info. Right now a user can't query its groups or its permissions.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8462). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
