### ISSUE TITLE
Docs: Move "Implementing a plugin" to a better place.

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#4486]
## Documentation

Ref: https://docs.dgraph.io/query-language/#implementing-a-plugin

This session should be in another, more technical area. Instead, it is at the end of a session that is about the `GraphQL+-` language. As plugins are not part of this language. I see no reason for this session to be in query-language. And is more helpful if it is more visible.

Cheers.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8463). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
