### ISSUE TITLE
Visit  http://10.254.0.80:8000/health return content: asset not found for path health

### ISSUE THREAD

**Issue by bqf9979** [dgraph-io/dgraph#4488]
### What version of Dgraph are you using?
answer: 1.1.1

### Have you tried reproducing the issue with the latest release?
answer:I've tried the previous version and the latest version will have this problem 

### What is the hardware spec (RAM, OS)?
answer: linux-amdx64

### Steps to reproduce the issue (command/config used to run Dgraph).
./dgraph zero --my=10.254.0.80:5080
./dgraph alpha --lru_mb=1024 --my=10.254.0.80:7080 --zero=10.254.0.80:5080
./dgraph-ratel

### Expected behaviour and actual result.
When I visit:
Http://10.254.0.80:8000 always shows that the connection is not available. I grabbed the packet and looked at it. I visited:
http://10.254.0.80:8000/health
The returned content is: asset not found for path health
In the official demo, the return value is a JSON string. I've tried many versions and configuration methods, but I still can't. what's wrong with my operation

**Comment by bqf9979** [comment]
![{F8F79414-EBAA-4C06-923C-DE7C346DE4C8}_20191231143526](https://user-images.githubusercontent.com/24972164/71612371-f3b7df00-2bda-11ea-9d27-c1d561135d24.jpg)

**Comment by Willem520** [comment]
health endpoint is for alpha node https://docs.dgraph.io/clients/#health-check-and-alpha-info

**Comment by bqf9979** [comment]
I understand what you mean, but my response is 404, no health path was found, I'm a stand-alone deployment

**Comment by bqf9979** [comment]
Thank you! I was negligent!
