### ISSUE TITLE
Feedback an incorrect address

### ISSUE THREAD

**Issue by bqf9979** [dgraph-io/dgraph#4492]
## Documentation
In the document, the client - > go says:
# Requires at least Go 1.11
export GO111MODULE=on
go get -u -v github.com/dgraph-io/dgo/v2
But this website does not exist, please update the document, thank you!

**Comment by bqf9979** [comment]
![2](https://user-images.githubusercontent.com/24972164/71638237-92a11180-2c95-11ea-8d39-6601561cbe29.jpg)

**Comment by bqf9979** [comment]
![2](https://user-images.githubusercontent.com/24972164/71638239-a8aed200-2c95-11ea-82a7-d99e717268b9.jpg)

**Comment by MichelDiz** [comment]
This address isn't a website. It is a command to install Dgo in a machine with Go lang env installed. This address is related to how a module is installed.

If you need to check the v2.x.x code you can use https://github.com/dgraph-io/dgo/tree/v2.1.0

Cheers.

**Comment by bqf9979** [comment]
![2](https://user-images.githubusercontent.com/24972164/71639972-8f6d4c00-2cbc-11ea-82c4-99b3cad75d22.jpg)
I know but you see,can't download it

**Comment by MichelDiz** [comment]
It is working fine on my side.
![Captura de Tela 2020-01-01 às 14 14 16](https://user-images.githubusercontent.com/6570955/71644043-0563ba00-2ca1-11ea-9d1f-ee76f165d907.png)

**Comment by bqf9979** [comment]
ok!thanks!
