### ISSUE TITLE
Support list type on facets

### ISSUE THREAD

**Issue by raxosiris** [dgraph-io/dgraph#4493]
## Experience Report
Facets are a useful way to add properties to an edge instead of a node. We'd like to make full use of them but turns out only a limited set of types are supported which hinders our use case.

### What you wanted to do
We wanted to contain the permission scopes (for example, for a particular slack channel) inside the user's relationship (edge) to that channel. 

### What you actually did
For now, we are storing permissions as a jsonstring formatted list. E.g. instead of ["channel:write:user", "channel:read"], we are storing  "\"channel:write:user\",\"channel:read\"" 

### Why that wasn't great, with examples
Making workarounds to store a more complex facet means that we have to manually parse the string into list format to send to our frontend.

### Any external references to support your case
Slack has a similar use case where they assign permission scopes per channel/per workspace.
https://api.slack.com/scopes

Ours is a bit more complex, involving payment scopes, task scopes etc.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8810). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
