### ISSUE TITLE
Support systemd service files creation on automatic download

### ISSUE THREAD

**Issue by ChStark** [dgraph-io/dgraph#4509]
### What you wanted to do
When I use the automatic downloader ( `curl https://get.dgraph.io -sSf | bash` ) I want it to generate the .service files on `/etc/systemd/system` to enable dgraph as an OS service

It would be great if the files also included the default parameters as a configuration example.

**Comment by PabloCastellano** [comment]
I'd like to give this issue a try.

Is [website-old](https://github.com/dgraph-io/website-old/) the repository for the bash script?

**Comment by ChStark** [comment]
@PabloCastellano it seems Is the website-old, but the naming doesn't make any sense @MichelDiz ?

**Comment by MichelDiz** [comment]
Not sure, Who can tell about this script is @danielmai

**Comment by MichelDiz** [comment]
Good news guys, now (or when the site build is complete) you can use the flag `--systemd` to install Dgraph in Linux distros via Systemd.

To request the systemd installation.
```
curl https://get.dgraph.io -sSf | bash -s -- --systemd
```
To request the systemd installation and accept the licence.
```
curl https://get.dgraph.io -sSf | bash -s -- -y --systemd
```

This will be closed when the PR 4710 be merged.

Cheers.
