### ISSUE TITLE
RDF vs Property Graph

### ISSUE THREAD

**Issue by jayachandra2128** [dgraph-io/dgraph#4515]
Hi,
Here https://neo4j.com/blog/rdf-triple-store-vs-labeled-property-graph-difference I see differences between RDF graph and LPG graph.
Does Dgraph support RDF based model?
I have built LPG based model using Dgraph. Am now interested to know how once can build Knowledge graph using RDF model? Do I have to define Types in RDF model as it is not required? How should schema be for RDF model?
Looking for your response asap. Thank you.

**Comment by MichelDiz** [comment]
This issue was closed due to a new issue with the same content in https://github.com/dgraph-io/dgraph/issues/4521.
