### ISSUE TITLE
Time To Live (TTL) on Predicates (Nodes & Relationships)

### ISSUE THREAD

**Issue by rahst12** [dgraph-io/dgraph#4516]
## Experience Report
I am currently ingesting a large continuous streaming data set.  The most recent data is the most important data.  The oldest - either by policy or by least importance needs to be aged-off.  Today, we use Neo4J Community Edition.  We perform a query to find nodes/relationships older than a specific date and then delete them.

Note: Feature requests are judged based on user experience and modeled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### What you wanted to do
After _x_ number of days, I want to age off data - without having to issue a query/mutation to find the data and remove it.

### What you actually did
Today, we use Neo4J Community Edition.  We perform a query to find nodes/relationships older than a specific date and then delete them.

### Why that wasn't great, with examples
N/A - the issues are with Neo4J - this is just a clear improvement over the Neo4J product that, while evaluating Dgraph is an obvious plus (especially because Badger has it).

### Any external references to support your case
https://discuss.dgraph.io/t/time-to-live-for-nodes-in-dgraph/2066
https://www.youtube.com/watch?v=VftmLgwk_cY

**Comment by MichelDiz** [comment]
Adding one more ref about this https://discuss.dgraph.io/t/time-to-live-for-nodes-etc-in-dgraph/6092

**Comment by lgalatin** [comment]
Specific edge level is hard, but node and predicate level can be done.

**Comment by damienburke** [comment]
Hey, just wanted to see if there is any update on this, as I will need to hand roll some custom ttl support otherwise. Thanks!

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8811). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
