### ISSUE TITLE
RDF vs Property Graph 

### ISSUE THREAD

**Issue by jayachandra2128** [dgraph-io/dgraph#4521]
Hi,
Here https://neo4j.com/blog/rdf-triple-store-vs-labeled-property-graph-difference I see differences between RDF graph and LPG graph.
Does Dgraph support RDF based model?
I have built LPG based model using Dgraph. Am now interested to know how once can build Knowledge graph using RDF model? Do I have to define Types in RDF model as it is not required? How should schema be for RDF model?
Looking for your response asap. Thank you.

**Comment by MichelDiz** [comment]
Dgraph have its own RDF type. And it is not compatible with other RDF's standards with varied features (and fancy ones). Dgraph's RDF is simple and straightforward. Triples + facets. Nothing else.

A knowledge graph is just a rich information graph edge-oriented. Any Graph DB you can build one. If there is a standard about it wouldn't be hard to make it work in Dgraph.

>Do I have to define Types in RDF model as it is not required? 

Types in RDF are optional but it is good for the parser you define it.

>How should schema be for RDF model?

I'm not sure what you mean. Can you be more specific? maybe give me some references.

Cheers.
