### ISSUE TITLE
Dgraph live doesn't work with Multi-Host with Docker Swarm default install

### ISSUE THREAD

**Issue by rahst12** [dgraph-io/dgraph#4527]
### What version of Dgraph are you using?
1.1.1

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
t2.micro, and Ubuntu

### Steps to reproduce the issue (command/config used to run Dgraph).
Follow the Dgraph steps to install Multi-host with Docker Swarm.

Does not work with Dgraph live:  docker-machine create --driver amazonec2 aws01   
Does work with Dgraph live: docker-machine create --driver amazonec2 --amazonec2-instance-type t2.medium --amazonec2-ami ami-02eac2c0129f6376b --amazonec2-ssh-user centos aws01  
The former uses the defaults - a t2.micro and ubuntuThe later uses a t2.medium and centos 

dgraph live -f 1million.rdf.gz --alpha 172.31.82.252:9080 --zero 172.31.82.252:5080 --schema ./1million.schema --verbose

The above command would hang when processing the schema file.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8465). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
