### ISSUE TITLE
Can't use goclient without ICU installed because tok is a dependency.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#453]
Get error

```
# github.com/dgraph-io/dgraph/tok
In file included from ../github.com/dgraph-io/dgraph/tok/tok.go:21:
./icuc.h:22:10: fatal error: 'unicode/ustring.h' file not found
#include <unicode/ustring.h>
``` 

while trying to build a project which uses goclient

**Comment by manishrjain** [comment]
https://github.com/dgraph-io/dgraph/commit/952af7f9ba293502198c08c441c34fbf5f164bde fixes it. Though, we should reconsider having tok as a dep in the types package. Is that the right place for it, @jchiu0?
