### ISSUE TITLE
Make sure pprof is installed in teamcity instances.

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/dgraph#4533]
Sometimes the posting list size tests fail because pprof is not installed in the team city agent. There should probably be a build step to install it as part of the test setup.

**Comment by danielmai** [comment]
Why do we need `pprof`? `go tool pprof` exists already.

**Comment by martinmr** [comment]
I guess the script should invoke `go tool pprof` instead. Let me see if that works.

**Comment by martinmr** [comment]
Fixed by #4536
