### ISSUE TITLE
Data types in Dgraph: Add a password type

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#454]
So, any string corresponding to this type would be salted and stored encrypted (bcrypt library might be a good choice, but needs investigation). This would be useful to store passwords in Dgraph.

We'll also need corresponding functions to check if the password specified is correct or not; without retrieving the encrypted password. Also, we shouldn't allow retrieving of this predicate by query. It should only be done via backup.

**Comment by gpsamson** [comment]
Is this improvement intended to be used by an application (customers) or by administrators and developers? If it's the latter, API keys would make more sense.

**Comment by manishrjain** [comment]
This is just for storage; so one could potentially do user authentication via Dgraph. This isn't really about client authentication with Dgraph itself. Agreed that the latter could be handled via API keys.

**Comment by squalfof** [comment]
List some use cases:
1. user set password

- if not the first time then he should provide previous password as well: 
    => left for user dev to deal with previous verify or, 
    => Dgraph provide on api to do both verify-and-set ?

- what syntax should it take ? 
    => via the normal form like "user password i-m-password", then inner component take special treatment on predicate 'password'
    => via special form like "user password i-m-password password@label", then inner component take special treatment on label-password

2. password verification

-  what syntax should it take ? how about taking advantage of filter-eq,
user(allof(user-name, "admin")) @filter(eq("password", "i-m-password")) {}
