### ISSUE TITLE
Dgraph process gets killed

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#455]
On Gru, Dgraph process gets killed because it takes up too much memory. This is after setting `stw_ram_mb` to 1000. Dgraph runs fine for sometime (3-4 days) and then gets killed. The machine has 4 GB RAM and other processes don't take up much memory. Could we free up some memory regularly? Or add some logs for the amount of memory being consumed by what?

I am attaching logs for `/var/log/kern.log` for reference.
[Logs.txt](https://github.com/dgraph-io/dgraph/files/692544/Logs.txt)

**Comment by manishrjain** [comment]
This is most likely a leak in Cgo. We already know about it. So, not sure what can we do here.

**Comment by manishrjain** [comment]
FWIW, I think we should use an 8GB instance.
