### ISSUE TITLE
TestDebugSupport is flaky in TeamCity.

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/dgraph#4560]
### What version of Dgraph are you using?
master

### Have you tried reproducing the issue with the latest release?
yes

### Steps to reproduce the issue (command/config used to run Dgraph).
Test is flaky. Example.

https://teamcity.dgraph.io/viewLog.html?buildId=39268&tab=buildResultsDiv&buildTypeId=Dgraph_CiDefaultTestCluster

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8468). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
