### ISSUE TITLE
error message could be more informative

### ISSUE THREAD

**Issue by dapperAuteur** [dgraph-io/dgraph#4562]
### What version of Dgraph are you using?
1.1.1
### Have you tried reproducing the issue with the latest release?
yes

### What is the hardware spec (RAM, OS)?
8 GB
os 10.15.2

### Steps to reproduce the issue (command/config used to run Dgraph).
ran mutation 
`{
	"set": [{
			"uid": < 0x3 > ,
			"inhabits": {
				"uid": "0x2711"
			}
		},
		{
			"uid": < 0x4 > ,
			"inhabits": {
				"uid": "0x2711"
			}
		}
	]
}
`

### Expected behaviour and actual result.
tell me which line the error is on and what's causing the error

**Comment by MichelDiz** [comment]
You are using angular brackets in a JSON file.  Change `< 0x3 >` and `< 0x4 >` to  `"0x3", "0x4"` and you are good to go.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8469). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
