### ISSUE TITLE
Blockade test is flaky

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#4570]
### What version of Dgraph are you using?

master

### Have you tried reproducing the issue with the latest release?

yes

### Steps to reproduce the issue (command/config used to run Dgraph).

This happens randomly for e.g. https://teamcity.dgraph.io/viewLog.html?buildId=39612&buildTypeId=Dgraph_Blockade

The error is as follows

```
[16:53:45] [Step 4/5] Error:
[16:53:45] [Step 4/5] No embargo exists in this context
```

The same test passed on a re-run without any code change. See https://teamcity.dgraph.io/viewLog.html?buildId=39614&

### Expected behaviour and actual result.

The test should only fail when there is an actual failure.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8470). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
