### ISSUE TITLE
Test UpsertWithValueVar is flaky

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#4571]
### What version of Dgraph are you using?

master

### Have you tried reproducing the issue with the latest release?

yes

### Steps to reproduce the issue (command/config used to run Dgraph).

This test failed without any related change https://teamcity.dgraph.io/viewLog.html?buildId=39620&buildTypeId=Dgraph_Ci&tab=buildResultsDiv

### Expected behaviour and actual result.

It should not be flaky

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8471). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
