### ISSUE TITLE
Dgraph doesn't respond when a query contains syntax error

### ISSUE THREAD

**Issue by gpsamson** [dgraph-io/dgraph#458]
This mutation that has mismatched single and double quotes causes Dgraph to get stuck and not respond with a SyntaxError.
```
mutation {
  set {
	_:gabe <name> "Gabe' .
	_:gabe <username> "gpsamson" .
  }
}
```

**Comment by gpsamson** [comment]
I must have been staring at it too long. The mutation is failing because the mismatched single and double quotes. 

The mutation works after that simple fix, but it brings up another issue - syntax errors.

**Comment by manishrjain** [comment]
@ashwin95r -- This doesn't get fixed even with your refactoring. I pulled it into my PR, but still hangs on this query. My PR is here: https://github.com/dgraph-io/dgraph/pull/462

**Comment by manishrjain** [comment]
Okay. My PR now fixes this issue. Just waiting for review, and then will submit.

**Comment by manishrjain** [comment]
The PR is now submitted. Dgraph would no longer get stuck, and respond with a query parsing error. To use this feature, you will have to build Dgraph manually, until the next release.
