### ISSUE TITLE
[v1.2.0-rc1] alpha fails to connect to zero: ] Connection lost with 127.0.0.1:5080. Error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure,

### ISSUE THREAD

**Issue by marvin-hansen** [dgraph-io/dgraph#4580]
### What version of Dgraph are you using?

Dgraph version   : v1.2.0-rc1
Dgraph SHA-256   : b0087ce7f8987e1d565c9c9097451d86c2c40b97c90bd7c6a7a1f300ef660c4d
Commit SHA-1     : 1b8347201
Commit timestamp : 2020-01-15 01:36:25 +0530
Branch           : HEAD
Go version       : go1.13.5

Docker image from [Dockerhub](https://hub.docker.com/layers/dgraph/dgraph/v1.2.0-rc1/images/sha256-a082260732034e97c2b6ea106846a0d4eda3e20ee08e499d4db23596695ccc2e) 

### Have you tried reproducing the issue with the latest release?

Yes, I tried the master branch with the commit from Jan/14 and it yields the same problem.  (1b8347201afce7dd5c1948eea7350cd5c40dc819) 

The previous release 1.1 is unaffected. 

### What is the hardware spec (RAM, OS)?

HP Spectre, i7, 16GB memory 

GKE / Kubernetes 4 vCPU / 8 GB memory  

### Steps to reproduce the issue (command/config used to run Dgraph).

1) Start Zero:

>docker run -it -p 5080:5080 -p 6080:6080 -v zero:/dgraph dgraph/dgraph:v1.2.0-rc1 dgraph zero --my=localhost:5080

2) Start Alpha 

> docker run -it -p 7080:7080 -p 8080:8080 -p 9080:9080 -v server1:/dgraph dgraph/dgraph:v1.2.0-rc1  dgraph alpha --lru_mb=1024 --zero=127.0.0.1:5080 --my=127.0.0.1:7080

>docker run -it -p 7081:7081 -p 8081:8081 -p 9081:9081 -v server2:/dgraph dgraph/dgraph:v1.2.0-rc1 dgraph alpha --lru_mb=1024 --zero=127.0.0.1:5080 --my=127.0.0.1:7081

3) Start Ratel:
>docker run -it -p 8000:8000 dgraph/dgraph:v1.2.0-rc1 dgraph-ratel

### Expected behavior

Alpha nodes should connect to running zero instance 

### Actual result 

> CONNECTING to 127.0.0.1:5080
> W0115 11:54:01.821226       1 pool.go:254] Connection lost with 127.0.0.1:5080. Error: rpc error: 
> code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection > error: desc = "transport: Error while dialing dial tcp 127.0.0.1:5080: connect: connection refused"

Detailed log attached!

[alpha.log](https://github.com/dgraph-io/dgraph/files/4064761/alpha.log)
[zero.log](https://github.com/dgraph-io/dgraph/files/4064762/zero.log)

**Comment by marvin-hansen** [comment]
@lolcoolkat I had the exact same issue in Kubernetes. Afaik, there is no fix right now, not even in the master branch, so you have to revert to any prior version to avoid the issue.

**Comment by danielmai** [comment]
@marvin-hansen @lolcoolkat Regarding the K8s config, there are K8s config changes in the current master regarding liveness and readiness probes that don't apply to the latest Dgraph release (v1.1.1). Please use the v1.1.1 K8s configs: https://github.com/dgraph-io/dgraph/blob/v1.1.1/contrib/config/kubernetes/dgraph-ha/dgraph-ha.yaml.

**Comment by danielmai** [comment]
@marvin-hansen The three `docker run` commands creates three separate Docker containers that are not connected to each other on a shared network, so communication over `127.0.0.1` doesn't work. 

You'll need to network them together to get it working. You can try the sample Docker Compose config which will create a shared network among the different containers defined in the docker-compose.yml: https://github.com/dgraph-io/dgraph/blob/master/contrib/config/docker/docker-compose.yml. You can update the image tag to try v1.2.0-rc1.

**Comment by marvin-hansen** [comment]
@danielmai Thank you for the hint.

The docker-compose kinda works with  v1.2.0-rc1. However, when I try to deploy a GraphQL schema to the admin endpoint, exactly as shown in the [GraphQL tutorial](GraphQL tutorial), I get an unauthorized error: 

> jq -n --arg schema "$(cat schema.graphql)" '{ query: "mutation updateGQLSchema($sch: String!) { updateGQLSchema(input: { set: { schema: $sch }}) { gqlSchema { schema } } }", variables: { sch: $schema }}' | curl -X POST -H "Content-Type: application/json" http://localhost:8080/admin -d @- | jq -r

```
 {
   "errors": [
     {
       "message": "Request from IP: 172.18.0.1",
       "extensions": {
         "code": "ErrorUnauthorized"
       }
     }
   ]
 }
$:/mnt/c/Users/marvi/PycharmProjects/goci-dgraph$
```

**Comment by marvin-hansen** [comment]
@danielmai  is there an update for the single k8s config planned? 

Out of curiosity, are the helm-charts already been tested for the 1.2X release?  

> @marvin-hansen @lolcoolkat Regarding the K8s config, there are K8s config changes in the current master regarding liveness and readiness probes that don't apply to the latest Dgraph release (v1.1.1). Please use the v1.1.1 K8s configs: https://github.com/dgraph-io/dgraph/blob/v1.1.1/contrib/config/kubernetes/dgraph-ha/dgraph-ha.yaml.

**Comment by MichelDiz** [comment]
This ip 172.18.0.1 is from the docker network context. To run any admin operation, you need to "docker exec" into that container. Or set a whitelist https://docs.dgraph.io/deploy/#whitelist-admin-operations

**Comment by danielmai** [comment]
> Out of curiosity, are the helm-charts already been tested for the 1.2X release?
> 
> >

We'll update the master branch K8s configs today. For now, you can use the configs in the v1.1.1 branch.

**Comment by MichelDiz** [comment]
As Dmai said, The problem is that Docker does not know how to handle connections between containers. The correct way to do it follows below. It's more complicated and longer typing than choosing the easiest way that is go with docker-compose.

I will close this issue because the problem is related to how Docker works and not Dgraph - But if need any further clarification, feel free to ping me or Dmai. 

There is another problem with this release, but it was already fixed in a recent commit that is on its way to being merged with Master.

Cheers

Create a network
```
docker network create dgraph_default
```
Run the containers:
```
docker run -it \
-p 5080:5080 \
-p 6080:6080 \
 -v zero:/dgraph \
--name zero \
--network dgraph_default \
dgraph/dgraph:v1.2.0-rc1 dgraph zero --my=zero:5080
```
```
docker run -it \
-p 7080:7080 \
-p 8080:8080 \
-p 9080:9080 \
-v server0:/dgraph \
--network dgraph_default \
--name alpha0 \
dgraph/dgraph:v1.2.0-rc1 \
dgraph alpha --lru_mb=1024 --zero=zero:5080 --my=alpha0:7080
```

> If any container fails giving an error/panic restart it by doing
> docker ps -a
> `docker rm 7488469a8fea ` 7488469a8fea is the ID of the failed container. Then use the same command used for it.

```
docker run -it \
-p 7081:7081 \
-p 8081:8081 \
-p 9081:9081 \
-v server1:/dgraph \
--network dgraph_default \
--name alpha1 \
dgraph/dgraph:v1.2.0-rc1 \
dgraph alpha --lru_mb=1024 --zero=zero:5080 --my=alpha1:7081 -o=1
```
```
docker run -it \
-p 8000:8000 \
--network dgraph_default \
--name ratel \
dgraph/dgraph:v1.2.0-rc1 \
dgraph-ratel
```
docker network connect zero alpha0

docker network connect zero alpha1

To retry do this steps:

Stop and Remove ALL containers running in Docker
```
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q) 
```

delete the volumes
```
docker volume rm server1 server2 zero
```
or
```
docker volume rm $(docker volume ls) 
```

Now go to:
```
http://${ localhost or vm IP}:8000/?latest
http://192.168.99.100:8000/?latest
```
Enter the url `http://${ localhost or vm IP}:8080/`

**Comment by marvin-hansen** [comment]
> We'll update the master branch K8s configs today. For now, you can use the configs in the v1.1.1 branch.

@danielmai  please add some bare minimum security to the k8s config. I opened another issue related to the security problems I found in the default config: 

https://github.com/dgraph-io/dgraph/issues/

There is an example with DGraph & ngnix as a proxy in front of DGraph. So technically, one can configure ngnix for authentication and I think it is the most sensible approach for the time being:

https://gist.github.com/MichelDiz/42954e321620159c872c35c20e9d85c6

https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
