### ISSUE TITLE
JSON mutation, Support facets for value edge lists

### ISSUE THREAD

**Issue by emile-tawfik** [dgraph-io/dgraph#4581]
Hi,

This issue follows this one #4081 and this PR #4267.

#4267 changes the output format, but does not reflect thoses changes for the input JSON mutation format.

This cause 2 issues:
- The JSON input and output are not permutable
- This impossibility to add facets to a value edge lists

I think the JSON mutation format should be modified accordingly to the output format.

Below are some examples of the modified JSON input : (coming from https://github.com/dgraph-io/dgraph/issues/4081#issuecomment-542837855)

## Facets on a singular value predicate
Schema:
```rdf
<name>: string .
```
Old-Data:
```json
{
    "name|kind": "first",
    "name": "Francesc"
}
```
Data:
```json
{
    "name|kind": "first",
    "name": "Francesc"
}
```
Query:
```graphql
{
   q(func: has(name)) {
      name @facets
   }
}
```
Result:
```json
{
  "data": {
    "q": [
      {
        "name|kind": "first",
        "name": "Francesc"
      }
    ]
  }
}
```

## Facets on lists of value predicates
Schema:
```rdf
<nickname>: [string] .
```
Old-Data:
```json
Impossible to write
```
Data:
```json
{
    "nickname": [
      "Cesc",
      "Francesc",
      "Tete"
    ],
    "nickname|kind": {
      "0": "friends",
      "1": "official"
    }
}
```
Query:
```graphql
{
   q(func: has(nickname)) {
      nickname @facets
   }
}
```
Result:
```json
{
  "data": {
    "q": [
      {
        "nickname": [
          "Cesc",
          "Francesc",
          "Tete"
        ],
        "nickname|kind": {
          "0": "friends",
          "1": "official"
        }
      }
    ]
  }
}
```

## Facets on a singular object predicate
Schema:
```rdf
<name>: string .
<state>: uid .
```
Old-Data:
```json
{
    "name": "San Francisco",
    "state": [
        {
            "name": "California",
            "state|capital": false
        }
    ]
}
```
Data:
```json
{
    "name": "San Francisco",
    "state": [
      {
        "name": "California"
      },
      "state|capital": false
    ]
}
```
Query:
```graphql
{
   q(func: has(state)) {
      name
      state @facets {
         name
      }
   }
}
```
Result:
```json
{
  "data": {
    "q": [
      {
        "name": "San Francisco",
        "state": [
          {
            "name": "California"
          },
          "state|capital": false
        ]
      }
    ]
  }
}
```

## Facets on a list of object predicates
Schema:
```rdf
<name>: string .
<speaks>: [uid] .
```
Old-Data:
```json
{
    "name": "Francesc",
    "speaks": [
      {
        "name": "Spanish",
        "speaks|fluent": true
      },
      {
        "name": "Chinese"
        "speaks|fluent": false
      }
    ]
}
```
Data:
```json
{
    "name": "Francesc",
    "speaks": [
      {
        "name": "Spanish"
      },
      {
        "name": "Chinese"
      }
    ],
    "speaks|fluent": {
       "0": true,
       "1": false
    }
}
```
Query:
```graphql
{
   q(func: has(state)) {
      name
      state @facets {
         name
      }
   }
}
```
Result:
```json
{
  "data": {
    "q": [
      {
        "name": "Francesc",
        "speaks": [
          {
            "name": "Spanish"
          },
          {
            "name": "Chinese"
          }
        ],
        "speaks|fluent": {
           "0": true,
           "1": false
        }
      }
    ]
  }
}
```

**Comment by MichelDiz** [comment]
The old way of doing facets between edges still works. So there are no changes to it. Just in the List Type.

For list-type facets I think it is pretty okay to be like this:
> I will document this.
```graphql
{
   q(func: has(nickname)) @filter(eq(name,"Julian")) {
      nickname @facets
   }
}
```
Result:

```JSON
{
    "q": [
      {
        "nickname|kind": {
          "0": "first",
          "1": "official",
          "2": "CS-GO"
        },
        "nickname": [
          "Jay-Jay",
          "Jules",
          "JB"
        ]
      }
    ]
  }
```
The JSON mutation executed
```JSON
{
  "set": [
    {
      "uid": "_:Julian",
      "name": "Julian",
      "nickname|kind": "first",
      "nickname": "Jay-Jay"
    },
    {
      "uid": "_:Julian",
      "nickname|kind": "official",
      "nickname": "Jules"
    },
    {
      "uid": "_:Julian",
      "nickname|kind": "CS-GO",
      "nickname": "JB"
    }
  ]
}
```

In RDF

```RDF
{
  set {
    _:Blank <nickname> "Cesc" (kind="friends") .
    _:Blank <nickname> "Francesc" (kind="official") .
    _:Blank <nickname> "Tete" .
  }
}
```

**Comment by MichelDiz** [comment]
Docs added, waiting for review. https://github.com/dgraph-io/dgraph/pull/4582

**Comment by emile-tawfik** [comment]
I haven't thought about reusing the same blanknode multiple times.

Concerning the benefits of the JSON mutation format in the docs (Source: https://docs.dgraph.io/mutations/#json-mutation-format)

> It also eliminates the need for apps to have custom serialisation code

This is not true because, at least for edge value lists, the serialization/deserialization format aren't the same.

**Comment by hackintoshrao** [comment]
Hey @emile-tawfik ,

Thanks for reporting this issue, only an avid Dgraph user could notice such tricky inconsistencies :)
Yes, I agree that least for edge value lists, the serialization/deserialization format aren't the same., this is an issue for sure, we'll take this up further and propose a solution.

**Comment by ashish-goswami** [comment]
Hi all, we have discussed facets format internally and prepared one document with different possible formats. Please checks below discuss post and provide your feedback.
https://discuss.dgraph.io/t/facets-format-in-mutation-requests-and-query-responses/6416

**Comment by lgalatin** [comment]
Fixed in https://github.com/dgraph-io/dgraph/pull/5424
