### ISSUE TITLE
Split predicates into multiple groups

### ISSUE THREAD

**Issue by rahst12** [dgraph-io/dgraph#4585]
## Experience Report
A given predicate always belongs to same group, i.e will always go same node (and its replicas)
So this node/server will eventually fill-up and there is no way to horizontally scale the storage.

![image](https://user-images.githubusercontent.com/4392617/72490309-edce1a80-37e4-11ea-9777-8a19c90787c6.png)

Note: Feature requests are judged based on user experience and modeled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### Any external references to support your case
https://discuss.dgraph.io/t/splitting-predicates-into-multiple-groups/5771

**Comment by MichelDiz** [comment]
Hey @rahst12, this was accepted but it was already in the 2020 roadmap as the name “Single predicate sharded across groups (TBD)”.

Cheers.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8818). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
