### ISSUE TITLE
Docker Swarm Install Improvements

### ISSUE THREAD

**Issue by rahst12** [dgraph-io/dgraph#4587]
## Documentation
https://docs.dgraph.io/deploy/#using-docker-swarm

I followed the Docker Swarm install instructions, and hit a couple issues.

1. A t2.micro only has 1GB of RAM.  The docker-compose.yml file sets the --lru_mb=2048 - twice that of the ram available.
2. A t2.micro continually failed to ingest the 1 mil, 78MB data set using the dgraph live loader.
```
wget "https://github.com/dgraph-io/tutorial/blob/master/resources/1million.rdf.gz?raw=true" -O 1million.rdf.gz -q
wget "https://raw.githubusercontent.com/dgraph-io/benchmarks/master/data/1million.schema" -O 1million.schema -q
```

I had to change the instance type to a --amazonec2-instance-type t2.medium to get that ingested.

**Comment by marvin-hansen** [comment]
@rahst12 There is a bug that allows setting lru_mb higher than the actual RAM available and it is known that it can cause crashes. See the linked issue below for details. 

The best you can do is to configure memory carefully and ensure you have >2GB available. 

https://github.com/dgraph-io/dgraph/issues/4555

**Comment by sleto-it** [comment]
Hi @rahst12,

Many thanks for reporting this. I agree that the documentation page requires an update

**Comment by danielmai** [comment]
Docker Swarm Install documentation has been updated in https://github.com/dgraph-io/dgraph/pull/5112.
