### ISSUE TITLE
Update with sixth tutorial link

### ISSUE THREAD

**Issue by enzotar** [dgraph-io/dgraph#4599]
* Doc page: [get-started/index.md](https://docs.dgraph.io/get-started/)
* Doc version: `release/v1.1.1`

**Comment by MichelDiz** [comment]
The link is already in master. https://docs.dgraph.io/master/get-started/
These docs changes were created after the cut release. Which means it won't go to v1.1.1 as far as I can tell. Unless @danielmai  cherry-pick it to v1.1.1.

**Comment by prashant-shahi** [comment]
6th tutorial has been added to the docs latest docs (`v1.1.1`)
