### ISSUE TITLE
Support DQL variables in mutations

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#4615]
### What you wanted to do
I want to perform a mutation in an upsert block using user-provided data safely.

### What you actually did
```
upsert ($name: string){
      query {
        var(func: eq(xid, "http://schema.org/Person")) {
          Type as uid
        }
        var(func: eq(<http://schema.org/name>, "Robin Wright")) {
          Person as uid
        }
      }
      mutation {
          set {
           uid(Person) <xid> "https://www.themoviedb.org/person/32-robin-wright" .
           uid(Person) <http://schema.org/type> uid(Type) .
           uid(Person) <http://schema.org/name> $name .
           uid(Person) <dgraph.type> "Person" .
          }
      }
    }
```

### Why that wasn't great, with examples
GraphQL variables are not supported in mutations, so it's impossible to safely mutate user-provided data without error-prone validation.

### Any external references to support your case
None at the moment.

**Comment by miko** [comment]
I also support this request. The rationale is the same as for GraphQL variables in queries: https://docs.dgraph.io/query-language/#graphql-variables

**Comment by MichaelJCompton** [comment]
This looks like a reasonable feature request.

I'm tagging it as accepted, which means it will get into our backlog of features to consider.  

If we decide to implement it, we'll post an update here.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8819). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
