### ISSUE TITLE
Add ingress support to Helm chart

### ISSUE THREAD

**Issue by marvin-hansen** [dgraph-io/dgraph#4616]
**[SOLVED]** I ended up adding a custom [Kong](https://konghq.com/products/kong-enterprise/kong-kubernetes/?itm_source=website&itm_medium=nav) ingress [controller ](https://itnext.io/kong-gateway-in-kubernetes-ad86981f93a5) with central routing, end to end connection encryption & http based authentication. 

## Experience Report

Essentially, I wanted to add secure remote access to Dgraph deployed in a GKE cluster. 

### What you wanted to do

Authentication & httpS connection encryption because it's not there. 

### What you actually did

Still working around this crap. NGNIX reverse proxy has largely been replaced with ingress controller in k8s, but no ingress is there in the deployment yaml nor the helm chart. 

### Why that wasn't great, with examples

It's not solved. 

### What would be truly great. 

Add ingress support because it allows out of the box http authentication, https encription, and proper routing. Essentially, it enables everything that is missing right now. 

### Any external references to support your case

Here is a walkthrough for authentication for another helm-chart that supports ingress controller. Adding authentication, encryption & routing is a piece of cake:

https://docs.bitnami.com/kubernetes/how-to/secure-kubernetes-services-with-ingress-tls-letsencrypt/

Documentation 
http://kubernetes.io/docs/user-guide/ingress/

Ingress explained. 
https://codeburst.io/kubernetes-ingress-simply-visually-explained-d9cad44e4419

Example values for ingress support.
https://github.com/helm/charts/blob/master/stable/joomla/values.yaml

**Comment by darkn3rd** [comment]
This has recently Implemented ingress for ratel and alpha (http/s) in https://github.com/dgraph-io/charts/.

We tested this on `ingress-nginx` (GCLB, ELB), `aws-alb-ingress-controller`, and GKE default `gce` and tested annotations for integration with AWS ACM or Kubernetes Cert Manager (ACME with HTTP01 challenge) and ExternalDNS with CloudDNS and Route53.
