### ISSUE TITLE
delete S * * pattern fails when strict mutations enabled

### ISSUE THREAD

**Issue by Fantastitech** [dgraph-io/dgraph#4617]
### What version of Dgraph are you using?

1.1.1

### Steps to reproduce the issue (command/config used to run Dgraph)

One Dgraph Zero, Alpha, and Ratel instance running inside an LXD container without docker. Alpha running with `--lru_mb=4096 --mutations strict`. Zero and Ratel running with no configs.

### Expected behaviour and actual result.

When sending the following delete mutation for a node with the --mutations strict flag enabled:

```
{
	delete {
		<0x68> * * .
	}
}
```

...the Dgraph server returns various type errors:

```
Error: t: Schema not defined for predicate: dgraph.group.acl.
Error: t: Schema not defined for predicate: dgraph.xid.
Error: t: Schema not defined for predicate: dgraph.password.
Error: t: Schema not defined for predicate: dgraph.user.group.
```

Only one error is returned each time. Which error comes up is random but the xid predicate error seems to be the most common. It appears Dgraph is attempting to delete internal edges that are causing failures due to type checking on my schema which doesn't include them for obvious reasons.

**Comment by ashish-goswami** [comment]
Hey @Fantastitech, looks like this has been fixed by https://github.com/dgraph-io/dgraph/pull/4656.

Can you verify it on master/latest release?

**Comment by emile-tawfik** [comment]
I hit seem that content of  the commit https://github.com/dgraph-io/dgraph/pull/4656/commits/86380a460578637659c9119d5a78fef220d79173 is not on master.

**Comment by ashish-goswami** [comment]
@emile-tawfik, my bad. Will check with the team.

**Comment by ashish-goswami** [comment]
Hey @emile-tawfik, this has been fixed in master. I don't see any error while performing above
delete mutation. I am closing this issue for now. Feel free to reopen, if you are still seeing this.
