### ISSUE TITLE
[K8/Devops] Issue with the Dgraph-ha config in the v1.2.0-rc1 release

### ISSUE THREAD

**Issue by hackintoshrao** [dgraph-io/dgraph#4627]
### What version of Dgraph are you using?
 v1.12 rc1 release

### Have you tried reproducing the issue with the latest release?
Yes, the configs here https://github.com/dgraph-io/dgraph/commit/aec19d53ff856befab2ee22e2ebb4d8fc094ec4b , fails with the last v1.1 release too.;

### What is the hardware spec (RAM, OS)?
K8's GKE, default nodes

### Steps to reproduce the issue (command/config used to run Dgraph).
Just install using the script here https://github.com/dgraph-io/dgraph/commit/aec19d53ff856befab2ee22e2ebb4d8fc094ec4b

### Expected behaviour and actual result.
Successfully install Dgraph

@prashant-shahi is investigating this further and meanwhile, he'll roll back the configs.

**Comment by marvin-hansen** [comment]
@hackintoshrao try the Helm charts from master.

You can set the version tag to deploy any specific release you want

https://docs.dgraph.io/master/deploy/#ha-cluster-setup-using-kubernetes

The chart worked about two days ago and, indeed, deployed DGraph HA although one can argue some configuration details.

**Comment by prashant-shahi** [comment]
@hackintoshrao There was some issue with liveness and readiness probes. For now, reverting the addition resolves it. We need to invest more time on this issue. It could be related to recent changes in `/health` and `/state` endpoints.

@marvin-hansen The Helm charts worked because by default it doesn't enable the liveness and readiness probes.

**Comment by marvin-hansen** [comment]
@prashant-shahi 

Yes, the k8s deployment files need more work and polishing. However, as you look into this, please consider adding proper [ingress support ](https://github.com/dgraph-io/dgraph/issues/4616)because that's really very much needed.

**Comment by prashant-shahi** [comment]
Thanks, @marvin-hansen for the feedback. Your enhancement request has been accepted.
