### ISSUE TITLE
Alpha 1.2.0-rc1 panics

### ISSUE THREAD

**Issue by emicklei** [dgraph-io/dgraph#4628]
### What version of Dgraph are you using?
1.2.0-rc1

### Have you tried reproducing the issue with the latest release?
No

### What is the hardware spec (RAM, OS)?
GKE using n1-standard-1 machine type. Linux

### Steps to reproduce the issue (command/config used to run Dgraph).
I lack the knowledge to reproduce this

### Expected behaviour and actual result.
Handle the nil value in the code.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1404dd1]

goroutine 73 [running]:
github.com/dgraph-io/dgraph/worker.(*groupi).AnyTwoServers(0x0, 0x1, 0x0, 0x0, 0x0)
	/tmp/go/src/github.com/dgraph-io/dgraph/worker/groups.go:497 +0x51
github.com/dgraph-io/dgraph/worker.SubscribeForUpdates(0xc02b320d60, 0x1, 0x1, 0xc02c562e70, 0x1)
	/tmp/go/src/github.com/dgraph-io/dgraph/worker/groups.go:1048 +0x4a
created by github.com/dgraph-io/dgraph/graphql/admin.newAdminResolver
	/tmp/go/src/github.com/dgraph-io/dgraph/graphql/admin/admin.go:181 +0x285
```

**Comment by MichelDiz** [comment]
I'm not sure, but someone was working on this problem.

**Comment by ashish-goswami** [comment]
Hey @emicklei @MichelDiz , this should be fixed by https://github.com/dgraph-io/dgraph/pull/4626.
