### ISSUE TITLE
Full-text tokenizer can't deal with apostrophe

### ISSUE THREAD

**Issue by Kubera2017** [dgraph-io/dgraph#4633]
### What version of Dgraph are you using?
1.1.1

### Have you tried reproducing the issue with the latest release?
No

### What is the hardware spec (RAM, OS)?
12GB, Ubuntu 19.04

### Steps to reproduce the issue (command/config used to run Dgraph).
1) Set the schema:
file_content: string @index(fulltext) @lang .
2) Insert data
"file_content@en": "unrelated breaks GIT Buccal micron Standard burst College Overall absorptive paracellular measures advance contains mm protein’s chymosin beyond β-lactotensin permanent respective rigid-body apical corneum information murine medium After supported mCherry—a ZOT fluorometer immobilized fully"
3) Try to search "protein"

### Expected behaviour and actual result.
Text search should found "protein" in "protein’s" but can't found it. Neo4j's Lucene can.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8472). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
