### ISSUE TITLE
Default (English) full-text tokenizer is not work when no language is specified 

### ISSUE THREAD

**Issue by Kubera2017** [dgraph-io/dgraph#4634]
### What version of Dgraph are you using?
1.1.1
### Have you tried reproducing the issue with the latest release?
No

### What is the hardware spec (RAM, OS)?
12GB, Ubuntu 19.04

### Steps to reproduce the issue (command/config used to run Dgraph).
1) Set the schema
file_content: string @index(fulltext) @lang .
2) Insert data
"file_content@en": "stabilize build mentioning recent breast Mediation web high-resolution Laffieneur Hata GG isolated patient gastro Protein-Facilitated posed"
3) Query:
{
  files ( func: alloftext(file_content,"protein")   )
  {
    label
    uid: file_id
    file_name
    content: file_content
  }
}
- no results

{
  files ( func: alloftext(file_content@en,"protein")   )
  {
    label
    uid: file_id
    file_name
    content: file_content
  }
}
- results founded, but without "content"

{
  files ( func: alloftext(file_content@en,"protein")   )
  {
    label
    uid: file_id
    file_name
    content: file_content@en
  }
}
- correct results founded

### Expected behaviour and actual result.
Should found the results when @en is omitted, as described in documentation
"In full-text search functions (alloftext, anyoftext), when no language is specified (untagged or @.), the default (English) full-text tokenizer is used."

**Comment by martinmr** [comment]
There's no problem here. The documentation is saying that English is used as a tokenizer when you query `file_content` or `file_content@.`. However, you added your data to `file_content@en`.

You can think of `file_content@en` and `file_content` as two different values. If you ask for `file_content` then the query will not look at `file_content@en`. That's the reason the first query does not return any results and why the second query finds the result but does not return it in the query body. The third query is properly written.

What the documentation is saying is that untagged values will be treated as if they were written in English. It's not saying that the untagged value and the value with the `en` tag are considered the same value. I'll change the documentation to hopefully make this clearer.
