### ISSUE TITLE
Query telemetry is wrong

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#4639]
### What version of Dgraph are you using?

master

### Have you tried reproducing the issue with the latest release?

yes

### What is the hardware spec (RAM, OS)?

n/a

### Steps to reproduce the issue (command/config used to run Dgraph).

Send a single GraphQL+- query to Dgraph and see the telemetry values it reports.

### Expected behaviour and actual result.

I would expect to see:

| NumGraphQL | NumQueries | SinceHours |
|-|-|-|
|0|1|1|

Instead, I see

| NumGraphQL | NumQueries | SinceHours |
|-|-|-|
|1|0|2562047|

The problems are:

1. The code involved with the counting of queries seems to be reversed, see https://github.com/dgraph-io/dgraph/commit/4d1d0e0701bd1495891dcc19243e7e1e7af7cf55#diff-cba0a28bf873e73873304fd5473a2a78R706

2. The telemetry name is `NumQueries` I would expect to have all of them counted, including the GraphQL ones.

3. The initialization of the `lastPostedAt` time is wrong! https://github.com/dgraph-io/dgraph/commit/4d1d0e0701bd1495891dcc19243e7e1e7af7cf55#diff-cba0a28bf873e73873304fd5473a2a78R96. It should initialize it to `time.Now`, no to zero time.

cc: @arijitAD

**Comment by campoy** [comment]
In addition to this, I see a bunch of metrics sent as zero which might mess up with some of our analysis.

For instance, `NumAlphas` or `ClusterSize` shows as zero every time it's sent from an Alpha node.

We should instead send *only* those metrics that are relevant to each node.

I propose using different structs for each server.

**Comment by arijitAD** [comment]
@campoy Initially, I was thinking if we could use a filter in the query to differentiate between alpha and zero stats. But adding a different struct would make more sense. I will make that change.

**Comment by martinmr** [comment]
@arijitAD Manish said there's no really need for separate structs for now. The other 3 points in the first comments are fixed by #4641
