### ISSUE TITLE
dgraph loading golden data - watermark should be below

### ISSUE THREAD

**Issue by djhenderson** [dgraph-io/dgraph#464]
I am following the install procedure in Get Started wiki page. At Step 4: Load dataset, the dgraph server stops with
`error.go:75: Watermark group: 1: 1812 should be below current mark: 1720`

Dgraph is running in VirtualBox VM running Ubuntu 10.4 and Dgraph 0.7.1. The dgraph server is running in the VBox console window. Dgraphloader runs in ssh terminal. Another ssh terminal monitors with top, df, etc.

I observed some warning messages (similar to below) scroll past.

![dgraph warning1](https://cloud.githubusercontent.com/assets/1244826/21789970/559e7384-d696-11e6-99cf-29eca867b43a.png)

After the server stopped, the dgraphloader was stuck in a loop retrying requests with many messages like:
    Retrying req: 1040. Error: rpc error: code = 14 desc = grpc: the connection is unavailable
    Retrying req: 1017. Error: rpc error: code = 14 desc = grpc: the connection is unavailable
    Retrying req: 1014. Error: rpc error: code = 14 desc = grpc: the connection is unavailable
    Retrying req: 976. Error: rpc error: code = 14 desc = grpc: the connection is unavailable

Required manual INT to stop. Seems like there should be some kind of limit on retries.

**Comment by manishrjain** [comment]
This is because we use a timeout-based technique to figure out about sync watermarks. The timeout is set to 1 minute, which is sufficient for fast machines, but not for slower machines. In this case, because you're running this in a VM (slow), it gets triggered.

I'll try and see if we could switch instead to a deterministic technique, instead of using timeouts.

**Comment by djhenderson** [comment]
Update: I the p and w directories and restarted the server. Then I ran with this command line, and results:

    doug@minny:~/dgraph$ dgraphloader -c 10 -r goldendata.rdf.gz
    2017/01/09 20:22:31 embedflag.go:35: ICU is working fine!

    Processing goldendata.rdf.gz
    Number of mutations run   : 1121
    Number of RDFs processed  : 1120879
    Time spent                : 9m7.555990499s
    RDFs processed per second : 2049
    doug@minny:~/dgraph$

This looks like it worked.

So manipulating the parameters to dgraphload may be a general way to get around some speed dependent problems, like mine.

**Comment by manishrjain** [comment]
Submitted. If you build the binary from master, it should now be able to work just fine on slower machines. Would be part of the next release.
