### ISSUE TITLE
Zero instance doesn't run ValueLog GC

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/dgraph#4642]
As of commit https://github.com/dgraph-io/dgraph/commit/4c5abcec53070259955a37fccead369fa0156c5a, the `zero` instance doesn't run `Value Log GC` .

Even though the amount of data written by zero is very less, we should run `GC` for it otherwise the `zw` will grow without any bounds.

Original post - https://discuss.dgraph.io/t/dgraph-is-not-calling-badger-vlog-gc-for-zw-directory/5861

Looks like the user has too many `vlog` files because of missing garbage collection https://discuss.dgraph.io/t/dgraph-is-not-calling-badger-vlog-gc-for-zw-directory/5861/3?u=ibrahim

**Comment by jarifibrahim** [comment]
This looks like a serious issue to me. Bumping up the priority to P1.

**Comment by lgalatin** [comment]
https://github.com/dgraph-io/dgraph/pull/4716
