### ISSUE TITLE
Update Dgraph version in Arch Linux

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#466]
The current version of Dgraph in Arch is 0.4.4. We should update it to 0.7.1.

CC: @trengrj -- You own that package. Can you please update it?

**Comment by trengrj** [comment]
@manishrjain sure will do

**Comment by manishrjain** [comment]
Note that we also now require setting an environment variable. This just needs to be passed to the Dgraph process. If you run `curl https://get.dgraph.io | bash`, you'll see those instructions.

Also, is there a way to automate this process? We always keep the script up to date; so could that potentially be used to update the AUR package?

**Comment by trengrj** [comment]
Hi @manishrjain 

What is the purpose of the new icudata file? Should I add it by default?

I'm happy to give you ownership of the AUR packages if you want to update them in lockstep with your releases. The `curl | bash` approach is handy, but you can't put this directly into a package as you need to checksum binaries and install in a chroot to create a package.

**Comment by manishrjain** [comment]
Sure, feel free to send me the ownership. I think for now our focus is on the get.dgraph.io script. As we reach v1.0, and start to publish packages for Linux distributions, at that time it would make sense to also maintain the AUR package. I doubt people run Arch as a server; so might not make sense to maintain it on an ongoing basis.

**Comment by trengrj** [comment]
Sure ok @manishrjain I disowned the packages and you should be able to reclaim them
https://aur.archlinux.org/packages/?O=0&SeB=nd&K=dgraph&outdated=&SB=n&SO=a&PP=50&do_Search=Go

**Comment by dahankzter** [comment]
Being an avid Arch user this would be great!

**Comment by dahankzter** [comment]
dgraph-git still has a rocksdb dep. I thought it would go away and be replaced by badger.

**Comment by manishrjain** [comment]
We don't have anyone handling Arch releases. Maybe we should switch to snapcraft.io for all Linux based releases -- that might make it easier to handle all the OS involved.

**Comment by dahankzter** [comment]
I don't mind giving Archlinux packaging a go. I no little about Snap but I am rather used to packman etc. I guess once 1.0 is out we could possibly even get it into the official packages.
