### ISSUE TITLE
Error message after clean exit request

### ISSUE THREAD

**Issue by djhenderson** [dgraph-io/dgraph#468]
After requesting a shutdown using

    curl -sS localhost:8080/admin/shutdown

I see these messages from the server

    2017/01/10 13:14:12 main.go:84: Got clean exit request
    2017/01/10 13:14:12 error.go:51: Error while serving http request error: mux: listener closed

or

    2017/01/10 13:28:14 main.go:84: Got clean exit request
    2017/01/10 13:28:14 error.go:51: Error while serving gRpc request error: mux: listener closed

Usually I get a response containing

    {"code":"ErrorOk","message":"Server has been shutdown"}

Is this error message indicating that the shutdown was not clean? The next startup seems to take as long as a startup after a SIGINT.

**Comment by manishrjain** [comment]
We should find a way to stop all the goroutines, start rejecting queries and do a clean shutdown ensuring that all the data from memory has made it's way to disk.

**Comment by ashishnegi** [comment]
Should be fixed after commit [#3ab4d05](https://github.com/dgraph-io/dgraph/commit/3ab4d053b287918c25260ecf73de0f908a295650)
@djhenderson If it is possible for you, Can you check on current master branch ?

**Comment by pawanrawal** [comment]
Confirmed on master, feel free to reopen if there is any issue.
