### ISSUE TITLE
Documentation is confusing in terms of json vs. gql+-

### ISSUE THREAD

**Issue by kesor** [dgraph-io/dgraph#4688]
## Documentation

The documentation for queries, mutations, schema and such are explained using different notations each time - making it very confusing to understand and hard to search for solutions amongst this confusion.

Sometimes an example might be written in GraphQL+- notation, sometimes it is the JSON notation, sometimes it has the RDF content type, sometimes it has examples for curl, javascript, java, etc... and sometimes there is just a snippet of text and the reader needs to figure out what that is on his own.

It would be way more beneficial to combine the examples so that each example is shown using all the different methods. Both all the different language clients, as well as RDF vs. JSON vs. GraphQL+- notations.

This will also allow the documentation to be more to the point with regards to "what needs to be done", and then much easier to understand with regards to "how to do it".

**Comment by danielmai** [comment]
> It would be way more beneficial to combine the examples so that each example is shown using all the different methods. Both all the different language clients, as well as RDF vs. JSON vs. GraphQL+- notations.

Agreed. Thanks for the feedback @kesor.

**Comment by ctwhome** [comment]
yes, adding to this, would be possible for you guys (anyway thank you for the efforts) to add a graphql query syntax version in the documents? 
On this place: https://dgraph.io/docs/query-language/#count how could I make the query with GraphQL syntax? it is possible to add a tab?
![image](https://user-images.githubusercontent.com/4195550/78456637-1c051d00-76a5-11ea-94de-a818d76ff800.png)

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8822). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
