### ISSUE TITLE
The arrows on the image describing a user authoring a tweet and a tweet mentioning a user are the wrong way

### ISSUE THREAD

**Issue by dragon788** [dgraph-io/dgraph#4699]
* Doc page: [tutorial-5/index.md](https://docs.dgraph.io/tutorial-5/)
* Doc version: `release/v1.2.0`

The image immediately following the text below has arrows going opposite the way the sentence describes them.

> A mentioned edge points from a Tweet node to a User node. These users are the ones who are mentioned in the tweet.

![image](https://user-images.githubusercontent.com/487774/73416668-3bfe1600-42db-11ea-93e8-a88172a5eb71.png)

**Comment by prashant-shahi** [comment]
This issue has been resolved.
