### ISSUE TITLE
Consider supporting edge naming via value variable

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#4700]
### What you wanted to do

Make a direct migration from Neo4J to Dgraph using the JSON structure that is exported via APOC.

### What you actually did

```RDF
  uid(from) <val(EDGE)> val(to) .
```

```graphql
upsert {
  query {
      var(func: has(properties)) @filter(eq(type,"relationship") AND NOT has(migrationDone) ){
      EDGE as label
      properties {
        summary as summary
        rating as rating
        roles as  roles
      }
      start {
        ID as id
      }
      end {
        endID as id
      }
      summaryMe as sum(val(summary))
      ratingMe as sum(val(rating))
      rolesMe as sum(val(roles))
    }
    from(func: eq(id, val(ID) )) @filter(NOT eq(type,"relationship") AND NOT has(~start) AND NOT has(~end)) {
     from as uid
    }
    to(func: eq(id, val(endID) )) @filter(NOT eq(type,"relationship") AND NOT has(~start) AND NOT has(~end)) {
     to as uid
    }
  }

  mutation {
    set {
      uid(from) <migrationDone> "True" .
      uid(from) <val(EDGE)> val(to) .
       # (...)
    }
  }

}
```

**Comment by mangalaman93** [comment]
I believe this is too much to expect from the query language. This should be done through using a script instead.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8476). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
