### ISSUE TITLE
The predicate `dgraph.type` is not indexed as a `term`

### ISSUE THREAD

**Issue by kesor** [dgraph-io/dgraph#4701]
## Experience Report

Using `dgraph` version `v1.2.0` I tried to query for multiple types, using the following:
```
query {
  results(func: anyofterms(dgraph.type,"TypeX TypeY")) {
```

Since `dgraph.type` is not indexed as a `term`, it does not work with the error:
`Message: : Attribute dgraph.type is not indexed with type term`

Then I thought I could add that index myself, which resulted in the following error:
`Could not alter schema: predicate dgraph.type is reserved and is not allowed to be modified`

### What you wanted to do

Query for multiple types in a single query.

### What you actually did

Failed.

### Why that wasn't great, with examples

Would love it if it would have worked.

**Comment by MichelDiz** [comment]
Sorry, but changing the behavior of `dgraph.type` would have implications for the Type System. So it is reserved.

But anyway, try the following:
```
results(func: has(dgraph.type)) @filter(anyofterms(dgraph.type,"TypeX TypeY"))  {
```

Cheers.

**Comment by kesor** [comment]
> Sorry, but changing the behavior of `dgraph.type` would have implications for the Type System. So it is reserved.
> 
> But anyway, try the following:
> 
> ```
> results(func: has(dgraph.type)) @filter(anyofterms(dgraph.type,"TypeX TypeY"))  {
> ```
> 
> Cheers.

Well, you can't "try the following" since when doing `@filter(anyofterms(dgraph.type` requires `dgraph.type`  to be indexed as a `term` ...

I could probably do something like:

`results(func:has(dgraph.type)) @filter(eq(dgraph.type,"TypeX") OR eq(dgraph.type,"TypeY")) {`

**Comment by MichelDiz** [comment]
In the latest version (1.2.0) you can run non-indexed queries like this. Just upgrade and test it out.

**Comment by kesor** [comment]
> In the latest version (1.2.0) you can run non-indexed queries like this (In filters). Just upgrade and test it out.

It doesn't work. And if it did work, that would be really weird and unintuitive.
