### ISSUE TITLE
Deleting a Node Ex : <0x1c3eb> * * . not deleting all the predicates

### ISSUE THREAD

**Issue by mkharibalaji** [dgraph-io/dgraph#4705]
### Steps to reproduce the issue (command/config used to run Dgraph).
1) try inserting some nodes and then try to delete the nodes attributes with uid
in this format

<0x1c3eb> * * .

And query that later then still for that uid you would be able to see the attributes

### Expected behaviour and actual result.
It should have deleted all the predicates and the node itself.

**Comment by MichelDiz** [comment]
You need to add a Type Schema https://docs.dgraph.io/query-language/#type-system and your node need to have the field `_:a <dgraph.type> "Person" .` to deletion works.
