### ISSUE TITLE
Predicates with @lang doesn't get expanded with _all_

### ISSUE THREAD

**Issue by jnylen** [dgraph-io/dgraph#4711]
### What version of Dgraph are you using?
1.2.0

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
archlinux, running in docker, 24GB RAM

### Steps to reproduce the issue (command/config used to run Dgraph).
Run `expand(_all_)` on any type that have a `@lang` predicate with data and that predicate won't get expanded with all values. The only way to get that data is doing `field@*`.

### Expected behaviour and actual result.
I expect `expand(_all_)` to return all values, including the ones tagged with `@lang`.

**Comment by ashish-goswami** [comment]
Hey @jnylen, this is the correct behaviour. Please check documentation for expand https://docs.dgraph.io/query-language/#expand-predicates. expand only returns predicate without lang 
tag. If you want to get with lang, you need to specify it separately.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8477). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
