### ISSUE TITLE
expect only ~100 mutations a second using a single client?

### ISSUE THREAD

**Issue by hieule1997** [dgraph-io/dgraph#4714]
> 
loop {
    txn = client.txn();
    txn.mutate(Mutation(...));
    txn.commit();
} 
>

to expect only ~100 mutations a second using a single client?

i was just running a performance test and i'm insert nodes (using the type system) with no edges (just insert an isolated node)

**Comment by MichelDiz** [comment]
I'm not sure about the question. Could you please use the issue template and elaborate better the question?

BTW  Please, make questions at discuss.dgraph.io. Let Github issues focussed on technical issues.

Cheers.

**Comment by hieule1997** [comment]
It mean i can send ~100 mutation using client. i had problem slow insert upsert block with query in upsert
example
`query = """{{
                    u1 as var(func: eq(msisdn, "{0}"))
                    u2 as var(func: eq(msisdn, "{1}"))
                    }}""".format(data["a_number"],data["b_number"])
                nquad = """
                    uid(u1) <msisdn> "{0}" .
                    uid(u1) <dgraph.type> "Sim" .
                    uid(u1) <tac> "{7}" .
                    uid(u2) <msisdn> "{1}" .
                    uid(u2) <dgraph.type> "Person" .
                    uid(u1) <friend> uid(u2) .
                    uid(u2) <friend> uid(u1) .
                    _:sim_a <b_number> "{1}" .
                    _:sim_a <service_type> "{2}" .
                    _:sim_a <b_prefix> "{4}" .
                    _:sim_a <start_time> "{5}" .
                    _:sim_a <duration> "{6}" .
                    _:sim_a <dgraph.type> "Info" .
                    _:sim_b <b_number> "{0}" .
                    _:sim_b <service_type> "{3}" .
                    _:sim_b <b_prefix> "{4}" .
                    _:sim_b <start_time> "{5}" .
                    _:sim_b <duration> "{6}" .
                    _:sim_b <dgraph.type> "Info" .
                    uid(u1) <info> _:sim_a .
                    uid(u2) <info> _:sim_b .
                    """.format(data["a_number"],data["b_number"],data["service_type"],service_type_b,data["b_prefix"],data["start_time"].strftime("%Y-%m-%dT%H:%M:%SZ"),data["duration"],data["tac"])`

**Comment by MichelDiz** [comment]
I'm testing another thing (the intention is to test something else) but is related to yours (with a single instance). I setup an env with JS, which sends 2k in mutations per second. I'm running it for about 1 hour. And no signs of serious fatigue. But the latency increase a bit.

**Comment by hieule1997** [comment]
readlly ? I need example go client

**Comment by MichelDiz** [comment]
Live load is an example https://github.com/dgraph-io/dgraph/tree/master/dgraph/cmd/live
It is a go "client", despite being different.

**Comment by MichelDiz** [comment]
Hey, this question is a bit old. Gonna close it. If you need to do more questions you can do at https://discuss.dgraph.io/ 

Also, you can have even higher (I mean HIGHER really) results with Ludicrous Mode.
https://discuss.dgraph.io/t/sharing-some-numbers-from-the-ludicrous-mode/6310

Cheers.
