### ISSUE TITLE
orderby in query groupby sum() ?

### ISSUE THREAD

**Issue by hieule1997** [dgraph-io/dgraph#4717]
<
{
  me(func: has(name)) @groupby(name ,orderdesc: sum(age)) {
    count(uid)
    sum(age)
  }
}
>
i can orderdesc when groupby ?

**Comment by MichelDiz** [comment]
No, you cant'. Groupby is a function that works only with edges.

**Comment by MichelDiz** [comment]
Please try this:
```
{
me(func: has(name),orderdesc: sum(age)) @groupby(name) {
count(uid)
sum(age)
}
}
```

Closing due a long time.
