### ISSUE TITLE
how to get reviews of someone user about some product with graphql api

### ISSUE THREAD

**Issue by shynome** [dgraph-io/dgraph#4720]
## Experience Report

add the blow schema to dgraph

```graphql
type Product {
    productID: ID!
    name: String @search(by: [term])
    reviews: [Review] @hasInverse(field: about)
}

type Customer {
    custID: ID!
    name: String @search(by: [hash, regexp])
    reviews: [Review] @hasInverse(field: by)
}

type Review {
    id: ID!
    about: Product!
    by: Customer!
    comment: String @search(by: [fulltext])
    rating: Int @search
}
```

### What you wanted to do

get reviews of someone user about some product 

```graphql
query {
  queryProduct(filter: { productID: ["dd", "fff"] }) {
    reviews {
      id
      comment
      by(filter: { custID: ["xx"] }) {
        custID
        name
      }
    }
  }
}

```

### What you actually did

the query response all reviews of those product and if some product user don't give a review  will throw a error "Non-nullable field 'by' (type Customer!) was not present in result from Dgraph.  GraphQL error propagation triggered."

### Why that wasn't great, with examples

I have to add field `byID` at `Review` type to implements that query

### Any external references to support your case

none

**Comment by shynome** [comment]
I found `Cascade` which is I need when learn dgraph, if this port to graphql filter will be good
https://tour.dgraph.io/basic/14/

**Comment by MichaelJCompton** [comment]
Thanks for the question.

Yes, graph queries that dig deeper into the graph and then filter the outer result based on some deep condition are a bit of a subtle art.

It's something that's supported nicely in Dgraph with `@cascade` and query variables, but we don't really support as a single query in GraphQL yet (you can do with multiple queries).

We plan to support more of the Dgraph GraphQL+- features in GraphQL as we move forward.

**Comment by MichaelJCompton** [comment]
I'm going to close this as it's not a specific issue that we'd fix in one go - we'll put up issues for features relating to this (e.g. cascade) as we move forward.

Please feel free to reopen or reach out on discuss or slack.
