### ISSUE TITLE
Add a way to install an old version via get.dgraph.io

### ISSUE THREAD

**Issue by sleto-it** [dgraph-io/dgraph#4730]
### What you wanted to do

Easily install an old version for testing purposes

### What you actually did

It is currently possible, but some manual work is required (i.e. download of the script and manual change of the `tag` option). Would be nice to have an option that can be passed directly to the `curl` command 

### Why that wasn't great, with examples

Requires some manual work

### Any external references to support your case

Discuss [topic](https://discuss.dgraph.io/t/install-specific-version-of-draph/5923)

**Comment by MichelDiz** [comment]
PR pull/83 created.

The user will be able to run like this
```
curl https://get.dgraph.io -sSf | bash -s -- --version=2.0.0-beta1
```
or using Environment variables:

```
curl https://get.dgraph.io -sSf | VERSION=1.2.1 bash
```

I had test locally like

```
VERSION=1.2.1 sh getdgraph.sh
# And
sh getdgraph.sh --version=2.0.0-beta1
```
