### ISSUE TITLE
LRU memory in Alpha server by default set to a negative value in MacOS

### ISSUE THREAD

**Issue by prashant-shahi** [dgraph-io/dgraph#4737]
### What version of Dgraph are you using?

```
Dgraph version   : v1.2.0
Dgraph SHA-256   : ff6a20cdd76a03a37f916b039b82bf0120b1d8ffb89edba90cecbac0652cc207
Commit SHA-1     : 24b4b7439
Commit timestamp : 2020-01-27 15:53:31 -0800
Branch           : HEAD
Go version       : go1.13.5
```

### What is the hardware spec (RAM, OS)?

```
MacOS Catlina version 10.15.2
Memory: 8 GB 1600 MHz DDR3
```

### Steps to reproduce the issue (command/config used to run Dgraph).

```sh
curl -sSf https://get.dgraph.io | bash
```

```sh
$ /usr/local/bin/dgraph alpha
[Decoder]: Using assembly version of decoder

2020/02/06 02:04:39 LRU memory (--lru_mb) must be at least 1024 MB. Currently set to: -1.000000

For more information on --lru_mb please read https://docs.dgraph.io/deploy/#config
```

### Expected behaviour and actual result.

Expected to bring up the Alpha server by setting LRU memory to 25% of the total memory as it is done in Linux.

**Comment by MichelDiz** [comment]
This must be some characteristic of mac OS. As the` --lru_mb` isn't defined at all by the binary or anything.

**Comment by animesh2049** [comment]
I think this is expected behavior, does it cause any problem on macOS? @prashant-shahi

**Comment by prashant-shahi** [comment]
@animesh2049  It doesn't work with the default settings on macOS as it does on Linux.
But yeah, it works when I manually set `--lru_mb`.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8480). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
