### ISSUE TITLE
the dateTime scalar can not be indexed

### ISSUE THREAD

**Issue by LoganLee1991** [dgraph-io/dgraph#4785]
### What version of Dgraph are you using?
1.2.1
### Have you tried reproducing the issue with the latest release?
YES

### What is the hardware spec (RAM, OS)?
Win10 8G RAM

### Steps to reproduce the issue (command/config used to run Dgraph).
1、data prepare
**test.schema contents as follows
      `type Customer {
    name
    birth_date
    cust_name
    age
}
name: string @index(term,fulltext) @upsert . 
cust_name: string @index(term) @lang .
birth_date: dateTime @index(month) .
age: int .`
**test.rdf contents as follows
`_:certNo1 <dgraph.type> "Customer" .
_:certNo1 <name> "cust1" .
_:certNo1 <cust_name> "Jarry" .
_:certNo1 <birth_date> "1992-01-01T01:01:01" .
_:certNo1 <age> "20" .`
2、run dgraph zero and then run dgraph live to insert the data
### Expected behaviour and actual result.
Expected: work right
Actual: 
error occur like:
`Found 1 data file(s) to process
Processing data file "./fraud_label_net_test/feature_cal_net2.rdf"
panic: interface conversion: interface {} is *time.Time, not time.Time

goroutine 32 [running]:
github.com/dgraph-io/dgraph/tok.MonthTokenizer.Tokens(0x12b7f60, 0xc00051f7e0, 0x10, 0xc00000ae10, 0xa, 0xc00002c663, 0xc0003d6000)
        /tmp/go/src/github.com/dgraph-io/dgraph/tok/tok.go:229 +0x257
github.com/dgraph-io/dgraph/tok.BuildTokens(0x12b7f60, 0xc00051f7e0, 0x14ca9a0, 0x1eca040, 0x14ca9a0, 0x1eca040, 0x0, 0x1, 0xc00000ae00)
        /tmp/go/src/github.com/dgraph-io/dgraph/tok/tok.go:104 +0x6a
github.com/dgraph-io/dgraph/dgraph/cmd/live.(*loader).conflictKeysForNQuad(0xc0001801c0, 0xc0002d0510, 0x8, 0x1, 0x1, 0x0, 0x0)
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/live/batch.go:309 +0x4a5
github.com/dgraph-io/dgraph/dgraph/cmd/live.(*loader).conflictKeysForReq(0xc0001801c0, 0xc000613f88, 0x1, 0xc0000f8c80, 0x0)
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/live/batch.go:330 +0xf0
github.com/dgraph-io/dgraph/dgraph/cmd/live.(*loader).makeRequests(0xc0001801c0)
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/live/batch.go:392 +0x1e2
created by github.com/dgraph-io/dgraph/dgraph/cmd/live.setup
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/live/run.go:359 +0x2f7`
**if I remove the index of birth_date, It will work well. So I think something wrong with that index.**

**Comment by MichelDiz** [comment]
This is a duplicated of https://github.com/dgraph-io/dgraph/issues/4468
The workaround for now is "Don't use a DateTime index during a load. Add it after the load".
