### ISSUE TITLE
Selectively updating and deleting facets

### ISSUE THREAD

**Issue by hackintoshrao** [dgraph-io/dgraph#4787]
### What version of Dgraph are you using?
Dgraph v1.1

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
NA

### Steps to reproduce the issue (command/config used to run Dgraph).
Create multiple facets for the same predicate and try to selectively update or delete one of them.

### Expected behaviour and actual result.
Currently, when you have multiple facets for a given predicate, it's not possible to write one query to selectively edit or delete one of them. 
The way around is to read all the facets for a given predicate into memory, selectively edit them, and write all of them back.

If we are giving people the freedom to have multiple facets, not able to able to selectively update  or delete them in one query is kind of counter-intuitive.
If this is not something we would want to support, we should at least document this behaviour and have more examples around it.

**Comment by MichelDiz** [comment]
There are some issues that cover this in some ways
https://github.com/dgraph-io/dgraph/issues/1996
https://github.com/dgraph-io/dgraph/issues/4520

In the issue 1996 I shared some ideas about doing it with upsert block too. But the idea is a bit different from the issue itself. Cuz I promote it by doing Upsert Block instead of a new feature to the parser.

**Comment by ChStark** [comment]
I made a syntax proposal on #4520 @hackintoshrao , can you share your thoughs ?

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8825). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
