### ISSUE TITLE
Java doesn't work with client keys generated by `dgraph cert` command

### ISSUE THREAD

**Issue by mangalaman93** [dgraph-io/dgraph#4790]
Related:
  * https://github.com/dgraph-io/dgraph4j/pull/132
  * https://github.com/dgraph-io/dgraph4j/pull/129

We need to do the following as part of this issue:
  * How old is PKCS#1? Should we consider moving to PKCS#8
  * Why are we using PKCS#1 for client keys?

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8826). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
