### ISSUE TITLE
New JSON facets response format cannot be unserialized back into client structures

### ISSUE THREAD

**Issue by mehdiym** [dgraph-io/dgraph#4798]
### What version of Dgraph are you using?

1.2.1

### Steps to reproduce the issue (command/config used to run Dgraph).

Query for UID facets, and then try to unmarshal them into a Go struct.

### Expected behaviour and actual result.

Expected: Facet values properly set.
Actual: Zero values.

I realize the facets response format [has recently changed](https://github.com/dgraph-io/dgo/commit/e8b9d9566692c89a664d53e5a36595257afb90f3#diff-82e41f22cfb9efa507f1989efdd6d4b4), but I don't understand how I can now unserialize it into my data structures : facets are now independent objects attached to the parent node while my Go facet properties are defined into the child node.

In the go doc example, the result is not unserialized into a Person anymore but instead into a generic `json.RawMessage`: does it mean it is not possible anymore?

How can I get facets directly back into my data structures?

**Comment by MiLeung** [comment]
I think I am having the same issue as @mehdiym 
https://www.youtube.com/watch?v=9dMvEoYY9_E
Correct me if I'm wrong, but in my video example, I think I `read @facets(read)` should be in the query result since it's clearly there when using `pings @facets(read) { ... }`. How can I get the facet result inside its corresponding node and not outside of it?

**Comment by MichelDiz** [comment]
@MiLeung the result is correct. This is the new facet's behavior.

**Comment by MichelDiz** [comment]
@MiLeung please, share you experience in this issue https://github.com/dgraph-io/dgraph/issues/4907

This issue `New JSON facets response format cannot be unserialized back into client structures #4798` is related to the new behavior. Even if we support both behaviors, this issue must be fixed.

**Comment by ashish-goswami** [comment]
Hi all, we have discussed facets format internally and prepared one document with different possible formats. Please checks below discuss post and provide your feedback.
https://discuss.dgraph.io/t/facets-format-in-mutation-requests-and-query-responses/6416
