### ISSUE TITLE
Bulk loader should split up big posting lists.

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/dgraph#4801]
## Experience Report

In #4752 the data loaded using the bulk loader causes the server to crash because the lists become too big (the size of the lists is limited by the size of the value log in badger - currently 1GB). The lists should be split up in the bulk loader to avoid this type of issues.

Using the live loader is the current solution but it's too slow.

**Comment by JimWen** [comment]
hi , are you guys working on this feature? it's so important for huge dataset, or do we have a plan release date on this?

**Comment by sleto-it** [comment]
Hi @JimWen,

Yes. We are currently actively working on this issue
We will share a target release version as soon as possible

Let us know if in the meantime we can do something else to help

Many Thanks,

**Comment by JimWen** [comment]
Thank you very much @sleto-it 
In factor, i met a related problem. With liveload big posting lists can be split, but it's too slow. And i found there's too much txn conflict even i use @noconflict，so i have to use liveload with concurrent=1,  the schema is as followings:

_type DeviceId {
  gid_device
}

type User{
  gid_user
  name
  has
}

gid_device: string @index(hash) @noconflict .
gid_user: int @index(int) @noconflict .
name: string @index(hash) @noconflict .
has: [uid] @count @reverse ._

Hope to get your help.

**Comment by martinmr** [comment]
Fixed by #4875
