### ISSUE TITLE
Duplicate entries aren't removed after schema alter from [default] to [int]

### ISSUE THREAD

**Issue by mangalaman93** [dgraph-io/dgraph#4808]
cc: @animesh2049 @pawanrawal 

Steps to reproduce:
1. Insert the below mutation in dgraph.
```
{
  set {
    <0x1> <value> "1" .
    <0x1> <value> "0" .
  }
}
```
2. Query the schema.
```
schema{}
```
**Result**
```
{
  "data": {
    "schema": [
      {
        "predicate": "value",
        "type": "default",
        "list": true
      }
    ]
  },
}
```
**Note**: type of *value* is default.
3. Now do an alter.
```
<value>: [int] .
```
4. Now do the same mutation as step 1
```
{
  set {
    <0x1> <value> "1" .
    <0x1> <value> "0" .
  }
}
```
5. Run this query
```
{
  q(func: has(value)) {
    uid
    value
  }
}
```
**Response**: 
```
{
  "data": {
    "q": [
      {
        "uid": "0x1",
        "value": [
          0,
          1,
          1,
          0
        ]
      }
    ]
  },
}
```
**Expected Response**:
```
{
  "data": {
    "q": [
      {
        "uid": "0x1",
        "value": [
          0,
          1,
        ]
      }
    ]
  },
}
```

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8827). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
