### ISSUE TITLE
Add a flag to listen other than localhost.

### ISSUE THREAD

**Issue by amosbird** [dgraph-io/dgraph#481]
As discussed on slack, this is a nice feature to have.

**Comment by manishrjain** [comment]
https://github.com/dgraph-io/dgraph/commit/c75ffa2dcb943aaa318d3d07a18c83524be01f64 adds a new flag to allow for that. For now, set both server and workers to use this flag for choosing localhost v/s 0.0.0.0. If users need them to be set differently, we can make changes accordingly.
