### ISSUE TITLE
 TestGQLAdminHealthWithClientCert

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/dgraph#4815]
### What version of Dgraph are you using?
master

### Have you tried reproducing the issue with the latest release?
yes

### Steps to reproduce the issue (command/config used to run Dgraph).

TestGQLAdminHealthWithClientCert test is failing in TeamCity. I've tried rerunning the test suite but the same test still fails

Example failure: https://teamcity.dgraph.io/viewLog.html?buildId=45157&tab=buildResultsDiv&buildTypeId=Dgraph_CiCustomClusterTests

**Comment by martinmr** [comment]
Assigning to @arijitAD since he pushed this test to master.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
