### ISSUE TITLE
restore: uid lease is not restored as it was in the original cluster.

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#4816]
### What version of Dgraph are you using?
v2.0.0-rc1

### Have you tried reproducing the issue with the latest release?
No.

### What is the hardware spec (RAM, OS)?
N/A

### Steps to reproduce the issue (command/config used to run Dgraph).

1. Run Dgraph cluster.
2. Load data to set a UID lease.
3. Run a backup.
4. Run a new Dgraph cluster.
5. Run `dgraph restore` to the new cluster.
6. Check /state in the old and new clusters. the `maxLeaseId` field is not set in the new cluster.

### Expected behaviour and actual result.

I expect the UID lease to be updated in the restored cluster so blank-node mutations start off from an unused range to create new nodes instead of updating existing nodes.

**Comment by sleto-it** [comment]
Hi all,

This issue has been fixed and the fix will be available in v1.2.2 and in the next 2.0 patch release

Many Thanks,
