### ISSUE TITLE
Add datetimenano as new scalar type?

### ISSUE THREAD

**Issue by MikeLeonard** [dgraph-io/dgraph#482]
The datetime scalar type looks like it goes down only to second-level accuracy.

When I was looking into RFC3339 I came across RFC3339Nano in go's time package. Could this be added as a scalar type? (perhaps called datetimenano?)

I think being able to store and sort by time at a sub-second granularity could be useful to users. With the speed of dgraph, a whole second seems like a lot!

**Comment by manishrjain** [comment]
I think we should make datetime go down to the nano-second level. I didn't realize that we only store up to seconds.

**Comment by clanstyles** [comment]
I like the idea of another scalar type. In a lot of situations the additional space required to store nanoseconds could cost a lot if it's not actually needed.

**Comment by MikeLeonard** [comment]
Yeah that was my thinking. Good to save space if you just want to store a specific day of the year or hour or even second.

If two are implemented, would be good to be able to switch between the two (at least datetime -> datetimenano if you later decide to get more granular with time).

**Comment by manishrjain** [comment]
We use https://golang.org/pkg/time/#Time.MarshalBinary, which uses 16 bytes to store the time, irrespective of whether it has nanoseconds or not. So, it doesn't affect space usage.

**Comment by MikeLeonard** [comment]
Ah well in that case then making sure that datetype stores nano seconds is the way to get then great.

**Comment by ashwin95r** [comment]
Hey @MikeLeonard, We already support storing nanoseconds in the datetime format. You can verify that by doing the following:
```
$ curl localhost:8080/query -XPOST -d $'mutation {
set {  
<b> <dt> "2006-01-02T15:04:05.999999999+10:00"<xs:datetime> .
}
}'

Now query it:

$ curl localhost:8080/query -XPOST -d $'{         
me(id:b) {
 dt 
 }
}'

This returns:
{"me":[{"dt":"2006-01-02T15:04:05.999999999+10:00"}]}
```

**Comment by MikeLeonard** [comment]
That's great news. Thanks a lot for the example.
