### ISSUE TITLE
(Re)Implement go client helper functions

### ISSUE THREAD

**Issue by MikeLeonard** [dgraph-io/dgraph#483]
Hi

The go client needs helper functions for the various types e.g. Int, Str, Float as well as Geo, datetime, etc.

This was mentioned on slack by @pawan. I'm keen to help the development of the go client move along, so thought I'd help by creating an issue to track this.

Previous helper function code:
[helper functions](https://github.com/dgraph-io/dgraph/commit/e6712d9023b1c7bab8c88e2bd236335afeff3558 these helper functions are required by the client)

**Comment by MikeLeonard** [comment]
Copy of slack chat:

pawan [10:08 PM] 
c.Query was changed to c.Run (edited)

[10:08]  
forgot to change the Wiki earlier.

[10:09]  
@mrjn https://github.com/dgraph-io/dgraph/commit/e6712d9023b1c7bab8c88e2bd236335afeff3558 these helper functions are required by the client.

[10:10]  
infact we should have wrapper functions for all of Int, Str, Float as was the case earlier before we introduced dependency on the types package.

mrjn [10:29 PM] 
Or, we could potentially move the indexing stuff out of types.

[10:30]  
That way, the tokenizer won't be required. And both the client and the dgraphloader would be set.

[10:30]  
Then we can bring back the helper functions.

**Comment by pawanrawal** [comment]
Hey @MikeLeonard, thanks for creating an issue. @manishrjain would be working on  moving the tok package out of types. Once that is done, maybe you can take up the task of re-implementing these functions. Happy to accept a PR.

**Comment by manishrjain** [comment]
@jchiu0 is working on that refactoring.

**Comment by manishrjain** [comment]
@jchiu0 has already implemented the move. So, I think we can bring back the helper functions. @pawanrawal -- I leave it to you to get this resolved.

**Comment by pawanrawal** [comment]
Hi @MikeLeonard. Do you want to take a go at it?

**Comment by MikeLeonard** [comment]
Hi @pawanrawal 
I'm afraid I haven't got the bandwidth at the moment. As I play with and test dgraph though I'll try to contribute with feedback/issues/help with docs. Down the line when I'm a bit more free I'll set up the various dev dependencies and look to help out more.

Thanks for working on the helper functions though. Once you've got them in I'll

**Comment by pawanrawal** [comment]
No worries @MikeLeonard. I will implement them. Reopening the issue.

**Comment by MikeLeonard** [comment]
Oops sorry didn't mean to click close!

**Comment by pawanrawal** [comment]
This is done.
