### ISSUE TITLE
GraphQL Fragment spread not working in Dgraph 2.0

### ISSUE THREAD

**Issue by soneymathew** [dgraph-io/dgraph#4830]
### What version of Dgraph are you using?
Probably the latest as exposed by
https://dgraph.io/graphql

### Have you tried reproducing the issue with the latest release?
NA

### What is the hardware spec (RAM, OS)?
Not sure

### Steps to reproduce the issue (command/config used to run Dgraph).
1. Goto https://dgraph.io/graphql
2. Execute query to check if results are returned
![image](https://user-images.githubusercontent.com/1210516/75029110-9282fc80-54f5-11ea-8fe4-225080924476.png)

3. Modify the query to use this GraphQL query in GraphiQL
```
query {
	queryLocation(
		filter: { name: {eq: "Bangalore"} }
	) {
		...locationFragment
	}
}

fragment locationFragment on Location {
  name
  	featured_in_films (
			order: { desc: initial_release_date },
			first: 3
		) {
			name
			initial_release_date
			featured_locations {
				name
			}
		}
}
```
4. No results returned
![image](https://user-images.githubusercontent.com/1210516/75029020-70897a00-54f5-11ea-8cb7-088c577768bb.png)

### Expected behaviour and actual result.

Expected Behaviour should be same as the results of the query without the named fragment

**Comment by MichaelJCompton** [comment]
Thanks for reporting. 

Fragments currently work in schema introspection queries, but not in regular queries.  

It's not great to have it like this, I'll prioritise this to get added.
