### ISSUE TITLE
[Bug]: GraphQL schema disappears randomly  

### ISSUE THREAD

**Issue by marvin-hansen** [dgraph-io/dgraph#4834]
[DBG.1582323935.zip](https://github.com/dgraph-io/dgraph/files/4238290/DBG.1582323935.zip)

## Summary 

A deployed GraphQL schema disappears randomly in a Dgraph cluster. 
However, this does not happen in single instance, so I suspect schema replication might be an issue.

### What version of Dgraph are you using?

Dgraph version   : v2.0.0-rc1
Dgraph SHA-256   : 447ca408b0e56702568f25ceab89eb712090f5f19f06752b70b9a28ca1260cd6
Commit SHA-1     : a4af81a36
Commit timestamp : 2020-02-14 17:05:06 -0800
Branch           : HEAD

### Have you tried reproducing the issue with the latest release?
No
Same behavior on version 1.1.x and 1.2.x 

### What is the hardware spec (RAM, OS)?

* Kubernetes
* 6 vCPUs 
* 24.00 GB memory 
* 5 alpha nodes
* 1 zero node 

### Steps to reproduce the issue (command/config used to run Dgraph).

For replication, the schema and data from the [GraphQL example](https://graphql.dgraph.io/docs/walk-through-example/) are sufficient to trigger the issue in [an HA setup](https://docs.dgraph.io/master/deploy/#using-helm-chart). The number of alpha or zero nodes have no impact whatsoever as long as there is more than one of each.  

1) upload a simple schema:

jq -n --arg schema "$(cat schema.graphql)" '{ query: "mutation updateGQLSchema($sch: String!) { updateGQLSchema(input: { set: { schema: $sch }}) { gqlSchema { schema } } }", variables: { sch: $schema }}' | curl -X POST -H "Content-Type: application/json" http://localhost:8080/admin -d @- | jq -r

2) Add some data  

3) Query the same data a few times 

The quickest way to trigger the bug is to deploy the GraphQL scheme to alpha-0 and then query another alpha node, say alpha-2. In Kubernetes, connecting against the exposed service seems to dispatch requests to nodes that have the schema and those that do not so it take between 3 and 15 attempts to catch this one, but eventually, it comes up.   

### Expected behavior and actual result.

Expected: Query should return the same results.  

Actual result: 

> {
  "errors": [
    {
      "message": "Not resolving XXX. There's no GraphQL schema in Dgraph.  
       Use the /admin API to add a GraphQL schema"
    }
  ]
}

The next attempt, however, delivers some data. The bug shows up pretty reliably every few queries and I have found no other mitigation other than moving from HA to a single server setup. 

Debug Infos attached! 

[DBG.1582323935.zip](https://github.com/dgraph-io/dgraph/files/4238291/DBG.1582323935.zip)

**Comment by pawanrawal** [comment]
Hey @marvin-hansen 

Thanks for reporting the issue. We are currently investigating this. Could you also please upload the logs from alpha nodes? Also what is the value of `--replicas` that you are using for Zero?

**Comment by marvin-hansen** [comment]
Thanks for looking into this @pawanrawal

Yes, you are right, the version info is incorrect, I did a mistake when copying it from some files. 

The correct version is this:
>dgraph version
> Dgraph version   : v2.0.0-rc1
> Dgraph SHA-256   : 447ca408b0e56702568f25ceab89eb712090f5f19f06752b70b9a28ca1260cd6
> Commit SHA-1     : a4af81a36
> Commit timestamp : 2020-02-14 17:05:06 -0800
> Branch           : HEAD
 
Considering the deployment, I used the Helm chart and  manually overwrote the version number and replica count for alpha and zero:

> helm install my-release dgraph/dgraph --set zero.replicaCount=1 --set alpha.replicaCount=5 --set image: v2.0.0-rc1

Inspecting the custom values confirms this:

> helm get values 
USER-SUPPLIED VALUES:
alpha:
  replicaCount: 5
image:
  tag: v2.0.0-rc1
zero:
  replicaCount: 1

When inspecting the deployed values, these replica values are all set the way it is supposed to be, at last, according to my humble understanding.

I have attached a complete dump of "helm get all". 


Yes, I added more debug Infos, specifically:

1) Full debug alpha & zero *before* schema update 
2) Then I uploaded GraphQL schema (~250 Loc), updated client & run query until the error hit
3) Full debug right *after* the error occurred. 

[HELM values.txt](https://github.com/dgraph-io/dgraph/files/4245434/values.txt)

[DBG.BEFORE.ERROR.1582561120.zip](https://github.com/dgraph-io/dgraph/files/4245593/DBG.BEFORE.1582561120.zip)

[DBG.AFTER.ERROR.1582561622.zip](https://github.com/dgraph-io/dgraph/files/4245592/DBG.AFTER.1582561622.zip)

Hope that helps. Let me know if you need any more debug, configs or any other information.

**Comment by pawanrawal** [comment]
Thanks for confirming the release version and other details. While inspecting the zip folders, I find the alpha and zero folders to be empty. Could you please re-upload the logs?

**Comment by marvin-hansen** [comment]
[DBG.AFTER.zip](https://github.com/dgraph-io/dgraph/files/4251625/DBG.AFTER.zip)
[DBG.BEFORE.1582656685.zip](https://github.com/dgraph-io/dgraph/files/4251626/DBG.BEFORE.1582656685.zip)

Here you go, all logs attached. 

The issue persists since day 1 in my cluster, but I could only find recently find the time to check config,  drill down, and report the bug. I have not found any other workaround than using a single server, which is kinda weird.

**Comment by marvin-hansen** [comment]
Update:

Due to an update error, I had to re-deploy the Dgraph cluster, re-import data, and since then the issue seems to be gone. A few minor details:
- Commit SHA-1 seems to be different  
- I changed config to 3 zero X 5 Alphas 
 
I added a complete set of log files for a possible diff vs. the previous one where the error was present. I honestly don't know what to say any more at this point. 

Feel free to close if it's impossible or to hard to replicate this strange bug. 

== Debug log files 
[DBG.AFTER-SCHEMA-UPLOAD.zip](https://github.com/dgraph-io/dgraph/files/4252491/DBG.AFTER-SCHEMA-UPLOAD.zip)
[DBG.BEFORE-SCHEMA-UPLOAD.zip](https://github.com/dgraph-io/dgraph/files/4252492/DBG.BEFORE-SCHEMA-UPLOAD.zip)

== Dgraph Version
Dgraph version   : v2.0.0-rc1
Dgraph SHA-256   : 447ca408b0e56702568f25ceab89eb712090f5f19f06752b70b9a28ca1260cd6
Commit SHA-1     : a4af81a36
Commit timestamp : 2020-02-14 17:05:06 -0800
Branch           : HEAD
Go version       : go1.13.7

**Comment by pawanrawal** [comment]
I still couldn't find any log file in the zip folders shared above. There are all different kind of debug profiles but no file containing the INFO logs printed from either an Alpha or Zero instance. I am closing this issue for now, feel free to reopen it in the future if the issue appears again along with the logs if possible.
