### ISSUE TITLE
[GraphQL] Adding support for facets in GraphQL

### ISSUE THREAD

**Issue by hackintoshrao** [dgraph-io/dgraph#4843]
## Experience Report

Note: Feature requests are judged based on user experience and modelled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### What you wanted to do
It would be great to prioritize support for facets in GraphQL, we're increasingly seeing our community interested in the feature.

Here is an open conversation in our community channel with this feature request:

<img width="443" alt="Screenshot 2020-02-24 at 3 49 21 PM" src="https://user-images.githubusercontent.com/2609511/75145540-208dfb80-571f-11ea-949d-e76d3f670a44.png">

**Comment by MichaelJCompton** [comment]
Facets are on our backlog to consider for upcoming GraphQL features.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8831). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
