### ISSUE TITLE
Improve documentation on restore - posting directories

### ISSUE THREAD

**Issue by spstarr** [dgraph-io/dgraph#4854]
## Documentation

When performing a restore, the documentation does not explain the postings directories.  Depending on your setup. 

For example, 3 EC2 instances, one instance contains an zero/alpha, the rest alphas.

When performing a restore, you need to rename p1 back to p, tarball p and scp this to the other non-running alphas, extract the data before you bring up the remaining alphas.

It would be clearer if the documentation explains that you need to manually do this and there is no auto syncing to the other alphas.

**Comment by martinmr** [comment]
With regards to the auto-syncing, the documentation already states that the posting directories have to be manually copied it.

However, you are right about the naming. I'll change the documentation to mention that you have to rename the folders if you want Dgraph to pick the data by default.

**Comment by spstarr** [comment]
> With regards to the auto-syncing, the documentation already states that the posting directories have to be manually copied it.

I don't see that in: https://docs.dgraph.io/master/enterprise-features/#restore-from-backup

Can you point me to where it says this?

**Comment by spstarr** [comment]
`After running the restore command, the directories inside the postings directory are copied over to the machines/containers running the alpha`

This implies to me *dgraph restore* will do this to the other alphas.. which is what I initially inferred from this.

**Comment by martinmr** [comment]
You are right. Thanks for pointing it out. I'll rephrase the sentence.
