### ISSUE TITLE
Binary Backups - AWS temporary credentials don't work

### ISSUE THREAD

**Issue by spstarr** [dgraph-io/dgraph#4855]
### What version of Dgraph are you using?
1.2.0

### Have you tried reproducing the issue with the latest release?
Only 1.2.0

### What is the hardware spec (RAM, OS)?
EC2 instance

### Steps to reproduce the issue (command/config used to run Dgraph).
Running dgraph with docker-compose
1) Do not set any AWS_* envvars inside the docker envs for the zero or alpha
2) perform a curl  `curl -XPOST localhost:8080/admin/backup -d "destination=s3:///<bucketname>"` but also pass as parameters the AWS temporary credentials for The access_key, secret_key, and session_token.

### Expected behaviour and actual result.
The backup should be successfully completed, actual result the backup fails with permission failure.

Not clear to me is:

1) If you do not have static AWS credentials how does this work?
2) Do you have to have AWS* envvars set in order to override any of those values in first place?
3) Can you use temporary AWS credentials?

**Comment by spstarr** [comment]
I should point out if i do pass static AWS credentials to the docker env then restart docker-compose fully, the backup works with the basic curl command above w/o credential override.

**Comment by martinmr** [comment]
Looking into it. I think I know what the issue is. The logic to set the proper host when the host is not in the path is not executed when you use custom credentials.

Since our test suite uses minio it didn't catch this before. I'll send a PR to fix this.
