### ISSUE TITLE
Dgraph can provide Unified endpoint between client and http

### ISSUE THREAD

**Issue by Willem520** [dgraph-io/dgraph#4871]
Hi,I used dgraph4j in my project,I need get cluster info like "/state" or "/health?all" to ensure my cluster is inited successfully.but in dgraph4j, I can only do mutate,alter and query on data. it means that I need to provide my own method to get the info by using httpclient.
but if I do these, there will have two way to access Dgraph. it look like grpc method is unnecessary，because http method can do all things what grpc do.
 I think if the dgraph4j can provide some manage method is much good.it will make me easy to manage my cluster or data.
from my point of view,I think the java client should have manage func like “/state” and data func like “mutate”.now, I can do all of above by http,but java client could not do that completely.
thx

See also:
- https://discuss.dgraph.io/t/dgraph-can-provide-unified-endpoint-between-client-and-http/6035

**Comment by pawanrawal** [comment]
Hey @Willem520, in the next version of Dgraph these admin endpoints like `/state` and `/health` would also be available over a GraphQL API at `/admin`. The gRPC client is mostly for executing queries and mutations and provides helper functions to make it easy for the client to do transactions whereas the Admin operations are available over HTTP.

**Comment by Willem520** [comment]
@pawanrawal Ok,I fully expect the next version

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8487). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
