### ISSUE TITLE
Upsert - setSetJson Facet with 4 digit numbered String Converted to Timestamp

### ISSUE THREAD

**Issue by mkharibalaji** [dgraph-io/dgraph#4873]
Hi Team,
     When i try to upsert a facet via json with a String of a four digit number it is inserted into the DB as a TimeStamp,This happens only in the facet.

Sample Data :
```
  { 
  prod_name: 'XXXXXXXX',
  prod_attr: 'YYYYYYYYYY',
  'prod_attr|prat_year': '2017' }
```

When I see it in the DB it looks like,
"prod_attr|prat_year": "2017-01-01T00:00:00Z",

I am using DGraph V 2.0 Beta in Windows Server.

**Comment by lgalatin** [comment]
For some reason the ticket was not moved but a duplicate was created in dgraph repo.  I am closing this one in favor of the other: https://github.com/dgraph-io/dgraph/issues/4873
