### ISSUE TITLE
Colons and slashes don't seem to be supported in IRIs

### ISSUE THREAD

**Issue by clanstyles** [dgraph-io/dgraph#488]
I will assume that the same dataset from #487 will also fail. If you attempt to bulk import any large dbpedia files, eventually they fail on an unknown character.

**Comment by squalfof** [comment]
hi, i tried http://downloads.dbpedia.org/current/core/mappingbased_objects_en.ttl, with '#' been filtered and dgraph works well. 
Could you provide some more examples relating to this issue ?

**Comment by clanstyles** [comment]
I'm on it!

**Comment by pawanrawal** [comment]
Closing this as its supported now. Feel to reopen if there are any issues.
