### ISSUE TITLE
Fix schema export with @reverse for 1.2.x 

### ISSUE THREAD

**Issue by miko** [dgraph-io/dgraph#4886]
The actual bug is described in #4856 and resolved in #4857 for master branch.
This should be backported to 1.2.x (and a new 1.2.x version should be released) because - as I understand - upgrading dgraph to v2.0.0. will require export from v1.2.x, and that will create unusable schemas for v.1.2.1 and earlier versions.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8832). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
