### ISSUE TITLE
[feature] uid_in query with QueryWithVars

### ISSUE THREAD

**Issue by u007** [dgraph-io/dgraph#4890]
is there any way to passing list of uid as []string{} for QueryWithVars ?

**Comment by MichelDiz** [comment]
it is already possible to do
```
follows @filter(uid_in(~follows, [0x1d, 0x1e, 0x20, 0x21])) 
```

unfortunately, you can't do: 

```
follows @filter(uid_in(~follows, $uids)) 
```
with multiple uids. Pinging @anurags92 

----
you can do
```
follows @filter(uid_in(~follows, [$uids]))
#Message: : Value "0x1d, 0x1e, 0x20, 0x21" in uid_in is not a number
```
but even so, you can add multiple uids in the GraphQL Query.

Also, it is not possible to force the pseudo-array in the GraphQL Query:
```
query query($uids: string = "[0x1d, 0x1e, 0x20, 0x21]") {
  query(func: has(follows)) @cascade
    {
    uid
      follows @filter(uid_in(~follows, $uids)) 
      {
        uid
      }
  }
}
```

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8833). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
