### ISSUE TITLE
Backup and restore options in the Community Edition

### ISSUE THREAD

**Issue by pe-s** [dgraph-io/dgraph#4900]
The docs state that backups are in the Enterprise Edition (EE) only. Did I get it right that there is no way to do systematic backups with the Community Edition (CE)? If yes, I'd love to know what we should do then with the CE than just playing around? 

For declaring a database production-ready you need to have some sort of backup system. Even if it's just via an underlying file backup, you need to document how to backup and restore these files in a manner with minimum data loss (which you don't). 

Until then the CE is just kind of an trial software without any production value and the label OSS does not feel appropriate but rather like a lure. Which is ok but please put disclaimers everywhere just users know where there are at and don't waste time.

No offense but crawling your docs took some time and not getting any clear answer created some frustration. However, I hope I'm wrong with my conclusions.

**Comment by sleto-it** [comment]
Hi @pe-s,

Thanks for trying Dgraph and for your feedback

The Enterprise Edition of Dgraph includes a [binary backup](https://docs.dgraph.io/enterprise-features/#binary-backups) and restore

If you are using the Community Edition you can still [export](https://docs.dgraph.io/deploy/#export-database) and [import](https://docs.dgraph.io/deploy/#fast-data-loading)

Another way to perform a backup, in the community and enterprise editions, is to shutdown the Dgraph cluster, wait that all writes complete, and then copy the data directories of all the involved alpha and zero processes to a safe place. I understand this method requires a shutdown, I am just mentioning it as yet another possibility

I agree our documentation can be improved and better describe all the backup and restore options. We are committed to improve it

I hope the above helps

Many thanks,

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8834). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by AugustDev** [comment]
I am using this tool for backup/restore to/from AWS S3 bucket for community edition dgraph https://github.com/AugustDev/dgbr
