### ISSUE TITLE
GraphQL __typename response on mutations differs in some cases

### ISSUE THREAD

**Issue by Birnsen** [dgraph-io/dgraph#4925]
### What version of Dgraph are you using?
v2.0.0-beta (Docker image)

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
RAM: 16GB
Linux 

### Steps to reproduce the issue (command/config used to run Dgraph).
I use the Altair GraphQL Client for the Requests

**Schema:**
```
type Stuff {
  id: ID!
  title: String!
  user: String!
}
```
**Mutation Request 1:**
```
mutation m {
  addStuff(input: [
    { title: "Hello World!", user: "birnsen"}
  ])
  {
    __typename
  }
}
```
**Response 1:**
```
{
  "data": {
    "addStuff": {
      "__typename": "AddStuffPayload"
    }
  }
}
```
**Mutation Request 2:**
```
mutation m {
  addStuff(input: [
    { title: "Hello World!", user: "birnsen"}
  ])
  {
    stuff {
      id
      __typename
    }
    __typename
  }
}
```
**Response 2:**
```
{
  "data": {
    "addStuff": {
      "stuff": [
        {
          "id": "0x3",
          "__typename": "Stuff"
        }
      ]
    }
  }
}
```

### Expected behaviour and actual result.
I expected that the second request returned with:
```
{
  "data": {
    "addStuff": {
      "stuff": [
        {
          "id": "0x3",
          "__typename": "Stuff"
        }
      ],
      "__typename": "AddStuffPayload"
    }
  }
}
```

Thread on discuss: https://discuss.dgraph.io/t/graphql-typename-response-on-mutations-differs-in-some-cases/6112

**Comment by MichaelJCompton** [comment]
Thanks for the report.  We'll schedule someone to dig into this.
