### ISSUE TITLE
Docker image dgraph:master should report better version string

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/dgraph#4934]
### What you wanted to do
In my Dgraph client application (Ratel) I need to do version detection to know which features or APIs are supported by my dgraph server.

### What you actually did

I queried `http://localhost:8080/health` and got a response:
```
[{"instance":"alpha","address":"alpha1:7080","status":"healthy","group":"1","version":"master","uptime":7,"lastEcho":1584107763}]
```

### Why that wasn't great, with examples

Response `version: "master"` is technically correct.  However, it **is not useful**, because its meaning depends on exact time when docker image has been pulled.

Docker image labeled `dgraph:latest` returns version in a much better way: `version:v1.2.1`.

Would be great if master images did something similar: e.g.`version:v2.0.0-prerelease+commitId` (timestamp instead of commitId).

**Comment by danielmai** [comment]
Would a version string like `v1.2.1-8-g0a0d273a7` work for you? This is a commit-ish version string following `git describe` (see [examples](https://git-scm.com/docs/git-describe#_examples)).

**Comment by paulftw** [comment]
@danielmai yes, that would work. Anything that starts with "production" version string has enough information to guess which features & API it supports.
