### ISSUE TITLE
gRPC over GraphQL

### ISSUE THREAD

**Issue by l4nn1312** [dgraph-io/dgraph#4939]
### What you wanted to do
I'd like to be able to query my v2 /graphql database from gRPC and the go client because protobufs are smaller than JSON (if I'm not mistaken) and I can keep a database ope
### What you actually did
Right now I'm having my go server make raw graphql queries to access the database which feels clunky.

### Any external references to support your case
Other folks suggested it in the discourse.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8491). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
