### ISSUE TITLE
Filtering by count

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#494]
We need to support a way by which we could filter entities by a count of their children.

For e.g.,

```
{
  director(eq("type.object.name.en", "Steven Spielberg")) @filter(gt(count(film.director.film), 0)) {
    type.object.name.en
    film.director.film (orderdesc: film.film.initial_release_date) {
      type.object.name.en
      film.film.initial_release_date
    }
  }
}
```

This would only return those entities with name `Steven Spielberg`, who have directed at least one movie; and then run the body of the query just for those entities.

**Comment by pawanrawal** [comment]
```
{
  director(func:allof(name.en, "Steven Spielberg")) @filter(gt(count(director.film), 0)) {
    name.en
    director.film (orderdesc: initial_release_date) {
      name.en
      initial_release_date
    }
  }
}
```
works now, though `eq` for string only excepts a single token hence we have to do allof here.

**Comment by manishrjain** [comment]
#618
