### ISSUE TITLE
golang docs incorrect

### ISSUE THREAD

**Issue by alexec** [dgraph-io/dgraph#4940]
* Doc page: [clients/index.md](https://docs.dgraph.io/clients/)
* Doc version: `release/v1.2.1`

You can't follow these instructions, as you're missing schema and (I think) incorrect pluralization of JSON fields.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8492). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
