### ISSUE TITLE
Strange response when applying enterprise license

### ISSUE THREAD

**Issue by Aelbannan** [dgraph-io/dgraph#4965]
### What version of Dgraph are you using?
v2.0.0-beta

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
16 GB, Windows (Docker)

### Steps to reproduce the issue (command/config used to run Dgraph).
Send a valid enterprise license to `/enterpriseLicense`

### Expected behaviour and actual result.
Expected: Success message and license applied

Actual: License applied, but error message. See below:
```
{
    "errors": [
        {
            "message": "Done",
            "extensions": {
                "code": "Success"
            }
        }
    ]
}
```

**Comment by anurags92** [comment]
@Aelbannan Unable to repro this, if I apply a key on my end I get 

`{
    "code": "Success",
    "message": "License applied."
}`

**Comment by anurags92** [comment]
> @Aelbannan Unable to repro this, if I apply a key on my end I get
> 
> `{ "code": "Success", "message": "License applied." }`

I stand corrected. It was actually an issue. I have proposed a small [PR](https://github.com/dgraph-io/dgraph/pull/5230) as a fix.
