### ISSUE TITLE
Shortest path queries

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#497]
We need to support shortest path queries. The main challenge here would be to figure out the right way to express it in GraphQL+-; and how to express the result in JSON.

We'll also want to consider the weight of the edges, which is a separate issue #495.

**Comment by ashwin95r** [comment]
We can now do shortest path queries as below.
```
{
 A as shortest(from: <srcnode>, to: <destnode>) {
   .
   <list of predicates to take with any supported operation>
   .
   . 
  }
 }
 
 Path(var: A) { _uid_ }  # This would fetch the uids of the nodes in shortest path
}
```

**Comment by pawanrawal** [comment]
Will be supported from v0.7.3.
