### ISSUE TITLE
Rename flag guardian_password to groot_password

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/dgraph#4980]
https://github.com/dgraph-io/dgraph/blob/master/ee/acl/run_ee.go#L31

I think flag `--guardian_password` to the `dgraph acl` command can be misleading: "guardians" is a group, and "groot" is a user. What this flag is really doing is checking the `groot` account password. 

I suggest we call the flag `--groot_password` if the change hasn't made a final release

cc @shekarm @pawanrawal

**Comment by mangalaman93** [comment]
@paulftw  `guardian` is a group and we may have more users than just `groot`. That is why I think @animesh2049 decided to call it `--guardian_password` and not `--groot_password`.

**Comment by pawanrawal** [comment]
@paulftw 

> What this flag is really doing is checking the groot account password.
That is not correct, it is checking the password for the user supplied as part of the `--guardian_name` flag, the default value of which is `groot` but it can be anything else too. Also, this change is already in `v1.2.0` and `v20.03`.

Given that we are deprecating the `dgraph acl` tool in favor of the GraphQL `/admin` API, I don't think we should be making any more changes to it apart from any bug fixes, hence I am closing this issue.
