### ISSUE TITLE
master: panic during calculateTabletSizes

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#4986]
### What version of Dgraph are you using?
built from the release/v20.03 branch
```
Dgraph version   : v20.03-beta.20200319
Dgraph SHA-256   : 6519578d8ff386e99f40f63f97945f1f9991bf13232aa029ebdf124c342e3a86
Commit SHA-1     : 9b483c31
Commit timestamp : 2020-03-19 17:51:46 -0700
Branch           : release/v20.03
Go version       : go1.14.1
```

### Have you tried reproducing the issue with the latest release?
this is the latest master.

### What is the hardware spec (RAM, OS)?
Ubuntu Linux

### Steps to reproduce the issue (command/config used to run Dgraph).

1. Run 1 Zero and 1 Alpha
2. Run some mutations (use `dgraph increment`).
3. This panic happens in Alpha

```
panic: runtime error: slice bounds out of range [:25185] with capacity 29

goroutine 271 [running]:
github.com/dgraph-io/dgraph/x.Parse(0xc00081c280, 0x14, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/go/src/github.com/dgraph-io/dgraph/x/keys.go:451 +0xced
github.com/dgraph-io/dgraph/worker.(*node).calculateTabletSizes(0xc0003052d0)
        /tmp/go/src/github.com/dgraph-io/dgraph/worker/draft.go:1176 +0x5b2
github.com/dgraph-io/dgraph/worker.(*node).processTabletSizes(0xc0003052d0)
        /tmp/go/src/github.com/dgraph-io/dgraph/worker/draft.go:553 +0xbb
created by github.com/dgraph-io/dgraph/worker.(*node).InitAndStartNode
        /tmp/go/src/github.com/dgraph-io/dgraph/worker/draft.go:1546 +0x498
```

### Expected behaviour and actual result.

This panic shouldn't happen.

Looks related to #4972.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8495). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
