### ISSUE TITLE
GraphQL+- should have a builder like GraphQL

### ISSUE THREAD

**Issue by glacierck** [dgraph-io/dgraph#4990]
## Experience Report

Note: Feature requests are judged based on user experience and modeled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### What you wanted to do
I need to generate query statements automatically according to the rules.
Need a builder to automatically map rules to corresponding syntax.

### What you actually did
I need to generate corresponding query or mutation according to a large number of JSON structures.
### Why that wasn't great, with examples
Repetitive mental work, but also easy to make mistakes
### Any external references to support your case
As far as I know, GraphQL has similar projects [typed-graphqlify](https://github.com/acro5piano/typed-graphqlify).
Its motive is my motive

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8496). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
