### ISSUE TITLE
Noisy log message when error while moving tablet

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#4997]
### What version of Dgraph are you using?
master

### Have you tried reproducing the issue with the latest release?
yes

### What is the hardware spec (RAM, OS)?
Ubuntu Linux

### Steps to reproduce the issue (command/config used to run Dgraph).

When move tablets are running to different groups this can show up in the Zero log:

```
E0321 13:45:23.570754     346 raft.go:352] While applying tablet proposal: Tablet is already being served
github.com/dgraph-io/dgraph/dgraph/cmd/zero.init
	/home/ashish/projects/src/github.com/dgraph-io/dgraph/dgraph/cmd/zero/raft.go:161
runtime.doInit
	/home/ashish/go/src/runtime/proc.go:5222
runtime.doInit
	/home/ashish/go/src/runtime/proc.go:5217
runtime.doInit
	/home/ashish/go/src/runtime/proc.go:5217
runtime.doInit
	/home/ashish/go/src/runtime/proc.go:5217
runtime.doInit
	/home/ashish/go/src/runtime/proc.go:5217
runtime.main
	/home/ashish/go/src/runtime/proc.go:190
runtime.goexit
	/home/ashish/go/src/runtime/asm_amd64.s:1357
```
This doesn't stop the Zero but this log with the trace makes it look like an issue.

### Expected behaviour and actual result.

The error message should say that the tablet is already being served and doesn't need to show the trace.

**Comment by lgalatin** [comment]
Fixed by https://github.com/dgraph-io/dgraph/pull/5333
