### ISSUE TITLE
Typos between set data and example queries

### ISSUE THREAD

**Issue by forstmeier** [dgraph-io/dgraph#5014]
* Doc page: [tutorial-3/index.md](https://docs.dgraph.io/tutorial-3/)
* Doc version: `release/v1.2.2`

The `set` data entered at the beginning of the 3rd tutorial includes predicate names of `tagged` and `published` but later in the examples this isn't referenced correctly (e.g. `tags` or `publishes`) which renders incorrect results in the UI.

**Comment by prashant-shahi** [comment]
This issue has been resolved.

Thank you, @forstmeier.
