### ISSUE TITLE
Unable to parse key: Invalid size for key

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#5026]
### What version of Dgraph are you using?

v20.03.0-beta.20200320 and master

### Have you tried reproducing the issue with the latest release?
Haven't tried on the latest release (v1.2.2).

### What is the hardware spec (RAM, OS)?
macOS, 16 GB.

### Steps to reproduce the issue (command/config used to run Dgraph).

1. Run 1 Zero and 1 Alpha with `-v=2` log level.
2. Run some queries and mutations (I used `dgraph increment`).
3. See this appear in the logs every time there's a tablet size calculation.

```
I0324 14:46:36.450146    5348 draft.go:819] [0x1] Set Raft progress to index: 40.
I0324 14:48:36.476935    5348 draft.go:1169] Calculating tablet sizes. Found 1 tables
I0324 14:48:36.477004    5348 draft.go:1178] Unable to parse key: Invalid size 25185 for key [33 98 97 100 103 101 114 33 104 101 97 100 255 255 255 255 255 255 255 254]
```

### Expected behaviour and actual result.

The info log showing that a key couldn't be parsed shouldn't happen.

**Comment by mangalaman93** [comment]
I notice this issue too when I run just `docker-compose up`  in the dgraph folder.
cc: @parasssh @jarifibrahim

**Comment by jarifibrahim** [comment]
@mangalaman93 @danielmai I tried running `dgraph increment` on local binary (and docker-compose) but it doesn't show me the error. Any suggestions on what else I can do to reproduce it?

**Comment by jarifibrahim** [comment]
The key for which dgraph complaints `33 98 97 100 103 101 114 33 104 101 97 100 255 255 255 255 255 255 255 254` is `!badger!head` key. The first key of table could be `badger!head` key and dgraph should deal with it accordingly.

The `!badger!head` key is a special key which helps in case of db crash.

**Comment by jarifibrahim** [comment]
I could make changes in Badger to not return the `!badger!head` key but I think dgraph should deal with badger internal keys properly. Badger also had `!badger!Move..`, `!badger!txn`, etc keys.

**Comment by jarifibrahim** [comment]
We decided to keep the code as it is. Nothing needs to be done here. See https://github.com/dgraph-io/badger/pull/1309#pullrequestreview-395548399
