### ISSUE TITLE
Predicate name support in DQL variables

### ISSUE THREAD

**Issue by llonchj** [dgraph-io/dgraph#5031]
Given I have a node:

```
<_:1> <type:emailAccount> "" .
<_:1> <name> "test@example.com" .
```

I want to be able to retrieve the `uid` given the `name` and `has(<type:emailAccount>)`.

I am trying to build the query using `QueryWithVars` and the golang api.

The query works with a hardcoded `$type` variable.

```go
        variables := map[string]string{
    		"$name": Name,
    		// "$type": Type,
    	}
    
    	q := `
    	query uid($name: string)
    	{
    		uid(func:eq(name, $name)) @filter(has(<type:emailAccount>)) {
    		  uid
    		}
    	  }
    	`
    	resp, err := txn.QueryWithVars(ctx, q, variables)
    	if err != nil {
    		return "", err
    	}
```

If i try to use `$type` as variable, returns the error: `rpc error: code = Unknown desc = Got empty attr for function: [has]`.

```
    	q := `
    	query uid($name: string)
    	{
    		uid(func:eq(name, $name)) @filter(has($type)) {
    		  uid
    		}
    	  }
    	`
```

What should be the query in order to work using `$type` to call `has($type)`?

Thanks

**Comment by MichelDiz** [comment]
I have moved this issue to Dgraph as this is a bug in Dgraph's query parser.

Reproducible with

```
query uid($name: string="test@example.com", $type: string="<type:emailAccount>"){
  uid(func:eq(name, $name)) @filter(has($type)) {
    uid
    name
  }
}
```

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8838). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by xpomul** [comment]
+1 for this feature.

My usecase is reported in https://discuss.dgraph.io/t/passing-sorting-criteria-to-custom-dql/17777/3

In short, I'd like to pass custom filtering or sorting criteria to a DQL query.

```
POST http://localhost:8080/query
Content-Type: application/dql

query q($p : string = "Person.firstName", $terms: string = "Harry", $orderby: string = "Person.lastName") {
      queryPersonCustom(func: anyofterms($p, $terms), orderasc: $orderby) {
        id : uid
        firstName : Person.firstName
        lastName : Person.lastName
      }
}
```
