### ISSUE TITLE
Cannot run "make regenerate"

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/dgraph#5047]
### What version of Dgraph are you using?
master

### Have you tried reproducing the issue with the latest release?
yes

### What is the hardware spec (RAM, OS)?
linux

### Steps to reproduce the issue (command/config used to run Dgraph).
run "make regenerate". it fails with the following:

```
➜  protos git:(master) make regenerate
Checking for semantic version 3.6.1 or newer
OK
Upgrading proto libraries before regenerating.
go: found github.com/golang/protobuf/protoc-gen-go in github.com/golang/protobuf v1.3.5
go: found github.com/gogo/protobuf/protoc-gen-gofast in github.com/gogo/protobuf v1.3.1
github.com/gogo/protobuf/gogoproto/gogo.proto: File not found.
pb.proto:29:1: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.
make: *** [Makefile:44: regenerate] Error 1
```

It also changes the proto file:

```
diff --git a/protos/pb.proto b/protos/pb.proto
index 9d89b6de7..0574a1cc3 100644
--- a/protos/pb.proto
+++ b/protos/pb.proto
@@ -25,7 +25,7 @@ syntax = "proto3";
 package pb;

 import "api.proto";
-import "github.com/dgraph-io/badger/v2/pb/pb.proto";
+import "github.com/dgraph-io/badger/pb/pb.proto";
 import "github.com/gogo/protobuf/gogoproto/gogo.proto";

 /* import "gogoproto/gogo.proto"; */
```

I don't think this is caused by a change in the code because I went back to commits that I know for sure used to work and I am still seeing this error. Seems like the behavior of one of our libraries changed. But I haven't been able to narrow it down further.

### Expected behaviour and actual result.
make regenerate works

**Comment by martinmr** [comment]
I tried a much earlier version and it works so I guess I just didn't go back far enough. I'll try using the bisect tool to find the commit that broke stuff.

**Comment by martinmr** [comment]
git bisect outputs this:

```
➜  dgraph git:(16811b06b) git bisect good
c9b83927d3855d8542f1549befd140cc7b051738 is the first bad commit
commit c9b83927d3855d8542f1549befd140cc7b051738
Author: Abhimanyu Singh Gaur <12651351+abhimanyusinghgaur@users.noreply.github.com>
Date:   Thu Feb 27 22:10:36 2020 +0530

    graphql: Replicate /state in admin (#4848)

    * state for graphql

    * complete admin state with test

    * update Rewrite signature

    * update schema

    * resolve review comments

 go.mod                       |   1 -
 go.sum                       |  22 +-
 graphql/admin/admin.go       |  72 +++++-
 graphql/admin/state.go       | 120 ++++++++++
 graphql/e2e/common/admin.go  | 140 +++++++++++
 graphql/e2e/common/common.go |   2 +
 protos/pb.proto              |  17 +-
 protos/pb/pb.pb.go           | 544 ++++++++++++++++++++++---------------------
```

Looks like that PR introduce the gogo

**Comment by martinmr** [comment]
@abhimanyusinghgaur I fixed this but is there a way we could not use the gogo library? It seems like importing it is causing the issue.

**Comment by abhimanyusinghgaur** [comment]
I had to use some protos inside custom go types. And, so had to use `json.Marshal()` with those types. gogo is needed for making normal `json.Marshal()` work similar to `jsonpb.Marshaler{}.Marshal()` by applying custom json tag values. Otherwise, it would require a lot of runtime conversion from proto to custom go types.

If we can find a way to make json tags for proto fields built same as json value in protobuf tag for that field, then we won't need gogo.

**Comment by martinmr** [comment]
ok. I think the workaround is good enough for now so we don't need to spend much time trying to find an alternate way to do conversions.
