### ISSUE TITLE
20.03.0: cannot retrieve UIDs from list with key...

### ISSUE THREAD

**Issue by mehdiym** [dgraph-io/dgraph#5066]
### What version of Dgraph are you using?

20.03.0
Single Alpha instance.

### What is the hardware spec (RAM, OS)?

Debian stable
i7-7700HQ CPU @ 2.80GHz, 16Gb RAM

### Steps to reproduce the issue (command/config used to run Dgraph).

When I run concurrent tests (multiple parallel go routines), I quickly get multiple errors of this kind:

```unexpected error: rpc error: code = Unknown desc = : cannot retrieve UIDs from list with key 00000b67616d655f616e7377657204000000000009ed05: readTs: 911 less than minTs: 915 for key: "\x00\x00\vgame_answer\x04\x00\x00\x00\x00\x00\t\xed\x05"```

Does not happen on my NOT concurrent tests.

**Comment by shekarm** [comment]
Can you specify which tests you are running?

**Comment by mehdiym** [comment]
For some unknown reasons, the problem is gone, closing it.
