### ISSUE TITLE
Query hangs forever

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#509]
{
  D as directors(allof("type.object.name.en", "steven spielberg")) {
    film.director.film {
    }
  }
	directors(D) {
    type.object.name.en
		film.director.film (orderdesc: film.film.initial_release_date) {
      type.object.name.en
      film.film.initial_release_date
		}
	}
}

**Comment by ashwin95r** [comment]
Fixed by 692a8ddaee5fd7bf063fb3bdfd8d2bf0af89a277.
