### ISSUE TITLE
Add store_xids to Liveloader

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#5106]
## Experience Report

This ticket is related to #4917 

--store_xids:

A feature that exists only in Bulkloader. It takes the XID or blank node and saves it to the same node as a property of it with the predicate name as "xid". e.g.:

```
<_:MichelDiz> <name> "Michel" .

It will be recorded as 

{
  "data": {
    "q": [
      {
        "name": "Michel",
        "xid": "_:MichelDiz"
      }
    ]
  }
```
This functionality at first does not seem useful. But I'm sure it's related to the approach on external IDs https://docs.dgraph.io/mutations/#external-ids

e.g.:

```
<0x321> <xid> "https://www.themoviedb.org/person/32-robin-wright" .
```

It can be useful in this case and we can use Upsert Block. But it is not useful for those who need to ingest large amounts of data. Only small cases.

**Comment by MichelDiz** [comment]
Observation: One thing I noticed in recent tests is that `store_xids` stores only real `XIDs`. I think It should store any kind of value except UIDs in fact. So my example in this issue is slightly wrong. Cuz I'm exemplifying with a blank node `<_:MichelDiz>` not a XID.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8501). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
