### ISSUE TITLE
Tracking zero counts

### ISSUE THREAD

**Issue by mehdiym** [dgraph-io/dgraph#5114]
Hello,

When using the count index at the query root, I regularly need to get values lower than a threshold, **including** zero.

For instance, suppose I have products connected to suppliers and I’d like to known when there are not enough suppliers. I could use the following query:
```
{
  me(func:lt(count(supplier), 3)) {
    uid
    product_name
  }
}
```

But I will miss the products with 0 suppliers: the most important ones to me.

I could use a second query block with a filter not has(supplier) but it is no efficient as not using any index.

What about adding an option on @count index to also track 0 counts?
It could be tracked only for the types containing the predicates with those indexes.

For example :
```
type Product {
  supplier
}
supplier: [uid] @count(zero) .
```

Original forum thread: https://discuss.dgraph.io/t/tracking-zero-counts/6235

**Comment by lgalatin** [comment]
I am accepting it for now which means we will work on it if it gets high priority.

**Comment by lgalatin** [comment]
This was given low priority for now, would you please let us know if the suggestions given in the discuss post work for you?

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8865). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
