### ISSUE TITLE
Adding/Updating nodes for XID inside XID doesn't work if parent XID already exists

### ISSUE THREAD

**Issue by abhimanyusinghgaur** [dgraph-io/dgraph#5128]
latest:master

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, OS)?

doesn't matter

### Steps to reproduce the issue (command/config used to run Dgraph).

* Add following graphql schema:
  ```graphql
  interface People {
          id: ID!
          xid: String! @id
          name: String!
  }

  type Teacher implements People {
          teaches: [Student]
  }

  type Student implements People {
          taughtBy: [Teacher]
  }
  ```
* Perform following mutation:
  ```graphql
  mutation {
    addStudent(input: [{
      xid: "S1"
      name: "George"
      taughtBy: [{
        xid: "T1"
    	name: "Seinfeld"
    	teaches: [{xid: "S2", name: "Kramer"}]
      }]
    }]) {
      student {
        id
        xid
        name
        taughtBy {
          id
          xid
          name
          teaches {
            id
            xid
            name
          }
        }
      }
    }
  }
  ```
* And we get what we expect:
  ```json
  {
    "data": {
      "addStudent": {
        "student": [
          {
            "id": "0x3",
            "xid": "S1",
            "name": "George",
            "taughtBy": [
              {
                "id": "0x4",
                "xid": "T1",
                "name": "Seinfeld",
                "teaches": [
                  {
                    "id": "0x2",
                    "xid": "S2",
                    "name": "Kramer"
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  }
  ```
* But, now perform following mutation:
  ```graphql
  mutation {
    addStudent(input: [{
      xid: "S3"
      name: "Elaine"
      taughtBy: [{
        xid: "T1"
    	name: "Seinfeld"
    	teaches: [{xid: "S4", name: "Newman"}]
      }]
    }]) {
      student {
        id
        xid
        name
        taughtBy {
          id
          xid
          name
          teaches {
            id
            xid
            name
          }
        }
      }
    }
  }
  ```
### Expected behaviour and actual result.

**Expected Behaviour**
We should be getting both `Kramer` and `Newman` in the `teaches` list for `Seinfeld`.
```json
{
  "data": {
    "addStudent": {
      "student": [
        {
          "id": "0x6",
          "xid": "S3",
          "name": "Elaine",
          "taughtBy": [
            {
              "id": "0x4",
              "xid": "T1",
              "name": "Seinfeld",
              "teaches": [
                {
                  "id": "0x2",
                  "xid": "S2",
                  "name": "Kramer"
                },
                {
                  "id": "0x5",
                  "xid": "S4",
                  "name": "Newman"
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```

**Actual Result**
We are getting only `Kramer`, which was added in the first mutation. `Newman` is not created at all.
```json
{
  "data": {
    "addStudent": {
      "student": [
        {
          "id": "0x5",
          "xid": "S3",
          "name": "Elaine",
          "taughtBy": [
            {
              "id": "0x4",
              "xid": "T1",
              "name": "Seinfeld",
              "teaches": [
                {
                  "id": "0x2",
                  "xid": "S2",
                  "name": "Kramer"
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```

### Steps to reproduce the issue (command/config used to run Dgraph).

* Continue from Case-1, same schema, and the mutations performed.
* Now perform following update mutation:
  ```graphql
  mutation {
    updateStudent(input: {
      filter: {
        xid: {eq: "S1"}
      }
      set: {
        taughtBy: [{
          xid: "T1"
          name: "Seinfeld"
          teaches: [{xid: "S5", name: "Peterman"}]
        }]
      }
    }) {
      student {
        id
        xid
        name
        taughtBy {
          id
          xid
          name
          teaches {
            id
            xid
            name
          }
        }
      }
    }
  }
  ```
### Expected behaviour and actual result.

**Expected Behaviour**
It should have updated the `teaches` list for `Seinfeld` to have `Peterman` as well.
```json
{
  "data": {
    "updateStudent": {
      "student": [
        {
          "id": "0x3",
          "xid": "S1",
          "name": "George",
          "taughtBy": [
            {
              "id": "0x4",
              "xid": "T1",
              "name": "Seinfeld",
              "teaches": [
                {
                  "id": "0x2",
                  "xid": "S2",
                  "name": "Kramer"
                },
                {
                  "id": "0x5",
                  "xid": "S5",
                  "name": "Peterman"
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```

**Actual Result**
We are getting only `Kramer`, which was added in the first mutation. `Peterman` is not created at all.
```json
{
  "data": {
    "updateStudent": {
      "student": [
        {
          "id": "0x3",
          "xid": "S1",
          "name": "George",
          "taughtBy": [
            {
              "id": "0x4",
              "xid": "T1",
              "name": "Seinfeld",
              "teaches": [
                {
                  "id": "0x2",
                  "xid": "S2",
                  "name": "Kramer"
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by MichaelJCompton** [comment]
This is a misunderstanding of our deep mutations, not a bug.  We probably need better docs to make the semantics clearer.

In short, our deep mutations don't have 'deep side effects' - side effects get too hard to reason about for a consumer.  

An 'add Elaine' mutation will add Elaine, but doesn't have side effects on other nodes in the graph (in the example above on the teaches edge of the Jerry node).  We'll add the new node you gave us, link it to things you told us to, and maybe create and link as part of a deep add, but no side effects.

The way to think about it is from the client's point of view.  We want to create an experience of serialize your client side data and send it to us, but deep side effects make that hard to do.  There's two problems in the example above:

* firstly the database data has that Seinfeld teaches Kramer, but the new mutation only has `name: "Seinfeld", teaches: [{xid: "S5", name: "Peterman"}]`, so what's that mutation asking us to do?  Is it add this new teaches data to the existing data for Seinfeld; or is it set the Seinfeld data to exactly this list.  Which ever side effect you pick, you still have to be super clear about that semantics and you still force users to prune their client side data and use an 'update Seinfeld' mutation why they wanted the other semantics.
* secondly, imagine a UI, you've queried the DB for the teachers and who they teach - in this case Seinfeld teaches Kramer.  Then the user is busy typing in the data that will make Elaine and set Seinfeld teaches Peterman, but there's no database transaction going on here, so in the background a mutation removes Kramer from the list of people Seinfeld teaches.  Now the data in the UI is stale and if there were side effects, when the UI serializes Elaine and the deep side effect, it would re-add the stale 'Seinfeld teaches Kramer' relationship.  That would mean clients could no longer just serialize and send, they'd have to write code to prune down pretty much every mutation.  But the other way works nicely - you know in the UI that Peterman was added to Seinfeld, so you send an update for just that.
