### ISSUE TITLE
Graph access control

### ISSUE THREAD

**Issue by emregency** [dgraph-io/dgraph#5167]
## Experience Report

Note: Feature requests are judged based on user experience and modeled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### What you wanted to do
I was considering to evaluate the Enterprise License as it includes ACL. I wanted to know if I can
limit a user seeing the projects of another user.

### What you actually did
I went to the Enterprise Features section of the documentation to see how ACL is handled.

### Why that wasn't great, with examples
The documentation mentions an ACL implementation at predicate-level, maybe similar to an ABAC. It would have been enough if dGraph was not a graph dB. However, as far as I understand from the [documentation](https://dgraph.io/docs/enterprise-features/#retrieve-users-and-groups-information), `lateral movement` is possible with queries and `need to know` principle cannot be enforced with this sort of ACL. 

### Any external references to support your case
[A paper on the topic](https://arxiv.org/ftp/arxiv/papers/1909/1909.09904.pdf)
[neo4j 4.0 new security model](https://neo4j.com/docs/cypher-manual/current/administration/security/subgraph/)

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8505). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
