### ISSUE TITLE
How to plan the cluster size

### ISSUE THREAD

**Issue by jameswangcnbj** [dgraph-io/dgraph#5177]
My current machine configuration is 8core16GB, 3node
After testing 400 million data imports, I found that the query is very slow. I am not sure whether the number of 3nodes currently used meets the requirements, or whether I use 6nodes, and then enable sharding. Could anyone give me some guidance?

**Comment by ashish-goswami** [comment]
Hi @jameswangcnbj, thanks for reaching out to us. I would like to ask to you few things before suggesting anything:

- Dgraph version you are running.
- Size of `p` directory.
- Type of query you are running.
- Also what are memory and CPU usage when you are running that query. You can also collect profiles if possible(https://dgraph.io/docs/howto/#profiling-information)

**Comment by jameswangcnbj** [comment]
dgraph 20.03
p:20GB
cpu:50% ram:60% or higher

**Comment by ashish-goswami** [comment]
Hey @jameswangcnbj, Thanks for above information. Are you running all 3 nodes on same machine? How much queries are you serving when CPU/RAM usage are as above.
As per above information query might be slow. Please tell us the type of query you are trying to run. Also expected and actual latency.

**Comment by jameswangcnbj** [comment]
no,i run 3node in 3 machine,i want to get the result in 10-500ms,the longest within 1s

**Comment by ashish-goswami** [comment]
@jameswangcnbj, if machines used for all alpha are different, this should be good enough. Please tell us the type of queries you are running. As part for query response, you can also check which part of query processing is consuming most time using debug param(https://dgraph.io/docs/query-language/#debug)

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8506). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
