### ISSUE TITLE
Homebrew package for macOS

### ISSUE THREAD

**Issue by zachvalenta** [dgraph-io/dgraph#5186]
## Documentation

Just dropping a line to see 1) possible to use Dgraph via Homebrew package? 2) if possible, that those instructions might be added to the `README.md` to supplement the `curl` command in the quick [install section](https://github.com/dgraph-io/dgraph#quick-install).

**Comment by darkn3rd** [comment]
This should be easy to do, someone already did something with an earlier version: https://github.com/srfrog/homebrew-dgraph/blob/master/Formula/dgraph.rb

**Comment by ankane** [comment]
Mac users can now do:

```sh
brew install dgraph
```
