### ISSUE TITLE
Chocolatey package for Windows

### ISSUE THREAD

**Issue by darkn3rd** [dgraph-io/dgraph#5190]
>  As a Windows user, I want to install dgraph binaries using Chocolatey, so that installation super easy and enjoy benefits of package management (searched, install audited, automation)
 
For those that do not know, Chocolatey is a popular package management solution on Windows based on nuget, and supported by Microsoft.

**Links**:
-  **General**: https://chocolatey.org/
-  **Creating Chocolatey Package**: https://chocolatey.org/docs/create-packages

**Comment by MichelDiz** [comment]
Hey @darkn3rd, thanks for the contribution.

About your issues. I think the only valid is the windows, I was thinking about it months ago, I had investigated, but I gave up. It seemed too complex to maintain. And it looks like you need to keep a service running. I didn't quite understand that. But needs a deeper investigation.

Do you know if is common to use windows as a back-end server? I remember that Apache was used for a long time on Windows. But nowadays most services are Linux based. That's another point tho.

The other issues the script we have on the web site just works fine. There's no issue with any Linux distro or mac as far as I know.

**Comment by darkn3rd** [comment]
As far as I understand you just need to publish to chocolatey and they will host it.  The script will then fetch it directly from github.  I will volunteer to implement this after doing the homebrew one.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8507). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
