### ISSUE TITLE
Debian Package for Debian/Ubuntu Linux

### ISSUE THREAD

**Issue by darkn3rd** [dgraph-io/dgraph#5191]
>  As a Linux user (Debian, Ubuntu, etc), I want to install dgraph binaries using apt-get, so that installation super easy and enjoy benefits of package management (searched, install audited, automation)

**Implementation**: We would post packages and gpg key on a web server, and users would then add the repository, such as through `add-apt-repository` or edit `/etc/apt/sources.list` or add a file to `/etc/apt/apt.conf.d/` and then use `sudo apt-get install dgraph` for example

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8508). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
