### ISSUE TITLE
RPM Package for RHEL/CentOS/Amzn Linux

### ISSUE THREAD

**Issue by darkn3rd** [dgraph-io/dgraph#5192]
>  As a Linux user (RHEL, CentOS), I want to install dgraph binaries using yum or dnf, so that installation super easy and enjoy benefits of package management (searched, install audited, automation)

**Implementation**: We would post packages and gpg key on a web server, and users would then use `yum -config-manager --add-repo URL` to add the repository, or edit `/etc/yum/conf` or add a file to `/etc/yum.repos.d`.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8509). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
