### ISSUE TITLE
how to hide  intermediate nodes

### ISSUE THREAD

**Issue by jameswangcnbj** [dgraph-io/dgraph#5228]
here is my graphsql:
```
{
  query(func:eq(dgraph.dg_law_firm.law_firm_name,"lawyerfirmA")){
    uid
    dgraph.dg_law_firm.law_firm_name
    lawyer:~dgraph.dg_lawyer.law_firm_id{
      uid
      dgraph.dg_lawyer.lawyer_name
      #caselawyer
      caselawyer:~dgraph.dg_case_lawyer.profile_id{
      case:dgraph.dg_case_lawyer.judgement_id{
            uid
        dgraph.dg_case.case_no

        
      }  
      }
    }
  }
}
```
there show me :
lawyer->caselawyer->case 3level graph info，but i want to hide "caselawyer" graph,only show
lawyer->case ,how can i  write graphsql?

**Comment by MichelDiz** [comment]
At the level you want to "hide" you can use https://dgraph.io/docs/query-language/#normalize-directive - with Normalize you will "flat" nodes nested to the "level above". You need to use aliases in each field that you need to return.

Let me know if it works.

**Comment by jameswangcnbj** [comment]
Thank you very much, it works well

**Comment by MichelDiz** [comment]
Nice! glad it worked for you!

Cheers.
