### ISSUE TITLE
Support multiple unique fields in dgraph GraphQL

### ISSUE THREAD

**Issue by sessionboy** [dgraph-io/dgraph#5232]
### What you wanted to do
Expect team to provide support for multiple unique fields in dgraph GraphQL, this is a very common requirement, like this:

```graphql
 type User {
    id: ID!
    name: String! @unique
    username: String! @unique
    phone_number: String! @unique
    email: String @unique
    ...
 }
```
The unique field is allowed to be empty, and no verification is performed when the value of the unique field is empty. For example email above.

### Any external references to support your case
[prisma](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/data-model) provides a great implementation for this, which can be used as a reference.

**Comment by MichaelJCompton** [comment]
Hi, thanks for the suggestion.

We'll take this onboard as we look at GraphQL features.

**Comment by sessionboy** [comment]
Thanks for team efforts, I look forward to it.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8512). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
