### ISSUE TITLE
GraphQL: Returning a 200 for errors

### ISSUE THREAD

**Issue by ardan-bkennedy** [dgraph-io/dgraph#5233]
### What version of Dgraph are you using?

v20.03.0

### Have you tried reproducing the issue with the latest release?

Using the latest release

### What is the hardware spec (RAM, OS)?

Running Dgraph in docker using `dgraph/standalone:v20.03.0`

### Steps to reproduce the issue (command/config used to run Dgraph).

Learning how to use native GraphQL in my Go project. Starting with a schema. I am clueless.

I am trying this schema document

```
schema := `type City {
		cityID: ID!
		name: String @search(by: [term])
		lat Float!
		lng Float!
	}`
```
and got an error back

2020/04/17 11:51:04 ****** GQL ********> 200 OK {"errors":[{"message":"Error parsing JSON at line 1, character 3: invalid character 'y' in literal true (expecting 'r')\n","extensions":{"code":"ErrorInvalidRequest"}}]}

### Expected behaviour and actual result.

The problem is the call returned a 200 which means to me the request was successful. The request was not successful. The server needs to return anything but a 200 back for this.

Now I need to inspect the returned document to identify if there was an error or not. Basically parse the string for this :( This makes everything much more complicated than it needs to be.

**Comment by ardan-bkennedy** [comment]
I am starting to think this is a function of the GraphQL spec? It seems that the structure returned looks like this.

```
type result struct {
	Data   interface{}
	Errors []Error
}
```

Please let me know if this is true.

**Comment by MichelDiz** [comment]
Can you share the way you are doing it?

If you are using dgo, sorry but dgo does not support GraphQL. You need to use third-party clients, any GraphQL client works. And some operations are done at specific endpoints.

**Comment by ardan-bkennedy** [comment]
The question is, based on the GraphQL spec, when an error occurs with a graphQL operation should the return code be 200 or something else?

**Comment by ardan-bkennedy** [comment]
http://spec.graphql.org/June2018/#sec-Response
The spec does not seem to define the status code, which is odd.

It's common practice to use 200 for all GraphQL requests. When errors happen, they're put in the "errors" key. Non-200 response codes indicate that some issue occurred at the HTTP transport layer, not the GraphQL layer.

I guess this is not an issue.

**Comment by MichelDiz** [comment]
I think that error handling is different in GraphQL. I've never seen anyone using HTTP status codes in GraphQL context tho. There are even many libs that do this error handling job. But maybe it would be good to add this, who knows.

**Comment by ardan-bkennedy** [comment]
If the spec does not specify the status code then PLEASE return anything but a 200 if there is a failure. This will help application development tremendously. I didn't see the spec say anything about the status code.
