### ISSUE TITLE
@normalize broken for >=v1.2.0 when using @facets

### ISSUE THREAD

**Issue by dkjii-g** [dgraph-io/dgraph#5241]
Description

@facets used to work when being normalized, but v1.2.0 introduced some nesting behavior, which gives a weird result when using @normalize with @facets

### What version of Dgraph are you using?

v1.2.0

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, OS)?

4G, Linux

### Steps to reproduce the issue (command/config used to run Dgraph).

Go to https://dgraph.io/docs/query-language/#facets-on-scalar-predicates
Try this query:
```
curl -H "Content-Type: application/graphql+-" localhost:8080/query -XPOST -d '
{
   data(func: eq(name, "Alice")) @normalize {
     name: name
     friend @facets(close) {
       nameTo: name
     }
   }
}' | python -m json.tool | less
```
in the facets playground
Result:

```
{
  "data": {
    "data": [
      {
        "0": true,
        "1": false,
        "2": true,
        "name": "Alice",
        "nameTo": "Bob"
      },
      {
        "0": true,
        "1": false,
        "2": true,
        "name": "Alice",
        "nameTo": "Charlie"
      },
      {
        "0": true,
        "1": false,
        "2": true,
        "name": "Alice",
        "nameTo": "Dave"
      }
    ]
  }
}
```

### Expected behaviour and actual result.
This is what used to happen on v1.1.1:
```
{
  "data": {
    "data": [
      {
       "friend|close": true,
        "name": "Alice",
        "nameTo": "Bob"
      },
      {
       "friend|close": false,
        "name": "Alice",
        "nameTo": "Charlie"
      },
      {
       "friend|close": true,
        "name": "Alice",
        "nameTo": "Dave"
      }
    ]
  }
}
```

**Comment by MichelDiz** [comment]
@ashish-goswami this is related to #4907
