### ISSUE TITLE
Support setting predicateMoveTimeout value

### ISSUE THREAD

**Issue by JimWen** [dgraph-io/dgraph#5246]
## Experience Report

Note: Feature requests are judged based on user experience and modeled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### What you wanted to do

Now the timeout param of movePredicate is set to a fix const value(predicateMoveTimeout=20min), but sometime the predicate is too big to finish moving in 20min.

### Why that wasn't great, with examples

Add an option param of alpha to support setting this value when starting an alpha node.

**Comment by JimWen** [comment]
If some meet the same problem of moving big predicate by hand, change the value in source code " dgraph/cmd/zero/tablet.go
" like followings and rebuild then restart the zero using new file.

`const (
	predicateMoveTimeout = 600 * time.Minute
)
`

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8513). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
