### ISSUE TITLE
Support starting a snapshot  at a fixed time manually

### ISSUE THREAD

**Issue by JimWen** [dgraph-io/dgraph#5247]
## Experience Report

Note: Feature requests are judged based on user experience and modeled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### What you wanted to do

Now a new Raft snapshot start after a fixed number of Raft entries which is set by param "--snapshot_after", but i want to start a new snapshot at a fixed time clock.

### Why that wasn't great, with examples

Sometimes, the snapshot would trigger rollup and log-compaction which consumes too much time at production env, so i want to do this operation when  the cluster is idle such as midnight.

### Any external references to support your case

Maybe we can refer to the "hbase log-compaction param" which support setting a fixed count interval or a fixed time or a fixed  time interval.

**Comment by ashish-goswami** [comment]
@JimWen Thanks for suggesting above behaviour for snapshot creation. We will get back to you after having internal discussion about this.

**Comment by ashish-goswami** [comment]
Hey @JimWen, from v20.03.0 we have support for incremental rollups(https://github.com/dgraph-io/dgraph/pull/4972). This means rollups does not happen just after snapshot creation. Rollups now keep happening in background, this should avoid sudden spike in system resources.

**Comment by JimWen** [comment]
> Hey @JimWen, from v20.03.0 we have support for incremental rollups(#4972). This means rollups does not happen just after snapshot creation. Rollups now keep happening in background, this should avoid sudden spike in system resources.

Really good news, but i have a problem with exporting data if i want to use the new version dgraph(#5204 ).  Wait for your help.

**Comment by ashish-goswami** [comment]
Hey @JimWen, I am closing this for now. Let me know you experience with incremental rollups once you upgrade to v20.03.0. After upgrade, if you still experience the issue, feel free to reopen it.
