### ISSUE TITLE
Inconsistent GraphQL schemas reported by Alpha and Ratel (GraphiQL agrees with Ratel)

### ISSUE THREAD

**Issue by giolekva** [dgraph-io/dgraph#5249]
I have a client code pushing new GraphQL schema using updateGQLSchema method on /admin endpoint.
Server returns success and querying new schema from that same client right away correctly returns new schema.
Adding new nodes using GraphQL auto-generated add functions works as well.
But when querying same /admin endpoint with GraphiQL I get old schema. Ratel returns same old schema as well.
Once I was able to mitigate this issue by restarting the Dgraph server.
Looking at the logs generated my code new GQL schema gets an id of "0x11171" while getGQLSchema() run from GraphiQL returns id "0x1".

My 2cents: I went through the Dgraph code and logs briefly and if I understand correctly there is some logic of committing new schemas. Which I suspect in this case was not run. Might be wrong though, this is first time I looked inside the implementation.

### What version of Dgraph are you using?
Using latest Docker image which as of filing this issue https://hub.docker.com/layers/dgraph/dgraph/latest/images/sha256-f0355f32b271764a718cbe720f58d4a11bee9aa6f3193299f61766782792a9be?context=explore

### Have you tried reproducing the issue with the latest release?
Happens both with latest and master.

### What is the hardware spec (RAM, OS)?
Running on Minikube cluster with officially released latest build.

### Steps to reproduce the issue (command/config used to run Dgraph).
1) Run Dgraph using latest or master release
2) See logs bellow for operations

### Expected behaviour and actual result.
All clients should be getting same schema.

### GraphiQL returns
{
  "data": {
    "getGQLSchema": {
      "id": "0x1",
      "schema": "type ZZ { XX: ID! YY: Int } "
    }
  }
}

### Logs
I0420 09:40:18.444428      55 dgraph_schema_store.go:64] Getting GraphQL schema with query: { "query": "{ getGQLSchema() { schema } }" }
I0420 09:40:18.451136      55 dgraph_schema_store.go:69] Response status code: 200
I0420 09:40:18.451327      55 dgraph_schema_store.go:74] Result: {"data":{"getGQLSchema":{"schema":" interface Node {    id: ID! }  type Image implements Node {      objectPath: String! @search(by: [exact])      segments: [ImageSegment] @hasInverse(field: sourceImage) }  type ImageSegment implements Node {      upperLeftX: Int!      upperLeftY: Int!      lowerRightX: Int!      lowerRightY: Int!      sourceImage: Image!      objectPath: String }  type XYZ implements Node {      ch: Float! }"}}}
I0420 09:40:18.451840      55 dgraph_schema_store.go:46] Setting GraphQL schema:
I0420 09:40:18.451920      55 dgraph_schema_store.go:47] 
interface Node {
	  id: ID!
}
type Image implements Node {
     objectPath: String! @search(by: [exact])
     segments: [ImageSegment] @hasInverse(field: sourceImage)
}
type ImageSegment implements Node {
     upperLeftX: Int!
     upperLeftY: Int!
     lowerRightX: Int!
     lowerRightY: Int!
     sourceImage: Image!
     objectPath: String
}
type XYZ implements Node {
     ch: Float!
}
I0420 09:40:18.480915      55 dgraph_schema_store.go:53] Response status code: 200
I0420 09:40:18.481098      55 dgraph_schema_store.go:58] Result: {"data":{"updateGQLSchema":{"gqlSchema":{"id":"0x11171","schema":" interface Node {    id: ID! }  type Image implements Node {      objectPath: String! @search(by: [exact])      segments: [ImageSegment] @hasInverse(field: sourceImage) }  type ImageSegment implements Node {      upperLeftX: Int!      upperLeftY: Int!      lowerRightX: Int!      lowerRightY: Int!      sourceImage: Image!      objectPath: String }  type XYZ implements Node {      ch: Float! }"}}}}
I0420 09:40:18.481115      55 dgraph_schema_store.go:64] Getting GraphQL schema with query: { "query": "{ getGQLSchema() { schema } }" }
I0420 09:40:18.484331      55 dgraph_schema_store.go:69] Response status code: 200
I0420 09:40:18.484749      55 dgraph_schema_store.go:74] Result: {"data":{"getGQLSchema":{"schema":" interface Node {    id: ID! }  type Image implements Node {      objectPath: String! @search(by: [exact])      segments: [ImageSegment] @hasInverse(field: sourceImage) }  type ImageSegment implements Node {      upperLeftX: Int!      upperLeftY: Int!      lowerRightX: Int!      lowerRightY: Int!      sourceImage: Image!      objectPath: String }  type XYZ implements Node {      ch: Float! }"}}}
I0420 09:41:40.959605      55 main.go:79] Received event from Minio: {"EventName":"s3:ObjectCreated:Put","Key":"images/P7260029.jpg","Records":[{"eventVersion":"2.0","eventSource":"minio:s3","awsRegion":"","eventTime":"2020-04-20T09:41:40Z","eventName":"s3:ObjectCreated:Put","userIdentity":{"principalId":"minio"},"requestParameters":{"accessKey":"minio","region":"","sourceIPAddress":"127.0.0.1"},"responseElements":{"x-amz-request-id":"16077DC9F23971E0","x-minio-deployment-id":"fa6465f3-9657-48bf-82a2-54aa5be3a7f1","x-minio-origin-endpoint":"http://172.17.0.15:9000"},"s3":{"s3SchemaVersion":"1.0","configurationId":"Config","bucket":{"name":"images","ownerIdentity":{"principalId":"minio"},"arn":"arn:aws:s3:::images"},"object":{"key":"P7260029.jpg","size":358465,"eTag":"0326271ef7ca495043a1b74de17df209-1","contentType":"image/jpeg","userMetadata":{"content-type":"image/jpeg"},"versionId":"1","sequencer":"16077DC9F41C38A7"}},"source":{"host":"127.0.0.1","port":"","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15"}}]}
I0420 09:41:40.960546      55 main.go:32] Insering new item, mutation query:
I0420 09:41:40.960573      55 main.go:33] { "query": "mutation { addImage(input: [{ objectPath: \"images/P7260029.jpg\"}]) { image { id } } }" }
I0420 09:41:40.970462      55 main.go:35] Response status: 200
I0420 09:41:40.970820      55 main.go:43] Response: {"data":{"addImage":{"image":[{"id":"0x1117a"}]}}}

**Comment by giolekva** [comment]
Note that this happens only when using updateGQLSchema and not when manually uploading schema using /admin/schema endpoint.

**Comment by MichaelJCompton** [comment]
I suspect we have fixed this issue.  We recently fixed a schema upload bug that could cause two GraphQL schemas to exist.

That fix should go into a 20.03.x patch.

I'll hold this issue open and confirm when we release a patch.

**Comment by giolekva** [comment]
After upgrading to new version can verify that now I'm able to set schema using updateGraphqlSchema mutation, and that it gets reflected on both /graphql and /admin endpoints.

Thanks!!
