### ISSUE TITLE
Bulk Load Enhancements

### ISSUE THREAD

**Issue by n3integration** [dgraph-io/dgraph#5282]
## Experience Report

Note: Feature requests are judged based on user experience and modeled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### What you wanted to do

Bulk load a large dataset within a few hours

### What you actually did

Bulk loaded a large dataset over the course of a few days

### Why that wasn't great, with examples

One issue when bulk loading large datasets is with error handling. The error messages displayed can sometimes be cryptic and don't always help to quickly pinpoint the issue. For example, if bulk loading several hundred or thousand files and a schema violation occurs, an error message that includes the invalid nquad would make huge strides towards improving the experience when debugging large datasets being bulk loaded.

Although this is a suggestion, I think that a 'dry-run' option could go a long way in improving the experience when executing a bulk load that takes several hours to execute. An invalid nquad that might not be detected until several hours into the map phase could possibly be detected within minutes.

**Comment by MichelDiz** [comment]
Hey sir, (dunno your name)

Thanks for the issue. I think there is some other issues that covers this. So it is a potential duplicated. I gonna check it tomorrow.

Quick question, how big is your dataset? or your datasets? or what is the bigger one you have that is causing the issue?

Cheers.

**Comment by ashish-goswami** [comment]
Yes, related to https://github.com/dgraph-io/dgraph/issues/4395

**Comment by n3integration** [comment]
Hey @MichelDiz / @ashish-goswami  - My bad. I didn't see the other issue, but to answer your question: one of the datasets was roughly ~10b nquads.

**Comment by MichelDiz** [comment]
@ashish-goswami also there is this one https://github.com/dgraph-io/dgraph/issues/3984
This one says the issue before to load and 4395 logs the issue during a load. Not sure what is best.

@n3integration I gonna close it. Feel free to follow both issues if you are interested in this. Give your support, if it is a popular issue. It can be prioritized in some moment.

Cheers.
