### ISSUE TITLE
GraphQL Schema Not support <> using   @dgraph(pred: "<other language>")

### ISSUE THREAD

**Issue by zhaolin-st** [dgraph-io/dgraph#5296]
```
type Call {
    from: phone_number @hasInverse(field: calling) @dgraph(pred: "<FROM>")
    to: phone_number @hasInverse(field:called) 
}
```
Using graphql to update schema with @dgarph would not work while muation
![image](https://user-images.githubusercontent.com/30283563/80296619-5dbe4a80-87af-11ea-8ea6-f3d9e2b1f047.png)
Dgraph Schema would generate a "<FROM>" predicate ,but there should not be "<>" in real schema data
![image](https://user-images.githubusercontent.com/30283563/80296625-657def00-87af-11ea-8cd8-acdb6dc34adf.png)

![image](https://user-images.githubusercontent.com/30283563/80296654-85adae00-87af-11ea-8d6a-79840e0d7237.png)

**Comment by MichelDiz** [comment]
Angular brackets are exclusive for `GraphQL+-`, there's no support in GraphQL Specs tho. So don't use `<>` in your GraphQL schema.

Cheers.

**Comment by zhaolin-st** [comment]
> Angular brackets are exclusive for `GraphQL+-`, there's no support in GraphQL Specs tho. So don't use `<>` in your GraphQL schema.
> 
> Cheers.

@draph（pred: "***"） dont't support other language if don't use "<>"

**Comment by MichelDiz** [comment]
Sorry, but what do you mean by support other language? the edge is UID type. There's no language support for UID, only Strings.

**Comment by MichelDiz** [comment]
Oh, you mean  i18n. Not sure if GraphQL specs support i18n. I gonna check.

**Comment by MichelDiz** [comment]
I wasn't able to find anything about i18n predicates in https://spec.graphql.org/
I have found some examples with i18n in the data, not the predicate see https://codesandbox.io/s/graphql-i18n-demo-znxvd

@MichaelJCompton is there support for languages in predicates in GraphQL?

**Comment by zhaolin-st** [comment]
https://graphql.dgraph.io/docs/dgraph/
I show "@dgraph" in this page about "GraphQL on Existing Dgraph"
> Dgraph also allows type and edge names that aren’t valid in GraphQL, so, often, you’ll need to expose valid GraphQL names. Dgraph admits special characters and even different languages (see here), while the GraphQL Spec requires that type and field (predicate) names are generated from /[_A-Za-z][_0-9A-Za-z]*/.

> By default, Dgraph generates a new predicate for each field in a GraphQL type. The name of the generated predicate is composed of the type name followed by a dot . and ending with the field name. Therefore, two different types with fields of the same name will turn out to be different Dgraph predicates and can have different indexes. 

Can I use @dgraph(pred: "***") in other language?

**Comment by MichaelJCompton** [comment]
Hi, 

This should work to allow you to map GraphQL compliant names down to names in other languages.  

I'll arrange this to be looked at in our next sprint and we'll patch it for 20.03.2 and master.
