### ISSUE TITLE
Ensure DGraph supports GraphiQL out of the box

### ISSUE THREAD

**Issue by koppula** [dgraph-io/dgraph#53]
[GraphiQL](https://github.com/graphql/graphiql) allows for in-browser interactive style querying and inspection of results (and other associated features). Investigate what it takes to make sure GraphiQL is supported out of the box with DGraph.

**Comment by manishrjain** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;67Oq9z33&#x2F;2-investigate-a-tool-based-on-graphiql-to-allow-for-in-browser-interactive-style-querying-and-inspection-of-results"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Investigate a tool based on GraphiQL to allow for in-browser interactive style querying and inspection of results</a>

**Comment by manishrjain** [comment]
Tracking in Trello. Closing here.
