### ISSUE TITLE
GraphQL Mutation Consume all memory

### ISSUE THREAD

**Issue by zhaolin-st** [dgraph-io/dgraph#5315]
I try to do mutation using GraphQL, this Consume all memory，and the server has not responded for a long time
![image](https://user-images.githubusercontent.com/30283563/80462525-6ce8f800-8969-11ea-8b91-11c70867750d.png)

the data is a Json Array about 400 lines.

![image](https://user-images.githubusercontent.com/30283563/80462128-dc121c80-8968-11ea-92c2-6ce99bdaa35b.png)

**Comment by zhaolin-st** [comment]
I have define idcard as "@id"  in  graphql schema

**Comment by MichaelJCompton** [comment]
Hi, closing this in favour of https://github.com/dgraph-io/dgraph/issues/5400 so we can track just one issue.
