### ISSUE TITLE
Standard deviation does not work as expected

### ISSUE THREAD

**Issue by sleto-it** [dgraph-io/dgraph#5339]
### What version of Dgraph are you using?

20.03.1

### Steps to reproduce the issue (command/config used to run Dgraph).

See https://discuss.dgraph.io/t/standard-deviation/6241 and comment from Pawan

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8847). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
