### ISSUE TITLE
TLS Self Signed Certificate Docs for Dgraph Live

### ISSUE THREAD

**Issue by darkn3rd** [dgraph-io/dgraph#5349]
## Documentation

The documentation for [TLS self signed certificates](https://dgraph.io/docs/deploy/#self-signed-certificates) is confusing and misleading.

Explicitly:
```bash
# Create node certificate (needed for Dgraph Live Loader using TLS)
$ dgraph cert -n live
```
This leads the user to believe that the string `live` is needed for a `dgraph live` command.  This confused me as a new user and also confused a user in discuss.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8519). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
