### ISSUE TITLE
TLS Options Documentation Not Working with v20.03.1

### ISSUE THREAD

**Issue by darkn3rd** [dgraph-io/dgraph#5350]
## Documentation

The documentation for [TLS Options](https://dgraph.io/docs/deploy/#tls-options) does not work in curent version `v20.03.1`

Specifically this no longer works:

```bash
# Now, connect to server using TLS
$ dgraph live --tls_dir tls -s 21million.schema -f 21million.rdf.gz
```

### Workaround

The correct command depends on how the certificate was setup, and also the host that the service is running on.  I was able to get it working with this:

```bash
dgraph live \
  --tls_cacert ./tls/ca.crt \
  --tls_cert ./tls/client.user.crt \
  --tls_key ./tls/client.user.key \
  --tls_server_name "$(hostname -f)" \
  -s 21million.schema \
  -f 21million.rdf.gz
```

I setup my environment with this:

```bash
curl -sSf https://get.dgraph.io | VERSION="v20.03.1" bash
dgraph cert
dgraph cert -n $(hostname -f)
dgraph cert -c user
dgraph zero --my="$(hostname -f):5080" --idx 1
dgraph alpha --my=$(hostname -f):7080 \
 --zero $(hostname -f):5080 \
  --lru_mb 2048 \
  --tls_dir=./tls \
  --tls_client_auth=REQUIREANDVERIFY
```

**Comment by darkn3rd** [comment]
I was hoping an engineer could look at this, verify if this was a feature at all.  But in mean time editing documentation to show another path.

**Comment by gumupaier** [comment]
I had the same problem,

`Error: unknown flag: --tls_dir
`

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8520). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
