### ISSUE TITLE
(GraphQL API) Add/UpdateTypePayload use lowercase instead of camelCase for Type field

### ISSUE THREAD

**Issue by CosmicPangolin** [dgraph-io/dgraph#5380]
What version of Dgraph are you using?
20.03.1

Have you tried reproducing the issue with the latest release?
Yep

What is the hardware spec (RAM, OS)?
N/A

Steps to reproduce the issue (command/config used to run Dgraph).
N/A

Expected behaviour and actual result.
Currently type-named payload fields are lowercase instead of camelCase.  This seems at odds with the rest of the query structure (eg, query/mutation names and other generated fields throughout the schema).

![image](https://user-images.githubusercontent.com/40650466/81236349-da240b00-8fb1-11ea-9c47-cdbd84ef5e31.png)

**Comment by MichaelJCompton** [comment]
That's a great catch.  Thanks!  Looks like we are lower casing the whole type, rather than the first char when we make that.

It'll be a breaking change, so can't go into 20.03.x, would have to go into 20.07.0.
