### ISSUE TITLE
As a user, I would like to fix typo in flag params without having to `rm -rf *` files.

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#5398]
### What you wanted to do

I wanted to change the param from a flag and expect a normal functionality of the nodes.

### Why that wasn't great, with examples

Let's say I have a typo in the flag `--my`. The user needs to fix this by removing the DB files (which basically means having to delete the DB to fix a typo), as it is hard recorded (persisted) in the hard drive. That's a bad experience for new users and newbies.

We should overwrite the values. I think they are recorded in badger format internally.

Originally seen on https://discuss.dgraph.io/t/unable-to-add-mutations-cannot-retrieve-predicate-information-no-connection-exists/6641

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8526). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
