### ISSUE TITLE
Run mutations concurrently per predicate in Ludicrous mode

### ISSUE THREAD

**Issue by lgalatin** [dgraph-io/dgraph#5403]
### What version of Dgraph are you using?
20.03.1

### Have you tried reproducing the issue with the latest release?

yes
### Steps to reproduce the issue (command/config used to run Dgraph).
Please see https://discuss.dgraph.io/t/dgraph-cant-idle-without-being-oomkilled-after-large-data-ingestion/6543

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8527). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
