### ISSUE TITLE
As a user, I would like to group by "value" instead of just edges.

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#5412]
## Experience Report

This issue can be solved by #5335 if we don't wanna do any specific approach for it some how.

> We wanna see if this topic is popular or not. Please, share your use cases and "vote" this.

### What you wanted to do

Run the groupby func in value edges.

https://dgraph.io/docs/query-language/#groupby

### What you actually did

See https://discuss.dgraph.io/t/suggestions-to-improve-groupby/4630

### Why that wasn't great, with examples

See https://discuss.dgraph.io/t/suggestions-to-improve-groupby/4630

### Any external references to support your case

This issue is similar but it is related to LIST TYPE https://github.com/dgraph-io/dgraph/issues/4170
See this questions https://discuss.dgraph.io/t/how-to-groupby-date/3040
There are other questions which I don't remember the link, but are several.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8529). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by MichelDiz** [comment]
This was partially fixed by https://github.com/dgraph-io/dgraph/pull/7746
But needs improvement

**Comment by MichelDiz** [comment]
I have added a Cherry-pick PR #8550 that would be a potential fix for this issue.
