### ISSUE TITLE
graphql schema won't parse comments

### ISSUE THREAD

**Issue by livetocode** [dgraph-io/dgraph#5423]
### What version of Dgraph are you using?

v20.03.1

### Have you tried reproducing the issue with the latest release?

yes

### What is the hardware spec (RAM, OS)?

MacOS 16GB

### Steps to reproduce the issue (command/config used to run Dgraph).

Following the quickstart (https://graphql.dgraph.io/docs/quick-start/):

I started DGraph using the following command:
```bash
 docker run -it  -p 8080:8080 dgraph/standalone:v20.03.1
```

Then I created a file named "schema.graphql" and inserted a comment at the beginning, like this:

```graphql
# This is a comment

type Product {
    productID: ID!
    name: String @search(by: [term])
    reviews: [Review] @hasInverse(field: about)
}

type Customer {
    username: String! @id @search(by: [hash, regexp])
    reviews: [Review] @hasInverse(field: by)
}

type Review {
    id: ID!
    about: Product!
    by: Customer!
    comment: String @search(by: [fulltext])
    rating: Int @search
}
```

Then I issued the following command to process the schema:
```curl
curl -X POST localhost:8080/admin/schema -d '@schema.graphql'
```

### Expected behaviour and actual result.

Expected a success but received the following error:

```javascript
{
   "errors":[
      {
         "message":"couldn't rewrite mutation updateGQLSchema because while parsing GraphQL schema: input:100: expected at least one definition, found }",
         "extensions":{
            "code":"Error"
         }
      }
   ]
}
```

Note that without the comment in the schema, DGraph will happily parse the submitted schema.

**Comment by pawanrawal** [comment]
The schema should work fine if `--data-binary` flag is used instead of `-d`. So please try the command below.

```
curl -X POST localhost:8080/admin/schema --data-binary '@schema.graphql'
```
Using `-d` removes newlines and merges the comment, type definition causing errors.

**Comment by livetocode** [comment]
Hi,
Thanks for your quick answer.
I'm sorry, I didn't realize that the -d option would cause the problem!
I confirm that using  --data-binary works perfectly!
I suggest that you update your documentation to avoid such errors in the future, or at least that you explain it better.
Thanks
