### ISSUE TITLE
Shortest path query returns paths with repeated nodes.

### ISSUE THREAD

**Issue by anurags92** [dgraph-io/dgraph#5426]
### What version of Dgraph are you using?
Dgraph version   : v2.0.0-rc1-307-gf9d850994
Dgraph SHA-256   : b28d687729c9a1ec7642ea1797d800140c374f82c0ebab4f4e5e576f3676a374
Commit SHA-1     : f9d850994
Commit timestamp : 2020-05-11 05:19:53 +0530
Branch           : master
Go version       : go1.14

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
RAM: 16GB
OS: Ubuntu 18.04.4 LTS

### Steps to reproduce the issue (command/config used to run Dgraph).
Mutation:
```
{
  set {
    <1> <name> "Michonne" .
    <24> <name> "Glenn Rhee" .
    <31> <name> "Andrea" .
    <1000> <name> "Alice" .
    <1001> <name> "Bob" .
    <1002> <name> "Matt" .
    <1003> <name> "John" .
    <1005> <name> "Tim" .
    <1006> <name> "Horton" .
    <1007> <name> "Oliver" .

    <1> <path> <31>  .
    <1> <path> <24>  .
    <31> <path> <1000> .
    <1000> <path> <1001> .
    <1000> <path> <1002> .
    <1001> <path> <1002> .
    <1002> <path> <1003> .
    <1001> <path> <1003> .
    <1003> <path> <1001> .
    <1002> <path> <1005> .
    <1005> <path> <1006> .
    <1006> <path> <1007> .
  }
}
```
Query:

```
{
A as shortest(from: 1, to:1002, numpaths: 3) {
	path
        }

me(func: uid( A)) {
	name
        }
}
```

### Expected behaviour and actual result.
IMO expected behavior should be to return only two paths. `1-31-1000-1002` and `1-31-1000-1001-1002`. 
Actual result:
`1-31-1000-1002`, `1-31-1000-1001-1002` and `1-31-1000-1002-1003-1001-1002`.

**Comment by lgalatin** [comment]
Fixed in #4510
