### ISSUE TITLE
Optimizing sum() performance 

### ISSUE THREAD

**Issue by lgalatin** [dgraph-io/dgraph#5432]
Based on performance #s in this discuss post: https://discuss.dgraph.io/t/optimizing-sum-performance-dgraph-takes-10s-16-vcpu-128gb-ram-postgresql-takes-1-12s-4vcpu-16gb-ram/6684 We need to look into what is causing the slowdown.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8532). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
