### ISSUE TITLE
@hasInverse is needed only in one  type definition and not Both

### ISSUE THREAD

**Issue by vadavallipavan** [dgraph-io/dgraph#5443]
## Documentation
The below directives section advises that the @hasInvese directive needs to be specified in both types. But i believe its not needed in both the types.  Please advise
https://graphql.dgraph.io/docs/schema/#Directives
![image](https://user-images.githubusercontent.com/32944428/81994346-40212a00-9665-11ea-9474-55bb7bd5dd8b.png)

**Comment by MichaelJCompton** [comment]
Hi, sorry that the docs were misleading there.  Yes it's only required in one direction (but it's valid to have it both ways).

I've touched up the docs to remove this confusion.
