### ISSUE TITLE
Alpha: Server is not ready to accept request

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/dgraph#5452]
### What version of Dgraph are you using?
4fce857829195bfc4bf45839a51aa20ed39b69f7
### Have you tried reproducing the issue with the latest release?
No.

### What is the hardware spec (RAM, OS)?
N/A

### Steps to reproduce the issue (command/config used to run Dgraph).
Run bulk loader
1. Start zero `dgraph zero`
2. Run bulk loader 
```
dgraph bulk -f $GOPATH/src/github.com/dgraph-io/benchmarks/data/21million.rdf.gz \
-s $GOPATH/src/github.com/dgraph-io/benchmarks/data/21million.schema -z localhost:5080
```
3. Start Alpha `dgraph alpha -p out/0/p`
4. Kill alpha
5. Remove the out directory `rm -rf out`
6. Start Alpha again `dgraph alpha`

Alpha continuously dumps
```
I0514 16:18:52.893580   28070 admin.go:520] Error reading GraphQL schema: Dgraph query failed because Dgraph query failed because Please retry again, server is not ready to accept requests.
```
Any requests sent to alpha return
```
Please retry again. Server is not ready to accept the request
```

### Expected behaviour and actual result.
Alpha should respond to queries :man_shrugging:

**Comment by jarifibrahim** [comment]
I noticed that I can't gracefully stop alpha with `ctrl+C` once it goes into this state.

**Comment by JatinDevDG** [comment]
Not able to reproduce.

**Comment by JatinDevDG** [comment]
Not able to reproduce.

**Comment by brent-williams** [comment]
Just hit this as well.  Seems completely unacceptable to simply close the issue without any attempt at resolution.

**Comment by brent-williams** [comment]
@jarifibrahim if it helps you any we tracked the same repeated error you saw to a file permissions issue, with that fixed the error went away for us.

**Comment by jarifibrahim** [comment]
Awesome @brent-williams. Was this file created by dgraph?

Can you give me bit more details about what did you change so that it can help future users?

**Comment by brent-williams** [comment]
Hi @jarifibrahim in our case we were using explicit paths w/ dgraph --wal | -p | -w.  The folder permissions were inadvertently changed and that led to the nonsensical repeated error message that you saw as well, "Dgraph query failed because Dgraph query failed because Please retry again".  With the permissions fixed things were back to normal.  Hope that helps.

**Comment by jarifibrahim** [comment]
Thanks for explaining @brent-williams 👍🏻
