### ISSUE TITLE
Dgraph GraphQL field validation via @custom()

### ISSUE THREAD

**Issue by geoyws** [dgraph-io/dgraph#5455]
## Experience Report

Note: Feature requests are judged based on user experience and modeled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### What you wanted to do

Performantly be able to do field validation (min/max integers, regex checks) using [Custom Logic](https://graphql.dgraph.io/docs/custom-logic/) or some other directive, without having to resort to HTTP calls. Original discussion [here](https://discuss.dgraph.io/t/graphql-custom-logic/6483/6).

**Comment by MichaelJCompton** [comment]
Thanks.  Added into our internal discussions.  I'll repost here if we pick it up and start further scoping of this feature.

**Comment by machship-mm** [comment]
I'd also like to see this. Would be particularly handy for collections also to enforce min/max length of the collection.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8534). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
