### ISSUE TITLE
Bulk load documentation --xidmap

### ISSUE THREAD

**Issue by ahctangU** [dgraph-io/dgraph#5486]
* Doc page: [deploy/index.md](https://dgraph.io/docs/deploy/)
* Doc version: `release/v20.03.1`

Bulk loader documentation talks about an --xidmap option, but it doesn't exist in v20.03.0

**Comment by anurags92** [comment]
@ahctangU Thanks for pointing out. Looks like a mismathc between doc version and release version. Let me take a look and get back. In the meanwhile if you wish to use `--xidmap`, its there in the master.

**Comment by anurags92** [comment]
@ahctangU Quick update: We released documentation commits in release/v20.03.1 but failed to cherry-pick the actual feature commits in release/v20.03.1. We plan to release the feature in release/v20.03.3. Like I said before you can build from master if you wish to test `--xidmap` flag.
