### ISSUE TITLE
Store arbitrary key-values to each edge

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#549]
Many people have asked for this feature. We should be able to store key-value pairs our `Posting`, so users can attach relevant information to each edge.

The best way I find this useful is the `film -> intermediate -> actor` relation in Freebase film data. The intermediate node is only present to allow attaching character information. But, this small detail, impacts all queries which now have to go 2 levels deep, just to ask for the cast of a movie.

Instead, one could directly go `film -> actor`, and attach character information to this edge (stored in Posting), and ask for this information if required.

**Comment by lazharichir** [comment]
300% behind this idea!

**Comment by ashishnegi** [comment]
We can now store and fetch `facets` (edges' key values) from commit [fd5b1887fbbfd9b](https://github.com/dgraph-io/dgraph/commit/fd5b1887fbbfd9b25e352afbbe51939a6f3840f2) onwards.
