### ISSUE TITLE
GraphQL: "Non-nullable field was not present in result" on identically named fields under interface

### ISSUE THREAD

**Issue by CosmicPangolin** [dgraph-io/dgraph#5516]
### What version of Dgraph are you using?
2020.03.1

### Have you tried reproducing the issue with the latest release?
Yah

### What is the hardware spec (RAM, OS)?
GCloud 8GB VM

### Steps to reproduce the issue (command/config used to run Dgraph).
Consider the following schema:

```
type User {
     id: ID!
}

interface Things {
    id: ID!
    name: String!
}

type Stuff {
    id: ID!
    things: [Things!]
}

type ThingOne implements Things {
    creator: User!
}

type ThingTwo implements Things {
    creator: User!
}

type ThingThree implements Things {
    randomField: Int!
}
```

And, for Stuff containing some Things, a query of the form:
```
query {
     getStuff(id: "1337") {
          things {
               ...on ThingOne { creator {id} }
               ...on ThingTwo { creator {id} }
               ...on ThingThree { randomField }
          }
     }
}

```
### Expected behaviour and actual result.
This query fails with "Non-nullable field was not present in result" for one of the creator fields.  This seems to only be the case when fields share the same name, types share the same interface, but field is not in interface.

**Comment by abhimanyusinghgaur** [comment]
Hi @CosmicPangolin,

This is most probably related to: #4878, as you have defined a `User` type which is also the name of the type which dgraph uses for storing ACL users and as you report that the problem is with `creator` fields which is of type `User`. We have a fix coming up for that.

Also, your query seems incomplete. As `creator` is of type `User`, it should have a selection set like this:
```
query {
     getStuff(id: "1337") {
          things {
               ...on ThingOne { creator { id } }
               ...on ThingTwo { creator { id } }
               ...on ThingThree { randomField }
          }
     }
}
```

But, please also update the issue description with the initial mutations you ran in order for us to reproduce this error.

**Comment by abhimanyusinghgaur** [comment]
Linking another similar issue: #5366.

**Comment by CosmicPangolin** [comment]
I can confirm that, in my case, this has nothing to do with the type `User`.  I renamed models/schma to `Human` and the same error persists.  I am not using ACL.

**Comment by abhimanyusinghgaur** [comment]
Thanks @CosmicPangolin.

This is a bug regarding fragment handling.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8851). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
