### ISSUE TITLE
Zero's /health endpoint returns just "Ok" where the same Alpha's endpoint returns a JSON

### ISSUE THREAD

**Issue by lukaszlenart** [dgraph-io/dgraph#5517]
I'm testing Dgraph 1.2.3 version and notice there is a difference in `/health` endpoints for Zero and Alpha. It would be good to unify that endpoint to return the same JSON structure.

Zero's response to `curl http://localhost:6080/health`
```
Ok
```

Alpha's reponse to `curl http://localhost:8080/health`:
```
{"version":"v1.2.3","instance":"alpha","uptime":59131}
```

**Comment by MichelDiz** [comment]
Also, let's add `"leader":"true"`

**Comment by tharun208** [comment]
I like to work on this @MichelDiz

**Comment by MichelDiz** [comment]
@tharun208 feel free. I think there's no dev working on it right now.

cc @lgalatin

**Comment by tharun208** [comment]
@MichelDiz , Started with it and found that cyclic dependency is occurring. Can we pull out this `healthCheck` to a separate package?

**Comment by MichelDiz** [comment]
@tharun208  You can do anything, someone will have to review it. Since I don't manage these codes, I don't have the competence to determine something there. But if your change doesn't break anything. It will be welcome.

**Comment by MichelDiz** [comment]
Hey @tharun208, would you mind to add a "default" version? like "master". This would help this issue #5721

**Comment by tharun208** [comment]
> Hey @tharun208, would you mind to add a "default" version? like "master". This would help this issue #5721

@MichelDiz I am able to get the version number while working on this PR. My machine config is also `darwin i386`.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8852). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
