### ISSUE TITLE
Kubernetes port names don't match Istio's port naming conventions

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#5530]
### What version of Dgraph are you using?
v20.03.1 latest

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
Kubernetes

### Steps to reproduce the issue (command/config used to run Dgraph).

1. Run Dgraph on Kubernetes using dgraph-ha.yaml or helm chart.
2. Use Istio service mesh.

https://istio.io/docs/ops/configuration/traffic-management/protocol-selection/

Istio provides routing and metrics based on the protocol of the port. It follows a naming convention of `<protocol>[-suffix]` to get the protocol of the port, or by using `appProtocol`.

The sample port names from the Dgraph Kubernetes config don't follow this naming convention. For example, it uses `alpha-grpc` for port 9080 instead of `grpc-alpha`.

### Expected behaviour and actual result.

Changing the port names would give Istio users an easier time integrating with the default config.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8541). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
