### ISSUE TITLE
GraphQL mutation fails for larger number of nodes

### ISSUE THREAD

**Issue by dpeek** [dgraph-io/dgraph#5558]
### What version of Dgraph are you using?

```
docker run --rm -it -p 8080:8080 -p 9080:9080 -p 8000:8000 -v ~/dgraph:/dgraph dgraph/standalone:v20.03.0
```

### Have you tried reproducing the issue with the latest release?

I tried master but the docker image fails with:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./run.sh\": stat ./run.sh: no such file or directory": unknown.
```

### What is the hardware spec (RAM, OS)?

macOS, 2017 MBP, 16GB

### Steps to reproduce the issue (command/config used to run Dgraph).

Repro here: https://github.com/dpeek/dgraph-graphql-mutation-fails

### Expected behaviour and actual result.

Expected: mutation works, actual: it doesn't :)

**Comment by MichaelJCompton** [comment]
Suspect this is the same issue as here https://github.com/dgraph-io/dgraph/issues/5400

@harshil-goel can you check your fix with the test data above to confirm.

**Comment by harshil-goel** [comment]
Yup, the PR fixes the issue.
