### ISSUE TITLE
Recent changes in goldendata.rdf.gz not reflected in tests

### ISSUE THREAD

**Issue by tzdybal** [dgraph-io/dgraph#556]
Recent changes in ```goldendata.rdf.gz``` (dgraph-io/benchmarks@96dfcc2936b82a9481392b66432e58c7109c9025) are not reflected in ```contrib/loader.sh``` tests. This causes failures on builds of ```master``` branch.

```goldendata.rdf.gz``` was somehow cached on build servers and issue was not visible immediately. But when re-running Travis builds, tests are failing.

**Comment by pawanrawal** [comment]
Travis was fixed, closing this.
