### ISSUE TITLE
GraphQL query variable usage in geo filter

### ISSUE THREAD

**Issue by iluminae** [dgraph-io/dgraph#5565]
## Experience Report
In graphql+-, I have a need to inject variables into a geo query in the form of floats, but this results in a lexing error: `Found invalid item: $ while parsing geo arguments.`

### What you wanted to do
I want to use a query like the following:
```graphql
query xy($x: float, $y: float) {
  q(func: contains(mygeofield,[$x,$y])){
    uid
  }
}
```
Even though `$x` and `$y` are floats, I cannot use them as the float for the coordinates of the geo field.

### What you actually did
Query has to be constructed with Sprintf() or templates
```go
tx.Query(ctx,fmt.Sprintf(`{q(func: contains(mygeofield,[%f,%f])){  uid  }}`,x,y))
```

### Why that wasn't great, with examples
Obviously this is what alot of users do with Sprintf() style variable injection but it would be nicer to use my variables wherever I can. Probably don't need to get into why using sprintf is not a good way to manage queries.

### Any external references to support your case
none

**Comment by MichelDiz** [comment]
This is a duplicated of #2272

You can also do like
```
query geoq($loca:string = "[-122.469829, 37.771935]") {
  tourist(func: near(loc, $loca, 1000) ) {
    name
  }
}
```

**Comment by iluminae** [comment]
oh thanks @MichelDiz, did not realize that could be a string. I will close this since it is a clear duplicate, thanks again.
