### ISSUE TITLE
Releases for ARM64

### ISSUE THREAD

**Issue by TiemenSch** [dgraph-io/dgraph#5566]
## Experience Report

Hi, ARM64 support was already requested and confirmed as a conclusion of #3586, but official releases of Dgraph haven't been included. It would be awesome if the Docker images of Dgraph would be cross-compiled and included in the manifests so they work on ARM64 out of the box.

### What you wanted to do

Run Dgraph on my Raspberry Pi 4 K3s cluster. I believe that the enthousiasts (like me) that want to try out Dgraph might just have an ARM server or cluster at home which requires ARM64 binaries or images.

### What you actually did

Currently, I made a pipeline over at Gitlab that compiles to ARM64 and stores a Docker image. That image seems to work on my Raspberry Pi 4's as a demo cluster. See:

https://gitlab.com/Tiemen/dgraph-aarch64
registry.gitlab.com/tiemen/dgraph-aarch64:latest

### Why that wasn't great, with examples

It's better to have a single "official" source of cross-compiled images in a single manifest. I'm for instance not sure what the compiled binary expects on the system, which is why I don't know if I can get away with a clean alpine image with the binary dropped in in the long run. (e.g. user rights, folder structure, etc.)

### Any external references to support your case

My custom setup uses Docker buildx: https://docs.docker.com/buildx/working-with-buildx/
I would be happy to submit a PR that mimics this, but as this influences your release process (and I usually work with Gitlab pipelines) I'm not entirely sure how this should work.

**Comment by jamesjarvis** [comment]
+1 this, would be a great (and simple) addition to have multi-arch docker images 😄

**Comment by TiemenSch** [comment]
The most important binary by far is the dgraph one itself, as ratel should be able to run remotely and tap into your database. Compiling ratel was also slightly more tricky in my limited attempt. I think an initial PR for the dgraph binary only would already go a long way!

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8544). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
