### ISSUE TITLE
Update Docs on Background Indexing

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/dgraph#5568]
## Documentation

Chapter on [Background Indexing](https://dgraph.io/docs/master/query-language/#indexes-in-background) ends with

> We also plan to add a simpler API soon to check the status of background indexing. See this PR for more details.

But the linked PR is already merged. The docs should be updated to describe the new API, before the next major release is cut

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8546). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
