### ISSUE TITLE
graphql report errors when query if nest type value was removed

### ISSUE THREAD

**Issue by conanchen** [dgraph-io/dgraph#5589]
### What version of Dgraph are you using?
20.3.1

### Have you tried reproducing the issue with the latest release?
NO

### What is the hardware spec (RAM, OS)?
centos7

### Steps to reproduce the issue (command/config used to run Dgraph).
1. originaly Store has place value "0x2726" 
![image](https://user-images.githubusercontent.com/1233799/83959500-1d72e180-a8b0-11ea-8b57-a5ab0cbd7eec.png)
2. delete the place "0x2726"  
![image](https://user-images.githubusercontent.com/1233799/83959427-58c0e080-a8af-11ea-9926-a397700c28b9.png)
3. the property "identifier" of Place type 
Place {
    id: ID!
    identifier: String! @id
}
![image](https://user-images.githubusercontent.com/1233799/83959489-0207d680-a8b0-11ea-9eb5-748e67016f8b.png)

### Expected behaviour and actual result.
- if nest value was removed , it also should be not visible from the reference one .
- no need to  report error as the nest value does not exist . 
- getStore() should return place value as null instead of value with id "0x2726" and report error "identifier" as "0x2726" was removed from dgraph database. 
- no need to report error as the nest value was remove. 
{
  "data": {
    "getStore": {
      "id": "0x2725",
      "identifier": "04b32732-e21b-4084-bd0f-9b57472faff3",
      "name": "store update name1",
      "place": null
    }
  }
}

**Comment by arijitAD** [comment]
Can you share your GraphQL schema?

**Comment by conanchen** [comment]
Type Store {
id: ID!
identifier: String!
name: String
place: Place
}

type Place{
id: ID!
identifier: String!
name: String
}

**Comment by arijitAD** [comment]
Currently, how deletion works is that when we delete a type when don't delete its reference. You are getting the error because you queried a non-nullable field that is not present.

**Comment by conanchen** [comment]
That is the point, but Place maybe shared with other Types. That is type Place I don't want to have property {store: [Store]}, or else I need to add other reference type to it and the reference type value maybe null. How would I handle this case? 
```
type Place {
  id: ID!
  identifier: String!
  name: String
  store: [Store] @hasInverse(field: place)
  company:[Company] @hasInverse(field: place)
  OtherX:[OtherX] @hasInverse(field: place)
  OtherY:[OtherY] @hasInverse(field: place)
  OtherZ:[OtherZ] @hasInverse(field: place)

```
