### ISSUE TITLE
Allow to turn off compression for Badger

### ISSUE THREAD

**Issue by OmarAyo** [dgraph-io/dgraph#5602]
It would be useful we if can disable compression for Badger.

We already have this flag for alpha only: `--badger.compression_level int` with a default value of `3`. It would be useful if we can add the value `0` for turning it off 

It will be also great if we can add the same flag for zero as well 

Thanks

**Comment by jarifibrahim** [comment]
Closing this ticket since we don't have compression enabled in zero.
