### ISSUE TITLE
Post-hoc indexing

### ISSUE THREAD

**Issue by andreaferretti** [dgraph-io/dgraph#562]
Is there a way in dgraph to add indices to a running instance? From what I have understood, one can only declare a schema while starting the server. In practice, though, graph databases excel at merging data coming from non-homogeneous sources, and when a new dataset arrives, it would be nice to be able to add its schema

**Comment by manishrjain** [comment]
Hey @andreaferretti,

We're working on a better design for our schema. It would be dynamic, so you can add and remove things on a running instance. Also, adding a new index would automatically trigger rebuilding the index for the existing data, and all new data that flows in would be indexed accordingly. All this is in works.

For now, in v0.7.2, what you can do is you can trigger an index rebuild by calling a special endpoint `/admin/index?attr=<pred>`.

@jchiu0: Can you document this in wiki?

**Comment by andreaferretti** [comment]
@manishrjain Thank you, I will the endpoint for now. By the way, how strongly is the schema enforced? I see I can easily add data that does not follow the schema (e.g. has some fields missing)

**Comment by jchiu0** [comment]
Sure I will update the wiki and wrap this up.

**Comment by jchiu0** [comment]
Added a bit of documentation to https://wiki.dgraph.io/Query_Language#Indexing. Might want to close this issue.

**Comment by andreaferretti** [comment]
Thank you
