### ISSUE TITLE
Documentation does not update after schema (SDL) update

### ISSUE THREAD

**Issue by matthewmcneely** [dgraph-io/dgraph#5620]
### What version of Dgraph are you using?
Master (Image sha256:726532a57d043a5512a8abff42da5c9e5681e8a7ec993a10ffaee896e7d88410)

### Have you tried reproducing the issue with the latest release?
Yes that's where the issue is occuring, this is not an issue on v20.03.1

### What is the hardware spec (RAM, OS)?
MacMini, 16GB RAM, OSX, Docker 19.03.8

### Steps to reproduce the issue (command/config used to run Dgraph).
1. Start a standalone container
2. Load an initial schema (curl -v -X POST localhost:8080/admin/schema -d '@./internal/data/schema.graphql')
3. Check the documentation (using Altair)
4. Update that schema (I added a new field to a class)
5. Check the documentation again, the added field is not recognized

### Expected behaviour and actual result.
The behavior as reflected in v20.03.1 (the field is recognized after the schema update)

**Comment by MichaelJCompton** [comment]
Hi @matthewmcneely, yeah this isn't great, but it's an Altair bug, not a Dgraph one.  

As soon as you update the schema, the Dgraph instance is ready to go with the new schema and responds properly to introspection queries ... unfortunately, different GUIs behave differently.  I think, GraphQL Playground refreshes the schema tab, but the intellisense doesn't work. In Insomnia, however, it works perfectly. Pretty sure Firecamp also works. Looks like Altair doesn't work perfectly in this regard.

**Comment by matthewmcneely** [comment]
@MichaelJCompton Thanks, I checked with Firecamp (thanks for mentioning that, I wasn't aware of that tool) and it works.

**Comment by JLaferri** [comment]
This is a bit old but I find myself having a similar issue but I'm pretty sure the schema is actually not updating. Using firecamp did not change anything.

I am using Dgraph 21.03

https://user-images.githubusercontent.com/1534726/128327897-11df8b39-f3f9-4b6e-bfae-12d65431a5dc.mp4
