### ISSUE TITLE
get.dgraph.io/latest should allow CORS requests

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/dgraph#5628]
In-browser JS applications need to be able to read latest dgraph version from the `get.dgraph.io/latest` endpoint.

Examples when it can be useful:
- Ratel could warn admins when newer version of Dgraph is available
- Interactive Dgraph tour could auto-generate docker-compose file with latest image baked in
- etc.

Right now `get.dgraph.io/latest` endpoint is closed to any JS that isn't hosted on `get.dgraph.io/`.
For it to become accessible it should return [CORS HTTP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

cc @danielmai @darkn3rd

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8553). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
