### ISSUE TITLE
Support comments in Mutate commands

### ISSUE THREAD

**Issue by masonlr** [dgraph-io/dgraph#5640]
In the Mutate console, the following mutation works.

Mutation:

```json
{
  "set": [
  	{"name": "foo"}
	]
}
```

Response message:

```json
{
  "data": {
    "code": "Success",
    "message": "Done",
    "queries": null,
    "uids": {
      "dg.932529826.109": "0xc3be"
    }
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 46600,
      "processing_ns": 3764100,
      "assign_timestamp_ns": 1099500,
      "total_ns": 4977500
    },
    "txn": {
      "start_ts": 70252,
      "commit_ts": 70253,
      "preds": [
        "1-name"
      ]
    }
  }
}
```

When comments are added, an error is returned. For example:

Mutation:

```json
{
  "set": [
  	{"name": "outer"}
	]
}

# foo
```

Response:

```json
{
  "name": "t",
  "url": "http://localhost:8080/mutate?commitNow=true",
  "errors": [
    {
      "message": "while lexing {\n  \"set\": [\n  \t{\"name\": \"outer\"}\n\t]\n}\n\n# foo at line 2 column 2: Unrecognized character inside mutation: U+0022 '\"'",
      "extensions": {
        "code": "ErrorInvalidRequest"
      }
    }
  ]
}
```

**Comment by OmarAyo** [comment]
Hi @masonlr,

You should be able to add a comment by using rdf format. I am looking why with JSON it's not working

**Comment by OmarAyo** [comment]
Hi @masonlr 

So if you use JSON style for mutation, comments are not allowed in JSON.
On the other hand, if you use graphql+-, comments should be allowed

**Comment by MichelDiz** [comment]
Actually, if you prefer, you can comment using JSON keys outside the scope of the mutation. Dgraph will simply ignore any key other than "set" or "delete".
```
{
  "set": [
  	{"name": "foo"}
    ],
  "COMMENT": "this iss a comment",
  "//COMMENT": "this iss a comment",
  "#COMMENT": "this iss a comment"
}
```

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8556). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
