### ISSUE TITLE
Custom Functions: Can't use `_` in identifiers

### ISSUE THREAD

**Issue by ardan-bkennedy** [dgraph-io/dgraph#5641]
### What version of Dgraph are you using?

master

### Have you tried reproducing the issue with the latest release?

Only on master

### What is the hardware spec (RAM, OS)?

Mac with latest OS

### Steps to reproduce the issue (command/config used to run Dgraph).

I have to define function parameters and field names in the body like this.

```
type Query{
	uploadFeed(countryCode: String!, cityName: String!, lat: Float!, lng: Float!): UploadFeedResponse @custom(http:{
		url: "{{.UploadFeedURL}}",
		method: "POST",
		body: "{countrycode: $countryCode, cityname: $cityName, lat: $lat, lng: $lng}"
	})
}
```

If I attempt to use an underscore `_` I get an error. As an example, renaming`countryCode` to `country_code`:

```
type Query{
	uploadFeed(country_code: String!, cityName: String!, lat: Float!, lng: Float!): UploadFeedResponse @custom(http:{
		url: "{{.UploadFeedURL}}",
		method: "POST",
		body: "{countrycode: $countryCode, cityname: $cityName, lat: $lat, lng: $lng}"
	})
}
```

I get this error.

```
Type Query; Field uploadFeed; body template inside @custom directive could not be parsed.
```

This would also happen if I use underscores for fields in the `body` document.

### Expected behaviour and actual result.

I expect I can use JSON proper variable naming.

**Comment by arijitAD** [comment]
Thanks for reporting this. GraphQL specs allow `_` in variable naming. Hence it's a valid use case. https://spec.graphql.org/June2018/#sec-Names
Filing a bug.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8853). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
