### ISSUE TITLE
sentry: unable to write CID to file  open : no such file or directory

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#5695]
### What version of Dgraph are you using?
master

### Have you tried reproducing the issue with the latest release?
Does not happen in latest release. (introduced in #5625)

### What is the hardware spec (RAM, OS)?
Ubuntu Linux (Docker)

### Steps to reproduce the issue (command/config used to run Dgraph).

1. Run Dgraph cluster with sentry reporting enabled.
2. Restart Dgraph cluster with sentry reporting disabled (`--enable_sentry=false`).
3. See the following warning log in Alpha

`W0619 18:50:54.447838       1 sentry_integration.go:116] unable to write CID to file  open : no such file or directory`

### Expected behaviour and actual result.

The warning log seems harmless, but it shouldn't happen. This log tells me that Sentry is still trying to do something even when the flag is set to disable it. This is where I start being skeptical and paranoid on whether Sentry is enabled or not.

**Comment by parasssh** [comment]
We should not attempt to write the CID to a file when sentry is disabled. The check for enable_sentry is missing there. It should be harmless though. Rest assured. It is disabled and no reports are sent.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8560). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
