### ISSUE TITLE
Dgraph Zero Reports Errors when Alpha Connects

### ISSUE THREAD

**Issue by darkn3rd** [dgraph-io/dgraph#5707]
### What version of Dgraph are you using?

```
v20.07.0-beta.Jun15
```

### Have you tried reproducing the issue with the latest release?

Yep.

### What is the hardware spec (RAM, OS)?

* 8 vCPUs, 30 GB memory, 100 GB  HD
* Ubuntu Bionic Beaver

### Steps to reproduce the issue (command/config used to run Dgraph).

```bash
dgraph zero &
dgraph alpha --tls_dir ./tls -p p1 -w w1 &
dgraph alpha --tls_dir ./tls -p p2 -w w2 -o1 &
```

### Expected behaviour and actual result.
The expected is that errors would report errors, and non-errors would not report errors.
The actual results are the following when starting up 1st alpha and 2nd alpha.
```
I0622 19:41:27.283878   23691 zero.go:422] Got connection request: cluster_info_only:true
I0622 19:41:27.284102   23691 zero.go:440] Connected: cluster_info_only:true
I0622 19:41:27.285139   23691 zero.go:422] Got connection request: addr:"localhost:7080"
I0622 19:41:27.285354   23691 pool.go:160] CONNECTING to localhost:7080
W0622 19:41:27.286628   23691 pool.go:254] Connection lost with localhost:7080. Error: rpc error: code = Unknown desc = No node has been set up yet
I0622 19:41:27.288309   23691 zero.go:571] Connected: id:1 group_id:1 addr:"localhost:7080"
I0622 19:43:44.026371   23691 zero.go:422] Got connection request: cluster_info_only:true
I0622 19:43:44.026598   23691 zero.go:440] Connected: cluster_info_only:true
I0622 19:43:44.027507   23691 zero.go:422] Got connection request: addr:"localhost:7081"
I0622 19:43:44.027810   23691 pool.go:160] CONNECTING to localhost:7081
W0622 19:43:44.028838   23691 pool.go:254] Connection lost with localhost:7081. Error: rpc error: code = Unknown desc = No node has been set up yet
I0622 19:43:44.030501   23691 zero.go:571] Connected: id:2 group_id:2 addr:"localhost:7081"
```

**Comment by danielmai** [comment]
From what I understand, although these warning messages show up, the cluster still starts up healthy and can accept requests.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8562). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
