### ISSUE TITLE
Live Loader can ignore a record if that gives an error, and let it continue to the next records

### ISSUE THREAD

**Issue by antblood** [dgraph-io/dgraph#5709]
## Experience Report

Note: Feature requests are judged based on user experience and modeled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### What you wanted to do
I want live loader to ignore a record in case the record is faulty and caused an error

### What you actually did
I made changes to the faulty record and re-ran the live loader again for all the records that were left

### Why that wasn't great, with examples
This isn't great because I might want to put some records to load using live loader overnight and wakes up in the morning to see that the first file was faulty and because of which the other records also couldn't be processed.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8563). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
