### ISSUE TITLE
Health endpoint doesn't show a version when built from master

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#5721]
Health endpoint doesn't show a version (at 8080/health) when built from master - This causes a block on Ratel UI. Also, any Dgraph version will get blocked by this. Not sure if this needs to be fixed on Dgraph itself or Ratel. Pinging @paulftw.

2 potential bugs (both true, not sure if both can be solved at Dgraph side)
1 - When using master, ratel thinks I'm using an old version.
2 - Got "Unsupported Content-Type".

### What version of Dgraph are you using?
Master

### Have you tried reproducing the issue with the latest release?
yes

### What is the hardware spec (RAM, OS)?
Darwin 32GB

### Steps to reproduce the issue (command/config used to run Dgraph).

1. Build Dgraph from master or any PR.
2. Start Dgraph's cluster built from master and run Ratel.
3. Connect Ratel to http://localhost:8080 

![Captura de Tela 2020-06-24 às 11 55 45](https://user-images.githubusercontent.com/6570955/85580269-f63b4480-b611-11ea-860d-72a14f27c58d.png)

![Captura de Tela 2020-06-24 às 11 58 24](https://user-images.githubusercontent.com/6570955/85580354-094e1480-b612-11ea-82c2-411229856138.png)

4. Now open the console (F12)

You might see in some moment an error like:

```
Login Failed http://localhost:8080 Error: Pre v1.1 clients do not support Login methods
```

Also several errors like:

```
serverAclState error t: Unsupported Content-Type. Supported content types are application/json, application/graphql+-
```

This is a normal health endpoint

![Captura de Tela 2020-06-24 às 11 45 27](https://user-images.githubusercontent.com/6570955/85581113-af018380-b612-11ea-8871-a5103cf28cdb.png)

And this is the one from master/PR builds.

![Captura de Tela 2020-06-24 às 11 45 17](https://user-images.githubusercontent.com/6570955/85581158-b9bc1880-b612-11ea-97d0-5360f98893f1.png)

### Expected behaviour and actual result.

That it should work with master builds.

**Comment by tharun208** [comment]
@MichelDiz  I am able to get the version on the health endpoint. My machine configuration is `darwin i386`.

**Comment by rahulgurnani** [comment]
Also the version that is getting picked is incorrect. If you execute `git describe` of master branch, you will get `v2.0.0-beta1-508-g931b8a81b` which is not the latest tag. What we really want is `v20.07.0-beta.Jun22`

**Comment by rahulgurnani** [comment]
I can work on this.

**Comment by dmitryyankowski** [comment]
I'm on master and also getting the error `Pre v1.1 clients do not support Login methods` 

Any updates on this? Thanks

**Comment by rahulgurnani** [comment]
Raised a PR for this.

**Comment by MichelDiz** [comment]
@rahulgurnani This fixes the issue with the wrong tag. But the issue with empty values continues. Anyway, I have found that this happens only with `go build`. And I think the issue is that, we have to discourage users from building it with golang build. They must use `make dgraph`.

**Comment by rahulgurnani** [comment]
Yes they should be using make install. This also happens when running dgraph in debug mode.

**Comment by MichelDiz** [comment]
Sure, in VScode debug mode this is a blocker. We can't use Ratel there. Se we need a "default" value set for cases like that.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8566). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
