### ISSUE TITLE
Aggregate additional data per entities

### ISSUE THREAD

**Issue by roscopecoltran** [dgraph-io/dgraph#573]
Hi all,

Hope you are all well !

I was wondering if it would be possible to aggregate additional informations per entities, returned in a search result, by binding a recursive tree of local or remote micro-services, probably wrapped docker containers. (Kind of api gateway or aggregator of related data for each type of entities)

**Example**: get additional data about an actor from wikipedia, imdb and some computer vision webservice to find similar pictures of this person. Like a graph of sub-requests, and be able to filter the final output with a template, in the same spirit as https://github.com/devopsfaith/krakend.

Hope that the concept was clear enough ^^

Have a great day to all !

Cheers,
Richard

**Comment by manishrjain** [comment]
Hi @roscopecoltran,

I think such functionality is better handled outside the database. You can issue queries to the DB, retrieve results, then enhance them via calls to micro-services.

**Comment by RXminuS** [comment]
This is very related to and can probably be achieved with #662 in cases **where it's reasonable**. There's other databases that implement similar features, like RethinkDB's ability to fetch images by just storing the URI. However, do agree that this kind of suger should probably be handled in a layer on top of dgraph (preferably a GraphQL api ofcourse :-P )...so the image-fetching was probably a bad example of that.

**Comment by manishrjain** [comment]
At this point, we're not looking at making Dgraph reach out to other services. That might be possible with custom plugins; which we haven't started work towards. We'll probably start work on them after v1.0. For now, this is not a priority.
