### ISSUE TITLE
Get a list of edges for a datastore

### ISSUE THREAD

**Issue by clanstyles** [dgraph-io/dgraph#574]
When uploading a datastore, we might not know all the edges. Would it be possible to get a list of edges in some sort of "describe tables" fashion?

**Comment by manishrjain** [comment]
Do you mean a list of predicates, or all data normalized. If you mean a list of predicates, we're already thinking of doing that.

**Comment by clanstyles** [comment]
Yeah a list of predicates is what I mean. When using existing datasets it would be very helpful.

**Comment by pawanrawal** [comment]
Just a heads up, we use an endpoint to get the list of predicates from the dynamic schema for autocompletion in the UI. Is the idea to get the list of predicates from `/query` endpoint?

**Comment by janardhan1993** [comment]
Yes, we will get list of predicates from /query endpoint.

**Comment by janardhan1993** [comment]
You can get a list of predicates now by sending the following to /query endpoint

schema() {
}
