### ISSUE TITLE
Weird output for date fields

### ISSUE THREAD

**Issue by etix** [dgraph-io/dgraph#575]
On 0.7.2, inserting a date using an NQuad:
```
nq = graph.NQuad{
    Subject:   "clara",
    Predicate: "birthdate",
}
client.Date(time.Date(1980, 1, 10, 0, 0, 0, 0, time.Local), &nq)
req.AddMutation(nq, client.SET)
```

and fetched back using a simple query like this:
```
query
{
    me(id: "clara")
    {
        birthdate
    }
}
```

causes a super weird output:
```
[
    {
        "attribute": "_root_",
        "children": [
            {
                "attribute": "me",
                "properties": [
                    {
                        "prop": "birthdate",
                        "value": {
                            "Val": {
                                "DateVal": "AQAAAA6KaykAAAAAAP//"
                            }
                        }
                    }
                ]
            }
        ]
    }
]
```

**Comment by pawanrawal** [comment]
Hi @etix 

You would have to unmarshal the value as mentioned https://wiki.dgraph.io/Clients#Go to get the date in `time.Time` format. We transfer back the data in bytes which has to be parsed by the client to get the actual date. 

Though, I now think we can as well return back the date as string, which the client can parse using time.Parse(). I will make this change.

**Comment by pawanrawal** [comment]
Pushed a fix which will make this readable. It will be part of next release. Also updated the Wiki documentation.
