### ISSUE TITLE
There is no leader for group 3,I just add new alpha to the cluster,and in this situation,the dgraph is not usable

### ISSUE THREAD

**Issue by chengyu3075** [dgraph-io/dgraph#5766]
![image](https://user-images.githubusercontent.com/23020087/86091154-fb9b0200-badd-11ea-8ba7-76a2043a8aa1.png)

**Comment by chengyu3075** [comment]
![image](https://user-images.githubusercontent.com/23020087/86091974-5a14b000-badf-11ea-9025-9ed28acaabb9.png)
When I add a new alpha node to group 3,there is still no leader,and dgraph version is 20.03.1
![image](https://user-images.githubusercontent.com/23020087/86092112-9c3df180-badf-11ea-8864-f2dd69614bcc.png)

**Comment by NamanJain8** [comment]
@chengyu3075, Can you please let us know the following info:
1. The output of `/state` and `/health?all` endpoint.
2. Have you tried it for the latest version?
3. Steps to reproduce this. (at least the command you used to add the node to the cluster)

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8570). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
