### ISSUE TITLE
filter with eq list argument behaves differently without index

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#5767]
### What version of Dgraph are you using?
v20.03.3

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?

Ubuntu Linux, Docker

### Steps to reproduce the issue (command/config used to run Dgraph).

1. Run Dgraph cluster
2. Set the following schema with a string predicate:

   ```
   curl 'localhost:8080/alter' \
        -d 'name: string .'
   ```

2. Run the following mutation

   ```
   curl 'localhost:8080/mutate?commitNow=true' \
        -H "Content-Type: application/json" \
        -d '{"set":[{"uid":"_:root","connects":[{"name": "A"},{"name":"B"}]}]}'
   ```

3. Run the following query

   ```
   curl 'localhost:8080/query' \
        -H "Content-Type: application/graphql+-" \
        -d '
   {
     q(func: has(connects)) {
       connects @filter(eq(name, ["A", "B"])) {
         name
       }
     }
   }'
   ```

### Expected behaviour and actual result.

The actual query result is:

```
{
  "data": {
    "q": [
      {
        "connects": [
          {
            "name": "B"
          }
        ]
      }
    ]
  }
}
```

The expected query result is that `eq(name, ["A", "B"])` in the filter returns back both nodes A and B in the response.

If I set an index on the name predicate, then the filter works as expected.

Alter schema:
```
name: string @index(hash) .
```
Query response:
```
{
  "data": {
    "q": [
      {
        "connects": [
          {
            "name": "A"
          },
          {
            "name": "B"
          }
        ]
      }
    ]
  }
}
```

**Comment by danielmai** [comment]
Either the non-indexed behavior should align with the indexed behavior or we need to update the `eq()` [docs](https://dgraph.io/docs/query-language/#equal-to) to state that `eq(predicate, [val1, val2, ..., valN])` only works with indexed predicates.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8571). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
