### ISSUE TITLE
Dgraph Live cannot parse negative years

### ISSUE THREAD

**Issue by EnricoMi** [dgraph-io/dgraph#5778]
### What version of Dgraph are you using?
v20.03.3

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
Unrelated

### Steps to reproduce the issue (command/config used to run Dgraph).
Start a fresh temporary dgraph instance with docker:
```
docker run -it --rm dgraph/standalone:v20.03.3 /bin/bash
```

Inside, run the following commands:
```
dgraph zero > /dev/null 2>&1 < /dev/null &
dgraph alpha --lru_mb 1024 > /dev/null 2>&1 < /dev/null &
echo "<a> <p> \"-0001-02-03\"^^<http://www.w3.org/2001/XMLSchema#date> ." > a.rdf
```
Wait a bit until dgraph alpha is up, then
```
dgraph live --files a.rdf
```

It fails on the date value with:
```
Error while processing data file "a.rdf": During parsing chunk in processLoadFile: while parsing line "<a> <p> \"-0001-02-03\"^^<http://www.w3.org/2001/XMLSchema#date> .\n": parsing time "-0001-02-03" as "2006-01-02T15:04:05": cannot parse "-0001-02-03" as "2006"
```

Negative years are defined by XMLSchema as *BC*: https://www.w3.org/TR/xmlschema-2/#dateTime.

### Expected behaviour and actual result.
The example date should be parsed as `-0001-02-03`, *i.e.* 3rd of February of year 1 BC.

**Comment by anurags92** [comment]
I think we parse date time [here](https://github.com/dgraph-io/dgraph/blob/master/types/scalar_types.go#L197). Does [this](https://gobyexample.com/time-formatting-parsing) package support negative years?

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8573). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
