### ISSUE TITLE
Pagination with `offset` does not scale with var blocks

### ISSUE THREAD

**Issue by EnricoMi** [dgraph-io/dgraph#5808]
### What version of Dgraph are you using?
20.03.3

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
Unrelated

### Steps to reproduce the issue (command/config used to run Dgraph).
I have a predicate for 40m uids, one triple per uid (if it exists). When I read the first 1k uids that have this predicate as:
```
{
  pred as var(func: has(<http://www.w3.org/2000/01/rdf-schema#label>))

  result (func: uid(pred), first: 1000, offset: 0) {
    uid
    <http://www.w3.org/2000/01/rdf-schema#label>
  }
}
```

the query takes minutes. When I read them as:
```
{
  result (func: has(<http://www.w3.org/2000/01/rdf-schema#label>), first: 1000, offset: 0) {
    uid
    <http://www.w3.org/2000/01/rdf-schema#label>
  }
}
```
the query takes milliseconds.

My impression from the timings is that the `pred as var` evaluates the entire result list (hence the constant high query time that depends on the size of the result set) and `result (func: uid(…))` then picks only the first 1000 results. Either `result (func: uid(…))` should push a limit into the evaluation of `pred as var`, or `pred as var` implements a better evaluation that allows `result (func: uid(…))` to seek and iterate.

If I modify the first query as:
```
{
  pred as var(func: has(<http://www.w3.org/2000/01/rdf-schema#label>), first: 1000)

  result (func: uid(pred), first: 1000, offset: 0) {
    uid
    <http://www.w3.org/2000/01/rdf-schema#label>
  }
}
```
I get my result in milliseconds.

With `pred as var(func: has(<http://www.w3.org/2000/01/rdf-schema#label>), first: {limit + offset})` this query scales with the offset as `result (func: uid(…))` does (see #5807). For more details see [this forum comment](https://discuss.dgraph.io/t/retrieve-a-set-of-predicates-for-all-nodes/7319/8).

The motivation why I am using `pred as var` here is that I want to read multiple predicates this way (see [this forum comment](https://discuss.dgraph.io/t/retrieve-a-set-of-predicates-for-all-nodes/7319/2)).

### Expected behaviour and actual result.
Both queries should be equally fast.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8578). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
