### ISSUE TITLE
Retrieve schema predicates or types only

### ISSUE THREAD

**Issue by EnricoMi** [dgraph-io/dgraph#5811]
### What you wanted to do
I retrieve the schema via `schema { }`. I may be interested in the predicates given in `"schema"` or the `"types"` only.

### Why that wasn't great, with examples
The response to that query always contains `"schema"` and `"types"`, one of them is irrelevant and pollutes the response. Would be great if I could select which of them I am interested in. Could be combined with pagination (see #5810).

### Any external references to support your case
Discussed in [the forum](https://discuss.dgraph.io/t/retrieve-large-schema-through-graphql/7490).

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8858). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
