### ISSUE TITLE
Absent uids are returned if querying via uid function

### ISSUE THREAD

**Issue by anurags92** [dgraph-io/dgraph#5817]
### What version of Dgraph are you using?
Dgraph version   : v2.0.0-rc1-452-g5c75240a3
Dgraph SHA-256   : c3fa23e3909376d2b5e567cbe963a81132c9c83e7e40b4051d56cba8105dece2
Commit SHA-1     : 5c75240a3
Commit timestamp : 2020-07-02 11:02:02 -0700
Branch           : master
Go version       : go1.14

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
RAM: 16gig
OS: Linux/Ubuntu
Model name:          Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

### Steps to reproduce the issue (command/config used to run Dgraph).

Query:
```
q (func: uid("0xa", "0xc")){
        uid
        name
    }
```

### Expected behavior and actual result.
Expected results: It should not give any result or throw since `uids` have not been created.
Actual results:
It seems that `uids` are present but the predicate is missing in them.
```
{
  "q": [
    {
      "uid": "0xa"
    }, 
    {
      "uid": "0xc"
    }
  ]
}
```

**Comment by sessionboy** [comment]
Looking forward to fixing this issue in the new version.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8581). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
