### ISSUE TITLE
Add equivalent of Dgraph's 'has' to GraphQL

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#5819]
It's currently not possible to filter in GraphQL by if a node does or does not have a particular edge.  We, should port Dgraph's `has` condition to solve that.

Expect it to look like

```graphql
queryUser(filter: { has: friends }) { 
   ... 
} 
```

or

```graphql
{
  queryUser(filter: {firstName: {eq: null}}) {
    username
    firstName
  }
}
```

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8582). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
