### ISSUE TITLE
Ludicrous Mode: Queries blocked for a long time

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/dgraph#5846]
### What version of Dgraph are you using?
5b6217340
### Have you tried reproducing the issue with the latest release?
No

### What is the hardware spec (RAM, OS)?
N/A

### Steps to reproduce the issue (command/config used to run Dgraph).
Run live loader against one zero and one alpha running in ludicrous mode.
I was running a 336million dataset (took 4 hours on live loader) generated by copy-pasting 21 million dataset.

1. Start alpha and zero in ludicrous mode
2. Run live loader
3. Wait for live loader to complete
4. Stop and restart the alpha

The alpha gets stuck in the `server overloaded` loop and doesn't respond to any queries. I did not stop zero. Zero was running all this time.
.
### Expected behavior and actual result.
I expected alpha to respond to the queries.

See alpha logs https://gist.github.com/jarifibrahim/8531ec73aa0d8dd6363591145d2e6a0f

**Comment by jarifibrahim** [comment]
Update - The queries were blocked for a long time but then they eventually started working. I don't remember how long they were blocked for.

**Comment by harshil-goel** [comment]
Alpha is replaying all the mutations, hence the server overload. The queries were unblocked after alpha loaded all the previous data.

**Comment by jarifibrahim** [comment]
@harshil-goel why would alpha replay all the mutations?

**Comment by harshil-goel** [comment]
We didn't use to take snapshots. Check now the bug should be fixed.
