### ISSUE TITLE
Add arm64 support to travis-ci >  issue: contrib/scripts/install.sh : No such file or directory

### ISSUE THREAD

**Issue by odidev** [dgraph-io/dgraph#5909]
Hi Team,

I am working on adding arm64 support to travis-ci.
Before adding arch: arm64, I have found that the travis-ci is failing for AMD64 itself. In the ‘install’ clause, install.sh file is being called (install: contrib/scripts/install.sh), but that file is not present at the location, or anywhere else in the project. Hence build fails. 
I proceeded with my work after eliminating the ‘install’ clause in .travis.yml, and adding arm64 architecture into travis as well. Travis-ci is running successfully for both the architectures. Please find my travis-ci jobs here :  https://travis-ci.com/github/rahulgit-ps/dgraph

Can you please suggest what changes are required in place of the install.sh file ?

**Comment by odidev** [comment]
Hi Team,

Can someone please help me out with this install.sh file issue in the ‘install’ clause during travis build?

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8585). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
