### ISSUE TITLE
'as' is a Dgraph reserved word; it shouldn't be allowed as a field name in GraphQL

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#5923]
https://discuss.dgraph.io/t/reserved-word-as-for-graphql-schema/7621

We should
* reject this at schema upload time
* add clearer docs for reserved words

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8586). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
