### ISSUE TITLE
Test Failure: graphql/e2e/custom_logic -> TestCustomNameForwardHeaders

### ISSUE THREAD

**Issue by darkn3rd** [dgraph-io/dgraph#5934]
The tests e2e/custom_logic are failing 27.3% of the time (3/11)

### What version of Dgraph are you using?

`latest`

### Have you tried reproducing the issue with the latest release?

yes

### What is the hardware spec (RAM, OS)?

Ubuntu Bionic Beaver

### Steps to reproduce the issue (command/config used to run Dgraph).

```
./test.sh -C 2>&1 | tee /tmp/master.custom_cluster.$(date +%Y%m%d_%H%M).txt
```

#### Expected

Passing Tests

#### Actual

Roughly 27.3% of the time, getting this error:

```
--- FAIL: TestCustomNameForwardHeaders (2.02s)
    custom_logic_test.go:234:
        	Error Trace:	custom_logic_test.go:234
        	Error:      	Expected nil, but got: x.GqlErrorList{(*x.GqlError)(0xc000138af0)}
        	Test:       	TestCustomNameForwardHeaders
FAIL
exit status 1
FAIL	github.com/dgraph-io/dgraph/graphql/e2e/custom_logic	59.958s
```

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8588). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
