### ISSUE TITLE
Support for Sequence Numbers, Constraints

### ISSUE THREAD

**Issue by soneymathew** [dgraph-io/dgraph#5943]
## Experience Report

While researching on migration possibilities from a postgres based system to DGraph, I came across few limitations in DGraph.

I was using the GraphQL first approach https://graphql.dgraph.io/
Discussion thread for reference: https://twitter.com/manishrjain/status/1281730614312353792?s=20

#### Sequence Numbers

I wanted a field to act as a sequence number whenever a specific GraphQL type is created. User will not be allowed to create or modify this field. This field must be created whenever a In postgres I achieve it using
https://www.postgresql.org/docs/current/sql-createsequence.html

#### Constraints

I wanted to ensure that a specific combination of fields are unique across the GraphQL type. In postgres I achieve it using
https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS

### What you actually did
Paused my research
### Why that wasn't great, with examples
This is blocking me from continuing my research for feasibility/adoption of DGraph
### Any external references to support your case
NA

**Comment by manishrjain** [comment]
Overridden by https://discuss.dgraph.io/t/support-for-sequence-counter/7665
