### ISSUE TITLE
[RFC] Go client response browsing

### ISSUE THREAD

**Issue by etix** [dgraph-io/dgraph#598]
This is a technical follow up of [this discussion](https://discuss.dgraph.io/t/golang-a-small-helper-for-manipulating-grpc-responses/1288) on Discourse.

The idea is to pick some interesting features from my Go helper ([xdgraph](https://github.com/etix/xdgraph)) and merge them into the official Go client.

I see two different ways to add similar functionalities to the Go client:
- Embedding the gRPC client into the Go client in a similar way of what has already been done for the NewBatchMutation.
- Keeping it as an external helper that can be used on any gRPC response (pretty much what the lib is already doing).

There are pros and cons on both options. Opinions?

**Comment by etix** [comment]
I pushed some improvements today, notably the possibility of matching multiple attributes:
```go
// Execute a function literal for each matched attribute
xd.First().Attribute("follows").Attribute("plays").Each(func(r xdgraph.Response) {
    fmt.Println(r.Property("name").ToString())
})

// Get multiple properties at once
for _, sign := range xd.First().Attribute("follows").Properties("sign") {
    fmt.Println(sign.ToString())
}
```
While the discussion goes on here, I will continue working on a real world application and see how far I can get using the library. I will make updates if necessary.

**Comment by pawanrawal** [comment]
Hi @etix 

It would be good to have some of these helper functions as part of the Go client, that way new users don't have to download two different libraries while using the client. I would suggest sending a PR with the features you have till now and then we can deliberate over it?

**Comment by manishrjain** [comment]
I think keeping it as a helper library is probably better. That way the Dgraph client can remain simple with a single focus; while encouraging others (and the broader community) to create helper libraries around the client.
