### ISSUE TITLE
Connection Timeout Issue

### ISSUE THREAD

**Issue by koppula** [dgraph-io/dgraph#61]
Ran into connections getting timed out with the server today after the HN post went up:

ATA[901074] dial tcp :12345: getsockopt: connection timed out call=Worker.ServeTask package=worker
INFO[901075] Sample value attr=root package=query val=
INFO[901075] ProcessTaskOverNetwork attr=film.director.film instanceIdx=1 numInstances=3 package=wor
ker runHere=false
FATA[901075] connection is shut down call=Worker.ServeTask package=worker
INFO[901075] Sample value attr=root package=query val=
INFO[901075] ProcessTaskOverNetwork attr=film.director.film instanceIdx=0 numInstances=3 package=wor
ker runHere=false
FATA[901075] connection is shut down call=Worker.ServeTask package=worker
Log Fatal due to connection timeout issue.

**Comment by manishrjain** [comment]
Fixed.
