### ISSUE TITLE
docker/devel: building fails because of undefined symbol references

### ISSUE THREAD

**Issue by etix** [dgraph-io/dgraph#612]
Docker built this way: `docker build -t dgraph/devel .`

Native code is built successfully but the go part fails while building `github.com/dgraph-io/dgraph/icutok`.

```
# github.com/dgraph-io/dgraph/icutok
/tmp/go-build766196873/github.com/dgraph-io/dgraph/icutok/_obj/icuc.o: In function `NewTokenizer':
src/github.com/dgraph-io/dgraph/icutok/icuc.c:38: undefined reference to `u_uastrcpy_57'
src/github.com/dgraph-io/dgraph/icutok/icuc.c:42: undefined reference to `u_strlen_57'
src/github.com/dgraph-io/dgraph/icutok/icuc.c:45: undefined reference to `ubrk_open_57'
src/github.com/dgraph-io/dgraph/icutok/icuc.c:50: undefined reference to `ubrk_first_57'
/tmp/go-build766196873/github.com/dgraph-io/dgraph/icutok/_obj/icuc.o: In function `DestroyTokenizer':
src/github.com/dgraph-io/dgraph/icutok/icuc.c:56: undefined reference to `ubrk_close_57'
/tmp/go-build766196873/github.com/dgraph-io/dgraph/icutok/_obj/icuc.o: In function `TokenizerNext':
src/github.com/dgraph-io/dgraph/icutok/icuc.c:70: undefined reference to `ubrk_next_57'
src/github.com/dgraph-io/dgraph/icutok/icuc.c:78: undefined reference to `u_austrncpy_57'
collect2: error: ld returned 1 exit status
```

A working workaround is to remove the `--disable-renaming` flag.

```diff
--- a/docker/devel/Dockerfile
+++ b/docker/devel/Dockerfile
@@ -29,7 +29,7 @@ RUN cd /installs && \
        wget http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-src.tgz && \
        tar xvzf icu4c-57_1-src.tgz
 RUN cd /installs/icu/source && \
-       ./configure --disable-renaming && \
+       ./configure && \
        make && \
        make install
```

I didn't have much time to investigate so I just leave this here for now. But it seems related to #288.

**Comment by pawanrawal** [comment]
Hi @etix 

We haven't use the development image of Docker in a longtime. I will have a look at this and make the changes that are needed for this. Are you trying to develop Dgraph using Docker?

**Comment by etix** [comment]
Hi @pawanrawal,

I used the docker/devel image to test the latest master without having to build and run Dgraph on my host machine. If this is not the recommended (or supported) way anymore then feel free to remove the image.

**Comment by manishrjain** [comment]
Yeah, we should remove it. Largely, we're telling users to use the binaries that we release, instead of building Dgraph, due to Cgo building issues. So, no point having a docker image that we don't support.

**Comment by pawanrawal** [comment]
Okay, removing it.
