### ISSUE TITLE
Support a better mutation format, potentially JSON-LD

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#616]
For mutations. Also ensure that it can work with facets.

**Comment by manishrjain** [comment]
Ref: #1

**Comment by ashwin95r** [comment]
This library seems to fit our need (https://github.com/kazarena/json-gold). We can convert the JSON-LD to RDF Nquads and then follow the same code path.

**Comment by harlantwood** [comment]
Very happy to see this on your roadmap! 👍

**Comment by manishrjain** [comment]
Now that v0.8.2 is out, we should spend some time on this and come up with a proposal for doing mutations in Dgraph. @pawanrawal

**Comment by manishrjain** [comment]
We now fully support JSON as input and output format.
