### ISSUE TITLE
Leaf predicate must be a scalar

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#619]
Running this query
```
{
 me(func:allof(name.en, "angelina jolie")) {
  name.en
   actor.film {
    performance.film {
     name.en
     genre
    }
   }
  }
}
```

returns an error `{ "code": "Error", "message": "Leaf predicate:'genre' must be a scalar." }`. It should not return the genre key in the result and not complain.

**Comment by manishrjain** [comment]
Thanks @pawanrawal. Great job assigning it as well.

**Comment by squalfof** [comment]
Reproduced it.
```
performance.film {
     name.en
     genre
}
```
if **genre** is empty, then it will fall into branch which happened to check if it's scalar or not
```
if !typ.IsScalar() {
          return sv, x.Errorf("Leaf predicate:'%v' must be a scalar, val %v.", attr, tv)
 }
```
issue triggered.

Should schema() treat it as non-scalar or not ...?
Note: we have in schema file "scalar ( genre: uid @reverse )"

**Comment by squalfof** [comment]
Our type system take **uid** as non-scalar by default? 
Why we set this way...
```
scalar (
	director.film: uid @reverse
	genre: uid @reverse
	name.en: string @index
)
```

**Comment by ashwin95r** [comment]
UID type should return false for `IsScalar()`
