### ISSUE TITLE
https://dgraph.io/docs/deploy/ page is empty

### ISSUE THREAD

**Issue by MickaelAlliel** [dgraph-io/dgraph#6194]
* Doc page: [deploy/index.md](https://dgraph.io/docs/deploy/)
* Doc version: `release/v20.07`

**Comment by lgalatin** [comment]
This issue is fixed by this PR: https://github.com/dgraph-io/dgraph/pull/6188 going forward please report issues in Discourse only.  thank you @MickaelAlliel
