### ISSUE TITLE
Other databases ?

### ISSUE THREAD

**Issue by joeblew99** [dgraph-io/dgraph#620]
Currently rockdb is default.

Is there any plans to allow other databases ? Nothing wrong with rocksdb but a pure golang dB would help for many use cases I have.

I would write a boktdb and QL database driver for example

**Comment by gedw99** [comment]
BoltDB was tested by the Dgraph team, and yes its a single writer bottleneck, but i think its useful because it allow for embedded use cases, where you just need a basic store to do things.

**Comment by manishrjain** [comment]
Yeah, BoltDB is super slow. We don't want to associate Dgraph name with something that slow. We're building a new KV store entirely in Go (called Badger), which we think could provide a similar level of performance as RocksDB. It should be out before we release v0.8.

**Comment by gedw99** [comment]
do you have a link yet ? would like to try a few things out on embedded with it

**Comment by manishrjain** [comment]
Still a WIP, in a private repo. Just need a couple of weeks of dedicated time to work on it. Once it's close to where I want it to be, we'll open source it.

**Comment by ohenepee** [comment]
@manishrjain Could you give a fairly abstract time-frame of when to expect it?

**Comment by manishrjain** [comment]
It would be part of the v0.8 release, which we will aim for by the end of March.

**Comment by ohenepee** [comment]
I'm actually targeting the Android platform thats why a purely Go database would be necessary as @joeblew99 requested
