### ISSUE TITLE
Contents on the right side is not scrollable

### ISSUE THREAD

**Issue by agrawal-utkarsh** [dgraph-io/dgraph#6227]
* Doc page: [query-language/functions.md](https://dgraph.io/docs/query-language/functions/)
* Doc version: `release/v20.07`

**Comment by lgalatin** [comment]
I created this post https://discuss.dgraph.io/t/contents-on-the-right-side-is-not-scrollable/9533. Going forward please use Discourse to report issues we are not monitoring Github for issues.  thanks @agrawal-utkarsh
