### ISSUE TITLE
Immutable data

### ISSUE THREAD

**Issue by natew** [dgraph-io/dgraph#624]
Apologies for making an issue, not a fan of signing up for yet another slack room.

Just curious, whats the potential for implementing an immutable style database on dgraph, or within dgraph?

By that I mean being able to see full history of changes for any data, and having delete operations just mark as "deleted". Generally, I'm not familiar with graph db's, so not sure if this is easy to implement externally or requires internal work.

**Comment by manishrjain** [comment]
This would require versioning. Dgraph doesn't support versioning.

**Comment by jasonkuhrt** [comment]
I'm interested about this too. I also don't have much experience in this space yet but am currently reading https://www.datastax.com/dev/blog/gremlins-time-machine with curiosity.
