### ISSUE TITLE
Schema should have constraint

### ISSUE THREAD

**Issue by squalfof** [dgraph-io/dgraph#627]
```
scalar (
	director.film: uid @reverse
	genre: uid @reverse
	initial_release_date: date @index
	name.en: string @index
)
```
uid type should not be specified as scalar, they are objects.
Maybe some warning during schema-parsing ?

**Comment by janardhan1993** [comment]
since we don't recognise objects/object types in schema, @manishrjain Can we remove scalar block from schema file and have the below directly. It's kind of weird to specify uid type inside scalar block.
        director.film: uid @reverse
	genre: uid @reverse
	initial_release_date: date @index
	name.en: string @index

**Comment by manishrjain** [comment]
Yes, I was thinking the same thing. Let's remove the scalar block.

**Comment by manishrjain** [comment]
We removed the scalar keyword. Also, we'll be getting rid of the schema file, instead allowing dynamic schema updates.
