### ISSUE TITLE
First query in getting started guide does not compile

### ISSUE THREAD

**Issue by AAAton** [dgraph-io/dgraph#633]
The first query on the [Get Started](https://wiki.dgraph.io/Get_Started) guide looks like:

`{
  me(allof("name", "Star Wars")) @filter(geq("release_date", "1980")) {
    name
    release_date
    revenue
    running_time
    director {
     name
    }
    starring {
     name
    }
  }
}`

This does not compile on Dgraph 0.7.3 on OS/X. As a complete novice I'm guessing that the issue is that ```me(allof(...))```should really be ```me(func:allof(...))```.

**Comment by pawanrawal** [comment]
Hi @AAAton , thats correct it should have a `func` at root. Modified the Wiki.
