### ISSUE TITLE
In loader, open UID RocksDB as ReadOnly

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#64]
https://github.com/facebook/rocksdb/wiki/RocksDB-Basics#readonly-mode

Read Only mode provides better performance; and that's exactly what we do during the second phase of the loader. So, allow UID RocksDB to be opened read only.
https://github.com/dgraph-io/dgraph/blob/master/server/loader/main.go#L79

The current RocksDB library that we use doesn't support this operation. So, consider switching to https://github.com/tecbot/gorocksdb

**Comment by ashwin95r** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;KJYQE0jr&#x2F;6-open-uid-dir-as-read-only"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Open UID dir as read-only</a>

**Comment by manishrjain** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;KJYQE0jr&#x2F;6-open-uid-dir-as-read-only"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Open UID dir as read-only</a>

**Comment by manishrjain** [comment]
Tracking in Trello. Closing here.
