### ISSUE TITLE
Sorting by string values doesn't work?

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#641]
Tried a couple of queries and the result isn't sorted. Could reproduce this on the release v0.7.3 branch. Would be good to check if this is an issue in v0.7.2 too.
```
{
  me(func: allof(name.en, "steven"), orderasc: name.en, first: 20) {
    name.en
  }
}
```

```
{
  me(id: m.06pj8) {
    name.en
    director.film (orderdesc: name.en) {
      name.en 
    } 
  }
}
```

**Comment by ashwin95r** [comment]
We shouldn't be sorting using  just the index keys for strings as we'd consider only the term with the lowest lexicographic order (which we see first).

**Comment by janardhan1993** [comment]
How about we use exact tokenizer to sort strings by default ?

**Comment by ashwin95r** [comment]
That would work. But, That should be an optimization if the index exists, I guess. We should be able to sort without any index as well.

**Comment by ashwin95r** [comment]
818341aec4f1800f284b5db6f9db423c8fc6611c fixes this.
