### ISSUE TITLE
Backup Language Error

### ISSUE THREAD

**Issue by Motakjuq** [dgraph-io/dgraph#655]
As I commented on #650, there is a bug related with the language in the backup process, this doesn't allow to write the language tag (@ lang) into the backup.

How to reproduce this error:
I ran this mutation:
> curl "http://localhost:8080/query" -XPOST -d $'mutation {
	set {
		<film.director.film>	<<http://www.w3.org/2000/01/rdf-schema#domain>>	<film.director>	.
		<film.director.film>	<<http://www.w3.org/2000/01/rdf-schema#range>>	<film.film>	.
		<film.director.film>	<type.object.name>	"Films ..."@en	.
		<film.director.film>	<type.object.name>	"Peliculas ..."@es	.
		<film.director.film>	<type.object.value>	"Some value"	.
		<film.director.film>	<type.property.expected_type>	<film.film>	.
		<film.director.film>	<type.property.schema>	<film.director>	.
	}
}

Create a backup
> curl "http://127.0.0.1:8080/admin/backup"

And I got this file:
> <0xdada9dc85b146592> <type.property.schema> <0xbc7552702ff50d6> .
<0xdada9dc85b146592> <type.property.expected_type> <0xa51fa2739211dcba> .
<0xdada9dc85b146592> <<http://www.w3.org/2000/01/rdf-schema#range>> <0xa51fa2739211dcba> .
<0xdada9dc85b146592> <<http://www.w3.org/2000/01/rdf-schema#domain>> <0xbc7552702ff50d6> .
<0xdada9dc85b146592> <type.object.value> "Some value" .
<0xdada9dc85b146592> <type.object.name> "Films ..."^^<xs:string> .
<0xdada9dc85b146592> <type.object.name> "Peliculas ..."^^<xs:string> .

As you see, the `<type.object.name>` doesn't have the language tag because it was recognized as type.StringID.

**Comment by ashishnegi** [comment]
Thanks for reporting this. The example is helpful.
I am able to reproduce it.

**Comment by janardhan1993** [comment]
Our schema grammar currently doesn't allow both IRI type and lang tag. If lang is specified we take it to be of string type. Either we need to change our grammar, or while writing backup if there is lang tag, we don't write the type.

**Comment by ashishnegi** [comment]
The problem is with backup code, as mentioned by @Motakjuq earlier in his PR.

**Comment by manishrjain** [comment]
> Our schema grammar currently doesn't allow both IRI type and lang tag.

This is RDF NQuad schema, not ours. I think the problem here isn't that anyway. The problem is that we're losing the language tags for the values. They should be retained.
