### ISSUE TITLE
Feature Request: Watch changes

### ISSUE THREAD

**Issue by joeblew99** [dgraph-io/dgraph#660]
In goshawkdb (another go lang graph db) there is a nice feature where any DB can watch for another DBs changes. Its automatic when set.
So you can have a huge DB namespace, and branches off them on other servers or clients (mobiles, desktops, microservices). Its very much like a hug and spoke physical pattern.
With the Watch aspect, you can have your spokes all automatically get fed the changes from the Hub. A spoke db can do local persisted mutations of many hundreds of objects over any time period and then do a transact from the Spoke to the Hub.  It will then try to transact and if its cant the server will return the marge changes set for the client to adapt to.  This allow offline editting and merge later.

This ends up giving you a quasi message queue integrated at the DB level.
Clients are totally insulated from it.

**Comment by RXminuS** [comment]
Do the CAP theorems required align though, sounds like you would need CP for that...DGraph's AP or?

**Comment by manishrjain** [comment]
Dgraph is atomically consistent and is CP in the CAP theorem. I'm not sure if this spoke and hub pattern would fit with Dgraph. Also, not sure of its need. Maybe you can elaborate with a real world use case.

**Comment by joeblew99** [comment]
Hey,

I will try to illustrate a bit more.....

This explains the feature called "GoshawkDB supports retry". You can find the heading
https://goshawkdb.io/features.html

In fact this page is great. It gets into the nitty gritty straight away so you really know what your dealing with as far as tradeoffs, which every DB has.

How you use this and other features is quite up to the imagination because it is quite different from other approaches, but a mix of many different things.
The Hub & Spoke pattern is just one that comes to mind for me. 

Its really a mix of many things that are going on, and converges them.
Some more links to see what i mean.

There is also a you tube videos
https://www.youtube.com/watch?v=PPZhksQdNBc

https://www.infoq.com/presentations/goshawkdb

https://www.infoq.com/presentations/event-streams-kafka

One other aspect is that your programming one to one. The objects in memory are "aligned" with the objects in the DB.  Its stupid simple to use.
You can front it with GRPC, GraphQl or whatever takes your fancy really.

**Comment by joeblew99** [comment]
Real world use cases.

1. You need to do streaming and batch computation on big data. Typically you need to run a job with jobs on jobs. With this DB you can have the data close to the computation and then transaction the changes. Take your pick how you want to keep them in sync and spread.

2. Mapping to the way organisations are. Large organisations ae often hub and spoke. Holding companies and trading companies. Whatever. You often need data to be split out and shared with security that is data driven. This can do that. The data driven security is pretty cool actually.

3. Mobiles to Server. a pain in the butt use case is mobile offline editing and then reconciliation. This gives you the tooling to do that without too much fan far.

**Comment by joeblew99** [comment]
@manishrjain Regarding CAP theorem, have a look at the link i gave at https://goshawkdb.io/features.html

Between database both in and out of the cluster, you can choose what namespaces to keep in sync.
Its a highly practical approach for graph DB's from my usage.
It relies on MVCC (https://en.wikipedia.org/wiki/Multiversion_concurrency_control) being present in the DB for the sync aspects to work, but its highly flexible how you use it which i have found very useful. 

Its written by the author of RabbitMQ, and is his second stab at making dbs and sync work.

**Comment by manishrjain** [comment]
This seems very out of scope for what we're aiming for at the moment.
