### ISSUE TITLE
Regexp function at root

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#661]
@RXminuS Says:

so I'm not able to use something like this yet?
```
query{
   me(func:regexp("name", "[0-9]")){
      name
   }
}
```

**Comment by ashwin95r** [comment]
It works for me at the root. 
```
curl localhost:8080/query -XPOST -d $'
mutation{
  set {
   <A> <name> "Ashwin Ramesh" .
 }
}'

curl localhost:8080/query -XPOST -d $'{
me(func: regexp(name, "^[A-Z a-z]*$")) { 
   name 
 } 
}'

**Comment by RXminuS** [comment]
Ah bugger...I see what I did wrong...the get.dgraph.io pulls from the latest release tag not master. Thought that the "merged" meant it was on the production branch
