### ISSUE TITLE
Feature Request: join custom resultsets

### ISSUE THREAD

**Issue by RXminuS** [dgraph-io/dgraph#662]
Love the simple architecture of DGraph. To me it would seem it should be fairly trivial to add the ability to join a custom resultset with the resultsets generated by dgraph workers.

That way we could for instance rely on an external database (for instance, we have another reverse-image-search database we would like to join) or API to generate some potential candidates and join/filter the results down further using the normal dgraph workers.

Maybe by making it easy to spin up "custom" workers that has custom resolver functions sending back the same GRPC message as normal workers?

**Comment by manishrjain** [comment]
You can pass in a list of ids in GraphQL+-. Would that work for you?

https://wiki.dgraph.io/Query_Language#Queries

**Comment by RXminuS** [comment]
Yes that's essentially what we're doing now and worked fine when experimenting with smaller sets. However, won't it become a problem if we want to start joining & filtering larger sets? Sending in 1000 id's seems a bit wrong...or would it work just fine?

**Comment by manishrjain** [comment]
Ideally, you move the entire data set within Dgraph, so all the searching happens within. Then, only for the final results, you can retrieve the images and serve them. This would be way faster than trying to unite two isolated systems, particularly if the result set is large.

To do anything else, would require either performance hit, or dissection of Dgraph architecture; none of which I'd recommend.

**Comment by RXminuS** [comment]
Our use-case would be to: have our image-index generate candidate images based on visual similarities with examples (not something trivial to move to dgraph...although not impossible) and then filter the candidates further based image metadata in dgraph.

But I can totally understand if it's too far outside dgraphs goals.

**Comment by manishrjain** [comment]
I see. I like the idea of having a custom worker, which can be called by Dgraph. What that would require is to have a special predicate/keyword, where Dgraph could send its query to. However, the only thing we generally send out is a list of UIDs; so across these 2 systems, the UIDs must be the same. Then, you can send back the filtered UID list (or UIDMatrix, if you're expanding the predicate). How feasible is this from your end?

**Comment by RXminuS** [comment]
That's is exactly what I was thinking, and would work perfectly for us. How are external uid's currently handled...would it be feasible for the custom worker to return a set of those instead of real UID's?

**Comment by RXminuS** [comment]
@manishrjain Maybe remove `author-to-reply` label so it doesn't get lost :-)

**Comment by manishrjain** [comment]
This feels like a fancy feature at this point. I think once Dgraph achieves v1.0; then it would be a good thing to build; I don't see it being used much by others before that.

Unless many people ask for this, I'll set it to be done after v1.0

**Comment by manishrjain** [comment]
We don't have any plans to work on this. So, will close it for now. Feel free to start a discussion on discuss.dgraph.io, if you feel we should build something like this.
