### ISSUE TITLE
add range support for bleve based search

### ISSUE THREAD

**Issue by joeblew99** [dgraph-io/dgraph#671]
Please provide for the range terms of bleve

numeric range and date range as explained here:  http://www.blevesearch.com/docs/Result-Faceting/

@tzdybal

**Comment by tzdybal** [comment]
@joeblew99, For numeric and date time attributes bleve is not used by dgraph.

**Comment by joeblew99** [comment]
@tzdybal  ok thanks. I will kick the tires on master to see how bleve goes for me.
is there any example code yet that uses it ?

**Comment by tzdybal** [comment]
Discussion moved to [discuss.dgraph.io](https://discuss.dgraph.io/t/faceted-search-support/1597?u=tzdybal).
