### ISSUE TITLE
Facets on reverse edges

### ISSUE THREAD

**Issue by RXminuS** [dgraph-io/dgraph#672]
Hey, I don't think reverse edges receive the facets set on the original edge. Am I doing something wrong or was this by design, if so why? I can look into fixing this myself this weekend if not fixed before then :-)

**How to reproduce:**
*schema:*
```graphql
type A{
     name: string
     b: uid @reverse
}

type B{
     name: string
}
```

*seed:*
```graphql
mutation{
  set{
    _:a <name> "a" .
    _:b <name> "b" .
    _:a <b> _:b (close=true) .
  }
}
```
*query b from a - OK, facets returned*:
```graphql
query{
  a(id: 0xfb49aa631eafd927){
    name
    b @facets{
      name
    }
  }
}
```
*query a from b - FAIL, no facets returned*:
```graphql
query{
  b(id: 0x8fa3752a1f22ad29){
    name
    ~b @facets{
      name
    }
  }
}
```

**Comment by ashishnegi** [comment]
Yes, reverse edges do not receive facets from original edge.
While designing, it seemed to me that not all edges will be symmetric in reverse direction. So, we left facets in reverse edge.

Thinking about it more, it seems that we should allow facets to be part of reverse edge. As users can't manipulate reverse edge in itself and facets on reverse edge will add helpful information for queries.
Adding @manishrjain for his view.

@RXminuS We will be happy to receive your PR. :) You may want to look at `postings/index.go` for this.

**Comment by RXminuS** [comment]
Cool! Should we make it the default behaviour to copy facets, configurable in the schema or toggable in the settings?

**Comment by manishrjain** [comment]
@ashishnegi @RXminuS Yeah, makes sense for reverses to receive the facets. We just need to be careful about ensuring they remain in sync.

> default behaviour to copy facets,

You mean, retrieve facets for all the edges in the query? Hmm... If you think this is going to be useful, we might do this as part of the request headers maybe, like we do debug.

**Comment by ashishnegi** [comment]
> default behaviour to copy facets

Yes, it should be default behaviour for reverse edges to have facets of original edge.

**Comment by manishrjain** [comment]
This went in. Would be present in the upcoming release.

**Comment by pawanrawal** [comment]
Verified that reverse edges get the facets and that they remain in sync when the original facets are modified.

Though when I try to modify the facets of the reverse edge nothing happens. Steps to reproduce.

Schema
```
name: string
b: uid @reverse
```

```
mutation{
  set{
    _:a <name> "a" .
    _:b <name> "b" .
    _:a <b> _:b (close=true) .
  }
}
```

This doesn't work
```
mutation{
  set{
    <0x767955dec48b28ed> <~b> <0xb4f1ae9d1bd11f3d> (close=false,age=13) .
  }
}
```

though
```
mutation{
  set{
    <0xb4f1ae9d1bd11f3d> <b> <0x767955dec48b28ed> (close=false,age=13) .
  }
}
```
works. So its a one-way sync where facets from original edge are copied to reverse but not the other way around. I suppose this is a bug @ashishnegi?

---
Another issue is regarding deletion of facets.
Say I do this mutation
```
mutation{
  set{
    <0x96916bd5b389834c> <name> "Alice" (gender="female", city="Sydney") .
  }
}
```
and then modify the name value but don't supply all the facets
```
mutation{
  set{
    <0x96916bd5b389834c> <name> "Bob"  (city="New York") .
  }
}
```
then the facets which are not supplied are deleted. Is that the intended behavior?

**Comment by pawanrawal** [comment]
Confirmed from @ashishnegi that deletion is the intended behaviour here.

**Comment by neetikh** [comment]
I m facing a problem here--
eg-
"a" is friendwith "b"
"a" is friendwith "c"
"a" is friendwith "d"

friendWith is the edge which has facets like - isclose, friendSince
And also, I hv kept this edge"friendwith " as a reverseEdge.

Now, when i am querying[using reverse edge] to-
 get the the friendSince for "c"---> "a" 

Its giving me all the details of ALL the "FriendWith" EDGES from "a"
Please suggest if I am missing on anything here
