### ISSUE TITLE
Document difference between <xs:string> and <http://www.w3.org/2001/XMLSchema#string>

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#684]
In the supported RDF types listed here: https://wiki.dgraph.io/Query_Language#Supported

There are a group of types prefixed with `<xs:>` and another group with `<http://www.w3.org/2001/XMLSchema#>`. The types appear to be identical and it is not clear when `<xs:>` or `<http://www.w3.org/2001/XMLSchema#`> should be used.

It would be nice if there could be more clarification in the docs regarding this.

**Comment by manishrjain** [comment]
These are RDF datatypes, not something we created. I've added a link to their spec in the section, which might help understand these better.

https://wiki.dgraph.io/Query_Language#Supported

Feel free to reopen the issue if you think we can better explain this.

**Comment by F21** [comment]
It might still be useful to mention when/why I should use 
```
mutation {
 set {
	<0x01> <name> "Alice"^^<xs:string> .
 }
}
```
over
```
mutation {
 set {
	<0x01> <name> "Alice"^^ <http://www.w3.org/2001/XMLSchema#string> .
 }
}
```

Are there any differences between the `<http://www.w3.org/2001/XMLSchema#string>` type and the `<xs:string>`, from a quick search, `<xs:string>` seems to be equivalent to `<http://www.w3.org/2001/XMLSchema#string>`. If so, why are there 2 types instead of 1 (less confusing) type?

**Comment by ashishnegi** [comment]
@F21 They both are mapped internally to same dgraph type `STRING`. So, for us, they are same, if that is your question.

You will need to check RDF specification to know when should you use one over other while creating RDFs.
