### ISSUE TITLE
Ability to store the schema on cluster

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#685]
We want to deploy dgraph on dynamic environments using orchestrators such as kubernetes.

It would reduce operational complexity if we can store and adjust the schema directly within dgraph through some api. This would enable us to be able to colocate the schema with our app, rather than colocating it with infrastructure config.

**Comment by manishrjain** [comment]
Yes, this is under works. @janardhan1993 is working on it. This should be part of v0.8 release by the end of this month.

**Comment by F21** [comment]
Awesome! Looking forward to it 😄
