### ISSUE TITLE
Automatically generate raft index

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#686]
It would be nice to not have to pass in `-idx` when running dgraph in cluster mode. This would be useful if you are running dgraph with a orchestrator such as docker swarm where task numbers are not supported.

It would also simplify operations, like cockroachdb:

```
$ ./cockroach start --background
$ ./cockroach start --store=cockroach-data2 --port=26258 --http-port=8081 --join=localhost:26257 --background
$ ./cockroach start --store=cockroach-data3 --port=26259 --http-port=8082 --join=localhost:26257 --background
```

**Comment by manishrjain** [comment]
We try to avoid doing a lot of "smarts" within Dgraph at this point. It's more robust to let users decide how they want to shard their data and how they run their servers. Instead, we will build a cluster manager which can help with these things later.

The issue with auto-assigning an idx is that there're many edge cases that all need to be handled by an algorithm. For e.g., if a server restarts, should it keep its old idx or should it get a new one? If we need to keep the old idx, where do you store it? If you now need to assign it a new idx, how do you remove the old one?

**Comment by F21** [comment]
In terms of kubernetes, you can run it as a petset and if a node fails, it will still get the same id. However, I was hoping it would be possible to not have to do this, so it would be possible to run this on docker swarm (where it doesn't assign a stable index per task) and scale up and down via a single command.

Currently, if you want to do this in docker swarm, you would need to deploy each node individually and manage them individually, which negates the benefits of using an orchestrator.

**Comment by manishrjain** [comment]
We could potentially add a simple flag which would assign an unused id to the node. This would have the limitation that for every restart, it would be assigned a new id.

@janardhan1993 : What do you think?

**Comment by janardhan1993** [comment]
Generating new id on restart in not a good idea. The node would have to sync up with leader(snapshot fetch and replay of logs) and it would affect disk io and we would loose the benefit of quick restart time.
It would be better if we generate new id and persist it to disk and handle the edge cases mentioned earlier. 

@F21 
We also need to keep the following in mind for docker swarm.
1)When starting nodes with a new group id, we need to ensure that membership information is propagated to group zero. If the nodes are started too quickly with same groupid, both of them would start as leaders.
2) We would have also have to deal with old id's in case we generate new id's on restart. We would loose the quorum eventually if old id's are not removed. 
We would need to detect dead node and remove them automatically which is tricky.

**Comment by manishrjain** [comment]
I'm not sure what's the action item here. I haven't played with docker swarm myself yet. @F21: What do you suggest?

**Comment by F21** [comment]
@manishrjain In the case of docker swarm, we would need dgraph to automatically assign an id to each node. With kubernetes, we can create a statefulset and kubernetes will assign a static numeric id to each node, but using statefulsets tend to not be used, except for legacy databases or apps where it is not possible.

**Comment by manishrjain** [comment]
@janardhan1993 : Can you play with docker swarm and see how Dgraph could work with it. For exploration.

**Comment by janardhan1993** [comment]
@F21 We could autogenerate raft id. If you pass a node  id we will use that or else we  would look up in wal. If it's not found then we would autogenerate and store it in wal. 
In case of data loss/disk corruption, we would be generating a new id since wal would be empty. So that machine would behave like a new server from raft's perspective on restart after disk failure and recovery. 

1.When scaling up a cluster in docker swarm, i didn't find any sequential deployment option which is present in  normal docker deployments. We would need dgraph servers to be started sequentially so that they can discover other nodes serving same group or else we might end up with split brain. (We should atleast one server per group, then other servers can start in parallel).

2. When you scale down a cluster, the removed nodes are not removed from peer list automatically. You would have to remove the nodes manually from the quorum by hitting our api. We don't remove a node automatically as of now. We could provide a flag -leave-on-termination wherein the server would gracefully leave the quorum and shutdown on receiving sigterm.(consul does the same).

**Comment by F21** [comment]
@janardhan1993 

Thanks for looking into this! 😄 

1. From my understanding, there is no way to sequentially start up containers using docker swarm or kubernetes.

2. I think the idea of `leave-on-termination` is the best way to do this. Is there a way to do this via a signal? This would make shutting down using kubernetes, swarm or some other orchestrator much easier.

**Comment by manishrjain** [comment]
https://docs.docker.com/engine/swarm/join-nodes/

Just quickly skimming through this page, it looks like you can add new nodes to the swarm. So, you could start with a swarm of 1 node, and then add nodes along the way.

**Comment by F21** [comment]
@manishrjain That is for setting up the docker swarm cluster. 

Having said that, you might be able to spin up dgraph with just 1 node and then slowly add more nodes manually, but that prevents automation and is harder to manage.

**Comment by manishrjain** [comment]
We'll be spending a considerable chunk of effort to make cluster management and monitoring easy; though it would be part of our enterprise offering. This would include running Dgraph cluster on AWS, GCE and auto-scaling the cluster based on various heuristics.

If you think this would be useful to you, happy to give out the enterprise version so you can trial it.

**Comment by F21** [comment]
@manishrjain That's great to hear. Is there any chance some basic cluster management features can be made available for the community edition?

In any case, I'd love to give the enterprise version a spin when it's available, but I am currently working on a  bootstrapped start up, so the enterprise version might be out of reach.

**Comment by manishrjain** [comment]
We'll be providing the enterprise version free of charge for startups with little or no funding. That goes without saying, in my mind :-).

**Comment by manishrjain** [comment]
This, along with auto-scaling, cluster management etc. would be part of the enterprise version. So, closing this issue here.
