### ISSUE TITLE
Improve documentation for sharding

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#687]
https://wiki.dgraph.io/Deploy#Data_sharding contains a fair bit of information about sharding, but some concepts are still a bit unclear.

- If we want to configure the shard calculation, we use `default: fp % N + k`. It would be nice to have some information on how `N` and `k` should be chosen.

- The documentation also gives an example of starting a clustered node: `dgraph --groups "0,1,2" --idx 4 --peer "<ip address>:<port>" --my "ip-address-others-should-access-me-at"` Will there be any adverse effects if a node is restarted with a different list of groups?
- The documentation also states that each group must be served by 1,3, or 5 servers, which can be hard to manage operationally. Are there any adverse effects if we just run a cluster with the default groups on all of them `--groups 0,1`?

**Comment by manishrjain** [comment]
The doc says this:
> <shard-id>: fp % N + k, where N = number of shards you want, and k = starting shard id.

Was that not clear?

- Node with different list of groups? That's an interesting case. It might or might not work correctly. @janardhan1993, any thoughts? To keep things clean, you should use a different idx if you're restarting with different groups.
- Consensus is less effective if you run it with more than 5 nodes. By running a cluster with more than 5 servers, all handling the same group, you're just replicating the same data more than 5x times. That doesn't sound useful.

**Comment by F21** [comment]
> The doc says this:
> 
> : fp % N + k, where N = number of shards you want, and k = starting shard id.
> Was that not clear?

In terms of this, my questions are:
- How do I decide how many shards I need?
- What is the maximum number of shards that can be placed on each node?

Somewhat off topic: Are there any plans to automate all of this (like cockroachdb), so that we can just keep adding servers and not have to working about sizing the shards or choosing which server to manage which shards?

**Comment by janardhan1993** [comment]
It's cleaner to use different idx if you change groups as manish suggested. 
It would work in general except is some cases it might screw up the membership information. 

If the node was serving group zero before restart, then after restart with different group id if we loose quorum for group zero, then membership information won't get synced which is bad. To fix this On server restart we should remove membership automatically if we receive a message for a group which is not served by the current node.

In general i think we shouldn't be adding nodes to cluster if we don't have quorum for group zero.

**Comment by MichaelJCompton** [comment]
There are new docs for v0.8 for sharding and clusters here

https://docs.dgraph.io/deploy/#running-dgraph
