### ISSUE TITLE
Lua/LuaJIT Client

### ISSUE THREAD

**Issue by hengestone** [dgraph-io/dgraph#689]
I would love to see a Lua client usable from OpenResty/LuaJIT/Lua using gRPC.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=42878019)](https://www.bountysource.com/issues/42878019-lua-luajit-client?utm_source=42878019&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by crackerplace** [comment]
@manishrjain @hengestone Lua is fun to code and openresty makes it even simpler.I will be interested in this.Also if dgraph only supports grpc,need to see if lua grpc libraries are well supported.

**Comment by hengestone** [comment]
dgraph has an HTTP interface too, which is trivial to use. See all the curl examples in the documentation.
This is about the protobuf interface.
Implementing a basic client that sends/receives messages to the dgraph server is relatively simple too, but requires putting together a few pieces:
1. Use github.com/starwing/lua-protobuf or github.com/Neopallium/lua-pb client to encode/decode messages
2. Connect to the dgraph server over gRPC.  
 2.a. Connecting over HTTP/2 and calling the service endpoints should work.
 2.b. Or for a less ad-hoc implementation binding the C library would be required:  www.grpc.io/grpc/core

I'm happy to give the bounty for 1 and 2.a  demonstrating sending a query to a Dgraph server and getting a response, with no authentication.

**Comment by crackerplace** [comment]
@hengestone Thanks for the detailed info.Got that.
One question that I had was why not use a lua grpc library directly for grcp communication with the dgraph server ? Is it because of lack of lua grpc support ? 

Will start working on this.Thanks.

**Comment by hengestone** [comment]
@crackerplace Using JSON/HTTP(S) is a good place to start, but using protobuf/gRPC is more efficient by far.

**Comment by crackerplace** [comment]
@hengestone yes protobuf/grpc is better.I think your use case is already covered if you go with HTTP endpoints(/query).Also I think the input for these endpoints is graphql query which is not json.

So,wanted to get some clarity on if there is something pending that you are looking for or nothing is needed.Thanks.

**Comment by hengestone** [comment]
You're right, the graphQL+- queries are not JSON, more like RDF. The return values are JSON though, and easily parsed.

So probably not worth pursuing a specialized protobuf client. Thanks again for taking a look :)

**Comment by crackerplace** [comment]
Kool.No Issues.

On the other side are there any lua grpc libraries.I want to just take a look.

**Comment by hengestone** [comment]
No, not that I could find, which was I was looking for a driver in the first place.

**Comment by crackerplace** [comment]
got that.thanks.

**Comment by manishrjain** [comment]
If users are interested, they can build this and send us a PR to add this in our unofficial list of clients. This doesn't need to be tracked here, we don't have any plans to build this.
