### ISSUE TITLE
Too relaxed parsing of function arguments

### ISSUE THREAD

**Issue by tzdybal** [dgraph-io/dgraph#694]
Parsing of function arguments is too relaxed - it is possible to separate arguments only with spaces, without commas. Quoted values can even be used without any separation.

For example, following queries works well:
`{
  movies(func:anyof("name.en" "big lebowski")) {
    name.en
  }
}
`

`{
  movies(func:anyof("name.en""big lebowski")) {
    name.en
  }
}
`
Both queries should cause parsing error.

(Note: Quoting of attribute name will be removed - code is already in the review).

**Comment by ashwin95r** [comment]
130efbf49b5c4bb909fb30db3d0c8644cd757ada should fix this.
