### ISSUE TITLE
Display some version information at the startup

### ISSUE THREAD

**Issue by Rader** [dgraph-io/dgraph#697]
I run into this issue - [Rpc error: unknown service graphp.Dgraph](https://discuss.dgraph.io/t/rpc-error-unknown-service-graphp-dgraph/1341)  -after I run `dgraph` from the command line. Finally I found and old version 0.7.3 is launched, instead of the latest build of Dgraph.

So I am thinking why don't we display some version information at the startup, so that we know we are running the right version of Dgraph?

**Comment by pawanrawal** [comment]
This has been merged to master and the next release would contain this.
