### ISSUE TITLE
Support deletion with only Subject + Predicate

### ISSUE THREAD

**Issue by etix** [dgraph-io/dgraph#699]
Currently deletion requires Subject + Predicate + Object. It should be possible to omit the Object for broader deletions.

**Comment by F21** [comment]
Any chance this can be used to support deletion with just the subject? This would allow us to simulate deleting a node by clearing its properties and all of its edges.

**Comment by janardhan1993** [comment]
Storing list of predicate names for each node is not scalable.
We do support getting list of all predicates, so for simulation you could probably issue a batch mutation by iterating over that list once the feature to delete by subject + predicate is built.

**Comment by manishrjain** [comment]
I think we can store a list of predicates per entity. https://github.com/dgraph-io/dgraph/issues/811

**Comment by ashwin95r** [comment]
`S P *` deletion is now possible from 90a0e3b194faf567c45e613d8e7a2dedc98e6ca9
