### ISSUE TITLE
Python JSON tool mucks up Unicode

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#7]
Write a Golang json parser and formatter tool. Should be pretty simple 20 lines of code.

**Comment by manishrjain** [comment]
Should lie in a separate repo, say dgraph-io/json, so people can `go get` it without pulling any other dependencies.

**Comment by jcmartins** [comment]
Maybe samething like this ?

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
)

func main() {
	b := []byte(`{"hello": "123"}`)
	b, _ = prettyprint(b)
	fmt.Printf("%s\n", b)
}

func prettyprint(b []byte) ([]byte, error) {
	var out bytes.Buffer
	err := json.Indent(&out, b, "", "  ")
	return out.Bytes(), err
}

**Comment by manishrjain** [comment]
Yeah, something similar. Another contributor is building this tool right now.

**Comment by manishrjain** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;8qFFUsIK&#x2F;6-write-a-go-json-parser"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Write a Go JSON parser</a>

**Comment by manishrjain** [comment]
Tracking in Trello. Closing here.

**Comment by Ofekmeister** [comment]
@manishrjain What is the issue?

**Comment by benjamin-rood** [comment]
Do you still want help with this? In Trello it's archived.

**Comment by manishrjain** [comment]
Nvm. It's a small one that we can just hack up quickly. Closing.
