### ISSUE TITLE
update bleve version to latest one

### ISSUE THREAD

**Issue by awsl-dbq** [dgraph-io/dgraph#7014]
Can dgraph upgrade the version of bleve to latest?

https://github.com/blevesearch/bleve/issues/1505#issuecomment-735537763

**Comment by rderbier** [comment]
We also have a request about CJK language linked to bleve.
https://github.com/dgraph-io/dgraph/issues/2801

Package update to be done.

**Comment by anurags92** [comment]
Wouldn't this have sufficed - https://github.com/dgraph-io/dgraph/pull/7040/files?
