### ISSUE TITLE
Vagrant environment for local development

### ISSUE THREAD

**Issue by davcdhanesh1** [dgraph-io/dgraph#702]
Currently, https://wiki.dgraph.io/Contributing_to_Dgraph#Install_statically_linked_Dgraph provides detailed and working instructions on how to setup local dev environment for different OS environments. But still, lots of community effort is wasted in maintaining it and answering queries related to it on different forums. 

- It would be great if we have a vagrant environment with one particular linux flavor supported as base image that setups dev environment. 
- Going ahead the same vagrant environment can be used to spin up Dgraph in cluster mode, otherwise similar queries will start flooding with regards how to run Dgraph in clustered mode.
- A vagrant environment also gives one an opportunity to try out some quick stuff with Dgraph without harming any of the existing Go environment. Currently, one needs to manually create a different Go workspace to setup Dgraph in order to not to conflict with any of the other dependencies on local.

**Comment by manishrjain** [comment]
Hey @davcdhanesh1,

Starting from v0.8, we'll be getting rid of all Cgo. That would allow anyone to `go get dgraph`, and make both development and running easy. Also, Dgraph deps are all vendored in, so it won't bring in lots of packages into your Go environment.

Given such a setup, would Vagrant still be useful?

**Comment by davcdhanesh1** [comment]
Yeah. May be that was something I was looking for. Although, I haven't
tried running in cluster mode on local. For that use case, it would be
great if one gets to see clustering happening between tow separate boxes.

For now, please close the issue

**Comment by manishrjain** [comment]
Feel free to reopen if you think vagrant would be helpful.
