### ISSUE TITLE
mutation with uid/subject 0 crashes dgraph

### ISSUE THREAD

**Issue by knarz** [dgraph-io/dgraph#707]
Hello,

I did a quick search to make sure that I didn't miss any open issues but didn't find anything.
I'm running ec04ad21c7a33a5999be9bbdafc2c5312f9b6535, trying to figure out the query language.

I ran the following via the web interface:

```
mutation {
  set {
   <0x0> <name> "Luke Skywalker" .
  }
 }
```

Which triggered this:

```
2017/03/17 00:34:39 error.go:68: Assert failed
github.com/dgraph-io/dgraph/x.Errorf
        /Users/s/src/go/src/github.com/dgraph-io/dgraph/x/error.go:103
github.com/dgraph-io/dgraph/x.AssertTrue
        /Users/s/src/go/src/github.com/dgraph-io/dgraph/x/error.go:68
github.com/dgraph-io/dgraph/posting.addIndexMutations
        /Users/s/src/go/src/github.com/dgraph-io/dgraph/posting/index.go:80
github.com/dgraph-io/dgraph/posting.(*List).AddMutationWithIndex
        /Users/s/src/go/src/github.com/dgraph-io/dgraph/posting/index.go:193
github.com/dgraph-io/dgraph/worker.runMutations
        /Users/s/src/go/src/github.com/dgraph-io/dgraph/worker/mutation.go:60
github.com/dgraph-io/dgraph/worker.(*node).processMutation
        /Users/s/src/go/src/github.com/dgraph-io/dgraph/worker/draft.go:389
github.com/dgraph-io/dgraph/worker.(*node).process
        /Users/s/src/go/src/github.com/dgraph-io/dgraph/worker/draft.go:422
runtime.goexit
        /usr/local/Cellar/go/1.8/libexec/src/runtime/asm_amd64.s:2197
```

Which then gets triggered every time I try to start dgraph back up until I delete the write-ahead log.

This also seems to trigger it:

```go
	req := client.Req{}
	nq := graphp.NQuad{
		Subject:   "0",
		Predicate: "name",
	}
	client.Str("Luke Skywalker", &nq)
	req.AddMutation(nq, client.SET)

	resp, err := c.Run(context.Background(), req.Request())
	if err != nil {
		log.Fatalf("c.Run: %v", err)
	}
	log.Printf("set resp: %#v", resp)
```

Started dgraph like so:

```
dgraph --debugmode --schema ./test.schema
```

Content of `test.schema`:

```
name: string @index
```

I hope this is not just me missing something.

**Comment by ashwin95r** [comment]
Hey @knarz,

We don't allow UID 0 and have an assert which checks that. We'd make it return an error. Using a non-xero UID should solve the problem.

Thanks

**Comment by manishrjain** [comment]
We should switch this, so an error is returned, instead of crashing the server.

**Comment by knarz** [comment]
Hey,

thank you for the replies. I am aware that the assert is just there to prevent the uid 0 from being added to the db but I don't think crashing the server and potentially leading to a corruption of the WAL is a very intuitive behaviour.

**Comment by ashwin95r** [comment]
Fixed.
