### ISSUE TITLE
Aggregation results not returned

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#708]
I tried to do this query after loading goldendata with the schema
```
{
  directors(
	func: anyofterms(name, "spielberg nolan tarantino"))
		@filter(gt(count(director.film), 5)) {
    name
    director.film {
      name
      min(initial_release_date)
    }
  }
}
```

It only returns `min(initial_release_date)` for Christopher Nolan which is strange.

P.S. - To load goldendata and reproduce this you would have to remove scalar blocks from the schema file.

**Comment by ashwin95r** [comment]
Fixed.
