### ISSUE TITLE
Schemafile should have stricter parsing.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#709]
I tried using the goldendata.schema file to load data on Dgraph master. Although, I had scalar block because of which the scalar types weren't parsed properly, I still did not get any error. Though, when I tried to perform a query which uses indexing, I didn't get back any results.

Either we shouldn't start and tell the user to remove the scalar block or we should be able to parse the scalars within the scalar block?

**Comment by davcdhanesh1** [comment]
+1. Have faced the same issue. And would have preferred an invalid schema
warning which says that filter kind of queries won't work on work fields.

On a side note, do we allow to create / update schema once dgraph server is
started ? I know that one can reindex the fields in existing schema, but
not sure if we can add / remove fields from being indexed.

**Comment by janardhan1993** [comment]
We are going to remove the schema file. 
From next release you would be able to set the schema through gql query

mutation {
schema {
name: string @index
initial_release_date: date @index
director.film:uid @reverse
}
}

**Comment by janardhan1993** [comment]
@davcdhanesh1 From next release you will be able to update/create schema. The changes are merged to master

This issue is no longer valid as we have removed schema file.
