### ISSUE TITLE
Set up Jepsen test for Dgraph

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#711]
Aphyr is super busy -- so it would be a while before he tests Dgraph. We have a few things that need to go in, but we're like to at least do a prelim test to find any edge cases that we haven't handled. So, would be great if someone could run Jepsen test on Dgraph (talk to us before, so we can put those last 5% things in).

**Comment by davcdhanesh1** [comment]
Do we already have a test suite for jepsen ? Or does this involve creating one ?

**Comment by manishrjain** [comment]
Nope, got no idea about what it involves to run Jepsen; so would require setting one up.

**Comment by davcdhanesh1** [comment]
Okay. Nice area for me to start helping dgraph. Will start looking at it.

**Comment by davcdhanesh1** [comment]
Can you tell me few guarantees that you expect Dgraph to always satisfy when running in clustered environment ? One that I can think of is linearizability. Initially, it would be good to start asserting on those and then add more edge cases. What does hivemind reckon about it ?

**Comment by davcdhanesh1** [comment]
Also I find that Dgraph's architecture is somewhat closer to https://github.com/cockroachdb/cockroach. This link ( https://jepsen.io/analyses/cockroachdb-beta-20160829#fnref1 ) shows jespen analysis for it. Can we move on similar lines ?

**Comment by manishrjain** [comment]
- I think linearizability is one of the top ones.
- Then, avoiding data loss in case of crashes.
- Bringing up a new replica server, and ensuring that its version of data equals other replicas.

**Comment by petersondrew** [comment]
I know I'm bumping a very old issue here, but has there been any work done on running DGraph under Jepsen?

**Comment by manishrjain** [comment]
Yes, Kyle himself is working on this :-).
