### ISSUE TITLE
Using order truncates results

### ISSUE THREAD

**Issue by foster36** [dgraph-io/dgraph#714]
The following query only returns a set of movies from 1990, not 1990 and after.

`curl localhost:8080/query -XPOST -d '{
  films(func:geq(initial_release_date, 1990) orderasc: initial_release_date) {
    name: name.en
    release: initial_release_date
    directed_by @filter(allof("name.en", "chris columbus")) {
      name: name.en
    }
  }
}
' | python -m json.tool | less`

If you run it without the orderasc parameter it works as expected, returning all movies from 1990 or later. Thus, the results are truncated when using order.

**Comment by manishrjain** [comment]
Yes, ordering would stop after retrieving 1000 results. If you need to get everything after 1990, then a simple `geq` query should be sufficient. In general, ordering is a bit more expensive operation than just retrieval; so we want users to think a bit deeper about it.

You should be able to override this behavior by specifying how many results you want. for e.g. adding `first: 10000` right next to `orderasc`, would give you 10000 movies sorted by initial release date.

**Comment by manishrjain** [comment]
Closing the issue for now. Please reopen if you'd like to see a different behavior.
