### ISSUE TITLE
Querying _xid_ returns a malformed JSON that can't be parsed

### ISSUE THREAD

**Issue by sayden** [dgraph-io/dgraph#715]
I have compiled commit 1037adf and installed RocksDB from Arch repositories (I'm sorry, I don't know how to check RocksDB version).

You can check with this simple mutation

```
mutation {
 set {
   <mario> <name> "sayden" .
   <mario> <likes> <tesla> .
   <tesla> <name> "teslunia" .
 }
}
```

And this query

```
{
	me(id: mario){
		name
		likes {
			name
			_xid_
		}
	}
}
```

Returns `Unexpected ','` because, actually, response has the following data:

```
{"me":[{"likes":[{"_xid_":,"name":"teslunia"}],"name":"sayden"}]}
```

Look that `_xid_` returns nothing (not an empty string I mean)

Regards!

**Comment by manishrjain** [comment]
Thanks for reporting this.

**Comment by pawanrawal** [comment]
Fixed and merged to master, will be part of next release.
