### ISSUE TITLE
May I ask why dgraph doesn’t have a real deletion of node?

### ISSUE THREAD

**Issue by huashaoxu** [dgraph-io/dgraph#7180]
Here is a question about the Node.
If I delete all the contents of the Node and leave it alone,there will be a Node exist in the databse all the time(the Node only has a UID).

Suppose we have many of these kinds of Node,Does this affect search efficiency or the usage of memeory?

**Comment by WolfgangFahl** [comment]
Why is this closed here?

**Comment by MichelDiz** [comment]
@huashaoxu nope, this scenario won't affect performance at all.
