### ISSUE TITLE
Support reloading TLS certificates

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#724]
TLS support was recently added which is really great!

It would be nice if there is some mechanism to support reloading TLS CA and node certificates. This would be extremely useful in cases where we are using something like Vault as a CA and want to issue short-lived certificates (24 to 48hrs). We would then have a process or container in Kubernetes renewing the certificate and having the ability to trigger dgraph to reload the certificates without restarting the server would enable this.

There is currently an RFC for this for cockroachdb that could be used as a reference: https://github.com/cockroachdb/cockroach/pull/14254

ref: https://github.com/cockroachdb/cockroach/issues/1674

**Comment by manishrjain** [comment]
@tzdybal Can you coordinate with the original contributor of this feature, to see if they'd be willing to help achieve this?

**Comment by tzdybal** [comment]
Yes. @Motakjuq contacted, waiting for response.

**Comment by tzdybal** [comment]
Committed to master (99452dbde73ab86e9d3f24e3c8b8f52902dd622b).
