### ISSUE TITLE
Support for mutation variables

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#726]
It would be nice if variables are supported (like graphql) for mutations. This would make the code for executing mutations much neater, as opposed to using `fmt.Sprintf` to piece a mutation together.

I am not sure if the mutation language is susceptible to injection like SQL, but if it is, variables would also offer projection.

**Comment by F21** [comment]
Query variables are supported. When using the go client, mutation variables are probably unnecessary.

**Comment by jimanvlad** [comment]
Mutation graphql variables should be useful in the case where you want to load chunks of streaming data.

For example, you have 100 rows of data from a relational database and, for each row, you want to create a number of nodes and edges. Evidence from Neo4J indicates that if you send the query string once, and a map of variables for the 100 rows, the I/O is much less and therefore everything should be processed quicker. 

Any views @pawanrawal ?

**Comment by pawanrawal** [comment]
We are going to support GraphQL mutations soon. Mutation variables would be supported along with that.

**Comment by jimanvlad** [comment]
> We are going to support GraphQL mutations soon.
What do you mean by GraphQL mutations? I thought we already have mutations in GraphQL+...

**Comment by pawanrawal** [comment]
Yeah we already have mutations in GraphQL+- but they are different from how GraphQL does them. Example of a GraphQL mutation http://graphql.org/learn/queries/#mutations.

**Comment by F21** [comment]
Reopening this as I have been trying out upsert blocks lately and this is a must:
- String concatenation of user supplied values in the mutation is unwieldly
- Blindly doing string concatenation of user supplied values in the mutation is outright dangerous/allows query/mutation injection

**Comment by MichelDiz** [comment]
hey @F21, please open a new issue. The newer the better, and the more unique, the better.

Folks who review the issues don't often come after old issues. The best tip is if you have something new, even if it has to do with this issue. Create a new one. And as detailed as possible, following the fill-up issues rules.

You have to attract the team. Reopening this issue and writing a short text makes us believe that it is part of a conversation. Not a new thing.

Cheers.
