### ISSUE TITLE
Support graphql variables in client

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#727]
GraphQL variables are supported in the query language: https://wiki.dgraph.io/Query_Language#GraphQL_Variables

It would be nice if the clients can be updated to support it.

I use neelance/graphql for creating graphql servers and it handles variables like this: https://godoc.org/github.com/neelance/graphql-go#Schema.Exec.

Variables are provided as a map: `map[string]interface{}`

**Comment by manishrjain** [comment]
This is done.

**Comment by pawanrawal** [comment]
Here is an example https://godoc.org/github.com/dgraph-io/dgraph/client#example-Req-SetQueryWithVariables demonstrating how it works.
