### ISSUE TITLE
Filtering for reverse uid returns an empty result

### ISSUE THREAD

**Issue by sayden** [dgraph-io/dgraph#731]
The use of `@filter` doesn't work as expected when used with reverse uids. How to reproduce:

Having the following schema:
```
name: string @index
dog_of_person: uid @reverse
type: string @index
```

Making the following mutation:
```
mutation{
	set{
		<sayden> <type> "Person" .
		<sayden> <name> "mario" .
		<tesla> <type> "Dog" .
		<tesla> <name> "Teslunia" .
		<tyrion> <type> "Dog" .
		<tyrion> <name> "Tyrionek" .
		<tyrion> <dog_of_person> <sayden> .
		<tesla> <dog_of_person> <sayden> .
		<ula> <type> "Person" .
		<ula> <name> "Ula" .
	}
}
```

We want to know people who has more than one dog. In this example, `sayden` has 2 dogs while `ula` has none. The name of the relationship is `dog_of_person` and goes from dog to person ( dog -> person).

I'm expecting this query to return the expected result:

```
{
	users(func:allofterms(type, "Person")) @filter(gt(count(~dog_of_person), 1)){
		type
		name
		count(~dog_of_person)
	}
}
```

Instead it is returning me an empty json `{}`

Trying without reverse index seems to work:

If you need more information, just ask :) I'm also open to fix it myself if you give some guidance through your code.

**Comment by davcdhanesh1** [comment]
A question regarding mutation,

Do you want to say that <sayden> own a dog named <tyrion> and <tesla>.
Then, entries in set block should be

<sayden> <dog_of_person> <tesla>
<sayden> <dog_of_person> <tyrion>

Or may be I misunderstood this ? Although, I haven't yet verified the
result of 'count' aggregate function with either of inputs.

**Comment by ashwin95r** [comment]
Hey @sayden,

Thanks for the detailed report! Yes this was a bug. I have a fix for this in: 

Will be merged soon. 

Thanks.

**Comment by davcdhanesh1** [comment]
For me it says, 'dog_of_person' ( i.e. reverse edge ) is not valid scalar
type. I have latest pull from yesterday evening.

**Comment by ashwin95r** [comment]
Try to clear the `p/` and `w/` dirs before running @davcdhanesh1.

**Comment by davcdhanesh1** [comment]
Worked.

**Comment by sayden** [comment]
@davcdhanesh1 

Yes. intuitively it would be "persons" pointing to "dogs" but in our data this relation in stored in reverse (dogs pointing to persons). We need to mainting this relationships, that's why we prefer to store it in the same way.

We could still store it "properly" but it would require and extra logic layer for this cases, which is quite common in our data.

Of course, dogs and persons are a simplification of our data.

**Comment by ashwin95r** [comment]
Fixed.
