### ISSUE TITLE
Allow specifying lang tags in order arguments

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#751]
```
{
 var(func:allofterms(name, "angelina jolie")) {
  name@en
   actor.film {
  performance.film {
    #D as name@en
     B AS genre 
    }
   }
  }

 films(id: var(B), first:3) @filter(gt(count(~genre), 1)){
  name@en
  ~genre (first:5, orderdesc: name@en) {
      name@en
    }
 }
}
```
This query throws `Expecting argument name. Got: lex.Item [15] "@"`. We should allow specifying lang tags in the argument list.
Just specifying name might pick up different tags for different entities and order based on them which might be incorrect.

**Comment by tzdybal** [comment]
Fix merged to `release/v0.7.4` branch.
