### ISSUE TITLE
Can't read schema written by backup

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#754]
I loaded the 21million.rdf.gz using the 21million.schema file via the dgraphloader. Then took a backup and tried to load back the data using the dgraphloader and backed up data and schema files and got the error.

```
Processing ../dgraph/backup/dgraph-schema-1-2017-03-27-15-56.rdf
2017/03/27 16:02:36 main.go:87: Error while parsing schema: Missing Type, on line:122 http://www.w3.org/2002/07/owl#inverseOf:uid
```

Another thing is that probably we shouldn't write schema (and backup?) file for group 0 because that's always empty?

**Comment by janardhan1993** [comment]
Now while writing backup if predicate contains colon, we output the predicate surrounded by <>
<http://www.w3.org/2002/07/owl#inverseOf>:uid

We don't have anything stored in group 0, so skipping backup for group zero.
