### ISSUE TITLE
Indexing name using exact tokenizer takes a lot of time.

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#758]
I loaded up the 21million.rdf.gz data set with the 21million.schema, which specifies the default index on name. Then I performed this mutation
```
curl localhost:8080/query -XPOST -d $'
mutation {
  schema {
    name: string @index(exact) 
  }
}' | python -m json.tool | less
```

After 20 minutes, we hadn't returned the request. Should we wait till indexing is completely done?

**Comment by janardhan1993** [comment]
We wait till the indexing is completely done. We could return early but then the user has to check the logs to find out when the indexing is completed.

**Comment by pawanrawal** [comment]
It took more than 25 mins earlier. Now after @ashwin95r's change it takes 2 mins which is more reasonable.
