### ISSUE TITLE
Setting bool as index crashes Dgraph server

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#764]
curl localhost:8080/query -XPOST -d 'mutation { schema { initial_release_date: bool @index }}' 

Would crash Dgraph.

**Comment by pawanrawal** [comment]
Related issue, we crash if its just `bool @index`, but `bool @index(term)` actually does indexing.

**Comment by pawanrawal** [comment]
This is done and merged to release branch.
