### ISSUE TITLE
No complaint if string index is not present

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#768]
```{
  directors(func: anyoftext(name@en, "spielberg nolan tarantino")) {
    director: name@en
  }
}
```

In this case, I ran `curl localhost:8080/query -XPOST -d 'mutation { schema { name: date @index }}'`. So, there's no FT index for `name`. But, no error is returned when running the query above.

Similarly, it should also complain if we run `anyofterm`, and the corresponding `allof` functions.

**Comment by tzdybal** [comment]
Merged to release branch.
