### ISSUE TITLE
Schema type behaving unpredictably

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#787]
```
mutation {
  set {
    <a> <age> "13" .
  }
}
```
No storage type given, so stored as default type.

```
mutation {
  set {
    <b> <age> "13"^^<xs:int> .
  }
}
```
This is also stored as default type as returned by `schema{}`

Now lets change its type to date.
```
mutation {
  schema {
    age: date .
  }
}
```

It succeeds.

Then doing
```
{
  me(id:a) {
    age
  }
}
```
doesn't return a age, but for id: b it returns an age.

**Comment by janardhan1993** [comment]
Expected behaviour, not an issue.
We try to convert to schema type, if conversion fails we ignore the value.
