### ISSUE TITLE
query schema through exception:Cannot read property 'total' of undefined

### ISSUE THREAD

**Issue by Rader** [dgraph-io/dgraph#788]
run this from UI
```
schema{
 
}
```
It reports error "**Cannot read property 'total' of undefined**" . But if open the dev console of Chrome, the schema has been return successfully in JSON.

**Comment by pawanrawal** [comment]
Hi @radar

This has been fixed in the release/v0.7.4 branch. Could you try with that? We will release v0.7.4 tomorrow.

**Comment by Rader** [comment]
OK, i will try it later

**Comment by manishrjain** [comment]
@pawanrawal -- is this fixed? Is it part of v0.7.4?

Any bug fixes should go into the latest release.

**Comment by pawanrawal** [comment]
Yes, this was fixed and is part of the release. Waiting for @Rader to confirm and close the issue.

**Comment by pawanrawal** [comment]
Hi @Rader 

I am closing this for now as this was fixed and pushed as part of v0.7.4 release. If you still face this issue, then feel free to reopen it.
