### ISSUE TITLE
Lang tag in orderasc errors

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#793]
This query 
```
{
  me(func:regexp(name, "^[a-zA-z]*[^Kk ]?[Nn]ight"), orderasc: name@en, first:5) {
	name@en
	name@de
	name@it
  }
}
```
returns
`Expecting argument name. Got: lex.Item [15] "@"`

**Comment by tzdybal** [comment]
The problem is when using `@lang` notation in ordering at root (in filters everything works fine).

**Comment by tzdybal** [comment]
Fix merged to master.
