### ISSUE TITLE
Avro support

### ISSUE THREAD

**Issue by jadbox** [dgraph-io/dgraph#794]
As an alternative to json and protobuf support, native encoded payloads for Avro would be ideal for our use-cases, as we've tried to standardize on a single encoding strategy across the board.

**Comment by manishrjain** [comment]
Thanks for the request. I'm not sure how many people/companies are using Apache Avro; when compared to JSON or Protobufs. If we add it to upstream, we'll have to maintain it over time. So, we'll do this if it seems like something enough people are going to need it.

**Comment by manishrjain** [comment]
Closing it for now. If there're enough people who want this, we'll consider building it.
