### ISSUE TITLE
Make BatchMutation.Flush()'s retry logic tunable for the Go client

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#796]
Calling `Flush()` on a `BatchMutation` retries forever (every 5ms). It would be nice if this is tunable.

For example, if the batch fails after retrying 5 times, abort and return an error.

**Comment by manishrjain** [comment]
@janardhan1993 : Can you have a look?

**Comment by pawanrawal** [comment]
This is now supported through the [MaxRetries](https://godoc.org/github.com/dgraph-io/dgraph/client#BatchMutationOptions) option.
