### ISSUE TITLE
@filter(NOT var(VARIABLE)) not working as expected

### ISSUE THREAD

**Issue by maktouch** [dgraph-io/dgraph#802]
## Preparation

```
mutation {
    schema {
        username: string @index .
        is_following: uid @reverse .
        is_blocking: uid @reverse .
    }

    set {
        <user_A> <username> "user_A" .
        _:B <username> "user_B" .
        _:C <username> "user_C" .
        _:D <username> "user_D" .
        _:E <username> "user_E" .
        _:F <username> "user_F" .

        <user_A> <is_following> _:B .
        <user_A> <is_following> _:C .
        <user_A> <is_following> _:D .
        <user_A> <is_following> _:E .
        <user_A> <is_following> _:F .

        _:C <is_blocking> <user_A> .
    }
}
```

Query A

```
{
    me(id: user_A) {
        username
        is_following {
            username
        }
    }
}
```

It should return 6 nodes, 5 edges. 

Query B 

```
{
    var(id: user_A){
        BlockingMe as ~is_blocking
    }
}

{
    me(id: user_A) {
        username
        is_following @filter(var(BlockingMe)) {
            username
        }
    }
}
```

It should return 2 nodes, 1 edge.

Now here's the interesting part

Query C

```
{
    var(id: user_A){
        BlockingMe as ~is_blocking
    }
}

{
    me(id: user_A) {
        username
        is_following @filter(NOT var(BlockingMe)) {
            username
        }
    }
}
```

It returns 2 nodes, 1 edge. Expected: 5 nodes, 4 edges.

**Comment by janardhan1993** [comment]
Fixed and pushed the changes to master and release/v0.7.4 branch.

**Comment by maktouch** [comment]
Hi, just to clarify, cause I see that 0.7.4 was released 5 days ago but you just pushed the changes to the same tag. How do I get the release with the patch? Do I have to compile the binaries on my own or do you guys have a CI pipeline? 

I want to help you guys test :-)

**Comment by pawanrawal** [comment]
Hi @maktouch 

We will do a `v0.7.4-1` release this Friday. Just waiting to see if there are any more fixes to go in and then we will tag the new release and upload the new binaries. Till then if you would like, you could build from source on the `release/v0.7.4` branch and test this.
