### ISSUE TITLE
Allow unused variables during development

### ISSUE THREAD

**Issue by jansenignacio** [dgraph-io/dgraph#803]
Is it possible to have a flag to turn off the check for unused variables? During development, I believe it's normal to have unused variables. I don't think it's practical to have to comment variables in and out when you're trying stuff out.

**Comment by maktouch** [comment]
`Some variables are defined but not used Defined:[A] Used:[]`

Very annoying indeed!

**Comment by manishrjain** [comment]
This behavior is consistent with how Golang deals with unused variables. Even though, it's annoying initially, it provides for better and more readable code in the long run.
