### ISSUE TITLE
Initial release date changes based on query timezone

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#807]
I'm seeing two different dates for a historical fact.

Query:
```
{
  me(id: m.06pj8) {
    name@en
    director.film(orderdesc: initial_release_date, first: 2) {
      name@en
      initial_release_date
    }
  }
}
```

Response 1:
```
{
  "me": [
    {
      "director.film": [
        {
          "initial_release_date": "2015-10-16",
          "name@en": "Bridge of Spies"
        },
        {
          "initial_release_date": "2012-10-08",
          "name@en": "Lincoln"
        }
      ],
      "name@en": "Steven Spielberg"
    }
  ]
}
```

Response 2:
```
{
  "me": [
    {
      "director.film": [
        {
          "initial_release_date": "2015-10-15",
          "name@en": "Bridge of Spies"
        },
        {
          "initial_release_date": "2012-10-07",
          "name@en": "Lincoln"
        },
      ],
      "name@en": "Steven Spielberg"
    }
  ]
}

```

**Comment by manishrjain** [comment]
Nothing. We had this reply on our documentation. I re-ran the query using play.dgraph.io; and the results were different. I think maybe because play.dgraph.io is running in the US timezone, and if you run it on your machine, it would be on the Australian timezone.

**Comment by pawanrawal** [comment]
The responses to the query on our docs are very old. This might have been in the older versions but cannot reproduce it on the current version. We take care to convert to `UTC()` while marshalling and un-marshalling dates.
