### ISSUE TITLE
Support GraphQL variables in functions

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#809]
The following is currently unsupported:

```graphql
query versions($version: int!) {
  versions(func:eq(type, "version")){
     _uid_
     versions @filter(eq(version_number, $version)) {
       _uid_
       version_number
      }
   }
}
```

**Comment by manishrjain** [comment]
Yeah. We should fix that. Though, something I noticed about the query: you can do the filtering right next to the type equality function.

**Comment by F21** [comment]
> Though, something I noticed about the query: you can do the filtering right next to the type equality function.

I am not sure what you mean here. Can you provide an example?

**Comment by manishrjain** [comment]
Sorry, I misunderstood the query. You're first looking for something of type "version", and then looking for all the versions attached to that entity; and then filtering on them.

If arranged differently, you could attach a type "version" to all the versions directly, and then look for them and filter them at the same time.

```
{
  versions(func: eq(type, "version")) @filter(eq(version_number, $version)) {
    version_number
  }
}
```

**Comment by ashwin95r** [comment]
Fixed.
