### ISSUE TITLE
eq func returns an error if no schema is set

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#810]
1. Start a brand new dgraph server with no data.

2. Run this query:
```graphql
{
    versions(func:eq(type, "versions")){
        version{
            version
        }
    }
}
```

It returns `Attribute type is not valid scalar type`.

I expect it to return no results.

**Comment by manishrjain** [comment]
I think the error can be modified to represent that we have no type information for `type`. But, it should still return an error.

Empty result makes sense if `eq` function returned no results. In this case, we couldn't even run the `eq` function. So, an error makes sense.

**Comment by pawanrawal** [comment]
Improved the error message and merged to release.
