### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [dgraph-io/dgraph#8113]
Hey there!

I belong to an open source security research community, and a member (@dwisiswant0) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by dwisiswant0** [comment]
Sorry for the ping, @manishrjain.

**Comment by danielmai** [comment]
Please email security@dgraph.io, thanks.

**Comment by JamieSlome** [comment]
It looks like our system sent further details to `contact@...`.

If you would prefer @danielmai, you can view the report details directly here:

https://huntr.dev/bounties/033a2a9c-358b-44e7-b034-019106fd8709/

It is only visible to maintainers with repository write permissions.

**Comment by JamieSlome** [comment]
@danielmai - sorry that this slipped through, I have just followed up with an e-mail to the `security@` address 👍
