### ISSUE TITLE
“func: type() “error in 20.11.03 or later

### ISSUE THREAD

**Issue by zhaolin-st** [dgraph-io/dgraph#8118]
I have report this issue in dgraph discuss https://discuss.dgraph.io/t/func-type-error-in-20-11-03-or-later/16237

After a month has passed, this issue has not been resolved, so I posted it in github issues again

In my application we use type() function ( using GraphQL+-) to get node list of nodes.

But in the new version I encountered a problem that I cannot query according to the node type.

We have no problem with the same data in version 20.11.0, but this version has the problem of write amplification.

After we upgraded to 20.11.3（which fix the wirte amplification）, we encountered the problem that some nodes could not be queried by node type.

There are more than a dozen types of nodes in our application, only two types of nodes (the two with the largest number，) will have problems, and other types can be queried normally using type

The two types of nodes in question have approximately 6,000,000 and 50,000,000 respectively.

Later, we tried 21.03.0 and 21.03.2, these two types of nodes still cannot be queried

The data of these nodes is not lost. It can still be queried through predict or has(predict_of_specific_node), but these two type of nodes just cannot be queried through the type fuction.

I would like to ask whether the version after 20.11.3 has made any new changes to the storage or query method of dgraph.type?

Later 

I tried to upgrade our dgraph to version 21.12.0

The problem of the previous node type query still exists, and it is more serious

query person 
```
{
  res(func: type(person)) {
    count(uid)
  }
}
```
The number of nodes of the person obtained by the query result is 0
```
{
    "res": [
      {
        "count": 0
      }
    ]
}
```
But when we change the query method, instead of using type, we query based on predicate, and we can see that there are actually nodes in the data with the dgraph.type attribute of **person**.

```
{
  res(func: has(person_name),first:3) {
    count(uid)
    uid
    dgraph.type
    gender
  }
}
```

```
{
    "res": [
      {
        "count": 3
      },
      {
        "uid": "0x1d9026e53a",
        "dgraph.type": [
          "person"
        ],
        "gender": [
          "f"
        ]
      },
      {
        "uid": "0x25c65d6603",
        "dgraph.type": [
          "person"
        ],
        "gender": [
          "f"
        ]
      },
      {
        "uid": "0x2b515fd59e",
        "dgraph.type": [
          "person"
        ],
        "gender": [
          "m"
        ]
      }
    ]
  }
```

**Comment by amaster507** [comment]
This seems to describe what you are seeing:

https://dgraph.io/blog/post/v2112-release/

> Forbid Massive Fan-outs
> 
> Certain keys in the graph suffer from a massive fan-out problem. These keys are typically index keys. For example, a certain string value might be a default value set to all the nodes in the graph. A reverse index on this value could point to millions of nodes in the graph, hence creating huge posting lists. Dgraph would split such a posting list across multiple keys, so as not to exceed Badger’s value limits and also allow partial reads of this index key.
> A typical key like this would have dozens of splits. We noticed, however, that some keys have thousands of splits – that’s possible when the fan-out is in billions of nodes. A query using this key would be slow at best and would crash the system at worst by causing a massive memory consumption or a massive CPU spike.
In v21.12, we have added a flag to forbid any key which has greater than 1000 splits by marking it forbidden in Badger. Once a key is forbidden, that key would continue to drop data and would always return an empty result.
> Almost all backends we have seen (in Dgraph Cloud) are not affected by this change. But, in the rare case that a user is affected, rewriting the query to use another key for the root function would fix the issue. We think this small downside is worth the upside of keeping the system stable and performant.

**Comment by zhaolin-st** [comment]
Hi, Amaster507! 
Nice to see you again !

I wirte a simple Python Script to repoduce this problem.

Frist, setup a dgraph by docker
```
docker run -it --name dgraph -p 5080:5080 -p 6080:6080 -p 8080:8080 -p 9080:9080 dgraph/standalone:v21.12.0
```

Then, you may need a python env to run the script and use pip to install pydgraph and faker
```
pip install faker pydgraph
```
```
import pydgraph
import hashlib
import time
import requests
from faker import Faker



client_stub = pydgraph.DgraphClientStub('192.168.171.77:9080')
client = pydgraph.DgraphClient(client_stub)

# lease_uid
# /assign?what=uids&num=100 allocates a range of UIDs specified by the num argument, 
# and returns a JSON map containing the startId and endId that defines the range of UIDs (inclusive). 
# This UID range can be safely assigned externally to new nodes during data ingestion.
# See docs in https://dgraph.io/docs/deploy/dgraph-zero/


url = "http://192.168.171.77:6080/assign?what=uids&num=1000000000000000000"

payload={}
headers = {}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)

# convert xid to dgraph_uid and make sure uid under uid num we juset lease(assign?what=uids&num=1000000000000000000)
def xid2uid(xid):
    uid = "0x" + hashlib.md5(xid.encode(encoding='utf-8')).hexdigest()[8:23]
    return uid

faker = Faker('en_US')


batch_size = 50
for i in range(10000):
    rdf = ""
    for j in range(batch_size):
    # create data
        name = faker.name()

        person_xid = f"person_{i*batch_size + j}"
        person_uid = xid2uid(person_xid)
        rdf += f'''<{person_uid}> <dgraph.type> "person" .\n'''
        rdf += f'''<{person_uid}> <xid> "{person_xid}" .\n'''
        rdf += f'''<{person_uid}> <person_name> "{name}" .\n'''
        
    txn = client.txn()
    # Running a Mutation
    txn.mutate(set_nquads=rdf)
    txn.commit()
    
    print(f"Finish mutation {i * batch_size + j} nodes")
 ```
The Script above make sure each nodes has a "person" dgraph.type and has a random value of person_name.

After run this,  I tried to check these nodes in Ratel
```
{
  res(func: has(person_name)){
    count(uid)
  }
}
```
```
{
  "data": {
    "res": [
      {
        "count": 500000
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 36031,
      "processing_ns": 2213543572,
      "encoding_ns": 120902912,
      "assign_timestamp_ns": 780213,
      "total_ns": 2335353583
    },
    "txn": {
      "start_ts": 21066
    },
    "metrics": {
      "num_uids": {
        "_total": 0,
        "person_name": 0
      }
    }
  }
}
```
```
{
  res(func: type(person)){
    count(uid)
  }
}
```
this result maybe 0, or other value lower than the result of query by has(person_name)

```
{
  res(func: has(person_name),first:3) @filter(not type(person)){
    count(uid)
    dgraph.type
    person_name
    xid
  }
}
```
```
{
  "data": {
    "res": [
      {
        "count": 3
      },
      {
        "dgraph.type": [
          "person"
        ],
        "person_name": "Jessica Johnson",
        "xid": "person_14228"
      },
      {
        "dgraph.type": [
          "person"
        ],
        "person_name": "Joe Stewart",
        "xid": "person_61"
      },
      {
        "dgraph.type": [
          "person"
        ],
        "person_name": "Linda Cox",
        "xid": "person_30812"
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 68446,
      "processing_ns": 89664232518,
      "encoding_ns": 59379,
      "assign_timestamp_ns": 295900,
      "total_ns": 89671218655
    },
    "txn": {
      "start_ts": 34260
    },
    "metrics": {
      "num_uids": {
        "": 105700,
        "_total": 211409,
        "dgraph.type": 105703,
        "person_name": 3,
        "xid": 3
      }
    }
  }
}
```
