### ISSUE TITLE
[Bug] Entities Response for Apollo Federation is out of order

### ISSUE THREAD

**Issue by JLaferri** [dgraph-io/dgraph#8120]
Unfortunately I don't know the minimal amount of data required to trigger this behavior but basically the data returned in `_entities` is not in the same order as the objects in my `representations` input. This causes the data to mismatch with the ID when using Dgraph as a subgraph.

Here is an example:
![image](https://user-images.githubusercontent.com/1534726/148892575-0fdcd993-cee4-415f-bbfb-3ff1823f14eb.png)

It does look like the logic attempts to order the entities correctly as per here: https://github.com/dgraph-io/dgraph/blob/master/graphql/resolve/resolver.go#L407

Seems for some reason this fails for me. I suppose I will tag @minhaj-shakeel as it seems this was written by them.

Additionally, I will try to get a local dev environment set up for Dgraph tomorrow to see if I can fix this bug though I have a feeling I may struggle getting that going.

**Comment by tomhollingworth** [comment]
What version are you running? I see that v21.12.0 *might* have a fix for this from https://github.com/dgraph-io/dgraph/pull/7542
