### ISSUE TITLE
sroar bug

### ISSUE THREAD

**Issue by rip-create-your-account** [dgraph-io/dgraph#8131]
Surely the [Memclr function in sroar](https://github.com/dgraph-io/sroar/blob/3e3f1b382a645baf0f452776a005e560e5010bf0/utils.go#L100) should instead look like the following:

``` go
func Memclr(b []uint16) {
	if len(b) == 0 {
		return
	}
	p := unsafe.Pointer(&b[0])
	memclrNoHeapPointers(p, uintptr(len(b) * 2))
}
```

Right now it's clearing only the first half of the array and top half of the middle element. [Now, watch this godbolt](https://go.godbolt.org/z/cqs79qbbP). If you go back in the commit history, you will notice that at one point it did clear the whole array.

**Comment by manishrjain** [comment]
This is correct. Looks like it got left behind when we converted from `[]byte` to `[]uint16` (the func was originally in Ristretto/z pkg). I'll get it fixed up in https://github.com/outcaste-io/sroar .

**Comment by manishrjain** [comment]
Done. https://github.com/outcaste-io/sroar/commit/32ae257f74102d179754c8fa59b84610297b7f5f

**Comment by rip-create-your-account** [comment]
Neat. Do I read it correctly that the use of Memclr is there just as a form of defensive programming? So this bug could have caused no harm. Also, should I close this issue?

**Comment by manishrjain** [comment]
> Do I read it correctly that the use of Memclr is there just as a form of defensive programming?

Incorrect Memclr could cause issues if a container switches from array to bitmap.

>  Also, should I close this issue?

I'm no longer with Dgraph Labs, so can't speak on their behalf. But, feel free to use outcaste-io/sroar which I and other original authors are maintaining.
