### ISSUE TITLE
Couldn\’t rewrite query because Argument () of * was not able to be parsed as a string

### ISSUE THREAD

**Issue by HugooB** [dgraph-io/dgraph#8134]
Hi there!

After days of debugging I just cannot figure out why my query is not working. This is the setup running [Dgraph v21.12.0](https://github.com/dgraph-io/dgraph/releases/tag/v21.12.0):

**Scheme**

```
type Chat {
  chat_id: Int! @id
  messages: [Message] @hasInverse(field: chat)
  title: String @search(by: [term, fulltext])
}

type Message {
  chat: Chat!
  message: String! @search(by: [term, fulltext])
  message_id: Int! @id
  timestamp: DateTime!
  user: User!
}

type User {
  messages: [Message] @hasInverse(field: user)
  user_id: Int! @id
  username: String
}
```
**Query**

```
query getChat($x: Int!) {
  getChat (chat_id: $x) {
    chat_id
    title
    messages { message }
  }
}
```
**Variables**
```
{"x": 1173233405}
```
**Error**

couldn’t rewrite query getChat because Argument (chat_id) of getChat was not able to be parsed as a string

Putting the chat_id directly into the query does work:

```
query getChatQuery {
  getChat(chat_id: 1173233405) {
    chat_id
    title
    messages { message }
  }
}
```
But separating the query and variables does not. Does anybody have any clue what I’m doing wrong?

After reading through the documentation I noticed that `@id` declarations can only be assigned to `Strings` types, [as stated in the docs](https://dgraph.io/docs/graphql/schema/ids/). However, the Dgraph v21.03.0 [release notes](https://github.com/dgraph-io/dgraph/releases/tag/v21.03.0) state the following:

- Fix(GraphQL): adding support for @id with type other than strings ([#7019](https://github.com/dgraph-io/dgraph/pull/7019))

So, it this a bug? @akon-dey encouraged me to file this Github issue, more info here:
https://discuss.dgraph.io/t/couldn-t-rewrite-query-because-argument-of-was-not-able-to-be-parsed-as-a-string/17376/2

**Comment by MichelDiz** [comment]
There's no fix until we process the cherry pick of #7019

**Comment by IDerr** [comment]
Perfect, thanks for the quick answer

**Comment by IDerr** [comment]
Is there any release planned for the cherry pick ? I just saw it was pushed 2y ago,
