### ISSUE TITLE
Sharding across multiple machines

### ISSUE THREAD

**Issue by iquerame2** [dgraph-io/dgraph#8135]
I am trying to deploy sharding in a multi-machine setting, where each physical machine (VM) contains a different shard collection (potentially with replicas). In particular, is it possible not to have the same shard collection automatically replicated across all machines? Otherwise said, can we work with different database fragments on each machine?
 Please tell me if you know some DBMS that ensure this setting.
 Thank you!

**Comment by rarvikar** [comment]
It is possible to shard the database across different physical machines (or VMs). Can you please reach out to us at success@dgraph.io for us to continue this conversation and provide you with detailed info based on your requirements. 

Thanks!

**Comment by MichelDiz** [comment]
@iquerame2 if you are still waiting for this. Please just open a thread at discuss https://discuss.dgraph.io/
this way we can help you. Issues on Github aren't for questions.
