### ISSUE TITLE
Dgraph cloud is down

### ISSUE THREAD

**Issue by dpgarrick** [dgraph-io/dgraph#8149]
Hi

We use Dgraph cloud and our backend is currently down.

I cannot log into the dgraph cloud site either.

Discuss pages also down.

Status page says everything is working.

Is this being worked on?

**Comment by skrdgraph** [comment]
@dpgarrick - we are aware of this issue. And we are working to get this resolved.

**Comment by dpgarrick** [comment]
Thanks for the update.

**Comment by skrdgraph** [comment]
@dpgarrick we have fixed the issue, and are keeping the status page in `monitoring` state. Please let us know if you continue to see errors. 

fyi @rarvikar

**Comment by dpgarrick** [comment]
Thank you, backend is working again now.

**Comment by rarvikar** [comment]
Thanks, a fix was implemented last week to address the issue. I'll go ahead and close this issue at this point.

**Comment by skrdgraph** [comment]
@dpgarrick - I think there is a small confusion on your end. When we reported the cloud-dashboard to be down, we also indicated the backends are healthy. The cloud-dashboard facilitates in making changes to your cluster. The existing backends were unaffected during this incident.

**Comment by dpgarrick** [comment]
> @dpgarrick - I think there is a small confusion on your end. When we reported the cloud-dashboard to be down, we also indicated the backends are healthy. The cloud-dashboard facilitates in making changes to your cluster. The existing backends were unaffected during this incident.

Our backend was inaccessible to us during the outage. It became accessible again after you applied your fix. I can't speak to your definition of a backend being healthy.

**Comment by skrdgraph** [comment]
@dpgarrick would it be possible to file a support ticket with us? We would like to look at your backend. Please don't share your backend information here (as this is public). Also in the ticket could you walk us through the exact issues you experienced.
