### ISSUE TITLE
Websockets Protocol (subscriptions-transport-ws) is Depreciated

### ISSUE THREAD

**Issue by jdgamble555** [dgraph-io/dgraph#8174]
DGraph currently uses a depreciated and insecure websockets protocol: `subscriptions-transport-ws`.  They recommend changing to use `graphql-ws`.  

https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md

The creator of the `graphql-ws` even suggested that you use it in [DGraph Discuss](https://discuss.dgraph.io/t/support-graphql-over-websocket/12698).  This would have to be updated before V1 is released, as it is NOT compatible with the other protocol.

[Hasura uses both](https://hasura.io/docs/latest/subscriptions/postgres/index/), so you could easily add the new protocol without causing depreciation problems!

J

**Comment by Poolshark** [comment]
This would be great! Especially for Relay users it would be much easier to use `garphql-ws`.
