### ISSUE TITLE
Feature Request - GraphQL - Composite (compound) ID fields - unique / primary

### ISSUE THREAD

**Issue by jdgamble555** [dgraph-io/dgraph#8176]
https://discuss.dgraph.io/t/composite-id-fields/13337
https://discuss.dgraph.io/t/support-multiple-unique-fields-in-dgraph-graphql/8512/15

There are 1000 links in the DGraph forum for this, but basically:

```graphql
type Bar @unique(user, date) {
  user: String!
  date: String!
}
```

We need this SQL equivalent:  ```ALTER TABLE `Bar` ADD UNIQUE `unique_index`(`user`, `date`);```

We need unique values based on two fields at the same time.  There are 1000 use cases for this, but it is a necessity in any mature database.  There are only work arounds in CERTAIN situations.  

J
___

**UPDATE**: This issue is already covered in [this issue](https://github.com/dgraph-io/dgraph/issues/8179).  Just refer there.

**Comment by jdgamble555** [comment]
@MichelDiz - You can close this, as my other github posts covers it.

**Comment by rderbier** [comment]
covered in https://github.com/dgraph-io/dgraph/issues/8179
