### ISSUE TITLE
Feature Request - Fuzzy Full Text Search (tf-idf scoring)

### ISSUE THREAD

**Issue by jdgamble555** [dgraph-io/dgraph#8177]
https://github.com/dgraph-io/dgraph/issues/3211#issuecomment-505932373

https://discuss.dgraph.io/t/fuzzy-full-text-search/16224

DGraph will need a way to do Fuzzy Full Text searching.  Currently, this only works on words with levenshtein distance algorithm, but not full-text fuzzy search capabilities.

J

**Comment by MichelDiz** [comment]
As this is a duplicated of #3211 we should decide which one to keep.

Or is this a different animal @jdgamble555 ? how so?

Thanks!

**Comment by jdgamble555** [comment]
You can delete this one.

**Comment by MichelDiz** [comment]
You mentioned there that is different, right? a complementation? I am not able to analyze details.
If this is an improvement with other characteristics, certainly to be added later. So this issue can continue. Just need to differentiate precisely.

**Comment by jdgamble555** [comment]
Well, it is basically the same thing.  I really don't care what algorithm it uses, as long as fuzzy search "phrases" would be possible and optimized for speed like algolia, elastic search, redis search etc.

J
