### ISSUE TITLE
Feature Request - Multiple and Single Primary and Unique Keys

### ISSUE THREAD

**Issue by jdgamble555** [dgraph-io/dgraph#8179]
Related to [this issue](https://github.com/dgraph-io/dgraph/issues/8176) for reference.

# Keys
**Composite Key** - has more than one attribute
**Compound Key** - a specific composite key where both attributes are also foreign keys

## [PK (Primary Key)](https://www.w3schools.com/sql/sql_primarykey.asp)

- _Right now, we can do this:_

### Single PK or @id (external id)
```graphql
type User {
  username: String! @id
  name: String!
}
```
### SQL
```sql
ADD PRIMARY KEY(username)
```
___
### Composite PK or @id
```graphql
type User {
  username: String! @id
  email: String! @id
}
```
### SQL
```sql
ADD PRIMARY KEY(username, email)
```
___
## [Unique Keys (Unique)](https://www.w3schools.com/sql/sql_unique.asp)

- **What we need to be able to do:**

### Single Unique or @unique
```graphql
type User {
  id: ID! @id
  username: String! @unique
  name: String!
}
```
### SQL
```sql
ADD CONSTRAINT UNIQUE (username)
```
___
### Multiple Uniques or @unique
```graphql
type User {
  id: ID! @id
  username: String! @unique
  email: String! @unique
}
```
### SQL
```sql
ADD CONSTRAINT UNIQUE (username)
ADD CONSTRAINT UNIQUE (email)
```
___
### Composite Uniques or @unique
```graphql
type User @unique(fields: ["firstName", "lastName"]) {
  email: String!
  firstName: String!
  lastName: String!
  ...
}
```
### SQL
```sql
ADD CONSTRAINT UNIQUE (firstName, lastName)
```
## Compound Keys - composite keys on foreign keys or nested fields
```graphql
type Book {
  id: ID!
  name: String!
  ...
}
type User {
  id: ID!
  name: String!
  reviews: [Review]!
  ...
}
type Review @unique(fields: ["reviewer.id", "book.id"]) {
  reviewer: User!
  book: Book!
  createdAt: DateTime!
}
```
### SQL
In SQL, there would be a composite pk on the junction table [book_id_fk, user_id_fk, created_at]:
```sql
ADD PRIMARY KEY(book_id_fk, user_id_fk)
```
So theoretically, there should be a unique key on reviewer.id and book.id.  This should also be possible for one foreign key, although I can't think of an example.
___

**UPDATE:** 11/2/22 - The @unique (not the @id) should be able to be null.  
```graphql
type User {
  id: ID! @id
  username: String @unique  // no ! in input
  email: String! @unique
}
```

Referring to [this post](https://github.com/dgraph-io/dgraph/issues/8117), you should also be able to get multiple fields based on their **COMPOSITE** primary or unique key(s) as well as [individual unique keys](https://dgraph.io/docs/graphql/schema/ids/), which is how it currently works:

```graphql
query {
  getUser(username: 'jdgamble555', email: 'someone@something.com') {
    username
    ...
  }
}
```

So we really have a few feature requests here:
1. Possibly rename @id to @unique
2. Allow top level @unique directive for multiple "composite" unique constraints
3. Allow "composite" unique constraints on nested fields (only one level), same as junction table
4. Make sure you can search with "get" for the composite fields
5. Allow nullable unique, as "no value" should not break the constraint

#2 is the main request here
___
- The GraphQL schema should fail if someone tries to add this directive on a field where there are "non unique" values.
- Some of this should be build on the [DQL level up](https://github.com/dgraph-io/dgraph/issues/8408), which is a different feature request. This should be implemented first.

J
___

Just for more reference - https://github.com/outcaste-io/issues/issues/26

**Comment by goluckycoding** [comment]
adding composite keys in mutation without query(like upsert) may be a good idea
