### ISSUE TITLE
[FEATURE]: Yell logs to a subscription query. [GraphQL]

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#8306]
### Have you tried Dgraph before this proposal? and did not find anything similar?

Yes

### What you wanted to do.

Access important logs easily.

### What you actually did.

I need to access via terminal, then ssh, then docker exec and finally I can gather some logs.

### Why wasn't it great, with examples.

In Dgraph there is the possibility to request extra logs such as knowing which query was executed X hour and Y minute. However, sometimes other logs are huge and I need to use tools like grep to reduce them. But it's not perfect.

>I1201 13:06:26.686466   10905 server.go:908] Got a query: query:"{\n  query(func: allofterms(name@en, \"Marc Caro\")) {\n  uid\n  name@en\n  director.film\n  }\n}"  

I would like to get logs like the one above via GraphQL subscriptions. With this we could create a log field in Ratel to be able to follow new events live.

It would be nice to also have a log of GraphQL queries executed in the application's GraphQL service (not Admin one). See https://github.com/dgraph-io/dgraph/issues/8305

### Additional information.

See https://dgraph.io/docs/deploy/log-format/#request-logging

This issue complements the https://github.com/dgraph-io/dgraph/issues/8299 for deeper debugging.

**Comment by damonfeldman** [comment]
I think seeing various logs (query logs, system logs) is important, but we should think about existing tools and customers' likely preferred tool chains, such as grafana/loki, splunk, cloudwatch, etc.

A different question is how users can see logs from a hosted solution (assuming that is secure and can be turned off for shared instances) or forward those to their own log tools.

We should clarify exactly which problem we want to solve. Logging all queries is definitely a good thing.
