### ISSUE TITLE
[BUG]: Enum values are not case senstive checked on insert

### ISSUE THREAD

**Issue by jrobber** [dgraph-io/dgraph#8328]
### What version of Dgraph are you using?

Cloud.  v21.03.0-92-g0c9f60156

### Tell us a little more about your go-environment?

Cloud

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

Cloud

### What steps will reproduce the bug?

Create a type.
Create an enum where the values are all uppercase letters
Add a field using the enum as it's type

Insert into the enum field, but pass in a PascalCase value for the enum.

### Expected behavior and actual result.

The insert is accepted.

### Additional information

Queries will fail if you have any values being retrieved that are not the right case.

This is a basic constraint that isn't checked right and is VERY dangerous for production.

**Comment by MichelDiz** [comment]
Hi, are you talking about GraphQL?

**Comment by jrobber** [comment]
Yes, Graphql.

Example schema:
```
enum ContactStatus {
    ACTIVE
}
```
+
```
type Contact {
  id: ID!
  status: ContactStatus! @search
}
`````


Then insert a contact with a status of Active.  It succeeds.

Then query contacts, and if your query tries to return the record you inserted the entire query will fail and instead of omitting the invalid row, you can get nothing.

**Comment by rderbier** [comment]
"insert a contact" : do you mean using the generated  graphQL API addContact  or using DQL.

GraphQL API seems correctly protected and does not allow the setting of "Active". in DQL I can set the predicate value to any string. Then I get 
```
{
  "errors": [
    {
      "message": "Error coercing value '\"Active\"' for field 'status' to type ContactStatus.",
```
Is that the behavior you see  ?

**Comment by rderbier** [comment]
tested on current cloud and on v22.0.0
It appears that GraphQL API is checking the constraint when using the addContact API.
However one can set the predicate value in DQL to whatever string value.
The GraphQL Query to search Contacts does not fail, it returns the valid data and a list of errors for each value which could not be coerced in the enum value.
-> need to decide what we want to do here - introduce enum type in DQL, expose a mechanism to optionaly prevent DQL mutations on predicated generated by GraphQL, just publish a best practice on DQL and GraphQL interoperability and risks. ...
