### ISSUE TITLE
[BUG]: Build failure on M1

### ISSUE THREAD

**Issue by skbly7** [dgraph-io/dgraph#8346]
### What version of Dgraph are you using?

master @ a80c6437

### Tell us a little more about your go-environment?

❯ go version
go version go1.16 darwin/arm64

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

Apple M1

### What steps will reproduce the bug?

```
#❯ make install
#❯ /Users/skbly7/go/bin/linux_amd64/dgraph
zsh: exec format error: /Users/skbly7/go/bin/linux_amd64/dgraph
```

### Expected behavior and actual result.

```
#❯ /Users/skbly7/go/bin/darwin_amd64/dgraph
Dgraph is a horizontally scalable and distributed graph database,
providing ACID transactions, consistent replication and linearizable reads.
It's built from the ground up to perform for a rich set of queries. Being a native
graph database, it tightly controls how the data is arranged on disk to optimize
for query performance and throughput, reducing disk seeks and network calls in a
cluster.
Dgraph version   : v22.0.0-RC1-20221003-1-gfa7033eee
Dgraph codename  : rocket-2
Dgraph SHA-256   : ea384f89350038d1d1b243983ab930d85df189888407ae305a0c23177a0d0ae8
Commit SHA-1     : fa7033eee
Commit timestamp : 2022-10-04 10:59:20 +0530
Branch           : main
Go version       : go1.19.1
jemalloc enabled : false

```

### Additional information

It looks like `GOOS=linux GOARCH=amd64` is hardcoded in `Makefile` since #8304.
Due to this the build process isn't respecting the underlying hardware which is `darwin`.

**Comment by MichelDiz** [comment]
Darwin(and in particular M1) is not supported. It could happen in the future.

Use Docker.

**Comment by skrdgraph** [comment]
@skbly7 the current supported architecture is `amd64`, and we are working towards `arm64`. For the time being we have been using https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment. There are some issues with underlying `xgo` (which we plan to figure out soon).

Our blessed way of running `dgraph` locally today is through `docker` on an `amd64` architecture. You could use Rosetta, and have this setup right. 

@joshua-goldstein can give you the steps for you to try.

**Comment by akon-dey** [comment]
@skbly7 development will continue on the main branch, not master going forward. Please use the main branch to submit pull requests if you or anyone happens to work on this. Please keep us informed so that we can help you.

**Comment by skbly7** [comment]
> Our blessed way of running `dgraph` locally today is through `docker` on an `amd64` architecture. You could use Rosetta, and have this setup right.

Thanks, I was able to run everything using docker. 👍

**Comment by matthewmcneely** [comment]
@skbly7 Note, `make install` now works as expected on the main branch.

**Comment by akon-dey** [comment]
Thank you @matthewmcneely. @skbly7 could you please verify and close the issue or put your findings in the notes.

**Comment by skbly7** [comment]
Thank you for the update. 🙌 
It is getting installed properly on my side. 

```
❯ make install
Installing Dgraph...
Commit SHA256: bc5f584c29b92d64adae0ffb7f14dc64873a0a13
Installed dgraph to /Users/skbly7/go/bin/dgraph
```
