### ISSUE TITLE
[Request]: Please make new release candidates available as standalone docker images

### ISSUE THREAD

**Issue by benwoodward** [dgraph-io/dgraph#8349]
I'd like to be able to test out release candidates using Docker standalone images.

Would be great if new RC builds were pushed to docker as images.

**Comment by skrdgraph** [comment]
@benwoodward that's a great feedback. I will see what we can do here.

For the time being, I would suggest you to follow these steps: https://github.com/dgraph-io/dgraph/tree/main/contrib/local-test#local-test

I will keep this issue open, and reference the docker images* when I have it ready.

**Comment by skrdgraph** [comment]
@benwoodward we are now doing this as part of our CD steps, and the release artifacts for RC/Beta are made available now. I am a little late to respond to this issue, but this process was setup a while ago.

The docker images for standalone are also made available as part of this and can be found here https://hub.docker.com/r/dgraph/standalone/tags
