### ISSUE TITLE
[BUG]: ReadTs less than minTs

### ISSUE THREAD

**Issue by RJKeevil** [dgraph-io/dgraph#8354]
### What version of Dgraph are you using?

22.0.0 RC

Dgraph version   : v21.03.2-111-ga80c64376
Dgraph codename  : rocket-2
Dgraph SHA-256   : 5897373a5d01974321a18deeac07f21280f49e97995986e574722390481a81cc
Commit SHA-1     : a80c64376
Commit timestamp : 2022-10-03 16:49:16 +0000
Branch           : main
Go version       : go1.18.3
jemalloc enabled : false

### Tell us a little more about your go-environment?

go version go1.19 linux/amd64

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

32G, Ryzen 3900x, wsl (Debian Bullseye)

### What steps will reproduce the bug?

Our entity resolution product issues many concurrent read and write requests to dgraph as it ingests data, returns candidate entities from dgraph, runs the data through a set of models, and updates the graph with the results.  Moving to the 22.0.0 RC from 21.12.0 has mostly gone well (ran with no code changes, similar performance), but we see a lot of failed transactions in the logs, such as the following:

rpc error: code = Unknown desc = : cannot retrieve UIDs from list with key 00000000000000000000185265736f6c766564456e746974792e6d657267655769746800000000000002ae85: readTs: 2625 less than minTs: 2626 for key: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x18ResolvedEntity.mergeWith\x00\x00\x00\x00\x00\x00\x02\xae\x85"

rpc error: code = Unknown desc = cannot retrieve posting for UID 18446744073709551615 from list with key 0000000000000000000021496e646976696475616c5265736f6c766564456e746974792e75706461746554530000000000000034a6: readTs: 76996 less than minTs: 76997 for key: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00!IndividualResolvedEntity.updateTS\x00\x00\x00\x00\x00\x00\x004\xa6"

These were not present in 21.12.0, but i do recall them occuring in 21.03 also.  I think the fix for this issue may need to be backported from 21.12.0

### Expected behavior and actual result.

Process runs without failed/retried transactions

### Additional information

Issue occurs on a small build set to only 6 threads in our product, but happeens increasingly often as the thread count increases, so this issue would dramatically limit our scalability in production volumes

**Comment by akon-dey** [comment]
@RJKeevil This issue seems to be the same as (or related to) https://github.com/dgraph-io/dgraph/issues/5105
It looks like the workaround is to handle the exception in the short term. See: https://github.com/dgraph-io/dgraph/issues/5105#issuecomment-638695502

Please try the workaround and in the meantime we will work on a fix for it.

**Comment by RJKeevil** [comment]
Thanks @akon-dey and @matthewmcneely , yes I am aware this was an old issue from 21.03 era.  I'm mostly flagging to give the context that this was fixed in 21.12, so this is now essentially a regression in 22.00.  We have exponential back off in our platform so are already using the workaround, and our regression tests do pass.  It is still reasonably high priority to fix for us as this has a performance cost, which increases as the number of threads increases, thus limitting scalability.

**Comment by RJKeevil** [comment]
Also worth mentioning is despite all the performance work that went into 21.12, for our workload 22.00 is actually slightly faster than 21.12.  This is a very pleasant suprise for us!

**Comment by RJKeevil** [comment]
To follow up, performance testing on a 32 core machine makes this occur much more frequently, and we then see 22.0.0 to be much slower than 21.12.0.  Hopefully solving this timestamp issue restores the performance, allowing us to migrate to 22.0.0

**Comment by anurags92** [comment]
@RJKeevil Would you be able to give a sample data and workload (in forms of query+mutations) to reproduce this?

**Comment by RJKeevil** [comment]
Hi @anurags92, it is quite challenging to provide a dataset for this. We are streaming into dgraph, running many queries and mutations on multiple concurrent threads.  I could dump out the jquery/mutate jsons to file, but you would need to replay them in the right sequence with the correct collisions to get the same issue.  I'm really keen to help you get to the bottom of this, perhaps we can arrange a session where I can show the issue first hand and to discuss how to tackle it?

**Comment by RJKeevil** [comment]
@MichelDiz @anurags92 Any update on this?  For us this means that dgraph 22.0.0 is currentlya no go because it doesnt scale beyond smaller test installations.  This means we are effectively tied to a now unsupported release due to this regression.

**Comment by matthewmcneely** [comment]
@RJKeevil I'd like to be able to set up a reproducible environment for this and/or use the benchmarking suite to recreate.  Can you provide a bit more detail?

1. Are you running this via dgo? If so, is it /dgo/v210?
2. You said "issues many concurrent read and write requests". Can you give me a sense of the number and size of both types of requests?

**Comment by RJKeevil** [comment]
Hi Matthew, yes we are using dgo (github.com/dgraph-io/dgo/v210 v210.0.0-20220113041351-ba0e5dfc4c3e).  Our engine works in the following way: 

We have a configurable number of workers (e.g. 6 for a small test instance, 32+ for a typical project will hundreds of mllions of input records).  Each worker constantly runs the following loop, operating as quickly as dgraph can handle the requests:
- loads a batch of records into memory (a ~10 list of input jsons, each with ~20 related nodes, with ~20 predicates stored on each of these these nodes), typically around 200kb of data per batch.
- inserts these "raw" nodes into dgraph in a single setJson transaction
- queries dgraph with ~1000 search and/or traversal queries in one transaction, to find nodes that are similar to those just inserted.
- runs a set of ML models to decide which matches are of high enough confidence to be considered the same
- creates or updates summary nodes that group the related nodes together, including a unique set of all their predicates.  This is also done as a single setJson transaction.

This loop usually takes ~0.5 seconds per worker, so on a 6 worker test instance this entire loop happens ~12 times per second, resulting in 24 large set transactions and 12 get transactions per second.  Simultaneous updates to the same summary node are common, so predicates are designed to be idempotent and are defined with noconflict in the schema to prevent thousands of conflicting failed transactions.

Dgraph is sized according to the size of a client's input data.  This issue occurs in all dgraph setups we try, so a single zero and alpha with 12+ cores and 16G+ ram should be sufficient to replicate the issue.  Larger sizes with more workers hit the issue more regularly, resulting in a bigger performance hit due to the retries.

I think in esscence we are doing something very similar to the live loader, with the added complexity of the query stage in between the writes.

Let me know if you need more info and thanks for looking into it.

**Comment by matthewmcneely** [comment]
I read in your initial report that you're running this under WSL. Is that the case? I've seen numerous discussions regarding poor disk I/O performance under WSL, for instance this: https://www.phoronix.com/review/windows10-okt-wsl/2

Dgraph is, to some extent, written with the idea that disk I/O will be better than average.

If you are on WSL, and you'd like to try running under native Linux, I'd be happy to help you attempt to run it that way.

One last request, can you reply with your dgraph deployment configuration details (group count, --limit flags, etc)?

**Comment by RJKeevil** [comment]
Hi Matthew, I only run in wsl2 during dev, this issue occurs on all our environments including large cloud VMs, with Azure premiumssdV2 mounts (8000 iops 500mbps).  This issue was often flagged previously by other users in the v21.03 era so I'm pretty sure it's not down to my environment, it occurs for dgraph users that really push large and concurrent workloads I think.  Even if it were environmental, it doesn't occur in 21.12 with the exact same config. I'll send over a typical docker compose in a couple of hours when I'm back, thanks.

**Comment by RJKeevil** [comment]
Here is a simple docker compose for a single machine instance, that hits this issue on a test build.  For clients i would naturally tune the memory and cache settings, num alphas and zeros, and the numgoroutines parameter.  That doesnt help with the ReadTS issue however, so the simpler case is enough to replicate.
`version: "3.9"
services:
  zero1:
    image: dgraph/dgraph:v22.0.0
    container_name: zero1
    volumes:
      - zero1:/dgraph
    ports:
      - "5080:5080"
      - "6080:6080"
    restart: on-failure
    command: dgraph zero --my=zero1:5080 --replicas 1 --telemetry sentry=false
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "512M"
  alpha1:
    image: dgraph/dgraph:v22.0.0
    container_name: alpha1
    volumes:
      - alpha1:/dgraph
    ports:
      - "8081:8081"
      - "9081:9081"
    restart: on-failure
    command: dgraph alpha --my=alpha1:7081 --zero=zero1:5080 --security whitelist=0.0.0.0/0 --limit mutations=strict --badger "numgoroutines=24" --cache "size-mb=3072;percentage=40,40,20;" --trace ratio=0.0000001 --telemetry sentry=false -o=1
    deploy:
      resources:
        limits:
          cpus: "24"
          memory: "16G"
#  alpha2:
#    image: dgraph/dgraph:v22.0.0
#    container_name: alpha2
#    volumes:
#      - alpha2:/dgraph
#    ports:
#      - "8082:8082"
#      - "9082:9082"
#    restart: on-failure
#    command: dgraph alpha --my=alpha2:7082 --zero=zero1:5080 --security whitelist=0.0.0.0/0 --limit mutations=strict --badger "numgoroutines=24" --cache "size-mb=3072;percentage=40,40,20;" --trace ratio=0.0000001 --telemetry sentry=false -o=2
#    deploy:
#      resources:
#        limits:
#          cpus: "24"
#          memory: "16G"

volumes:
  zero1:
  alpha1:
#  alpha2:`

**Comment by RJKeevil** [comment]
As an update, in our code I have implemented silent retries for errors containing "cannot retrieve posting for UID" or "cannot retrieve UIDs from list with key".  So far benchmarks are showing a 20% hit to performance with this workaround vs 21.12,  preventing us from releasing 22.0.0 into our production branch for clients.  Due to how often this occurs it its difficult to say whether this bug explains the full slowdown in the new release, or if  the revert of 21.12 is removing optimisations that helped our workload.

**Comment by matthewmcneely** [comment]
> or if the revert of 21.12 is removing optimisations that helped our workload

It is most likely this. v22.0 was basically v21.03 with some functional bug fixes and CREs. The implementation of serialized roaring bitmaps [SROAR](https://dgraph.io/blog/post/serialized-roaring-bitmaps-golang/) in v21.12 increased performance without question. But as many have noted in the forums, the release had stability issues and the (new) team chose to revert to the v21.03 branch until it gains the requisite expertise to identify and address the issues.

**Comment by RJKeevil** [comment]
@matthewmcneely thanks for the response, yes I fully understand the decision to revert and think it was probably the right choice in the circumstances.  We could probably take the performance hit for the sake of better stability and being on a supported version.

But then I would really love to see this readTS issue solved as it is causing an even greater performance hit due to the constant retries, plus the log spam in the alpha logs from this issue is really horrible, hiding any real issues that do occur. Maybe a quick win is just to detect this scenario on the Dgraph side and silently retry the transaction once if the readTs error is logged?  It fits the story that it is expected behaviour now, so it would be strange for expected behaviour to be flooding logs with errors, and requiring special logic client side.

I know I am the only client really pushing this one, but given it has also been flagged in the past I dont think that we are doing anything too unusual.  I think it is purely because a) we do not use the Live/Bulk loaders (because our inserts depend on the results of previous inserts), and b) we have a highly concurrent, high throughput usage pattern.
