### ISSUE TITLE
[BUG]: Deployment with dgraph-single on Kubernetes is broken

### ISSUE THREAD

**Issue by andylibrian** [dgraph-io/dgraph#8386]
### What version of Dgraph are you using?

Latest

### Tell us a little more about your go-environment?

Not relevant

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

Not relevant

### What steps will reproduce the bug?

1. Follow the instruction here: https://dgraph.io/docs/deploy/kubernetes/#deploy-single-server
2. Run

    ```
    kubectl create --filename https://raw.githubusercontent.com/dgraph-io/dgraph/main/contrib/config/kubernetes/dgraph-single/dgraph-single.yaml
    ```
 
 3. See the error: `kubectl get pods`

     ```
    $ kubectl get pods 
    NAME       READY   STATUS             RESTARTS     AGE
    dgraph-0   2/3     CrashLoopBackOff   1 (6s ago)   39s
    ```

### Expected behavior and actual result.

Expected behavior: The pod should be running.
Actual result: CrashLoopBackOff

```
  Normal   Created    13s (x2 over 14s)  kubelet            Created container ratel
  Warning  Failed     13s (x2 over 14s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "dgraph-ratel": executable file not found in $PATH: unknown
  Normal   Pulled     13s                kubelet            Container image "dgraph/dgraph:latest" already present on machine
  Warning  BackOff    11s (x2 over 12s)  kubelet            Back-off restarting failed container

```

The problem seems to be that dgraph-ratel is not found. It's not included in `dgraph/dgraph:latest` image. Instead, it should probably use `dgraph/ratel` instead.

### Additional information

If you agree that this should be fixed, I'm interested to open a PR. If this is not the appropriate place to report this, please let me know the correct one.

**Comment by skrdgraph** [comment]
@andylibrian thanks for reporting this issue. 

as a part of our current release we have focused on Dgraph-binary & related Docker images. We intend to streamline and extend this to K8S support. The existing methods where you have faced this issue will change a little. We will make sure to reference and fix this up correctly.

**Comment by MichelDiz** [comment]
@andylibrian To let you know, we've made a temporary change that address your specific case. We will soon change how these examples are presented to the community. Please note that these examples are not 100% secure and your team should take due care in security and related matters.
