### ISSUE TITLE
gRPC and large messages

### ISSUE THREAD

**Issue by kjnsn** [dgraph-io/dgraph#839]
Currently receiving this error while loading data into dgraph using the go client:

`rpc error: code = Internal desc = grpc: received message length 5277856 exceeding the max size 4194304`

This is while trying to load over 17 million nquads using both the batch system and the plain req/run.

**Comment by manishrjain** [comment]
Sounds like a gRPC problem, not specific to Dgraph. The Dgraph client already does incremental batching, so it doesn't exceed this size.

**Comment by manishrjain** [comment]
Sorry, just read that you were using the go client's batching system. Can you please provide steps to reproduce this?

**Comment by pawanrawal** [comment]
The server now can accept requests with size upto 256MB so this shouldn't be an issue anymore.
