### ISSUE TITLE
[FEATURE]: Unique Constraint in DQL

### ISSUE THREAD

**Issue by jdgamble555** [dgraph-io/dgraph#8408]
### What you wanted to do.

From the DQL level up, there should be a way to force uniqueness.  For backwards compatibility this should be easy.  Adding this to a node that already has duplicate values would not be allowed.

This simplest way todo this would be to have a @unique directive in the [dql schema](https://dgraph.io/docs/query-language/schema/):

```graphql
type Film {
  name @unique 
  release_date
  revenue
  running_time
  starring
  director
}
```
or with a composite index:
```graphql
type Film @unique(name, release_date)  {
  name
  release_date
  revenue
  running_time
  starring
  director
}
```
___

This should also be possible on a 'facet', but there would need to be a way to declare facet types in dql.  Perhaps:
```graphql
facet Friend {
  close @unique
  ...
```
and for composite:
```graphql
facet Friend @unique(close, date) {
  close
  date
}
```
**Note:** In GraphQL, the unique directive would need the "field" input to be not break the GraphQL spec, here we can simplify it with just an array inside ().

### What you actually did.

You can create this in GraphQL, but it is not enforced once added, and DQL is certainly not enforced.  Composite indexes are also currently impossible.

### Why wasn't it great, with examples.

We need better data integrity.

### Additional information.

It should be 100% impossible to add any kind of duplicate data once this unique directive is activated.

Unique constraints should be **nullable** by default, but could be not null with the @notnull directive.

This is how @akon-dey wants to implement this.  First in DQL, then GraphQL.

**Related to:**
- [GraphQL Composite Uniques](https://github.com/dgraph-io/dgraph/issues/8179)
- [DQL Non Null Constraints](https://github.com/dgraph-io/dgraph/issues/8409)
- [Check Constraints](https://github.com/dgraph-io/dgraph/issues/8410)

**Comment by rderbier** [comment]
partially addressed in JIRA https://dgraph.atlassian.net/browse/DGRAPHCORE-206 sprint 5

**Comment by rderbier** [comment]
replaced by https://github.com/dgraph-io/dgraph/issues/8865 which is linked to the JIRA covering this new feature
