### ISSUE TITLE
[QUESTION]: Where are the windows binaries ?

### ISSUE THREAD

**Issue by HijackHornet** [dgraph-io/dgraph#8414]
### Question.

This might be a feature request, but i cant find the windows binaries nor the documentation regarding building for windows. Why is that so ? I'm not to thrilled about running a docker container just for the sake of not building plateform specific binaries.

Thanks

**Comment by damonfeldman** [comment]
I think this is a good feature request, but for immediate help, can you post your question to discuss.dgraph.io where the community may have a recommendation?

**Comment by matthewmcneely** [comment]
@HijackHornet Also, please see this: https://github.com/dgraph-io/dgraph#supported-platforms

**Comment by akon-dey** [comment]
@HijackHornet we would be happy to provide you with know-how to get you started if you are interested in helping us to support Windows. As @matthewmcneely mentioned, we don't have immediate plans to have a Windows build.

**Comment by HijackHornet** [comment]
Hi,
Yeah from my understanding, some of the dependencies of dgraph are not available on windows. It was apparently decided to drop windows support because you really wanted to use that lib.
I'll close this ticket. But fyi i ended up not using dgraph by lack of binaries and because i dont want to run a docker just for my db instance.

**Comment by MichelDiz** [comment]
@HijackHornet if you wanna use Dgraph on Windows you can build it. It will work fine, but you won't have some RAM fixes that have been solve using jemalloc and others(there was file system issues too). But this binary will run with a limited manner. It is useful for small tests and studying.

Steps:

1. Install Go
2. Clone the repo (install all packages)
3. go to the path `dgraph/dgraph` and run  `go build .`
4. Now you can run  `.\\dgraph.exe zero` and `.\\dgraph.exe alpha` - Dgraph run via terminal only.

Pay attention that some issues may appear cuz we are not addressing the old issues that we had with windows in the main branch for a long time.

**Comment by HijackHornet** [comment]
Thanks
I tried building the binaries but i dont think the build command work anymore. If i was to reconsider dgraph i'll try again. Thanks

**Comment by MichelDiz** [comment]
It works, I use Windows daily. I did exactly what I showed above and it built normally.
