### ISSUE TITLE
Database corruption on exit

### ISSUE THREAD

**Issue by kjnsn** [dgraph-io/dgraph#842]
When killing dgraph with C-c, I often get the following errors when starting it up again:

`Error initializing postings store error: Corruption: Sst file size mismatch: p/001382.sst. Size recorded in manifest 67209297, actual size 67211264`

**Comment by manishrjain** [comment]
Hmm.. I've never seen that before. This looks like a corruption at RocksDB level; which is pretty stable -- so I'd guess that this has to do with some issue at your end.

Maybe clean up the directory and retry -- see if you still see these issues.

**Comment by tzdybal** [comment]
I had the same issue today, after loading `goldendata.rdf.gz` and using `Ctrl+C`.

**Comment by manishrjain** [comment]
If you guys can reproduce this, please feel free to reopen this issue.
