### ISSUE TITLE
[FEATURE]: GraphQL @id uniqueness at interface level

### ISSUE THREAD

**Issue by rderbier** [dgraph-io/dgraph#8434]
### What you wanted to do.

In v22.0, @id fields in the interface are unique only in one implementing type. 
But there are several use cases that require @id field to be unique across all the implementation types. 
Also currently. get a query on the interface can result in unexpected errors as we can have multiple implementing types have the same value for that @id field.

PR merged in v21.13 to be picked in v22.x.y

See details at  https://github.com/dgraph-io/dgraph/pull/7710

**Comment by skrdgraph** [comment]
> PR merged in v21.13 to be picked in v22.x.y

guessing you mean `22.12`?

**Comment by xnoreq** [comment]
Having the same issue. This is blocking us from upgrading from v21 to v22.

**Comment by mangalaman93** [comment]
Fixed in #8876
