### ISSUE TITLE
Need Way To Store Raw Byte Blobs, Backup, and Restore Them

### ISSUE THREAD

**Issue by willcj33** [dgraph-io/dgraph#844]
I have a custom proto (call it Date Of Birth) that I want to store directly to dgraph without unmarshaling because I dont care to know what the value is until I get it back. When I do get it back, I just want it in the SAME []byte format that it was before. Currently I am storing it like so:

```
 value := string(payload[:]) 
```

 The issue with this is, if I want to do a restore (from a dgraph backup) it fails because it cannot read the RDF file due to special characters in the string. 

he output to the rdf file looks like so:

```
 <0x4d0c4a5c4b53350c> <dob> "
37 years oldÄÊµíÄÕ∫°"^^<xs:string> . 
```

There should probably be a way (at least through the Golang client) to be able to safely store these []byte payloads, back them up, and restore them.

**Comment by tzdybal** [comment]
Ascii85 or Z85 encoding may be used.

**Comment by manishrjain** [comment]
Go client needs to support this. I doubt this can be supported via the http endpoint.

**Comment by manishrjain** [comment]
@pawanrawal : Can you add an API in the Go client?

**Comment by pawanrawal** [comment]
Added support for this to master.
