### ISSUE TITLE
[Documentation]: The undefined behavior when using value variable in a wrong context

### ISSUE THREAD

**Issue by garylavayou** [dgraph-io/dgraph#8459]
### What version of Dgraph is the target?

latest (`v22.0.1`).

### Documentation.

What is the behavior when using **value variable** `val(var_name)` in a wrong context is not clearly described in the [document](https://dgraph.io/docs/query-language/value-variables/).

### Additional information.

I have followed the [Dgraph DQL tour](https://dgraph.io/tour/blocksvars/11/#expand), and I created a query that is a little different from the tutorial's answer, as follows,
```go
{
  var(func: has(director.film))@cascade {
    director.film {
      film_date as initial_release_date
    }
    latest as max(val(film_date))
  }
    
  order_director(func: uid(latest), orderdesc: val(latest), first: 10 ) 
  @normalize {
    name: name@.
    latest_date: val(latest)  // right usage: latest date of the corresponding director
    s : director.film (orderdesc: initial_release_date, first: 1)
    @filter( eq(initial_release_date, val(latest))  )  // a: wrong usage of val(latest)
    { 
    	film_name: name@.
    	date: initial_release_date
      the_latest: val(latest)  // b: wrong usage of val(latest)
    }
  }
}
```
As I am not very familiar with DQL, so I have by mistake put the **value variable** `val(latest)` in wrong context, as `@filter( eq(initial_release_date, val(latest))  ) ` and `the_latest: val(latest)`. Though it is wrong, the filter still works and I still get the data for `film_name` and `date`, which like
```json
{
  "data": {
    "order_director": [
      {
        "date": "2017-12-01T00:00:00Z",
        "film_name": "Avatar 3",
        "latest_date": "2017-12-01T00:00:00Z",
        "name": "James Cameron"
      },
      {
        "date": "2017-07-06T00:00:00Z",
        "film_name": "Pirates of the Caribbean: Dead Men Tell No Tales",
        "latest_date": "2017-07-06T00:00:00Z",
        "name": "Joachim Rønning"
      }
  ]
}
```
The result of  `@filter( eq(initial_release_date, val(latest))  ) ` is undefined. But from the results, I can guess that all the dates in `latest` has been passed to `eq` function, which makes the equality satisfied (as I know, scalar can be compared to list with `eq` function, in terms of the include relationship, while list cannot be compared to a scalar). However, `val(latest)` inside the referred node `director.film` returns nothing since there is no such `the_latest` field in the response data.

So, it really confuses me, why the two wrong usages have different behavior. Though the document says we should use value variables in context with matched `uids`, some explanation might be added to the documents or the tour tutorial, so that a beginner can better avoid such wrong usages.

**Comment by MichelDiz** [comment]
Variables only work 1:1 with the level they were created at.
The variable takes a UID map with the value(like "KV"). The UID is from the level the variable belongs to. Cannot use this MAP to filter nested blocks/levels.

There really should be an error in the usage you mention. For example, if you use `@filter( uid(val(latest))` it will not return anything because the UID map is from the director and not from the movie.

**Comment by garylavayou** [comment]
> Variables only work 1:1 with the level they were created at. The variable takes a UID map with the value(like "KV"). The UID is from the level the variable belongs to. Cannot use this MAP to filter nested blocks/levels.
> 
> There really should be an error in the usage you mention. For example, if you use `@filter( uid(val(latest))` it will not return anything because the UID map is from the director and not from the movie.

Yes, issuing an error message in such cases would be fine for Dgraph novices. If not return an error, the behavior that `val(var_name)` return nothing should be consistent in all wrong context.
