### ISSUE TITLE
[FEATURE]: add @default directive to GraphQL schema

### ISSUE THREAD

**Issue by rderbier** [dgraph-io/dgraph#8463]
Allow user to set a default value on fields for add and update operation.
Allow use of $now to set current date time as default.
 
Was covered in v21.12 
https://github.com/dgraph-io/dgraph/pull/8017

default value provided as string.
$now replaced by current DateTime on the server.
See PR, investigate if we can add default value for enums.

**Comment by gregpavl** [comment]
is there any update on this feature?

**Comment by jimrazmus** [comment]
I am also interested in seeing the @default option added.
