### ISSUE TITLE
HTML output in graph window for bad query

### ISSUE THREAD

**Issue by kjnsn** [dgraph-io/dgraph#848]
To reproduce, run the following bad query on play.dgraph.io:
```
{
  
  
	actor(id: 0xcbcefccffb9eb400) {
    ~performance.actor {
    name@en
  }
  }
}```

**Comment by sungwoncho** [comment]
I could not reproduce using the given query. However I can confirm that this happens when server is down, resulting in `404` Not Found in the UI.

Next release will fix this issue.

**Comment by pawanrawal** [comment]
We are thinking of doing the release by Friday. @sungwoncho can this fix go in before that?

**Comment by sungwoncho** [comment]
@pawanrawal ok, let's aim for the release by this Friday.

**Comment by manishrjain** [comment]
Is this still a thing?

**Comment by manishrjain** [comment]
Closing this.
