### ISSUE TITLE
[FEATURE]: Add Zero API to bulk load tablets

### ISSUE THREAD

**Issue by rderbier** [dgraph-io/dgraph#8480]
See https://github.com/dgraph-io/dgraph/pull/8088
 bulk API for zero so that alpha can inform about the predicates in a single go during the restart. This was needed for use cases where clients have 151k predicates and during the bulk loader zero was not started up. It was because alpha was sending the predicates one at a time and this turns into O(n^2) problem which never completes in a deterministic manner.

**Comment by MichelDiz** [comment]
This is already in Main.
