### ISSUE TITLE
[ENHANCEMENT]: clusterID flag added for alpha sentry reports (gql-services)

### ISSUE THREAD

**Issue by rderbier** [dgraph-io/dgraph#8484]
### What you wanted to do.

PR from v21.12 : https://github.com/dgraph-io/dgraph/pull/7580

**Comment by mangalaman93** [comment]
@MichelDiz could you check if this is useful? I don't think we are using sentry (we should though) and maybe this is useful for other reports that we get from various clusters?

**Comment by mangalaman93** [comment]
This is already present in main https://github.com/dgraph-io/dgraph/pull/7580 https://github.com/dgraph-io/dgraph/commit/eeab3fb21f831c36ecb917636c3aa0f117364d46

**Comment by MichelDiz** [comment]
@mangalaman93 in general it is not useful for telemetry. Can be for Sentry. About that I can't tell much.

We should verify and decide to remove. Cuz this can cause confusion in the telemetry data. As users can play with it. I've seen two cluster with funny names...
