### ISSUE TITLE
Support graphql variables in UI

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#849]
There doesn't appear to be a way to send graphql variables along with the query to the server using the UI.

It would be nice if this can be supported.

**Comment by MichelDiz** [comment]
I believe this is already supported for a long time.


To test go to https://play.dgraph.io/ and Run this Query.

```JS
query test($name: string = "/^Steven.*$/i") {
  directors(func: regexp(name@en, $name), first: 20) {
    name@en
  }
}
```

If not the expected, feel free to reopen.
