### ISSUE TITLE
Support include directive

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#850]
We should support `@include` directive.

```
{
  var shareids(eq(_share_hash_, "hash"))

  me(id: var(shareids)) { # gives you share ids.
    _share_  @include(if: gt(count(var(shareids)), 1))
  }
}

```

**Comment by MichelDiz** [comment]
This `@include` directive as an if statement is a very interesting feature we can use in Dgraph.
btw there's a "`@skip`" directive that does the opposite.

With GraphQL Variables (something very similar as standard use of GraphQL)
```YAML
curl localhost:8080/query -XPOST -H 'X-Dgraph-Vars: {"$a": "5", "$b": "10", "$name": "Steven Spielberg", "$director": true}' -d '
query test($a: int, $b: int, $name: string, $director: boolean) {
  me(func: allofterms(name@en, $name)) {
    name@en
    director.film @include(if: $director)  (first: $a, offset: $b) {
      name @en
      genre(first: $a) {
        name@en
      }
    }
  }
}' | python -m json.tool | less
```

The first example updated
```
{
 shareids as var(eq(_share_hash_, "hash"))

  me(func: uid(shareids)) { # gives you share ids.
       uid
    _share_  @include(if: gt(count(var(shareids)), 1)) {
       uid
       expand(_all_)
    }
  }
}
```


### Original GraphQL usage
```
query Hero($episode: Episode, $withFriends: Boolean!) {
  hero(episode: $episode) {
    name
    friends @include(if: $withFriends) {
      name
    }
  }
}
```
source https://graphql.org/learn/queries/

**Comment by campoy** [comment]
I've read this issue a couple of times and I still don't understand what this is about.

Could someone explain what's the goal of having `@include` and what's the difference with `@filter`?

How is this query: 

```
{
  var shareids(eq(_share_hash_, "hash"))

  me(id: var(shareids)) { # gives you share ids.
    _share_  @include(if: gt(count(var(shareids)), 1))
  }
}
```

different to this one?

```
{
  var shareids(eq(_share_hash_, "hash"))

  me(id: var(shareids)) { # gives you share ids.
    _share_  @filter(gt(count(var(shareids)), 1))
  }
}
```

**Comment by MichelDiz** [comment]
In the link https://graphql.org/learn/queries/#directives
there are docs about this directives `@include and @skip` it is based on a boolean value to skip or include a nested block. And in general, uses GraphQL variable to do it.

The first example of Manish is not exactly accurate with the specifications of these directives, but it is a mix of the Dgraph and GraphQL specifications. But it has the same meaning.

**Comment by campoy** [comment]
I'm not sure why we need this feature, since we already have `filter`

For instance, this will only `include` those movies whose movies include a given word:

```graphql
query search($name: string = "Steven Spielberg", $movie: string = "Jurassic"){
    user(func: eq(name@en, $name)) {
        director.film @filter(anyofterms(name@., $movie)) {
            name@.
        }
    }
}
```

We could indeed use `include` instead so the query would look like:

```graphql
query search($name: string = "Steven Spielberg", $movie: string = "Jurassic"){
    user(func: eq(name@en, $name)) {
        director.film @include(if: anyofterms(name@., $movie)) {
            name@.
        }
    }
}
```

But I do not see the benefit.

**Comment by MichelDiz** [comment]
@campoy in the GraphQL convention the "@include" and "@skip" are boolean directives. It is used more like a "templating" thing. And it uses the GraphQL Variables.

> GraphQL Variables are used to prevent unwanted data injection. And also slightly decrease the size of the query(sanity thing). Also, It is usually used in input mutations.

So, in GraphQL some nested blocks would be shown or not if the user passes the true/false value. the Skip and include are not related to functions or filters. But it's a "kind of filter" that helps reuse queries. Similar to Fragments. But Fragments adds things, while Skip and Include, places or drops parts of the query according to users logic.

In our case, for our lang, could be even beyond. Today we have some logic with Math functions https://docs.dgraph.io/query-language/#math-on-value-variables. But there's none logic (like if) to edges or query blocks. In math we have the operator "cond(a, b, c)" that is "first operand must be a boolean | selects b if a is true else c".

We can do some tricks with math's cond(), but only who already know `GraphQL+-` for some time. And it is very limited tho.

Although I am explaining this feature more precisely. It is not extremely necessary, but is widely used in the context of GraphQL. However, this feature has no priority or need/wish (as far as I can see) from the community. For me, it's very useful but I don't see new users using it.

**Comment by campoy** [comment]
I think we should not support this directive, since `@filter` provides an alternative.
Those wishing to use it, they can definitely use our GraphQL layer.

What do you think, @manishrjain ?

**Comment by MichelDiz** [comment]
I don't get if you followed what I meant. Maybe I'm not clear in explaining the feature.

This query.
```graphql
query search($name: string = "Steven Spielberg", $movie: string = "Jurassic"){
    user(func: eq(name@en, $name)) {
        director.film @filter(anyofterms(name@., $movie)) {
            name@.
        }
    }
}
```
Is a kind of "hacky way". And the right form would be `@filter(eq(name@., $movie))` cuz `anyofterms` would be related to a value filter and so it doesn't have the same effect. Of the mentioned directives.

Who would use the "skip", "include" directives, would be interested in add or not a nested block following a templating logic. It's not based on edges/predicates/nodes values. But what parts of a query I wanna show at that moment.

This kind of feature is good to decrease the number of repeated queries in the client.

**Comment by manishrjain** [comment]
This issue has been around for a while, but hasn't seen much enthusiasm from the community. So, perhaps, no need to build this. Once a clear use case comes from a user with a decent experience report, we can consider then.

**Comment by campoy** [comment]
Let's close this issue and reconsider later on.
Michel, let's schedule a chat if you want to discuss more on this.
