### ISSUE TITLE
[FEATURE]: Optimize use of type(T) as a filter to a root function

### ISSUE THREAD

**Issue by damonfeldman** [dgraph-io/dgraph#8502]
### Have you tried Dgraph before this proposal? and did not find anything similar?

None

### What you wanted to do.

Write a query block such as 

  target as var(func:eq(id,$target)) @filter(type(User))

and have it run fast

### What you actually did.

Needed to optimize by removing type(User). There are 4M users and just a little more than 4M nodes in this DB.

We replaced it with has(property-only-on-User-type) to check the same condition without using type().

Alternatively, ensuring User.id is unique across types would allow us to remove the @filter altogether.

### Why wasn't it great, with examples.

This ran much faster (< 1ms) optimized, so the server should do something similar automatically.

The profile of the code showed that handleUidPostings is calling Uids() in the default case, and Uids is using a lot of time expanding a slice (likely in an append() call). 

This should better use the UID to quickly find the right value, or even just look up the specific node type by accessing the dgraph.type::0x2343532 key. I think we may be in some index lookup code that is not working properly.

**Comment by damonfeldman** [comment]
[indykite-typeuser-cpu.out.gz](https://github.com/dgraph-io/dgraph/files/10200609/indykite-typeuser-cpu.out.gz)

**Comment by damonfeldman** [comment]
attached a pprof cpu file

**Comment by MichelDiz** [comment]
Alternative solution https://discuss.dgraph.io/t/rfc-proposal-for-change-in-type-system/17983

But we need to fix this cuz it may also be a problem with eq() functions.
