### ISSUE TITLE
Support a new hash tokenizer

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#851]
Most times we just want to check for string equality, nothing more. In that case, we can use a hash function tokenizer, instead of exact tokenizer. The benefit of hash tokenizer would be smaller and consistently sized keys. And we can also easily break collisions, by retrieving the values for the uids returned, and doing actual string matching.

**Comment by manishrjain** [comment]
We can use this for XIDs as well.

**Comment by pawanrawal** [comment]
This has been merged to master.
