### ISSUE TITLE
[ENHANCEMENT]: Add support for rdf response via http

### ISSUE THREAD

**Issue by rderbier** [dgraph-io/dgraph#8529]
### What you wanted to do.

v21.12 PR https://github.com/dgraph-io/dgraph/pull/8004

**Comment by matthewmcneely** [comment]
Confirmed PR #8004 is not in main. It's a simple one-file change at the http processing level. A test should be added tho (the original PR has no test)

**Comment by rderbier** [comment]
Note that getting RDF on queries is possible with the gRPC client : https://dgraph.io/docs/clients/go/#query-with-rdf-response
