### ISSUE TITLE
[ENHANCEMENT]: prevents DB to start up on old version of posting list (magic number)

### ISSUE THREAD

**Issue by rderbier** [dgraph-io/dgraph#8535]
### What you wanted to do.

v21.12 PR https://github.com/dgraph-io/dgraph/pull/8032

introduce a magic number to prevents DB to start up if the version is not compatible. Avoid corruption.

**Comment by mangalaman93** [comment]
I think we should have test for this that in case a customer starts the wrong version of Dgraph on a p directory, it shouldn't do bad things. If the tests conclude that we need a magic number, we can cherry-pick this PR. This one should be done soon.
