### ISSUE TITLE
[FEATURE]: a random function in DQL

### ISSUE THREAD

**Issue by rderbier** [dgraph-io/dgraph#8537]
### What you wanted to do.
Random nodes can be selected from the graph using random: <number of nodes>
v21.12 PR https://github.com/dgraph-io/dgraph/pull/7693

**Comment by iuriatan** [comment]
Is this feature deprecated or is it going to be included in v23?

**Comment by c-nv-s** [comment]
I am still looking for how to use the ``random`` function via graphql ?
#7693 is showing as merged but as I understand for whatever reason the functionality is not available in the latest version.
