### ISSUE TITLE
[FEATURE]: @groupby on scalar fields and count duplicate

### ISSUE THREAD

**Issue by rderbier** [dgraph-io/dgraph#8538]
### What you wanted to do.

v21.12 PR https://github.com/dgraph-io/dgraph/pull/7746

and 
https://github.com/dgraph-io/dgraph/issues/5412

**Comment by rderbier** [comment]
need SROAR update before this

**Comment by MichelDiz** [comment]
hey @rderbier isn't that issue a duplicate of #5412 ?
