### ISSUE TITLE
Root filters do not work with query variables

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#854]
Given this mutation:

```
mutation {
 set {
   _:o1 <type> "object-type" .
   _:o1 <app_id> "core/crm" . 
   _:o1 <key> "testkey" .
 }
}
```

This query returns nothing:

```graphql
query migrations($app: "core/crm"){
	objects(func:eq(type, "object-type")) @filter(eq(app_id, $app)) {
		_uid_
		key
	}
}
```

But this one returns something:

```graphql
query migrations($app: "core/crm"){
	objects(func:eq(type, "object-type"))  {
		_uid_
		app_id @filter(eq(app_id, $app))
		key
	}
}
```

**Comment by manishrjain** [comment]
I think the latter returns something, because `@filter` won't return anything. That filter would work on the children of app_id (in essence app_id of app_id = $app). So, basically, the filter isn't returning anything.

**Comment by ashwin95r** [comment]
This was due to the extra `"` in `"core/crm"`. It wasn't being trimmed and considered as part of the string. So there was no match. This was not related to GQL var at root. Fixed now.
