### ISSUE TITLE
Support multiple equality

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#855]
Use case: I want to find all nodes given that `key` is in a list of `key1, key2, key3`. This is similar to the following SQL: `SELECT * FROM something WHERE key IN('key1', 'key2', 'key3')`.

Currently, the solution is to use any of terms:

```graphql
query migrations($app: "%s", $objectKeys: "%s","){
	objects(func:eq(type, "object-type"))  @filter(eq(app_id, $app) AND anyofterms(key, $objectKeys)){
		_uid_
		key
	}
}
```

However, the terms index will break strings into terms using stopwords. Unfortunately, this means that if a key contains `-`, it will not be an exact match.

The solution is to use `eq`, but that requires a lot of query building on the client side and multiple query blocks, which can make the query pretty unreadable.

It would be nice if there is a function to support multiple equality, for example `in(key, "key-1", "key2", "key 3")`.

**Comment by manishrjain** [comment]
I think we should be able to support `eq(pred, ["key1", "key2", "key3"])`. @ashwin95r can weigh in.

**Comment by F21** [comment]
@manishrjain will that require a `list` type when using graphql variables: `eq(pred, $myListOfKeys)`?

**Comment by manishrjain** [comment]
Yes, I think so.

**Comment by manishrjain** [comment]
Internally we can convert these to ORs: `eq(pred, "key1) || eq(pred, "key2") || ..`

**Comment by pawanrawal** [comment]
This has been merged to master and would go in the next release.

**Comment by arpanbag001** [comment]
@pawanrawal Any update / how-to on this?
I am using Dgraph go client, just for your reference.
