### ISSUE TITLE
[FEATURE]: Better error logging for failed queries.

### ISSUE THREAD

**Issue by all-seeing-code** [dgraph-io/dgraph#8580]
### Have you tried Dgraph before this proposal? and did not find anything similar?

We tried various logging approaches to see queries and errors. The best we found is to enable both Request Logging and AUDIT logging, so that the query at the start and end of a query are both logged, which reflects the time taken, and a missing AUDIT indicates there was an error (we don't log an AUDIT if the event did not take place).

### What you wanted to do.

I want to see failed queries consistently at a lower log level (in particular the typical log level of 2). 

See latest logging in this PR: 
https://github.com/dgraph-io/dgraph/pull/8507/files#diff-a5ff13fe9a91d3c6cb2e50d49b59e58e40d23f65651adeaf14864a607c38e6afR1372

### What you actually did.

The latest v22.0.2 logging does show errors at v3 logging level, but we want to proactively see all errors. Often, in the cloud product, a customer gets some error, and it is important to see that error in the logs without having to increase logging to level 3.

### Why wasn't it great, with examples.

Even if the log level is lower (v 2) and Request Logging is off, we want to see the following when there is an error:
* error type and message
* time taken since query start
* the query text
* other data easily available and shown in request logging or auditing, such as user, namespace, etc.

### Additional information.
* Recommend the current logging check at level v3 be changed to v2, and start timestamp/duration added

_No response_

**Comment by damonfeldman** [comment]
From a Support perspective this is a P1 feature. 

It would be P0, but there is a partial workaround:

Workaround: of enable OpenCensus (Jaeger trace) information, which should include errors, durations and query text as of v22.0.2. OpenCensus data is sampled (often 1% of calls) so is not ideal, but will show recurring issues.
