### ISSUE TITLE
[FEATURE]: Allow log level to change without a restart

### ISSUE THREAD

**Issue by damonfeldman** [dgraph-io/dgraph#8591]
### Have you tried Dgraph before this proposal? and did not find anything similar?

None

### What you wanted to do.

Alter the log level with an admin mutation (as we do with request logging)

### What you actually did.

Had to modify the sts (k8s stateful set) config, which caused all nodes to restart, and in turn results in a short outage.

### Additional information.

May be useful to see how worker.go::UpdateLogRequest() handles this.

**Comment by MichelDiz** [comment]
Hummm, this is weird. The UpdateLogRequest state change happens in memory. I should immediately reflect.
