### ISSUE TITLE
gRPC vendoring issue

### ISSUE THREAD

**Issue by etix** [dgraph-io/dgraph#860]
Running the [go client example](https://docs.dgraph.io/v0.7.5/clients/#example) against the latest master does not build.

```
# command-line-arguments
./dgraph.go:25: cannot use conn (type *"google.golang.org/grpc".ClientConn) as type *"github.com/dgraph-io/dgraph/vendor/google.golang.org/grpc".ClientConn in argument to graphp.NewDgraphClient
```

**Comment by etix** [comment]
This is the same issue that was previously reported on the old dgraphgoclient repository: https://github.com/dgraph-io/dgraphgoclient/issues/10

**Comment by janardhan1993** [comment]
@etix: I think you are building go client outside dgraph repo right ?. This is a know issue.
The only solution would be to build it inside dgraph repo or delete the grpc vendored package.(vendor/google.golang.org/grpc)
https://discuss.dgraph.io/t/goclient-and-vendor-mismatch-issues/1166
https://forum.golangbridge.org/t/version-mismatch-between-vendored-version-of-dependency-and-normal-version/4073
https://groups.google.com/forum/#!topic/golang-nuts/liKQ6gtU4hk

**Comment by ashwin95r** [comment]
I think I vendored in the grpc package. We can remove the vendoring if it's causing troubles.

**Comment by manishrjain** [comment]
Yes, let's remove the vendored grpc package immediately, unless there's a specific reason to keep it vendored.

**Comment by etix** [comment]
Same goes for `golang.org/x/net/context` I think, or else it's not possible to use the Go client outside of dgraph itself.

**Comment by ashwin95r** [comment]
I have removed some packages from vendor. Can you please verify if it works for you? @etix

**Comment by ashwin95r** [comment]
Closing now. Feel free to reopen if the problem persists.
