### ISSUE TITLE
Alias support for ID

### ISSUE THREAD

**Issue by MrSaints** [dgraph-io/dgraph#861]
Aliases do not currently work for UID, and quite possibly, XID. That is, the following query:

```
{
    me(id:0x01) {
        id:_uid_
        MyName:name
        gender
        alive
        Buddies:friend {
            BudName:name
        }
    }
}
```

Will not return a result with `id`, but `_uid_` instead, assuming we are using the JSON output. 

From the looks of it, there doesn't seem to be a nice quick fix for this (happy to be told otherwise!) since:

1. The proto models are pretty much set on `Uid`, and `Xid`, so changing the `SetUID(..)` interface is probably not an option
2. But even disregarding the proto node, it seems like the codebase relies heavily on the _knowledge_ of `_uid_`, and there are cases where `SetUID(..)` is called without knowledge of the alias, yet

That being said, it does seem pretty trivial to alter the code to set an additional ID field using the alias without breaking the existing tests. But, that will just result in 2 fields / attributes containing the ID when an alias is used. That is potentially confusing, and inconsistent behaviour, so it is probably not an option (unless the old `_uid_` is deleted).

I think this would be a great feature / fix to have since it is something that works in most _official_ GraphQL implementations.

---

For now, I have somewhat achieved it by doing:

```go
// outputnode.go
type uidAlias interface {
	SetUIDAlias(uid uint64, alias string)
}

func (fj *fastJsonNode) setUID(uid uint64, alias string) {
        // `setUID` is just the original `SetUID`, but without the `_uid_` hardcoding
        // i.e. `fj.attrs["_uid_"]` -> `fj.attrs[alias]`
}

func (fj *fastJsonNode) SetUID(uid uint64) {
	fj.setUID(uid, "_uid_")
}

func (fj *fastJsonNode) SetUIDAlias(uid uint64, alias string) {
	fj.setUID(uid, alias)
	if _, found := fj.attrs["_uid_"]; found {
		delete(fj.attrs, "_uid_")
	}
}
```

And:

```go
// query.go
} else if pc.Attr == "_uid_" {
    if !uidAlreadySet {
        uidAlreadySet = true
        dst.SetUID(uid)
    }
    if ua, ok := dst.(uidAlias); ok && fieldName != "_uid_" {
        ua.SetUIDAlias(uid, fieldName)
    }
}
```

It passes all the tests (even ones that test for the UID). But, I get the feeling that there will be potential edge cases where the attributes will conflict. Needless to say, it does not stop someone from already causing a conflict like:

```
{
    me(id:0x01) {
        _uid_:name
        gender
        _uid_
        alive
        Buddies:friend {
            BudName:name
        }
    }
}
```

**Comment by pawanrawal** [comment]
Hey @MrSaints 

Agree it would be nice to have. I am working on this. For protocol buffer we can actually make UID and XID as part of the Properties and that way they can have the alias.

**Comment by pawanrawal** [comment]
This is now supported from 5e843244e334852f2ef6c47eb02765f4047794d8.

**Comment by MrSaints** [comment]
Awesome. Thanks!
