### ISSUE TITLE
[BUG]: variable cannot be used for facets in upsert mutation

### ISSUE THREAD

**Issue by rderbier** [dgraph-io/dgraph#8630]
### What version of Dgraph are you using?

22.0

### Have you tried reproducing the issue with the latest release?

None

### What is the hardware spec (RAM, CPU, OS)?

-

### What steps will reproduce the bug?

creating an upsert mutation with a query block setting a value variable and using in in the mutation block to set a predicate with a facet value is not parsed :
```
    
 mutation {
      set {
         uid(A) <proximity> uid(distance) (Jaccard=val(distance) ) .
      }
      
    }

```
### Expected behavior and actual result.

Query parsed and executed, the facets value must be the value of the value variable.

### Additional information

 "message": "while lexing uid(A) <proximity> uid(distance) (Jaccard=val(distance) ) . at line 1 column 55: Invalid input: ) at lexText",

**Comment by MichelDiz** [comment]
This is duplicated of #4520 and #1996 also there is a RFC https://discuss.dgraph.io/t/improve-facets-with-upsert-block/5640
