### ISSUE TITLE
[BUG]: Checksums for release assets don't match

### ISSUE THREAD

**Issue by acls** [dgraph-io/dgraph#8631]
### Have you tried reproducing the issue with the latest release?

None

### What is the hardware spec (RAM, CPU, OS)?

Linux

### What steps will reproduce the bug?

Download assets from https://github.com/dgraph-io/dgraph/releases/tag/v22.0.2 and compare checksums to actual checksums.

### Expected behavior and actual result.

I expected the .sha256 files to match the results of running the sha256sum command. Below are the actual results:
```
$ sha256sum badger-linux-amd64.tar.gz
e626fe7974021638a40b87fffffe59eb72eacf58801666fcde8894be7e413df1  badger-linux-amd64.tar.gz
$ cat badger-checksum-linux-amd64.sha256 
eb3a2d490fe3980188ed4fabbc1270cf2d633ec2b9d3add7376a145caf750d3c
```
```
$ sha256sum badger-linux-arm64.tar.gz
3927d7e09d325fd12034283c2298d78b20d18cc6c90536023633a73f50669d97  badger-linux-arm64.tar.gz
$ cat badger-checksum-linux-arm64.sha256 
54626c81d66b7f3af9a61d0f6d6ee2827923946afd67af1ef21138ffd0d508d4
```
```
$ sha256sum dgraph-linux-amd64.tar.gz
657e7c0c8348707f93078731d4e87e70a180075dd0e54f2a4b86f5ef2ae7ea7e  dgraph-linux-amd64.tar.gz
$ cat dgraph-checksum-linux-amd64.sha256 
a11258bf3352eff0521bc68983a5aedb9316414947719920d75f12143dd368bd
```
```
$ sha256sum dgraph-linux-arm64.tar.gz
3d6e960c1b14f2709bd9b1339ec5ca832d83cb5428690e4bc76f3784d3cc6be1  dgraph-linux-arm64.tar.gz
$ cat dgraph-checksum-linux-arm64.sha256 
2d20d50783c67594f3a5cc65aebf13b8807ffc35ec68e0f7f4abb2bc0c59eb2e
```

**Comment by skrdgraph** [comment]
@acls - thanks for reporting this. We will investigate and respond back here shortly 
cc: @joshua-goldstein

**Comment by joshua-goldstein** [comment]
Hi @acls , looks like you are taking the SHA of the tarball.  We provide the SHA of the binary.  E.g.,
```
> tar -xvf badger-linux-amd64.tar 
x badger-linux-amd64
> sha256sum badger-linux-amd64
eb3a2d490fe3980188ed4fabbc1270cf2d633ec2b9d3add7376a145caf750d3c  badger-linux-amd64
> cat badger-checksum-linux-amd64.sha256 
eb3a2d490fe3980188ed4fabbc1270cf2d633ec2b9d3add7376a145caf750d3c
```
Others are similar @skrdgraph

**Comment by skrdgraph** [comment]
Yes ^ ... @joshua-goldstein is right 

Also @acls, we don't build `badger` binaries in our `dgraph` release process. We reference the built binaries from `badger` repository. If you look at our release pipeline [here](https://github.com/dgraph-io/dgraph/blob/main/.github/workflows/cd-dgraph.yml#L25-L37) .. we simply pull the tar-ball & corresponding SHA's. And we upload the artifacts as part of `dgraph` release [here](https://github.com/dgraph-io/dgraph/blob/main/.github/workflows/cd-dgraph.yml#L58-L65)

Our SHA generation steps for `badger` are [here](https://github.com/dgraph-io/badger/blob/main/.github/workflows/cd-badger.yml#L33-L38). This conforms to standard practice of checking the SHA against the binary & not the tar-ball (as @joshua-goldstein mentions above).

Hope this helps clear the air. Please feel free to re-open the issue - if there are any doubts or concern. At this time we will close this issue with the above explanation.

**Comment by acls** [comment]
@joshua-goldstein @skrdgraph 
That's a little unexpected since that means I have to extract the file before checking the checksum. I don't recall having to do that before.
 
One suggested improvement to the checksum would be to include the file name after the checksum, eg:
```
a11258bf3352eff0521bc68983a5aedb9316414947719920d75f12143dd368bd  dgraph-linux-amd64
```
It would make it obvious which file was used to make the checksum.
It would also make it so the following command works after extracting the file:
```
sha256sum --check dgraph-checksum-linux-amd64.sha256
```
