### ISSUE TITLE
[BUG]: passing a value to first argument of a comparison function cause panic

### ISSUE THREAD

**Issue by jx6f** [dgraph-io/dgraph#8637]
### What version of Dgraph are you using?

v22.0.2

### Tell us a little more about your go-environment?

go version go1.19.5 linux/amd64

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

* RAM: 16GB
* CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
* OS: Arch Linux

### What steps will reproduce the bug?

pass a fixed value to first argument of a comparison function.

* for example:  `eq(1,len(variable))`
* reproduce command: `curl -H 'Content-Type: application/dql' localhost:8080/query -d '{ q as var(func: uid(0x1)) qq (func: uid(q)) @filter(eq(1,len(q))) {uid} }'`

### Expected behavior and actual result.

Passing a value to first argument is not allowed by dgraph's spec, I believe.
For example, Dgraph returns a "ErrorInvalidRequest" error for query `eq(len(q),len(q))`.

### Additional information

* logs during the crash

```
panic: runtime error: index out of range [0] with length 0

goroutine 239 [running]:
github.com/dgraph-io/dgraph/query.ProcessGraph({0x224a5b8?, 0xc0066e0f00}, 0xc0066a7b00, 0xc0066a7800, 0x0?)
	/home/runner/work/dgraph/dgraph/query/query.go:2128 +0x21f1
created by github.com/dgraph-io/dgraph/query.ProcessGraph
	/home/runner/work/dgraph/dgraph/query/query.go:2223 +0x130c
W0130 05:40:51.345753       8 sentry_integration.go:140] unable to read CID from file /tmp/dgraph-alpha-cid-sentry open /tmp/dgraph-alpha-cid-sentry: no such file or directory. Skip
```

* source code location of the panic

https://github.com/dgraph-io/dgraph/blob/2212e3fde6c3f5e74dfe7c9b9a77dfbada668575/query/query.go#L2126-L2128

From the comments, it seems correct that errors are handled during parse.

Thank you.

**Comment by mangalaman93** [comment]
This is the stack trace:
```
panic: runtime error: index out of range [0] with length 0

goroutine 379 [running]:
github.com/dgraph-io/dgraph/query.ProcessGraph({0x229d190?, 0xc00b926e40}, 0xc001044f00, 0xc001044c00, 0x0?)
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/query/query.go:2128 +0x20d1
created by github.com/dgraph-io/dgraph/query.ProcessGraph
	/home/aman/gocode/src/github.com/dgraph-io/dgraph/query/query.go:2221 +0x123f
[Sentry] 2023/02/08 12:28:59 Sending fatal event [3e6e2de8de824daea1acf0b753bcb2e9] to o318308.ingest.sentry.io project: 1805390
[Sentry] 2023/02/08 12:28:59 Buffer flushed successfully.
```

**Comment by jx6f** [comment]
Thank you very much :pray:
