### ISSUE TITLE
TerarkDB to replace RocksDB?

### ISSUE THREAD

**Issue by tomByrer** [dgraph-io/dgraph#865]
Seems to be a freeium version of RocksDB:
https://github.com/Terark/terarkdb/wiki

Maybe once you get to the stage of a commercial version?

**Comment by manishrjain** [comment]
TerarkDB guys were testing Dgraph with the replacement -- but they haven't concluded their tests yet. So, we'll see if that actually turns out to be faster or not.

**Comment by manishrjain** [comment]
Please move this to discuss.dgraph.io. Closing for now.
