### ISSUE TITLE
[QUESTION]: What do you mean by "Zero serves a tablet" ?

### ISSUE THREAD

**Issue by cscetbon** [dgraph-io/dgraph#8674]
### Question.

I'm trying to understand what does [this](https://github.com/dgraph-io/dgraph/blob/cbec2309413a9b17d407b3417300f719381b36d7/dgraph/cmd/zero/zero.go#L442) mean in zero.go, cause when I read it it seems that it would be served by a Zero node but as there is a groupId on a Tablet and data is stored on Alphas it doesn't make any sense to me. Same question for [this](https://github.com/dgraph-io/dgraph/blob/43f1d8aebcdf0bf8ab78ffb7db2e3ef9030d7300/worker/groups.go#L421) in groups.go which calls the previous method. When it says **_"Zero serves the Tablet"_** I feel like it's saying that data is sent by the Zero node but those servers only manage the cluster and should not interfere with queries other than sending information regarding which group stores a researched predicate. Can you explain it to me ?

**Comment by MichelDiz** [comment]
Zero doesn't do any of that. It just provides timestamps, releases UIDs, and manages groups. It also informs the Alphas of a series of things.

**Comment by cscetbon** [comment]
I understand that @MichelDiz based on the paper. However the comment is confusing and I'm asking what it means exactly.

**Comment by cscetbon** [comment]
I think I understand now, it doesn't ask Zero to serve the tablet, but ask Zero if it can serve the tablet which is why I was confused. Closing this question now. Thanks
