### ISSUE TITLE
[FEATURE]: GraphQL Schema Updates / Parts / Modules

### ISSUE THREAD

**Issue by ruidscampos** [dgraph-io/dgraph#8689]
### Use case

On a more complex application with a larger schema, where several parts of the schema are managed by different people, each with different views of the application who should only be concerned / see their specific part.

At the moment we need a person that combines all elements and updates the schema.

What would be ideal is for these individual people to update their own elements without seeing the entire schema, and have only permissions to update their specific elements of the schema.

### Solution proposal

Follow 3 possibilities that don't add much change to Dgraph and how the schema works, but enable better management of the schema as a whole.

One approach, allow the schema to be broken into parts, with access to each part controlled by @auth, and those authorized could manage their specific part. All parts would be merged together to form the entire schema, with all normal errors raised for duplicate definitions, etc.

Another approach, allow the invididual items on schemas (inputs, types, etc) to be updated / deleted individually, with some new condition added to it for access control. It would be a partial solution, but could work for many cases when the purpose is evolving an existing schema.

Finally, a more complex approach, create the concept of modules, where a schema is the top level that exists today, and modules are specialized areas of a schema that can be granted specific access and have their own special naming.

Example for this:

Schema {
  type User {
    userID: ID!
    name: String!
    lastSignIn: DateTime
    recentScores: [Float]
    reputation: Int
    active: Boolean
  }
}

ModuleProfile {
  type ModuleProfile.Profile {
    nickname: String!
    user: User!
  }
}

ModuleBooks {
  type ModuleBooks.Book {
    title: String!
    author: ModuleProfile.Profile!
  }
}

This enables teams to develop their solutions separately, while also allowing them to collaborate with each other.
It also allows for better security on who can access the schema and different parts of the schema / modules.
Fundamentally it doesn't change much of how Dgraph works, but adds a very powerful solution for bigger projects.

**Comment by rderbier** [comment]
Thanks for this feature request. We recognize that having a single big file with all types and all @auth is difficult to manage on medium to large project. We are collecting requirements at this point so your input is very valuable. One idea is also to use a concept of namespace (close to your module).  We at least 2 requirements here, the possibility to update only a portion of the schema and the addition ACL on schema parts. Adding this to the roadmap.
