### ISSUE TITLE
GNU-AGPL-3.0 is dev UNFRIENDLY

### ISSUE THREAD

**Issue by tomByrer** [dgraph-io/dgraph#869]
> You MUST disclose your source code when you distribute, publish or serve (i.e. through a web portal) modified or derivative software.

https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)
http://producingoss.com/en/license-choosing.html

So this forces ALL developers to share their code that they edit inside Dgraph.  This may (WILL for some to many) prevent it being used in a commercial context.  An authoritarian license like this will scare some CTOs & lawyers away from using this code at all.  Can't touch Dgraph with anything proprietary; if a dev needs to tweak Dgraph to optimally work with their copyright reserved system, then they will expose part of their private system (at least the API, which they may not want to do).

I know you guys mean well; you want to encourage sharing code improvements.  But forcing everyone to share risks fewer devs to use your system in the first place.  A more liberal license like MIT is less scary for lawyers and owners who have any likelihood of selling or splitting their company.  Also, I suspect NodeJS became more popular faster because almost of the NodeJS code on GitHub is MIT, which encourages worryless use in commercial use, & more users can mean more PRs.

https://www.slant.co/versus/3575/3582/~mit-license_vs_agpl

**Comment by manishrjain** [comment]
Hey @tomByrer,

Thanks for sharing your concern. The reasons we chose AGPL are outlined here:
https://open.dgraph.io/post/licensing/

If you wish to edit Dgraph server code without releasing the changes, you can purchase the commercial license. We haven't yet modified our website to advertise it, but feel free to reach out to me directly, and I can set you up with it.

**Comment by tomByrer** [comment]
Oh, OK, yes please modify your website to advertise the 'commercial license to advertise'; I read 5 blog posts of yours & missed that one.

**Comment by manishrjain** [comment]
https://github.com/dgraph-io/dgraph/issues/871 filed.
