### ISSUE TITLE
wrong docs version number

### ISSUE THREAD

**Issue by tomByrer** [dgraph-io/dgraph#870]
Link on page is hardwired for [v0.7.4](https://docs.dgraph.io/v0.7.4/query-language/).

I know versioning docs is a good idea, but I suggest there should be an alias for `/latest/` to redirect to prevent linking to outdated docs.  Not too big an issue now, but will once v1 or v2 is released.

* Doc page: [guides/intro-to-graphs.md](https://docs.dgraph.io/v0.7.5/guides/intro-to-graphs/)
* Doc version: `release/v0.7.5`

**Comment by manishrjain** [comment]
Thanks for submitting this, @tomByrer.

**Comment by sungwoncho** [comment]
Removed the hardcoded version number and instead started using paths relative for the current version selected by the user. https://github.com/dgraph-io/dgraph/commit/7a2975384e8fa2a2811060f10c8ae3b1ef73bb1d

I think having `/latest` alias is a good idea, but not needed at the moment. Simply avoiding hard-coding version number is a good enough solution for now. But that latest alias might be usesful as we have more documented releases. I will close this for now.

Thanks for reporting.

**Comment by tomByrer** [comment]
Works now, thanks!

> But that latest alias might be usesful as we have more documented releases. 

Yes, maybe when v1.0 is released.
