### ISSUE TITLE
[BUG]: Docker images don't work when built locally on a 22.04 ubuntu machine

### ISSUE THREAD

**Issue by all-seeing-code** [dgraph-io/dgraph#8701]
### What version of Dgraph are you using?

Dgraph version   : local
Dgraph codename  : dgraph
Dgraph SHA-256   : 57783495102de2b9461ed0f79e9984994e448c5d3b37b2906642d892a38ee0c0
Commit SHA-1     : d981392d8
Commit timestamp : 2023-02-24 11:20:24 +0530
Branch           : main
Go version       : go1.20
jemalloc enabled : true

### Tell us a little more about your go-environment?

go version go1.20 linux/amd64

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

RAM
```
               total        used        free      shared  buff/cache   available
Mem:            31Gi        10Gi       6.3Gi       2.1Gi        13Gi        17Gi
Swap:          2.0Gi        12Mi       2.0Gi

```
CPU
```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  20
  On-line CPU(s) list:   0-19
Vendor ID:               GenuineIntel
  Model name:            12th Gen Intel(R) Core(TM) i7-12700H
    CPU family:          6
    Model:               154

```
OS
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

```

### What steps will reproduce the bug?

`make docker-image`

`docker run dgraph/dgraph:local dgraph version`

### Expected behavior and actual result.

Expected: 

It should output the version of dgraph inside the docker image

Actual:
```
dgraph: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by dgraph)
dgraph: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by dgraph)
```

### Additional information

This happens when I try to build a docker image on Ubuntu22.04 machine.

**Comment by anurags92** [comment]
As a quick fix:
Update `contrib/Dockerfile` as:
```
FROM ubuntu:22.04
```
