### ISSUE TITLE
[ENHANCEMENT]: Consider use of reverse index for GraphQL hasInverse schema element

### ISSUE THREAD

**Issue by damonfeldman** [dgraph-io/dgraph#8735]
### Use case and current behavior

Currently, if one specifies hasInverse in a GraphQL Schema, the underlying DQL schema does not get created with a reverse index, and also not a "real edge" backwards.

### Enhancement

It may be more performant if this is indexed this way by default. It requires testing, and we need to consider how reverse edges are deleted (or not) and other aspects of system behavior. Adding hasInverse to DQL which would add a first-class predicate (perhaps hidden?) for the other direction.

A question to address here is why or if the reverse index is different from an edge in the other direction.

### Solution proposal

see options above

**Comment by jdgamble555** [comment]
Related to this - https://github.com/dgraph-io/dgraph/issues/8411
