### ISSUE TITLE
[FEATURE]: Expose Rebuild index via Alter API for users.

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#8738]
### Use case

The user can run this function to possibly get more performance.
```
(go buildIndexes(su, rebuild, closer))
```

There are reports that the simple fact of removing the index and putting it back. It resulted in perf changes. The goal here is to give Rebuild access directly. Without the user having to go all around.

### Current state

Have to be done by manually removing the index.

### Solution proposal

Give an operation for this.

e.g:

```
op.setRebuildAll(true);

OR

op.setRebuildattr("age");

Also (maybe? why not?)
op.setRebuildattr("dgraph.type");
```

**Comment by mangalaman93** [comment]
@MichelDiz this is already available through the Alter API. You can drop indexes and then, add them back again and Dgraph will build the indexes again.

**Comment by MichelDiz** [comment]
That is not true. When you drop the predicate it will DELETE the tablet. The objective here is to have a non-destructive rebuild.

Please, close an issue with proves. I couldn't find any "drop indexes only" or "rebuild indexes" in the Schema API. 

There is only:
dropAll
dropData
dropAttr
dropNs(namespace)

PS. If you don't get the objective, ask to clarify. I can improve the text to be more clear if the case.

**Comment by mangalaman93** [comment]
How will that benefit? Internally the implementation will drop and recreate the indexes?

**Comment by MichelDiz** [comment]
I don't believe there are any drops. Dgraph has always done this, rebuilding the index on the fly with each new Schema change. It was after I requested for this to stop that we didn't do it anymore. I remember Martin doing that. Since then I noticed that users were complaining about indexing. So I suspected it was this change.

We didn't drop the data. We just deleted the index and it was recreated.

**Comment by MichelDiz** [comment]
Here the issue https://github.com/dgraph-io/dgraph/issues/2828

**Comment by mangalaman93** [comment]
I still am not sure what is expected here. Maybe elaborate more. Currently we have enough of options for the user to delete attributes, any indexes (one or more) and recreate them.

**Comment by mangalaman93** [comment]
I think I see your point now. You are right that we don't have an explicit API for rebuilding indexes.
