### ISSUE TITLE
[ENHANCEMENT]: Extend parameterized cascades to work on aliases

### ISSUE THREAD

**Issue by WillfulExplorer** [dgraph-io/dgraph#8810]
### Use case and current behavior

I was looking at the examples for [parameterized cascades](https://dgraph.io/docs/query-language/cascade-directive/#parameterized-cascade) and I noticed that when used with aliases, the aliased fields are not treated as mandatory.

For example: when genre in the runnable is aliased as aliasedField, it is then treated as an optional field. 
![cascade](https://user-images.githubusercontent.com/9165843/235006673-00c493d2-c8e7-421a-8b14-ecd027bc2d2f.png)

### Enhancement

Parameterized cascades, when used with aliased fields, should treat those fields as mandatory.

**Comment by mangalaman93** [comment]
Thank you for filling the issue @WillfulExplorer, this seems reasonable and we will look into it.
