### ISSUE TITLE
[ENHANCEMENT]: BigInt data type support

### ISSUE THREAD

**Issue by rderbier** [dgraph-io/dgraph#8813]
### Use case and current behavior

DQL types include int64. Some use cases (finance and others) require arbitrary-precision arithmetic (big numbers).

### Enhancement

Big.Int must be supported.

As Go Big package also has Rat (rational) Float, would be nice to have those types too.

**Comment by rarvikar** [comment]
There was some demand in the past to add support for BigDecimal scalar types like uint256. We currently only support `int64` for decimal scalar types and `uint64` for the UID type. This was added as a low priority backlog via the [GitHub issue](https://github.com/dgraph-io/dgraph/issues/2107) and later 'Closed'. 

But `uint256` is heavily used in all crypto implementations. Ethereum uses 256-bit words natively. Their design rationale is that 4 or 8 byte words are too restrictive to store both addresses and values for computations and 32 byte words provide the perfect balance between performance and building a successful GAS model around it. Banks and financial institutions also rely on BigDecimal to avoid loss of precision while working with very large numbers.

Some requests from customers for this feat.: 

https://discuss.dgraph.io/t/support-arbitrary-precision-numeric-types/8746
https://discuss.dgraph.io/t/data-type-for-money/4899/3
https://github.com/dgraph-io/dgraph/issues/2107

This feature was requested in the recent past by multiple prospects in the fields of finance, commerce and block-chain, viz., IDFC Bank Ltd., Coinbase, KNN3, Commerce Extensions etc.

**Comment by mangalaman93** [comment]
Existing work on this feature: https://github.com/dgraph-io/dgraph/pull/3981
