### ISSUE TITLE
[BUG]: Dgraph Bulk loader alpha replication snapshot sync is not working for small datasets

### ISSUE THREAD

**Issue by mickymics** [dgraph-io/dgraph#8828]
### What version of Dgraph are you using?

v23.0.0 and v22.0.0

### Tell us a little more about your go-environment?

go 1.18.5 and go 1.19

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

32 GB RAM 8 Core CPU and Ubuntu WSL2

### What steps will reproduce the bug?

I am running dgraph with 3 zeros and 3 alphas [one alpha group] using docker-compose-ha.yaml and I did the bulk load to load goldendata.rdf file and schema file respectively and then I manually copy the p directory to one of the alpha and start the alpha process and wait for few minutes and then I start the remaining 2 alphas in that group.

Looks like followers p directory is not getting sync with the alpha leader.

### Expected behavior and actual result.

As per dgraph documentation https://dgraph.io/docs/howto/importdata/bulk-loader/#how-to-properly-bulk-load for smaller subsets the snapshot sync should happen automatically from leader alpha to other alpha followers in the same replica group and you don't need to copy the generated p directory to each and every alpha node separately

**Comment by mangalaman93** [comment]
Thank you for filing the issue. We are planning to work on this pretty soon.

**Comment by mickymics** [comment]
Thanks @mangalaman93, please let us know once it got fixed.
