### ISSUE TITLE
Support deletion of all predicates for a given node (S * *)

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#883]
To delete all the edges coming out of `<user>` node
```
mutation {
  delete {
     <user> * * .
  }
}
```

**Comment by manishrjain** [comment]
Shouldn't this be `* <user> *`?

**Comment by ashwin95r** [comment]
No, this is for deleting all the predicates for a given node. Updated the description.

**Comment by ashwin95r** [comment]
Done.
