### ISSUE TITLE
[BUG]: install_oss broken after commit c175edcaf4

### ISSUE THREAD

**Issue by kaniini** [dgraph-io/dgraph#8831]
### Tell us a little more about your go-environment?

go version go1.20.2 darwin/arm64

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

Apple M1 Max, 64GB RAM

### What steps will reproduce the bug?

`make install_oss`

### Expected behavior and actual result.

`make install_oss` is expected to succeed.

Instead, it fails because c175edcaf4 introduced a dependency on `github.com/dgraph-io/dgraph/ee/acl`, which is stubbed out in an OSS build.

**Comment by kaniini** [comment]
The 23.0.0 release was affected by this and presently fails to build.  Is it possible to get a 23.0.1 release which fixes this?

**Comment by mangalaman93** [comment]
We have release v23.0.1, you should be able to use it now. We are still to announce it though.
