### ISSUE TITLE
[ENHANCEMENT]: Possible to bring back binary backups for non enterprise

### ISSUE THREAD

**Issue by pbsladek** [dgraph-io/dgraph#8847]
### Use case and current behavior

We were on https://github.com/dgraph-io/dgraph/releases/tag/v21.12.0. 

Made the migration to v22.0.2. We were unaware that this feature had been undone.

https://github.com/dgraph-io/dgraph/pull/8067

Can we please put it back? Afaik this wasn't in any of the release notes that I came across.

### Enhancement

Bring the binary backup back to non enterprise.

### Solution proposal

https://github.com/dgraph-io/dgraph/pull/8067

**Comment by arpanbag001** [comment]
+1

**Comment by xqqp** [comment]
Recently upgraded to v24 and noticed backup/restore missing. Please consider adding it again.
