### ISSUE TITLE
[ENHANCEMENT]: Add @unique constraints to predicates in DQL schema

### ISSUE THREAD

**Issue by rderbier** [dgraph-io/dgraph#8865]
### Use case and current behavior

Dgraph does not enforce uniqueness in the DQL schema.
It is a first step  to address other feature requests from https://github.com/dgraph-io/dgraph/issues/8179

### Enhancement

The users can specify uniqueness constraint using @unique directive in the schema for a given predicate. 

### Links to Discuss, RFC or previous Issues and PRs

[jdgamble555](https://github.com/jdgamble555) requests]https://github.com/dgraph-io/dgraph/issues/8179

**Comment by mangalaman93** [comment]
Partially fixed in https://github.com/dgraph-io/dgraph/pull/8827
