### ISSUE TITLE
[BUG]: dgraph live loops on error when loading a float RDF to a int predicate

### ISSUE THREAD

**Issue by rderbier** [dgraph-io/dgraph#8881]
### What version of Dgraph are you using?

v23.0

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

cloud

### What steps will reproduce the bug?

create a predicate end_index of type int

load the predicate 
<_:test> <end_index> "116.0" .

with dgraph live loader

you get an infinite 
Processing data file "a.rdf"
Error while mutating: strconv.ParseInt: parsing "116.0": invalid syntax s.Code Unknown
Error while mutating: strconv.ParseInt: parsing "116.0": invalid syntax s.Code Unknown
Error while mutating: strconv.ParseInt: parsing "116.0": invalid syntax s.Code Unknown
Error while mutating: strconv.ParseInt: parsing "116.0": invalid syntax s.Code Unknown
Error while mutating: strconv.ParseInt: parsing "116.0": invalid syntax s.Code Unknown
Error while mutating: strconv.ParseInt: parsing "116.0": invalid syntax s.Code Unknown
...

**Comment by mangalaman93** [comment]
@rderbier to me this seems acceptable, that I see the issue and stop the live loader. Then fix it and run it again. What do you expect to see different here?
