### ISSUE TITLE
[BUG]: `make oss` fails for tag v23.0.0

### ISSUE THREAD

**Issue by protosam** [dgraph-io/dgraph#8885]
### What version of Dgraph are you using?

This is fixed in main, but it seems like the CI didn't validate `make oss` works.

Some code was missing in this file: https://github.com/dgraph-io/dgraph/blob/v23.0.0/ee/acl/run.go

The main branch was updated with changes that fixed the issue, but isn't in the tagged release: https://github.com/dgraph-io/dgraph/blob/bad5a0919b63e1e0d1105ec4a623da3ad2959663/ee/acl/run.go

### Tell us a little more about your go-environment?

N/A

### Have you tried reproducing the issue with the latest release?

None

### What is the hardware spec (RAM, CPU, OS)?

N/A

### What steps will reproduce the bug?

```
docker run --rm -it golang:1.20-bullseye bash
export DEBIAN_FRONTEND=noninteractive
apt update && apt install -y bzip2
git clone https://github.com/dgraph-io/dgraph.git /usr/src/dgraph && cd $_ && git checkout v23.0.0
make oss
```

Error from `make oss`:
```
root@cfc51c66be51:/usr/src/dgraph# make oss
make BUILD_TAGS=oss
make[1]: Entering directory '/usr/src/dgraph'
make -w -C dgraph all
make[2]: Entering directory '/usr/src/dgraph/dgraph'
# github.com/dgraph-io/dgraph/dgraph/cmd/bulk
cmd/bulk/mapper.go:246:39: undefined: acl.CreateGroupNQuads
cmd/bulk/mapper.go:247:39: undefined: acl.CreateUserNQuads
make[2]: *** [Makefile:80: dgraph] Error 1
make[2]: Leaving directory '/usr/src/dgraph/dgraph'
make[1]: *** [Makefile:38: dgraph] Error 2
make[1]: Leaving directory '/usr/src/dgraph'
make: *** [Makefile:46: oss] Error 2
```

### Expected behavior and actual result.

This should probably have been checked and failed during CI.

**Comment by mangalaman93** [comment]
We are planning to do a release soon and already added a CI so that this doesn't happen again. Is there anything that is not working for you on main?

**Comment by sanjayk-github-dev** [comment]
You could use `make dgraph` instead.

**Comment by protosam** [comment]
@sanjayk-github-dev that produces a non-opensource build, which can't be packaged and shipped everywhere.

@mangalaman93 everything seems fine in main from what I've tested today. The [CI file](https://github.com/dgraph-io/dgraph/blob/main/.github/workflows/ci-dgraph-oss-build.yml) looks good. This should be a non-issue in the future. Going to close this issue.

Thanks :)
