### ISSUE TITLE
[BUG]: Drop Type does not work as expected in self hosted dgraph

### ISSUE THREAD

**Issue by fcavazzoli** [dgraph-io/dgraph#8905]
### What version of Dgraph are you using?

v23.0.1

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

Self hosted cluster in AWS 
2 CPUs 
4Gb RAM
OS: linux (amd64)

### What steps will reproduce the bug?

1) create a schema with multiple types in it
2) Make mutations in some types 
3) call `curl -X POST localhost:8080/alter -d '{"drop_op": "TYPE", "drop_value": "TypeYouWantToDrop"}'`

### Expected behavior and actual result.

I expect for the type to be dropped but to keep the schema. 

result: 
The request returns success, but type still there and data is still there

**Comment by MichelDiz** [comment]
Sorry, but where did you see that you can drop types? You could delete the type, but not "drop" expecting some recursive delete.
