### ISSUE TITLE
[QUESTION]: IDE for DQL

### ISSUE THREAD

**Issue by cxcel** [dgraph-io/dgraph#8980]
### Question.

Is there a better IDE for the dql language of dgraph (such as the vscode plug-in),
For novices, the efficiency of writing dql is too low, and it is not easy to check for errors

**Comment by elkmi** [comment]
Perhaps it is possible to generate a schema file from a protobuf file

**Comment by MichelDiz** [comment]
No, we don't have any. I have created a snippet some time ago. https://github.com/MichelDiz/vscode-dgraph-snippets
But we don't have any Lint and such.
