### ISSUE TITLE
[QUESTION]: data writing is slow

### ISSUE THREAD

**Issue by elkmi** [dgraph-io/dgraph#8983]
### Question.

	
type Author struct {
	Id   uint64
	Dob  time.Time `json:"dob,omitempty"`
	Name string    `json:"name,omitempty"`
}
        t1 := time.Now()
	author := Author{}
	txn := dg.NewTxn()
	for i := 0; i < 1e4; i++ {
		author.Name = fmt.Sprintf("name_%d", i)
		author.Dob = time.Now()
		out, _ := json.Marshal(&author)

		_, err := txn.Mutate(ctx, &api.Mutation{SetJson: out})
		if err != nil {
			fmt.Println("Mutate:", err)
			break
		}

	}
	err = txn.Commit(ctx)
	if err != nil {
		fmt.Println("commit:", err)
	}

This code inserts 10,000 pieces of data and takes 5 minutes.
Is this normal, can it be faster?

**Comment by mangalaman93** [comment]
I think you should consider batching together multiple pieces of data into multiple txn. You could also run multiple txns in parallel if they are writing different data into dgraph to ensure there are no conflicts.

**Comment by elkmi** [comment]
thanks
