### ISSUE TITLE
remove reflexive edges from results

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#899]
Add a directive to remove self edges from results.  For example, in the following query, to remove actors as co actors of themselves.

```
{
  coactors(func:allofterms(name, "Jane Campion")) @cascade @normalize {
    JC_films as director.film {      # JC_films = all Jane Campion's films
      starting_movie: name
      starring {
        JC_actors as performance.actor {      # JC_actors = all actors in all JC films
          actor : name
          actor.film {
            performance.film @filter(not var(JC_films)) {  # find a different film
              film_together : name
              starring {
                # find a coactor who has been in some JC film
                performance.actor @filter(var(JC_actors)) {
                  coactor_name: name
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by MichaelJCompton** [comment]
Actually, maybe this isn't enough.  In this case, how to specify where I want the duplicates removed from - it's not a simple self referential edge, and never would be in a the movie dataset because it's quite a few edges from an actor to their co-actors.

The most general mechanism seems to be to be able to accumulate variables specific to the current branch in the query, rather than globally.  In this case, it looks like both global and local are required.

**Comment by ashwin95r** [comment]
We don't need a direct self-referential edge. Providing the directive would mean that a uid cannot be its own child at any level.

**Comment by MichaelJCompton** [comment]
What if _uid_ was assigned to a value variable and then used in filters?
```
q(...) {
  myid as _uid
  ...
  some { edges { later @filter(NOT(var(myid))) } }
}
```
This syntax is accepted at the moment, but I guess after following other edges, it's no longer the correct context to use `myid`.

**Comment by pawanrawal** [comment]
@MichaelJCompton That might work in case of a single starting node but wont work as desired for multiple starting nodes as you would want to only remove the starting node from a particular tree path.

**Comment by pawanrawal** [comment]
This is now supported and has been merged to master.
