### ISSUE TITLE
Cancel schema and improve it to automatically generate schema, modify schema, and update schema based on data without human intervention, and ensure compatibility with historical data.

### ISSUE THREAD

**Issue by hktalent** [dgraph-io/dgraph#9028]
### Use case

Cancel schema and improve it to automatically generate schema, modify schema, and update schema based on data without human intervention, and ensure compatibility with historical data.
Reduce the difficulty of use

**Comment by rarvikar** [comment]
Please

**Comment by rarvikar** [comment]
Closed by mistake. Re-opening.
