### ISSUE TITLE
Add Ability to Bulk Delete Based on Results of a Query

### ISSUE THREAD

**Issue by willcj33** [dgraph-io/dgraph#903]
I think it would be useful to have the ability to run a query like so: 
`
{deleteItems as var(func: eq(property, someval)){} 
delete(id: var(deleteItems)) }
` 
That may be poor syntax, but just having the ability to query and delete based on that query would be great.

**Comment by manishrjain** [comment]
This depends upon #919.

**Comment by manishrjain** [comment]
@ashwin95r Can you confirm that this would work now? Test it out before marking this issue as resolved.

**Comment by ashwin95r** [comment]
Yes, It doesn't work now. I'm looking into it.

**Comment by zboralski** [comment]
is it possible to make a query ... for example get all nodes with predicate x, filter nodes that don't have predicate y... delete all resulting nodes?

**Comment by pawanrawal** [comment]
This is possible in a two-step process. 
1. Make a query as part of a transaction to get the uids of all filtered nodes. 
2. Issue another mutation as part of the same transaction to delete them.
