### ISSUE TITLE
DGraph Crashes on CentOs-7

### ISSUE THREAD

**Issue by ravieze** [dgraph-io/dgraph#906]
environment: Windows 10
Oracle VM Virtual box 4.3.12
Cent OS7 minimalistic installation
install docker with command : Yum install docker
start docker
run the command:  docker run -it -p 8080:8080 -v ~/dgraph:/dgraph:Z dgraph/dgraph dgraph --debugmode --bindall=true

run the command:  docker run -it -p 12345:12345  -v ~/dgraph:/dgraph dgraph/dgraph dgraphloader -r goldendata.rdf.gz

After 45 min of digestion the Dgraph is no more there (Crash?)
now try restarting Dgraph with the command:
 docker run -it -p 12345:12345  -v ~/dgraph:/dgraph dgraph/dgraph dgraphloader -r goldendata.rdf.gz

Dgraph tries to ingest data and eventually crashes.. 

every new restart of Dgraph ends in crash with in minutes from now onwards

**Comment by manishrjain** [comment]
Can you add the crash log?

**Comment by ravieze** [comment]
[log.txt](https://github.com/dgraph-io/dgraph/files/982521/log.txt)

**Comment by manishrjain** [comment]
This log has no crash. All the lines look normal.

**Comment by ravieze** [comment]
Dont know, but there is no DGraph process either.

**Comment by ashwin95r** [comment]
The master no longer uses Cgo. It should now work, but we don't have access to CentOS machine, so we can't verify.

**Comment by manishrjain** [comment]
@srh will check and ensure that Dgraph master works on CentOS.

**Comment by srh** [comment]
Things work fine in CentOS.

@ravieze Maybe your problem arose from using `docker run` to run dgraphloader.  My understanding is that `docker run` creates a new container.  (I am not too familiar with docker, so correct me if I'm wrong and there is subtle behavior there.)  What I get when running dgraphloader inside of docker is a connection error.  I guess I'll re-close, if nobody has any problem with that.

**Comment by ravieze** [comment]
I tried DGraph on a proper m/c with cent os installed. Things worked fine. I have been using this for a while.
