### ISSUE TITLE
How to query all fields of a node?

### ISSUE THREAD

**Issue by AlexanderChen1989** [dgraph-io/dgraph#909]
How to query all fields of a node?

**Comment by AlexanderChen1989** [comment]
Query all fields of node without knowing the schema

**Comment by pawanrawal** [comment]
Hi @AlexanderChen1989 , `_predicate_` should help you do that. 
https://docs.dgraph.io/v0.7.6/query-language/#expand-predicates

**Comment by AlexanderChen1989** [comment]
@pawanrawal thanks
