### ISSUE TITLE
common graph algorithms support

### ISSUE THREAD

**Issue by yuhengShii** [dgraph-io/dgraph#9091]
### Question.

Hi,
Is there any implementation about some common common graph algorithms?
I have only  found "K-Shortest Path queries" in document.

**Comment by rarvikar** [comment]
Hi @yuhengShii ,

The only native implementation available is indeed the K-Shortest Path algorithm as you noticed. 

If you have any requirements for specific graph algorithms, I'd suggest submitting an enhancement request instead, or if you will, maybe even a contribution to the codebase under the Apache 2.0 license. :) 

Thanks!
