### ISSUE TITLE
Broken examples

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#910]
* Doc page: [query-language/index.md](https://docs.dgraph.io/v0.7.6/query-language/)
* Doc version: `release/v0.7.6`

Following examples not working: 

* https://docs.dgraph.io/v0.7.6/query-language/#value-variables

* GraphQL Variables examples go code no longer current - should use `SetQueryWithVariables()` ?
https://docs.dgraph.io/v0.7.6/query-language/#graphql-variables

* https://docs.dgraph.io/v0.7.6/query-language/#regular-expressions looks ok, but the index isn't in the indexes listed at the beginning of the doc, so it's likely not to be able to be run.

**Comment by pawanrawal** [comment]
Thanks for reporting the bugs.

1. The first issue was a bug and has been fixed now.
2. We need a way to fix this in the docs repo. Right now we just have a placeholder for the go-grpc code which has `SetQuery` hardcoded. We need a way to give custom examples to it which would be helpful in this case and also when we want to show mutation examples. I have an open issue here https://github.com/dgraph-io/hugo-docs/issues/14.
3. This has been fixed. Data wasn't reloaded after adding the index.

**Comment by pawanrawal** [comment]
To fix Issue no 2 above, we need a script which can convert custom gRPC examples to a single line so that runnable shortcode can take them as parameters. @MichaelJCompton is working on such a script.
