### ISSUE TITLE
[BUG]: Using GraphQL PointList in schema produces error

### ISSUE THREAD

**Issue by matthewmcneely** [dgraph-io/dgraph#9101]
### What version of Dgraph are you using?

v24.0.0

### Tell us a little more about your go-environment?

Cloud

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

Cloud

### What steps will reproduce the bug?

Create a simple schema:

```
type Foo {
    path: PointList
}
```

Apply the schema and get:

```
resolving updateGQLSchema failed because while validating GraphQL schema: input:21: Undefined type PointListFilter.
```

### Expected behavior and actual result.

As per the docs, the applying of the schema should be successful.

**Comment by rarvikar** [comment]
Hi,

The `PointList` type is unsupported and we recommend using an array of points as [Point] instead, which should work.

```
type Foo {
  path:  [Point]
}
```
Other "collection of points such as Polygon and Multipolygon are indeed supported as well. 

I believe the types section from the docs [cites an example](https://dgraph.io/docs/graphql/schema/types/#pointlist) for `Pointlist` which is misleading and needs to be removed, although the description specifically only mentions `Point`, `Polygon` and `Multipolygon` as the supported types. 
I've submitted a request to update the docs in that regard. 

As such I'll close out this issue for now but feel feel free to re-open if you have any other related queries. 
Best,
Rahul
