### ISSUE TITLE
Returning uid when no further edge specified (debug mode) 

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#912]
Currently 

```
{
	me(id: 0x443e596719408209) {
		director.film 
	}
}
```

won't return the uid of each film in debug mode.  But that seems a clear intent of such a query.

One can fake it with
```
{
	me(id: 0x443e596719408209) {
		director.film { thisIsNotAnEdge }
	}
}
```
or with a real edge.  But these things won't always work if there is an `@cascade` directive used as well.

It would be nice to be able to query for triple patterns like this without having to find an extra edge.

**Comment by MichaelJCompton** [comment]
Actually, I'm not sure if debug mode is the right thing - it seems that wanting `uid`'s in results is more generally applicable than just debugging.  For example, to update some nodes, one would query for the right nodes with `uid`, write out triples and batch an update.

Maybe there could be a directive in the query that switches on `uid` returns and also gives a behaviour like this issue?

**Comment by Motakjuq** [comment]
You can use `_uid_` in the query to get the uid when you are not using debug

**Comment by MichaelJCompton** [comment]
Looks like this also works

```
{
  q(func: allofterms(name, "Peter Jackson")) {
    director.film { _uid_ }
  }
}
```

Thanks to @Motakjuq

**Comment by pawanrawal** [comment]
Now
```
{
	me(id: 0x443e596719408209) {
		director.film 
	}
}
```
Would return all film ids in debug mode.
