### ISSUE TITLE
The resulting number of nodes changes for the same query.

### ISSUE THREAD

**Issue by sungwoncho** [dgraph-io/dgraph#914]
**version: 0.7.6**

Description:

The number of nodes returned from the server is inconsistent every time a query is run, if the query is using `gt` and `count` on the root level.

Steps to reproduce:

1. Set up data by running the following:

```
mutation {
  set {
    <_:nd> <foo> "a" .
    <_:nd2> <foo> "a" .
    <_:nd3> <foo> "a" .
    <_:nd4> <foo> "a" .
    <_:nd5> <foo> "a" .
    <_:nd6> <foo> "a" .
    <_:nd7> <foo> "a" .
    <_:nd8> <foo> "a" .
    <_:nd9> <foo> "a" .
    <_:nd10> <foo> "a" .
    <_:nd11> <foo> "a" .
    <_:nd12> <foo> "a" .
    <_:nd13> <foo> "a" .
    <_:nd14> <foo> "a" .
    <_:nd15> <foo> "a" .
    <_:nd16> <foo> "a" .
  }
}
```

2. Run the following query

```
{
  me(func: gt(count(foo), 0)) {
  }
}
```

The number of nodes changes sometimes.

**Comment by ashwin95r** [comment]
Fixed in 7a37a1c35fe117b580407900ecd222034c90ebf4
