### ISSUE TITLE
Modify query block representation

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#918]
Currently we do: 
```
mutation{
 set {
  <a> <b> <c> .
 }
}
query {
  me(id: a) {
   _uid_
  }
}
```
But the idea is to allow
```
set {
  <a> <b> <c> .
}
me(id: a) {
   _uid_
}
```
So we basically remove one outer level `{` and the `mutation` or `query` keywords.
so the new key words would be `set`, `delete`, `setschema`, or `some query root` and  also we'd allow multiple set delete and query blocks (which we already do) in the same query. 

PS: more thought has to be put into the `{ }` at the start and end of the block if we need to kep compatibility with graphQL.

**Comment by szymonm** [comment]
You mentioned setschema to be new keyword, why not just schema?

**Comment by szymonm** [comment]
How about having `{ }` around query block optional?

**Comment by ashwin95r** [comment]
> You mentioned setschema to be new keyword, why not just schema?

`setschema` because `schema` would be used for retrieving the schema as we do now. 
> How about having { } around query block optional?

That's the part I'm not sure of. It might make us graphQL incompatible.

**Comment by manishrjain** [comment]
> How about having { } around query block optional?

That's one of the main designs of this change. We would no longer have just empty `{}`. Each query would just have named blocks. Notice this:

```
set {
  <a> <b> <c> .
}
me(id: a) {
   _uid_
}```

There would be no other way to write this. You can replace `me` with something else, but can't drop it altogether. Also, there's no `{}` around this whole query.

**Comment by szymonm** [comment]
Do we also intend to change the grpc calls to allow multiple mutations in a single request?

So we decide to break graphQL compatibility for queries and backwards compatibility with dgraph, right?

**Comment by szymonm** [comment]
We should decide on the structure of a named query, when using variables:

before it was
```
query me($id: uint64) {
    me(id: $id) {
        _uid_
    }
}```

should we have just:
```
me($id: uint64) {
    me(id: $id) {
        _uid_
    }
}
```
Looks confusing and will make parser a bit more complicated, because it needs to read `$` sign to know that first `me` is a named query definition and not a unnamed query root.

We agreed with @ashwin95r to discuss it tomorrow. CC: @manishrjain

**Comment by szymonm** [comment]
Tried implementing the lookahead in parser and it wasn't as bad as I thought.

Nevertheless, we decided to abandon the change for now as it would be confusing for the users.
