### ISSUE TITLE
Support variables in mutation blocks.

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#919]
There would be dependency between query and mutation blocks (just like we have among query blocks now).

Eg: 
```
mutation {
 set {
  var(adults) <isadult> "true" .
  <a> <b> <c> .
  . . .
 }

 delete {
  var(adults) <ischild> "true" .
 } 
}
{
 me(id: a) {
   adults as friends @filter(gt(age, 18))
 }
}
```
This would fetch my friends whose age is above 18. Then for each UID in that list perform the mutation.

**Comment by szymonm** [comment]
The example supports only uid vars. How about having also value vars? We need special object value then (like "_")?

 Use case would be as follows:
```
mutation {
 set {
  var(c) <friendsCount> _ .
 }
}
{
 var(id: [id1, id2, id3]) {
   c as count(friends)
 }
}
```

**Comment by ashwin95r** [comment]
We support variables in mutations now.
