### ISSUE TITLE
[BUG]: Unable to Completely Delete Nodes or Whole Graph in Dgraph

### ISSUE THREAD

**Issue by imrahul361** [dgraph-io/dgraph#9213]
## **Description**
I am encountering an issue with Dgraph where I am unable to fully delete a node or the entire graph. Although I can delete individual predicates from a node, complete node deletion using either the JSON mutation syntax or RDF N-Quad format does not seem to work as expected. Instead of being fully removed, nodes turn into orphan nodes with no data but still apparently occupy space on disk.

### JSON Mutation Query
``` 
{
  "delete": {
    "uid": "0x37..."
  }
}
```

###  RDF N-Quad Format
```
{
  delete {
    <0x37...> * * .
  }
}
```
In both scenarios, I am consistently facing issues with Dgraph where efforts to completely delete nodes using JSON mutations do not work as intended. Despite receiving a "done" success message, the node remains unaffected.

### Deleting all predicates one by one from a node
```
{
  delete {
    <0x37...> <name> * .
    <0x37...> <age> * .
   .
   .
   .
   .
  }
}
```

In the above case, the nodes are not entirely removed; they simply become empty objects. When I query these nodes post attempted deletion, they appear as empty or orphaned nodes, indicating that although their predicates have been cleared, the nodes themselves linger.

## **Environment Details**
Dgraph Version: v24.0.1
Deployment: Standalone
RAM: 8GB
Disk Setup: HDD, 50GB
Number of Alpha Nodes: 3
Number of Zero Nodes: 3
Operating System: Debian GNU/Linux 12 (bookworm)
CPU: 2 cores

## **Requirement**
The requirement is that when a node is deleted, not only should all its predicates be deleted but it should also be entirely removed from the disk to not waste space and possibly affect performance. This behavior is crucial for managing dynamic graphs where nodes are frequently created and deleted.

Please let me know if there are additional configurations or methods that should be followed to completely delete nodes and free up all associated resources, or if this might be a potential bug that needs addressing this memory leak.

Any assistance or clarification on this issue would be greatly appreciated, as it impacts our ability to efficiently manage storage and maintain the graph's integrity.

Thank you!

### Tell us a little more about your go-environment?

Go version 1.20.2

### Have you tried reproducing the issue with the latest release?

None

### What is the hardware spec (RAM, CPU, OS)?

Dgraph Version: v24.0.1
Deployment: Standalone
RAM: 8GB
Disk Setup: HDD, 50GB
Number of Alpha Nodes: 3
Number of Zero Nodes: 3
Operating System: Debian GNU/Linux 12 (bookworm)
CPU: 2 cores

### Create a node, Let's say:
```
{
 "set" : {
   "name" : "xyz",
   "age" : 20,
   "city" : mumbai
  }
}
```
On success, it will create an uid. let's say <0x123...>

### Get the Details:
```
{
  response(func: uid(0x123...)) {
   	name
   	age
   	city
  }
}
```

### Delete the Node:
```
{
  delete {
    <0x123...> * * .
  }
}
```

### Deleting all predicates one by one from a node
```
{
  delete {
    <0x123...> <name> * .
    <0x123...> <age> * .
   .
   .
   .
   .
  }
}
```

### Expected Behavior:
The object with uid <0x123...> should no longer exist.

### Actual Behavior:
1. The node remains unaffected despite the successful message "done".
2. The result is an empty object devoid of any predicates.

**Comment by harshil-goel** [comment]
What do you mean object shouldn't exists? In Dgraph UID is just a identifier. It's uint64, and all the UIDs are technically empty objects in which you are adding some data. UIDs don't get deleted, you can keep reusing them.

**Comment by imrahul361** [comment]
Is there a more efficient way to delete nodes in Dgraph than removing all predicates to empty the object? If I only have the UID of the root node, is it possible to delete the entire graph? What is the optimal approach to delete an entire graph in Dgraph given the root node's UID?

**Comment by imrahul361** [comment]
> What do you mean object shouldn't exists? In Dgraph UID is just a identifier. It's uint64, and all the UIDs are technically empty objects in which you are adding some data. UIDs don't get deleted, you can keep reusing them.

{
  delete {
    <0x123...> * * .
  }
}

using this Mutation query, I am unable to empty the object/node

**Comment by asta331** [comment]
You can use the type feature to specify predicates of a given node: https://dgraph.io/docs/dql/dql-schema/#node-types
The reason your delete mutation doesn't work is because dgraph doesn't know which predicates the node has.
I don't think this is a bug.

**Comment by rarvikar** [comment]
Hi @imrahul361, 

Using the wild-card delete mutation as `<some-uid> * * .` does result in a successful deletion of all edges outgoing from that node. This includes all non-uid edges of any of the supported scalar types like `Int`, `String`, `Point` etc. 
Are you referring to the existence of the UID following the deletion ? If yes, that's a non-issue as that UID can be re-used again in Dgraph and does not indicate a failed deletion. 

As such, we would be closing this issue for now but let us know if you have any queries.
