### ISSUE TITLE
Support count at the root level

### ISSUE THREAD

**Issue by sungwoncho** [dgraph-io/dgraph#925]
As a user, when I want the count of 'directors', I have to fetch all directors and count the length manually.

e.g.

```
{
  dir(func: gt(count(director.film), 0))
}
```

However it might be useful if I can just fetch `count` at the root level.

```
{
  director_count: count(dir(func: gt(count(director.film), 0)))
}
```

**Comment by pawanrawal** [comment]
We can have the alias as mentioned. If no alias is asked for, we can have `count(dir)` in the response. 
If count is asked at root, that query block can't have children.

**Comment by pawanrawal** [comment]
This is now supported. You can do the following query to get count of all directors at root.
```
{
  dir(func: gt(count(director.film), 0)) {
    count()
  }
}
```
