### ISSUE TITLE
Support rdf type xsd:decimal

### ISSUE THREAD

**Issue by zaredb** [dgraph-io/dgraph#926]
Importing an RDF with officially supported XML data type decimal fails

RDF Compatible core types: https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-compatible-xsd-types

Supported types in dgraph loader https://github.com/dgraph-io/dgraph/blob/350209fbbe4be50416f2f361491c2cf879d7d494/rdf/parse.go#L412

**Comment by ashwin95r** [comment]
Supporting arbitrary precision decimal numbers isn't on the roadmap. You can use float (which uses 64 bits), or strings to represent this data.

**Comment by EronWright** [comment]
Support for big decimals would be quite handy for cryptocurrency applications, which routinely model currency units (e.g. Ethereum _ether_, _wei_) as `BigDecimal`.

**Comment by manishrjain** [comment]
Yeah, we should consider supporting BigDecimal types.

**Comment by EronWright** [comment]
To facilitate a contribution, would someone kindly enumerate the high-level tasks?  Thanks!

**Comment by manishrjain** [comment]
Closing this in favor of a newer duplicate issue.
