### ISSUE TITLE
Increment operation

### ISSUE THREAD

**Issue by sungwoncho** [dgraph-io/dgraph#929]
IDEA: Increment operation will allow to increment an integer without fetching its current value.

Example usage:

Incrementing view counts for a post

  - Currently users have to make two queries
    - One to get the current `count` and `_uid_`
    - One to do the mutation based on the result from the previous query.

```
// query 1
{
  var(id: u4) {
    ~viewer {
        vid as _uid_
        vc as view_count
    }
  }
}

// query 2
mutation {
  set {
    <some_id> <count> "some_value" .
}
```

**Comment by manishrjain** [comment]
This is harder than it sounds. It would break idempotency of all current Dgraph operations. That is, if the operation fails after doing the increment, and gets re-run; we'd end up incrementing twice.

This won't be possible until we support some level of atomics.

**Comment by ashwin95r** [comment]
This would be possible with CAS counters, if we support them in Dgraph. Needs more thought.

**Comment by manishrjain** [comment]
This would be now possible due to transactions. Though, would still make sense to batch up these view counts to decrease how many transactions are run (to avoid running one txn per view).
