### ISSUE TITLE
dgraphloader doesn't respect blank nodes

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#935]
dgraphloader isn't preserving blank nodes across batches.  For a trivial example file

```
<testXID> <findME> _:testBN .
_:testBN <name> "value 1" .
```

dgraphloader reports

```
Processing trivialBatch.gz
Number of mutations run   : 2                                                                       
Number of RDFs processed  : 2
```

and a test query for

```
{
  q(id: testXID) {
    expand(_all_) {
      expand(_all_)
    }
  }
}
```

doesn't find any outgoing edges.

**Comment by manishrjain** [comment]
I'll work on the Go client. It needs to be carefully looked at to address all these issues.

**Comment by janardhan1993** [comment]
We remember blank nodes across the batches now.
