### ISSUE TITLE
Delete all references to subject

### ISSUE THREAD

**Issue by dpeek** [dgraph-io/dgraph#940]
The new wildcard syntax for deleting all subject predicates is great, but sill leaves users with a tricky problem: to truly delete a subject we must also find all references to it (uid edges) and delete those too. I can vaguely understand how supporting this might be difficult to scale, but the alternative (users solving it themselves) sounds equally challenging and error prone.

The syntax seems obvious enough: delete this value for all predicates on all subjects.

```
mutation { delete {
  * * <0x1422bef15176814> .
}}
```

Or perhaps there's a way of achieving this with the current query language?

**Comment by manishrjain** [comment]
Hey @dpeek, This isn't a scalable operation. The way data is sharded, we can key `subject -> objects`, but not vice-versa. That'd require us to traverse over everything, which is slow; or keep track of more things than we need to, which gets complex.

There's an alternative way to achieve this, which is via mutation variables (WIP). If you have a reverse index on the predicates that you frequently want to delete in this way, you'll be able to run something like this:

```
{
  var(id: 0x1422bef15176814) {
    x as ~friend
  }
  mutation {
    del {
      var(x) <friend> <0x1422bef15176814> .
    }
  }
}
```

This isn't perfect, but it should give you the functionality.
