### ISSUE TITLE
term matching broken on public site

### ISSUE THREAD

**Issue by joeblew99** [dgraph-io/dgraph#946]
https://docs.dgraph.io/v0.7.5/query-language/#term-matching

None of the bleve stuff is working there.

**Comment by pawanrawal** [comment]
Hi @joeblew99 

Please have a look at
```
https://docs.dgraph.io/v0.7.6/query-language/#term-matching
```

All the queries are powered by the latest Dgraph release, so some queries on older releases might not work because of syntax changes.

**Comment by joeblew99** [comment]
k
