### ISSUE TITLE
issue with UID var in filter

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#950]
Hi, this works in 0.7.6, but not on master

```
{
  peterJ(func:allofterms(name, "Peter Jackson")) @normalize @cascade {  
    F as director.film 

    actor.film {
      performance.film @filter(var(F)) {
        film_name: name
      }
      performance.character {
        character: name
      }
    }
  }
}
```
Looks like the UID variable isn't matching properly in the filter.

**Comment by pawanrawal** [comment]
Based upon my conversation with @ashwin95r this worked in v0.7.6 because of a bug. Variables are only passed from a parent to children within a query. You could use this alternate way to do this query
```
{
  P as var(func:allofterms(name, "Peter Jackson")) {
    F as director.film
  }

  peterJ(id: var(P)) {
    name
    actor.film {
      performance.film @filter(var(F)) {
        name
      }
      performance.character {
        name
      }
    }
  }
}
```

I am not sure if we should support passing variables to children of siblings as that would make our queries slower because we won't be able to always do them concurrently as we do now.

**Comment by MichaelJCompton** [comment]
Not a problem.  I had just noticed the behaviour and assumed it was as expected.  I had written the query the way round I did just to demonstrate that use of variables.  I'm happy to remove it though.

I would expect that there isn't any change to how expressive GraphQL+- is by allowing or not allowing this - at a first thought, queries like mine could always be rewritten to ones like your example.  And then the execution is roughly the same - i.e. it would be a bit like siblings not run concurrently?  I assume Dgraph forms some sort of topological ordering between queries based on variables and executes them in that order.

The only argument then for having it would be for simpler looking queries.

**Comment by ashwin95r** [comment]
>  I assume Dgraph forms some sort of topological ordering between queries based on variables and executes them in that order.

Yes that's right.

> The only argument then for having it would be for simpler looking queries.

But it'd affect the concurrent execution of sibling nodes which is not desirable. So I think we're better of supporting variables within blocks to be used only in the children which would always be executed after the parent. And it also keeps the code simple.
