### ISSUE TITLE
Support retrieving the min/max entity in groupby

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#962]
```
{
 var(id: 1) {
  friends @groupby(school) {
   a as max(age)
  }
 }
}
```

Here `var(a)` would contain the mapping from school to the maximum age of friends who belong to that school. But we also want to have a way to retrieve the actual entity that contributed to the max.

**Comment by ashwin95r** [comment]
We should be able to do this:

```
top(id: uid(a)) {
  va as val(a)
  students @filter(eq(age, va) { name }
}
```

**Comment by campoy** [comment]
I just checked whether this was implemented and ... it was!!

You can try out the example below on play.dgraph.io and see that indeed `max` and `min` are supported in `groupby` clauses

```js
{
  var(func:allofterms(name@en, "steven spielberg")) {
    director.film @groupby(genre) {
      latest as max(initial_release_date)
    }
  }

  byGenre(func: uid(latest)) {
    name@en
    latest_movie : val(latest)
  }
}
```
