### ISSUE TITLE
Has function to quickly check presence of edge

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#968]
A lot of times, we derive the type of entity by checking if a node has a certain edge. For e.g., for directors, we do this: `func: gt(count(film.director), 0)`, to generate a list of all directors.

This does 2 things: It generates a count first, and then it does the filtering. This is a common enough query that it would make sense to do it in one step.

`func: has(film.director)`. This would generate a list of all directors. And it can do so by only iterating over keys, which is a super fast operation in Badger.

**Comment by pawanrawal** [comment]
If we only iterate over keys the results might not be right always as the user could have deleted the edge and the posting list might have zero postings.

**Comment by pawanrawal** [comment]
This is done and merged to master.
