### ISSUE TITLE
Code Review System

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#97]
We need a code review system which can highlight all the golint, go vet, and other issues. Given the high noise ratio, we want to show these to the reviewer and the author of the change, so they can make a decision about which ones to fix. Not all these issues are relevant, so we don't want to block the changelist just because golint complains.

So far I think Phabricator seems to have such a mechanism. We should also look into Gerrit. Once decided, we should set up one. Suggestions on other code review systems which can allow for above customization are welcome!

**Comment by sreeram-boyapati** [comment]
At HackerEarth, We use phabricator. It is working very well for a mid-size team.
Features:
Code Review
Wiki Hosting
Manifest for triaging tasks.

you can host it yourself.

**Comment by hackintoshrao** [comment]
Integration of govet, gofmt and other tool sets in Travis would solve the need too.

**Comment by manishrjain** [comment]
@sreeram-boyapati Would it be able to show errors from a customized `golint`? We want to do it so it can show the author and the reviewer these things if needed. So, the reviewer can decide which ones the author should fix, and which ones to ignore.

**Comment by sreeram-boyapati** [comment]
@manishrjain https://github.com/kalbasit/arcanist-go
https://secure.phabricator.com/T6867

We use arc as a command line tool to push commits. we can integrate go linters so the code pushed for review is written properly.
It has not yet been accepted into the main repo though.

**Comment by dan-compton** [comment]
Along the lines of what @hackintoshrao said: Seems natural to have this run by a build container (to eliminate inconsistency) and have every branch run tests -- not just master.  There's a wercker build-step much like what you describe: https://github.com/wercker/step-golint

I'm not a wercker expert, but it might be possible to have wercker publish a comment on the PR via webhook which contains the formatted output.  Although this seems redundant given that the test output will contain this information.

**Comment by manishrjain** [comment]
Reviewable is working out alright for us. We'll probably write a Github bot which can do some of the special things that we need done. Closing this issue.
