### ISSUE TITLE
Java Driver

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#98]
We want to build a very basic Java client driver similar to Go client we have right now. It would communicate with the server over gRPC and can run queries and mutations.

**Comment by bitmalloc** [comment]
I can take on this task

**Comment by manishrjain** [comment]
I can assign it to you once you approve the collaborator request.

**Comment by crackerplace** [comment]
If this is not done,I would want to do this.

**Comment by bitmalloc** [comment]
It's in progress and soon to be done.

**Comment by bitmalloc** [comment]
Done.
Implementation: https://github.com/dgraph-io/dgraph4j
Docs: https://wiki.dgraph.io/Clients#Java

**Comment by manishrjain** [comment]
Manish R Jain removed needed-by dependency to issue #1150 (posted by Codetree)
