### ISSUE TITLE
[browser] localStorage quota is reached

### ISSUE THREAD

**Issue by sungwoncho** [dgraph-io/dgraph#981]
Persisting to localStorage no longer works when the user has run a number of queries with large responses. (Chrome has [10MB limit](https://stackoverflow.com/questions/2989284/what-is-the-max-size-of-localstorage-values))

    Uncaught (in promise) DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'reduxPersist:frames' exceeded the quota.

Possible solutions

* Do not store the response in the `frame`. After this, we have two options:
  * Rather, run a new query every time a frame is expanded.
  * Disallow expanding a frame. Only action possible would be to load the query to the editor.
* Do not store the frames in the localStorage at all. Once we have the feature to store queries in dgraph as favorite, this might as well make sense.

@pawanrawal any ideas?

**Comment by manishrjain** [comment]
Do not store the responses. You can just re-run the queries.

**Comment by manishrjain** [comment]
Can we do this, if we haven't already?

**Comment by pawanrawal** [comment]
I think we don't need to store the response and can just rerun the queries when a frame is expanded. I will make this change.
