### ISSUE TITLE
cleanup: lexer - parser isolation

### ISSUE THREAD

**Issue by szymonm** [dgraph-io/dgraph#983]
Currently, our lexers are doing much more than just splitting input into tokens. This results in duplicated coded with parsers and mess in unit tests (usually lexers or not tested at all while parsers have complicated tests).

**Comment by manishrjain** [comment]
@pawanrawal made some changes recently. Pawan: Can you have a look and see if we need to do anything more there.

**Comment by pawanrawal** [comment]
We split tokens for arrays i.e. for `id: [ ]` and other places now. Closing this for now.
