### ISSUE TITLE
Bug in parser

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/dgraph#984]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab2f55]

goroutine 2540 [running]:
github.com/dgraph-io/dgraph/gql.godeep(0xc4201c5d58, 0xc420146c60, 0x0, 0x0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/gql/parser.go:2197 +0x265
github.com/dgraph-io/dgraph/gql.getQuery(0xc4201c5d58, 0xc42013a2d0, 0x1, 0x1)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/gql/parser.go:741 +0x664
github.com/dgraph-io/dgraph/gql.Parse(0xc421ef6a00, 0x1fd, 0xc4221cc330, 0x1, 0xc42146cad0, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/gql/parser.go:534 +0x9e7
main.parseQueryAndMutation.func1(0xc421956cc0, 0xc421ef6a00, 0x1fd, 0xc4221cc330, 0x1, 0xc421c3eae0)
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:450 +0x66
created by main.parseQueryAndMutation
	/home/travis/gopath/src/github.com/dgraph-io/dgraph/cmd/dgraph/main.go:452 +0x20c

**Comment by szymonm** [comment]
@manishrjain Do you have any information about dgraph version and query executed?
