### ISSUE TITLE
Specify name of reverse predicate?

### ISSUE THREAD

**Issue by dpeek** [dgraph-io/dgraph#986]
Would it be possible to specify the name for a reverse predicate when defining the schema?

```
mutation {
  schema {
    children: uid @reverse(parents) .
  }
}
```

**Comment by Rader** [comment]
@dpeek you can just use predicate `parents`, instead of define a reverse predicate.

**Comment by manishrjain** [comment]
@dpeek : It would add extra management complexity for us, and I'm not sure what the value of this change would be.
