### ISSUE TITLE
Allow creation of @reverse edges using reverse predicate

### ISSUE THREAD

**Issue by dpeek** [dgraph-io/dgraph#987]
Right now `@reverse` only when you create the non-reversed predicate, as shown here:

```
mutation {
  set {
    <person1> <name> "Jim" .
    <person2> <name> "Bob" .
    <person1> <children> <person2> .
    <person3> <name> "Joan" .
    <person4> <name> "Gladys" .
    <person3> <~children> <person4> .
  }
}
```

```
query {
  person1_children(id:<person1>) {
    name
    children {
      name
    }
  }
  person2_parents(id:<person2>) {
    name
    ~children {
      name
    }
  }
  person3_parents(id:<person3>) {
    name
    ~children {
      name
    }
  }
  person4_children(id:<person4>) {
    name
    children {
      name
    }
  }
}
```

Would it be possible to support creation in the other direction like this?

**Comment by manishrjain** [comment]
> Would it be possible to support creation in the other direction like this?

No. We automatically deal with generating reverses. You should only be creating edges in the forward direction. The above mutation can be easily rewritten as:

`<person4> <children> <person3> .`
