### ISSUE TITLE
Python Driver

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#99]
We want to build a very basic Python client driver similar to the Go client we have right now. It would communicate with the server over gRPC and can run queries and mutations.

**Comment by szymonm** [comment]
I'm on it

**Comment by mohitranka** [comment]
@szymonm Are you still working on it? If not, I can pick it up.

**Comment by szymonm** [comment]
Started, but I'm quite busy right now. Please give me just a few days until Sunday eod.

**Comment by szymonm** [comment]
Hej @mohitranka, I'm almost done. Let me finish this.

**Comment by mohitranka** [comment]
The driver is available at https://github.com/dgraph-io/pydgraph. Closing the issue.
