### ISSUE TITLE
Stop users from using reserved words as predicates

### ISSUE THREAD

**Issue by sungwoncho** [dgraph-io/dgraph#991]
Suppose a user runs the following mutation:

```
mutation {
  set {
    <tag1> <Count> "100" .
  }
}
```

The mutation runs. But now user cannot fetch `Count`, because when she runs the following:

```
{
  me(id: tag1) {
    Count
  }
}
```

she will get:

    Invalid mention of count.

Ideas:

1. Respond with error when a predicate in a mutation includes a reserved word.
2. Make the parser differentiate between predicate and operation. e.g. `count` and `count()` and return result as `_count_` if latter (like `_uid_`)

**Comment by ashwin95r** [comment]
Resolved in master.
