### ISSUE TITLE
Find language returned in language preference

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#994]
We can query for a language preference, e.g.

```
{
  q(func: allofterms(name, "Farhan Akhtar")) {
    name@hi:en

    director.film {
      name@ru:hi:en
    }
  }
}
```
But the result doesn't say which language was matched - the returned is `name@ru:hi:en` would be better as `name@ru` or `name@hi` depending on which was returned.

**Comment by calummoore** [comment]
That might violate the principle that the field name you request, is the field name you get back.

How do I know which property to look for when parsing the response? I'd have to check all of the different possible outcomes (`name@ru`, `name@hi`, etc).

Maybe it could return a lang type field (similar to how facets work)?

```
director.film {
  "@lang": {
    "name": "en"
  },
  "name@ru:hi:en": "John"
}
```
Or in the introspection type format?

```
director.film {
  "__lang": {
    "name": "en"
  },
  "name@ru:hi:en": "John"
}
```

**Comment by tzdybal** [comment]
After discussing the issue, we think that this improvement is not necessary. It's hard to think about real use cases when it's absolutely required.

If someone is interested in particular languages, querying for each language separately should be enough.

    director.film {
      "name@ru"
      "name@hi"
      "name@en"
    }

If kind of "default translation" is required, information about language is probably not important anyways.

Additionally we're implementing improvement to language lists, to clarify it's behaviour (see #1010).
